### ISSUE TITLE
position of back command wrong on first call to addCommand in SideMenuBar class

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1007]
Original [issue 1007](https://code.google.com/p/codenameone/issues/detail?id=1007) created by codenameone on 2013-12-21T20:29:38.000Z:

Occurs in simulator &amp; on devices

Forum thread https://groups.google.com/forum/#!topic/codenameone-discussions/2MrJyca1raU

I found the issue is here in the addCommand(Command, index) method in SideMenuBar.class

        if (getBackCommand() != null
                &amp;&amp; getCommandCount() &gt; 0
                &amp;&amp; !UIManager.getInstance().isThemeConstant(&quot;hideBackCommandBool&quot;, false)
                &amp;&amp; !getCommands().contains(getBackCommand())) {
            getCommands().insertElementAt(getBackCommand(), 0);
        }

The first time this is called the back command isn't in the commands list so it gets inserted at position 0 which is incorrect for the side menu since the commands are subsequently iterated in reverse order.

On subsequent calls to this method the back command is already in the commands list so it ends up at the end of the list and the order of commands displayed in the side menu is then correct.

Have worked around it for now by doing a dummy add/remove command sequence before adding the required commands.

Would suggest that the insertion of the back command be down at the end of the commands list.

**Comment by chen-fishbein** [comment]
fixed
