### ISSUE TITLE
MapComponent: Change Vector/Hashtable to ArrayList/HashMap

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1025]
Original [issue 1025](https://code.google.com/p/codenameone/issues/detail?id=1025) created by codenameone on 2014-01-10T19:13:03.000Z:

I'd like to change the internal use of Vectors and Hashtables in MapComponent to use ArrayLists and HashMaps for performance reasons.  Obviously I wouldn't change anything that affects the public API or inheritance  (i.e. I would change only private members and local variables).  Is this sort of change OK with you guys, or would you still prefer to keep the older thread-safe collections in the core classes?

**Comment by shannah** [comment]
No longer necessary with new vm
