### ISSUE TITLE
textfield contents sometimes not drawn on iOS

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1073]
Original [issue 1074](https://code.google.com/p/codenameone/issues/detail?id=1074) created by codenameone on 2014-03-05T12:52:04.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>
<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

<b>What steps will reproduce the problem?</b>
1. Create a simple form with textfields and a checkbox (screenshot attached)
2. in iOS app tap on a textfield to open the virtual keyboard, enter some text and tap on the checkbox

<b>What is the expected output? What do you see instead?</b>

The entered text should be shown in the textfield, but the textfield is empty and you can see field contents only after the field is repainted. Please note that the problem occurs only if the keyboard is dismissed by tapping on the CheckBox, clicking elsewhere is not causing the problem.

<b>What version of the product are you using? On what operating system?</b>

the latest build server build, iOS 7.0.6, tested on iPhone 4S and 5S. In some reason it is not reproducable on iOS simulator.

<b>Please provide any additional information below.</b>

The problem seams to come from this that textfield is not repainted so often as it used to be in older CN1 versions. I could fix the problem by adding repaint(); call to the beginning of com.codename1.uiTextField method fireDataChanged:

public void fireDataChanged(int type, int index) {
		repaint();
.....

**Comment by shannah** [comment]
Cannot reproduce.  This is the test code I'm using.  Tried with ios.keyboardOpen=false

~~~~
package com.codename1.issue1156;

import com.codename1.io.ConnectionRequest;
import java.io.IOException;

import com.codename1.ui.CheckBox;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.TextField;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

public class Issue1073Test {

    private Form current;

    public void init(Object context) {
        try {
            final Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch (final IOException e) {
            e.printStackTrace();
        }
    }

    ConnectionRequest conn;
    int threadNum = 0;
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Transparents");
        
        TextField tf = new TextField();
        TextField tf2 = new TextField();
        CheckBox cb = new CheckBox("Checkbox");
        
        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        hi.addComponent(tf);
        hi.addComponent(tf2);
        hi.addComponent(cb);
        
        hi.show();
        
        
       
    }

    

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

  
}

~~~~
