### ISSUE TITLE
virtual keyboard might scroll content behind statusbar on iOS7

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1074]
Original [issue 1075](https://code.google.com/p/codenameone/issues/detail?id=1075) created by codenameone on 2014-03-05T15:20:02.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>
<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

<b>What steps will reproduce the problem?</b>
1. Create a form with textfields on the bottom of the screen (keyboard_closed.png)
2. Edit one of the bottom textfields in iOS7 device. This scrolls the content view so that the edited textfield would not be behind the virtual keyboard (keyboard_open.png)

<b>What is the expected output? What do you see instead?</b>

The look is a bit ugly. Due to transparent statusbar on iOS7 it might get mixed with form content.

<b>What version of the product are you using? On what operating system?</b>

the latest CN1 buildserver, iOS7

<b>Please provide any additional information below.</b>

I din't managed to find an easy solution for the problem. One option is to add for keyboard showing time a panel behind the status bar. It could be done by adding an UIVIew to CodenameOne_GLViewController'r view in keyboardWillShow method end like it shown in the following code example. But the solution leaves some open questions as described in the code comments.

if(isIOS7()) {
    UIView *addStatusBar = [[UIView alloc] init];
    //todo: the addStatusBar should be later also released (probably in keyboardWillHide)
    addStatusBar.frame = CGRectMake(0, 0, MAX(self.view.frame.size.width, self.view.frame.size.height), 20);
    addStatusBar.backgroundColor = [UIColor colorWithRed:1 green:0 blue:0 alpha:1]; 
    //todo: actually the background might also be an image, this makes life quite unconvinient
    [self.view addSubview:addStatusBar];
    
    CGRect statusbarFrame = CGRectMake(-viewFrame.origin.x, -viewFrame.origin.y, 
                 addStatusBar.frame.size.width, addStatusBar.frame.size.height);
}
    
    
    [UIView beginAnimations:nil context:NULL];
    [UIView setAnimationBeginsFromCurrentState:YES];
    [UIView setAnimationDuration:0.3];
    [self.view setFrame:viewFrame];

    if(isIOS7()) {
        [addStatusBar setFrame: statusbarFrame];
    }
.....

**Comment by codenameone** [comment]
This should be fixed by now.

**Comment by jaanushansen** [comment]
Hi!

Could you please explain a bit how was it fixed? A simple test did show the same picture as in the original issue.

https://code.google.com/p/codenameone/issues/detail?id=1075

**Comment by codenameone** [comment]
We made a lot of changes to the VKB and fixed many issues, I assumed this was one of those. Reopening and assigning.

**Comment by shannah** [comment]
I modified it so that the status bar will be hidden in this case.  Not a perfect solution, but it is better than the previous situation.
