### ISSUE TITLE
CommonTransitions.createFade() does not properly support containers.

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1094]
Original [issue 1095](https://code.google.com/p/codenameone/issues/detail?id=1095) created by codenameone on 2014-04-03T11:59:27.000Z:

The &quot;current&quot; and &quot;next&quot; components appear to not be properly laid out during the fade transition, making this transition useless for containers holding other components.

<b>What steps will reproduce the problem?</b>
1. Create Form with a Container containing a Label(&quot;Source text&quot;).
2. Perform a replaceAndWait with a CommonTransitions.createFade(500) to another Container containing a Label(&quot;Destination text&quot;);
3. Run this code.

<b>What is the expected output? What do you see instead?</b>
Expected the text in the source container to fade into the destination container text. Instead, the labels inside the containers appear to loose (part of?) their theme settings during the transition. When performing the same transition with a CommonTransitions.createCover(...), this does not happen.

<b>What version of the product are you using? On what operating system?</b>
Today's project libraries. (Checked for an update to be sure.)

<b>Please provide any additional information below.</b>
(None)

**Comment by chen-fishbein** [comment]
works fine, I'm closing this
