### ISSUE TITLE
Container.replace() with null transition does not update x, y, width and height of next component.

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1095]
Original [issue 1096](https://code.google.com/p/codenameone/issues/detail?id=1096) created by codenameone on 2014-04-03T12:08:31.000Z:

A replace() with a null transition leaves the next component not properly initialized.

<b>What steps will reproduce the problem?</b>
1. Create a Container with two Labels in a BoxY layout.
2. Layout the Container.
2. Replace the second Label with a third Label.
3. Check the x, y, width and heigh of the third Label.

<b>What is the expected output? What do you see instead?</b>
Expected the third Label to have proper coordinates. Instead x,y,width and height are zero. This causes a problem if the next action on the third Label is e.g. an animation.

<b>What version of the product are you using? On what operating system?</b>
Today's version.

<b>Please provide any additional information below.</b>
The documentation of CommonTransitions.createEmpty() states it is the equivalent of replace() with a null parameter. This is not true, if the above is &quot;as designed&quot;.

**Comment by codenameone** [comment]
I think this is a dupe of 1094.

**Comment by chen-fishbein** [comment]
fixed, thanks
