### ISSUE TITLE
Slider not showing in simulator iOs skins

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1160]
Original [issue 1161](https://code.google.com/p/codenameone/issues/detail?id=1161) created by codenameone on 2014-07-30T14:31:42.000Z:

The slider is not showing in the simulator on iOs skins. Other skins are showing the slider.

<b>What steps will reproduce the problem?</b>
1. Add a slider to the main form
2. Run in simulator in an iOs skin

<b>What is the expected output? What do you see instead?</b>

The expected output is a slider on the screen. I see nothing. When I set 'setRenderValueOnTop' to true and I slide to left and right on the place the slider should be, I can see the number going up and down. So there is a slider, but it's not visible.

<b>What version of the product are you using? On what operating system?</b>

Netbeans 8, Java 1.8, Linux, CodenameOne plugin: latest (I can't find the version in Netbeans, last check was today and there is no newer version).

<b>Please provide any additional information below.</b>

In all other platforms (simulated), there is a slider showing. I didn't test on real devices.

**Comment by sidiabale** [comment]
Same issue here. Seems like it only happens with the ~_OS7. For example, the slider is visible in iphone4.skin but not in iphone4_OS7.skin
