### ISSUE TITLE
URI scheme and AppArg on Android

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1168]
Original [issue 1169](https://code.google.com/p/codenameone/issues/detail?id=1169) created by codenameone on 2014-08-18T11:49:39.000Z:

<b>What steps will reproduce the problem?</b>
1. build and deploy AppArgBug CN1 application (sources attached) on an Android device
2. open the application - there is a label with AppArg text - will be NULL_VALUE, because the application was not opened by URI scheme
3. open a web page (in firefox, because the newest chrome does not call URI scheme, but the exact application)
http://android.alucid.eu/help/q.html and click the PEIG - TEST link -&gt; this will open the AppArgBug application with the AppArg property value in label or only white page - if the first one, continue with 4
4. Minimize the AppArg application with home button (not the back button)
5. Open the AppArg application again from menu

<b>What is the expected output? What do you see instead?</b>
The screen is either all white, or only Title area is rendered and the rest is all black.

The following second scenario:
6. Check the logs

<b>What is the expected output? What do you see instead?</b>

The AppArg property should be null (because it was not started by URI scheme), but it has still the first value - it is not made null never - even when the Display.getInstance.setProperty(&quot;AppArg&quot;, null) is called anywhere

<b>What version of the product are you using? On what operating system?</b>
Tested on two devices - Tablet with Android 4.0.4 and a phone with Android 4.1.1 the behaviour was the same.

<b>Please provide any additional information below.</b>
The URI scheme is alucid://callback - it is registered in codenameone_settings.xml
There are two fundamental problems:
1) The AppArg property is sometimes not set and if so it is never nulled then.
2) The application form is not rendered when the application is resumed after it was first opened by URI scheme.

**Comment by codenameone** [comment]
I think this was fixed already?

**Comment by chen-fishbein** [comment]
yes, this is fixed already
