### ISSUE TITLE
Enum not supporting valueOf

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1187]
Original [issue 1188](https://code.google.com/p/codenameone/issues/detail?id=1188) created by codenameone on 2014-09-22T11:13:10.000Z:

Apparently the C1 implementation of the Enum class does not support the valueOf method.

**Comment by ddyer0** [comment]
I independently encountered this defect.  A single file test program is attached.
[Dtest.zip](https://github.com/codenameone/CodenameOne/files/146879/Dtest.zip)

**Comment by codenameone** [comment]
This was fixed a while back
