### ISSUE TITLE
Limiting iOS minimum version

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1198]
Original [issue 1199](https://code.google.com/p/codenameone/issues/detail?id=1199) created by codenameone on 2014-09-30T12:51:12.000Z:

Hey guys,

this is a feature request to expose the ablity to limit iOS app versions to a minimum operating system version, this could probably be exposed through a build argument.

This could be very useful to prevent users with very old hardware still lying around, getting app crashes or strange behaviour and giving bad reviews on the store.

Thanks.

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now

**Comment by codenameone** [comment]
@shannah can we add a build hint to set the `MinimumOSVersion` flag in the plist?

**Comment by shannah** [comment]
@codenameone Is this different than just setting the deployment target?

http://stackoverflow.com/questions/29736871/setting-the-minimum-ios-version-in-xcode

E.g. We can set the target platform using `ios.pods.platform=8.0`.  Is this sufficient?

**Comment by codenameone** [comment]
The use case is to prevent install on older versions will that work for this use case?
What if pods aren't used?

**Comment by shannah** [comment]
I believe that should work.  Pods are always used in the new build servers.  This was the easiest way to make project compatible with new toolchain.

**Comment by codenameone** [comment]
@shannah pods.platform seems to be an undocumented build hint in the build hints section

**Comment by shannah** [comment]
Looks like you're right.  It is mentioned [in the cocoapods blog post](https://www.codenameone.com/blog/cocoapods.html), but not [in advanced topics](https://www.codenameone.com/manual/advanced-topics.html).

I'll add it.
