### ISSUE TITLE
Remove the auto complete popup with suggestions when one opens the sidebarmenu

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1202]
Original [issue 1203](https://code.google.com/p/codenameone/issues/detail?id=1203) created by codenameone on 2014-10-02T13:35:02.000Z:

<b>What steps will reproduce the problem?</b>
1. I'm using the Autocomplete Textfield. When the suggestions are displayed and I click on the hamburger sidebarmenu, the autocomplete suggestion box is not removed.

<b>What is the expected output? What do you see instead?</b>

it should be removed automatically, otherwise it keeps on lingering around.

<b>Please provide any additional information below.</b>

**Comment by codenameone** [comment]
Chen, was this fixed?

**Comment by chen-fishbein** [comment]
yes
