### ISSUE TITLE
Apple Maps app doesn't start with navigation

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1213]
Original [issue 1214](https://code.google.com/p/codenameone/issues/detail?id=1214) created by codenameone on 2014-10-17T08:53:03.000Z:

Hi there guys,
On iOS 8 (iPad 2 and iPad Mini) launching the native maps app won't directly start a navigation to the given coordinates.
I'm using the following code:
     double lat = 48.774111;
     double lng = 9.156070;
     Display.getInstance().openNativeNavigationApp(lat, lng);

Under android the maps app will correctly open and start the navigation but iOS 8 won't do it.

<b>What steps will reproduce the problem?</b>
1.use the code above
2.build app
3.try on iOS8

<b>What is the expected output? What do you see instead?</b>
Expected: opening maps app and start navigation
result: nothing but opened maps app

<b>What version of the product are you using? On what operating system?</b>
iPad mini newest generation and iPad 2 both on iOS 8.0.2

**Comment by shannah** [comment]
This appears to have been fixed.  It is working for me on my iPhone 6S (10.0.1).  Looking at the code, it it now uses `"http://maps.apple.com/?daddr=" + latitude+ "," + longitude;` if that is supported.
