### ISSUE TITLE
RFE: Arc/Elliptical shapes support

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1234]
Original [issue 1235](https://code.google.com/p/codenameone/issues/detail?id=1235) created by codenameone on 2014-12-01T17:42:21.000Z:

Reason: CN1 recommendation is to avoid using Graphics.drawArc and fillArc since it is specially problematic in iOS and that Shapes should be used instead. The problem is that there is no proper replacement for this, GeneralPath as it is cannot draw an acceptable elliptical arc.

The Arc2D Shape would be enough for my use case, even better would be the ExtendedGeneralPath from Apache Batik that could be used as a base to the existing GeneralPath.

**Comment by codenameone** [comment]
I think this was already fixed in GIT, Steve?

**Comment by shannah** [comment]
Yes.  This was added here
https://github.com/codenameone/CodenameOne/commit/53d873c1e064a9f4146aec738a66c2f652018bdb#diff-1ca20ffd2d1a4ae7fd5c69f7ea97fe03
