### ISSUE TITLE
 IOS - Facebook login work every only every other attempt

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1287]
Original [issue 1288](https://code.google.com/p/codenameone/issues/detail?id=1288) created by codenameone on 2015-01-15T08:41:17.000Z:

It seems that consecutive Facebook login work every only every other attempt.
- if the user signs in with Facebook from the first screen everything works fine: he is redirected to the main screen of the app and in the My Account section from the menu he can see his Facebook credentials (user name and profile picture) and the log out button.
- the user can choose to log out from Facebook by clicking the &quot;Log out&quot; button. Once this happens, the view is refreshed and the &quot;sign in with Facebook&quot; button is shown instead of the &quot;Log out&quot; button. If he chooses to log in again with Facebook, the log in fails. I can't see any error messages. The user is just left in the same screen. Only, when he clicks &quot;sign in with Facebook&quot; button for the third time he is actually logged in and the screen is refreshed showing him the Facebook credentials.

This behavior is repetitive, meaning the log in always works the first time, the third time, the fifth time etc but it always fails the second time, the fourth time, the sixth time etc.

Facebook log in is done like this:

FacebookConnect connect = FacebookConnect.getInstance();

if (connect.isFacebookSDKSupported()) {
connect.setCallback(new LoginCallback() {

@Override
public void loginFailed(String errorMessage) {
Log.p(&quot;Login failed: &quot; + errorMessage);

}

@Override
public void loginSuccessful() {
Log.p(&quot;Success&quot;);
}
});
connect.login();

Please note that when the login fails the error message from loginFailed() is blank.

This problem only appears on IOS. On Android the same code works as expected.

Tested on iPad Air with IOS version 8.0.2.

**Comment by shannah** [comment]
I'm working with the FacebookDemo and I can't even get logout to work at all.  It seems that app keeps everything cached.

Can someone provide a test case for this?

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now
