### ISSUE TITLE
ios app hangs when AutoCompleteTextField is in scrollable container

### ISSUE THREAD

**Issue by ghost** [codenameone/CodenameOne#1294]
Original [issue 1295](https://code.google.com/p/codenameone/issues/detail?id=1295) created by codenameone on 2015-01-18T14:05:36.000Z:

<b>What steps will reproduce the problem?</b>
1. Paste the following code in the start() of a new HelloWorld codenameone project:

```
    if(current != null)
    {
        current.show();
        return;
    }  

    Form hi = new Form();
    hi.setLayout(new BorderLayout());
    Container c = new Container(new FlowLayout());
    c.setScrollable(true);

    String[] s = {&quot;Java&quot;, &quot;CN1&quot;, &quot;Codename One&quot;, &quot;Form&quot;, &quot;Container&quot;, &quot;Theme&quot;, &quot;BorderLayout&quot;, &quot;FlowLayout&quot;};
    AutoCompleteTextField af = new AutoCompleteTextField(s);
    c.addComponent(af);

    hi.addComponent(BorderLayout.CENTER, c);
    hi.show();
```
1. Make a build for ios and install/run the program. Add random characters to the autocompletetextfield. Also, use the 'backspace' button. You can see the cursor is at the start of the textfield and it's 'blinking'.
2. The app will hang after some time.

<b>What is the expected output? What do you see instead?</b>
Expected output is a smooth textfield.

<b>What version of the product are you using? On what operating system?</b>
iOS 7. On Android, this is working well, as well as in the simulator.

<b>Please provide any additional information below.</b>
The hanging app is caused by a scrollable container. When the AutoCompleteTextField is not in a scrollable container, everything is OK. On Android, this is working OK, but on iOS (ios 7, didn't test on another version), it's not. This is seen on the new VM as well on the old VM.
When typing a word that's already in the list, the autocompletetextfield is working OK. 
When using a model instead of an Array, the same problem occurs.

**Comment by maaikez** [comment]
I finally had time to go on with the app development. I hoped everything was ok now, but the app still hangs with above code :(.
