### ISSUE TITLE
On DateTimeSinner can localize only the month, not the day.

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1295]
Original [issue 1296](https://code.google.com/p/codenameone/issues/detail?id=1296) created by codenameone on 2015-01-18T21:19:32.000Z:

<b>What steps will reproduce the problem?</b>
1. set some values in the form of &quot;Calendar.Month&quot;(short form ex: Jan) and &quot;Calendar.Day&quot;(both forms: Sun and Sunday)
2. set the bundle to a language
3. show a DateTimeSpinner

<b>What is the expected output? What do you see instead?</b>
localized month and day
only month is changed

<b>What version of the product are you using? On what operating system?</b>
last on Android 2.3, iOS 6.1 and the simulator

**Comment by chen-fishbein** [comment]
fixed
