### ISSUE TITLE
Graphics performance on NewVM laggy.

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1326]
Original [issue 1327](https://code.google.com/p/codenameone/issues/detail?id=1327) created by codenameone on 2015-01-31T01:57:36.000Z:

Responsiveness on new vm is noticeably slower than on the old vm.  I will post a simple sample app to demonstrate - right now I'm using some real-world apps and noticing this.

Steps:

1. A list with a custom renderer (just an image and text) with enough items to scroll ( at least 20 or so).
2. Scroll list up and down with index finger at varying speeds.

In old VM the list scroll is quite responsive, staying with the finger.
On new VM the list scroll is laggy, often times a full up-down movement behind.

This issue should lead to two activities:

1.  Work on improving graphics pipeline efficiency.
2. Work on improving performance of VM in general.

**Comment by shannah** [comment]
Performance is much improved since this was originally opened.  There are still things that can be done to improve UI performance, but that is unrelated to the NewVM.
