### ISSUE TITLE
Improve the performance of UTF-8 decoding/encoding which is a major bottlneck

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1340]
Original [issue 1341](https://code.google.com/p/codenameone/issues/detail?id=1341) created by codenameone on 2015-02-08T14:13:47.000Z:

This seems to be the main reason some test cases perform worse on the new VM e.g. Issue 1304. 
This just means not reaching the Objective-C character decoding logic and ideally doing everything in C e.g. like this: http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
The relevant code is in java_lang_String_bytesToChars___byte_1ARRAY_int_int_java_lang_String_R_char_1ARRAY in the UTF-8 portion. It should be optimized like the US-ASCII code path.

**Comment by shannah** [comment]
I'm not sure this is as big a bottleneck as we think.  The test in Issue 1372 uses Strings heavily and profiling showed that this method wasn't a major contributor to slow-downs.  (If we could get this method down to zero, it would have represented less than a 10% performance improvement).

**Comment by codenameone** [comment]
I'm assuming the method didn't use UTF-8 and only used ASCII strings (which are UTF-8 compatible). 
I have special case code that makes it VERY fast for ASCII (or UTF-8 that includes only ASCII characters) which is why you don't see the overhead. However, if you write text processing code that processes foreign text you will instantly see the overhead.

**Comment by shannah** [comment]
Do you have any unit tests or test cases that rely on this so that I can observe the current performance, and test any changes to be sure that I don't introduce regressions?  If not, I guess I can put together some tests myself... it will just take more time.

**Comment by codenameone** [comment]
Its not an urgent issue. Don't waste your time on this right now.
The main idea is avoiding NSString which is expensive.

**Comment by shannah** [comment]
This is now marked for 3.8.  I'm starting to look at 3.8 issues oldest to newest so this is "high" in my queue.  If you have any test code that demonstrates the performance problem, it would make it easier to start to tackle this.

**Comment by codenameone** [comment]
This isn't high priority but it should probably be fixed. Right now the UTF code has a special optimization for ASCII code that makes it effectively very fast. See nativeMethods.m line 196.

Unfortunately the fallback uses `NSString` instead of fast C code. This means that if a String has non-USASCII codes  it will perform significantly slower.

This is pretty deep in so I doubt it would show in benchmarks as it's so low level and would only happen for foreign language apps.
