### ISSUE TITLE
Dodgy tensile scrolling

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1365]
Original [issue 1366](https://code.google.com/p/codenameone/issues/detail?id=1366) created by codenameone on 2015-02-20T11:07:48.000Z:

Dragging a list or any scrollable component beyond its limits causes tensile scrolling under IOS. I noticed that once on taps while the tensile scrolling is still in progress it just stops.
This can be reproduced at least under IOS on a real device.

**Comment by saeder** [comment]
This has't been fixed yet.
Still having a list which is smaller than the form., scrolling it beyond start and tapping the list ends up at the end of the form.

![whqri](https://cloud.githubusercontent.com/assets/9945131/14420347/e6f2c922-ffcb-11e5-9040-0aed0aa10fba.jpg)

**Comment by saeder** [comment]
The same with an InfiniteScrollAdapter

![codenameone screenshot 1](https://cloud.githubusercontent.com/assets/9945131/14452295/0a7e543e-008e-11e6-8324-807aef9af8a9.png)

**Comment by codenameone** [comment]
Duplicate of #1735
