### ISSUE TITLE
Keyboard showing scrolls incorrectly in landscape orientation, when landscape is not supported (ios.keyboardOpen=false)

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1377]
Original [issue 1378](https://code.google.com/p/codenameone/issues/detail?id=1378) created by codenameone on 2015-02-27T09:21:50.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>
<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

The problem happens on iOS when iPhone is in landscape mode, but app supports only portrait mode. And build argument ios.keyboardOpen=false

<b>What steps will reproduce the problem?</b>
1. Rotate your phone to landscape mode
2. Tap on a lower textfield, which editing needs screen scrolling 

<b>What is the expected output? What do you see instead?</b>

The view should scroll to show the edited field, but it scrolls in opposite direction and the field is not visible at all (see attached screenshot).

<b>What version of the product are you using? On what operating system?</b>

the latest build server

<b>Please provide any additional information below.</b>

I don't have a clean solution for the problem, but when only iPad supports landscape, then the problem can be solved by modifying CodenameOne_GLViewController.m's method shouldAutorotate beginning to like this:

- (BOOL)shouldAutorotate {
    UIInterfaceOrientation interfaceOrientation = [[UIDevice currentDevice] orientation];
    upsideDownMultiplier = 1;
    

    if (!isIPad()) {
        //extra: if not iPad, then do not change upsideDownMultiplier 
        return NO;
    }

PS. There is also another related problem on the new iOS VM - build argument ios.interface_orientation=UIInterfaceOrientationPortrait has no effect, so I had set the only supported device orientation to Portrait in XCode.

**Comment by shannah** [comment]
This was *very* painful, but I think I got it figured out with this change.  Test case I used was:

~~~~
package com.codename1.issue1156;

import java.io.IOException;

import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

public class Issue1378Test {

    private Form current;

    public void init(Object context) {
        try {
            final Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch (final IOException e) {
            e.printStackTrace();
        }
    }

    private boolean loadingFormFirstTime = true;
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        

        final Form startForm = new Form("Issue 1450");
        startForm.setLayout(new BorderLayout());
        TextField f = new TextField();
        startForm.addComponent(BorderLayout.SOUTH, f);
        
        startForm.show();
    
       
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

}
~~~~

Tested on iOS 7.1 simulator (iPhone 4S) and iOS 8.2 iPhone 4S physical device.
