### ISSUE TITLE
com.codename1.ui.Container.Anim.animate() throwing java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1378]
Original [issue 1379](https://code.google.com/p/codenameone/issues/detail?id=1379) created by codenameone on 2015-02-27T12:21:53.000Z:

com.codename1.ui.Container.Anim.animate() throws an java.lang.ArrayIndexOutOfBoundsException when a component is added to the animated Container whilst an animation is already registered.
The XXX is thrown when it accesses the motions array for a component which did not yet exist when the animation was registered. 

it does this continuously because the animation never finishes because of the exception. 

I suggest that the animate() method should be wrapped in a try-catch block and that the animation is cancelled in case of an exception.

I also suggest that the animate() method only iterates over as many entries as the motions array contains - use motions.length instead of componentCount. Either this or - another solution was to integrate the new component(s) in the animation by extending the animations arrays.

**Comment by chen-fishbein** [comment]
fixed, thanks
