### ISSUE TITLE
Android intent filter for MIME type/file extension - AppArg always empty on cold start

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1380]
Original [issue 1381](https://code.google.com/p/codenameone/issues/detail?id=1381) created by codenameone on 2015-03-01T13:04:54.000Z:

With android.xintent_filter =
&lt;intent-filter&gt;                      
    &lt;action android:name=&quot;android.intent.action.VIEW&quot; /&gt;
    &lt;category android:name=&quot;android.intent.category.DEFAULT&quot; /&gt;                      
    &lt;data android:mimeType=&quot;application/myfile&quot; /&gt;
    &lt;data android:host=&quot;*&quot; /&gt;
    &lt;data android:pathPattern=&quot;.*\\.myfile&quot; /&gt;
&lt;/intent-filter&gt;

on Android and opening a file attached to an email with a MIME type of &quot;application/myfile&quot; and the app not running the start() method is called and Display.getInstance().getProperty(&quot;AppArg&quot;, null) delivers nothing.
That is just with a cold start. If the app is running Display.getInstance().getProperty(&quot;AppArg&quot;, null) delivers a file path.

**Comment by chen-fishbein** [comment]
works fine for me.

**Comment by saeder** [comment]
I tested it again. It has changed. Now it works only on cold start and never when the app is still running. This was tested with Android 4.4.4 on a Cubot X9

**Comment by chen-fishbein** [comment]
Can you please post your test code? and how to reproduce this?

**Comment by igo211** [comment]
I can confirm as well - 

As far as I can tell,  AppArg is not getting set at all now (for both launching - aka "cold starts" and also in the case where the app was already running) on both iOS and Android.  

We have app code that follows this: http://www.codenameone.com/blog/intercepting-urls-on-ios-android.html.  This used to work for us, but one of our users recently pointed out that it no longer fully works - our app launches or comes to the foreground in response to the custom URL (aka deep link), but the AppArg value is empty in both cases.

**Comment by igo211** [comment]
Please disregard last comment... the issue with our app is different from the setting of the AppArg value (i.e. it does appear to be getting set for us after all).
