### ISSUE TITLE
Incorrect splash flash for iPad in landscape with the new iOS vm

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1381]
Original [issue 1382](https://code.google.com/p/codenameone/issues/detail?id=1382) created by codenameone on 2015-03-02T13:42:56.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>
<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

The problem occurs on on iPad with the new iOS vm

<b>What steps will reproduce the problem?</b>
1. Open app in landscape orientation

<b>What is the expected output? What do you see instead?</b>

For a moment the splash drawn in awakeFromNib is incorrect, a log statement

NSLog(@&quot;Drew image on %i, %i for display %i, %i&quot;, imgHeight, imgWidth, wi, he);

in CodenameOne_GLViewController.m prints like this:

Drew image on 768, 768 for display 1024, 768

(that is for splash is used a square image and right side of the screen is black as seen in attached screenshot)

<b>What version of the product are you using? On what operating system?</b>

the latest buildserver with ios.newVM=true, tested with iOS 8 simulator an on iPad 2

<b>Please provide any additional information below.</b>

It would be nice to remove the mentioned log statement once the problem is fixed.

**Comment by jaanushansen** [comment]
I needed this fixed ASAP, so I made the following code change:

in Ports/iOSPort/nativeSources/CodenameOne_GLViewController.m replaced lines 1537 - 1544 with the following code:

    CGImageRef imageRef;
    BOOL ios8 = isIOS8();
    if (ios8) {
        imageRef = CGImageCreateWithImageInRect([img CGImage], CGRectMake(0, statusbarHeight * scale, wi, he));
    } else {
         imageRef = CGImageCreateWithImageInRect([img CGImage], CGRectMake(0, statusbarHeight * scale, he, wi));
    }
    img = [UIImage imageWithCGImage:imageRef];
    CGImageRelease(imageRef);
            
    gl = [[GLUIImage alloc] initWithImage:img];
    int imgHeight = img.size.height;
    int imgWidth = img.size.width;
    if (ios8) {
        dr = [[DrawImage alloc] initWithArgs:255 xpos:0 ypos:0 i:gl w:imgWidth h:imgHeight];
    } else {
        dr = [[DrawImage alloc] initWithArgs:255 xpos:0 ypos:0 i:gl w:imgHeight h:imgWidth];
    }

It's a bit hacky, but at least it removes the ugly black rectangle on iOS 8.
