### ISSUE TITLE
Tensile Drag - in X+Y direction

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1403]
Original [issue 1404](https://code.google.com/p/codenameone/issues/detail?id=1404) created by codenameone on 2015-03-18T05:49:33.000Z:

When a component that can scroll in both the X + Y directions has tensile drag enabled.  

If the component is pulled so it is experiencing tensile drag in both directions, when you let go it only snaps back in only one of the directions.

**Comment by chen-fishbein** [comment]
fixed
