### ISSUE TITLE
Version numbering on iOS forces review on Testflight.

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1405]
Original [issue 1406](https://code.google.com/p/codenameone/issues/detail?id=1406) created by codenameone on 2015-03-18T22:24:44.000Z:
## 
## Apologies if the terminology is incorrect.  I'm talking about the (app) version number styled as 1.60 for example and the bundle version number styled as 160

Due to the new testing system from Apple builds need to be reviewed if the version number changes, but not if only the bundle version number changes.  But also its not possible to upload two builds with the same bundle version number.

Codenameone's management of version numbers means that new builds are flagged as new versions and need to go through review, which means its 48 hours or so before customers can get hold of updates for testing.  If there was an option in CN1 that allowed setting the bundle version number independently of the application version then it would be possible to update testflight builds without review and get them out faster.

**Comment by vitormss** [comment]
I've uploaded in iTunes Connect a new release and returned "Invalid team id in signature".
I’ve corrected the issues with signature in my App, but i can’t upload since the wrong one still is in iTunes Store and the error message of Application Loader is: “ERROR ITMS-4238: "Redundant Binary Upload. Apple support said "To resolve this issue, please try increasing the build number- if you are currently trying to upload version 1.1 build 1.0, please renumber the binary as V1.1 build 2.0.". How can i resolve this once with codenameone we can't have 1.1.x build number?

**Comment by codenameone** [comment]
Unfortunately I don't recall the relevant link to the version number documentation here and since the original issue didn't link to the discussion group thread I have no recollection of this.

**Comment by DigNZ** [comment]
In xcode there is a version number and a Build number.  We need a way to change the build number without changing the version number.  

Changing the version number requires a review for testflight builds.  Once a version is reviewed new builds can be uploaded and distributed without review as long as they have the same version number and different build numbers.

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/BetaTestingTheApp.html

**Comment by codenameone** [comment]
I can't see any specific version number related to that.
I added a build hint called ios.minorVersionNumber which you can set to any number and it will map to version.minorversion etc. version == 2.3 and minor version == 4 will result in app version 2.3.4.

This will be in the next server update.

**Comment by DigNZ** [comment]
This isn't going to fix the issue.  We need to be able to submit builds to Apple with exactly the same version number but a different build number.  

See this image here.  We need to be able to control the version number and build number independently.
![image](https://cloud.githubusercontent.com/assets/817657/7109357/61c8c3a4-e1f0-11e4-80f4-5f75a4c82706.png)

Currently they are linked and if we change the version number then apple requires a review for testflight.  If we can keep the version number the same and increment the build number then it doesn't need to be reviewed and we can get it to testers much faster.

At the moment we need to include sources, open it in xcode, change the build number, recompile and submit to apple.  Having a build hint that sets the build number would mean that the build from the build server was suitable to send to test flight straight away.

**Comment by codenameone** [comment]
I see. I removed that patch and added ios.bundleVersion=versionNumber instead.
Its a bit of a complex patch so I'm not sure it will work.

**Comment by DigNZ** [comment]
I'm not sure if this has been patched on the build server but it doesn't seem to be working.  

I'm not sure why its complex, in the Info.plist we just want to be able to set CFBundleShortVersionString and CFBundleVersion to separate values.  The first to the version in the main codename one properties panel as it currently is, and the second to the value of ios.bundleVersion build hint, if there is no ios.bundleVersion build hint then they can be the same value as they currently are...

**Comment by kutoman** [comment]
it's an old issue but still valid in my opinion

**Comment by codenameone** [comment]
The last comment from Nick was missed probably due to the github migration or something. It's hard to recall from 2015
