### ISSUE TITLE
getProducts never returns when no internet connection

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1408]
Original [issue 1409](https://code.google.com/p/codenameone/issues/detail?id=1409) created by codenameone on 2015-03-23T18:05:45.000Z:

I encountered the problem that getProducts never returns when there is no internet connection

<b>What steps will reproduce the problem?</b>
1. set device info flight mode
2. start app and call getProducts to get product infos like localized description and price
3. wait for the response of getProducts

<b>What is the expected output? What do you see instead?</b>
I would expect to get a null or empty response or some exception.
But none of these happen. The method never returns anything.

<b>What version of the product are you using? On what operating system?</b>
libVersion=84
iOS 8.1.3 on iPhone 5

<b>Please provide any additional information below.</b>
When there *is* an internet connection, getProducts works fine.

**Comment by t-arn** [comment]
I have tested the fix on my iPhone and it still does not work.
Purchase.getProducts still never returns when there is no internet connection.

**Comment by t-arn** [comment]
It now works fine.
When there is no internet connection, I get an Exception:
java.io.IOException - Failed to fetch products: The operation couldn't complete.

Thanks!
Tom
