### ISSUE TITLE
wasPurchased always returns false

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1409]
Original [issue 1410](https://code.google.com/p/codenameone/issues/detail?id=1410) created by codenameone on 2015-03-23T18:14:51.000Z:

I encountered the problem that wasPurchased always returns false, even for (managed) products that I have successfully bought.

<b>What steps will reproduce the problem?</b>
1. create a managed non-consumable in-app product
2. buy the product
3. call wasPurchased to find out whether you bought the product

<b>What is the expected output? What do you see instead?</b>
I would expect the method to return true for bought products.
But I always get false, also for successfully bought products.

<b>What version of the product are you using? On what operating system?</b>
libVersion=84
iOS 8.1.3 on iPhone 5

<b>Please provide any additional information below.</b>
When I try to buy an already bought product, I get the message that I have already bought it and if I want to restore it for free. But still, wasPurchased returns false for this product

**Comment by t-arn** [comment]
I have tested the fix on my iPhone and now, Purchase.wasPurchased works fine.
Also, Purchase.restore now works again.

Many thanks for the fast fix!

I have one suggestion:
It seems that Purchase.wasPurchased only returns true if the product has been bought on the very device or if Purchase.restore was called. So, Purchase.wasPurchased does not get the info directly from the store but rather when PurchaseCallback.itemPurchased or RestoreCallback.itemRestored is called.
Maybe, this could be documented in the JavaDoc ?

**Comment by shannah** [comment]
Reopening this issue for purpose of adding javadoc to describe how wasPurchased works.
