### ISSUE TITLE
iOS: Animations still running while app is background

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1410]
Original [issue 1411](https://code.google.com/p/codenameone/issues/detail?id=1411) created by codenameone on 2015-03-24T07:42:22.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>
<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

the problems is on iOS.

<b>What steps will reproduce the problem?</b>
1. I created a plain project with a form with a Timeline image.
2. Run in on iOS simulator and locked the device. 

<b>What is the expected output? What do you see instead?</b>

Animations should stop while app is in background, but debugging shows, that com_codename1_ui_Form_repaintAnimations was still called and also CPU activity was something like 2%

<b>What version of the product are you using? On what operating system?</b>

The latest buildserver build.

<b>Please provide any additional information below.</b>

I also discussed the issue in forum and Shai suggested to file an issue:

https://groups.google.com/forum/embed/?place=forum/codenameone-discussions&amp;showsearch=true&amp;showpopout=true&amp;hl=en&amp;parenturl=http%3A%2F%2Fwww.codenameone.com%2Fdiscussion-forum.html#!topic/codenameone-discussions/y10IxD_4Kvw

**Comment by shannah** [comment]
I posted a fix that will be on the build server soon.  I don't have a test case for this so I can't 100% verify that it fixes the issue.  All I know is that it doesn't seem to break anything.
