### ISSUE TITLE
Better scrolling while dragging

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1412]
Original [issue 1413](https://code.google.com/p/codenameone/issues/detail?id=1413) created by codenameone on 2015-03-25T16:11:13.000Z:

See the attached simple source code.

When dragging one of the labels toward the end of the scrollable area it will scroll further down, but stop scrolling before you are anywhere near the end of the scrollable container.
Then of course you can continue rubbing to scroll further down but it would be much more sensible to just continue scrolling while the drag position is still in the lower area of the scrollable container - just like in the IOS world clock when arranging locations.

**Comment by chen-fishbein** [comment]
fixed
