### ISSUE TITLE
Container's removeAll method can cause an effective memory leak on iOS, and eventual OOM crash

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1416]
On iOS only (confirmed not an issue on Android) , it appears there is an effective memory leak related to the use of the Container's removeAll().  

This is true for both the new VM and the old VM (although it's more pronounced on the new VM).

This is most obvious when using the new InfiniteContainer class and doing a pull-to-fresh (which calls Container.removeAll() on each refresh), but the same issue would surface whenever you repeatedly remove components from a container (& when the original component references from the construction/container add step are now out of scope).

The member objects and graphics memory of all of the components removed by removeAll()'s call to removeComponent() aren't ever freed up after the component is removed from it's parent container.

If a removed component happens to have a large child tree (like say, a nested set of containers, various UI components, and a fair number of images) and was repeated quite a bit in the parent container, the unfreed memory can add up very fast and cause the app to crash due to an OOM condition....

For instance, on an iPhone 5S, I can cause an OOM with only 15 refreshes in my app (or fewer if I do a small amount of scrolling around between refreshes).

On an iPad 2 or iPhone 4S, it would take half that number due to having 1/2 the RAM.

Attached are screenshots of Xcode Allocations profiling of the test case app.

Each generation was created between every pull-to-refresh.  
The larger growth in generations E & F are due to scrolling the main container, which was not done in the other generations, causing more of the contained labels to be drawn.

The second screenshot shows the inverted call tree of generation F, although generations B thru G show the same calls (at point of memory allocation).

Since the test case eclipse project is larger than 10MB, I can't attach it to the issue.
I'll send a download link via email once I've made it available for download.

![new_vm_new_pipeline_generations](https://cloud.githubusercontent.com/assets/11697822/6882301/e7a65cf4-d53c-11e4-85f6-e99d876800b5.png)
![new_vm_new_pipeline_leaks](https://cloud.githubusercontent.com/assets/11697822/6882325/954f8f56-d53d-11e4-8747-143969382e67.png)

**Comment by igo211** [comment]
As suggested by Steve Hannah...
Gist to reproduce:  https://gist.github.com/igo211/c09b6d721ce70b8572ab

**Comment by codenameone** [comment]
I've tried this on an iPod touch 4g running iOS 6.x, iPad 3 running iOS 8 and iPhone 6 running iOS 8.2. 
Neither one crashed despite well over 60 pull to refreshes.

The memory monitor in xcode is very inaccurate so you can't rely on that.

My only guess is that you are compiling via xcode instead of a build server compile and that you turned on memory monitoring tools in the preferences here:
![screen shot 2015-03-30 at 9 26 02 am](https://cloud.githubusercontent.com/assets/2353641/6891065/d1ed183e-d6be-11e4-84b1-8206379aae29.png)
Which will result in memory related crashes since these tools are inherently broken when allocating many small objects.

**Comment by igo211** [comment]
Please re-open the bug. 

Sorry, guess I wasn't being clear...
My comment:
"For instance, on an iPhone 5S, I can cause an OOM with only 15 refreshes in my app (or fewer if I do a small amount of scrolling around between refreshes)."  

wasn't referring to the test case project / gist... it was a reference to my real world app.
The example app shows the leak in Xcode, but because it's so simple (just adding a single label as a component) getting it to crash with an OOM would either take about 25x more pulls, or 2X more pulls combined with scrolling from top to bottom for each pull.  (That should be obvious from the first screenshot above which shows how much is leaked between pulls).

That crash happens using a the CN1 server build of my real world app, directly on any iOS device, and it's an OOM after 15 refreshes. (You may still have the source code to that real world app from the previous memory management bug. - if not, let me know and I'll send you another link to it again).

I provided the simplified test case because when both are profiled using Instruments (specifically "Allocations") under Xcode, they show most of the same leaked allocations (the only differences being due to the differences in the components returned from fetchComponents() between the test case and my real world app).    Since you always seem to insist on a small test case, I found one that shows the same leak(s), and shares a common aspect - a container which has many objects and that gets alot of components added and removed from it repeatedly.

You claim that using Xcode's memory monitor isn't reliable and that it will result in "memory related crashes since these tools are inherently broken when allocating many small objects."  Can you site your sources?  I tried Googling for it, but haven't been able to find any reference to such issues.

**Comment by codenameone** [comment]
The problem is that xcode is unreliable for this so the memory leak isn't necessarily a leak.
I'm assuming that what you are seeing in the production situation relates to the URLImage usage or something like that.
If you test it in the simulator do you see memory usage growing or does it shrink back?

**Comment by igo211** [comment]
Again, please site your sources about Xcode being unreliable for memory profiling.

As stated at the start of this issue, this is an iOS specific issue.  
This issue is not seen on Android, so I sincerely doubt it'll be seen in the simulator.
But, I'll give it a try.  So, where exactly in the simulator is there a memory monitor?

**Comment by igo211** [comment]
BTW, if I up the number of fetched components to 10000 per pull, I can get the example/test case app, running on an iOS device (no Xcode involved), to crash with an OOM at 56 pulls.  The time for each refresh to complete is 21 seconds (on an iPhone 5S).

I'm sure I can further reduce the number of pulls required to cause an OOM crash by simply upping the # of components per pull (although the pull completion will take longer), or alternatively increasing the complexity of the added components (the latter being the case in my real-world app).

You've got an effective memory leak,  it's specific to iOS, and it has nothing to do with URLImage.

**Comment by igo211** [comment]
I should note that the 56 pulls mentioned above included 3 "deep scroll down/scroll ups" along the way.

**Comment by igo211** [comment]
FYI - increasing the fetched components to 20000 per pull causes the example/test case app, running on an iOS device (no Xcode), to crash with an OOM at 20 pulls. (FYI, time to refresh is 1:45 per pull, until the last 2 or so, which take alot longer due to the OOM condition).

**Comment by codenameone** [comment]
I'll look into this, assuming there is a memory leak somewhere its pretty hard to detect with the volume of objects.

**Comment by codenameone** [comment]
OK, I was able to track this. Its a regression from the previous GC crash fixes that triggered a memory leak for very short lived objects. That made it hard to track down since these objects are usually pretty small and temporary, but they do add up. The fact that you crashed faster in the main app means you have large short lived objects which might impact the performance of your app, you should try to minimize that.

**Comment by codenameone** [comment]
FYI its fixed and in the build servers

**Comment by igo211** [comment]
Please re-open.

OK, you've fixed only *one* of the leak sources - admittedly the largest source, but there are others.
Your fix reduced the leak by about 80%, but 20% of the original leak sources are still there, and appear to be related to graphics resources.   

Of the the remaining leaks, it appears that the drawing of both pull-to-refresh and InfiniteProgress is responsible for ~11% (of the original ~20%).  The other 89% (of the original ~20%) comes from 2 allocations in drawFrame (not sure exactly what that coorelates to in the CN1 Java API).

**Comment by codenameone** [comment]
Graphics data is cached using weak references and will only be discarded when we get a memory warning from the OS.
