### ISSUE TITLE
Wrong ComboBox height in Android after screen keyboard hiding

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1418]
# Case:
* Choose TextField field
* Press to ComboBox
* Keyboard hides and ComboBox stratched to wrong size

![Screenshot of ComboBox]
(http://cs625519.vk.me/v625519524/245e7/OQ-21EIjIoI.jpg)

**Comment by codenameone** [comment]
Steve, could this be related to the popup change with the keyboard?

**Comment by shannah** [comment]
What popup change are you referring to?  I don't recall making any changes that would affect the android port, but maybe I'm just forgetting something.

**Comment by codenameone** [comment]
The Picker change you made with the keyboard. Could that be related?

Just thinking about it though, is this on Android or iOS.

**Comment by shannah** [comment]
It says android in the title.  I think my picker changes were limited to the iOS port.

**Comment by codenameone** [comment]
Ugh, missed that initially.

I don't think this issue is fixable on Android due to the screen resize on keyboard input which requires a big change. Its something we'd like to change eventually but its a pretty big revolution in the code.

**Comment by chen-fishbein** [comment]
partially fixed - it won't be stretched it now, but it also won't try to do any resize on the popup, which is in most cases, ok.
