### ISSUE TITLE
Alpha-transparent on iOS

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1419]
Strange work alpha transparents on iOS

Code
-------

```Java
setLayout(new BorderLayout());

monthLabel.setUIID("LabelMonth");
leftButton.setUIID("LabelArrow");
rightButton.setUIID("LabelArrow");
dayLabel.setUIID("LabelDay");
setUIID("ContainerHeader");

addComponent(BorderLayout.SOUTH,  monthLabel);
addComponent(BorderLayout.WEST,   leftButton);
addComponent(BorderLayout.EAST,   rightButton);
addComponent(BorderLayout.CENTER, dayLabel);
```

Screenshots
----------------

![Alpha demo]
(http://cs625519.vk.me/v625519524/2488a/9mrdlMxOLZ4.jpg)

monthLabel UUID
------------------------

![monthLabel]
(http://cs625519.vk.me/v625519524/24891/AoykB_brCik.jpg)

**Comment by shannah** [comment]
Where is the red gradient background coming from for monthLabel?  Based on the information you've posted (if that was all there was), then the iOS version is correct.  If you can post a single file test case that reproduces the issue, that would make it much easier for me.

**Comment by codenameone** [comment]
Historically fillRect ignored the alpha component when drawing in the old pipeline. This maps to the derive transparency property. I'm guessing that this bug still exists in the new pipeline.

**Comment by ftp27** [comment]
The red fradient background as image came from ContainerHeader. Unfortunately, I ran out of build points for creation test project with this issue. iOS builds is very expensive :)

**Comment by ftp27** [comment]
New month - new points :) 
https://github.com/ftp27/cn1-transparent-test

**Comment by ftp27** [comment]
When we can see results on server?
