### ISSUE TITLE
Android Date/ Time Picker "Cancel" button click disabled the component

### ISSUE THREAD

**Issue by CN1Android** [codenameone/CodenameOne#1421]
Date Picker or Time Picker on Android gets disabled when clicking on "Cancel" button.
Further clicking on the component does nothing.

1. Date/ Time Component - Enabled state
2. When clicking on the component -> this goes into disabled state and the native date component is shown
3. If I click on "Set", the date is set in the componenet and it is enabled. But if "Cancel" nutton is clicked, the component gets disabled. 
Happens on Android device (2.3 &&  4.0.4) as tested

**Comment by chen-fishbein** [comment]
Hi,
Please share the code, I am not able to reproduce the problem.

**Comment by CN1Android** [comment]
For sample, 
I have a form FormA. In the method PostFormA() i have 
findPickertest(f).setType(Display.getInstance().PICKER_TYPE_TIME);
//whether i handle the AddactionLIstener or not, with the above line of code the pciker time component is displayed. When clicking on the picker, the time is displayed with Set and cancel button. Click on cancel, and the picker component is disabled.

**Comment by chen-fishbein** [comment]
Ok, found it.
Thanks

**Comment by CN1Android** [comment]
Hi, 
I took a latest build today morning. The changes seems to be working for "Time Picker alone". Are there any changes made for "Date Picker" too. [ As mentioned in the Ticket , the issue was occurring in Date and Time Picker on android.
