### ISSUE TITLE
Not possible to clear cookies in iOS

### ISSUE THREAD

**Issue by Munken** [codenameone/CodenameOne#1422]
Clearing cookies in iOS does not work. 

The following code snippet test the cookie clearing:

```Java
ConnectionRequest req = new ConnectionRequest();
req.setUrl("http://emhermunch.dk/cookie.php");
NetworkManager.getInstance().addToQueueAndWait(req);
Log.p("COOKIE TEST");
Log.p("COOKIE 0: " + new String(req.getResponseData()));
NetworkManager.getInstance().addToQueueAndWait(req);
Log.p("COOKIE 1: " + new String(req.getResponseData()));
Cookie.clearCookiesFromStorage();
Log.p("Cleared cookies");
NetworkManager.getInstance().addToQueueAndWait(req);
Log.p("COOKIE 2: " + new String(req.getResponseData()));
```

On my device this gives
[EDT] 0:0:0,0 - COOKIE TEST
[EDT] 0:0:0,1 - COOKIE 0: <!DOCTYPE html>
<html>
<body>

Cookie named 'user' is not set!
</body>
</html>

[EDT] 0:0:0,76 - COOKIE 1: <!DOCTYPE html>
<html>
<body>

Cookie 'user' is set!<br>Value is: John Doe
</body>
</html>

[EDT] 0:0:0,76 - Cleared cookies
[EDT] 0:0:0,137 - COOKIE 2: <!DOCTYPE html>
<html>
<body>

Cookie 'user' is set!<br>Value is: John Doe
</body>
</html>

Ie. the cookie is not cleared.

**Comment by Munken** [comment]
Is there a workaround while we wait for a fix?
I have a AppStore submit waiting on this.

**Comment by shannah** [comment]
Workaround: I suspect that if you don't reuse the ConnectionRequest, it will work properly.  
I'm looking into why the cookies aren't being reset on iOS for the connection request.

**Comment by shannah** [comment]
No wait... I see the issue.  Will have a fix shortly.
