### ISSUE TITLE
BlackBerry Build Error

### ISSUE THREAD

**Issue by thopeactra** [codenameone/CodenameOne#1423]
When trying to build for BlackBerry I get a series of warnings and an error saying to correct the warnings. 

    Warning: com.codename1.charts.models.XYSeries$XYEntry: can't find referenced class java.util.Map
    Warning: com.codename1.charts.models.XYSeries$XYEntry: can't find referenced class java.util.Map$Entry
    Warning: com.codename1.charts.views.XYChart: can't find referenced class java.util.Map
    Warning: com.codename1.charts.views.XYChart: can't find referenced class java.util.Map$Entry
    Warning: com.codename1.ui.layouts.mig.ConstraintParser: can't find referenced class java.util.Map
    Warning: com.codename1.ui.layouts.mig.ConstraintParser: can't find referenced class java.util.Map$Entry
    Warning: com.codename1.ui.layouts.mig.Grid: can't find referenced class java.util.Map
    Warning: com.codename1.ui.layouts.mig.Grid: can't find referenced class java.util.Map$Entry
    Warning: com.codename1.ui.layouts.mig.MigLayout: can't find referenced class java.util.Map
    Warning: com.codename1.ui.layouts.mig.MigLayout: can't find referenced class java.util.Map$Entry
    Warning: com.codename1.ui.util.WeakHashMap: can't find referenced class java.util.Map
    Warning: com.codename1.ui.util.WeakHashMap: can't find referenced class java.util.Map$Entry
    Warning: there were 12 unresolved references to classes or interfaces.
        You may need to specify additional library jars (using '-libraryjars').
    Error: Please correct the above warnings first.

Even when I removed the Map references in my code and replaced them with a Hashtable I still got these error messages.

**Comment by codenameone** [comment]
Do you have any specific build arguments?
Do you use the Charts API or the MigLayout in your code?

**Comment by thopeactra** [comment]
I do not have any specific build arguments. I am using IntelliJ IDEA and just right click and use the "Send RIM Build" option from the Codename One sub-menu.

I do not use Charts to my knowledge I do not use the MigLayout in my project. I only have containers, forms and textfields.

**Comment by codenameone** [comment]
This seems to be a misbehavior of the IDEA plugin. You can add the build hint:
rim.obfuscation=false
Or just add codename1.arg.rim.obfuscation=false to the codenameone_settings.properties file

I'm leaving this open since we need to improve this in a more generic way.

**Comment by thopeactra** [comment]
Changing the obfuscation to false gave me a successful build!
