### ISSUE TITLE
Failed to fetch address from contact on iOS

### ISSUE THREAD

**Issue by orinzhao** [codenameone/CodenameOne#1424]
Use CN1 API to fetch address information, it works on Android and emulator, doesn't work on iOS

Here is the test code:

     Hashtable addresses = contact.getAddresses();
              if(addresses!=null){
                     // Test Code
                     Enumeration e = addresses.keys();
                     String sAddressType = null;
                     com.codename1.contacts.Address aCurrentAddress = null;
                     StringBuilder sbAddress = new StringBuilder();
                     while(e.hasMoreElements()) {
                         sAddressType = (String) e.nextElement();
                         sbAddress.append(sAddressType);
                         sbAddress.append(": ");
                         aCurrentAddress = (com.codename1.contacts.Address) addresses.get(sAddressType);
                         sbAddress.append(getAddressFormatted(aCurrentAddress));
                         sbAddress.append("\n");
                      }
              }
             Log.p("Addresses : " + addresses.toString() + " / " + sbAddress.toString());

On iOS, receives "Addresses : {} /"
On emulator, receives "Addresses : {home=com.codename1.contacts.Address@23b706fb} / home: US,South Park,"

Tried to compile with newVM and not, doesn't work under either one.
Please help take a look, thanks a lot.

**Comment by codenameone** [comment]
So what you are saying is contact.getAddresses() returns an empty Hashtable even when a contact has an address defined?

Wouldn't that be better served with a test case such as:

    Contact[] contacts = getAllContacts(true, true, false, true, false, true);
    for(Contact c : contacts) {
        if(c.getAddresses().size() > 0) {
            Dialog.show("Test Passed", c.getAddresses().toString, "OK", null);
            return;
        }
    }
    Dialog.show("Test Failed", "No address found", "OK", null);

**Comment by orinzhao** [comment]
Hi,

Thanks a lot for response.

I updated our code a bit like this:

String[] contactIDs = ContactsManager.getAllContacts();
for (String deviceContactID : contactIDs)
{
        Contact c = Display.getInstance().getContactById(deviceContactID);
        if(c.getAddresses().size() > 0) {
               // Previous test code
        }
        else
              Dialog.show("Test Failed", "No address found", "OK", null);
}

And I received the test failed dialog.
I double checked that the contact address field is not empty:
![img_0134](https://cloud.githubusercontent.com/assets/11760553/6966824/c0a70f4a-d929-11e4-809b-8e647048ccd1.PNG)
![img_0135](https://cloud.githubusercontent.com/assets/11760553/6966846/c62a70f6-d929-11e4-93c6-9a02e1f6f82a.PNG)

**Comment by codenameone** [comment]
Your test case fails if one of the contacts doesn't have an address. Mine fails if none of the contacts has an address. If mine passes and yours failed then this isn't a bug.

**Comment by orinzhao** [comment]
My test code doesn't work because I only selected this contact : "AaNew AaNative", that's why I provided  screenshots. I cannot use your test code, because I have around 2000 contacts created on iPad2. Sorry, I don't think this issue has been resolved.

**Comment by codenameone** [comment]
That's hardly something we can run on our devices since we obviously don't have your address book.
If my test case passes and yours fails for a specific contact then you need to figure out what makes that specific contact problematic and provide us with a way to reproduce this.

**Comment by orinzhao** [comment]
True, you have neither access to my address book nor my device. I don't expect it will be easy to identify the cause of this issue if you guys didn't encounter it before.
Let me state couple facts here:
1.) I just created a new contact on device with home address and work address, and then try to access it using "Display.getInstance().getContactById(deviceContactID)", this works on Android but not iOS.
2.) I tried to use "Display.getInstance().getContactById(deviceContactID, true, true, true, true, true)" instead of  "Display.getInstance().getContactById(deviceContactID)", still returns no address info on iOS.
3.) I cannot use "getAllContacts(true, true, false, true, false, true)" due to limit of memory, it seems load all contacts into memory at once. Even your test code works it still won't resolve my problem.

Here is the request, can you kindly provide some test code using getContactById and works on iOS? Or are you saying getContactById doesn't work well with addresses on iOS?
Thanks a lot.

**Comment by codenameone** [comment]
It shouldn't be a big deal since my test case doesn't fetch images. But If you want something more fine grained you can use this. You can also restrict it to the first 100 entries:

    String[] contacts = Display.getInstance().getAllContacts(true);
    for(String cid : contacts) {
        Contact c = Display.getInstance().getContactById(cid);
        if(c.getAddresses().size() > 0) {
            Dialog.show("Test Passed", c.getAddresses().toString, "OK", null);
            return;
        }
    }
   Dialog.show("Test Failed", "No address found", "OK", null);

**Comment by orinzhao** [comment]
I changed the test code a little bit:
                        boolean foundAddress = false;
			String[] contacts = Display.getInstance().getAllContacts(true);
			for(String cid : contacts) {
			    Contact c = Display.getInstance().getContactById(cid);
			    if(c.getAddresses().size() > 0) {
			        Dialog.show("Test Passed", c.getAddresses().toString(), "OK", null);
			        foundAddress = true;
			        break;
			    }
			}
			if (!foundAddress)
				Dialog.show("Test Failed", "No address found", "OK", null);

I received "Test Passed" on CN1 emulator.
I received "Test Failed" dialog, on iPhone 5s this time.
I am sure there are at least 2 contacts on this devices have phone numbers and home addresses.
CN1 build: CodenameOneFeature	1.0.0.201504021245

Any idea? Thanks

**Comment by codenameone** [comment]
We'll have a look

**Comment by orinzhao** [comment]
Thanks a lot. Have a good night.

**Comment by orinzhao** [comment]
Hi,

I waited for the latest CN1 plugin update: 1.0.0.201504261358

Tried with same code: 
boolean foundAddress = false;
String[] contacts = Display.getInstance().getAllContacts(true);
for(String cid : contacts) {
Contact c = Display.getInstance().getContactById(cid);
if(c.getAddresses().size() > 0) {
Dialog.show("Test Passed", c.getAddresses().toString(), "OK", null);
foundAddress = true;
break;
}
}
if (!foundAddress)
Dialog.show("Test Failed", "No address found", "OK", null);

Still the same:
I received "Test Passed" on CN1 emulator.
I received "Test Failed" dialog, on iPhone 5s this time.
I am sure there are at least 2 contacts on this devices have phone numbers and home addresses.

iOS is 8.1.3, is there any chance you guys are using deprecated Apple methods? Just guess, I'm not familiar with VM.

Any help? Thank you very much.

**Comment by orinzhao** [comment]
Hi,

Here is some update and 1 problem remaining:
After updating CN1 plugins, I am able to get address from iPhone (iPad2 actually).
There is still a problem though: com.codename1.contacts.Address.getStreetAddress returns the country name instead of street info, all the rests are working fine. (locality region postalCode country)
Would you mind help take a look? Thanks a lot.
