### ISSUE TITLE
OutOfMemory error when posting data to MultipartRequest

### ISSUE THREAD

**Issue by jensanthegreat** [codenameone/CodenameOne#1425]
Platform:
Emulator with jdk1.7.0_65
iOS 8.1 on iPhone6+
Android 4.4.2 on Nexus 5

Problem:
When sending file of more than 64MB with MultipartRequest.addData, it crashes and gives OutOfMemoryError.

Expected behavior:
The file is sent to the server without crash.

Steps to reproduce:
1. Copy a file called "TestData" to the FileSystemStorage
2. Run the following code (the "VALID_HOST_URL" is a server which receives files)

        try {
            MultipartRequest req = new MultipartRequest();
            req.setUrl(VALID_HOST_URL);
            req.setHttpMethod("POST");
            req.addData("test", Storage.getInstance().createInputStream("TestData"), 0, " application/octet-stream");
            NetworkManager.getInstance().addToQueueAndWait(req);
            System.out.println(new String(req.getResponseData(), "UTF-8"));
        } catch (Exception ex){
            ex.printStackTrace();
            Dialog.show("Test", ex.getMessage(), "OK", null );
        }

3.
The memory increases rapidly and finally throws OutOfMemory error.
Stacktrace:
`java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2271)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
    at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
    at sun.net.www.http.PosterOutputStream.write(PosterOutputStream.java:78)
    at com.codename1.io.BufferedOutputStream.write(BufferedOutputStream.java:170)
    at com.codename1.io.MultipartRequest.buildRequestBody(MultipartRequest.java:269)
    at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:339)
    at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:261)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
[Network Thread] 0:0:0,0 - java.lang.OutOfMemoryError: Java heap space
[Network Thread] 0:0:0,15 - java.lang.OutOfMemoryError: Java heap space`

**Comment by chen-fishbein** [comment]
is this happening on ios as well?

**Comment by jensanthegreat** [comment]
Sorry for late reply. Yes.

**Comment by codenameone** [comment]
Assigning to Steve to provide iOS evaluation

**Comment by shannah** [comment]
I made some changes on iOS so that it now handles most input and output streams with a constant memory footprint.  I tested it with some larger file uploads (100megs or so) on an iPhone 4S and it appears to be working.   

One note on the test code provided:

~~~~
try {
        MultipartRequest req = new MultipartRequest();
        req.setUrl(VALID_HOST_URL);
        req.setHttpMethod("POST");
        req.addData("test", Storage.getInstance().createInputStream("TestData"), 0, " application/octet-stream");
        NetworkManager.getInstance().addToQueueAndWait(req);
        System.out.println(new String(req.getResponseData(), "UTF-8"));
    } catch (Exception ex){
        ex.printStackTrace();
        Dialog.show("Test", ex.getMessage(), "OK", null );
    }
~~~~

When providing an InputStream to addData() you *must* provide an accurate "length" value.  You cannot provide zero.  IOS will freak out if you don't.  The safer way if you don't know the length is to just use a version that provides a file path.

**Comment by chen-fishbein** [comment]
fixed, will be available in the next server update
