### ISSUE TITLE
Customize InfiniteProgress in InfiniteScrollAdapter

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1427]
By default the InfiniteProgress placed on left part of the screen. This is not convenient for some tasks. Can you add some functions for customize container for InfiniteProgress? 

For example to change FlowLayout to LayeredLayout

[this place in code](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/components/InfiniteScrollAdapter.java#L55-L60)

**Comment by codenameone** [comment]
You are linking to a place where we center that component, I don't understand the issue description.

**Comment by ftp27** [comment]
![image](https://cloud.githubusercontent.com/assets/579162/7002239/34f2e1e8-dc50-11e4-9763-61c414276a75.png)
![image](https://cloud.githubusercontent.com/assets/579162/7002260/ad659be8-dc50-11e4-80f4-246674f06ec5.png)

- ContentPane
    - x: 0 
    - y: 53 
    - absX: 0 
    - absY: -2960 
    - Width: 320 
    - Height: 427 
    - Prefered Size: 680, 4541
- FormCalendar 
    - x: 0 
    - y: 0 
    - absX: 0 
    - absY: -2960 
    - Width: 318 
    - Height: 4541 
    - Prefered Size: 680, 4541
- Container 
    - x: 0 
    - y: 3405 
    - absX: 0 
    - absY: 3405 
    - Width: 35 
    - Height: 35 
    - Prefered Size: 35, 35
- InfiniteProgress 
    - x: 0 
    - y: 0 
    - absX: 0 
    - absY: 3405 
    - Width: 35 
    - Height: 35 
    - Prefered Size: 35, 35

This occurs because of incorrect of Container Prefered Size.

**Comment by ftp27** [comment]
Sorry. This is my fault. FormCalendar use FlowLayout instead of BoxLayout
