### ISSUE TITLE
Contributing CNTest to Codename One

### ISSUE THREAD

**Issue by sdwolf** [codenameone/CodenameOne#1429]
Related to: https://groups.google.com/forum/#!topic/codenameone-discussions/1KaTOqshQpg

I want to add the methods I defined in https://github.com/sdwolf/CNTest/blob/master/src/CNTest.java to the Codename One project. 

A few questions:

* Should I be adding them only for the AbstractTest class or to TestUtils as well?
* Are there any other classes I should be looking at?
* Can you share your settings for the netbeans auto formatting and the coding style guide you use for the project?

I will "DRY" up my code and add javadocs as well in the following days, any suggestions are welcome.

**Comment by sdwolf** [comment]
You can check my progress on my branch:
https://github.com/sdwolf/CodenameOne/tree/feature/add_cntest_methods
I will constantly be adding modifications and rebasing to make code review easier on your part. 
Feedback is welcome!

As for the coding style, I assumed the usual:
* camel case for method and variable names
* 4 space indents

**Comment by codenameone** [comment]
Thanks, merged the pull request.
