### ISSUE TITLE
Wrong iOS work in Adapter

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1431]
I use URLimage for downloading images. As adapter I used my custom adapter. It's code you can find in this [link](https://github.com/ftp27/cn1-imageAdapter-test/blob/master/src/eu/indevgroup/cn1/test/imageAdapter/main.java#L28-L100). Link to [repository](https://github.com/ftp27/cn1-imageAdapter-test)

You can see Issue on this screenshots :)
![image](https://cloud.githubusercontent.com/assets/579162/7024211/c53ae2de-dd43-11e4-90e2-10b4581d8965.png)

Question on Stackoverflow:
http://stackoverflow.com/questions/29301811/some-troubles-with-graphics-in-codenameone-on-ios/

**Comment by shannah** [comment]
Note to self (from email with Shai):I think this is a problem because subimage generates an image with width/height scaling (without changing the pixel data) and then getRGB ignores those values...

Looking into it.

**Comment by shannah** [comment]
Need to test further.  Works for this test case, but need some test cases where getRGB() gets a sub-image with non-zero x,y coordinates.
