### ISSUE TITLE
Double precision issue on iOS

### ISSUE THREAD

**Issue by orinzhao** [codenameone/CodenameOne#1432]
Hi,

I just discovered an interesting issue, which caused a few minor bugs in our app.
I have 2 test cases listed here, double value in test case B is not as precise as it is in test case A

Here is my test code:
// Test case 1:
                        String testJsonArray = "{\"root\":{\"AppointmentStart\": 1433091600,\"AppointmentEnd\": 1433095200}}";
			Result resultArray = Result.fromContent(testJsonArray, Result.JSON);
			Vector<Hashtable> array = (Vector) resultArray.getAsArray("root");
			for (Hashtable hash : array) {
				Double appointmentStartDouble = (Double) hash.get("AppointmentStart");
				Double appointmentEndDouble = (Double) hash.get("AppointmentEnd");
				Dialog.show("Activity Time", String.valueOf(appointmentStartDouble.longValue()) + " / " + String.valueOf(appointmentEndDouble.longValue()), "OK", null);
			}

I get 1433091600 / 1433095200

// Test case 2:
			String testJson = "{\"AppointmentStart\": 1433091600,\"AppointmentEnd\": 1433095200}";
			Result result = Result.fromContent(testJson, Result.JSON);
			Double appointmentStartDouble = result.getAsDouble("AppointmentStart");
			Double appointmentEndDouble = result.getAsDouble("AppointmentEnd");
			Dialog.show("Activity Time", String.valueOf(appointmentStartDouble.longValue()) + " / " + String.valueOf(appointmentEndDouble.longValue()), "OK", null);

I get 1433092000 / 1433095000

This only happens on iOS, both newVM and oldVM, so far I tested on iPad2 and iPhone 5s, iOS8.1.x (1&3), it works fine on Android and simulator.
I have one workaround to resolve this precision issue, which is making web service always return in array format, but this is not favoured, any better idea is very welcomed here.
Thanks a lot.

Orin@Gryphtech

**Comment by codenameone** [comment]
So if I understand correctly getAsDouble is problematic here. As far as I can tell it just uses the to string code of double then parses it back. We'll need a lower level test case to track this down, hopefully Steve can isolate something here.

**Comment by orinzhao** [comment]
Yes, it is a tricky one since it only happens on iOS, which means it could be deep down in somewhere of the VM.

And I did another test, using getAsLong instead of getAsDouble

String testJson = "{\"AppointmentStart\": 1433091600,\"AppointmentEnd\": 1433095200}";
			Result result = Result.fromContent(testJson, Result.JSON);
			Long appointmentStart = result.getAsLong("AppointmentStart");
			Long appointmentEnd = result.getAsLong("AppointmentEnd");
			Dialog.show("Activity Time", String.valueOf(appointmentStart) + " / " + String.valueOf(appointmentEnd), "OK", null);

This piece of code compiles, but failed at runtime, on simulator:
Exception: java.lang.NumberFormatException - For input string: "1.4330916E9"

This makes getAsDouble the only choice, if there are other options, please share, thanks a lot.

**Comment by codenameone** [comment]
Steve, this isn't a must fix for 3.0 because its an old VM issue. However, I would like the issue to be simplified before the code freeze (more decent test case that pinpoints the issue).

**Comment by orinzhao** [comment]
BTW, I built with new VM.
