### ISSUE TITLE
Picker type strings does not remember the selected value on the popup - ios

### ISSUE THREAD

**Issue by chen-fishbein** [codenameone/CodenameOne#1433]
When using 
        Picker p = new Picker();
        p.setType(Display.PICKER_TYPE_STRINGS);
        p.setStrings(new String[]{"aaa", "bbb", "ccc"});

When pressing on the picker the popup always displays with the first(default) value "aaa" on the selected value. 

The popup should show the picker selected value as the popup selected value.

**Comment by shannah** [comment]
Is this only in the iOS port or in all of them?

**Comment by chen-fishbein** [comment]
works fine on Android, this is an iOS port issue.
