### ISSUE TITLE
Android Date Picker "Cancel" button click disabled the component

### ISSUE THREAD

**Issue by CN1Android** [codenameone/CodenameOne#1436]
Date Picker  on Android gets disabled when clicking on "Cancel" button.
Further clicking on the component does nothing.

Date Component - Enabled state
When clicking on the component -> this goes into disabled state and the native date component is shown
If I click on "Set", the date is set in the componenet and it is enabled. But if "Cancel" nutton is clicked, the component gets disabled. Happens on Android device (2.3 && 4.0.4) as tested.

Issue 1421 was created for this issue. But this seems to have been fixed only for Time picker.  The issue still exist for Date Picker.

**Comment by chen-fishbein** [comment]
I wasn't able to reproduce this myself on my Android 5.1, but I applied
the same patch from #1421 which is harmless and will probably will fix
this
