### ISSUE TITLE
UIPrerenderedIcon not set to true on the new iOS vm

### ISSUE THREAD

**Issue by jaanushansen** [codenameone/CodenameOne#1437]
Hi!

In project settings I have

codename1.arg.ios.prerendered_icon=true

but in the CN1-created plist file is:

<key>UIPrerenderedIcon</key>
        <false/>

This means, that on iOS 6.0 the system adds gloss effect for the icons. It's not problematic on iOS 7.0+, because Apple has dropped the effect, but still icon should look nice also on iOS 6.

**Comment by shannah** [comment]
Fixed in SVN rev 1194
