### ISSUE TITLE
iOS crashes when printing Log

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#1438]
After running the app for a while it crashes in com_codename1_oi_Log.m with a EXC_BAD_ACCESS 0x4, the offending method is:

    JAVA_VOID com_codename1_io_Log_print___java_lang_String_int(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT  __cn1ThisObject, JAVA_OBJECT __cn1Arg1, JAVA_INT __cn1Arg2)

and the offending line (847) is:

    DEFINE_CATCH_BLOCK(catch_L1316342000cn1_class_id_java_lang_Throwable3, label_L1178747561, restoreToL1316342000cn1_class_id_java_lang_Throwable3);

Although I don't have a step by step to reach this bug it was reproducible quite often. Please let me know if you need more information.

**Comment by codenameone** [comment]
I'm afraid that's not enough, we need a test case.
