### ISSUE TITLE
Add display of current in-use codename one client library versions in the IDE

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1439]
This is an enhancement request for the various CodenameOne IDE plugins - 

Currently there is no convenient and obvious way for a dev to know what version of the codename one client libraries are in use, and what recent bugfixes and enhancements they include.

Currently, the only workaround and way to have any idea is to manually examine a jar file - in Eclipse, the most relevent file appears to be "CodeNameOneBuildClient.jar" - by unjaring it, and looking at the version.properties file, which has a single "build" property with a ISO style date value ( e.g. build=20150402 ).  

Suggested solution...

At a minimum, I suggest extracting and showing the aforementioned build property in the IDE, next to the "Update Project libs" button.  This would go a long way towards eliminating dev confusion on what they're working with.

Additionally, I suggest including a text file in CodeNameOneBuildClient.jar that describes the changes since the last client library update, *and* display that file's contents in the IDE... again, near the "Update project libs" button.  The text file contents doesn't have to be full-on release notes (although that would be great), but could just be a list of the github issue numbers & titles since the last CodeNameOneBuildClient.jar file update, so that devs know what's new / fixed in the client lib(s) they have in use.

For bonus points -  I suggest showing the build dates/release dates of the plugin and any other relevant codename one released files in use (so that they clearly understand that the plugin updates/versions and the client library(s) updates/versions are independent of each other).

**Comment by codenameone** [comment]
That's actually the wrong file.
There are many complexities related to that and there is a separate issue and lengthy discussions about this in the discussion forum. 

We won't be doing this since people don't understand the fact that we have several separate pieces each of which has a separate unrelated update process. This will breed even more confusion.
