### ISSUE TITLE
OS Startup Orientation Issue

### ISSUE THREAD

**Issue by 312burnsy** [codenameone/CodenameOne#1440]
I'm porting a existing Android application to IOS and attempting force startup orientation to landscape then lock in place with no success. The application always starts in portrait and locks in place. 

Any help would be appreciated.

codenameone_settings.properties:
#
#Tue Mar 31 11:00:54 EDT 2015
codename1.vendor=CodenameOne
codename1.displayName=Solview 2.0.1
codename1.icon=G\:\\Development\\Projects\\IPhone\\Solview 2.0.1\\res\\theme\\solview_icon.png
codename1.languageLevel=5
codename1.ios.debug.certificatePassword=apple
codename1.secondaryTitle=Solview 2.0.1
codename1.version=1.0
package=generated
codename1.mainName=SolviewMain
codename1.ios.certificatePassword=
codename1.ios.release.provision=G\:\\Development\\Tools\\CodeName One\\Distribution.mobileprovision
codename1.rim.signtoolDb=
libVersion=85
codename1.ios.release.certificatePassword=apple
codename1.ios.certificate=
userClass=src/userclasses/StateMachine.java
codename1.ios.release.certificate=G\:\\Development\\Tools\\CodeName One\\iphone_dev.p12
codename1.ios.appid=7T54K88TH6.com.solential.solview
codename1.android.keystorePassword=
codename1.j2me.nativeTheme=nativej2me.res
codename1.rim.signtoolCsk=
codename1.ios.debug.certificate=G\:\\Development\\Tools\\CodeName One\\iphone_dev.p12
codename1.arg.ios.interface_orientation=UIInterfaceOrientationLandscapeLeft\:UIInterfaceOrientationLandscapeRight
mainForm=Main
baseClass=src/generated/StateMachineBase.java
codename1.android.keystore=
guiResource=theme.res
codename1.android.keystoreAlias=
codename1.rim.certificatePassword=
codename1.ios.debug.provision=G\:\\Development\\Tools\\CodeName One\\DevProfile.mobileprovision
codename1.ios.provision=
codename1.packageName=com.solential.solview

Main Class:
package com.solential.solview;

import com.codename1.io.Log;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import userclasses.StateMachine;

public class SolviewMain {
   
    private Form current;
    
    public void init(Object context) {
        // Pro users - uncomment this code to get crash reports sent to you automatically
        /*Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });*/
    
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        
        Display disp = Display.getInstance();
        disp.lockOrientation(true);
        new StateMachine("/theme");        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }
}

**Comment by codenameone** [comment]
You need to ask questions in the discussion forum not issue tracker.

**Comment by codenameone** [comment]
Sorry I misread the issue (too many concurrent threads). Its fixed in git and should probably work already with current builds.
