### ISSUE TITLE
Missing files for compilation

### ISSUE THREAD

**Issue by heralight** [codenameone/CodenameOne#1442]
Hi!

There is apparently some missing files or there is another git project to fetch ?

stamp:
[propertyfile] Updating property file: /m/dev/githubCn1/CodenameOneDesigner/src/version.properties
[propertyfile] Creating new property file: /m/dev/CodenameOne/NBPlugin/CodenameOnePlugin/src/version.properties

BUILD FAILED
/m/dev/githubCn1/CodenameOne/build.xml:122: java.io.FileNotFoundException: /opt/u/m/dev/CodenameOne/NBPlugin/CodenameOnePlugin/src/version.properties (Aucun fichier ou dossier de ce type)

**Comment by codenameone** [comment]
This was always the case, you can comment out the relevant build xml portions, they aren't important.
