### ISSUE TITLE
Paint function bug

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1447]
I faced an error during runtime of my app. The entire area of the form is filled with black until repaint function is on (this may be becausr of scrolling or something else). The situations can be different and it's hard to catch this moment. Often this occurs while adding elements to BoxLayout in InfinitiveList. Log of this error looks like:
```
I/Codename One( 4218): Resource not found: theme_phone.ovr
I/Codename One( 4218): Resource not found: theme_android.ovr
I/Codename One( 4218): Resource not found: theme_android-phone.ovr
```
In iOS the trouble is the same

Video with bug:
https://youtu.be/dXFwRB8JrXw?t=28

Code with this moment:
```java 
public void response(int responseCode, Hashtable response) {
    if (responseCode == 200) {
        model = new modelCalendar(response);
        InfiniteScrollAdapter.addMoreComponents(
            form, 
            CalendarListEntity.getArrayOfComponents(model.getEntitiesArray()), 
            true
        );
    }
}
```

**Comment by codenameone** [comment]
The notices printed above have nothing to do with the error and are completely fine.
I'm guessing you are blocking the EDT for some duration. The messages above are printed when the theme is loaded from scratch, I'm guessing you are triggering that on the EDT with your code.

**Comment by ftp27** [comment]
Nonetheless this trouble doesn't appear on emulator. Which indicates that the error is not in my code.
