### ISSUE TITLE
Null pointer exception in iPhone when using editString

### ISSUE THREAD

**Issue by nirmaljuthani** [codenameone/CodenameOne#1450]
Hi,

I am getting Null pointer exception with the following stack trace in iPhone 4, iOS ver 7.1.2:

Apr 16 11:57:00 Vaishalis-Iphone S2PayApp[1769] <Warning>: java.lang.NullPointerException
	    at com_codename1_ui_Display.processSerialCalls:1145
	    at com_codename1_ui_Display.edtLoopImpl:1083
	    at com_codename1_ui_Display.invokeAndBlock:1199
	    at com_codename1_ui_Display.invokeAndBlock:1234
	    at com_codename1_impl_ios_IOSImplementation.editString:541
	    at com_codename1_impl_CodenameOneImplementation.editStringImpl:291
	    at com_codename1_ui_Display.editString:1509
	    at com_codename1_ui_Display.editString:1481
	    at com_nvsoft_s2pay_fsm_PayMoneyUI_4_1.run:301
	    at com_codename1_ui_Display.processSerialCalls:1145
	    at com_codename1_ui_Display.edtLoopImpl:1083
	    at com_codename1_ui_Display.mainEDTLoop:989
	    at com_codename1_ui_RunnableWrapper.run:120
	    at com_codename1_impl_CodenameOneThread.run:176
	    at java_lang_Thread.runImpl:153

This used to work earlier, but in recent build it is giving this error. Please note, I am using editString() function in one form to show the keyboard on form load. After the user enters the value in text field, the work flow moves ahead and that action is completed. But after few seconds a Null pointer exception is thrown with the above stack trace.

**Comment by nirmaljuthani** [comment]
Following is the code, through which editString is called:

        parentForm.addShowListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //now setting focus once when form is shown, in other events we don't need to set focus
                //if this flag is removed it will cause UI issues
                //also navigation back may not properly
                if(loadingFormFirstTime){
                    loadingFormFirstTime=false;
                    pin.requestFocus();
                    if (Display.getInstance().isTouchScreenDevice()) {
                        Display.getInstance().callSerially(new Runnable() {
                            @Override
                            public void run() {
                                // NOTE: As per Shai's recommendation, always run
                                // editString in a callSerially call even if we are already on EDT
                                Display.getInstance().editString(pin,
                                        pin.getMaxSize(), pin.getConstraint(), pin.getText());
                            }
                        });
                    }
                }
            }
        });

**Comment by shannah** [comment]
I can't seem to reproduce this issue.  Here is my test case:

~~~~
package com.codename1.issue1156;

import java.io.IOException;

import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

public class Issue1450Test {

    private Form current;

    public void init(Object context) {
        try {
            final Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch (final IOException e) {
            e.printStackTrace();
        }
    }

    private boolean loadingFormFirstTime = true;
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        final Form hi = new Form("EditStringImpl");
        final TextField pin = new TextField();
        hi.addComponent(pin);
        hi.addShowListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //now setting focus once when form is shown, in other events we don't need to set focus
                //if this flag is removed it will cause UI issues
                //also navigation back may not properly
                if(loadingFormFirstTime){
                    loadingFormFirstTime=false;
                    pin.requestFocus();
                    if (Display.getInstance().isTouchScreenDevice()) {
                        Display.getInstance().callSerially(new Runnable() {
                            @Override
                            public void run() {
                                // NOTE: As per Shai's recommendation, always run
                                // editString in a callSerially call even if we are already on EDT
                                Display.getInstance().editString(pin,
                                        pin.getMaxSize(), pin.getConstraint(), pin.getText());
                            }
                        });
                    }
                }
            }
        });

        final Form startForm = new Form("Issue 1450");
        final Button testButton = new Button(new Command("Test Issue"){

            @Override
            public void actionPerformed(ActionEvent evt) {
                hi.show();
            }
            
        });
        startForm.addComponent(testButton);
        
        startForm.show();
    
       
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

}
~~~~

I have run it in iOS simulator (iPhone 4S, iOS 7.1) and on Device (iOS 8.2 iPhone 4S), a few times.  

Closing for now.  If you can provide a full test case that reproduces this issue, I'll reopen.
