### ISSUE TITLE
All methods of PurchaseCallback are called off the EDT

### ISSUE THREAD

**Issue by t-arn** [codenameone/CodenameOne#1460]
**Environment:**
libVersion 85 on Android

**Problem:**
All methods of PurchaseCallback are called off the EDT.
Shai says that they should be called on the EDT (which is the case in iOS).
https://groups.google.com/d/msg/codenameone-discussions/dYDaa5Af7N8/YFHXXXHGKA0J

**Comment by chen-fishbein** [comment]
fixed, thanks
