### ISSUE TITLE
RIM - Error starting MyApplication5: Module 'MyApplication5-10' has verification error 2924 at offset cac9 (codfile version 79)

### ISSUE THREAD

**Issue by VTsoumanis** [codenameone/CodenameOne#1465]
In Eclipse create the default CN1 Hello World Project (either manual or visual). 
Send a RIM build to the server . 
Install the cod file in any BB OS 5 or later simulator.
Start the app.
Launching fails with Log Event 
00:48.644: VM:VECPs=com.codename1.ui.util.
 0:00:48.644: VM:VECCs=UIBuilder$1
 0:00:48.644: VM:VECMm=get()
 0:00:48.644: Module 'MyApplication5-10' has verification error 2924 at offset cac9 (codfile version 79)
 0:00:48.644: 
 0:00:48.644: Linker error: 'VerifyError' for MyApplication5
 0:00:48.644: VM:CLRCv=0
 0:00:48.644: VM:CLRCv=0
 0:00:48.644: VM:CLRCv=0
 0:00:48.644: VM:CLRCv=0
 0:00:48.644: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.660: VM:CLRCv=0
 0:00:48.675: VM:CLRCv=0
 0:00:48.675: CMM: set CRC 432b3594
 0:00:48.691: NVS: delete 2
 0:00:48.691: NVS: write 2
 0:00:48.691: NVS: erase 298
 0:00:48.691: NVS: commit 734
 0:00:48.691: AM: Error starting MyApplication5: Module 'MyApplication5-10' has verification error 2924 at offset cac9 (codfile version 79)
 0:00:48.691: VM:NCICv=0,w=0
 0:00:48.707: GS(createSurface): Temporarily promoting window size

**Comment by codenameone** [comment]
This should be fixed now.

**Comment by codenameone** [comment]
This should be up in the cloud now, let us know if its still unresolved.

**Comment by VTsoumanis** [comment]
Its still unresolved as a verification error but the UIBuilder$1 critical value has changed to 
UIBuilder$LazyValueC

Here is the log event from BB produced by the standard Hello World manual project in Eclipse
This is from an obfuscated .cod file. 
 
0:11:10.336: AM: Starting MyApplication5
 0:11:10.368: VM:LINK MyApplication5
 0:11:10.418: VM:ISMFn=MyApplication5-2,o=11040
 0:11:10.418: VM:ISMFn=MyApplication5-2,o=11492
 0:11:10.508: Method  get
 0:11:10.508: VM:VECPs=com.codename1.ui.util.
 0:11:10.508: VM:VECCs=UIBuilder$LazyValueC
 0:11:10.508: VM:VECMm=get()
 0:11:10.508: Module 'MyApplication5-10' has verification error 2924 at offset ce4e (codfile version 79)
 0:11:10.519: 
 0:11:10.519: Linker error: 'VerifyError' for MyApplication5
 0:11:10.526: VM:CLRCv=0
 0:11:10.528: VM:CLRCv=0
 0:11:10.530: VM:CLRCv=0
 0:11:10.532: VM:CLRCv=0
 0:11:10.534: VM:CLRCv=0
 0:11:10.536: VM:CLRCv=0
 0:11:10.538: VM:CLRCv=0
 0:11:10.541: VM:CLRCv=0
 0:11:10.542: VM:CLRCv=0
 0:11:10.542: VM:CLRCv=0
 0:11:10.542: VM:CLRCv=0
 0:11:10.542: VM:CLRCv=0
 0:11:10.542: VM:CLRCv=0
 0:11:10.552: VM:CLRCv=0
 0:11:10.552: VM:CLRCv=0
 0:11:10.552: VM:CLRCv=0
 0:11:10.552: VM:CLRCv=0
 0:11:10.552: VM:CLRCv=0
 0:11:10.602: CMM: set CRC 8d6a0605
 0:11:10.602: NVS: delete 2
 0:11:10.612: NVS: write 2
 0:11:10.612: NVS: erase 46
 0:11:10.612: NVS: commit 574
 0:11:10.612: AM: Error starting MyApplication5: Module 'MyApplication5-10' has verification error 2924 at offset ce4e (codfile version 79)
 0:11:10.622: VM:NCICv=0,w=0
 0:11:10.632: GS(createSurface): Temporarily promoting window size

**Comment by VTsoumanis** [comment]
Is the fix on cloud?

**Comment by codenameone** [comment]
It is now.

**Comment by VTsoumanis** [comment]
It seems ok now , 
thanks. (i ve tried only handcoded apps)
