### ISSUE TITLE
Update Android Google Play libs in order to allow for support of Google App Indexing API

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1468]
With the Android build process, it appears the Google Play Services libs being used are out of date, and as such, do not include support of Google App Indexing.

When attempting to implement a native code solution on Android for Google App Indexing ( https://developers.google.com/app-indexing/webmasters/appindexingapi ) in order to drive app install links via Google search results ( http://android-developers.blogspot.com/2015/04/drive-app-installs-through-app-indexing.html  ), the following build error (along with several similar errors) occurs in the Android native code implementation:

<snip>

    [javac] error: cannot find symbol
    [javac] import com.google.android.gms.appindexing.Action;
    [javac]                                          ^
    [javac]   symbol:   class Action
    [javac]   location: package com.google.android.gms.appindexing

</snip>

The following imports must be resolvable in order to support the Google App Indexing API:

import com.google.android.gms.appindexing.Action;
import com.google.android.gms.appindexing.AppIndex;
import com.google.android.gms.common.api.GoogleApiClient;

**Comment by chen-fishbein** [comment]
fixed, will be available in the next server update.
