### ISSUE TITLE
Auto-scrolling while dragging does not behave well

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#1470]
With #1412 a new bug has been introduced.
This is caused by the following code in com.codename1.ui.Component.pointerDragged(int, int):
```java
                        //keep move it until edges or until it is fully visible in the scrollable parent container
                        Display.getInstance().callSerially(new Runnable() {

                            public void run() {
                                pointerDragged(x,y);
                            }
                        });
```

This is bound to build up a stack of postponed pointerDragged Events when the pointer is really moving which causes confusing behaviour.
Basically an auto-generated pointerDragged should not be executed when a real one occured after the auto-generated one has been created.
And - auto-generated pointerDragged events should always have the pointer location of the most recent real pointerEvent!

The FormInvestigateDraggingTweaked.java example I supplied with issue #1412 worked much better as it restricted the number of auto-generated pointerDragged events.

The way it is now I don't dare to publish my app because dragging within lists is an essential and much-used feature in my app.

**Comment by saeder** [comment]
You may use the following code to reproduce the misbehavior by dragging an entry towards the end of the list and keeping moving the pointer near the end of the list; then move back to the middle of the list keeping the pointer depressed. The list keeps scrolling.

```java
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;

public class FormInvestigateDragging extends Form {
	public FormInvestigateDragging() {
        setTitle("InvestigateDragging");
        setScrollable(false);
        setLayout(new BorderLayout());
        final Container panelCenter = new Container(new BoxLayout(BoxLayout.Y_AXIS));
		addComponent(BorderLayout.CENTER, panelCenter);
		panelCenter.setScrollable(true);
        for (int iLoop = 0; iLoop < 200; iLoop++) {
        	final Label label = new Label("line" + iLoop);
        	label.setAlignment(Component.CENTER);
        	label.setDraggable(true);
			panelCenter.addComponent(label);
        }
	}
}
```

**Comment by saeder** [comment]
And - auto-generated pointerDragged events should never occur after the pointer has been released.

**Comment by chen-fishbein** [comment]
Hi,
I tried to run your sample code and I don't observe any misbehavior.

**Comment by saeder** [comment]
I just created a project Issue1470, did "Update Project libs" and ran my sample code in the simulator.
When dragging the entry "line6" towards the end of the visible area the list starts to scroll.
Moving the pointer to the middle of the list while keeping the pointer pressed the list keeps scrolling down.

Real trouble starts to add up when more and more conflicting virtual pointerDragged events add up. Then it becomes more jumpy.

This is on the simulator and on IOS. It should be pretty obvious.

**Comment by chen-fishbein** [comment]
Ok, I now see this.
I have used your approach from the FormInvestigateDraggingTweaked, It is now fixed.

Thanks

**Comment by saeder** [comment]
The fix is neither on the build server nor in the Eclipse-plugin yet.
Do You really want to drive me to do my own builds with all force?
