### ISSUE TITLE
javascript build: round double

### ISSUE THREAD

**Issue by maaikez** [codenameone/CodenameOne#1475]
I'm doing something with rounding, which works perfectly in the built ios/android app and the simulator, but not in javascript, as you can see in the picture (second row first column, frequency).
I am using this:
            double f = (double)Math.round(frequency * 100000) / 100000;
            String formattedFrequency = Double.toString(f);

![download](https://cloud.githubusercontent.com/assets/4672351/7417951/31e6ba60-ef6a-11e4-9d7a-9420b7560c4c.png)

**Comment by shannah** [comment]
This should be fixed now.
