### ISSUE TITLE
request: selecting components in components inspector

### ISSUE THREAD

**Issue by maaikez** [codenameone/CodenameOne#1476]
It would be nice to be able to select a component in the component inspector, so you can see what component it is and what the name is. So just like in for example the Developer Tools in Chrome: click somewhere in the simulator on a component and the right component is selected in the component inspector.

It would be even better if you can also change some values in the Component Inspector to see live what the change is on the screen (for example: change the margin in the Component Inspector and you see directly what the result is of this change).

**Comment by igo211** [comment]
I'll second both those requests!

Both of those would increase development speed.
I spend far too much development time iterating on trivial layout & styling issues.

I'd also request not just current component inspector-shown values, but also the other style related settings as well ( background values, color values, alignment, border values, font values ).

**Comment by kutoman** [comment]
I agree and think it's still relevant having the year 2019

**Comment by codenameone** [comment]
Both this and #2695 would be really easy for community members to implement and contribute as a pull request. It's a pretty isolated piece of the code which you can easily debug in NetBeans without need of native or anything complex. We can do it but we have a huge pipeline of tasks to go through...

**Comment by codenameone** [comment]
This is implemented in the latest commit. Live editing is already supported both for CSS and designer tool.
