### ISSUE TITLE
"May 1th" on build server

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#1478]
![image](https://cloud.githubusercontent.com/assets/2677562/7442325/df1b8f6e-f0c1-11e4-8025-a6a4cf629210.png)

**Comment by codenameone** [comment]
Odd... You are better at JS than I am, why wouldn't this code work:

                                    var finishing = "";
                                    switch(asDateValue.getDate() % 10) {
                                        case 1:
                                            finishing = "st";
                                        case 2:
                                            finishing = "nd";
                                        case 3:
                                            finishing = "rd";
                                        default:
                                            finishing = "th";
                                    }

From cn1.js line 390 or so.

**Comment by shannah** [comment]
You need a "break" statement at the end of each case.  Same as java :p

On Sat, May 2, 2015 at 12:07 PM, codenameone <notifications@github.com>
wrote:

> Odd... You are better at JS than I am, why wouldn't this code work:
>
>                                 var finishing = "";
>                                 switch(asDateValue.getDate() % 10) {
>                                     case 1:
>                                         finishing = "st";
>                                     case 2:
>                                         finishing = "nd";
>                                     case 3:
>                                         finishing = "rd";
>                                     default:
>                                         finishing = "th";
>                                 }
>
> From cn1.js line 390 or so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1478#issuecomment-98387545>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by codenameone** [comment]
Ugh...
Thanks!
