### ISSUE TITLE
OAuth2 result access token processing causes StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1479]
When using the Oauth2 class to authenticate against an Oauth2 service provider (such as Instagram), a StringIndexOutOfBoundsException will happen if the Oauth2 service provider does not pass back any additional arguments in beyond the access token provided in the resulting redirect URL.

The problem is line 327 in the Oauth2 class:
token = accessToken.substring(accessToken.indexOf("=") + 1, accessToken.indexOf("&"));

Specifically, the "accessToken.indexOf("&")" part means there's an assumption that the redirect URL will always contain at least 1 additional arg beyond the access token - which is not true in the case of Instagram, and likely other Oauth2 providers as well.

**Comment by igo211** [comment]
Actually, I take back one thing... extra args wouldn't show up in the accessToken var, because that's everything after the "#" in the returned redirect URL (extra args would be before the "#").   So, the "accessToken.indexOf("&")" part of the above makes no sense whatsoever.

so, the fixed line would simply be:
token = accessToken.substring(accessToken.indexOf("=") + 1)

**Comment by igo211** [comment]
Just curious - what's the ETA for this fix?

**Comment by chen-fishbein** [comment]
fixed, thanks

**Comment by igo211** [comment]
I'm not seeing the fix in the simulator or the plugin's copy of the class, and my project libs and eclipse plugin are up-to-date.  Has the fix been made available yet?
