### ISSUE TITLE
Data stored using the Storage class may be automatically removed by IOS on memory shortage

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#1480]
Apparently on IOS and using the Storage class the data stored goes into the directory \<Application_Home>/Library/Caches. See also the iOS Data Storage Guidelines https://developer.apple.com/icloud/documentation/data-storage/index.html .

The data therefore is treated as cached data, data that can be downloaded again or regenerated. I noticed this only after one of my testers lost all application data because he got his iPhone in a low memory situation and afterwards all the application data stored using the Storage class was lost.
I could not find any hints in the Codename One Developer Guide. This should be at least clearly documented!
I'd expect the Storage class to use the \<Application_Home>/Documents directory.

**Comment by codenameone** [comment]
Thanks, this will work correctly for newly created projects. To define it for this in older projects you can use the build argument `ios.newStorageLocation=true`

**Comment by saeder** [comment]
When will it be effectively on the buld server?
And will it work with version 3.0 set in the Codename One Properties, too?

**Comment by codenameone** [comment]
3.0 is closed so no. 3.1 is currently planned for the end of July so it should be available then.
I think it should already be in the servers.

**Comment by codenameone** [comment]
I've decided to change the behavior here. If `ios.newStorageLocation` is defined we will use documents. If its undefined we will check if the documents directory cn1storage exists. Assuming it doesn't all files from caches will be copied in. This will provide a clean/seamless migration path to users.
