### ISSUE TITLE
FlowLayout with setFillRows = true draws contained component (button) shifted to the right

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1481]
On simulator, android, and iOS - 
With a container whose style is center aligned, with 4 pixels of padding and margin each on left and right, and whose layout is a FlowLayout with setFillRows set to true,  a single added button (whose style is centered, with 2mm padding and 1 mm margin on left and right)...

The button is drawn incorrectly - it is shifted to the right by a few pixels (i.e. it is not centered in the container, despite equal amounts of padding and margin on both left and right sides).

**Comment by chen-fishbein** [comment]
not sure this is a bug, the fill row will try to expand the last component to fill the empty space.

**Comment by igo211** [comment]
Actually, it appears all components in the row are resized equally to fill the empty space,
but I would expect that.

In any case, I think you don't understand the bug description.
Let me restate:

The observed issue is that there appears to be something wrong with either the component width calculation (too big/doesn't respect the padding/margin on the left or right sides) ...OR... the x position of one or more of the components in the container are incorrectly set - I'm not 100% certain which at present, but I'm leaning towards the width calculation being wrong.
See the attached screenshot.

![flowlayout_bug](https://cloud.githubusercontent.com/assets/11697822/7671219/62ef90f2-fc79-11e4-89c7-4360539fa78a.png)

**Comment by igo211** [comment]
I could be wrong, but based on what I'm seeing in the component inspector for the above example,  it appears that Flowlayout's calculation of the component widths are likely wrong - it appears the component's margins are not being included in the calculation.

**Comment by igo211** [comment]
Also, another separate but related issue (this may equate to a separate RFE)...

I see in fillRows(...) that all components aren't resized to an equal size, but rather increased in size an equal amount above their preferred size (i.e. the excess space is divided equally then added to each comp's preferred size). 

 I don't think this is what most devs really want (I know I don't) - I would expect that in the setFillRows(true) case, each component's preferred size would act as a minimum size, and all components are resized to an equal size when possible (not increased in size by an equal amount as is it now).   

I suppose I could create my own custom layout by copying FlowLayout and then modifying the fillrows(...) method.

Or, might I suggest that FlowLayout's fillrows(...) method signature be changed to either protected or public to allow for dev customized setFillRows behavior?

**Comment by chen-fishbein** [comment]
fixed the layout to take into consideration the margins and also changed the fillRow to be protected to allow subclasses to override the default behavior.
