### ISSUE TITLE
Cannot cast TextArea to TextField (JavaSE port)

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#1482]
When editing strings in a TextArea in the simulator, you get a ClassCastException.

**Comment by shannah** [comment]
@codenameone I think this is important enough to go into 3.0.  Please review.

**Comment by codenameone** [comment]
3.0 is closed we won't be updating it.
Since 3.1 will come out in July this isn't such a big deal and since this is a simulator only issue its even less of an issue.

**Comment by codenameone** [comment]
Also that specific bug didn't exist in 3.0, its a new commit that wasn't released yet.
