### ISSUE TITLE
Android build error:  com.android.dex.DexException: Cannot merge new index XXXXX into a non-jumbo instruction

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1483]
When generating an Android build for a (large-ish?) project, the build fails with 
com.android.dex.DexException: Cannot merge new index XXXXX into a non-jumbo instruction
Where XXXXX is some large integer.

This sounds like the following issue:
http://stackoverflow.com/questions/26093664/android-studio-only-dexexception-cannot-merge-new-index-65536-into-a-non-jumbo

Since this is related to the number of strings allowed per dex file, the build error is related to the total number of strings in a project.  I suspect a small, simple example project might be possible by somehow generating a file with a large number of static strings. 

Anecdotally - In my app's case, adding facebook support (by adding the facebook.appid CN1 build flag) tipped the scales from a successful build to a failing build - but this by itself is not sufficient to reproduce the issue in a much smaller project, such as the basic CN1 template project.

In any case...
I would assume that the solution is as stated in the stackoverflow thread - add the dex.force.jumbo=true argument to the build (maybe expose this as a CN1 build flag?).

Example build output snippet:

-dex:
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/bin/classes
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/dependency/google-play-services_lib/bin/classes.jar
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/dependency/facebook/bin/classes.jar
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/dependency/facebook/libs/bolts.jar
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/libs/userClasses.jar
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/dependency/facebook/libs/android-support-v4.jar
      [dex] input: /tmp/build4379253526082834767xxx/WhozTop/dependency/google-play-services_lib/libs/google-play-services.jar
      [dex] Pre-Dexing /tmp/build4379253526082834767xxx/WhozTop/dependency/google-play-services_lib/bin/classes.jar -> classes-fb2d00eb62a15bde88264969dc4039c6.jar
      [dex] Pre-Dexing /tmp/build4379253526082834767xxx/WhozTop/dependency/facebook/bin/classes.jar -> classes-4dbf8ce2fd6c32f7f04d2254918dc8c3.jar
      [dex] Pre-Dexing /tmp/build4379253526082834767xxx/WhozTop/dependency/facebook/libs/bolts.jar -> bolts-5b42248ba2d014acce81d35933dab6cd.jar
      [dex] Pre-Dexing /tmp/build4379253526082834767xxx/WhozTop/libs/userClasses.jar -> userClasses-7639d7a4a34efb1639bd64ab20ef0eb3.jar
      [dex] Pre-Dexing /tmp/build4379253526082834767xxx/WhozTop/dependency/facebook/libs/android-support-v4.jar -> android-support-v4-34e164ae3a0b5cb53af3b6e0cb3b8773.jar
      [dex] Pre-Dexing /tmp/build4379253526082834767xxx/WhozTop/dependency/google-play-services_lib/libs/google-play-services.jar -> google-play-services-5fedc27dbbb2243ae6e8c5e63bb64e63.jar
      [dex] Found new input file
      [dex] Converting compiled files and external libraries into /tmp/build4379253526082834767xxx/WhozTop/bin/classes.dex...
       [dx] Merged dex A (1088 defs/2669.4KiB) with dex B (1 defs/0.4KiB). Result is 1089 defs/3317.6KiB. Took 0.8s
       [dx] Result compacted from 4908.6KiB to 3092.8KiB to save 1815.8KiB
       [dx] Merged dex A (1089 defs/3317.6KiB) with dex B (346 defs/446.5KiB). Result is 1435 defs/3092.8KiB. Took 2.6s
       [dx] Merged dex A (1435 defs/3092.8KiB) with dex B (34 defs/39.4KiB). Result is 1469 defs/3896.0KiB. Took 0.2s
       [dx] Result compacted from 6674.0KiB to 4344.6KiB to save 2329.5KiB
       [dx] Merged dex A (1469 defs/3896.0KiB) with dex B (1066 defs/1257.7KiB). Result is 2535 defs/4344.6KiB. Took 0.4s
       [dx] Result compacted from 6397.7KiB to 5129.9KiB to save 1267.8KiB
       [dx] Merged dex A (2535 defs/4344.6KiB) with dex B (805 defs/810.0KiB). Result is 3340 defs/5129.9KiB. Took 0.4s
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Cannot merge new index 67092 into a non-jumbo instruction!
       [dx] 	at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:108)
       [dx] 	at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:25)
       [dx] 	at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:71)
       [dx] 	at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
       [dx] 	at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
       [dx] 	at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:48)
       [dx] 	at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:840)
       [dx] 	at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:811)
       [dx] 	at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:783)
       [dx] 	at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:680)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:540)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:230)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:199)
       [dx] 	at com.android.dx.command.Main.main(Main.java:103)
       [dx] 

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:892: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:894: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:906: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:283: null returned: 2

**Comment by chen-fishbein** [comment]
added the property the the project.properties, will be on the servers in the weekend
