### ISSUE TITLE
OnOffSwitch for android not working

### ISSUE THREAD

**Issue by epudev** [codenameone/CodenameOne#1488]
Hello
After upgrading my project to use the latest version 3 lib, and re compile my android app
i having issues with OnOffSwitch.

I have in may app a list of selections that opens the selected from.
One of the selections is pointing to configuration form with OnOffSwitch.
The OnOffSwitch value(true/false) are set during beforeForm load.
findCmdAutoAuthenticate(f).setValue(true);

This has been working great before no issues.
But now if a set the a value to false, the form is not shown at all, and im also losing images in the selection list.
If all OnOffSwitch are set to true the form load correctly.
But if one is set to false, the form is not shown.
I get this in both the simulator and on my phone.

If i switch skin to iPhone 4, everything works ok with OnOffSwitch, but using android skin fails.
I have tried to send a build with  android.asyncPaint=false, and that didn't work.

I recreated the problem by creating an new project.
but in this case setting the OnOffSwitch to true prevented the form to load, setting it to false made show the form.
i believe its linked to the default state you have set in the GUI builder.

I see in the thread monitor that i get invokeAndBlock1 when it doesn't work.
There  is no exceptions, it feels like a infinity loop

IDE: NetBeans
Desktop OS: Windows 8.1
Simulator: Android 
Device: Galaxy note 3

To recreate the problem
you create a standard Codnameone hello project
add to the main form a OnOffSwitch via the GUI builder
The switch is now by default off.
Via the GUI builder select Events Before Show
In the netbeans code window you now have
protected void beforeMain(Form f){
}
Add to this
findOnOffSwitch(f).setValue(true)
you should now have 

protected void beforeMain(Form f){
findOnOffSwitch(f).setValue(true);
}

Run the project, using android  skin like nexus
Now you should get a blank page or no page at all.
the page dose not show the hello box and not the switch

Now change it t
findOnOffSwitch(f).setValue(false);
and run, it should now work ok.

**Comment by chen-fishbein** [comment]
fixed, thanks
