### ISSUE TITLE
iOS NewVM - very slow in crypto operations (RSA key generation)

### ISSUE THREAD

**Issue by tomasjotov** [codenameone/CodenameOne#1489]
Hello,
With NewVM for iOS we’re experiencing performance problems – RSA key pair generation (using Bouncy Castle) is extremely slow comparing to XMLVM, witn NewVM (32-bit code) it is from 10s to 50s on iPhone5S, 4S never goes under 20 s

RSA key algorith:
http://doctrina.org/How-RSA-Works-With-Examples.html

Test code:

```
@Override
protected void onMain_ButtonAction(Component c, ActionEvent event) {
    final int rounds = 5;
    long startTime = System.currentTimeMillis();

    for (int i = 0; i < rounds; i++) {
        final int cnt = i + 1;

        int secs = (int) ((System.currentTimeMillis() - startTime) / 1000);
        findLabel1().setText("run: " + cnt + " time elapsed: " + secs);
        Display.getInstance().invokeAndBlock(new Runnable() {
            @Override
            public void run() {
                try {
                    KeyPair kp = null;
                    kp = PeigCryptoServices.generateAsymmetricKeyPair("RSA", 1024);
                }
                catch (NoSuchAlgorithmException e) {};
            }
        });
    }

    int secs = (int) ((System.currentTimeMillis() - startTime) / 1000);
    findLabel1().setText("DONE in " + secs + " secs");
}
```

Thanks
Tomas Jotov

**Comment by tomasjotov** [comment]
I have CN1 test project ready if needed - but don't know ho to attach it here

**Comment by chen-fishbein** [comment]
Hi,
Can you please create an issue for us in the git project and attach your
project, please make the project minimal as possible.

Best Regards,
Chen



On Thu, May 14, 2015 at 10:24 AM, tomasjotov <notifications@github.com>
wrote:

> I have CN1 test project ready if needed - but don't know ho to attach it
> here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1489#issuecomment-101950343>
> .
>



-- 

* <http://www.codenameone.com>*
*Chen Fishbein*
*+972-54-5448440 <chen@codenameone.com>*

**Comment by shannah** [comment]
This is sufficient.  I should be able to test if with what you have provided.

**Comment by shannah** [comment]
Actually, is `PeigCryptoServices` part of the BouncyCastle library or one of your own classes?

**Comment by tomasjotov** [comment]
Hello, it's our class which call Crypto provider, in this case BouncyCastle

    public static KeyPair generateAsymmetricKeyPair(String algorithm, int keySize) throws NoSuchAlgorithmException {
        KeyPairGenerator keyGen = KeyPairGenerator.getInstance(algorithm);
        SecureRandom random = SecureRandomProvider != null ? SecureRandom.getInstance(PEIG_RANDOM_GENERATOR, SecureRandomProvider) : SecureRandom.getInstance(PEIG_RANDOM_GENERATOR); // implementacni parametr
        keyGen.initialize(keySize, random);
        KeyPair pair = keyGen.generateKeyPair();
        return (pair);
    }

I put whole project on the forum, thread 
CodenameOne Discussions ›
iOS NewVM - very slow in crypto operations (RSA key generation)

https://docs.google.com/viewer?a=v&pid=forums&srcid=MDUzNjA1OTIxMDYzMDkwMTM2ODQBMTEzNzM4ODkyMjM2MTQwNzkwMDUBUDZPNjJyclFLa01KATAuMQEBdjI&authuser=0

**Comment by shannah** [comment]
I just get a Google error page when I click that link.

Is there any way you can just create a self-contained source sample that only depends on the BouncyCastle library and post that?

**Comment by tomasjotov** [comment]
I put it on Dropbox, please use this link
https://www.dropbox.com/s/ppeqsim1wk6gkb9/tst-cn1-speed.zip?dl=0

**Comment by shannah** [comment]
This project is missing some files.  com.aducid.util.URISchemmer and com.aducid.tools.Observable
Possibly others.

**Comment by tomasjotov** [comment]
I put whole test project to zip again:

https://www.dropbox.com/s/ppeqsim1wk6gkb9/tst-cn1-speed.zip?dl=0

**Comment by codenameone** [comment]
It seems the project provided here is WAY too complex and doesn't compile properly because it has conflicting classes between the library and the source.

**Comment by codenameone** [comment]
Steve did some performance improvements to the numeric code in 3.7 which should bring this to native performance levels. If this isn't the case we'd appreciate a microbenchmark as these are pretty hard to follow.
