### ISSUE TITLE
RFE:  Add a getExpiresIn method to FacebookConnect

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1490]
Facebook authorization returns more than just the access token.
It returns numerous other pieces of data - the most important of which is the expiration of the access token.

Specifically, FB returns an expires_in value which is in seconds.
It would be useful to have easy access to that value via the FacebookConnect object.
Either the raw returned integer value, or as a Date object.

**Comment by chen-fishbein** [comment]
implemented along time ago
