### ISSUE TITLE
Don't wotk String.toUpperCase on iOS

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1494]
![Demonstration](http://cs624931.vk.me/v624931524/2f5e5/hXWVJz5DNss.jpg)

p.s. How can I change status bar theme to white?

**Comment by shannah** [comment]
Fixed
https://github.com/codenameone/CodenameOne/commit/1646954ff160b2b78da2bdedd196a2e0026d6030
and

https://github.com/codenameone/CodenameOne/commit/b2e03af0e739f4b6c500724891de6d493023d1af

Will be on build server soon.
