### ISSUE TITLE
Start event doesn't occur

### ISSUE THREAD

**Issue by tomasjotov** [codenameone/CodenameOne#1495]
Hello,
I think that start event works differently with NewVM.
On iOS (tested iPhone 5S) it is fired when I start application, change forms, but it is not fired when I return to the application. Is it a bug or feature? Or how I can detect that user reopened the app? 

Scenario:
1. Application starts , "Start" event is fired
2. User goes to another app / or minimizes myapp
3. User returns to my app, but I cannot detect it

==> the main issue is to capture URI scheme parameters form AppArgs :( - but in step 3) there is no event fired
I am pretty sure it worked with XMLVM 

Thanks
¨Tomas Jotov

**Comment by codenameone** [comment]
This works exactly as expected:

        public class Issue1495 {

            private Form current;
            private Form hi;

            public void init(Object context) {
                try {
                    Resources theme = Resources.openLayered("/theme");
                    UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
                } catch(IOException e){
                    e.printStackTrace();
                }
            }

            public void start() {
                if(hi != null) {
                    hi.addComponent(new Label("Start " + System.currentTimeMillis()));
                    hi.revalidate();
                }
                if(current != null){
                    current.show();
                    return;
                }
                hi = new Form("Issue1495");
                hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
                hi.addComponent(new Label("Start " + System.currentTimeMillis()));
                hi.show();
            }

            public void stop() {
                current = Display.getInstance().getCurrent();
                hi.addComponent(new Label("Stop " + System.currentTimeMillis()));
            }

            public void destroy() {
            }

        }

**Comment by tomasjotov** [comment]
Hello,
does it really work on iOS?
In my case method start isn't called when user re-opens app or app is called form other app using custom URI (iPhone 5S, iPhone 5C) - it worked with previous versions but not now.
But if I switch between forms (using tabs), "start" method is called properly; also after first start it is called as well.

**Comment by codenameone** [comment]
I'm guessing your app crashes in the background for some reason. I suggest you check the test case then modify it to reproduce your issue.

**Comment by tomasjotov** [comment]
Hello, I'll prepare a test project
it doesn't crash - it just doesn't call start method when user starts app for the second time (app is already in memory)
