### ISSUE TITLE
Media Player Controls behaviour

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#1497]
There are some strange things I've noticed with the media player on Android.

1.  There are two sets of controls - they appear at the bottom of the screen and also if you tap the video you get the native controls.  I see that there is a call in the MediaPlayer source to check if native controls are supported but its not registering correctly as I'm getting both.

2.  The controls added by CN1 are just words, even if images are set in the UI designer.  If you set images in code, or via theme constants then they will show properly.

**Comment by chen-fishbein** [comment]
fixed in the repository, thanks
