### ISSUE TITLE
Hint text doesn't clear on Android

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#1503]
If you have a number of text input fields and navigate with the 'next' button on the keyboard then you will end up typing over the hint text.  

The hint does clear if you tap in the textarea, but doesn't if you move to one text area from another.

To reproduce, create a form with at least two text areas and hint text in the second one.  Tap the first text area and type, use the next button on the virtual keyboard to move to the second text area and the hint text will remain under your typing until the keyboard is closed or you tap inside the text area.

**Comment by codenameone** [comment]
I think this is a different issue from 2015 as text input went through a lot of changes since then. We posted a fix yesterday that might impact this regression so please test this with a new build
