### ISSUE TITLE
Please fix vm/ByteCodeTranslator/src/nativeMethod.m

### ISSUE THREAD

**Issue by tomasjotov** [codenameone/CodenameOne#1504]
Please fix vm/ByteCodeTranslator/src/nativeMethod.m
ADD this: row
  if (encArr == NULL) return -1;

//fix this method:
JAVA_INT java_lang_String_indexOf___int_int_R_int(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT  __cn1ThisObject, JAVA_INT ch, JAVA_INT fromIndex) {
    fromIndex = MAX(0, fromIndex);
    struct obj__java_lang_String* encString = (struct obj__java_lang_String*)__cn1ThisObject;
    JAVA_ARRAY_CHAR* encArr = (JAVA_ARRAY_CHAR*)((JAVA_ARRAY)(encString->java_lang_String_value))->data;

//!!! add this
    if (encArr == NULL) return -1;
//!!! add this

    //releaseForReturn(threadStateData, cn1LocalsBeginInThread, stackPointer - 1, 2, stack, locals);
    int off = get_field_java_lang_String_offset(__cn1ThisObject);
    int endOff = off+encString->java_lang_String_count;
    for (int i=off+fromIndex; i<endOff; i++) {
        if (encArr[i] == ch) {
            return i-off;
        }
    }
    return -1;
}

**Comment by shannah** [comment]
This case should never happen.  Can you post a  minimal test case that demonstrates the problem?

**Comment by tomasjotov** [comment]
Apparently it happens - ho do you think we found it?
We use this fix in our build environment, so I posted this issue just in case you wanna fix it - it works fine for us :)

**Comment by codenameone** [comment]
That's the wrong fix, the correct fix is already in the source control/build cloud.
