### ISSUE TITLE
JS Native Stub generation changes

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#1507]
The native stub generation for javascript in Netbeans works well except:

1. Selecting "Generate Native Access" seems to generate native stubs for all classes when it should only generate stubs for interfaces that extend NativeInterface.
2. I'd like to change the generation of the isSupported() method to use callbacks also - for consistency.
E.g.
Instead of generating

~~~~
    o.isSupported_ = function(callback) {
        return false;
    };
~~~~

generate

~~~~
    o.isSupported_ = function(callback) {
        callback.complete(false);
    };
~~~~

**Comment by codenameone** [comment]
How do you trigger issue 1? It doesn't happen for me.

**Comment by shannah** [comment]
Hmm.  Now it's not happening.  Perhaps I already had some JS files that I had added to native and this confused me.
