### ISSUE TITLE
Double.toString() returns bad result on Android and Simulator, ok on iOS

### ISSUE THREAD

**Issue by rbryx** [codenameone/CodenameOne#1508]
Label l = new Label(new Double(0.9).toString());

showing the label results in 0.899999999999999999 instead of 0.9.

**Comment by codenameone** [comment]
That's actually a problem in the iOS version. The correct value should be the 0.89999999999 because of the way numbers are represented in floating point systems. I doubt we'll fix it though.

**Comment by rbryx** [comment]
... maybe it is not clear or I don't understand:
on iOS the result is correct
on Android it is NOT correct
on Simulator it is NOT correct
why are you saying me that the problem is in iOS?

**Comment by shannah** [comment]
This thread might help you to understand why.
http://stackoverflow.com/questions/1089018/why-cant-decimal-numbers-be-represented-exactly-in-binary

Steve

On Tue, May 26, 2015 at 10:32 AM, rbryx <notifications@github.com> wrote:

> ... maybe it is not clear or I don't understand:
> on iOS the result is correct
> on Android it is NOT correct
> on Simulator it is NOT correct
> why are you saying me that the problem is in iOS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1508#issuecomment-105613145>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.
