### ISSUE TITLE
disposing a dialog keeps its TextField on screen and focused on iOS

### ISSUE THREAD

**Issue by rbryx** [codenameone/CodenameOne#1509]
create a dialog as below and show it. 
click on the TextField to make the keyboard appear.
type some text and tap the dialog's "ok" button without disposing the keyboard.
as result you obtain a dialog.dispose() but a transparent TextField with the typed text and the keyboard remains on screen and still with focus.

```java
Command c1 = new Command("ok");
Command c2 = new Command("cancel");
Command[] cs = new Command[]{c1, c2};
TextField tf = new TextField(entry.getCommento());
Command c = Dialog.show("insertComment", tf, cs);
if (c == c1) {
    //do something
} else {
    //do something else
}
```

**Comment by shannah** [comment]
Just tested this and can't reproduce. It has probably been fixed sometime in the past 14 months.
