### ISSUE TITLE
New iOS VM build has unnecerary flag that prevents upgrade

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#1513]
When submitting the appstore build update to review I receive the following error:

"This bundle is invalid. The key UIRequiredDeviceCapabilities in the Info.plist may not contain values that would prevent this application from running on devices that were supported by previous versions."

The referenced capability that brings this error is the armv7, according to this discussion it is not needed for the new ios sdk and should be removed:

https://devforums.apple.com/message/1137785#1137785

I've built this removing the armv7 restriction and tested it in a range of devices, from old ipod touch to iphone 6 with no issues, the manually compiled build was accepted for review.

I suggest there should be an option for this and it probably may be removed with no side effects.

**Comment by codenameone** [comment]
Thanks, this should be fixed now.

**Comment by FabricioCabeca** [comment]
Thanks Shai, but I've just noticed this patch didn't make it into stable version 3.0:

https://github.com/codenameone/CodenameOne/blob/Version-3.0/vm/ByteCodeTranslator/src/template/template/template-Info.plist

Would you mind adding this patch there too ?

**Comment by codenameone** [comment]
We don't change past releases. 3.1 will be out early next week.

**Comment by FabricioCabeca** [comment]
I guess this bug was reported and fixed even before the official 3.0 release, but I will wait for 3.1, thanks. When 3.1 is out I can expect that bugs will be fixed in both 3.1 branch and master until the next release is near, right ?
