### ISSUE TITLE
Netbeans Refresh Libs doesn't copy native/javascript resources

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#1514]
I'm trying this with the GoogleMaps test project.   I updated the build.xml script for the project first, then copied in a .cn1lib that includes a nativejavascript.zip inside it.  Then I selected "Refresh Libs".  It did not copy the resources in native/javascript of the lib into the lib/impl/native directory as I expect it to.

**Comment by codenameone** [comment]
As far as I can tell everything is in order. Are you using the latest version of the NetBeans plugin?
