### ISSUE TITLE
Javascipr port, form not support keylistener

### ISSUE THREAD

**Issue by Manukaki** [codenameone/CodenameOne#1516]
form "KeyListener" not working. The compiled JS apps just don't listen to the key pressed.

f.addKeyListener('a', new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
        String strChar = getChar(evt.getKeyEvent());
        System.out.println("Key " + evt.getKeyEvent() + " pressed,getChar() = " + strChar);
        evt.consume();
    }
});

**Comment by Manukaki** [comment]
Hi, I am sorry to ask here, about how soon this feature can be implemented? I am waiting to upgrade my subscription..

**Comment by shannah** [comment]
It is on my list.  Likely this week.

Steve

On Sun, Jun 14, 2015 at 3:07 AM, Manukaki <notifications@github.com> wrote:

> Hi, I am sorry to ask here, about how soon this feature can be
> implemented? I am waiting to upgrade my subscription..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1516#issuecomment-111809315>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by Manukaki** [comment]
Thank you, waiting for your good news!

**Comment by shannah** [comment]
Just implemented and pushed to SVN.  Should be on the build server shortly.

**Comment by Manukaki** [comment]
I just compile and test, the keylistener is not yet fully working. 
- "ENTER" char fail to capture, 
- Numberic keypad pad (hardware keyboard) also not captured.

Tested on Mac Desktop Chrome browser.

Thanks.
