### ISSUE TITLE
Error while building to Codename One 3.0

### ISSUE THREAD

**Issue by mayasoftdeveloper** [codenameone/CodenameOne#1517]
I have an error when sending an Android build using Codename One 2.0: 

Executing: /home/ec2-user/android-sdk/tools/android create project --target android-21 --name MovinspectionMovil --path /tmp/build4636659370243047648xxx/MovinspectionMovil --activity MovinspectionMovilStub --package com.mayasoft.movinspectionmovil Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/src/com/mayasoft/movinspectionmovil
Added file /tmp/build4636659370243047648xxx/MovinspectionMovil/src/com/mayasoft/movinspectionmovil/MovinspectionMovilStub.java
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/bin
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/libs
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res/values
Added file /tmp/build4636659370243047648xxx/MovinspectionMovil/res/values/strings.xml
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res/layout
Added file /tmp/build4636659370243047648xxx/MovinspectionMovil/res/layout/main.xml
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res/drawable-xhdpi
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res/drawable-hdpi
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res/drawable-mdpi
Created directory /tmp/build4636659370243047648xxx/MovinspectionMovil/res/drawable-ldpi
Added file /tmp/build4636659370243047648xxx/MovinspectionMovil/AndroidManifest.xml
Added file /tmp/build4636659370243047648xxx/MovinspectionMovil/build.xml
Added file /tmp/build4636659370243047648xxx/MovinspectionMovil/proguard-project.txt
Exception: java.io.FileNotFoundException: /tmp/build4636659370243047648xxx/MovinspectionMovil/src/com/codename1/impl/android/AndroidBrowserComponentCallback.java (No such file or directory)
java.io.FileInputStream.open(Native Method)
java.io.FileInputStream.<init>(FileInputStream.java:146)
com.codename1.build.daemon.Executor.replaceInFile(Executor.java:118)
com.codename1.build.daemon.AndroidBuilder.build(AndroidBuilder.java:579)
com.codename1.build.daemon.Executor$4.run(Executor.java:660)

**Comment by chen-fishbein** [comment]
Fixed, thanks
