### ISSUE TITLE
admob shows black container

### ISSUE THREAD

**Issue by maaikez** [codenameone/CodenameOne#1520]
I added admob to two of my apps this way: https://www.codenameone.com/blog/adding-google-play-ads.html. On Android however, when clicking on the ad, the main form is getting black, titlebar and ad still showing. The back button closes the app.
When using toolbar instead of the standard titlebar, only a black screen and the ad are showing.

On an iPhone, this is going well, when clicking on the ad, a browser will open. This is the behaviour I also want to have on Android.
Tested on Android 5, Android 4.2.

This is also the case with a Hello World app.

**Comment by chen-fishbein** [comment]
This is working just fine for me on my moto g android 5.
Are you seeing an exception? in the ddms

**Comment by maaikez** [comment]
I checked again, because I tested this on several devices. It seems the reason is the kind of ad. I had another ad, working well. However, it looks like I get a Zalando ad very often (on all my devices yesterday).
I just got an ad from Google Opinion Rewards, which is the same kind of ad as the Zalando one: an ad to install a new app. 
When clicking on the 'install' button, the app is also getting black, but google play is opening and when going back to the app, it's normal again.
However, when clicking on the ad itself, download button is getting bigger and screen will be black. When clicking again, download button is getting smaller again, but screen is staying black. Also, after some time without clicking (just looking to the ad), screen is getting black.

I added some screenshots to show what I mean with a black screen and the size of the download button.

I think the screen is always getting black when clicking on the ad, but when opening a browser or google play or whatever and going back to the app, everything is normal again. However, when there will be only an action with the ad (so no other action like opening another program), the screen is getting black and never is resetting, so is never getting normal again.

Problem stays that when not clicking on the ad, screen is also getting black after some waiting time.

![image](https://cloud.githubusercontent.com/assets/4672351/7938186/7bded834-0944-11e5-9bf7-1568ad9a8386.png)
![image](https://cloud.githubusercontent.com/assets/4672351/7938195/84eacdd4-0944-11e5-8902-c970836f9564.png)

**Comment by chen-fishbein** [comment]
Are you seeing any exception in the ddms?

**Comment by maaikez** [comment]
no errors

**Comment by chen-fishbein** [comment]
Can you try again? I've added a patch which might fix this

**Comment by maaikez** [comment]
I made a new build. Doesn't help unfortunately.

**Comment by chen-fishbein** [comment]
Can you try this app and let me know how this works for you?
http://codename-one.appspot.com/5563015037452288/abb7a14f-555f-4b18-8999-90d479f36c52/MyApplication-debug.apk

**Comment by maaikez** [comment]
Yes, screen gets black and within a second, it's normal again.

**Comment by chen-fishbein** [comment]
Ok, I see the flickers, but does it stays black? like what you described in
the bug?

**Comment by maaikez** [comment]
No, after a second (indeed it flickers) it's normal again!
So it doesn't stay black.

Maaike

**Comment by chen-fishbein** [comment]
Ok, does your app behaves the same? if yes can I close this bug? and you can open a new issue about the flickering.

**Comment by maaikez** [comment]
No in my (hello world) app the container stays black (I just built and installed a new version).

**Comment by chen-fishbein** [comment]
please post your code

**Comment by maaikez** [comment]
AdmobTest.Java:

package com.test.admobtest;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.io.IOException;

public class AdmobTest {

    private Form current;

    public void init(Object context) {
        try {
            Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        /*Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });*/
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World");
        hi.addComponent(new Label("Hi World"));
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }

}




codenameone_settings.properties:

#
#Mon Jun 01 18:45:52 CEST 2015
codename1.vendor=CodenameOne
codename1.displayName=AdmobTest
codename1.icon=icon.png
codename1.languageLevel=5
codename1.ios.debug.certificatePassword=
codename1.secondaryTitle=CodenameOne_Template
codename1.version=1.0
codename1.mainName=AdmobTest
codename1.ios.certificatePassword=
codename1.ios.release.provision=
codename1.rim.signtoolDb=
libVersion=88
codename1.ios.release.certificatePassword=
codename1.ios.certificate=
codename1.ios.appid=Q5GHSKAL2F.com.test.admobtest
codename1.android.keystorePassword=
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.ios.release.certificate=
codename1.rim.signtoolCsk=
codename1.ios.debug.certificate=
codename1.arg.android.googleAdUnitId=ca-app-pub-9456456456456456/4040404040
codename1.android.keystore=
codename1.android.keystoreAlias=
codename1.rim.certificatePassword=
codename1.ios.provision=
codename1.ios.debug.provision=
codename1.packageName=com.test.admobtest

**Comment by chen-fishbein** [comment]
I committed a fix to the android port, it will be on the servers in the next update.
I'm leaving this issue open for now until you verify that it works

**Comment by maaikez** [comment]
When will be the next update? Then I will test this.

**Comment by maaikez** [comment]
It looks solved, thank you!
