### ISSUE TITLE
Override the android:label in the Application tag - AndroidManifest.xml

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#1521]
Using build hints its possible to add additional attributes to the application tag in the AndroidManifest  however you can't replace the existing ones - it causes a build error by ahving duplicate attributes.  It would be good if we could use the android.xapplication_attr to replace existing attributes such as android:label

**Comment by chen-fishbein** [comment]
fixed, thanks.
will up on the next update
