### ISSUE TITLE
Javascipr port, Picker not yet implement.

### ISSUE THREAD

**Issue by Manukaki** [codenameone/CodenameOne#1525]
The javascript port's Picker component not yet implemented. It is not working after compiled success, the form contain the Picker component is just not shown.

**Comment by codenameone** [comment]
Which browser/device/OS?

**Comment by Manukaki** [comment]
Google Chrome on Mac

**Comment by Manukaki** [comment]
It is implemented. I just compile and tested.
Thanks.
