### ISSUE TITLE
Android port, recent updated build server, ConnectionRequest missing sent Content-Length while POST

### ISSUE THREAD

**Issue by Manukaki** [codenameone/CodenameOne#1526]
My apps is running ok for few months, and I am always building for few time a week.  
Recent updated build server (should be in last few days) missing sent Content-Length while POST for ConnectionRequest object.

My server is reply with 
"POST request must have a Content-Length header"
which previously don't have this error.

Here is the code:

        ConnectionRequest r = new ConnectionRequest();
	r.setTimeout(15000);
	r.setPost(true);
	r.setUrl(serverURL+"index.php?client=TABLET&v=445);		
	r.addArgument("UserLogin[uname]", login);
	r.addArgument("UserLogin[upass]", password);
	r.addArgument("UserLogin[ncaptcha]", scaptcha);	
	InfiniteProgress prog = new InfiniteProgress();
	Dialog dlg = prog.showInifiniteBlocking();
	r.setDisposeOnCompletion(dlg);
		
	NetworkManager.getInstance().addToQueueAndWait(r);

Please advice.

**Comment by chen-fishbein** [comment]
fixed, thanks.
will be deployed in the next server update
