### ISSUE TITLE
Checkboxes inside Multilist stops working and return to work strangely.

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#1528]
I'm facing annoying behavior on Multilist component with checkboxes. 

The problem is quite difficult to explain with few  words.
So, I've recorded a video that shows it occurring
and can help to see easily what's going on. 
In summary:
The checkbox (inside Multilist - emblem attribute)  stops working and return to work strangely.

I've also created a small enough test case for it to be readable and fully runnable that reproduces the problem. The video that I did mention before was recorded using this test case.

I've also created gist-snippets for StateMachine.java file.
This file contains all code that I wrote.
All other java source files was created by Codename wizard (plugin)
(https://gist.github.com/hrugani/e378e8a0197c3ff7742f)
To create a complete netbeans project to run and debug this project is very simple:
1. Step1: On Netbeans , create a CodenameOne project using the wizard.
2. Step2: Substitute the content of file StateMachine.java by content from gist snippet (link above)
After that, you have a complete project allowing you compile, run and debug.

Below the links to getting the complete NetBeans project (zip file) with test case and 
the video explaining what is the problem:

NetBeans Project: https://drive.google.com/file/d/0Bzc65Jiqgy3zemx4eS0yT243SFk/view?usp=sharing
Video:  https://drive.google.com/file/d/0Bzc65Jiqgy3zdlBUNWVPa2NPakU/view?usp=sharing

You can get complete project from github too:
https://github.com/hrugani/CodeNameOne_Checkbox_Problem

**Comment by jotiagorb** [comment]
I'm experiencing  the same problem. The problem has a dinamic of a flip-flop (on the first return do previus interface all check become uneditable, and doing the same navigation again they return working properly).  Such issue makes the entire application in fact unusable.

**Comment by chen-fishbein** [comment]
fixed, it was an interesting bug - the listener wasn't removed therefore each time the form was displayed another listener was added and when it was an even number they actually cancelled each which caused the list to not change it's state.
