### ISSUE TITLE
ios.urlScheme build flag doesn't work unless the facebook.appId build flag is also in use

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1529]
The title explains says it - ios.urlScheme build flag doesn't work unless the facebook.appId build flag is also in use...  If this is intentional, it's at the very least not currently documented (on http://www.codenameone.com/manual/advanced-topics.html#_sending_arguments_to_the_build_server )

As a side note, it's rather odd that the documentation shows the ios.urlScheme build flag, but then also later talks about the other, original way of supporting a custom url scheme on iOS ( using ios.plistInject ).
Shouldn't it be one way or the other, not both?

**Comment by codenameone** [comment]
Thanks. It seems that in some points in the code `ios.urlScheme` was used where in others `ios.urlSchemes` was used. I've fixed it so both will work from now on. This will be up in the next server deployment.
