### ISSUE TITLE
FlowLayout issue

### ISSUE THREAD

**Issue by bcTekGuy** [codenameone/CodenameOne#1530]
There appears to be an issue with the FlowLayout if the container has a larger left padding than the left and right margins on the last component in the container.

The issue appears to be caused by this:

 public void layoutContainer(Container parent) {
        int x = parent.getStyle().getPadding(parent.isRTL(), Component.LEFT);
        int width = parent.getLayoutWidth() - parent.getSideGap() - parent.getStyle().getPadding(parent.isRTL(), Component.RIGHT) - x;

....
            if((x == parent.getStyle().getPadding(rtl, Component.LEFT)) || ( x+ cmp.getPreferredW() <= width) ) {

x is initialized to the left padding of the parent.
width is the layoutWidth of the parent minus the left and right padding = amount of room for all components.

Possible solution:
 ( x+ cmp.getPreferredW() <= width)

to 
 ( x+ cmp.getPreferredW()+marginX <= width+initX)

When investigating this problem, I also noticed that the parent.getSideGap() does not appear to be supported in the getPreferredSize.  This may cause a similar issue.

Here's a recreate for this issue.  Just create a blank app and paste

    public void start() {
        if(current != null){
          current.show();
          return;
        }
        new StateMachine("/theme");       
        current=Display.getInstance().getCurrent();
        current.removeAll();
        current.setTitle(null);
        current.setLayout(new BorderLayout());
        current.addComponent(BorderLayout.CENTER, new Container());
        Container cntWest=new Container(new BorderLayout());
        current.addComponent(BorderLayout.WEST,cntWest);
        
        Container cntTestPadding=new Container(new FlowLayout());
        cntTestPadding.getStyle().setPadding(Component.LEFT, 10);
        cntWest.addComponent(BorderLayout.NORTH,cntTestPadding);
        Label label=new Label("Tester");
        cntTestPadding.addComponent(label);
        cntTestPadding.addComponent(new ComboBox(new String[]{"Item1","Item2"}));
        cntTestPadding.addComponent(new CheckBox("My CheckBox"));
    
        Container cntTestSideGap=new Container(new FlowLayout()){
          @Override
          public int getSideGap() {
            return 50;
          }
        };
        cntWest.addComponent(BorderLayout.CENTER,cntTestSideGap);
        label=new Label("Tester");
        cntTestSideGap.addComponent(label);
        cntTestSideGap.addComponent(new ComboBox(new String[]{"Item1","Item2"}));
        cntTestSideGap.addComponent(new CheckBox("My CheckBox"));
        
        Container cntTestNoPadding=new Container(new FlowLayout());
        cntWest.addComponent(BorderLayout.SOUTH,cntTestNoPadding);
        label=new Label("Tester");
        cntTestNoPadding.addComponent(label);
        cntTestNoPadding.addComponent(new ComboBox(new String[]{"Item1","Item2"}));
        cntTestNoPadding.addComponent(new CheckBox("My CheckBox"));        
    }

**Comment by chen-fishbein** [comment]
It's not clear from the above test case what is the issue you are experiencing, the proposed fix is wrong and creates broken layout
