### ISSUE TITLE
ContactsManager.getAllContactsWithNumber does not return contactId in first record in iPhone

### ISSUE THREAD

**Issue by nirmaljuthani** [codenameone/CodenameOne#1533]
There is a bug in ContactsManager.getAllContactsWithNumber() method  in iPhone and it does not return the first contact. If you instead call ContactsManager.getAllContacts() instead, it returns all the contacts. On looking at the code at line number 2855 of file iOSNative.m in iOS port, we can see a possible bug. I have pasted the code from that line below:

    CFArrayRef allPeople = ABAddressBookCopyArrayOfAllPeople(addressBook);
    if(includeNumbers) {
        CFIndex nPeople = ABAddressBookGetPersonCount(addressBook);
        int responseCount = 0;
        for(int iter = 0 ; iter < nPeople ; iter++) {
            ABRecordRef ref = CFArrayGetValueAtIndex(allPeople, iter);
            ABMultiValueRef numbers = ABRecordCopyValue(ref, kABPersonPhoneProperty);
            
            if(numbers != nil && ABMultiValueGetCount(numbers) > 0) {
               responseCount++;
                data[responseCount] = ABRecordGetRecordID(ref);
            }
        }
        
        POOL_END();
        return;
    }
    for(int iter = 0 ; iter < size ; iter++) {
        ABRecordRef ref = CFArrayGetValueAtIndex(allPeople, iter);
        data[iter] = ABRecordGetRecordID(ref);
    }  

If you look in above code, the responseCount is initialized to 0 and then incremented before using it as an index to store contact in data array. This causes it to skip the 0 index in array. Can you please review and fix this issue.

**Comment by codenameone** [comment]
I think this was fixed in a recent commit from @shannah
