### ISSUE TITLE
Versioned builds download libraries for each build.

### ISSUE THREAD

**Issue by samlotti2** [codenameone/CodenameOne#1537]
I set my version to 3.0 and it downloads the libraries every time I do a build.  I am using IOS and Android, both have the issue.

Below is a snippet of the output.

build-for-android-device:
[codeNameOne] Your local libraries are out of date updating them from the server. After update is completed the build might fail! You will need to resubmit the build with the updated libraries!
[codeNameOne] 
[codeNameOne] Download Starting...
[codeNameOne] Downloading 15460894 bytes
[codeNameOne] Downloaded 1%
[codeNameOne] Downloaded 2%
[codeNameOne] Downloaded 3%
[codeNameOne] Downloaded 4%
[codeNameOne] Downloaded 5%
[codeNameOne] Downloaded 6%
[codeNameOne] Downloaded 7%
[codeNameOne] Downloaded 8%
[codeNameOne] Downloaded 9%
[codeNameOne] Downloaded 10%
[codeNameOne] Downloaded 11%
[codeNameOne] Downloaded 12%
[codeNameOne] Downloaded 13%
[codeNameOne] Downloaded 14%
[codeNameOne] Downloaded 15%
[codeNameOne] Downloaded 16%
[codeNameOne] Downloaded 17%
[codeNameOne] Downloaded 18%
[codeNameOne] Downloaded 19%

**Comment by chen-fishbein** [comment]
Thanks, it's fixed.
The fix will be part of the next plugin update
