### ISSUE TITLE
Graphics.drawImage is not working on Image, big memory leaks (iOS)

### ISSUE THREAD

**Issue by PiotrZub** [codenameone/CodenameOne#1539]
There is problem with Graphics.drawImage on image. The first run is working but in next graphics is not drawing anything and make there is a big memory leak, program crash after a few minutes.

package eu.forann.fmapapp;

import com.codename1.io.FileSystemStorage;
import com.codename1.io.Log;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.util.ImageIO;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import userclasses.StateMachine;

public class TestApp {

	private Form current;
	private TestForm iTestForm;
	private StateMachine iStateMachine;
	private Timer iTimer;
	private TestApp iTestApp;

	public void init(Object context) {
	}

	public void start() {
		iTestApp = this;
		if (current != null) {
			current.show();
			return;
		}
		iTestForm = new TestForm();
		iStateMachine = new StateMachine("/theme");
		iTestForm.show();
		startThreads();
	}

	/**
	 * start watchdog process to take care about GPS is working state and sending CGI
	 */
	private void startThreads() {
		iTimer = new Timer();
		iTimer.schedule(new TimerTask() {
			public void run() {
				Log.p("Timer");
				iTestForm.drawBackImage();
				iTestForm.repaint();
				Thread.yield();
			}
		}, 1000, 1000);
	}

	;

  public void stop() {
		current = Display.getInstance().getCurrent();
	}

	public void destroy() {
	}
}

class TestForm extends Form {

	Image iImage = null;
	int iX = 0;
	int iY = 0;

	public TestForm() {
		drawBackImage();
	}

	public static void drawRegion(Graphics aGraph, Image aImage, int aX, int aY) {
		aImage = aImage.subImage(10, 10, 400, 400, true);
		aGraph.drawImage(aImage, aX, aY);
	}
	Image iSourceImage=null;
	public void drawBackImage() {
		if(iSourceImage==null){
			iSourceImage = Image.createImage(100, 100, 0x00ffff);
			Graphics g1 = iSourceImage.getGraphics();
			g1.setColor(0x00ff00);
			g1.drawArc(40, 30, 50, 50, 0, 270);
		}
		iImage = Image.createImage(1000, 1000, 0x00ff00);
		Graphics g = iImage.getGraphics();
		g.drawImage(iSourceImage, 10, 10, 500, 500);
		Log.p("drawBackImage");
	}

	public void paint(Graphics g) {
		String mess = "";
			for (int i = 1; i < 3; i++) {
				drawRegion(g, iImage, i + iX++, iY++);
			}
			mess = "Paint iX:" + iX;

		mess = "Clip w/h:" + g.getClipWidth() + "/" + g.getClipHeight() + " mem(u/f):"
				+ (Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) / 1024 / 1024
				+ "/" + Runtime.getRuntime().freeMemory() / 1024 / 1024 + "MB;" + mess;
		g.setColor(0x008F40);
		g.drawString(mess, 10, 50);
		Log.p(mess);
	}

}

**Comment by codenameone** [comment]
That accesses Codename One code off the EDT which isn't supported.

**Comment by PiotrZub** [comment]
Thanks you are right.
Where can I find information which class is not thread safe? In JavaDoc 
there is no information. I can turn on debug EDT but than I get many 
false message about Image.width/height...
Can we suppose that all UI and Image class is not thread safe except 
getting properties like width/height?


W dniu 20-06-2015 o 14:55, codenameone pisze:
>
> That accesses Codename One code off the EDT which isn't supported.
>
