### ISSUE TITLE
Network request is halted when the dialog cannot be shown up due to network problem.

### ISSUE THREAD

**Issue by jackyy415** [codenameone/CodenameOne#1540]
We are trying to show an error dialog during network problem. When the screen is turned on, the dialog can be shown correctly and other connection requests can be made successfully afterwards. 
However, if the error dialog is shown during the screen is turned off, the dialog cannot be shown when the screen is turned on again. Even worse, no more connection request can be made afterwards. There is no response when I tried to make connection request again.

From my debugging, it looks like the connection request halted is due to the dialog not dismissed. As the dialog is not shown up, user cannot dismiss the dialog. The connection request will wait until the dialog is dismissed and thus no more connection request can be made.

The core sample codes are shown as below:

protected void initVars(Resources res) {
    NetworkManager.getInstance().addErrorListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            evt.consume();
            Dialog.show("Error", "There are errors.", "OK", null);
        }
    });
}

@Override
protected void onMain_ButtonAction(Component c, final ActionEvent event) {
    Display.getInstance().invokeAndBlock(new Runnable() {
        @Override
        public void run() {
            final ConnectionRequest cr = new ConnectionRequest();
            cr.setUrl("http://www.yahoo.c");

            cr.addResponseListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    Dialog.show("Received Response", "Received Response: " + new String(cr.getResponseData()), "OK", null);
                }
            });

            NetworkManager.getInstance().addToQueue(cr);

        }
    });

}

Steps to reproduce the problem:
1) Click the button to send the connection request. I have hard-coded the url to an invalid one so the error dialog should be shown up after clicking the button.
2) Click the button again. Turn off the screen before the error dialog is shown.
3) Wait for 5-10 seconds
4) Turn on the screen 
5) No error dialog is shown
6) Try to make another connection request by clicking the button again. 
7) No error dialog is shown even the screen is on.

Reference post:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/codenameone-discussions/mVXwo83lioY

**Comment by codenameone** [comment]
This should be fixed now, thanks.

**Comment by codenameone** [comment]
Closed this issue by mistake. The commit was for #1519

**Comment by chen-fishbein** [comment]
fixed, modal Dialogs won't show on a minimized app.
in your error handler check if minimized and do some other logic to handle this state
