### ISSUE TITLE
Don't work FacebookConnect and GoogleConnect classes

### ISSUE THREAD

**Issue by ftp27** [codenameone/CodenameOne#1553]
I'm trying to use new social authorisation, but have some problems with receiving feedback from Login class. I've prepared test project with this issue: https://github.com/ftp27/cn1-oauth2-test. In some login types our server answer with error, but even in this situation I need to receive some feedback. Because it blocks the whole work process.

**Comment by chen-fishbein** [comment]
Hi,
I have ran your project and I've seen the 400 error from FB and G+.
I have replaced the params with my own (appId, secret and redirectURI )and got the successful screen, so this is a configuration issue of your app identity on FB and G+

**Comment by ftp27** [comment]
Which answer should the server give from redirectURI address?

**Comment by chen-fishbein** [comment]
The redirect URI is just a URI that needs to be declared on the app(on server) when, check this latest post and verify your G+ is configured correctly:
http://codenameone.com/blog/building-a-chat-app-with-codename-one-part-2.html

**Comment by ftp27** [comment]
How can I receive feedback from the component in case if my server answers with error?

**Comment by chen-fishbein** [comment]
What kind of error? you can add error handler to the NetworkManager

**Comment by ftp27** [comment]
I can't handle error in code. There are all UI blocks in this case
