### ISSUE TITLE
Android "DexIndexOverflowException" error from codename one android build latest version

### ISSUE THREAD

**Issue by RonaldCY** [codenameone/CodenameOne#1555]
Dear Sir/Madam,

When I use Android build from codename one latest version and I put the generated 'source.zip' into IntelliJ IDEA 13 to compile, the error message come out

Error:Android Dex: [Test] Unable to execute DX
Error:Android Dex: [Test] com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
Error:Android Dex: [Test] at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
Error:Android Dex: [Test] at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
Error:Android Dex: [Test] at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
Error:Android Dex: [Test] at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
Error:Android Dex: [Test] at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Error:Android Dex: [Test] at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
Error:Android Dex: [Test] at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
Error:Android Dex: [Test] at com.android.dx.command.dexer.Main.run(Main.java:246)
Error:Android Dex: [Test] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:Android Dex: [Test] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
Error:Android Dex: [Test] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:Android Dex: [Test] at java.lang.reflect.Method.invoke(Method.java:606)
Error:Android Dex: [Test] at org.jetbrains.android.compiler.tools.AndroidDxRunner.runDex(AndroidDxRunner.java:161)
Error:Android Dex: [Test] at org.jetbrains.android.compiler.tools.AndroidDxRunner.main(AndroidDxRunner.java:294)
Error:Android Dex: [Test] at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:121)

so that I could not compile and debug.

The "DexIndexOverflowException" means there are too many methods http://developer.android.com/tools/building/multidex.html , in the generated application .apk. Please advice how i could resolve that issue.

Thanks and Best Regards,
Ronald Chan

**Comment by codenameone** [comment]
This was addressed with the recent migration to gradle: http://www.codenameone.com/blog/material-icons-background-music-geofencing-gradle.html
