### ISSUE TITLE
Basic App (no code added, just Theme design so far) crashes on Android: RenderThread seg-fault

### ISSUE THREAD

**Issue by jvkessel** [codenameone/CodenameOne#1562]
Uploaded to Github to get assistance from you in investigation if this is an issue.  Link to this specific commit as it's the simplest version with the least bells and whistles added to it:
https://github.com/jvkessel/TrainingTool/commit/3ad1718a727cf1009b42b1ffa2f0ac10def52b1c

Update:  I tried this app with an old Samsung Galaxy S3 phone and it actually runs, but the lag time is measured almost in minutes between pressing buttons and getting a response.

IDE: IDEA 14.1.2
Desktop OS: Windows 7 Enterprise
Simulator: N/A
Device: Galaxy S6, Android OS 5.0.2
Compiling with Java 1.8

I have a 2-form app with some lists and buttons with sample data, and I haven't edited the provided code at all (although I did start building separate classes for data structures, but I haven't used them for anything in the applicaiton or state machine classes yet).

I sent it in to build, downloaded it OTA to my Android device and ran it.

It clears the screen, puts the (unformatted) title at the top of the screen and sits there for about 15 seconds before crashing.

I added Android to the project in IDEA so that I could use logcat to debug and got the following output (See below the message).  it appears to be in libhwui or related to RenderThread, neither of which appear to be directly part of CN1.

What do you need from me to help you debug or troubleshoot?

Debug output:
8-08 16:14:40.458    3054-3125/ca.zettabot.trainingtool A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7fa93d4008 in tid 3125 (RenderThread)
08-08 16:14:40.548    1211-1211/? I/DEBUG﹕ pid: 3054, tid: 3125, name: RenderThread  >>> ca.zettabot.trainingtool <<<
08-08 16:14:40.828    3531-3177/? W/ActivityManager﹕ Force finishing activity ca.zettabot.trainingtool/.MyApplicationStub
08-08 16:14:40.828    3531-3177/? V/ApplicationPolicy﹕ isApplicationStateBlocked userId 0 pkgname ca.zettabot.trainingtool
08-08 16:14:41.018    3531-3531/? D/CrashAnrDetector﹕ Build: samsung/zerofltebmc/zerofltebmc:5.0.2/LRX22G/G920W8VLU1AOE1:user/release-keys
    Hardware: universal7420
    Revision: 11
    Bootloader: G920W8VLU1AOE1
    Radio: unknown
    Kernel: Linux version 3.10.61-4808800 (dpi@SWDD5906) (gcc version 4.9 20140514 (prerelease) (GCC) ) #1 SMP PREEMPT Sun May 3 00:30:07 KST 2015
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'samsung/zerofltebmc/zerofltebmc:5.0.2/LRX22G/G920W8VLU1AOE1:user/release-keys'
    Revision: '11'
    ABI: 'arm64'
    pid: 3054, tid: 3125, name: RenderThread  >>> ca.zettabot.trainingtool <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7fa93d4008
    x0   0000000000000001  x1   0000000000000011  x2   0000000000000001  x3   0000007f83002018
    x4   0000007fad0b5f58  x5   00000000001bcba0  x6   0000007fad0b5000  x7   0000007fad0b5f58
    x8   00000000001bcbb0  x9   0000007fa94ff3e0  x10  0000007fa9342830  x11  0000007fa4936c80
    x12  0000000000000001  x13  00000000000009ff  x14  0000007f8301a408  x15  0000007f83002018
    x16  0000007f85ad7c98  x17  0000007f85ad7ce0  x18  0000000000000001  x19  0000007fa93d4030
    x20  0000007f834878d8  x21  00000000000183f0  x22  0000000000000001  x23  0000000000000000
    x24  0000007f9589d000  x25  0000007f9532dd64  x26  0000000000001840  x27  0000007faab4fa10
    x28  0000007faab4f9e8  x29  0000007fa94ff3e0  x30  0000007fad0b9614
    sp   0000007fa9342830  pc   0000007fad0b9598  pstate 0000000060000000
    v0   00000000000000000000000043ea8000  v1   00000000000000000000000044e82000
    v2   00000000000000000000000043de0000  v3   000000000000000000000000449a8000
    v4   00000000000000000000000044e52000  v5   00000000000000000000000000000000
    v6   00000000000000000000000044978000  v7   00000000000000000000000043ea8000
    v8   00000000000000000000000000000000  v9   00000000000000000000007fa9342830
    v10  0000000000000000000000003f000000  v11  000000000000000000000000437f0000
    v12  00000000000000000000007faaa46f40  v13  00000000000000000000007fd9e18d68
    v14  00000000000000000000000000000004  v15  00000000000000000000000000000000
    v16  0000000000000000000000003f800000  v17  00000000000000000000000000000000
    v18  0000000000000000000000003f800000  v19  00000000000000000000000044e6a000
    v20  00000000000000000000000041c80000  v21  000000000000000000000000441b4000
    v22  00000000000000000000000043de0000  v23  00000000000000000000000044990000
    v24  00000000000000000000000044e6a000  v25  00000000000000000000000043f08000
    v26  00000000000000000000000044990000  v27  00000000000000000000000043e40000
    v28  00000000000000000000000044e82000  v29  00000000000000000000000043ea8000
    v30  000000000000000000000000449a8000  v31  00000000000000000000000043de0000
    fpsr 00000010  fpcr 00000000
    backtrace:
    #00 pc 0000000000033598  /system/lib64/libhwui.so
    #01 pc 000000000002e4c0  /system/lib64/libhwui.so
    #02 pc 000000000002ed78  /system/lib64/libhwui.so
    #03 pc 0000000000042ac4  /system/lib64/libhwui.so
    #04 pc 0000000000078564  /system/lib64/libhwui.so
    #05 pc 000000000007a3f0  /system/lib64/libhwui.so
    #06 pc 000000000007d470  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+124)
    #07 pc 0000000000016f2c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+188)
    #08 pc 0000000000098cd0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+96)
    #09 pc 0000000000016790  /system/lib64/libutils.so
    #10 pc 000000000001ea50  /system/lib64/libc.so (__pthread_start(void*)+52)
    #11 pc 000000000001af44  /system/lib64/libc.so (__start_thread+16)
    stack:
    0000007fa9342730  0000000000000000
    0000007fa9342738  0000000000000000
    0000007fa9342740  0000000000000000
    0000007fa9342748  0000000000000000
    0000007fa9342750  0000000000000000
    0000007fa9342758  0000000000000000
    0000007fa9342760  0000000000000000
    0000007fa9342768  0000000000000000
    0000007fa9342

**Comment by jvkessel** [comment]
Uploaded to Github to get assistance from you in investigation if this is an issue. Link to this specific commit as it's the simplest version with the least bells and whistles added to it:
jvkessel/TrainingTool@3ad1718

Update: I tried this app with an old Samsung Galaxy S3 phone and it actually runs, but the lag time is measured almost in minutes between pressing buttons and getting a response.

**Comment by jvkessel** [comment]
Update 2: I tried simplifying my theme and it seems to run a bit better on S6 (but still a bit laggy in screen transitions).  the galaxy S3 runs well.

What I removed was a transparency on a list and the radial gradient background on the "form" UIID.  These apparently caused the app to be basically unusable on a galaxy S3, and crash on a Galaxy s6.   Although I've resolved this, I think it warrants investigation why its so slow and whether this is a bug.

**Comment by codenameone** [comment]
If you are using gradients excessively you shouldn't. This is something we would remove but some people on older platforms still depend on those features (they will be gone in a future iteration of the tool). See this: https://www.codenameone.com/how-do-i---improve-application-performance-or-track-down-performance-issues.html
