### ISSUE TITLE
RFE: Add support for Android push notifications custom sounds

### ISSUE THREAD

**Issue by daognibe** [codenameone/CodenameOne#1569]
On Android devices, in order to play a custom sound upon receiving a push notification, you must put your .wav file in /res/raw folder of the apk.
At the moment CN1 build process does not allow the management of such a folder.
It would be cool for example to place the file under /native/android/res/raw/myfile.wav and after the build having it it in /res/raw/myfile.wav

**Comment by chen-fishbein** [comment]
added support for this.
place your file under /native/android/res/raw/myfile.wav and add a build hint android.pushSound=myfile
Will be available in the next server update

**Comment by davids2316** [comment]
Hello,

I tried to place the file under /native/android/res/raw/bellbox.wav and add the build hint android.pushSound = bellbox but this does not work. At the moment it is not playing any sound also, I tried modifying the vibration pattern with the build hint android.pushVibratePattern = 1000 and did not have any luck either. 

Please help me, thanks

**Comment by chen-fishbein** [comment]
It was my mistake in the comment above the file should be under /native/android/raw/myfile.wav
