### ISSUE TITLE
BigDecimal initialized wrongly

### ISSUE THREAD

**Issue by Zoran-F** [codenameone/CodenameOne#1576]
I experienced a strange behaviour when I created a simple BigDecimal. Putting a scale for it doesn't scale the number but it divides it in half.

Codename One code:
import com.codename1.util.BigDecimal;
import com.codename1.util.BigInteger;
...
...
BigDecimal amount = new BigDecimal(new BigInteger("100"),0);
Log.p(amount.toString());
amount = new BigDecimal(new BigInteger("100"),1);
Log.p(amount.toString());
amount = new BigDecimal(new BigInteger("100"),2);
Log.p(amount.toString());

Output:
[EDT] 0:0:0,0 - 100
[EDT] 0:0:0,5 - 50.0
[EDT] 0:0:0,5 - 25.00

I tried the same with pure Java, there it works as expected. (see below)
Java code:
import java.math.BigDecimal;
import java.math.BigInteger;
...
...
public static void main(String[] args) {
    BigDecimal amount = new BigDecimal(new BigInteger("100"),0);
    System.out.println(amount.toString());
    amount = new BigDecimal(new BigInteger("100"),1);
    System.out.println(amount.toString());
    amount = new BigDecimal(new BigInteger("100"),2);
    System.out.println(amount.toString());
}

Output:
100
10.0
1.00

**Comment by shannah** [comment]
The problem here is that the BigDecimal class from BouncyCastle works differently than the BigDecimal class from JDK.  Found these javadocs:

https://github.com/sake/bouncycastle-java/blob/master/src/org/bouncycastle/math/ec/SimpleBigDecimal.java#L39-L55: 

~~~~
/**
     * Constructor for <code>SimpleBigDecimal</code>. The value of the
     * constructed <code>SimpleBigDecimal</code> equals <code>bigInt / 
     * 2<sup>scale</sup></code>.
     * @param bigInt The <code>bigInt</code> value parameter.
     * @param scale The scale of the constructed <code>SimpleBigDecimal</code>.
     */
    public SimpleBigDecimal(BigInteger bigInt, int scale)
    {
        if (scale < 0)
        {
            throw new IllegalArgumentException("scale may not be negative");
        }

        this.bigInt = bigInt;
        this.scale = scale;
    }
~~~~

In the JDK BigDecimal, the scale adjusts the `bigInt` by a factor of `10^-scale` whereas the BouncyCastle implementation uses a factor of `2^-scale`.

Two possible solutions:

1. Update our Javadocs to clarify this:
2. Change our implementation to conform to JDK.

I think that updating the docs is the better approach.  Do you have a preference @codenameone ?

**Comment by shannah** [comment]
Actually.. just checked, and our javadocs already state this.  Closing this issue.

**Comment by Zoran-F** [comment]
Hi!
Thanks for looking into this, but I still don't know how to use BigDecimal
to perform decimal calculations. I don't even know how to create a
BigDecimal now, because the scale works with base 2 and changes my original
number!!!

How can I get 12.3 into BigDecimal?
Normally in Java it would be
        BigDecimal bd = new BigDecimal(new BigInteger("123"),1);

In codename One I get 61.1 which is a pretty useless number for me as I
wanted to have 12.3.
What for then there exist BigDecimal class in Codename One if I cannot use
it for financial software?

Can you please give me an example how to do this in Codename, but with
BigDecimal:
double price1=45.6;
double price2=23.3;
double sum=price1+price2;
Log.p(String.valueOf(sum));

Output:
68.9

Thx, Zoran

2015-09-14 17:59 GMT+02:00 Steve Hannah <notifications@github.com>:

**Comment by shannah** [comment]
Good point.  I'm reluctant to change the implementation in case it breaks
code.  But I'm not sure whether to:
a) Just replace this implementation with one that works in base 10.
b) Add an additional class that works in Base10  (e.g. Base10BigDecimal).
c) Add a flag in the class to specify whether it is in base 10 or base 2,
and have it work either way.
d) Do nothing, and allow developers to create their own wrappers.

What do you think @codenameone?

Steve

On Mon, Sep 14, 2015 at 10:29 AM, Zoran-F <notifications@github.com> wrote:

> Hi!
> Thanks for looking into this, but I still don't know how to use BigDecimal
> to perform decimal calculations. I don't even know how to create a
> BigDecimal now, because the scale works with base 2 and changes my original
> number!!!
>
> How can I get 12.3 into BigDecimal?
> Normally in Java it would be
> BigDecimal bd = new BigDecimal(new BigInteger("123"),1);
>
> In codename One I get 61.1 which is a pretty useless number for me as I
> wanted to have 12.3.
> What for then there exist BigDecimal class in Codename One if I cannot use
> it for financial software?
>
> Can you please give me an example how to do this in Codename, but with
> BigDecimal:
> double price1=45.6;
> double price2=23.3;
> double sum=price1+price2;
> Log.p(String.valueOf(sum));
>
> Output:
> 68.9
>
> Thx, Zoran
>
> 2015-09-14 17:59 GMT+02:00 Steve Hannah <notifications@github.com>:
>
> > Closed #1576 <https://github.com/codenameone/CodenameOne/issues/1576>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/codenameone/CodenameOne/issues/1576#event-408830841
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1576#issuecomment-140153196>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by codenameone** [comment]
I think we need a proper big decimal/integer implementation that's aligned with JavaSE as much as possible.
Maybe I made a mistake by just grabbing the bouncy castle code, unfortunately the Apache implementation seemed a bit too reliant on native.

**Comment by shannah** [comment]
TeaVM has a fairly clean implementation that I can port.  I'll do that in the morning.

**Comment by codenameone** [comment]
Sounds good. Make sure it has the same method signatures so we don't break binary compatibility in builds.

**Comment by shannah** [comment]
I pulled in the TeaVM classes mostly unchanged as package private, then I changed the implementations of BigDecimal and BigInteger to act as proxies for the TeaVM classes.  This results in some extra classes, but they are all package private and the public API is unchanged.
