### ISSUE TITLE
Push Notification - Personalization  : ENHANCEMENT 

### ISSUE THREAD

**Issue by fleetsimple** [codenameone/CodenameOne#1583]
Push Enhancement Request : Please enable push-personalization like whatsApp i.e. while receiving the push-message it shld show the sender name as in receiver phone contacts
for ex: in the receiver contact list , the name for 12345678 has been set as  "Test Name" , 
the push notification recvd from  12345678 shld be shown as  Test Name  followed by msg.
<Test Name> 
<msg >

Currently it shows sender name as Common "App name " , need to show the "sender name as in receiver's contact list"

**Comment by chen-fishbein** [comment]
We need to add another push type for this

**Comment by fleetsimple** [comment]
may i know approx. scheduled date of implementation for the additional push type to enable personalization. tks 
-sai.

**Comment by chen-fishbein** [comment]
We added push type 4 for this the message should look like this "<title>;<body>".
It will be available in the next servers update

**Comment by chen-fishbein** [comment]
git formatted the message badly, the message should look like this "title;body"

**Comment by fleetsimple** [comment]
i don't remember setting push type and title . if this a special type to be set kindly advise how to incorporate the push type and title in the client code. Thanks a lot!
