### ISSUE TITLE
KitchenSink video playback has an IOException on iOS

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1595]
This seems to be a recent regression

**Comment by codenameone** [comment]
Actually it seems to be happening in 3.1 builds too

**Comment by amiga** [comment]
Works now but onCompletion runnable is still not working in iOS.

**Comment by amiga** [comment]
Awesome, although testing reveals no difference, I will try again in a few hours to see if servers didnt update.

**Comment by shannah** [comment]
I doubt it's up on the servers yet.  It's the middle of the night in
Israel.  Give Shai a break :)

On Mon, Nov 16, 2015 at 4:18 PM, Gareth Murfin <notifications@github.com>
wrote:

> Awesome, although testing reveals no difference, I will try again in a few
> hours to see if servers didnt update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1595#issuecomment-157217863>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by amiga** [comment]
No problemo, I thought it might auto go up from github :)  These processes are mystified to us users :)

**Comment by amiga** [comment]
Verified as fixed, thank you so much guys.
