### ISSUE TITLE
Extending SideMenuBar not working with Toolbar

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#1596]
I'm trying to extend SideMenuBar to allow me placing a container at the South Layout of the Side menu, but nothing I did in my class is effective due to being overridden by Toolbar SideMenuBar as mentioned by [Chen](https://github.com/chen-fishbein) in my [post](https://groups.google.com/forum/embed/?place=forum%2Fcodenameone-discussions&showsearch=true&showpopout=true&hl=en&parenturl=https%3A%2F%2Fwww.codenameone.com%2Fdiscussion-forum.html#!searchin/codenameone-discussions/SideNavigationPanel/codenameone-discussions/ev5Xa3pLyHk/7uENCbDUEAAJ) to the forum.

**Comment by chen-fishbein** [comment]
Hi,
Just added support for this to the source.
You will need to extend the Toolbar and override createSideNavigationComponent which is now expose on the Toolbar class

**Comment by diamondobama** [comment]
Thanks Chen, Do I have to wait for the next plugin update or there's a workaround?

**Comment by chen-fishbein** [comment]
Yes, it will be on the next update.
You can take the full Toolbar and SidemenuBar sources from the repository
and include them in your project, but if it's not urgent I's suggest you to
wait for the update
