### ISSUE TITLE
Contacts Search exception after "zero search results" with FilterProxyListModel

### ISSUE THREAD

**Issue by fleetsimple** [codenameone/CodenameOne#1597]
filterproxyListmodel.install, throws null pointer exception after "ZERO Search Results"  
 
FilterProxyListModel.install(search, contactsList);

The error occurs after "Empty Search Results" 

For ex:  
=======================================================
1. Enter Keyword : "123" in search text box, the list returns 0 rows/items as  "0" match exists for "123"
2. remove the "UnMatched" keyword , the app throws null error
=======================================================
1. Enter Keyword : "ABC" in search text box, the list returns x rows/items  as there are matched contacts exists for "ABC"
2. remove the "Matched " keyword after X search results , the list shows all contacts.
=======================================================
Error Trace : 
[EDT] 0:0:0,0 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
	at java.util.Hashtable.get(Hashtable.java:363)
[EDT] 0:0:0,39 - Exception in AppName version 1.3
[EDT] 0:0:0,40 - OS ios
[EDT] 0:0:0,40 - Error java.lang.NullPointerException
[EDT] 0:0:0,40 - Current Form null
	at com.codename1.contacts.ContactsModel.getItemAt(ContactsModel.java:68)
[EDT] 0:0:0,40 - Exception: java.lang.NullPointerException - null
=======================================================

**Comment by codenameone** [comment]
This was fixed in git and should be fixed for device builds already.

**Comment by fleetsimple** [comment]
Thanks.
