### ISSUE TITLE
iOS : Contacts Sorting and "blank first entry "

### ISSUE THREAD

**Issue by fleetsimple** [codenameone/CodenameOne#1598]
Kindly assist to Fix the following : 
====================================================================
1.  Contacts is not auto-sort by displayname in iOS 
2.  Displays blank first entry in iOS

The above exists in Both (1) & (2)
1. Display.getInstance().getAllContacts(true)
2. Display.getInstance().getAllContacts(true, true, false, true, false, false)
Contacts are listed in list using ListRenderer
====================================================================
To replace empty displayname with Phone Number in contactsmodel
====================================================================
Is it possible to set 
Display Name = Phone Number when displayname is empty in contactsModel 
or 
add a new fields as Displaynamephone = phone number when display name is empty
====================================================================

**Comment by shannah** [comment]
I can't find anywhere in the docs that it says that contacts should be sorted by default in any way.  

I have changed getDisplayName() to return an alternate value.  This will be included in the next update.
https://github.com/codenameone/CodenameOne/commit/92a605ecf44733146824dac3ad971b2e9b1ee588

@codenameone What is your opinion on sorting contacts?  Should we auto-sort in the native layer, expose sorting in the API for ContactsModel, or just leave it the way it is and let people sort contacts themselves?

**Comment by codenameone** [comment]
I think @chen-fishbein made Android act that way but didn't document it.

**Comment by chen-fishbein** [comment]
Yes, on android they are sorted

**Comment by fleetsimple** [comment]
Thanks.

Contact Extraction  : 
Display.getInstance().getAllContacts(true, true, false, true, false, false); 
Display name set to : contact.getDisplayName

if i display contact.getDisplayName it will be auto-sort in both iOS and Android  and auto-replaced with phone number if contact name is empty or null ? 

Kindly confirm.
