### ISSUE TITLE
Menu missing with Android 6 Marshmallow

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1602]
My Nexus 7 tablet just upgraded to Android 6 Marshmallow. I can now reproduce a problem that a user reported from the field. The Android menu is missing from the title bar. I am also seeing crashes in shipping apps. I will file more reports as I isolate the problems.

Source code is attached to reproduce the missing menu problem. Just run the app, sometimes the menu will be there, sometimes it won't. If it is there, hit the back button and run it again.

I cannot seem to attach my source file to this stupid system.

=== Sample Source Code ===
package com.readerware.xware.test;

import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.List;
import com.codename1.ui.list.DefaultListModel;
import com.codename1.ui.list.ListModel;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.io.IOException;

public class TWMain {

    private Form current;

    public void init(Object context) {
        try {
            Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }

        MyForm form = new MyForm();

        form.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

    private class MyForm    extends     Form
                            implements  ActionListener {
        public MyForm() {
            super("CodenameOne Test");
            getContentPane().setLayout(new BorderLayout());

            Command backCommand = new Command("Home", 1);
            setBackCommand(backCommand);

            Command searchCommand = new Command("Search", 2);
            addCommand(searchCommand, 0);

            Command command2 = new Command("Menu 2", 3);
            addCommand(command2, 1);

            Command command3 = new Command("Menu 3", 4);
            addCommand(command3, 2);

            Command command4 = new Command("Menu 4", 5);
            addCommand(command4, 3);

            Command command5 = new Command("Menu 5", 6);
            addCommand(command5, 4);

            addCommandListener(this);

            setLayout(new BorderLayout());
            setScrollable(false);

            ListModel listModel = new DefaultListModel();

            for (int i=0; i<100; i++) {
                listModel.addItem("Line " + (i + 1));
            }

            List list = new List();
            list.setScrollVisible(false);
            list.setModel(listModel);
            addComponent(BorderLayout.CENTER, list);
        }

        public void actionPerformed(ActionEvent actionEvent) {
            Command command = actionEvent.getCommand();

            if (command != null) {
                int cmd = command.getId();

                switch (cmd) {
                  case 1:
                    stop();
                    Display.getInstance().exitApplication();
                    return;

                  default:
                    return;
                }
            }
        }
    }
}

**Comment by chen-fishbein** [comment]
fixed, thanks.
Will be available in the next server update
