### ISSUE TITLE
Browser component is not working in .exe where as working in .jar

### ISSUE THREAD

**Issue by akash-more4apps** [codenameone/CodenameOne#1606]
Hi I would be keen if the Browser Component works in Windows Desktop build.

At the moment I installed windows desktop build on Windows 7 PC but it didn't reach to login screen, that is requirement of my project to use that web login page.

The login form (having browser component) is not able to be opened and I am getting NO error / exception ! (I tested by some alerts and writing log into .txt file).

Though I am able to open forms, able to click on buttons and navigation and all before login screen.

Any idea about Browser Component supports in Desktop Windows Build , please ?

Thanks.

**Comment by akash-more4apps** [comment]
Shai:
Hi,
it should work as far as I know. It technically just installs a JAR and JRE somewhere and that JRE should include FX which should allow for the browser component.
If you run the jar from command line does it work? Does it print something?
Is this a recent regression? We changed something in the JavaSEPort to workaround a designer issue but it should have no affect on the desktop build.

Me:
Thanks, that **exe didnt work but .jar worked with browser component**.

**Comment by codenameone** [comment]
BTW did you try the Mac desktop builds? Does this work on the Mac?

**Comment by akash-more4apps** [comment]
No, unfortunately I haven't access to Mac at the moment..

**Comment by codenameone** [comment]
This should be fixed now in current builds. I verified the fix works on Mac OS X (which also displayed the problem) and applied the fix for the Windows desktop build.
