### ISSUE TITLE
Support new native fonts API in JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1607]
The native: scheme recently committed to git https://github.com/codenameone/CodenameOne/commit/2634fc09aff2d3354a6c3faed02d7a05bf9615cd 
Uses native: hardcoded values to provide font objects. This should map to a set of CSS font styles (or something similar) that give reasonable platform defaults.

**Comment by shannah** [comment]
This was implemented in this commit: https://github.com/shannah/cn1-teavm-port/commit/ef4226291ee7111a7be48898b752122809ec8e0c
