### ISSUE TITLE
Opening a PDF or any file in the browser component and display thru Display.execute

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#1616]
i had tried in android mobiles, it opens a blank form and doesnt work. however i went through google group and found out that if i set the docs.google.com/gview?embedded=true&url=http://… as my url it works... and so is my case as well

code:
 WebBrowser pdfview = new WebBrowser();
                pdfview.setURL("http://www.codenameone.com/files/developer-guide.pdf");  
//this link downloads the pdf file in browser but does nothing in codename one browser...
                f.addComponent(pdfview);

**Comment by codenameone** [comment]
This should be covered by a fix for #1651

**Comment by bbeckk** [comment]
i have updated to 3.3.4 but it still is not working just as before

**Comment by codenameone** [comment]
We can't/won't change that use case as it relates to the native browser peer over which we don't have control. #1651 provides the official way to support viewing a PDF file from Codename One.
