### ISSUE TITLE
Builds in the website should auto-clear to match their expiry time

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1617]
Right now old builds are kept in the view even after reload despite the server physically expiring them. E.g. lifespan of an AWS build is less than 3 days. 

The JavaScript code in the website should remove these old builds implicitly to avoid confusion.

**Comment by shannah** [comment]
I set it up to strip out anything older than 4 days old.  I left a buffer in case of time-zone etc..  Good enough?
