### ISSUE TITLE
Deprecate codescanner and remove it from Codename One into a cn1lib

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1618]
The QR code functionality is problematic in many ports e.g. the iOS port makes it very difficult to work with bitcode etc. because of the binary nature of the zlib library. This should have been a cn1lib to begin with but we didn't have those when we added that feature.

**Comment by shannah** [comment]
I have ported all the codescanning stuff over to https://github.com/shannah/cn1-codescan

**Comment by codenameone** [comment]
Thanks, moved it into the codenameone user for easier discoverability https://github.com/codenameone/cn1-codescan
