### ISSUE TITLE
AutoCompleteTextField component works only at first tab in tabs component but not for second tab and respectively next tabs.

### ISSUE THREAD

**Issue by santoshko** [codenameone/CodenameOne#1627]
Example:
Tabs t = new Tabs(); 
ListModel<String> list = new DefaultListModel<String>(); 
list.addItem("santosh"); 
list.addItem("sagar"); 
list.addItem("Afaque"); 
list.addItem("Akash"); 
list.addItem("sushma"); 
list.addItem("akil"); 
list.addItem("srikanth"); 
AutoCompleteTextField actxt = new AutoCompleteTextField(list);
AutoCompleteTextField at = new AutoCompleteTextField(new String[]{"Common", "Code", "Codename One", "Correct", "Correlation", "Co-location", "Corporate"});
t.addTab("AC", actxt); 
t.addTab("BC", at); 
t.setSelectedIndex(0); 
addComponent(t);

**Comment by chen-fishbein** [comment]
fixed, thanks!
