### ISSUE TITLE
Current shape and most newer graphics API's aren't implemented on iOS mutable images

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1629]
This creates a situation where some transitions or effects with a chart on the page just fail to show the chart. This also prevents use cases like this: http://stackoverflow.com/questions/34626617/sharing-a-chart

**Comment by shannah** [comment]
fc32f61 has charts working on mutable images for the most part.  transforms aren't supported yet so some text labels along the y-axis show horizontally instead of vertically.  Working on adding that support today.
