### ISSUE TITLE
Bug in Netbeans plugin build hints

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1634]
In the build hints section of the project properties window, the build hint keys don't save edits after being saved once.  I was still able to edit them through the codename.properties file.

I wasn't sure whether to file the issue here or with Netbeans, so I filed here, because I've never run into it with other Netbeans projects.

**Comment by codenameone** [comment]
I'm assuming you are trying to change a variable like `ios.includePush` etc.

Search for it in the UI for the appropriate platform first as that overrides manually entered settings.

**Comment by jegesh** [comment]
The variable was android.xpermissions.  I had originally typed in android.xpermission by accident, and was unable to save my edit until I changed it in the codenameone_settings.properties file.  I think this is a bug, the build hint keys are editable, but don't save.

**Comment by codenameone** [comment]
After finishing the editing you need to click elsewhere or press enter and not directly on OK. That's a JTable oddity in Swing.

**Comment by jegesh** [comment]
Ok, thanks. I'll keep that in mind for the future.
