### ISSUE TITLE
Android dialogs broken in latest build

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1638]
![screenshot_2016-01-13-14-13-30](https://cloud.githubusercontent.com/assets/14006739/12358893/5935132a-bb64-11e5-9719-d118a4d3f463.png)
![screenshot_2016-01-13-14-12-55](https://cloud.githubusercontent.com/assets/14006739/12358902/67cb647a-bb64-11e5-8ea0-bfedcedef2ea.png)

The first screenshot, the books screen shot, shows one of my dialogs as it has always looked.

The second screenshot, the music screenshot, displays the same dialog in a new build. The dialog is not opaque, the background form is partially visible. The titlebar and many fields now have a gray background.

Same code for both dialogs.

I have tried to come up with a test case to reproduce this. The following code does exhibit many of the same problems but for some unknown reason the background color is a much lighter gray. You have to move the screen around to see that many fields do have a background color. Hopefully if you can fix this it will fix the problems in my shipping app too.

package com.readerware.xware.test;

import com.codename1.components.InfiniteProgress;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.List;
import com.codename1.ui.layouts.GridBagConstraints;
import com.codename1.ui.layouts.GridBagLayout;
import com.codename1.ui.layouts.Insets;
import com.codename1.ui.list.DefaultListModel;
import com.codename1.ui.list.ListModel;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.animations.CommonTransitions;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.util.Resources;
import java.io.IOException;

public class TWMain {

    private Form current;
    private Form form;
    protected Toolbar _myToolbar;

    public void init(Object context) {
        try {
            Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }

        form = new MyForm();

        form.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

    private class MyForm    extends     Form
                            implements  ActionListener {
        public MyForm() {
            super("CodenameOne Test");
            getContentPane().setLayout(new BorderLayout());

            setTintColor(0x80808080);

            Command backCommand = new Command("Home", 1);
            setBackCommand(backCommand);

            _myToolbar = new Toolbar();
            setToolBar(_myToolbar);
            _myToolbar.setTitle("My Test App");

            Command command1 = new Command("Menu 1", 2);
            _myToolbar.addCommandToOverflowMenu(command1);

            Command command2 = new Command("Menu 2", 3);
            _myToolbar.addCommandToOverflowMenu(command2);

            Command command3 = new Command("Menu 3", 4);
            _myToolbar.addCommandToOverflowMenu(command3);

            Command command4 = new Command("Menu 4", 5);
            _myToolbar.addCommandToOverflowMenu(command4);

            Command command5 = new Command("Menu 5", 6);
            _myToolbar.addCommandToOverflowMenu(command5);

            addCommandListener(this);

            setLayout(new BorderLayout());
            setScrollable(false);

            ListModel listModel = new DefaultListModel();

            for (int i=0; i<100; i++) {
                listModel.addItem("Line " + (i + 1));
            }

            List list = new List();
            list.setScrollVisible(false);
            list.setModel(listModel);
            addComponent(BorderLayout.CENTER, list);
        }

        public void actionPerformed(ActionEvent actionEvent) {
            Command command = actionEvent.getCommand();

            if (command != null) {
                int cmd = command.getId();

                switch (cmd) {
                  case 1:
                    stop();
                    Display.getInstance().exitApplication();
                    return;

                  case 2:
                    ConnectForm connectForm = new ConnectForm();
                    connectForm.show();
                    break;

                  default:
                    break;
                }
            }
        }
    }

    private class ConnectForm   extends    Dialog {

        private Command                         _backCommand;
        private TextField                       _hostField;
        private TextField                       _portField;
        private InfiniteProgress                _progress;
        private Label                           _statusMessage;
        private Label                           _completeMessage;
        private Command                         _connectCommand;
        private Button                          _connectButton;
        private Command                         _cancelCommand;
        private Button                          _cancelButton;
        private Command                         _doneCommand;

        /**
          *  Display a connection dialog and then process the request.
          */
        public ConnectForm() {
            super("Connect to Readerware");
            setName("ConnectForm");
            setAutoDispose(false);

            _backCommand = new Command("List");
            setBackCommand(_backCommand);

            GridBagLayout gbl = new GridBagLayout();
            GridBagConstraints gbc = new GridBagConstraints();
            setLayout(gbl);

            int y = 0;
            int x = 0;
            TextArea intro = new TextArea("To connect to Readerware 3 (Music) enter the host name OR the IP address of your computer. The default port is 9030.");
            intro.setUIID("Label");
            intro.setEditable(false);
            intro.setRows(3);
            intro.setGrowByContent(false);
            intro.setScrollVisible(false);
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.BOTH;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(5, 10, 0, 10);
            gbl.setConstraints(intro, gbc);
            addComponent(intro);

            y++;
            x = 0;

            Label host = new Label("Host ir IP:");
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = 1;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.BOTH;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 10, 0);
            gbl.setConstraints(host, gbc);
            addComponent(host);
            x++;

            _hostField = new TextField();
            _hostField.setHint("Host name or IP address");
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.1;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 10, 10);
            gbl.setConstraints(_hostField, gbc);
            addComponent(_hostField);

            y++;
            x = 0;

            Label port = new Label("Port:");
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = 1;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.BOTH;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 0, 0);
            gbl.setConstraints(port, gbc);
            addComponent(port);
            x++;

            _portField = new TextField();
            _portField.setHint("Port number");
            _portField.setInputMode("123");
            _portField.setConstraint(TextArea.NUMERIC);
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.1;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 0, 10);
            gbl.setConstraints(_portField, gbc);
            addComponent(_portField);

            y++;
            x = 0;
            _progress = new InfiniteProgress();
            _progress.setVisible(false);

            /*
             * Put in container, we want this component to be invisible initially.
             * If we add it directly when it is hidden, no space is allocated
             * and it is never shown.
             */
            Container progress = new Container(new FlowLayout());
            progress.addComponent(_progress);
            gbc.anchor        = GridBagConstraints.NORTH;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.NONE;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 0, 10);
            gbl.setConstraints(progress, gbc);
            addComponent(progress);

            y++;
            x = 0;
            _statusMessage = new Label(" ");
            _statusMessage.setPreferredW(500);
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 0, 10);
            gbl.setConstraints(_statusMessage, gbc);
            addComponent(_statusMessage);

            y++;
            x = 0;
            _completeMessage = new Label(" ");
            _completeMessage.setPreferredW(500);

            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 0, 10);
            gbl.setConstraints(_completeMessage, gbc);
            addComponent(_completeMessage);

            y++;
            x = 0;
            Container buttons = new Container();
            buttons.setLayout(new FlowLayout(Component.CENTER));
            _cancelCommand = new Command("Cancel");
            _cancelButton = new Button(_cancelCommand);
            buttons.addComponent(_cancelButton);
            _connectCommand = new Command("Connect");
            _doneCommand = new Command("Done");
            _connectButton = new Button(_connectCommand);
            buttons.addComponent(_connectButton);

            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 10, 10);
            gbl.setConstraints(buttons, gbc);
            addComponent(buttons);
        }

        public void actionCommand(Command command) {
            if (command == _backCommand) {
                dispose();
                return;
            }
        }
    }
}

**Comment by mwarnett** [comment]
Forget to mention when running the test app, select the first system menu item to display the dialog.

**Comment by codenameone** [comment]
Thanks, I saw a big mistake in restoring alpha to its original value after fill rect we'll try to have this in the servers over the weekend.

**Comment by codenameone** [comment]
The servers are up to date and I tried this which didn't fix the issue. I then tried this against an older version and the behavior is identical due to the default background color in Android being f0f0f0 instead of ffffff.

I did make a fix to something that might fix it in your actual app. However, this test case doesn't seem to reproduce that issue. So please check if the problem persists in the actual app and if so we'll need some other way to reproduce this.

**Comment by mwarnett** [comment]
Didn't really help. Latest screenshot attached. The entry fields now have a white background but everything else is the same. When I rotated the device, the entry field background went back to gray.

I will try working on another test case.
![screenshot_2016-01-16-09-30-45](https://cloud.githubusercontent.com/assets/14006739/12373634/bc121ada-bc34-11e5-93bc-c0478db1109a.png)

**Comment by mwarnett** [comment]
Could someone reopen this issue, it is not fixed.

I have tried two ways to come up with sample code to reproduce this.

I took the form class and put it in a generic shell app to try and reproduce the problem. I added more and more startup code from my app but could never reproduce the problem apart from the small color variation which is still a problem and definitely not present in my shipping app.

Today I tried gutting my full app to try and get it to a point where it worked. I removed all code related to the display and set it up so that this form was called right away. It always failed, I was never able to get it to work.

Don't know what to try next.

Could my theme,res file be an issue? This is an old app so the theme.res file I am using has been around a long time.

**Comment by codenameone** [comment]
Yes, this could be related to the theme.res file.

**Comment by mwarnett** [comment]
I created a new native theme and accessed it via name in my init method, did not help unfortunately.

i created a new FlatBlue theme, the dialog looks fully painted but still has a gray transparent background and gray text making it unreadable. Never used the themes before so not sure how they should look or if this is the same problem.

I can't recreate the theme.res file completely as I have a lot of images and localized strings in it.

![screenshot_2016-01-16-15-56-06](https://cloud.githubusercontent.com/assets/14006739/12375164/97db2522-bc6a-11e5-9eaa-ce1ded9e0a91.png)

Not sue what to try next

**Comment by mwarnett** [comment]
I changed ConnectForm to subclass Form instead of Dialog and it paints correctly. Does that suggest anything to you?

Not really what I want to do but may enable me to work around this.

**Comment by mwarnett** [comment]
Back to the dialog and i checked output with the Dalvik Debug Monitor. Attached trace shows the app running, then I bring up the dialog. there is an endless stream of SurfaceView messages, same two messages repeated over and over. As soon as I cancel the dialog, the messages stop.


[log.txt](https://github.com/codenameone/CodenameOne/files/93161/log.txt)

**Comment by codenameone** [comment]
If you take the res file from your actual app and stick it into the test case does it reproduce the issue?
If so just email us the res file.

I'm not really sure why the log shows that, it looks like an image problem if that indicates something to you.

**Comment by mwarnett** [comment]
Using the res file with the test app did not make a difference, so I don't think it is te .res file.

There are no images on the dialog

**Comment by mwarnett** [comment]
I did a build with CodenameOne 3.1, everything worked fine.

I did a build with CodenameOne 3.2 and the dialog problem was back.

So that is the timeframe. I also noticed Android UI changes for example in 3.1 the Toolbar system menu was larger, in 3.2 the size of the system menu was a lot smaller, too small I think.

**Comment by codenameone** [comment]
So we might have been looking at this all wrong then. I assumed the latest changes were the culprit but if this was from something we did 3-6 months ago it might be pretty hard to track.

Just to be sure that this isn't from the latest changes try including:

```java
Display.getInstance().setProperty("platformHint.compatPaintMode", "true");
```

**Comment by mwarnett** [comment]
My last Android release was on November 19 2015. Everything was fine then obviously but I haven't been working on the apps since the release.

Adding that line to init mdid not help unfortunately.

**Comment by codenameone** [comment]
Back then did you build against 3.1 or did you use the trunk?
Do you have any special build hints, e.g. async paint etc?

**Comment by mwarnett** [comment]
I built from the latest version. This release was to correct some problems that cropped up with Android Marshmallow so I needed the latest at that point. The actual build date was 11/18.

These are my Android build hints:

android.asyncPaint=false

Actually that is it, the others are just xpermissions, debug etc.

**Comment by codenameone** [comment]
That might be the source of the problem. Can you set it to true which should be the default? 
I'll try to reproduce the issue with the asyncPaint false flag.

**Comment by mwarnett** [comment]
Seeing as how you mention asyncPaint, I changed it to true and rebuilt.

Problem solved.

It has been in there a long time, I cannot tell you now why I chose it. probably had some painting issues way back that it fixed.

**Comment by codenameone** [comment]
I was just about to write that I was able to reproduce the issue with `asyncPaint=false`. I'm leaving the issue for now since I want to understand why that pipeline doesn't work.

**Comment by mwarnett** [comment]
I just ran the same test here. I added asyncPaint=false to my test app and it now reproduces the problem. 

I am good I know how to fix the problem now. Thanks for all your help.

**Comment by codenameone** [comment]
OK, just fixed this for the other pipeline too. Thanks!
