### ISSUE TITLE
Toolbar broken in simulator

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1639]
The Toolbar does not work in the simulator when using Android skins, android.skin, nexus.skin, xoom.skin etc.

No system menu is displayed in the toolbar. The device menu button does nothing. 

So no way to access system menu functionality in application.

You can use the code submitted with problem number 1638 to reproduce this problem.

**Comment by codenameone** [comment]
The overflow button had an issue with a missing image for that. @chen-fishbein fixed it in a commit a while ago so it will work in the next simulator update.
