### ISSUE TITLE
setText from non-EDT thread results in corrupt TextArea

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1644]
If I call "setText" and then "setScrollY" from a non-EDT thread, 
the text displayed becomes corrupt, because it's all displayed on
one line.

I narrowed down the culprit to this bit in TextArea.java

    private void initRowString() {
        if (!Display.getInstance().isEdt()) {
            if(rowStrings == null) {
                rowStrings = new ArrayList();
                rowStrings.add(getText());
                return;
            }
        }
     ....
    }

Whatever the alternate path the !isEdt case is intended to do, it breaks the redisplay.
Just removing the offending clause seems to fix the problem, but it was presumably 
there for a reason.

**Comment by codenameone** [comment]
We don't support non-EDT access. This class has a long history of us trying to make it safe for non-EDT access and failing, there is no way to do it without a huge performance overhead.

This code is there so you won't get an exception in an odd place later on that doesn't include much of an indication.

**Comment by ddyer0** [comment]
Is it setText, or setScrollY or both, (and how many other public apis) that are on the secret don't use list?

**Comment by codenameone** [comment]
As I said, no API supports off EDT access unless explicitly stated otherwise.

**Comment by ddyer0** [comment]
It seems like a poor policy to have hundreds of openly callable APIs, and in you back pocket say "we told you not to do that" if anything goes wrong.  At least in the debug/development environment, all these APIs ought to be booby trapped to throw an error if used from unsupported threads.   discuss.

**Comment by codenameone** [comment]
There are 3 approaches to GUI API development:

- Thread safe - no one does that.
- Hard fail - Some do that but most don't (notably neither Android nor iOS do that).
- Soft fail - it just won't work "sometimes".

We, Android, iOS, Swing etc. all use the soft fail approach on invalid off EDT access. 

We also provide an edt violation detector tool which you explicitly chose to ignore **DESPITE** my warning you in the forum. Notice that none of the other API's mentioned even provide that level of tooling out of the box... They just fail oddly.

Hard fail is problematic in several senses but most of all its bad for performance as you need to constantly check if's in the most critical section of the code.

**Comment by ddyer0** [comment]
I'm obviously in the minority, but IMO "soft fail" should be thought of as a path to guarantee unreliable applications.

**Comment by codenameone** [comment]
I actually agree with that. 

Normally we try to fail fast, but since this would incur a performance overhead and goes against the common standard its probably not a direction we'll take.

**Comment by ddyer0** [comment]
There are a consequences to this that ought to give you pause.  Customers who are more reluctant that I am to dive into the sources will take behavior like that at the beginning of this thread as evidence that your code is buggy and unreliable.  Bad for you.  Every customer will independently spent time encountering, investigating, working around things like this.  Bad for them, and also bad for you.

These entry points into EDT-land (such as setScrollY) are not in any critical path, or at least 
if they are there's already a serious performance problem.  Adding tripwires in these cases
would not even be measurable in the overall performance.

**Comment by codenameone** [comment]
Nope. Most customers never leave the EDT.

**Comment by ddyer0** [comment]
So what's your position on making it fail softer (or less frequently), verses letting sleeping dogs lie,
verses adding exclusions to make bad behavior impossible?   #1 or #3 definitely are better than #2 IMO.

**Comment by codenameone** [comment]
That is softer. The alternative is crashing.

**Comment by ddyer0** [comment]
Making a few methods synchronized mitigates the problem for setText.  Will you accept that?

**Comment by shannah** [comment]
I would say that any attempt to introduce multi-threading or multi-thread safety into the UI is misguided.    Synchronization has a performance cost.  And then you can never be sure which things are safe off the EDT and which things aren't.  Currently it's simple:  Don't access/modify the UI off the EDT.  Period.

**Comment by ddyer0** [comment]
So your answer is "leave it broken" rather than "make is better but not perfect" or "make it impossible to try"?   I just want a clear statement.

**Comment by shannah** [comment]
I don't think it's broken.  Every modern UI kit works this way.  Try setting text in a Swing TextComponent off the EDT.  You will get strange things happening.  Try doing it on iOS or Android native UI.  It will cause strange results.

People have been researching this for years.  The general consensus is:  keep it single threaded.
If you want to create your own thread-safe wrappers you're free to do that.   There is a performance penalty.  Don't make everyone pay a penalty because you want to go against the best practice.

**Comment by ddyer0** [comment]
By my definition, anything that gets a nullpointerexception with probability between zero and 1
is broken by definition.   But if that's the way you're happiest with it, I'll do my own wrappers that
no one else will benefit from.

**Comment by shannah** [comment]
If the car manual says to use brake fluid in the brake lines, but you insist on using canola oil, then the results are undefined.  Might work, might not.  Doesn't mean the car is broken.  It just means that the user didn't follow directions.

If you follow directions on the TextArea (only access on EDT), you won't get a nullpointer exception ever.  If you refuse to follow directions, then the results are undefined.  Doesn't mean it's broken.

**Comment by ddyer0** [comment]
IWhen they switched to unleaded fuel, the also made the nozzles smaller so it was impossible to put leaded fuel in the tank by accident.
-- but enough of this.

**Comment by codenameone** [comment]
We used to have a synchronized statement there. We no longer do.

Synchronized is REALLY expensive in AOT compilation so this would mean that the people who do use the API correctly will pay a performance penalty for a slightly less broken behavior. Notice that it didn't come close to solving the issue or even seriously mitigating it. It just made it slightly harder to reproduce which IMO is WAY worse!
