### ISSUE TITLE
fillRect() with alpha parameter does not position correctly

### ISSUE THREAD

**Issue by timovandeput** [codenameone/CodenameOne#1648]
When using fillRect with an alpha parameter, the position of the rectangle appears to be offset from the screen instead of the component. (The rectangle stays at a fixed position when the form scrolls into view.)

This can be demonstrated by positioning a component in the middle of the form, and filling the same rectangle with and without alpha in a custom paint() handler.

The offset is actually different on the simulator, iOS and on Android.

**Comment by codenameone** [comment]
Can you provide a test case?

Some additional details on how the offset differs between platforms?

We use fill rect with alpha quite a bit so this would be surprising.
