### ISSUE TITLE
TextField does not apply constraints on Android

### ISSUE THREAD

**Issue by timovandeput** [codenameone/CodenameOne#1649]
I added constraints to a text field using `textField.setConstraint(TextField.NON_PREDICTIVE | TextField.INITIAL_CAPS_WORD);`

On iOS this automatically toggles the shift button when entering text, but on Android this appears to be broken.

**Comment by codenameone** [comment]
I think there is a bit of a conceptual problem with the code within InPlaceEditView.java.
We need to remove the usage of the `mInputTypeMap` and replace it with if statements since the value of the constraint can be or'd together.
