### ISSUE TITLE
Fix file Display.execute for iOS

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1651]
Currently the Display.execute() call works with file: URL's on Android but fails in iOS for common files such as images or PDF's. This should be fixed in the API implementation or thru a new portable API.

**Comment by shyamsth** [comment]
is this issue solved ?

**Comment by codenameone** [comment]
It's fixed now. Will be up in the Friday release.

**Comment by shyamsth** [comment]
hi
Thanks alot
I am most awaiting for it.

Kindly Regards
Shyam Tha (Shrestha)
gshyamktha@gmail.com

+9779841822318(primary)
+9779803465499(secondary)
