### ISSUE TITLE
Animation flickers on Android device

### ISSUE THREAD

**Issue by jjvanhorssen** [codenameone/CodenameOne#1654]
In my app I have an Android animation issue that can be reproduced in your Solitaire demo.

Test case: Solitaire demo, see the deal-from-deck and autoplay (2nd move-in-a-row and higher) animations. When a card starts moving, the destination location usually flashes.

It looks like the card is very briefly (one frame?) shown at the destination location and then it starts moving from the source location to the destination, as it should.

CN1 plugin 3.3.1, libs 2016-01-21, Android 5.1.1 (Nexus 7)

**Comment by shannah** [comment]
It is possible that this is fixed with the shape clip enhancements.  Assigning to myself to test.
