### ISSUE TITLE
ActionEvent.getComponent() return Button instance instead of MultiButton one

### ISSUE THREAD

**Issue by JrmyDev** [codenameone/CodenameOne#1655]
In this example : 
```
MultiButton mb = new MultiButton();
mb.addActionListener(new ActionListener(){
   @Override
    public void actionPerformed(ActionEvent evt){
        Component c = evt.getComponent();
   }
});
```
The Component c is an instance of Button (the emblem button enclosing in the mb MultiButton) instead of the mb instance.
If I would like to retrieve the MultiButton mb that I have triggered, I have to do that : 
`MultiButton theMButtonTriggered = evt.getComponent().getParent().getParent();`

**Comment by codenameone** [comment]
The fix was made by adding a new getter method `getActualComponent`. We changed this behavior in the past for the `getComponent()`` method and it had a cascading effect that caused a lot of issues.
