### ISSUE TITLE
Black screen after new hint for Android

### ISSUE THREAD

**Issue by AliSayed** [codenameone/CodenameOne#1656]
I get black screen on Android device if used the new paint hint

Display.getInstance().setProperty("platformHint.legacyPaint", "false");

I've tried it on Sample "PropertyCross"

I've tested using HTC 516 running Android 4.3

**Comment by codenameone** [comment]
Do you get it all the time or just an occasional flicker as you scroll?

**Comment by diamondobama** [comment]
On my side, I got this all the time...without scrolling.

The screen wasn't actually blacked out, but some texts turn black including all my fonticons that were originally white.

**Comment by codenameone** [comment]
@diamondobama on which devices/OS versions?

**Comment by amiga** [comment]
could it be related to this fix, and you havent defined selected states for
textfields?

https://github.com/codenameone/CodenameOne/commit/
e709a5c52014cd8503cc5a082d6f55ebb6cefba2

On 29 January 2016 at 11:43, codenameone <notifications@github.com> wrote:

> @diamondobama <https://github.com/diamondobama> on which devices/OS
> versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1656#issuecomment-176556352>
> .
>



-- 
Gareth Murfin
(Android Freelancer - www.garethmurfin.co.uk)

**Comment by diamondobama** [comment]
Samsung s5 mini, Android 5.1 Lollilop

**Comment by codenameone** [comment]
Did you use the FontImage class or did you customize a label to get that?

Can you submit a test case for it? It sounds like a somewhat different issue from the one mentioned here.

**Comment by codenameone** [comment]
@AliSayed can you see if you have any output in DDMS such as errors, exceptions/warnings?

**Comment by diamondobama** [comment]
Here is a log from my App
[log.txt](https://github.com/codenameone/CodenameOne/files/109470/log.txt)

**Comment by AliSayed** [comment]
sample PropertyCross DDMS
[PropertyCross.txt](https://github.com/codenameone/CodenameOne/files/109682/PropertyCross.txt)

**Comment by codenameone** [comment]
Seems to be the same issue as reported by @diamondobama this is fixed for the next server update sometime later today. Thanks!

**Comment by AliSayed** [comment]
can you update me when it updated to re-test

**Comment by codenameone** [comment]
It was up 2 days ago. If you still see an issue please see if you have any additional output in DDMS?

**Comment by AliSayed** [comment]
[log.txt](https://github.com/codenameone/CodenameOne/files/112010/log.txt)
check this built today

**Comment by codenameone** [comment]
Odd. Maybe the update failed. Can you try again? I updated just now.

**Comment by AliSayed** [comment]
PropertyCross works now ,but Check this crash I think its not the same , it's a different app 
[log.txt](https://github.com/codenameone/CodenameOne/files/112282/log.txt)

**Comment by codenameone** [comment]
I just pushed a fix for this. Can you see if it resolves that issue?

**Comment by AliSayed** [comment]
it fixed

**Comment by codenameone** [comment]
Great, thanks!

**Comment by AliSayed** [comment]
bug appeared again today
[log.txt](https://github.com/codenameone/CodenameOne/files/126883/log.txt)

**Comment by codenameone** [comment]
Thanks for the headsup. This was due to a wrong configuration on our end. This should be fixed now.

**Comment by AliSayed** [comment]
the black scree is fixed , but I get this exception sometimes when scrollling
[log.txt](https://github.com/codenameone/CodenameOne/files/129809/log.txt)

**Comment by codenameone** [comment]
That is odd. I've made a change which should hopefully fix that exception.
