### ISSUE TITLE
ComboBox does not fire ActionListener

### ISSUE THREAD

**Issue by jazter** [codenameone/CodenameOne#1657]
I am experimenting an issue with the ComboBox, when I press an option, drag outside the list and then click outside of the ComboBox, the ComboBox shows the option selected but the actionPerformed was not fired. I can reproduce this behavior in the simulator and android.

This behavior also happens when you select an option and rotate the device.
![captura de pantalla 2016-01-27 14 47 42](https://cloud.githubusercontent.com/assets/1778899/12656408/bcae7c52-c5c3-11e5-8728-ce811305058b.png)
![captura de pantalla 2016-01-27 14 47 34](https://cloud.githubusercontent.com/assets/1778899/12656407/bcabf7f2-c5c3-11e5-95bf-757b1bacd3f9.png)

**Comment by codenameone** [comment]
We fixed this in git by restoring the original value of the combo box when clicking outside of it or rotating the device.
