### ISSUE TITLE
isNativeBrowserSupported() invoked only in WebComponent constructor

### ISSUE THREAD

**Issue by JrmyDev** [codenameone/CodenameOne#1659]
```
` /**
     * This constructor will work as expected when a browser component is supported, see isNativeBrowserSupported()
     */
    public BrowserComponent() {
        setUIID("BrowserComponent");
        PeerComponent c = Display.getInstance().getImplementation().createBrowserComponent(this);
        setLayout(new BorderLayout());
        addComponent(BorderLayout.CENTER, c);
        internal = c;
        Style s = internal.getUnselectedStyle();
        s.setPadding(0, 0, 0, 0);
        s.setMargin(0, 0, 0, 0);
        s.setBgTransparency(255);
    }`
```
There is no invocation of `isNativeBrowserSupported()` method in BrowserComponent constructor.

So, when I instanciate a BrowserComponent and build for iOS, I obtain this error log : 

```
java.lang.NullPointerException
           at com.codename1.impl.javase.JavaSEPort.createBrowserComponent(JavaSEPort.java:6832)
```
etc...

**Comment by JrmyDev** [comment]
(I know that WebBrowser should be used just in case the platform doesn't support BrowserComponent, but in my case, i'm pretty sure that it's ok since I build for iOS and Android --> maybe the solution is to have a second BrowserComponent constructor). Thanks.

**Comment by codenameone** [comment]
That's problematic. The main issue here is the screenshot process see https://www.codenameone.com/manual/appendix-ios.html#_the_ios_screenshot_splash_screen_process

If you use a browser component in the first form of a Codename One application it will look horrible on iOS as you would be faced with the way the web UI is rendered on the desktop and not with the way it is rendered on the device. For a web application you must use a splash screen.
