### ISSUE TITLE
android won't issue a GET request (always uses POST)

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1665]
In android builds, my http code, which for historical reasons uses raw openConnection rather than the more structured "addArgument" paradigm, would not issue a GET request, despite explicitly calling setRequestMethod("GET").  It works fine in the simulator.

I haven't completely analyzed the logic, but it appears that httpRequestMethod is effectively ignored in the android VM, and instead the boolean "isPost" determines the kind of request.  

I find that this small change above the VM level fixes the problem.

    /**
     * Sets the http method for the request
     * @param httpMethod the http method string
     */
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
        // in the android branch, httpMethod is ignored in favor of the isPost flag.
        // this at least keeps them in sync.
        setPost("POST".equals(httpMethod));
    } 

However, I don't believe this completely fixes all the problems implied by ignoring httpRequestMethod.  In particular, it is probably still impossible to get the android
VM to issue any of the more esoteric request types, such as "HEAD".

**Comment by codenameone** [comment]
This will fail. Arguments need to be placed in the hash differently for get/post so this might occur too late. There are other cases such as PUT and case insensitivity which you also ignore.

**Comment by ddyer0** [comment]
As stated, the hash is not being used, only raw openconnection.
It is obviously incorrect for setHttpMethod to have no effect.

**Comment by codenameone** [comment]
You should have called setPost(false) in your own code.

That change you suggested would fail badly if you added arguments when you try to make a connection.

**Comment by ddyer0** [comment]
I did try to express my appreciation for the complexities in my original complaint, that's why i proposed a direction but didn't try to push a patch.  I am using setpost as a fix in my own code, but it remains
the case that setHttpMethod does not work.

It also occurs to me that "get" is the normal default.

**Comment by codenameone** [comment]
https://www.codenameone.com/javadoc/com/codename1/io/ConnectionRequest.html#setPost-boolean-
