### ISSUE TITLE
getListCellRendererComponent bugs after update 3.3

### ISSUE THREAD

**Issue by Manukaki** [codenameone/CodenameOne#1669]
After send the android build for this new 3.3 update, the ListCellRenderer, isSelected always return true, this made all items in the list look "highlighted".

The code is working properly before this upgrade.
```
@Override
public Component getListCellRendererComponent(List list, Object value, int index, boolean isSelected) 
{
	if (isSelected) {
		getStyle().setBgColor(0xFFCC33);
		getStyle().setBgTransparency(100);
	} else {
		getStyle().setBgTransparency(0);
	}		
	return this;
}



```

Please advice.

**Comment by codenameone** [comment]
https://github.com/codenameone/CodenameOne/issues/1645
