### ISSUE TITLE
weak hash maps are buggy on android

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1670]
Keys in weak hash maps are being dropped (presumably by the GC) when there are still 
strong links elsewhere.   This is real, not theoretical; it was producing mystery misbehavior
in my game app.     

Here's a test program.

	public int testHashMap(int limit)
	{	int errors = 0;
		// weak map has rectangles linked to strings
		WeakHashMap<Rectangle,String>weakMap = new WeakHashMap<Rectangle,String>();
		// strong map has all the same rectangles, so none should ever be purged.
		Vector<Rectangle> strongMap = new Vector<Rectangle>();
		
		int index = 0;
		while(index<=limit)
		{	// check that all the old entries are there
			for(int i=0;i<index;i++)
			{
				Rectangle oldval = strongMap.elementAt(i);
				String value = weakMap.get(oldval);
				String expected = ""+i;	// this is deliberately thrashing memory
				if(!expected.equals(value)) { errors++; }
			}
			// add one new entry
			Rectangle newval = new Rectangle(index,index,index,index);
			strongMap.addElement(newval);
			weakMap.put(newval,""+index);
			index++;
		}
		return(errors);
	}
My android device starts generating errors at around a limit of 250, but presumably
it depends on the state of the GC, available memory etc.   I combined this test with
my previous display glitch producer to produce a watchable fail.

package com.mycompany.myapp;

import java.util.Vector;

import com.codename1.io.ConnectionRequest;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.geom.Rectangle;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.WeakHashMap;

class DisplayComponent extends Component
{	public Image fixed = null;
	public Image front = null;
	public void fillFixed()
	{	int w = getWidth();
		int h = getHeight();
		Graphics g = fixed.getGraphics();
		g.setColor(0xd0d0d0);
		g.fillRect(0,0,w,h);
	}
	int frame = 0;
	
	// test weak hash maps ability to hold keys
	public int testHashMap(int limit)
	{	int errors = 0;
		// weak map has rectangles linked to strings
		WeakHashMap<Rectangle,String>weakMap = new WeakHashMap<Rectangle,String>();
		// strong map has all the same rectangles, so none should ever be purged.
		Vector<Rectangle> strongMap = new Vector<Rectangle>();
		
		int index = 0;
		while(index<=limit)
		{	// check that all the old entries are there
			for(int i=0;i<index;i++)
			{
				Rectangle oldval = strongMap.elementAt(i);
				String value = weakMap.get(oldval);
				String expected = ""+i;	// this is deliberately thrashing memory
				if(!expected.equals(value)) { errors++; }
			}
			// add one new entry
			Rectangle newval = new Rectangle(index,index,index,index);
			strongMap.addElement(newval);
			weakMap.put(newval,""+index);
			index++;
		}
		return(errors);
	}
	public Dimension getPreferredSize() 
	{ Container parent = getParent();
	  return(new Dimension(parent.getWidth(),parent.getHeight()));
	}
	int firstErr = 0;
	int badFrames = 0;
	public void fillFront()
	{	int w = getWidth();
		int h = getHeight();
		frame++;
		int errors = testHashMap(frame);
		if(errors>0)  { badFrames++; }
		if((errors>0) && (firstErr==0)) { firstErr=frame; }
		Graphics g = front.getGraphics();
		g.drawImage(fixed,0,0);
		g.setColor(0);
		g.fillRect(w/3,0,w/4,h);
		g.setColor(0xff);
		g.drawLine(0,0,w,h);
		g.setColor(0xff00);
		g.drawString("Frame "+frame+" hashmap errors "+errors,w/3+20,h/2);
		g.drawString(""+badFrames +" bad frames, first error on frame "+firstErr,w/3+20,h/2+20);
	}
	public boolean animate()
	{
		return(true);
	}
	public void paint(Graphics g)
	{	int w = getWidth();
		int h = getHeight();
		if(fixed==null) { fixed = Image.createImage(w,h); fillFixed(); }
		if(front==null) { front = Image.createImage(w,h); fillFront(); }
		if(front!=null)
		{
		g.drawImage(front,0,0);
		// prepare the next frame
		fillFront();
		repaint();
		}
	}
	
}

public class MyApplication {

	private Form current;
	private DisplayComponent display = null;
	public void init(Object context) {
		// Pro only feature, uncomment if you have a pro subscription
		// Log.bindCrashProtection(true);
	}

	public void start() {
		if (current != null) {
			current.show();
			return;
		}
		Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
		
		display = new DisplayComponent();
		display.setVisible(true);
		hi.add("Center",display);
		hi.registerAnimated(display);
		hi.show();
	}

	public void stop() {
		current = Display.getInstance().getCurrent();
	}

	public void destroy() {
	}

}

**Comment by codenameone** [comment]
We use soft references on Android http://developer.android.com/reference/java/lang/ref/SoftReference.html it gets evicted when memory is low and doesn't test if there is a hard reference somewhere.

**Comment by ddyer0** [comment]
ok, but it ought to be called something else (too late now).  A definite faux ami to call the class weakHashMap.
