### ISSUE TITLE
Eclipse plugin doesn't seem to work correctly with JavaSE native code

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1674]
The mapping to lib/impl/native/javase and its local native counterpart is missing from the build path in a newly created project.

**Comment by codenameone** [comment]
It seems that the JavaSE directory gets the .java files instead of the .class files from the JavaSE implementation.

**Comment by chen-fishbein** [comment]
I created a project and created a javase native impl and it worked, what is the use case that fails?

**Comment by vprise** [comment]
The issue is that it fails for Java SE building if I remember correctly. Notice that this is for the native code from the cn1lib and not regular native code.

**Comment by chen-fishbein** [comment]
is this failing for running in the simulator or on the cloud build?

**Comment by codenameone** [comment]
I forwarded to you the email that triggered this issue. The cn1lib for websockets just wouldn't work for him on Eclipse.

**Comment by nefuwu** [comment]
Hello guys , i have the same problem and for me in eclipse it just dont work. i try it for ages.Is there on update ore solution for this problem ? Otherwise i change to netbeans, but netbeans 12 have no codename one plugin--
