### ISSUE TITLE
Implement IAP (in App Purchase) Subscription on iOS

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1675]
This functionality has been stubbed on iOS since IAP launched

**Comment by shannah** [comment]
Note to self.  [this article](http://savvyapps.com/blog/how-setup-test-auto-renewable-subscription-ios-app) gives a good overview of implementing auto-renewable subscriptions in iOS.

**Comment by kazza186** [comment]
Hi,
Just wondering if this will be implemented in the near future? If not I will need to rework things in my app. Thanks.

**Comment by codenameone** [comment]
It's scheduled for 3.5 which is due by August. It might get postponed to 3.6 which is due on December.

**Comment by codenameone** [comment]
I pushed it to 3.6 as it doesn't seem that this will make it in time for the code freeze with the current workload.

**Comment by shannah** [comment]
This is complete now.
