### ISSUE TITLE
IOS build fails, related to compiling interfaces

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1681]
refer to this forum thread.
https://groups.google.com/forum/#!topic/codenameone-discussions/2aIsDIoNbaQ

the attached file will cause IOS builds to fail with some complaint related
to the use of "nextPlayer" in the Play2Constants interface.  The chain of 
inheritance of the interfaces seems to be part of the problem.

[Dtest.zip](https://github.com/codenameone/CodenameOne/files/126044/Dtest.zip)

**Comment by codenameone** [comment]
This doesn't happen when I try this so I'm assuming this was fixed in one of the changes since submission
