### ISSUE TITLE
IOS build produces hard crashes when executed

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1682]
refer to this forum thread.
https://groups.google.com/forum/#!topic/codenameone-discussions/2aIsDIoNbaQ

Another problem compiling interfaces on IOS - the build succeeds but the resulting code
produces a hard crash when run.  Integrate the attached (single file) into any runnable
project and run it.   
[Dtest.zip](https://github.com/codenameone/CodenameOne/files/126057/Dtest.zip)

**Comment by codenameone** [comment]
This doesn't happen when I try this so I'm assuming this was fixed in one of the changes since submission
