### ISSUE TITLE
IOS connection "succeeds" on malformed host name

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1684]
On IOS, when opening a TCP connection with a malformed host name, no connection
is made to the desired port, but the "successfully connected" callback is used.  This
results in a dead socket, or at best a connection on a socket other than the intended.

     Util.getImplementation().connectSocket("192.168.0.2:80", 2244);

It's possible this connected to port 80, but it's clearly not what's intended.
Other platforms do no "succeed" given a situation like this.

**Comment by codenameone** [comment]
FYI Util.getImplementation() is an internal API that shouldn't be invoked. It's package private to indicate that.

**Comment by ddyer0** [comment]
Not a problem.  I used getImplementation in the complaint only to show you where the problem
actually lies - I use the public APIs.
