### ISSUE TITLE
Second AutoCompleteTextField popup shown at bottom of screen

### ISSUE THREAD

**Issue by gerbenk** [codenameone/CodenameOne#1687]
When you use two AutoCompleteTextField objects in a single form, the popup of the second one is shown at the bottom of the screen and not directly next to the TextField.

<img width="524" alt="screenshot 2016-02-12 16 42 42" src="https://cloud.githubusercontent.com/assets/2700802/13046558/b816d35a-d3d9-11e5-922e-19008730b3e4.png">

It happens on both the simulator and iOS.

**Comment by codenameone** [comment]
Was just able to reproduce this:

```java
Form hi = new Form("AutoComplete", new BoxLayout(BoxLayout.Y_AXIS));
hi.add(new AutoCompleteTextField("AAAA", "ABBB", "ACCCC", "ABC")).
                add(new AutoCompleteTextField("AAAA", "ABBB", "ACCCC", "ABC"));
hi.show();
```
Not sure why the popup is initialized the way it is. We'll need to dig into it.

**Comment by 3lix** [comment]
I submitted issue #1697 that could be related to this one. It is different symptoms with potentially the same root cause. 
-3lix-

**Comment by mjweb48** [comment]
I'm having an issue that may be related, but the symptoms are a bit different.  I've made a form in the GUI builder that has 6 auto complete text fields.  All are made in exactly the same way with their completion arrays set before the form is shown, also in exactly the same way.  The first two fields work as expected.  The second two fields only show their completion options after some of the picker components are used on the form (they are in the same container), and the last two never show their completion options (or are showing them off screen?).

**Comment by chen-fishbein** [comment]
fixed, thanks!
Will be available in the next update

**Comment by mjweb48** [comment]
Thanks Chen!
