### ISSUE TITLE
IOS random number generator is seriously broken

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1689]
on IOS, the class Random does not produce consistent random numbers.

Insert this test function into any suitable test frame.

	public void testRandom(Graphics g,int x,int y)
	{	
		{ Random r = new Random(63546);
		  for(int i=0;i<3;i++) 
		  	{ String val = ""+r.nextLong();
		  	  g.drawString(val,x,y);
		  	  y+=20;
		  	}
		}
		y+=20;
		{ Random r2 = new Random(63546);
		for(int i=0;i<3;i++) 
	  	{ String val = ""+r2.nextLong();
	  	  g.drawString(val,x,y);
	  	  y+=20;
	  	}
		}
	}
It should generate two sets of three identical random numbers.  It does not.

**Comment by shannah** [comment]
I can't seem to reproduce this problem.  Tried the test code posted here.  Built for iOS.  Running on Xcode iOS simulator (iOS 9.2, Xcode 7).

I tried with the current master.
And with the version from Friday (Feb. 19th).  

Here is the test
https://gist.github.com/shannah/7a45f56467a4b2bccb1e

Here is the result (the y spacing of 20 causes overlap, but you can see that the two sequences are identical.

![image](https://cloud.githubusercontent.com/assets/2677562/13226782/14ecbd38-d948-11e5-86f1-0ae5eef1cf8a.png)

**Comment by codenameone** [comment]
The current cloud version of ParparVM is reverted to 3.3 level so it won't reproduce the issue. I'm guessing the pull request refactor has the issue but I'm still not sure what it is.

**Comment by shannah** [comment]
I was building locally.  My build sources still include the refactor (e.g. `(SP*)` instead of `stack[stackPointer]`.

**Comment by sannysanoff** [comment]
Neither it reproduces on mine.

**Comment by ddyer0** [comment]
I had saved a source build for the "bad" version of Random, and comparing it to the current
source build from the same inputs, it's clear it was produced by a significantly different engine -
so it's pretty clear that revisions and reversions of the jar converter are in play.

It's a bit thick to casually browse and determine what's really different, but I will attach both files
for your amusement.


[Random.zip](https://github.com/codenameone/CodenameOne/files/143088/Random.zip)

**Comment by shannah** [comment]
@ddyer0 Can you post the Java for your test case?  I can't do much with those source files on their own.
@codenameone Have you managed to reproduce this problem?  The test case I posted (which is just a the same one that @ddyer0 posted) works for me with the latest in git.

**Comment by ddyer0** [comment]
Here's the source for "Random".  It's a simplified version of java.util.Random which fails
in the same way that the library version did.   All this is actually used by the failing test
is "new" and "nextLong"
[Random.zip](https://github.com/codenameone/CodenameOne/files/143167/Random.zip)

**Comment by shannah** [comment]
@ddyer0 Can you post your test case also?  I tried the snippet you posted before, but, as I mentioned, I can't get it to fail.  If you can create a single lifecycle class (e.g. the class with start(), init(), stop(), etc...) that exhibit(ed) the problem, that would be ideal.

**Comment by codenameone** [comment]
@shannah we had an issue from a customer that looked like it might relate to that. I applied the fix you emailed to me https://github.com/codenameone/CodenameOne/commit/552e736dc4a74b7242212ceb277f6f73af0db96a but there was still a problem. Turns out the issue was unrelated so you fix might have solved it to that customer.

I think we'll update to the latest version of the VM tomorrow again and see how it goes.

**Comment by ddyer0** [comment]
This single file ought to do it.   Note that it runs continuously, showing that (when failing) not only are
the two sets of random numbers different but EVERY pass is different from the previous.
[Dtest.zip](https://github.com/codenameone/CodenameOne/files/143214/Dtest.zip)

**Comment by shannah** [comment]
I just tested that file in both Xcode simulator and device (iPhone 6S), and it works correctly in the latest git.  I also compared the C sources of the Random class in my working sample against the "bad" sample @ddyer0 provided, and it doesn't look like there is any meaningful difference between them.

I still haven't been able to reproduce this problem at all.
