### ISSUE TITLE
background gradient type does not work on Android

### ISSUE THREAD

**Issue by chen-fishbein** [codenameone/CodenameOne#1696]
We should either fix this or remove this option from the designer and deprecate the API, since these gradients keeps cause various issues

**Comment by draedel** [comment]
In V3.1 it was working - and it's used in a project of mine. So please try to fix it ;-)

**Comment by codenameone** [comment]
To be clear, this never "really" worked. Gradients were always buggy and performed badly and we always recommended using images. If your app relies on this a better strategy is to switch to images which are faster and more memory efficient.

**Comment by draedel** [comment]
Well... okay.
I tried using a gradient background image with 1px width using the latest cn1 libs some weeks ago, but the real App failed (only simulator worked).
Now that I have an account on GitHub, I can try this again and file a bug if the error persists :)

Thanks for the clarification!
