### ISSUE TITLE
Need to use ZXing with codename one?

### ISSUE THREAD

**Issue by ghost** [codenameone/CodenameOne#170]
Original [issue 170](https://code.google.com/p/codenameone/issues/detail?id=170) created by codenameone on 2012-04-20T06:51:53.000Z:

I need to use ZXing with Codename One. I need to scan the QR code using ZXing. I will develop this application on both Android and iPhone. How to do this one? Is it possible?

**Comment by tsoikkel** [comment]
I also use zbar. Can you confirm it works with Codename One?
