### ISSUE TITLE
Toolbar: Unusable mobile ui

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1708]
The title of this issue came from one of my users. I have several reports all from Nexus phone Android 6 Marshmallow users. The basic problem is that the system menu size and position make it very difficult to select.

A bit of background. I only need the basic title bar and system menu and have always used the Android System Menu using addCommand(). With the release of Android 6 Marshmallow I ran into a crash when using the system menu. This issue is still open [Issue 1605](https://github.com/codenameone/CodenameOne/issues/1605#issuecomment-155819125) The only way I could find around this problem was to use your Toolbar class instead. I do this on Marshmallow only, on all other versions of Android I use the standard system menu.

Image 1 is a screenshot of my application running on a Nexus 5x:
![image1](https://cloud.githubusercontent.com/assets/14006739/13550713/b8ebab8a-e2d8-11e5-925f-0d6aeb1e8b18.png)

Image 2 is of the Google Setting app on the same device:
![image2](https://cloud.githubusercontent.com/assets/14006739/13550721/d046f712-e2d8-11e5-869e-3b86b58e1c89.png)

Image 3 is Google Chrome on the same device:
![image3](https://cloud.githubusercontent.com/assets/14006739/13550729/017b975c-e2d9-11e5-8ff7-2207ced68142.png)

As you can see the title bar on my app is shorter than the other title bars, the system menu icon is much smaller and closer to the right edge of the screen. Users have mentioned both the size and closeness to the right edge as making it very difficult to select.

I don't have as Nexus phone here to test on but I do have a Nexus 7 with Android 6. I do see the same problem although because of the bigger screen it is not as difficult to select the smaller menu. It is phone devices that really have the problem. I am not sure that this is just a Nexus problem even though all reports have been Nexus users. It could be that Google is pushing out Android 6 to Nexus devices but other manufacturers are not. It is an issue with the Toolbar class on Android 6.

**Comment by mwarnett** [comment]
A couple more images. Image4 is my app running on a Nexus 7 under Android 6 using the Toolbar class:
![image4](https://cloud.githubusercontent.com/assets/14006739/13550960/8bd0ea56-e2de-11e5-9bfb-2255a71cc9c3.png)

Image5 is my app running on the same device but using the native system menu. This still crashes so I cannot ship like this:
![image5](https://cloud.githubusercontent.com/assets/14006739/13550963/a9b4e310-e2de-11e5-8d8c-665e61a11ea9.png)

You can see the title bar is not as tall, the system menu smaller and closer to the right edge of the device. This may not seem like a big deal but it really does make a big difference when trying to select the system menu, especially on phones.

**Comment by codenameone** [comment]
The main issue is that the `Toolbar` has compatibility based UIID's of `Title` & `TitleArea`  so the `TitleArea` UIID needs far more padding when the `Toolbar` is "on". I think the right solution would be to switch toolbar to the "on" mode by default and fixing everything to feel right.

I've also made some changes that should allow us to set the size of the overflow menu in millimeters, I'll do some experiments here.

@chen-fishbein feel free to chime in if you have any thoughts on this.

**Comment by codenameone** [comment]
Padding and shadow were also added in a separate commit
