### ISSUE TITLE
Label.endsWith3Points = true has no effect when Label.icon != null

### ISSUE THREAD

**Issue by gerbenk** [codenameone/CodenameOne#1712]
Try the following code and see that the 3 dots will not appear in on the l1, but do on l2.

```java
Container c = new Container(new BoxLayout(BoxLayout.Y_AXIS));

Label l1 = new Label("This piece of text is wat too long and I am sure it wil never fit on a single line, not even on those modern large display phablets.", Image.createImage(30, 30));
l1.setEndsWith3Points(true);
Label l2 = new Label("This piece of text is wat too long and I am sure it wil never fit on a single line, not even on those modern large display phablets.");
l2.setEndsWith3Points(true);

c.addComponent(l1);
c.addComponent(l2);
```

**Comment by codenameone** [comment]
Thanks!

**Comment by gerbenk** [comment]
It's still not fixed in the current version.

**Comment by codenameone** [comment]
In which OS?

**Comment by gerbenk** [comment]
Simulator and iOS

**Comment by codenameone** [comment]
Make sure you aren't using versioned builds for 3.3.

````java
Form hi = new Form("Ends", new BoxLayout(BoxLayout.Y_AXIS));

Label l1 = new Label("This piece of text is wat too long and I am sure it wil never fit on a single line, not even on those modern large display phablets.", Image.createImage(30, 30));
l1.setEndsWith3Points(true);
Label l2 = new Label("This piece of text is wat too long and I am sure it wil never fit on a single line, not even on those modern large display phablets.");
l2.setEndsWith3Points(true);

hi.add(l1).add(l2);

hi.show();   
````

![codenameone screenshot 41](https://cloud.githubusercontent.com/assets/2353641/14060014/e682e3bc-f366-11e5-918b-d03a9ff691fc.png)

**Comment by gerbenk** [comment]
Sorry, you're right. It works in the code fragment. I guess I'll have an additional problem which I'll try to pinpoint next week.

**Comment by gerbenk** [comment]
Ok, this is what I found:
I forgot calling:  setEndsWith3Points(true); 
The documentation says the default is true, but it seems it isn't.

After adding that, it works in the simulator, but still not on iOS though.

![img_3566](https://cloud.githubusercontent.com/assets/2700802/14102977/132793a2-f59e-11e5-8beb-a19787bef9e6.jpg)

**Comment by codenameone** [comment]
We flipped the default to 3 points a while back. The 3 points feature has some performance overhead and applying it universally to all labels didn't make sense in that context. Where in the docs is that default mentioned? We should fix that.

**Comment by gerbenk** [comment]
That was mentioned here:

https://www.codenameone.com/javadoc/com/codename1/ui/Label.html#setEndsWith3Points-boolean-


--Gerben

**Comment by gerbenk** [comment]
The result in iOS is still the same.

**Comment by codenameone** [comment]
We'll look into it
