### ISSUE TITLE
FacebookConnect isn't supported in the JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1713]
The [FacebookConnect](https://www.codenameone.com/javadoc/com/codename1/social/FacebookConnect.html) class and the [share functionality](https://www.codenameone.com/javadoc/com/codename1/share/ShareService.html) aren't implemented on the JavaScript port:

http://stackoverflow.com/questions/35878091/facebook-login-not-working-in-cn1-javascript-port

**Comment by shannah** [comment]
Implemented facebook connect.  Login and publish permissions only so far.  Haven't implemented invite friends yet.
https://github.com/shannah/cn1-teavm-port/commit/76d7adab20799ce8a252d74a5764240347d8b1d0

**Comment by shannah** [comment]
The closest thing I can find to inviteFriends in the web version is Game requests.

https://developers.facebook.com/docs/games/services/gamerequests

And this isn't a perfect fit.  Leaving this unimplemented for now.
