### ISSUE TITLE
Android crashes when it runs out of memory, no OutOfMemoryException

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1716]
When android runs out of memory "the hard way" by increasing storage of small bits until
there is no more, it crashes with no warning, trace, or exception.  The attached test program
demonstrates this.  I run it on modest tablets with 1g of main memory, though I don't think
that matters.  This program also makes the simulator behave strangely, but not quite so
disastrously.

[Dtest.zip](https://github.com/codenameone/CodenameOne/files/170347/Dtest.zip)

**Comment by codenameone** [comment]
That's a bug for Google not us. Please don't attach code as zips as it makes it harder to grep.

**Comment by ddyer0** [comment]
I don't know the details of the APIs involved, but surely there must be a way to monitor
the progress toward the limit, and declare "out of memory" at a chosen point when the 
reserves get low. You don't want to be actually out anyway, some is needed to report 
or recover.

The interface doesn't allow uploading .java source files.
