### ISSUE TITLE
There is currently no way to track permission denial in Codename One

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1718]
When a user denies permissions for the app we have no way of distinguishing that vs. unavailability. iOS has https://www.codenameone.com/javadoc/com/codename1/ui/Display.html#isContactsPermissionGranted-- but we probably need to add that for other API's and we might want something more generic (accepts a String?). This should work for Marshmallow builds.
 
See:
http://stackoverflow.com/questions/36049909/if-a-user-denies-access-to-the-camera-in-codename-one-can-you-find-out-from-code

**Comment by chen-fishbein** [comment]
implemented
