### ISSUE TITLE
Android keyboard no longer closes when done button hit

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1722]
This just started happening, build date 03/19/2016.

I create a TextField with a done listener:

            _searchFor = new TextField();
            _searchFor.setColumns(8);
            _searchFor.setInputMode("abc");
            _searchFor.setConstraint(TextField.ANY | TextField.NON_PREDICTIVE);
            _searchFor.setDoneListener(this);
            _searchFor.putClientProperty("searchField", true);

Expected behavior is when user enters text and hits the done button on the keyboard, the app receives the input and the keyboard closes. This is no longer happening, the app does receive the input so the done listener is getting called but the keyboard remains open and the user has to use the back button to close it.

When trying to create a simple test case I noticed this is only happening if I change the done button icon in the keyboard. This is done by the last statement above, I change the standard done button icon to the search icon. If the putClientProperty line is commented out, the program works as expected, the keyboard has the standard done button icon and closes when it is selected. But when I change the icon, the keyboard stays open.

Full source included:

package com.readerware.xware.test;

import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridBagConstraints;
import com.codename1.ui.layouts.GridBagLayout;
import com.codename1.ui.layouts.Insets;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.util.Resources;
import java.io.IOException;

public class TWMain {

    private Form current;
    private Form form;
    protected Toolbar _myToolbar;

    public void init(Object context) {

        try {
            Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }

        form = new MyForm();

        form.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

    private class MyForm    extends     Form
                            implements  ActionListener {
        Command         _backCommand;
        TextField       _searchFor;
        Label           _statusMessage;

        public MyForm() {
            super("CodenameOne Test");
            getContentPane().setLayout(new BorderLayout());

            _backCommand = new Command("Home", 1);
            setBackCommand(_backCommand);

            addCommandListener(this);

            GridBagLayout gbl = new GridBagLayout();
            GridBagConstraints gbc = new GridBagConstraints();
            setLayout(gbl);

            int y = 0;
            int x = 0;
            _searchFor = new TextField();
            _searchFor.setColumns(8);
            _searchFor.setInputMode("abc");
            _searchFor.setConstraint(TextField.ANY | TextField.NON_PREDICTIVE);
            _searchFor.setDoneListener(this);
            _searchFor.putClientProperty("searchField", true);

            gbc.anchor        = GridBagConstraints.SOUTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = 1;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.1;
            gbc.weighty       = 0.0;
            gbl.setConstraints(_searchFor, gbc);
            addComponent(_searchFor);

            y++;
            x = 0;
            _statusMessage = new Label(" ");
            _statusMessage.setPreferredW(500);
            Style style = _statusMessage.getStyle();
            style.setAlignment(Component.CENTER);
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 10, 0, 10);
            gbl.setConstraints(_statusMessage, gbc);
            addComponent(_statusMessage);

            y++;
            x = 0;
            Label filler = new Label();

            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = 1;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.VERTICAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.1;
            gbc.insets        = new Insets(0, 0, 0, 0);
            gbl.setConstraints(filler, gbc);
            addComponent(filler);
        }

            public void actionPerformed(ActionEvent actionEvent) {
            Command command = actionEvent.getCommand();

            if (command != null) {
                if (command == _backCommand) {
                    stop();
                    Display.getInstance().exitApplication();
                    return;
                }
            }

            Object source = actionEvent.getSource();

            if (source == _searchFor) {
                _statusMessage.setText("GOT: " + _searchFor.getText());

                return;
            }
        }
    }
}

**Comment by mwarnett** [comment]
To use the sample code, touch the input field to activate the keyboard, enter some text and hit the Search button in the keyboard. The app will display the input received but the keyboard is still displayed and must be removed using the back button.

**Comment by chen-fishbein** [comment]
fixed, thanks
