### ISSUE TITLE
Networking Problem while installing Plugin

### ISSUE THREAD

**Issue by Kraelern** [codenameone/CodenameOne#1728]
Every time I try to install the plugin
it shows an error that's  like:-
Warning
**"Networking problem in 
http://plugins.netbeans.org/nbpluginportal/files/nbms/1458134205_com-codename1.nbm"**
and below it says
"Check your proxy settings or try again later. The server may be unavailable at the moment. You may also want to make sure that your firewall is not blocking network traffic. Your cache may be out of date. Please click Check for Updates to refresh content."

**Comment by codenameone** [comment]
It seems that the netbeans plugin portal is down: http://plugins.netbeans.org/ I've notified our contacts at Oracle and hopefully this will be up soon.

**Comment by codenameone** [comment]
FYI the NetBeans team seems to have fixed it so it should work now.

**Comment by Kraelern** [comment]
I tried it out but it keeps saying *"this page is unavailable".*

basically this is the error that pops up

**Comment by codenameone** [comment]
It seems that they have some scheduled downtime: https://twitter.com/netbeans/status/716393938052071429 it's pretty sporadic.

**Comment by codenameone** [comment]
Despite everything it seems the NetBeans team is still struggling with restoring the site, we placed the latest version of the plugin here: https://www.codenameone.com/files/com-codename1.nbm

We suggest uninstalling it once NetBeans get their act together so you can enjoy automatic updates but for now this seems to be the only way.
