### ISSUE TITLE
Enable adding native image resources for push notification icon

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1732]
At the very least on Android I know you can set a custom push icon. In Android it is accomplished by setting the path of a drawable in the manifest file under application settings, but there is currently no way to add a file to the cn1 project that will end up in the appropriate directory (res/drawable-xhdpi) in the generated Android project, short of building from source and adding it manually.

**Comment by chen-fishbein** [comment]
This is already implemented:
http://stackoverflow.com/questions/34995371/notification-icon-is-white-on-the-notification-tray/34995372#34995372
