### ISSUE TITLE
Error constructing IOS sources

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1733]
This error:
Undefined symbols for architecture armv7:
  "_get_static_com_boardspace_Dtest_TextureNames", referenced from:
      _com_boardspace_Dtest_init___java_lang_Object in com_boardspace_Dtest.o

Appears to be due to an error in the name construction algorithm for IOS.  The 
symbol in question is Associated with an inherited interface.  A single file that exhibits
the problem is attached.
[Dtest.zip](https://github.com/codenameone/CodenameOne/files/211471/Dtest.zip)

**Comment by codenameone** [comment]
This might have been fixed by one of my commits @shannah can you please check if this still happens?

**Comment by ddyer0** [comment]
still fails

/Dtest_dependency_info.dat -o /var/folders/p7/d3z112yd0156kxkm2p21p8ym0000gn/T/build636119007844256136xxx/dist/build/Release-iphoneos/Dtest.app/Dtest
Undefined symbols for architecture armv7:
  "_get_static_dtest_boardspace_Dtest_TextureNames", referenced from:
      _dtest_boardspace_Dtest_init___java_lang_Object in dtest_boardspace_Dtest.o

**Comment by ddyer0** [comment]
Still fails for me.

....
The following build commands failed:
	CompileC build/Build/Intermediates/ArchiveIntermediates/Dtest/IntermediateBuildFilesPath/Dtest.build/Release-iphoneos/Dtest.build/Objects-normal/arm64/dtest_boardspace_Dtest.o Dtest-src/dtest_boardspace_Dtest.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Failed xcodebuild step

**Comment by shannah** [comment]
This fix isn't deployed to the build server yet.  It will be included in the next update.
