### ISSUE TITLE
Background fetch

### ISSUE THREAD

**Issue by Munken** [codenameone/CodenameOne#1741]
I was about to implement background fetch using native interface, but I stumbled over this [gitbook](https://shannah.gitbooks.io/techposts/content/BackgroundFetch.html) by shannah, which mentions a CN1 background fetch API. 

However I cannot find any other reference to it. Is it still in the works? If so what is the timeline ?

**Comment by codenameone** [comment]
I think these sort of things are best raised in the discussion group as they are more conversational than an issue.

**Comment by Munken** [comment]
All right. I have opened the discussion in the group. 

https://www.codenameone.com/discussion-forum.html?place=msg%2Fcodenameone-discussions%2Fi2bJdx4KobI%2FpYni69FfCQAJ

Feel free to close this.
