### ISSUE TITLE
Implement background fetch API

### ISSUE THREAD

**Issue by Munken** [codenameone/CodenameOne#1743]
Currently background fetch must be implemented with native interfaces. Possibly crossing back into the java code. Not exactly clean. 

Steve made a [gitbook](https://shannah.gitbooks.io/techposts/content/BackgroundFetch.html) which shows an example API. I think this looks quite neat. 

Can something like this be implemented?

**Comment by shannah** [comment]
For reference, the implementation that we opted not to use back in August.
https://github.com/codenameone/CodenameOne/commits/background-exec

Last 2 commits.

**Comment by shannah** [comment]
Implemented in this commit

https://github.com/codenameone/CodenameOne/commit/2ac46496af0a7dc23b1548767a0f9b21b34c89aa

Snippet showing the use of it:

https://gist.github.com/shannah/4b023ed09e7f64ab6420647b22d1823d

Usage instructions found in javadocs for BackgroundFetch class:

https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/background/BackgroundFetch.java

**Comment by Munken** [comment]
Looks good!

However the meaning of the return value given to `onComplete` is not clear. Is new data = true or ?

**Comment by shannah** [comment]
Yes.  new data = true.
No new data = false
If it fails, then you use the onError callback.

**Comment by Munken** [comment]
Hmm just tried to build, but it fails due to `java.lang.IllegalArgumentException: Negative delay.`

[f87c5188-dbe9-46a5-829a-affa8d6384c6-1466317482186-error.txt](https://github.com/codenameone/CodenameOne/files/322146/f87c5188-dbe9-46a5-829a-affa8d6384c6-1466317482186-error.txt)

All I'm doing is this: `d.setPreferredBackgroundFetchInterval(15*60 /*15 minutes*/);`

**Comment by Munken** [comment]
This can be fixed with `if (d.isBackgroundFetchSupported())`, but it should probably be added to the example gist.

**Comment by shannah** [comment]
Thanks.  I'll insulate this on the port itself so that these methods just do nothing if isBackgroundFetchSupported() is false.... that will fix these types of errors also.
