### ISSUE TITLE
RFE: Evaluate moving the retrolambda implementation to use the new fork from JakeWharton

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1749]
The efficiency gains could be quite nice: 
https://github.com/JakeWharton/retrolambda

**Comment by codenameone** [comment]
This was now rolled into retrolambda 2.3 so we might want to upgrade to that at least for the Android build. This reduces method count significantly and might speed up builds while reducing the whole "out of memory" issues we got on Android.

**Comment by shannah** [comment]
Updated to 2.5.1.  Tested KitchenSink for iOS, Android, and UWP.  Worked fine.
