### ISSUE TITLE
Audio playback cleanup issue

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1750]
A crash report was posted to stackoverflow here: http://stackoverflow.com/questions/36900773/codename-one-audio-play-back-crash-on-ios

Could it be related to this?
https://github.com/codenameone/CodenameOne/blob/master/Ports/iOSPort/src/com/codename1/impl/ios/IOSImplementation.java#L3052-L3054

**Comment by shannah** [comment]
@codenameone Can you please review.  I have tested and it seems to work.

**Comment by codenameone** [comment]
Lets keep it for post 3.4. It looks fine but I don't think this should go into this release.
