### ISSUE TITLE
Android build requests WAKE_LOCK permission for empty app

### ISSUE THREAD

**Issue by timovandeput** [codenameone/CodenameOne#1756]
Android apps request WAKE_LOCK permission, although there is no explicit reference to `Display.lockScreen()` or `Display.setScreenSaverEnabled()`.

To verify my observation I created a new empty app using the wizard, and built it for Android.
Installation on my Samsung A3 Android 5.0.2 phone indicates this app requests rights to control "sleep mode".

This is what the application properties shows:

![screenshot_2016-04-30-09-22-40](https://cloud.githubusercontent.com/assets/5458560/14934593/9501348e-0eb5-11e6-8721-b133b0a8754c.png)

**Comment by codenameone** [comment]
We don't require that permission, it is derived from Google play services and isn't a part of Codename One itself.

You can disable the analytics service to remove this permission by setting the build hint `android.playService.analytics=false`
Notice that this will implicitly disable all other google play services turned on by default so you will have to explicitly turn on any such service you want as explained here: https://www.codenameone.com/manual/advanced-topics.html
