### ISSUE TITLE
RFE: Allow peer components to deal with different z-ordering behaviors

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1758]
Currently peer components are rendered always on top. This is problematic for many use cases and we need to provide more flexibility even in a platform dependent way. 

Based on capabilities of the platform we propose 3 different solutions in order of their desireability:
1. Render peer components in the correct component z-order - we believe that might be possible with the new Android async pipeline.
2. Provide a dedicated "peer" layer which will reside in a predefined position where all native peers will reside. Some content will be drawn below and some above. The position of this layer will be determined based on the z-order of the first peer drawn.
3. Provide a way for the peer to draw in the background or in the foreground and let the peer author or the developer to determine where he wants the peer to appear.

**Comment by codenameone** [comment]
This has an experimental Android implementation that landed for 3.5. We'll work on iOS/Desktop in 3.6

**Comment by codenameone** [comment]
I won't be able to take on the iOS/Desktop versions @shannah can you add it to the bottom of your task lists?

**Comment by shannah** [comment]
This is now supported in all major platforms
