### ISSUE TITLE
java.lang.IllegalArgumentException: valid values are between 0-255

### ISSUE THREAD

**Issue by amiga** [codenameone/CodenameOne#1761]
I have some animation that happens in my app which appears fine, but I have recently started getting bug reports like this:
- java.lang.IllegalArgumentException: valid values are between 0-255
  [EDT] 22:57:14,611 - java.lang.IllegalArgumentException: valid values are between 0-255
      at com.codename1.ui.plaf.Style.setOpacity(Style.java:1205)
      at com.codename1.ui.Container$MorphAnimation.updateState(Container.java:2779)
      at com.codename1.ui.animations.ComponentAnimation.updateAnimationState(ComponentAnimation.java:80)
      at com.codename1.ui.AnimationManager.updateAnimations(AnimationManager.java:67)
      at com.codename1.ui.Form.repaintAnimations(Form.java:1336)
      at com.codename1.ui.Display.edtLoopImpl(Display.java:1078)
      at com.codename1.ui.Display.mainEDTLoop(Display.java:995)
      at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
      at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
      at java.lang.Thread.run(Thread.java:818)

Here is my code, I cannot figure out what line is causing this. opacityWhenLeaving is set to 75, any ideas why im getting this ?

``
 case CAT_FROM_LEFT:
                _("CAT_FROM_LEFT");
                //new cat from below
                final Container containerForCatC = createContainer(resources, "CATanimFROM_LEFT");
                containerForCatC.addPointerPressedListener(new ActionListener(){
                    public void actionPerformed(ActionEvent evt) {
                          _("containerForCatC TAPPED");
                          catTapped(f);  
                    }
                });
                //set it off screen
                final int iinitialXc =-f.getWidth()*3;//3200 ;
                final int iinitialYc = f.getHeight()/8;
                containerForCatC.setX(iinitialXc);
                containerForCatC.setY(iinitialYc  );

```
            //add it to bottom
            c.add(BorderLayout.WEST,containerForCatC);                                              
            //now animate it over time                                
            c.animateLayout(randomSpeedComingIn);
            //wait til anim finishes, then flush, then we do the opposite so can vanishes!
            c.getAnimationManager().flushAnimation(new Runnable(){
                @Override
                public void run() {
                    _("remove cat");
                    containerForCatC.setX(iinitialXc);
                    containerForCatC.setY(iinitialYc);
                    //c.removeComponent(containerForCatD);
                    c.animateUnlayout(randomSpeedComingOut, opacityWhenLeaving, new Runnable(){

                        @Override
                        public void run() {
                           _("unanimated, remove cat");
                           c.removeComponent(containerForCatC);
                        }
                    });//.animateLayout(5000);//c.revalidate();                                        
                }
            });
            break;
```

``

**Comment by codenameone** [comment]
Is this still happening? We added some debugging data to the exception log can you check if it contains the actual value used now?

**Comment by amiga** [comment]
I cannot tell until I get the bug reports back. If I get none of them on my next release then I can tell you it's fixed, otherwise I will forward them also :-) Thanks for the awesome work as usual, codename one is really something very special.

**Comment by codenameone** [comment]
Closing for now
