### ISSUE TITLE
Bar chart freezes application on asyncPaint=true

### ISSUE THREAD

**Issue by ivanilavsky** [codenameone/CodenameOne#1762]
refs: [https://goo.gl/eVSmZh](https://goo.gl/eVSmZh)

Hi,
the problem with app hang up has ChartsDemo too. 
Just create new project in your IDE using Demo project Charts, and set codename1.arg.android.asyncPaint=true
Run the aplication (in android device!) and click "Sales Bar Chart", the transition starts but never ends and application freezes.

Best regards
Ivan

**Comment by shannah** [comment]
Just tried exactly what you said with the Charts demo.  Did a debug build on the build server.  android.asyncPaint=true

And it is working fine on a Nexus 5 running Android 5.0.1

**Comment by ivanilavsky** [comment]
Hi, this is my version build from Eclipse, running on Xiaomi Redmi Note 3, Android 5.0.2, does not work, can you try it pls?

https://www.dropbox.com/s/ajfx6y8iw2zzs4q/7c885c4c-f625-437c-98b8-fe977f5ed344-1462540358058-ChartsDemo-debug.apk?dl=0

**Comment by shannah** [comment]
That build is different than mine a several little ways.  Are you doing a versioned build?

**Comment by ivanilavsky** [comment]
no, nothing special, just right click on project -> Codename One -> Send Android build
this previous is probably built with libs ver. 107
here is my latest build (still not working): 
https://www.dropbox.com/s/a3id9kzmg9nvn1y/ChartsDemo-debug.apk?dl=0

**Comment by shannah** [comment]
OK.  I've tried it every which way. I tried a versioned build (3.3), a non-versioned build.  I've tried with android.asyncPaint=true, android.asyncPaint=false, and android.asyncPaint omitted.

My builds are drastically different than yours.  Background colors are different, etc...

It looks like you must be using a really old plugin or something.

What IDE are you using?  What version of the plugin?

**Comment by ivanilavsky** [comment]
IDE is Eclipse Indigo 3.7.2, plugin version is 1.0.0.201504021245

**Comment by codenameone** [comment]
I'll try to look at this a bit later and see if I can see something.

**Comment by ivanilavsky** [comment]
I upgraded my IDE to Eclipse Neon v4.6, plugin version 1.0.0.201605011250, created new project based on demo project Charts and the bahavior is still the same, here is my build:
https://dl.dropboxusercontent.com/u/2533926/ChartsDemo-debug-neon.apk

notes: 
- when I remove codename1.arg.android.asyncPaint (default setup) charts do not work
- when I switch codename1.arg.android.asyncPaint=false charts are working well
- when I switch codename1.arg.android.asyncPaint=true or default and check the "Render on Mutable Image" checkbox in the demo, charts are working well

**Comment by codenameone** [comment]
I just installed your APK and it's not happening on my device. Please connect your device with a cable to your computer and run DDMS look at the logs when this is happening and see if you can see and exception/error. Please post this here.

**Comment by ivanilavsky** [comment]
this is the log from start of charts demo until the "Sales Bar Chart" click. After I click it nothing happens in log any more, the last record is about "BufferQueueProducer ChartsDemoStub" and application hangs up:

05-11 12:48:33.954: I/ActivityManager(730): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.codename1.demos.charts/.ChartsDemoStub bnds=[317,96][509,288] (has extras)} from uid 10022 on display 0
05-11 12:48:33.966: I/BufferQueueConsumer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:0,p:-1,c:257) setConsumerName: Starting com.codename1.demos.charts
05-11 12:48:33.966: I/BufferQueueConsumer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:0,p:-1,c:257) setDefaultBufferSize: width=1 height=1
05-11 12:48:33.974: I/ActivityManager(730): Start proc com.codename1.demos.charts for activity com.codename1.demos.charts/.ChartsDemoStub: pid=24265 uid=10146 gids={50146, 9997, 3003, 1028, 1015} abi=arm64-v8a
05-11 12:48:33.981: I/BufferQueueConsumer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:0,p:-1,c:257) setDefaultBufferSize: width=1080 height=1920
05-11 12:48:34.001: I/BufferQueueProducer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:2,p:730,c:257) connect(P): api=2 producer=(730:system_server) producerControlledByApp=false
05-11 12:48:34.002: I/BufferQueueProducer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:2,p:730,c:257) new GraphicBuffer needed
05-11 12:48:34.003: D/PowerKeeperEventLogManager(1701): notifyForegroundCompomentChanged ComponentInfo{com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}
05-11 12:48:34.036: D/ActivityThread(24265): installProvider: context.getPackageName()=com.codename1.demos.charts
05-11 12:48:34.074: D/ActivityThread(24265): BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{2bf2bbfa com.codename1.demos.charts}}
05-11 12:48:34.074: V/ActivityThread(24265): Handling launch of ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}}
05-11 12:48:34.077: V/ActivityThread(24265): ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}}: app=android.app.Application@a09dc6, appName=com.codename1.demos.charts, pkg=com.codename1.demos.charts, comp={com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}, dir=/data/app/com.codename1.demos.charts-1/base.apk
05-11 12:48:34.120: V/ActivityThread(24265): Performing resume of ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}}
05-11 12:48:34.163: D/ActivityThread(24265): ACT-AM_ON_RESUME_CALLED ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}}
05-11 12:48:34.163: V/ActivityThread(24265): Resume ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}} started activity: false, hideForNow: false, finished: false
05-11 12:48:34.185: V/ActivityThread(24265): Resuming ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}} with isForward=true
05-11 12:48:34.185: V/PhoneWindow(24265): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{30d87775 com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{17f1e8b4 V.ED.... R.....ID 0,0-0,0}
05-11 12:48:34.185: V/ActivityThread(24265): Scheduling idle handler for ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}}
05-11 12:48:34.186: D/ActivityThread(24265): ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{8fc65ab token=android.os.BinderProxy@7b39408 {com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}}
05-11 12:48:34.192: I/BufferQueueConsumer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:0,p:-1,c:257) setConsumerName: com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub
05-11 12:48:34.192: I/BufferQueueConsumer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:0,p:-1,c:257) setDefaultBufferSize: width=1 height=1
05-11 12:48:34.194: V/WindowManager(730): Changing focus from null to Window{cf8302f u0 com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:-1 com.android.server.wm.Session.relayout:-1 android.view.IWindowSession$Stub.onTransact:237 com.android.server.wm.Session.onTransact:-1 
05-11 12:48:34.198: I/BufferQueueConsumer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:0,p:-1,c:257) setDefaultBufferSize: width=1080 height=1920
05-11 12:48:34.204: I/WindowManager(730): Gaining focus: Window{cf8302f u0 com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub}
05-11 12:48:34.226: I/BufferQueueProducer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:1,p:24265,c:257) connect(P): api=1 producer=(24265:com.codename1.demos.charts) producerControlledByApp=true
05-11 12:48:34.228: I/BufferQueueProducer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:1,p:24265,c:257) new GraphicBuffer needed
05-11 12:48:34.235: D/BufferQueueProducer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:1,p:24265,c:257) allocateBuffers: allocating from 1 buffers up to 3 buffers
05-11 12:48:34.238: D/BufferQueueProducer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:1,p:24265,c:257) allocateBuffers: allocating from 3 buffers up to 3 buffers
05-11 12:48:34.247: V/InputMethodManager(24265): onWindowFocus: com.codename1.impl.android.AndroidAsyncView{6aaea80 VFED..C. .F....ID 0,0-1080,1860 #7d1} softInputMode=275 first=true flags=#81810100
05-11 12:48:34.247: V/InputMethodManager(24265): START INPUT: com.codename1.impl.android.AndroidAsyncView{6aaea80 VFED..C. .F....ID 0,0-1080,1860 #7d1} ic=null tba=android.view.inputmethod.EditorInfo@c5b5af3 controlFlags=#105
05-11 12:48:34.297: D/Codename One(24265): sizechanged: 1080 1860 com.codename1.impl.android.CodenameOneView@34d69adc
05-11 12:48:34.335: I/ActivityManager(730): [AppLaunch] Displayed Displayed com.codename1.demos.charts/.ChartsDemoStub: +371ms
05-11 12:48:34.335: D/ActivityManager(730): AP_PROF:AppLaunch_LaunchTime:com.codename1.demos.charts/.ChartsDemoStub:371:518729931
05-11 12:48:34.365: D/Codename One(24265): sizechanged: 1080 1692 com.codename1.impl.android.CodenameOneView@34d69adc
05-11 12:48:34.400: I/Timeline(730): Timeline: Activity_windows_visible id: ActivityRecord{1dc6f19d u0 com.codename1.demos.charts/.ChartsDemoStub t1531} time:518729997
05-11 12:48:34.535: I/BufferQueueProducer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:2,p:-1,c:257) disconnect(P): api 2
05-11 12:48:34.535: I/BufferQueueConsumer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:2,p:-1,c:257) getReleasedBuffers: returning mask 0xffffffffffffffff
05-11 12:48:34.549: I/BufferQueueConsumer(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:2,p:-1,c:-1) disconnect(C)
05-11 12:48:34.549: I/BufferQueue(257): [Starting com.codename1.demos.charts](this:0x559f55a9a0,id:15037,api:2,p:-1,c:-1) ~BufferQueueCore
05-11 12:48:36.657: I/BufferQueueProducer(257): [com.codename1.demos.charts/com.codename1.demos.charts.ChartsDemoStub](this:0x559f558930,id:15038,api:1,p:24265,c:257) queueBuffer: fps=1.72 dur=2328.42 max=2035.85 min=3.84

**Comment by ivanilavsky** [comment]
this is the system wide trace when I click the  "Sales Bar Chart" link
[trace.txt](https://github.com/codenameone/CodenameOne/files/259119/trace.txt)

**Comment by codenameone** [comment]
Sorry this got buried under a pile of emails. The trace doesn't contain the details we need. We need to see where the EDT or native threads are "stuck" I'm guessing it's the EDT that's stuck otherwise the app would crash.

To do that we need to reproduce this in the debugger and press pause then you can see the thread stack for the EDT and provide that stack.

**Comment by codenameone** [comment]
@ivanilavsky were you able to reproduce this in the native Android Studio sources?

**Comment by ivanilavsky** [comment]
hi, no, I used workaround: when I'm rendering the chart on mutable image everything works fine

**Comment by codenameone** [comment]
I'm removing this from a specific milestone until we can get some way to reproduce this or stack traces pointing on where it's stuck

**Comment by shannah** [comment]
Was finally able to reproduce this - and fix it.
