### ISSUE TITLE
Better support for retina macbooks with JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1765]
https://coderwall.com/p/vmkk6a/how-to-make-the-canvas-not-look-like-crap-on-retina

This might trigger issues with things such as text input in place etc.

**Comment by shannah** [comment]
Fixed.  Should be working now on pretty much any device with pretty much any density.

https://github.com/shannah/cn1-teavm-port/commit/9cdd2a57920369e5887207832bc868151eacae27
https://github.com/shannah/cn1-teavm-port/commit/ae21c6795f07ec8a37e9998114858355bb569991
https://github.com/shannah/cn1-teavm-port/commit/e01848441543821f5a9351fbbc658d0ee1d7b3c0
https://github.com/shannah/cn1-teavm-port/commit/d681b71442d0664e34916a1d82bd572503295005
