### ISSUE TITLE
Display image/video Gallery on JavaScript port should probably map to a file chooser

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1766]
I'm not sure if this is doable but currently the gallery just fallsback to a dialog instead of doing what the Java SE port does which is show a file picker. I think the latter makes more sense although I'm not sure if something like that can be implemented.

**Comment by shannah** [comment]
Implemented
https://github.com/shannah/cn1-teavm-port/commit/a55ecc92d6b1d64e57534695269e0c1a42cd437b
