### ISSUE TITLE
Calling Toolbar.setGlobalToolbar(false) results in two Toolbars.

### ISSUE THREAD

**Issue by SwingGuy1024** [codenameone/CodenameOne#1767]
Here's a skeleton of an application with a main window, a two-page wizard, and a settings page. I only want the toolbar in the main window, so I called setGlobalToolbar(false). It runs properly in the simulator, but when I run it on my Android phone, As soon as I go to a second form, I get two toolbars instead of zero. The top one appears to be a title bar, and when I return to the main Form, it retains the name of the last form I was at.  To verify this, launch this demo application.

(To see what happens when you use the global toolbar, you will need to change two lines, marked with comments.)

    import java.io.IOException;
    import com.codename1.io.FileSystemStorage;
    import com.codename1.ui.Button;
    import com.codename1.ui.Command;
    import com.codename1.ui.FontImage;
    import com.codename1.ui.Form;
    import com.codename1.ui.Image;
    import com.codename1.ui.animations.Transition;
    import com.codename1.ui.events.ActionEvent;
    import com.codename1.ui.layouts.BoxLayout;
    import com.codename1.ui.plaf.Style;
    import com.codename1.ui.plaf.UIManager;
    import com.codename1.ui.util.Resources;
    import com.codename1.ui.Toolbar;
    
    @SuppressWarnings("HardCodedStringLiteral")
    public class Playground {
    
      private Form current;
      private MainForm mainForm;
      public void init(Object context) {
        UIManager.initFirstTheme("/theme");
    
        // Disable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(false);  // Change to true to restore the global Toolbar.
        
        mainForm = new MainForm();
      }
    
      public void start() {
        if (current != null) {
          current.show();
          return;
        }
    
        Form hi = mainForm;
        hi.show();
        current = hi;
      }
    
      public void stop() {
      }
    
      public void destroy() {
      }
    
      private class MainForm extends Form {
        MainForm() {
          super("Playground");
          setLayout(new BoxLayout(BoxLayout.Y_AXIS));
          Button startWizard = new Button("Start Wizard");
          startWizard.addActionListener(this::gotoToPageOne);
          add(startWizard);

          setToolbar(new Toolbar());                                  // comment me out to go to a global toolbar
          Command settingsCommand = new Command("Settings") {
            @Override
            public void actionPerformed(final ActionEvent evt) {
              navigateTo(mainForm, new SettingsForm(), null);
            }
          };
          getToolbar().addCommandToOverflowMenu(settingsCommand);
          
        }
        
        private void gotoToPageOne(final ActionEvent actionEvent) {
          Form pageOne = makePageOne();
          navigateTo(mainForm, pageOne, null);
        }
      }
      
      private Form makePageOne() {
        Form pageOne = new Form("Page One of Wizard");
        pageOne.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        Button next = new Button("next");
        next.addActionListener((evt) -> navigateToPageTwo(pageOne));
        pageOne.add(next);
        return pageOne;
      }
    
      private void navigateToPageTwo(Form pageOne) {
        Form pageTwo = new Form("Page Two of Wizard");
        pageTwo.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        Button done = new Button("Done");
        done.addActionListener((evt) -> {
          navigateTo(mainForm, mainForm, null);
        });
        pageTwo.add(done);
        navigateTo(pageOne, pageTwo, null);
      }
    
      private class SettingsForm extends Form {
    
        public SettingsForm() {
          super("Settings");
          setLayout(new BoxLayout(BoxLayout.Y_AXIS));
    
          Button colorButton = new Button("Background Color", createClearMaterialIcon(FontImage.MATERIAL_VISIBILITY));
          colorButton.getAllStyles().setAlignment(LEFT);
          colorButton.addActionListener((evt) -> selectColor());
          add(colorButton);
        }
    
        Image createClearMaterialIcon(char icon) {
          Style materialIconStyle = new Style();
          materialIconStyle.setBgTransparency(0, true);
          return FontImage.createMaterial(icon, materialIconStyle);
        }
    
        private void selectColor() {
        }
      }
    
      /**
       * This may also be used in place of Form.show(). This sets a backCommand into the specified destination Form
       * that will return the user to specified starting Form. Then it shows the destination form.
       *
       * @param startingForm The Form to return to when the user presses the back button
       * @param destination  The destination Form to show
       * @param transition   The transition to use, or null to use the existing transitions in the form.
       */
      static void navigateTo(final Form startingForm, final Form destination, Transition transition) {
        assert startingForm != null;
        assert destination != null;
        Command backCommand = createBackCommand(startingForm);
        if (transition != null) {
          startingForm.setTransitionOutAnimator(transition);
        }
        destination.setBackCommand(backCommand);
        destination.show();
      }
    
      static Command createBackCommand(final Form startingForm) {
        return new Command("Back") {
          @Override
          public void actionPerformed(final ActionEvent evt) {
            startingForm.showBack();
          }
        };
      }
    }

**Comment by codenameone** [comment]
This was unclear in the docs. It won't work that way toolbar is per form.

**Comment by SwingGuy1024** [comment]
Why was this closed? The documentation is now clearer, but the "fix" doesn't address the unusual behavior, or the mismatch between the names on the two visible toolbars. I have a hard time believing there are supposed to be two tool bars present when I disable the global toolbar. Also, in the supplied test case, when I return to a form, the top toolbar still has the name of the previous form. Is that really the desired behavior? Please look at the test case again to see what I'm talking about.

I should also mention that the documentation is still not clear. It says "enabled/disables the Toolbar for all the forms in the application." This suggests that setting the globalToolBar to false will disable the Toolbars in all the Forms at once. That's not the behavior I'm seeing. It might also be taken to mean that, when this is enabled, each Form will get a Toolbar by default, whereas if it's false, each Form will need to to have a toolbar explicitly added for the user to see a toolbar. This is closer to the behavior I'm seeing, but it's not quite what the documentation says. If that's the actual intended behavior (which I'm not sure of), then a better description might be this: "Determines whether new forms will have a Toolbar installed automatically when they are instantiated."

**Comment by codenameone** [comment]
I think I misunderstood the issue. What you are seeing isn't two toolbars but the native Android menu. Is this only happening on the device?

**Comment by SwingGuy1024** [comment]
I only see it on my Android. It doesn't show up on the simulator. Also, the title is often wrong. (I filed this as a separate issue, #1771.) When I go through the wizard, the title for the last page of the wizard remains.
