### ISSUE TITLE
Committing theme.res in subversion launches multiple copies of Resource Editor

### ISSUE THREAD

**Issue by SwingGuy1024** [codenameone/CodenameOne#1772]
I'm using the CodenameOne plugin in IntelliJ. Whenever I have made changes to theme.res, and I want to check them into Subversion, it launches multiple copies of the ResourceEditor. I've seen it launch the ResourceEditor over thirty times, all at once. It may be doing this once for each image in the editor, but that's just a guess, since the number of instances seems to go up as the number of images goes up. I don't know if this happens under any other editor. My Mac slows to a crawl when this happens, and I need to use Force Quit to close them all.

**Comment by codenameone** [comment]
I've just tried to reproduce this and couldn't. Can you create a video the demonstrates the process?

**Comment by codenameone** [comment]
I've added a workaround for this into the SVN which should be available in the next update.
