### ISSUE TITLE
Disable landscape editing mode in Android and make the editor pane scrollable

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1774]
Currently Android editing mode still resizes the screen instead of increasing the scroll area, in landscape it still uses the Android 2.x notation of full screen editing. 

Both of these aren't used in newer Android OS versions and should be replaced to use the newer conventions similar to iOS.

**Comment by chen-fishbein** [comment]
fixed issue, the re-size will still happen if the there is a scrollable parent otherwise the screen will pan

**Comment by bbeckk** [comment]
Has this issue been solved. I get the same as before. 
http://stackoverflow.com/questions/37343278/landscape-search-textfield-and-keyboard-issue

**Comment by codenameone** [comment]
I just verified that this works as expected. I did run into an issue when pressing the back button in the native action bar but since we are migrating to the Toolbar API this is probably not a big deal.
