### ISSUE TITLE
RFE: SwipeableContainer should not draw the bottom containers when not swiped

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1775]
With the current implementation of SwipeableContainer, the bottom Containers are drawn, even when the top container is not swiped. 

This causes problems when the top container is transparent since the bottom containers 'show through'. The code and simulator screenshot below show the result using the built-in theme SocialBoo.

I suppose it can also has some impact on performance, especially if the bottom Containers are complex. 

`        Form hi = new Form("Welcome", BoxLayout.y());
        hi.add(new SwipeableContainer(new Button("XXX"), new Label("Label text")));
        hi.show();
`

![image](https://cloud.githubusercontent.com/assets/16265939/15453868/c5a59270-2025-11e6-9e16-240f9cc3bcba.png)

**Comment by ilanaloubser** [comment]
I've had the same problem.

Regards,
Ilana

**Comment by chen-fishbein** [comment]
fixed

**Comment by ThomasH99** [comment]
Great, thanks!
