### ISSUE TITLE
java.util.Stack is missing from the JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1776]
This is one of the supported classes...

**Comment by shannah** [comment]
Fixed. 
https://github.com/shannah/cn1-teavm-builds/commit/0384f807ece03deddcdd42dad8c8886d51c3beb4
https://github.com/shannah/cn1-teavm-builds/releases/tag/1.0.0-cn1-004
https://github.com/shannah/cn1-teavm-port/commit/1962701e5bc693fb0f7f68dbd57b98b9d927efbf
