### ISSUE TITLE
browser.window.location.hostname throws exception on javascript build

### ISSUE THREAD

**Issue by mickeyng** [codenameone/CodenameOne#1778]
Using Display.getInstance().getProperty("browser.window.location.hostname", "default str") will throw an "Uncaught TypeError: Cannot read property 'length' of undefined" in the runtime.js. This is reproducible on IE, Chrome and Firefox

runtime.js?v={APP_VERSION}:486 
Uncaught TypeError: Cannot read property 'length' of undefined
$rt_str @ classes.js?v={APP_VERSION}:9
ccih_HTML5Implementation1427_getProperty886 @ HTML5Implementation.java:971
ccu_Display784_getProperty886 @ Display.java:2805
cutc_WelcomeView1241_$init41 @ classes.js?v={APP_VERSION}:74056
cutc_WelcomeView1241_$init8 @ classes.js?v={APP_VERSION}:74722
cutc_SplashView3676_onShowCompleted769 @ classes.js?v={APP_VERSION}:205158
(anonymous function) @ Container.java:2735
ccu_Form208_onShowCompletedImpl768 @ Form.java:1710
(anonymous function) @ Container.java:2735
ccu_Display784_setCurrentForm1892 @ Display.java:1464
ccu_Display784_setCurrent838 @ Display.java:1398
ccu_Form208_show789 @ Form.java:1630
ccu_Form208_show787 @ Form.java:1608
cutc_CIPApp3541_start162 @ classes.js?v={APP_VERSION}:199399
ccih_Stub2697_run585 @ Stub.java:79
(anonymous function) @ Container.java:2735
ccu_Display784_processSerialCalls1862 @ Display.java:1150
ccu_Display784_mainEDTLoop1852 @ Display.java:967
ccu_RunnableWrapper2798_run585 @ RunnableWrapper.java:120
(anonymous function) @ Container.java:2735
cci_CodenameOneThread1163_run585 @ CodenameOneThread.java:176
(anonymous function) @ Container.java:2735
jl_Thread$12831_run585 @ TThread.java:68
(anonymous function) @ Container.java:2735
otp_Platform3141_launchThread4648 @ Platform.java:122
(anonymous function) @ runtime.js?v={APP_VERSION}:421
TeaVMThread.run @ runtime.js?v={APP_VERSION}:502
TeaVMThread.resume @ runtime.js?v={APP_VERSION}:496
callback.complete17 @ classes.js?v={APP_VERSION}:6659
otpp_AsyncCallbackWrapper4180_complete17 @ AsyncCallbackWrapper.java:37
jl_Object2_monitorEnterWait16 @ TObject.java:102
jl_Object$NotifyListenerImpl1798_run585 @ TObject.java:315
(anonymous function) @ Container.java:2735
otp_Platform3141_launchThread4648 @ Platform.java:122
(anonymous function) @ classes.js?v={APP_VERSION}:180984

**Comment by shannah** [comment]
This is fixed.  Will be on the build server for next update.
