### ISSUE TITLE
LikeButton should be deprecated and switched to opening a web page

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1781]
It seems from this discussion https://groups.google.com/d/msgid/codenameone-discussions/1b6fe65d-df0e-47cc-8dd7-068294ff0b9a%40googlegroups.com?utm_medium=email&utm_source=footer 

That Facebook no longer supports using the like button in the way we used it. So our API here needs to be deprecated and for now just open the web page for people still using it (which should work).

**Comment by amiga** [comment]
Ah nice, wish Id not wasted 2 days trying to make it work! Opening a browser works pretty good on iOS.

**Comment by chen-fishbein** [comment]
deprecated the class
