### ISSUE TITLE
Add suggested workaround for text email messages to prevent exception on Android devices

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1782]
The workaround suggested [here](https://code.google.com/p/android/issues/detail?id=38303) :

``` java
ArrayList<String> extra_text = new ArrayList<String>();
extra_text.add("See attached CSV files.");
sendIntent.putStringArrayListExtra(Intent.EXTRA_TEXT, extra_text); 
```

Should be added when plain text message is sent to prevent the exception mentioned [here](http://stackoverflow.com/questions/37219177/message-setattachment-is-silently-failing/37222048?noredirect=1#comment62484248_37222048).

**Comment by SwingGuy1024** [comment]
I would like to point out that I set the messages to "text/plain", but they arrive as "text.html". I don't know if it's your code that makes the switch or if that happens later, but you should probably make sure the mime type is what you set it to be at the point where you put this code.
