### ISSUE TITLE
Add support for the java.lang.Number class

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1783]
This is long overdue and should be added to the core VM API to make things like JSONParser more usable...

**Comment by flewby** [comment]
Please also add `compareTo()` methods, and implement `Comparable<Integer>` (etc.) so `Collections.sort()` and `Collections.binarySearch()` will work!

(Note that `String` also needs this `Comparable`)

**Comment by shannah** [comment]
There is a problem with the `byteValue()` method.  Our existing `java.lang.Long` `byteValue()` method returns an `int`, but `java.lang.Integer` returns a `byte`.  `java.lang.Number` should return a `byte` - which cooperates with `java.lang.Integer`-  but changing either the `java.lang.Integer` or `java.lang.Long` return type could break backward compatibility.  (I'm not 100% on that, but it would at least result in a different signature which might cause problems with binary compatibility).

The safest approach would be to *not* implement `java.lang.Number.byteValue()` - but then our *Number* would be different than OpenJDK's *Number* class.

@codenameone Do you have a preference of solution here?

**Comment by codenameone** [comment]
We can do that in two steps. I'm guessing the return value was a copy and paste issue, we should fix it in the CLDC classes that get compiled into the releases but should ignore that method in Number (for now). Once the new CLDC11.jar is everywhere we can just add the method to number.
