### ISSUE TITLE
Command T and other common shortcuts are typed into JavaScript port text fields

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1784]
In a JavaScript port app, edit a text field then try various browser shortcuts e.g. tab, arrow, cmd-T (for new tab) etc. Many of those type a character into the text field.

**Comment by shannah** [comment]
Fixed https://github.com/shannah/cn1-teavm-port/commit/7d1ea2194095824505ebfb7fc10b3a012a0c0292
