### ISSUE TITLE
Placing an HTML BorwserComponent in a Tab leaves an artifact on the screen in the JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1788]
The problem relates to ignoring "lightweight mode". The Tabs component asks the heavyweight widget to be in lightweight mode when it's not physically visible or partially rendered. In those cases the HTML should be rendered thru the canvas if possible or just even as a placeholder image. 
<img width="1267" alt="screen shot 2016-05-29 at 12 17 09 pm" src="https://cloud.githubusercontent.com/assets/2353641/15632363/a088c148-2597-11e6-92d9-23d48195912b.png">

**Comment by shannah** [comment]
I can't reproduce.  I think I fixed this a while back when working on a different issue.
