### ISSUE TITLE
Banner is not shown on iPhone 6 and 6+ in landscape orientation using ios.googleAdUnitId build hint

### ISSUE THREAD

**Issue by tranhiepvn** [codenameone/CodenameOne#1790]
Banner is not shown on iPhone 6 and iPhone 6+ in landscape orientation using ios.googleAdUnitId build hint although the form is scaled up and a white bar is shown at the bottom.

**Comment by codenameone** [comment]
This probably means we need to update the google play services on iOS builds. I think the right thing to do is to make them work with the new cocoapods support so they will always build against the latest version. However, since this is a big change I'm assigning it to 3.6

**Comment by shannah** [comment]
Just committed change in SVN (rev 2293) to use Cocoapods for Google ads.  This appears to fix this issue.
