### ISSUE TITLE
Need to update all documentation and process for Google+ signin

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1791]
Google+ signin was predictably deprecated, we need to update the code and docs to use Google signin:
http://orastack.com/migrating-to-google-sign-in-with-android.html

**Comment by shannah** [comment]
I think we should push this to 3.7 as this might be a pretty big change to introduce at the last minute for 3.6.  I have fixed the issue with the Google Plus login on API 23 (https://github.com/codenameone/CodenameOne/issues/1961) so at least Google login is working.

@codenameone @chen-fishbein What do you guys think?

**Comment by codenameone** [comment]
OK

**Comment by codenameone** [comment]
@shannah  I've just pushed this to 3.8 since again this is too late by now. Please deal with this early in the 3.8 cycle so we don't need to go thru this over again...

**Comment by shannah** [comment]
I have migrated GoogleConnect to use GoogleSignIn instead of Google+ on iOS and Android.  I have written documentation in the wiki [here](https://github.com/codenameone/CodenameOne/wiki/GoogleSignIn).

This should be integrated in various places throughout the site still.

**Comment by shannah** [comment]
I believe this is now integrated into the developer guide.
