### ISSUE TITLE
Validator Error Message

### ISSUE THREAD

**Issue by MoKamal** [codenameone/CodenameOne#1792]
1. when I use the Validtor.setShowErrorMessageForFocusedComponent(true), the popup error message does not close after correcting the invalid email or even after losing the focus on the TextField, and the only way to get ride of it, is to lose and gain the focus again on the TextField!.

2. No internationalisation support for the error message and inline with the Label components. for example, you can use the RegexConstraint.validEmail("invalid.email") to retrive the localized message.

3. As time of writing this!!, I have no idea on how to style the popup error component via CSS lib!!

**Comment by codenameone** [comment]
I suggest reading https://www.codenameone.com/blog/issue-submission-guideline.html before submitting an issue

These are 3 separate things all of whom should start as questions.
