### ISSUE TITLE
new ios convention of textField in android are causing that the actionListener are not firing when the keyboar is open

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#1794]
new ios convention of textField in android are causing that the actionListener are not firing when the keyboar is open, please check the issue. I would like keep the old behaivor of the keyboard when It's editing some textField. For example the Whatspp behaivor on its chat.

**Comment by codenameone** [comment]
When focus leaves the action event fires. This is used in chat applications https://www.codenameone.com/blog/issue-submission-guideline.html
