### ISSUE TITLE
jpeg images decoded incorrectly

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1796]
refer to this thread:
https://groups.google.com/forum/#!topic/codenameone-discussions/eorqZtusOHs

[src.zip](https://github.com/codenameone/CodenameOne/files/299644/src.zip)

The attached source file and resource file illustrate that jpg images which "ought to" decode
to pure white, in fact decode to slightly less.  AFAIK this only occurs on Kindle Fire, not
on the simulator, ios, or any other android platform I have available to test.

I realize that at the margin, pixel values are not guaranteed in jpg images, but pure 
white fields ought to be (and in all except one case are) decoded as they were encoded.

**Comment by codenameone** [comment]
As mentioned in the group, this is a native platform issue.
