### ISSUE TITLE
Intermittent 404's with Util.downloadImageToStorage in simulator

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1797]
In my app, I thought I was having trouble with the URLImage, so I switched to a more manual procedure using downloadImageToStorage, and then I finally checked the network monitor and it showed that for certain images (very consistently, for particular ones), it was getting 404 errors, for urls that showed up fine in a browser.  Afterwards I built for Android and all the images showed up just fine.  I haven't tested on any other device at this point.  About 20% of the images downloaded properly.  I don't know of any distinguishing characteristics that would differentiate between the images that worked and those that didn't.

**Comment by codenameone** [comment]
This isn't something we can reproduce based on the description above: https://www.codenameone.com/blog/issue-submission-guideline.html

**Comment by jegesh** [comment]
Should I post a list of the image urls I was using?

**Comment by codenameone** [comment]
I doubt that will help. If you can isolate the difference between the images that work and those that don't work it could be interesting 404 usually means that the resource wasn't found so I'm guessing this is something in the URL which isn't working e.g. using the pipe symbol etc.

**Comment by jegesh** [comment]
I solved this recently.  The problem was that the urls that didn't load contained unencoded unicode characters.  Strange that it worked on the device.  I later discovered that it didn't work on all devices, either.
