### ISSUE TITLE
isTablet() isn't implemented in the JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1800]
By default on the desktop isTablet() should return true and not show the phone UI so when isDesktop() is true isTablet() must always be true.

**Comment by codenameone** [comment]
We will need a way to turn it off when simulating a device skin though... So is tablet/desktop should allow for a case like we have in recent demos of embedding into an iPhone skin.

**Comment by shannah** [comment]
It actually was implemented, but I had it returning the opposite.  I am using the user agent string to determine whether the device is a phone.  It should return true for any device that is not a phone (i.e. tablets, desktops, etc...

You can even use the Chrome developer tools to simulate any device you like and it will behave appropriately for that device.

I have now also added an isTablet (values 0 or 1) GET parameter to override the value that is returned for this method if you want to explicitly simulate a tablet or phone.
