### ISSUE TITLE
RFE: Check box should support use of material icons

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1801]
The default checkbox symbol does not look nice on e.g. an iPhone and there is currently no way to change it to a material icon to make sure it is visually consistent with other material icons used.

**Comment by codenameone** [comment]
You can use the methods in DefaultLookAndFeel to replace the checkbox image. 
Using the material font isn't exactly native for iOS.

We should allow adding material icons to the theme as images and ideally using arbitrary icon fonts. But that's a different issue altogether.
