### ISSUE TITLE
Migrate iOS Google Play Services to CocoaPods

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1803]
Currently the Google Play Services functionality is mapped to builtin libraries. We need to provide a build hint that will use CocoaPods and the latest version of GooglePlay as currently sign in with Google is producing the same issue of a bad web login that we had with Facebook.

**Comment by shannah** [comment]
Since the google plus IOS sdk is deprecated, we'll want to migrate to Google Signin.

https://developers.google.com/identity/sign-in/ios/

https://developers.google.com/identity/sign-in/ios/start-integrating

**Comment by codenameone** [comment]
That's #1791

**Comment by shannah** [comment]
I changed Google Plus to use cocoapods.  Unfortunately even with the latest version of Google plus, it still uses Safari to try to login if the Google Plus app isn't installed.

Therefore I changed the default behaviour to show an error if you try to login without Google plus install.  The message looks like:

![image](https://cloud.githubusercontent.com/assets/2677562/16315503/7102ef4e-3937-11e6-9bed-8e4f756de732.png)

You can revert this behaviour and allow it to login using Safari by calling:

~~~~
Display.getInstance().setProperty("ios.gplus.requireGplusAppForLogin", "false");
~~~~

Before trying to log in.

I also added a build hint to revert to the old version of Google plus (without Cocoapods):

`ios.gplus.usePods=false`

The better solution to this problem will be https://github.com/codenameone/CodenameOne/issues/1791

**Comment by codenameone** [comment]
@shannah would this trigger a compile error for older use cases http://stackoverflow.com/questions/38444722/build-ios-failed-after-changing-back-to-the-old-xcode-build-servers/38449331

**Comment by tranhiepvn** [comment]
Any update?

**Comment by shannah** [comment]
I found an issue in the build server that could cause the compile error described [here](http://stackoverflow.com/questions/38444722/build-ios-failed-after-changing-back-to-the-old-xcode-build-servers/38449331).  It is fixed in SVN so should be on the build server soon.

**Comment by tranhiepvn** [comment]
Thank you
