### ISSUE TITLE
Tabs + BoxLayout Y cause an odd behavior when swiping and scrolling

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#1807]
Odd behavior with following configuration:
Tab containers, each one of them containing BoxLayout Y containers to scroll vertically.

The issue affects simulator and all platforms.

Steps to reproduce:
- In Tab1, scroll down, release and before it stops scrolling, swipe to next tab
- In Tab 2, try to scroll down. You won't be able because the scrolling is affecting Tab1 even when you are trying to scroll in Tab2.

Test Case:

``` java
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form f = new Form(new BorderLayout());  
        Tabs t = new Tabs();
        for (int x = 0; x < 3; x++) {
            Container cont = new Container(new BoxLayout(BoxLayout.Y_AXIS));
            cont.setScrollableY(true);    
            for (int i = 0; i< 3; i++) {
                Label l = new Label() {
                    @Override
                    protected Dimension calcPreferredSize() {
                        return new Dimension(Display.getInstance().getDisplayWidth(), Display.getInstance().getDisplayHeight());
                    }                    
                };
                FontImage.setMaterialIcon(l, FontImage.MATERIAL_ADD_A_PHOTO, 20);                    
                cont.add(l);                
            }            
            t.addTab("", cont);
        }
        f.addComponent(BorderLayout.CENTER, t);
        f.show();
    }
```

Video:
https://www.youtube.com/watch?v=G1zs5WTgYN0&feature=youtu.be

**Comment by shannah** [comment]
@codenameone Can you take a look at this fix and see if I'm missing anything obvious?  It fixes the test case, and my demos seem to run OK, but scrolling is complex and this is pretty core, so could benefit from another set of eyes.

**Comment by codenameone** [comment]
Makes sense but it's kind of hard to see.
