### ISSUE TITLE
Decimal places not used in L10NManager format

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#1811]
Even if specified, the variable decimalPlaces was never used to format values in [L10NManager.java](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/l10n/L10NManager.java#L182-L190). This makes the values be formatted to 2 or 3 decimal places by default.

**Comment by codenameone** [comment]
Fixed by this commit https://github.com/codenameone/CodenameOne/commit/bff9ac349bee96ee7c83c377758ece3020be100b

**Comment by JrmyDev** [comment]
It seems that with loose precision : 
` /**
     * Formats a number as a String with a fixed number of decimal places
     * @param number the number
     * @param decimalPlaces decimals
     * @return formatted string 
     */
    public String format(double number, int decimalPlaces) {
        if(decimalPlaces == 0) {
            return format((double)((long)number));
        }
            
        double pos = 10;
        for(int iter = 1 ; iter < decimalPlaces ; iter++) {
            pos *= 10;
        }
        long ln = (long)(number * pos);
        number = ((double)ln) / pos;
        return format(number);
    }`
call to format(number) loose precision when casting to String. It will works with :
`return String.valueOf(number);`

I've tried the method with decimalPlaces = 5 and it gives me 3 digits behind decimal.

**Comment by codenameone** [comment]
Maybe changing this:

**Comment by codenameone** [comment]
Maybe changing this:

````java
long ln = (long)(number * pos);
````

To this:

````java
long ln = Math.round(number * pos);
````

Will fix it? 

Can you check?

**Comment by JrmyDev** [comment]
I've debug this code. There is no problem here
 ``java
long ln = (long)(number * pos);
``
When : 
``java

**Comment by codenameone** [comment]
Did you test that on a device too? Specifically iOS?

**Comment by JrmyDev** [comment]
Yes, I have test it on iOS too ...

**Comment by codenameone** [comment]
I meant did you test the fix, not the problem?
If so a pull request might be a better form of addressing this
