### ISSUE TITLE
Ability to debug iOS application on device using Java source code

### ISSUE THREAD

**Issue by sveryovka** [codenameone/CodenameOne#1812]
Hello,

As far as I understand current approach to debugging on iOS is to:
1. Have cloud build server generate C code
2. Download generated C code and setup XCode project
3. Run XCode project and debug C code

I expect that everybody agrees that this is time consuming and not very convenient. And frankly speaking looking at generated C code I must say that for many developers this approach is quite challenging. It is not that easy to relate your Java code with generated C code.

Are there any exact plans to have more advanced debugging support when using ParparVM on iOS? I mean definitely the end desired goal is to be able to use Java code from Java IDE to debug application running on iOS device or in device emulator. 

I am pretty sure that this is not an easy task to implement but at the same time definitely will be very welcomed by existing and potential new customers.. 

Serhiy

**Comment by codenameone** [comment]
Hi, 
this is a question not an issue and as such it doesn't really fit here:
https://www.codenameone.com/blog/clarifying-our-support.html
We have such plans but naturally this is a non-trivial feature that's in the horizon rather than the immediate future.
