### ISSUE TITLE
Dialog.show doesn't show buttons unless the theme includes native

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#1815]
This form of Dialog.show:

Dialog.show(String title, String text, String okText, String cancelText)

`Dialog.show("Title","Some Content","OK",null);`

Doesn't display the buttons on the simulator or on devices if includeNativeBool is false which means you can't dismiss the dialog

**Comment by codenameone** [comment]
You need to use dialogButtonCommandsBool=true

**Comment by codenameone** [comment]
I would recommend always deriving from native theme!
