### ISSUE TITLE
How about a native general file picker?

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1820]
cn1 supports native photo/video galleries, but I think a general file picker would be welcome as well.  I had a need for a general file picker in my app, and I ended up making a hacky file picker based around a FileTree, and it was rather disappointing, especially compared to a native file picker.  The implementation, at least for the major platforms (iOS and Android) is probably pretty trivial.

**Comment by codenameone** [comment]
We evaluated this for a pro subscriber not so long ago. No. Neither iOS nor Android have any abstraction of a file picker that is usable. Mobile devices work in the other direction where an app can send a file to process in a different app.

If you need this for the platforms that do support this you can use native interfaces.
