### ISSUE TITLE
User included TTF fonts not working on UWP

### ISSUE THREAD

**Issue by bryanjbuchanan** [codenameone/CodenameOne#1822]
UWP app on WP10 does not use loaded TTF fonts, only seems to use builtin font. Download any font from Google to test.

    public class MyApplication {
    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }

        theme = UIManager.initNamedTheme("/theme", "Theme");

        final Form hi = new Form("Fonts");
        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        hi.setScrollableX(false);
        hi.setScrollableY(true);

        int[] sizes = {2, 3, 4, 6, 8};

        String[] fonts = {"ArchitectsDaughter",
            "Cabin-Regular",
            "Cabin-Bold",
            "Kalam-Regular",
            "Kalam-Bold",
            "Merienda-Regular",
            "Merienda-Bold",
            "Montserrat-Regular",
            "Montserrat-Bold",
            "NotoSans-Regular",
            "NotoSans-Bold",
            "OpenSans-Regular",
            "PlayfairDisplay-Regular",
            "PlayfairDisplay-Bold",
            "Roboto-Regular",
            "Roboto-Bold",
            "Ubuntu-Regular",
            "Ubuntu-Bold"};

        for (String s : fonts) {
            Button b = new Button(s);
            b.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {

                    Form f = new Form(s);
                    f.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
                    f.setScrollableX(true);
                    f.setScrollableY(true);

                    for (int i : sizes) {
                        int fontSize = Display.getInstance().convertToPixels(i);
                        Font ttfFont = Font.createTrueTypeFont(s, s + ".ttf").derive(fontSize, Font.STYLE_PLAIN);
                        f.add(createForFont(ttfFont, i + "mm: The quick brown fox"));
                        f.add(createForFont(ttfFont, i + "mm: 0123456789"));

                    }
                    setBackCommand(hi, f);
                    f.show();
                }

            });
            hi.add(b);
        }

        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

    private Label createForFont(Font fnt, String s) {
        Label l = new Label(s);
        l.getUnselectedStyle().setFont(fnt);
        return l;
    }

    protected void setBackCommand(final Form back, final Form f) {

        Command c = new Command("") {

            @Override
            public void actionPerformed(ActionEvent evt) {
                back.showBack();
            }

        };
        Image img = FontImage.createMaterial(FontImage.MATERIAL_ARROW_BACK, UIManager.getInstance().getComponentStyle("TitleCommand"));
        c.setIcon(img);
        f.setBackCommand(c);

        f.getToolbar().setTitleCentered(true);
        f.getToolbar().addCommandToLeftBar(c);
    }
    }

**Comment by bryanjbuchanan** [comment]
Tested by also adding fonts to theme in case it's the same as iOS (see http://stackoverflow.com/questions/38253008/codename-one-text-not-showing-using-roboto-or-keep-calm-medium-font-on-ios), but still does not change font.

      for (int i = 1; i < 10; i++) {
            Label l = new Label("The quick brown fox");
            l.setUIID("Label" + i);
            hi.add(l);
            
            l = new Label("0123456789");
            l.setUIID("Label" + i);
            hi.add(l);
        }

**Comment by shannah** [comment]
It looks UWP is just being picky about the font name.  Other platforms will take a TTF file and will just complain with a quiet warning if the font name doesn't match what's in the TTF file.   For example, I suspect that the font "Cabin-Regular" font name is actually just "Cabin".  So calling `Font.createTrueTypeFont("Cabin", "Cabin-Regular.ttf")` will work, but `Font.createTrueTypeFont("Cabin-Regular", "Cabin-Regular.ttf")` won't.

Currently looking into a way to make it "not care".

**Comment by shannah** [comment]
This is now fixed so that it will work even if you give it incorrect font names.  If the font name is incorrect, it will just use the first font in the TTF file.

**Comment by shannah** [comment]
Reopening, as the command-line build is having trouble with one of the APIs, though it builds fine in VS.

**Comment by shannah** [comment]
Actually, turns out that the build server was missing the nuget.exe CLI so it wasn't updating packages correctly.
