### ISSUE TITLE
jar URL not working in on UWP

### ISSUE THREAD

**Issue by meseriegh** [codenameone/CodenameOne#1829]
I display the help in my app using the WebBroser:
`WebBrowser html = new WebBrowser();`
`html.setURL("jar:///help.html");`
When I run the app in Windows 10 I get the following error:
cli.System.ArgumentException: the given System.Uri cannot be converted into a Windows.Foundation.Uri

**Comment by TonGalaxy** [comment]
thawatchai

เมื่อ 15 ก.ค. 2016 23:58 "meseriegh" <notifications@github.com> เขียนว่า

**Comment by shannah** [comment]
Note to self:  Got this working in local debug environment by using:

~~~~
Uri localUri = new Uri("ms-appx:///res" + path);
~~~~

Inside setBrowserUrl() of port.

Didn't commit because there are other issues with WebBrowser, that I'd like to resolve at same time.

**Comment by shannah** [comment]
This issue was fixed a while back.
