### ISSUE TITLE
iOS on camera preview form keep listening click events

### ISSUE THREAD

**Issue by jazter** [codenameone/CodenameOne#1831]
If you are experiencing an issue please mention the full platform your issue applies to:
IDE: NetBeans
OS: iOS
Device: iPhone 4 (ios 7.1.2), iPhone 5 (ios 9.3.2)
CN1 version: 3.4.3

When I call the Capture.capturePhoto() in iOS and click over the camera preview to set the autofocus, the click event pass through the camera preview and the form components catch the click event.

These are the steps to reproduce the bug:
![bug1](https://cloud.githubusercontent.com/assets/1778899/16927171/ca2882a0-4cf1-11e6-8624-ea41acb17428.png)
![bug2](https://cloud.githubusercontent.com/assets/1778899/16927170/ca280f5a-4cf1-11e6-8403-9dcaaa6b06de.png)
![bug3](https://cloud.githubusercontent.com/assets/1778899/16927172/ca2a1c8c-4cf1-11e6-9b1d-eb3913bb03e9.png)

**Comment by codenameone** [comment]
Thanks, fixed here: https://github.com/codenameone/CodenameOne/commit/f367e8e7e9c424f3ef601ac758cf9d53a30c761f
