### ISSUE TITLE
problems resizing related to keyboard

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1832]
There are some circumstances where the screen doesn't reformat properly,  related to the appearance/disappearance of the keyboard.  I believe this is a recent problem on Android only.

Run the program below, tap the text area to bring up the keyboard, and rotate the device.
Note that the form doesn't reformat to the new device geometry.   This reconfiguration failure
also happens sometimes when you have raised and lowered the keyboard.

I also note that "paint" is called a lot of times before the screen stabilizes.

''''Java
//
// this version shows the keyboard reshape problem
//

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.TextField;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;

public class Dtest  {
	
	private TextField text;
    private Form current;
    @SuppressWarnings("unused")
	private Resources theme;
 
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    int loops = 0;
   
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi >>0 World");
         current = hi;
        hi.setLayout(new BorderLayout());
        hi.addComponent(BorderLayout.SOUTH,new TextField());
        hi.addComponent(BorderLayout.CENTER, new Label("Hi Textfield") 
        {
        
            @Override
            public void paint(Graphics g) {
             	int w = getWidth();
            	int h = getHeight();
             	g.setColor(0xfaf9f7f);
            	g.fillRect(0,0,w,h);
            	loops++;
            	g.setColor(0x0);
            	g.drawString("text redraw "+loops,100,100);  
            }
            
        });
        hi.show();
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }
}
''''

**Comment by codenameone** [comment]
Thanks, this looks like a very good idea for debugging this issue

**Comment by shannah** [comment]
This should be fixed in this commit.
https://github.com/codenameone/CodenameOne/commit/ac3936bc9ea2d5affeee53b30ea99ec99f83f2d0
