### ISSUE TITLE
Designer does not properly scale added multi-images

### ISSUE THREAD

**Issue by SwingGuy1024** [codenameone/CodenameOne#1833]
When adding a multi-image to the designer, it scales the original to many different sizes, but the scaling algorithm produces scaled-down images with very poor anti-aliasing. There are better ways to scale an image. The following method can be used to scale an image down and get a much higher quality image:

` 
     
		/**
		 * Adapted from http://stackoverflow.com/questions/7951290/re-sizing-an-image-without-losing-quality
		 * All imports are in java.awt.* or java.awt.image.*
		 *
		 * @param img The Image to scale
		 * @param targetWidth target width
		 * @param targetHeight target height
		 * @return A scaled image copy of the original image.
		 * @throws IllegalArgumentException If a negative target value is provided.
		 */
		public BufferedImage getScaledInstance(BufferedImage img,
		                                       int targetWidth,
		                                       int targetHeight
		) {
			if (targetWidth < 0) {
				throw new IllegalArgumentException(String.format("Negative target sizes not allowed: %d", targetWidth));
			}
			if (targetHeight < 0) {
				throw new IllegalArgumentException(String.format("Negative target sizes not allowed: %d", targetHeight));
			}
			int type = (img.getTransparency() == Transparency.OPAQUE) ?
					BufferedImage.TYPE_INT_RGB : BufferedImage.TYPE_INT_ARGB;
			BufferedImage ret = img;
			int w;
			int h;
			// Use multi-step technique: start with original size, then
			// scale down in multiple passes with drawImage()
			// until the target size is reached
			w = img.getWidth();
			h = img.getHeight();
			
			do {
				w = reduce(w, targetWidth);
				h = reduce(h, targetHeight);
				
				BufferedImage tmp = new BufferedImage(w, h, type);
				Graphics2D g2 = tmp.createGraphics();
				g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
				g2.drawImage(ret, 0, 0, w, h, null);
				g2.dispose();
	
				ret = tmp;
			} while ((w != targetWidth) || (h != targetHeight));
			
			return ret;
		}

		private int reduce(int dimension, int targetDimension) {
			if (dimension > targetDimension) {
				dimension /= 2;
			}
			if (dimension < targetDimension) {
				dimension = targetDimension;
			}
			return dimension;
		}
`

**Comment by amiga** [comment]
so this entire time images have been scaling badly?

**Comment by codenameone** [comment]
No. This is only for the multi-image import. This is only for very specific types of image scaling, in most cases you wouldn't notice the difference.

**Comment by amiga** [comment]
Yes, I haven't noticed it at all, so I was confused.

**Comment by SwingGuy1024** [comment]
The problem was that it did a lousy job of anti-aliasing when it produced very small images. Without this fix, reducing a 200x200 pixel image to, say 28x28 pixels, the anti-aliasing was terrible. With this fix, it will do a much better job anti-aliasing the tiny images, which is where it's needed most. Thanks for putting this in.
