### ISSUE TITLE
iOS for loop breaks on substring exception inside a try-catch block

### ISSUE THREAD

**Issue by jazter** [codenameone/CodenameOne#1834]
If you are experiencing an issue please mention the full platform your issue applies to:
IDE: NetBeans
OS: iOS
Device: iPhone 4 (ios 7.1.2), iPhone 5 (ios 9.3.2)
CN1 version: 3.4.3

I found a very rare bug in ios, when an exception occurs when trying to get a substring of an empty string inside a for loop, even when this code is inside a try-catch block, the system breaks the loop. Here is the code to reproduce it:

```
String[] names = {"Ulises", "John", "", "Alexis", "Willy"}; 
String resultStr = "";
for (int i = 0; i < names.length; i++){
    try{
        String firstChar = names[i].substring(0, 1);
        resultStr += firstChar;
    }catch(Exception ex){
        Dialog.show("Error Dialog", "This dialog will show but the for statment should not have to break", "ok", "cancel");
    }
}
Dialog.show("Result Dialog", resultStr, "ok", "cancel");
```

**The result string should be "UJAW" but in iOS the result string is "UJ".**

**Comment by shannah** [comment]
I'm going to need a full test case.  I tried copying and pasting this snippet into my own test case and it worked correctly on the iOS simulator (Xcode).

![image](https://cloud.githubusercontent.com/assets/2677562/17119874/99f49876-527d-11e6-8d53-6dac973fb3d1.png)

My test case is here:

https://gist.github.com/shannah/5756c99cf6b669f6527c55ee25e5abe8

**Comment by codenameone** [comment]
Try looking at #1701 
Who knows, it might be a device only thing... Those happen sometimes. Maybe it's byte alignment differences etc.

**Comment by jazter** [comment]
Have you tried on a physical device? I can reproduce it on an iphone5 (ios 7.1.2) and iphone6 (ios 9.3.2).

**Comment by shannah** [comment]
If this fails on a physical device, but succeeds in the iOS simulator, then it is a problem with LLVM.  Highly unlikely.  But, no, didn't try on device.  

I'll be looking into #1701 today to see if that gets me closer to the issue.

**Comment by codenameone** [comment]
Not necessarily. We might have a bug related to big/little endian or assumptions about alignment that don't apply correctly. So when we unwind the stack something might break.

**Comment by shannah** [comment]
Looks like https://github.com/codenameone/CodenameOne/commit/f9485a2bf4128be293cb8bd69de63a691b490dfd fixed this issue.
