### ISSUE TITLE
FloatingHint is not working properly on multiple time of fucus

### ISSUE THREAD

**Issue by smpatel** [codenameone/CodenameOne#1836]
FloatingHint is not float when it refocus 
## How to reproduce:

I have created two Textfiled having FloatingHint in a form. After initialising form,  focus is on first Textfiled and hint is lifted up properly.

Then I am writing in first Textfiled and then second Textfiled. After I click on the Form anywhere and then if I click on fist textfileld, the focus is not comming to textfild and I can not edit.

Now if I click on second Textfiled and then click fist textfiled. it will work. What could be the problem?

**Comment by codenameone** [comment]
Referencing relevant group discussion: https://groups.google.com/d/msg/codenameone-discussions/ohAxrGBdWjM/_x4RNCFPBgAJ
