### ISSUE TITLE
Runtime adding components to a container is not shown in device simulator

### ISSUE THREAD

**Issue by hristo-vrigazov** [codenameone/CodenameOne#1844]
Steps to reproduce:
1. Create a form with a button in it.
2. When button is clicked, add a label to the form.
The labels are not shown in device simulator, but are shown on actual devices correctly.
To reproduce, just paste this in the start method:
`        Form hi = new Form("Hi World");
        Button button = new Button("Add");
        button.addActionListener((actionEvent) -> {
            hi.add("message");
        });
        hi.add(button);
        hi.show();
`
See the attached gif
![out](https://cloud.githubusercontent.com/assets/14914140/17405493/56cda770-5a68-11e6-900b-b1c55d1a99ba.gif)

**Comment by codenameone** [comment]
That's "by design". I suggest reading the revalidate() section here: https://www.codenameone.com/manual/basics.html

**Comment by hristo-vrigazov** [comment]
Would you be more concrete? I searched for "revalidate" and found nothing in the page

**Comment by codenameone** [comment]
That paragraph I was referring to was moved here:  https://www.codenameone.com/manual/animations.html

**Comment by hristo-vrigazov** [comment]
Great! Thanks a lot!
