### ISSUE TITLE
Pan & Zoom Within Charts don't make sense

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1850]
The chart support has builtin pan/zoom support that just increases/decreases the surface and is overly hardcoded. 

E.g. it enlarges the axis as well as the chart data and when zooming out you can have a "stamp" chart in the middle of white space. 

This is really hard to use and inconsistent with similar products. Pan and Zoom should manipulate the renderer properties to shift the content of the chart around/zoom it. This should have no effect on the AXIS of the chart.

As a sidenote the renderer feature to show zoom buttons on the chart doesn't work... It should either be deprecated or fixed.

**Comment by shannah** [comment]
The current zoom implementation was developed with the pie-chart in mind - and it makes more sense in that context.

Adding zoom at the renderer level is a good idea too.  We can add methods to renderer to check if the renderer supports pan and zoom, and zoom/pan methods to perform the zooming.  These would have to be implemented separately by each renderer.  Then the ChartComponent could tap into the renderer-supported zoom if implemented - and fall back to the default zoom/pan behaviour if not implemented.

I'll deprecate the zoom buttons.

**Comment by shannah** [comment]
Made improvements here for XYCharts
https://github.com/codenameone/CodenameOne/commit/99d13827b2ea8fad1e068a6d25b3e9c100bd06fd
