### ISSUE TITLE
Build ads hint for windows universal

### ISSUE THREAD

**Issue by developmentblog** [codenameone/CodenameOne#1852]
There are some options for add ads to windows universal apps in as windows native apps. Part of my business is related to ads so would great if I can build one single app to all platforms with ads in every app.

Thanks.

**Comment by codenameone** [comment]
We are moving towards a cn1lib approach for ads. The build hint approach predated newer cn1lib efforts which are the way forward, those can be made portable to Windows more easily. 
I'm not sure UWP even has admob support.
