### ISSUE TITLE
Tests are not run in IntelliJ Idea

### ISSUE THREAD

**Issue by hristo-vrigazov** [codenameone/CodenameOne#1853]
I have a new Java 8 Codenam One project in IntelliJ. It works fine, but when I record a test and then "Run unit tests" from Codenameone dropdown, I get the following error:

java.lang.ClassNotFoundException: com.codename1.impl.javase.TestExecuter

Copied from [here](https://groups.google.com/forum/#!topic/codenameone-discussions/rZSos-SXOX4)

**Comment by hristo-vrigazov** [comment]
Would you suggest some workarounds for this until the  release? It is critical for us. Or how to migrate the project to Eclipse / Netbeans?

**Comment by codenameone** [comment]
I looked at this just now and it seems that there is a simple fix and workaround (which took me a while to figure...). Open the build.xml file and fine the block:

````xml
    <target depends="compile-test" name="-do-test-run">
        <echo>JavaSE.jar is: ${file.reference.JavaSE.jar}</echo>
        <!-- JavaSE.jar is added here since the test execution might fail otherwise for a pre-existing project -->
        <java classpath="dist/unitTests.jar:${javac.test.classpath}:${file.reference.JavaSE.jar}" classname="com.codename1.impl.javase.TestRunner" fork="true">
            <arg value="${codename1.packageName}.${codename1.mainName}" />
        </java>
    </target>
````

change `<java ` to `<java fork="true" ` we'll fix this for the next plugin update

**Comment by hristo-vrigazov** [comment]
Awesome, thanks a lot!
