### ISSUE TITLE
Native interfaces on UWP

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#1857]
Still need to implement native interfaces on UWP.

I'm assuming we'll generate these in the native/windows directory?  @codenameone

**Comment by codenameone** [comment]
I think it should use the code from the win directory that we used for the old port. We can move forward and most of the infrastructure should be there.

**Comment by shannah** [comment]
OK. That would be easier.  I was just apprehensive about breaking it for people who are still deploying to the old winphone ports.

**Comment by shannah** [comment]
This is now implemented in SVN.  Will be available in next server update (Friday).   There were also some changes necessary to how the native implementations are generated in the plugin.  These will be available in the next plugin update, which will take longer.
