### ISSUE TITLE
Swiping between tabs while scrolling breaks scrolling

### ISSUE THREAD

**Issue by CS-JSI** [codenameone/CodenameOne#1858]
Dear CNO,

I have prepared a short video of demonstration on Simulator for this bug. Exactly the same is happening on iOS, while on Android only the need for second pull (as explained latter) is required. When a pointer is being pressed in video, a circle is drawn around it.

[Video](http://cs.ijs.si/CodeNameOne.mov)

In video you can see, how the content is left in the middle of the screen after swipe during the scroll (this only happens on Simulator and iOS). And if the swipe is done while the content is being pulled down, the next tab content needs to be pulled down twice (this part is also affected on the Android) for the the scrolling to work (see in the first seconds of the video, that I needed to pull twice on "Monday" for actual scroll to happen). And if I do that (pull at least once), the content of the previous tab has corrected itself (moved to the top), but if I do not, the content is wrongly positioned. So it seems that the next pull that is done on the tab (that was swiped while pulling) still affects the previous tab and not the current one (this can be clearly seen in video). I really hope you can identify the problem and fix it, since it is really undesirable feature and makes application look "bad".

I am attaching a response from Shai from discussion forum where this was firstly reported:

> I think we can workaround the latter but I'm not so sure. We normally block sidescrolling when scrolling vertically but since tab swiping is a special case it isn't affected by that block. File an issue on that and we might be able to resolve it.

Best regards,
CS

**Comment by codenameone** [comment]
Relevance link: https://groups.google.com/d/msg/codenameone-discussions/DN0qEfP-s0c/4CQhruOECQAJ

**Comment by codenameone** [comment]
I've evaluated the complexity of fixing this and I'm not sure it's worth it. I think disabling the tabs swiping should work well for solving this case and is probably the right thing to do overall. The alternative would mean checking the entire component hierarchy for every drag event in the tabs which will make the whole thing even slower than it already is.
