### ISSUE TITLE
The text is overlapping in TextField

### ISSUE THREAD

**Issue by jazter** [codenameone/CodenameOne#1867]
Device: Android (Moto G, Galaxy s6, Galaxy s7)
Android: (5.0, 6.0)

To reproduce it:

Add two TextInput on a Form and run the app in Android:

Type the word "Hello" in the first TextInput and type the word "World" in the second TextInput.

![photo670714849452469256](https://cloud.githubusercontent.com/assets/1778899/17980817/9f48d9e8-6ac6-11e6-85a1-d5bdd3e540a7.jpg)

Select the first TextInput and click Backspace until the start of the TextInput (The word will not be erased)
Type the word "Second"

![photo670714849452469257](https://cloud.githubusercontent.com/assets/1778899/17980815/9f47b234-6ac6-11e6-8820-3f414d6e6647.jpg)

Select the second TextInput and do the same: Click Backspace until you reach the begining of the TextInput and type the word "Third"

![photo670714849452469258](https://cloud.githubusercontent.com/assets/1778899/17980816/9f47ac6c-6ac6-11e6-9aa3-2eda655da87d.jpg)

Then close the Keyboard

![photo670714849452469254](https://cloud.githubusercontent.com/assets/1778899/17980819/9f49297a-6ac6-11e6-965e-64b11b47ea14.jpg)

**Comment by shannah** [comment]
I wasn't able to reproduce this issue, however, I believe this is related to some other issues with native text field focusing that I was able to reproduce with my tests.  So I think this should be resolved.  (Will be included with next server update).
