### ISSUE TITLE
UWP Infinite Progress image

### ISSUE THREAD

**Issue by bryanjbuchanan** [codenameone/CodenameOne#1871]
The default infinite progress image doesn't spin about itself but the whole image seems to spin around a point at the bottom RHS of the image.

```java
        hi = new Form("Test");
        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        hi.setScrollableY(true);
        hi.add(new InfiniteProgress());
        hi.show();
```

**Comment by shannah** [comment]
Narrowed this down a little today.  It appears to be a problem with the port's font sizing for the font image that it used for the progress.  Will drill down further tomorrow and hopefully get this fixed.  It is likely related to some other font sizing issues that I've observed in other apps (like Kitchen sink) in the UWP port.

**Comment by bryanjbuchanan** [comment]
Just tried this and still no rotating about itself (with latest libs).

**Comment by bryanjbuchanan** [comment]
Just tried this and still not rotating about itself.
