### ISSUE TITLE
Error in toolbar.java

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1873]
This looks like an error in toolbar.java, although surprising that it hasn't been caught somewhere. 

createCommandComponent is called with `commands`, but it is the global variable `overflowCommands` that is being used inside the method: 

```java        
       @Override
        protected Component createCommandComponent(Vector commands) {
            return createOverflowCommandList(overflowCommands); // <-- should be commands
        }
```

**Comment by codenameone** [comment]
No that looks like the correct value. If it was commands it would include additional commands.
