### ISSUE TITLE
Vague error message when adding missing device to provisioning profile.

### ISSUE THREAD

**Issue by SwingGuy1024** [codenameone/CodenameOne#1874]
I went to Codename One Preferences and hit the certificate generator button. After logging in, I tried to add another iPhone to my provisioning profile. But I made a mistake. I didn't realize I needed to add it first on the apple site, at https://developer.apple.com/ios/manage/provisioningprofiles/index.action

The trouble is that the error message was useless. This is the error message I got: 

(RuntimeError) Please login using `Spaceship::Portal.login('user', 'password')`

Huh?

The UI could supply a more useful error message here. (Spaceship? Really?)

**Comment by shannah** [comment]
Fixed yesterday.
