### ISSUE TITLE
Include source doesn't work for UWP appstore builds

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1880]
When using include source and sending an appstore build the resulting sources file is HUGE:

```
     [exec]     54 Warning(s)
     [exec]     0 Error(s)
     [exec] 
     [exec] Time Elapsed 00:02:07.04

BUILD SUCCESSFUL
Total time: 2 minutes 33 seconds
Result file exceed 200mb limit indicating a potential problem: UWPProject-sources.zip
```

This used to generate a memory issue but I just made it fail the build. I'm guessing some binaries slipped into the sources for this build type.

**Comment by shannah** [comment]
Fixed in SVN.  Will be included in next server update.
