### ISSUE TITLE
iOS Signing Tool supplies incorrect file paths. 

### ISSUE THREAD

**Issue by SwingGuy1024** [codenameone/CodenameOne#1882]
I'm launching the Codename One Preferences from the IntelliJ IDE. When I click on the iOS Signing Tool, I see some strange behavior. If I hit the browse button next to either Certificate field it asks me to choose a file. If I then click on a file, the path that it puts into the field is all wrong. It should be the path to the file I just clicked on, but it's this:

file:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/appstore_certificate.p12

That's the wrong place for a certificate, it's not the path to the file I clicked on, and there's no certificate in that directory.

**Comment by codenameone** [comment]
This seems to be related to [this stackoverflow question](http://stackoverflow.com/questions/39482677/wrong-paths-in-codename-one-preferences/39503371), I wasn't able to reproduce it in full although I did fix the `file:` prefix. The paths I got were correct despite all my attempts.

My only guess is that this might be an issue that affected an earlier version of the tool so I've added a version number to the title (`1.13` in my current version). If this still happens in the next plugin update and the title of the preferences is `1.13` or newer I'd like to know.
