### ISSUE TITLE
SQLite support for the Windows UWP port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1889]
This is currently missing in the implementation but should be there for the production release of the VM

**Comment by shannah** [comment]
@codenameone You may need to install the SQLite VSIX extension on the server for builds to work after this.  It can be downloaded here:

https://visualstudiogallery.msdn.microsoft.com/4913e7d5-96c9-4dde-a1a1-69820d615936

You simply double click the visx file and follow the prompts.

It is possible that you don't need to install it.  If you are able to build the SQLSample demo app without installing this, then I wouldn't bother installing it.

**Comment by codenameone** [comment]
FYI seems to work without the install
