### ISSUE TITLE
CodeNameOneBuildClient: sideMenu command "cmd_null"

### ISSUE THREAD

**Issue by ahmedengu** [codenameone/CodenameOne#1891]
Greetings,

I couldn't find a repository for CodeNameOneBuildClient.jar thus this issue.
some of the issues mentioned [here](https://groups.google.com/forum/#!topic/codenameone-discussions/1SFxicw369A) but i think he did not open an issue as i couldn't find it.

com.codename1.build.client.GenerateGuiSources :

1- in the main there is:
```
g.setSrcDir(new File("/Users/shai/temp/Travel2gether2/src"));
g.setGuiDir(new File("/Users/shai/temp/Travel2gether2/res/guibuilder"));
```

2- missing semicolon line 472 
`result.append("}\n");`
to 
`result.append("};\n");`

3- returns null : lines (486, 490, 494, 499, ...)
`                        result.append(uiXMLData.getCommandVarName());
`

4- missing ')': line: 827 appendCommandIcon
`result.append("\");\n");
`
to 
` result.append("\"));\n");
`

also from the thread: "setToolBar is deprecated, use setToolbar (lowercase b)"

Best regards,
Ahmed

**Comment by codenameone** [comment]
Thanks, these will be fixed for the next update. We just released an update yesterday so this will probably take 3 weeks or so to make it out.
