### ISSUE TITLE
ANDROID : MapContainer and play services Version

### ISSUE THREAD

**Issue by romancanoniero2** [codenameone/CodenameOne#1892]
Please, upgrade the version dependence of the playservice on android the current is working with the com.google.android.gms/play-services-maps/8.3.0/ and the last version is 9.4 who includes a lot of improvements in maps 

i need to execute the following procedure:

GoogleMap.setMaxZoomPreference(10.0f);

thanks!

**Comment by romancanoniero2** [comment]
hi chen! recently i take notice that the version 3.6 will be on air on january 17. are no chances to get the update, before? thanks!

**Comment by codenameone** [comment]
We added a new experimental build hint to set the play services version, I forget the name but it's already listed in the docs https://www.codenameone.com/manual/advanced-topics.html
I'm marking this as fixed
