### ISSUE TITLE
ios 10 Camera and lock screen

### ISSUE THREAD

**Issue by mcellinpaul** [codenameone/CodenameOne#1895]
I have found that on ios 10 devices, if my application uses the camera (Camera.capture()) then later locks the screen (or times out and goes to lock screen). The application crashes/is terminated.

I suspect it relates to the new camera n lock screen feature that ios 10 has but that is just my feeling. Either way, it makes any app that uses the camera liable to crashes/data loss.

**Comment by shannah** [comment]
I just upgraded my phone to iOS 10 and I am trying to reproduce this with one of my apps that uses Capture, but I can't seem to reproduce it.  Steps I have tried:

1. Call capture() to open up the native camera screen.
2. With camera still open, I press the "power" button on side of phone.
3. Turn the phone back on, and proceed.

I have also tried turning the phone on and off after having completed a capture and it still seems to work OK.

iPhone 6S iOS 10.0.2 (14A456)

**Comment by mcellinpaul** [comment]
Hi Steve,

I have done some further investigate and created a small demo app rather 
than using the photos within my own code. I have a very simple app with 
a single class - I have pasted the code below. I can't really create an 
app for you to run as it's apple so had to build it with my own 
certifacate/provisioning profile etc.

I have a button which calls Capture.capturePhoto(); and does nothing 
else. As it is difficult to see if the app has restarted, in the init() 
method I have a lael which logs the current UTC Time.

Upon running it, if I do not activate the button I can go back to home 
screen, restart the app and the time displayed does not change, it it 
has not restarted. If I take a photo, come back to the form, then even 
just press the home button then the time displayed has changed, the 
application has restarted.

This is obviusly more noticable in my real app as the user gets the 
splash screen back and has to log in again and will have lost any 
unsaved work.

Regards,

Paul

**Comment by mcellinpaul** [comment]
Hi Steve,

Sorry for the delay in replying, I was out of the office yesterday. I'm 
looking into this a bit more but the problem occurs of you lock the 
screen after returning from the native camera screen. E.g. if I run this 
code :-

Button b1 = new Button("Take Photo");
         b1.addActionListener(new ActionListener() {
             public void actionPerformed(ActionEvent e) {
               String photoPath = Capture.capturePhoto();

             }
         });

Then return back to the form that this button is on, then lock the 
screen (power button). Then press the home button twice (once to open 
onto lock screen, then to unlock, adn the app is no longer running.

Thanks,

Paul

**Comment by mcellinpaul** [comment]
I forgot to paste in the code of my demo... Sorry...

public class MyApplication {

     private Form current;
     private Resources theme;

     public void init(Object context) {
         theme = UIManager.initFirstTheme("/theme");

         // Enable Toolbar on all Forms by default
         Toolbar.setGlobalToolbar(true);

         // Pro only feature, uncomment if you have a pro subscription
         // Log.bindCrashProtection(true);

         Form hi = new Form("Welcome", new 
BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
         final Label apple = new Label(theme.getImage("apple-icon.png"));
         final Label android = new 
Label(theme.getImage("android-icon.png"));
         final Label windows = new 
Label(theme.getImage("windows-icon.png"));


         Calendar cal = Calendar.getInstance();
         long time = cal.getTime().getTime();
         Label l = new Label("Time start is " + time);
         Button b1 = new Button("Take a Photo");
         b1.addActionListener(new ActionListener() {
             public void actionPerformed(ActionEvent e) {
                 final String photoPath = Capture.capturePhoto();

             }
         });
         hi.addComponent(BorderLayout.NORTH, l);
         hi.addComponent(BorderLayout.CENTER, b1);
         hi.show();
     }

     public void start() {

     }

     public void stop() {
         current = Display.getInstance().getCurrent();
         if(current instanceof Dialog) {
             ((Dialog)current).dispose();
             current = Display.getInstance().getCurrent();
         }
     }

     public void destroy() {

     }

}

**Comment by shannah** [comment]
I updated to Xcode 8 on my development machine to try to reproduce this issue.  I wasn't able to reproduce this issue exactly, but I did find that if I compile with Xcode 8, I need to include some extra values in my Info.plist if I want to use the camera. 

http://stackoverflow.com/questions/39465687/nscamerausagedescription-in-ios-10-0-runtime-crash

Try adding the following to your ios.plistInject build hint:

`ios.plistInject=<key>NSCameraUsageDescription</key><string>Need to use the camera</string>`

And see if it resolves the issue for you.

I have added some auto detection in my local version of the build server script to add generic description here if it detects that you are using the capture API, but I don't want to deploy it yet as Xcode 8 has broken my local build toolchain - so I can't test it properly yet.

**Comment by mcellinpaul** [comment]
Hi Steve,

Thanks for looking at it. I haven't an iPhone with ios 10 on it with me 
at the moment but did a build with your suggestion and sent it to 
someone in the office but it failed. I just added a build hint of 
ios.plistInject and set it to 
<key>NSCameraUsageDescription</key><String>Need to use the 
camera</string> in the build hints in eclipse.

One thing though this versioning makes me think of is that I am still 
having to use "iphone_old" as the target_type as just useing "iphone" is 
giving me build errors with the certificate. Could this cause it do you 
think? I shall get the error info together about this and get it over to 
you shortly.

Kind regards,

Paul

**Comment by mcellinpaul** [comment]
Hi Steve,

Further to my mentioning that I'm having to use iPhone_old, if I try and 
use the target type "iphone" I get this at the end of the error log. Any 
clues on the problem? I'm using the same signing info in the build as 
when it successfully does an iphone_old build.

I'll post this to the main discussions board as well.

Thanks

LOGNAME=administrator
_=/usr/bin/env
+ /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -exportArchive -archivePath ApplicationWrapper.xcarchive -exportPath /var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/build1347080266284814304xxx/result -exportOptionsPlist /var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/export8364358331285155482.plist -verbose PROVISIONING_PROFILE=790dba8e-41b9-4541-b71a-4780864e6073 'CODE_SIGN_IDENTITY=iPhone Distribution: eSay Solutions Limited (EA67SMA4LD)' KEYCHAIN=/Users/administrator/Library/Keychains/temp1478080279572.keychain CODE_SIGN_ENTITLEMENTS=/var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/Entitlements1956301248681602482.plist
2016-11-02 05:07:05.069 xcodebuild[75594:19129460] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/ApplicationWrapper_2016-11-02_05-07-05.068.xcdistributionlogs'.
2016-11-02 05:07:05.096 xcodebuild[75594:19129460] [MT] DeveloperPortal: Using pre-existing current store at URL (file:///Users/administrator/Library/Developer/Xcode/DeveloperPortal%207.3.1.db).
2016-11-02 05:07:05.280 xcodebuild[75594:19129460] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fd0fcbc7ca0>: Error Domain=IDEDistributionErrorDomain Code=1 "(null)"
error: exportArchive: The operation couldnâ€™t be completed. (IDEDistributionErrorDomain error 1.)

Error Domain=IDEDistributionErrorDomain Code=1 "(null)"

** EXPORT FAILED **

Failed export step
2016-11-02 10:07:04 +0000 [MT] Step failed: <IDEDistributionSigningAssetsStep: 0x7fcf51632470>: Error Domain=IDEDistributionErrorDomain Code=1 "(null)"


2016-11-02 10:07:04 +0000 [MT] Running step: IDEDistributionSigningAssetsStep with <IDEDistributionContext: 0x7fcf53e1f530; archive(resolved)='<IDEArchive: 0x7fcf53da3880>', distributionTask(resolved)='2', distributionMethod(resolved)='<IDEDistributionMethodDevelopmentSigned: 0x7fcf53db59b0>', teamID(resolved)='(null)'>
	Chain (2, self inclusive):
	<IDEDistributionContext: 0x7fcf53e1f530; archive = '(null)', distributionMethod='<IDEDistributionMethodDevelopmentSigned: 0x7fcf53db59b0>', teamID='(null)'>
	<IDEDistributionContext: 0x7fcf53da46b0; archive = '<IDEArchive: 0x7fcf53da3880>', distributionMethod='(null)', teamID='(null)'>
</IDEDistributionContext: 0x7fcf53e1f530>


2016-11-02 10:07:04 +0000 [MT] Available distribution methods: (
     "<IDEDistributionMethodiOSAppStoreExport: 0x7fcf53db57d0>",
     "<IDEDistributionMethodAdHoc: 0x7fcf53db5d10>",
     "<IDEDistributionMethodEnterprise: 0x7fcf53db5950>",
     "<IDEDistributionMethodDevelopmentSigned: 0x7fcf53db59b0>"
)
2016-11-02 10:07:04 +0000 [MT] IDEDistributionItem init <DVTFilePath:0x7fcf53da4260:'/var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/build1347080266284814304xxx/dist/ApplicationWrapper.xcarchive/Products/Applications/ApplicationWrapper.app'>
2016-11-02 10:07:04 +0000 [MT] Set distributionItems on context: (
     "<IDEDistributionItem: 0x7fcf51640f90 'uk.co.esayltd.mobile.workmobile.codenameone' '<DVTFilePath:0x7fcf53da4260:'/var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/build1347080266284814304xxx/dist/ApplicationWrapper.xcarchive/Products/Applications/ApplicationWrapper.app'>'>"
)
2016-11-02 10:07:04 +0000 [MT] -[IDEDistributionProvisioning _itemToSigningInfoMap:]: Locating assets for items = (
     "<IDEDistributionItem: 0x7fcf51640f90 'uk.co.esayltd.mobile.workmobile.codenameone' '<DVTFilePath:0x7fcf53da4260:'/var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/build1347080266284814304xxx/dist/ApplicationWrapper.xcarchive/Products/Applications/ApplicationWrapper.app'>'>"
)
2016-11-02 10:07:04 +0000 [MT] Disqualifying <DVTSigningCertificate: 0x7fcf53e6d340; name='iPhone Distribution: eSay Solutions Limited (EA67SMA4LD)', hash='8CA541C42B972ABE22314A7E27E09258FEBAF070', certificateKind='1.2.840.113635.100.6.1.4'> due to certificateKind (input 1.2.840.113635.100.6.1.2 doesn't match 1.2.840.113635.100.6.1.4)
2016-11-02 10:07:04 +0000 [MT] -[IDEDistributionProvisioning _signingCertificatesApplicableForTeamID:certificateKind:isForInstaller:error:]: identityCertificatesMatchingKind [kind=1.2.840.113635.100.6.1.2] = (
)

**Comment by shannah** [comment]
Was the build that you tried using the test app that you provided in this issue or a different app?  Let's try to stay on the test app to rule out other factors.

It is possible that the "iphone_old" toolchain has problems for iOS 10.  If you create a fresh certificate and distribution profile using the certificate wizard for the test app then it will build correctly.  I just did that myself and the test works on iOS 10 with the plistInject.

**Comment by mcellinpaul** [comment]
Thanks Steve, much appreciated.

I tried the pListInject with my actual app not the test one. I shall 
give that a try soon, but when I built the test app I also used 
iphone_old as I was using the same certificate and provisioning profile 
and had the same issues when I build with "iphone" not "iphone_old" - 
it's starting to look like that is where the problem lies. I shall try 
to get round this issue tomorrow at some point when I can (meetings etc 
in the morning).

So you suggest that I create brand new certificate provisioning profiles 
to build with and then I shouldn't need to use iphone_old? Again I will 
do that tomorrow when I can access a Mac to do it from.

However, are you saying there is a tool that codename one provide to 
generate a debug certificate/provisioning profile (when you mention the 
certificate wizard?)

Thank you,

Paul

**Comment by mcellinpaul** [comment]
Ah yes, I see - use the generate button - I shall try and create my 
certificates that way. Thanks again Steve.

Paul

**Comment by shannah** [comment]
I suggest not using "iphone_old".  That is an old toolchain and I have run into numerous cases where the build works, but something fails at runtime - especially with new versions of iOS.  If "iphone" fails, then there is a problem that needs to be fixed either in the certificate, provisioning profile, the app entitlements, or some required build hints.  It's frustrating, but the error log generally offers a clue as to where to look.

For example, the error log you provided showed that the certificate kind didn't match that build type.  That isn't immediately actionable, but it does narrow it down.

**Comment by mcellinpaul** [comment]
Thanks Again Steve,

I'm going to create the cedrtificates from your Generate wizard. I 
assume its compatable from ap store debug and enterprise certificates 
(we use them all).

Thanks,

Paul

**Comment by shannah** [comment]
Closing this issue as it was indicated in the Google discussion group that the issue resolved with the certificates issue was sorted out.
