### ISSUE TITLE
Media Not Stopping, Stretching and Not Working in Full Screen on Android (making it effectively unusable).

### ISSUE THREAD

**Issue by tobymundy** [codenameone/CodenameOne#1896]
I have an app which I made over two years ago which has a list of videos. When one of the list buttons is clicked, the media played full screen. This was working perfectly OK on Android (I have't tried other platforms) until I resubmitted it to the build server on 31-07-2016. After this I noticed that the videos were no longer working full screen. In September 2016, I resubmitted the app to the build server and now there are a couple more things that don't work. The most noticeable feature is that the video is stretched in portrait orientation to fill the form (even without setFullScreen()). The other issue I have noticed is that if I click the back button and play another video, I get the new video and the old video still playing at the side / corner of the screen. I have tried pause() and then cleanup() but they seem to have no effect. I have tried adding the Media directly to a Container and using MediaPlayer and found the same issues with both.

setNativePlayerMode() does not work either (there may be a separate issue logged for this).

I have also noticed these issues in the Kitchen Sink demo.

**Comment by chen-fishbein** [comment]
fixed the stretching and the video not cleaned properly, the fullscreen is still an issue.
Are you sure the fullscreen ever worked properly?

**Comment by tobymundy** [comment]
Chen,
I have just checked an app that I made and send to the build server 11 months ago. The video is not completely full screen but does covers form title bar leaving only the part with the mobile signal level and battery level etc showing. The apps that I compiled on the build server at the time I reported this issue and now are showing the form title bar.
Toby
On 4 Oct 2016 20:51, Chen Fishbein <notifications@github.com> wrote:fixed the stretching and the video not cleaned properly, the fullscreen is still an issue.
Are you sure the fullscreen ever worked properly?

**Comment by tobymundy** [comment]
I have just sent the apps to the build server and found things have changed. The video no longer stretches but is very small at the top left corner of the screen instead of fitting the screen width. This can be seen in the KitchenSink demo also.

**Comment by kazza186** [comment]
I'm having this exact same problem. @tobymundy Did you manage to get the video back to normal size?

**Comment by tobymundy** [comment]
No @kazza186 it is still not sizing correctly however this issue is still 'open'.

**Comment by chen-fishbein** [comment]
fixed, will be available in the next server update next week
