### ISSUE TITLE
Log.getLogContent() does not seem to work

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1899]
I've tried to use the `getLogContent()`  but it doesn't seem to work correctly. 

I've gone through the source code and although I'm not sure to completely understand how it is supposed to work, it seems that the `getLogContent()` doesn't fetch the content from the same file as `sendLogContent()`.

I've tried reading the documentation to see if I'm missing something, but haven't been able to find anything, so if it's not a bug, it would be great to improve the documentation. 

Here's an example to reproduce the problem: 

    Log.bindCrashProtection(false);
    Log.p("test if getLogContent() works");
    Dialog.show("Log content", Log.getLogContent(), "OK", null); //ERROR - Dialog shows no content
    if (Dialog.show("Send Log", Log.getLogContent(), "OK", null)) {
        Log.sendLog(); //sendLog works (an email with "test if getLogContent() works" is received
    }

Thanks in advance

**Comment by codenameone** [comment]
The solution is to deprecate that method. Logs can get pretty big and the approach of reading them to a string is probably not tenable. We should cull this method

**Comment by ThomasH99** [comment]
I don't agree. On the device, this would leave only the sendLog() which is slow since you have to wait for and open the emailed log. Since CN1 doesn't support debugging on the device (and because successful execution in the simulator far from ensures successful execution on the device) it is quite important to easily visualize the log file. 

To get around the problem of size, I would suggest to add a `maxSize` parameter to only get the last maxSize characters of the log.

**Comment by codenameone** [comment]
As you pointed out the  right thing to do is on-device-debugging. We have plans to launch on-device-debugging by Q2 2017.

**Comment by ThomasH99** [comment]
That sounds absolutely great and the right (if probably not easy) way to go. But a quick small improvement would certainly make the 6-9 months until then feel shorter ;-)
