### ISSUE TITLE
RFE: Simulator should be able to simulate the device buzzer - Display.vibrate()

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1900]
The device buzzer `Display.getInstance().vibrate()` can currently only be tested on the device which is quite cumbersome (and means consuming compile time on your servers for very little good reason). 

I suggest that you add a buzz sound to Simulator that replicates the vibration.

**Comment by codenameone** [comment]
We'll fix this by adding a System.out in such cases. This will let you know that vibrate was invoked.
