### ISSUE TITLE
Location Simulation always opens in Simulator

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1901]
I don't know if this is the intended behavior, but if it is, I find it rather annoying:
With one project that relies heavily on location, I used the Location Simulation tool one time, and ever since then it opens whenever I run the simulator (just for that particular project), on top of the Simulator itself (blocking it on the screen), even though I always close it before I close the simulator.  Shouldn't it have behavior similar to the Network Monitor tool, and not automatically reopen if it was closed when the Simulator last exited?

**Comment by codenameone** [comment]
I agree it's annoying. It was contributed by a user a while back as part of a big pull request and we need a better way to disable it

**Comment by codenameone** [comment]
This was fixed a while back
