### ISSUE TITLE
Display.vibrate on iOS (iPhone 6s) does not vibrate the indicated duration

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1904]
When using Display.vibrate(int duration), my iPhone 6s with iOS 10 seems to vibrate the same time (seems to be somewhere between 0,5 and 1 second), no matter what value I use for duration. This makes it impossible for example to create a specific vibration pattern for my app.

**Comment by codenameone** [comment]
That's problematic on iOS. We map to AudioServicesPlaySystemSound(kSystemSoundID_Vibrate); which doesn't accept a duration value.

There are ways around it http://stackoverflow.com/questions/12966467/are-there-apis-for-custom-vibrations-in-ios but they can get your app rejected...

**Comment by ThomasH99** [comment]
Would be great if you could update the documentation with this limitation. It would have reduced the time I spend on the issue to less than 5 minutes, instead of the 1-2 hours I used to read the doc, google and test, so others may save time as well.

**Comment by codenameone** [comment]
Makes sense. I was not aware of this limitation and it's pretty old code.
