### ISSUE TITLE
RFE: add CN1 support for clearing a text field on iOS and Android

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1906]
Most apps with text entry fields have the little (x) at the right-hand side of the text entry to quickly clear the field. This would be great to have built-in CN1 support for as well.
![image](https://cloud.githubusercontent.com/assets/16265939/19142703/ca60a922-8b9f-11e6-8b17-ce9d495aace2.png)

**Comment by codenameone** [comment]
I looked a bit more on this issue and came to the conclusion that this shouldn't be implemented natively as Android has no native implementation of this. Initially I was under the impression that this required z-ordering but looking at the Safari implementation on iOS it seems the text is cropped before the edge of the X button which means this is something we can just implement by wrapping.
