### ISSUE TITLE
IntelliJ plugin not found

### ISSUE THREAD

**Issue by ahmedengu** [codenameone/CodenameOne#1908]
Greetings,

Latest version of the IntelliJ plugin got removed from dropbox :
https://dl.dropboxusercontent.com/u/57067724/IntelliJCodenameOneSupport.zip
https://plugins.jetbrains.com/plugin/7357?pr=

**Comment by codenameone** [comment]
Ugh. That's my fault.
I was sure Jetbrains was copying the URL content when submitting so I just deleted the file. I don't want to share a dropbox URL so I had to update the version number and place it in the website for the upload to actually take.
