### ISSUE TITLE
hard crash on IOS

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1911]
This test program, when build for IOS, crashes immediately in the function IncrementAllegiance.
There is no error thrown or other possibility to recover, and it works fine on the simulator
and on android.

``` java
package dtest.boardspace;
//
// this version, when built for IOS and the resulting sources are compiled,
// generates a warning that should be heeded for the double[][] = new .. clause
//
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;

import java.util.Random;

enum replayMode
{   /** live indicates the user is manipulating the UI directly, but the robot is using accelerated move specifiers, 
    so normally the usert's moves are not animated, but the robot's move are. */
    Live,
    /** Replay means a high speed replay or a robot move search is in progress, so no animations should be done */
    Replay, 
    /** Single means a single step replay is in progress, so both the user and robot's moves should be animated */
    Single
}

interface EuphoriaConstants
{
enum Allegiance { Euphorian, Subterran, Wastelander, Icarite;
}
static int AllegianceSteps=12;
}
class EuphoriaBoard implements EuphoriaConstants
{
    private int allegiance[] = new int[Allegiance.values().length];
    // return true if actually incremented

    private void awardAllegianceStars(Allegiance faction,replayMode replay)
    {
    }
    public boolean incrementAllegiance(Allegiance faction,replayMode replay)
    {   
        int ord = faction.ordinal();
        if(allegiance[ord] < AllegianceSteps-1) 
            { 
            allegiance[ord]++;
            if(allegiance[ord]==(AllegianceSteps-1)) { awardAllegianceStars(faction,replay); }
            return(true); 
            }
        return(false);
    }
    public boolean doit()
    {
        return incrementAllegiance(Allegiance.Subterran,replayMode.Live);
    }
}
public class Dtest  {

    private Form current;
    @SuppressWarnings("unused")
    private Resources theme;
    EuphoriaBoard b = null;
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
        b = new EuphoriaBoard();
    }

    public void start() {
        Form hi = new Form("Hi >>0 World");
        current = hi;
        current.show();
        hi.setLayout(new BorderLayout());
        b.doit();

        hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {


            @Override
            public void paint(Graphics g) {
                int w = getWidth();
                int h = getHeight();
                g.setColor(0x8f8f9f7f);
                g.fillRect(0,0,w,h);
                g.setColor(0);


                repaint();
            }

        });
        hi.show();

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

static int pass =0;
public void testRandom(Graphics g,int x,int y)
{   pass ++;
    g.drawString("Pass "+pass,x,y);
    y+=20;
    { Random r = new Random(63546);
      for(int i=0;i<3;i++) 
        { String val = ""+r.nextLong();
          g.drawString(val,x,y);
          y+=20;
        }
    }
    y+=20;
    { Random r2 = new Random(63546);
    for(int i=0;i<3;i++) 
    { String val = ""+r2.nextLong();
      g.drawString(val,x,y);
      y+=20;
    }
    }
    }


}
```

I'm certain that at some point in the past, this worked.   I suspect the breakage
occurred when the build servers were changed to the new mode about a month ago.

**Comment by ddyer0** [comment]
changing the test in IncrementAlliance as follows fixes the problem

    	boolean test = allegiance[ord] < AllegianceSteps-1;
    	if(test)

**Comment by ddyer0** [comment]
You need to give this one the red ball treatment.  It looks like there's a simple underpopped
stack, but it can be triggered from any if clause with a nontrivial boolean.  I'm amazed this hasn't
caused screems from many developers.

**Comment by ddyer0** [comment]
also, curiously, this doesn't seem to generate any errors or crashes when the source code is compiled and run under apple's simulator.

**Comment by ddyer0** [comment]
Also, I'm complaining again that this crash, whatever the actual cause, was not caught or reported
in ANY way, so the only way to locate the errant code was to conduct a binary search.  This one took
2 days (with my 45 minute build time) to locate; and I was fortunate that I found a simple way
to induce it.

If there's anything you can do, however limited, to improve on this situation for the future will
be wonderful.

**Comment by shannah** [comment]
Is there something missing from your test case?  When I build this test it just shows me a green screen in form titled "Hi>>0 World".

The testRandom() method is not referenced anywhere.  And importantly, I don't experience any crashes running on iPhone 6S running iOS 10.

**Comment by ddyer0** [comment]
The screen you describe is the expected result, unless there's a crash.
testRandom is just junk left over from re-using the same test files.

I just rebuilt and re-ran the test, and it no longer fails.

The device I used to produce the problem was an ipad 2, but I think I recall testing it on
an iphone 6 too.  Maybe the recent change to the build process is relevant.  

The code being generated that corresponds to the crash is substantially the
same.  Here it is:

> JAVA_BOOLEAN dtest_boardspace_EuphoriaBoard_incrementAllegiance___dtest_boardspace_EuphoriaConstants_Allegiance_dtest_boardspace_replayMode_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT  __cn1ThisObject, JAVA_OBJECT __cn1Arg1, JAVA_OBJECT __cn1Arg2) {
    JAVA_INT ilocals_3_; /* v3 */
    DEFINE_INSTANCE_METHOD_STACK(4, 4, 0, 6185, 6187);
    locals[0].data.o = __cn1ThisObject; locals[0].type = CN1_TYPE_OBJECT;     locals[1].data.o = __cn1Arg1;
    locals[1].type = CN1_TYPE_OBJECT;
    locals[2].data.o = __cn1Arg2;
    locals[2].type = CN1_TYPE_OBJECT;
    BC_ALOAD(1);
    { JAVA_INT tmpResult = virtual_dtest_boardspace_EuphoriaConstants_Allegiance_ordinal___R_int(threadStateData, SP[-1].data.o);
    SP[-1].data.i = tmpResult; SP[-1].type = CN1_TYPE_INT; }
    BC_ISTORE(3);
    PUSH_POINTER(get_field_dtest_boardspace_EuphoriaBoard_allegiance(__cn1ThisObject));
    (*SP).type = CN1_TYPE_INT; /* ILOAD */ 
    (*SP).data.i = ilocals_3_; 
    SP++;
    CHECK_ARRAY_ACCESS(2, SP[-1].data.i); /* IALOAD */
    SP--; SP[-1].type = CN1_TYPE_INT; 
    SP[-1].data.i = ((JAVA_ARRAY_INT*) (*(JAVA_ARRAY)SP[-1].data.o).data)[(*SP).data.i];
    PUSH_INT(11);
    SP-=2; if((*SP).data.i >= SP[1].data.i) /* IF_ICMPGE */ goto label_L120064195;
    PUSH_POINTER(get_field_dtest_boardspace_EuphoriaBoard_allegiance(__cn1ThisObject));
    (*SP).type = CN1_TYPE_INT; /* ILOAD */ 
    (*SP).data.i = ilocals_3_; 
    SP++;
    BC_DUP2(); /* DUP2 */
    CHECK_ARRAY_ACCESS(2, SP[-1].data.i); /* IALOAD */
    SP--; SP[-1].type = CN1_TYPE_INT; 
    SP[-1].data.i = ((JAVA_ARRAY_INT*) (*(JAVA_ARRAY)SP[-1].data.o).data)[(*SP).data.i];
    PUSH_INT(1); /* ICONST_1 */
    SP--; SP[-1].data.i = SP[-1].data.i + (*SP).data.i; /* IADD */
    CHECK_ARRAY_ACCESS(3, SP[-2].data.i); /* IASTORE */
    ((JAVA_ARRAY_INT*) (*(JAVA_ARRAY)SP[-3].data.o).data)[SP[-2].data.i] = SP[-1].data.i; SP -= 3;
    PUSH_POINTER(get_field_dtest_boardspace_EuphoriaBoard_allegiance(__cn1ThisObject));
    (*SP).type = CN1_TYPE_INT; /* ILOAD */ 
    (*SP).data.i = ilocals_3_; 
    SP++;
    CHECK_ARRAY_ACCESS(2, SP[-1].data.i); /* IALOAD */
    SP--; SP[-1].type = CN1_TYPE_INT; 
    SP[-1].data.i = ((JAVA_ARRAY_INT*) (*(JAVA_ARRAY)SP[-1].data.o).data)[(*SP).data.i];
    PUSH_INT(11);
    SP-=2; if((*SP).data.i != SP[1].data.i) /* IF_ICMPNE */ goto label_L1431780832;
    BC_ALOAD(0);
    /* CustomInvoke */dtest_boardspace_EuphoriaBoard_awardAllegianceStars___dtest_boardspace_EuphoriaConstants_Allegiance_dtest_boardspace_replayMode(threadStateData, SP[-1].data.o, locals[1].data.o, locals[2].data.o);     SP -= 1;

label_L1431780832:
    RETURN_AND_RELEASE_FROM_METHOD(1, 4);

label_L120064195:
    RETURN_AND_RELEASE_FROM_METHOD(0, 4);
}

> 

The line I had flagged as the probable error is the "push_int(11)" which loads
something onto the stack, and if the branch immediately following branches, 
the exit takes no notice of the extra item on the stack.

**Comment by shannah** [comment]
OK.  I'll close this then.  Please reopen if you find a way to reproduce it.

**Comment by ddyer0** [comment]
I don't think its appropriate to close this unless you understand why it no longer fails.
Otherwise something is still lurking out there.   To begin, what do you have to say about
the "push_int(11)".  Is that code kosher?

**Comment by shannah** [comment]
If the issue can't be reproduced, then I don't want it taking up mindspace in my queue.  If you can reproduce it, or it happens again, then reopen it.
