### ISSUE TITLE
getDatabasePath isn't implemented in the JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1915]

**Comment by shannah** [comment]
I can't think of a reasonable way to do this.   

http://stackoverflow.com/questions/7183049/how-to-delete-a-database-in-websql-programmatically

It is best just not to rely on this functionality

**Comment by codenameone** [comment]
Interesting. This needs to be documented both in the method signature and the developer guide section mentioning this.

**Comment by shannah** [comment]
Added notes in javadocs for Database.

https://github.com/codenameone/CodenameOne/commit/219cd287e77f8b6cfd3b9bdee729475f5267e3eb

**Comment by shannah** [comment]
Added a warning to the storage section of the developer guide also.

https://github.com/codenameone/CodenameOne/wiki/File-System,-Storage,-Network-&-Parsing/_compare/7a9d62ff9e8b13951c871c73766794db663facd7...31f22a4734e3ade4699f8db7c333f9ce599a1a74

**Comment by shannah** [comment]
Additionally, added warnings in the simulator console output if these methods are executed.
https://github.com/codenameone/CodenameOne/commit/9e2fff16ac07f09c9aad39bbe766adfd89239839
