### ISSUE TITLE
iOS Build process includes 64 bit support even for debug builds

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1928]
Historically we built only 32bit arch by default when building debug versions to speed up compilation time. It seems that the newer xcode build process doesn't include that ability and always builds 64+32 bit.

**Comment by shannah** [comment]
Thanks for finding this.  I was frustrated that it seemed to be compiling everything twice, which was taking a long time, but I thought this was just necessary.

I am testing out building for ARCHS=armv7 for debug builds  right now.  So far so good.

**Comment by shannah** [comment]
Changed it in SVN.  Tested it out on one of my apps and verified that result installed fine on iPhone 6S.
