### ISSUE TITLE
GUIBuilder: Opening a second instance of the GUI builder on a different file causes data loss!

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1930]
This is pretty serious...

Open one file in GUI builder and change stuff open another one without closing the first.

Go back to the first, save and close. It will write on top of the new file instead of the old file losing your XML in the process...

**Comment by codenameone** [comment]
Just lost a lot of work on this...

**Comment by chen-fishbein** [comment]
any idea how to do this? I am trying to avoid a guibuilder.lock file that might cause other problems if the gui builder has crashed

**Comment by codenameone** [comment]
It should already be solved... The connector class should use the connector instance with which the GUI builder was launched and not the one that is currently on disk. So when writing the GUI xml file we should always write to the original location. I don't see a need for a lock file, we should be able to edit two GUI files at once. That's why when the GUI builder sends data back to the IDE it uses a unique file name.

**Comment by chen-fishbein** [comment]
not sure I follow you, can I close this?

**Comment by codenameone** [comment]
No, I'll take it.

**Comment by codenameone** [comment]
Fixed in SVN
