### ISSUE TITLE
GUIBuilder: Lead component doesn't work and MultiButton is broken

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1937]
Adding a mutli button results in the following XML generated:

````xml
    <component type="MultiButton" leadComponent="Button[x=0 y=0 width=0 height=0, text = , gap = 2]" uiid="Label" icon="resFile:contact-c.png" name="Multi_Button_1">
````

Notice that the lead component of the multi button should not be written as this is a builtin component. Also notice that the property is generated incorrectly with the `toString()` value instead of the `getName()` value.

**Comment by chen-fishbein** [comment]
fixed
