### ISSUE TITLE
GUIBuilder: We need an ability to instanciate a custom component

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1940]
We need the ability to have custom creation code in the XML format/GUI builder so we can create component subclasses. This is essential for some features. 

One approach I think makes sense is to have a "Custom Creation Code" option that will be in the "Events" section. It will call a factory method in the class that will default to create the new instance but the code will be outside of the generated block so it could be customized to anything.

**Comment by chen-fishbein** [comment]
added
