### ISSUE TITLE
Javascript port Calendar date calculation value overflow 

### ISSUE THREAD

**Issue by mickeyng** [codenameone/CodenameOne#1941]
In the Javascript port, the Calendar class overflows when using dates at the year value 1969.
See code snippet below

```
form.add("how old am I if born on 1970-01-01? ").add("ans: " + getAge("19700101"));
form.add("how old am I if born on 1969-01-01? ").add("ans: " + getAge("19690101"));
form.add("how old am I if born on 1968-01-01? ").add("ans: " + getAge("19680101"));
...

public static int getAge(String dob) {
        SimpleDateFormat df = new SimpleDateFormat("yyyyMMdd");
        Calendar birthDate = Calendar.getInstance();
        try {
            birthDate.setTime(df.parse(dob));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        Calendar today = Calendar.getInstance();
        int age = today.get(Calendar.YEAR) - birthDate.get(Calendar.YEAR);
        if (today.get(Calendar.MONTH) < birthDate.get(Calendar.MONTH)) {
            age--;
        } else if (today.get(Calendar.MONTH) == birthDate.get(Calendar.MONTH)
                && today.get(Calendar.DAY_OF_MONTH) < birthDate.get(Calendar.DAY_OF_MONTH)) {
            age--;
        }
        return age;
    }
```

Result:
how old am I if born on 1970-01-01?
ans: 46
how old am I if born on 1969-01-01?
ans: -11754996
how old am I if born on 1968-01-01?
ans: 48

**Comment by shannah** [comment]
I have reproduced this issue.  Just trying to track it down.
Can you confirm that you are using `SimpleDateFormat` from the `com.codename1.l10n` package and not `java.text`?

**Comment by mickeyng** [comment]
Yes, SimpleDateForm is from the com.codename1.l10n package

**Comment by shannah** [comment]
This fix requires a change inside TeaVM itself.  I have a few changes there that will be ready to push out next week.  ETA:  It will be included with next week's server update.

**Comment by shannah** [comment]
Just tracked it down.  Turned out to be a problem with "long" division.

https://github.com/konsoletyper/teavm/issues/228

Will be part of the server update next week.
