### ISSUE TITLE
iOS - ZooZSDK 64 bit support issue

### ISSUE THREAD

**Issue by Bhavesh-Limbachiya** [codenameone/CodenameOne#1946]
Compiling with arm64, error generated

"OBJC_CLASS$_ZooZInvoiceItem", referenced from:

**Comment by codenameone** [comment]
We now support braintree: https://www.codenameone.com/blog/braintree-paypal-cn1lib.html

It's probably better as the integration is a cn1lib you can customize. So we will discontinue the Zooz support.
