### ISSUE TITLE
OnOffSwitch in Wrong Package using (New) GUIBuilder

### ISSUE THREAD

**Issue by tobymundy** [codenameone/CodenameOne#1951]
The nnew GUIBuilder is putting the OnOffSwitch in the wrong package.
I used the new GUIBuilder to add an OnOffSwitch to a container. When I run the App in Netbeans it declares the component as follows:
`private com.codename1.ui.OnOffSwitch gui_On_Off_Switch_1_1 = new com.codename1.ui.OnOffSwitch();`
Netbeans gives error: cannot find symbol
The OnOffSwitch is in com.codename1.components.OnOffSwitch

**Comment by codenameone** [comment]
Thanks, last minute fix hopefully will release this today
