### ISSUE TITLE
GUIBuilder Generated MultiButtons Not Working 

### ISSUE THREAD

**Issue by tobymundy** [codenameone/CodenameOne#1954]
Have just updated the Codename One plugin on Netbeans from 3.5.6 to 3.5.7. The MultiButtons added with the GUIBuilder are no longer working.

old version 3.5.6 (OK): Generated code - class EventCallbackClass - actionPerformed started with:
`

        public void actionPerformed(com.codename1.ui.events.ActionEvent ev) {
            com.codename1.ui.Component sourceComponent = ev.getComponent();
            if(sourceComponent.getParent().getLeadParent() != null) {
                sourceComponent = sourceComponent.getParent().getLeadParent();
            }

            if(sourceComponent == gui_Diagnose_Multi_Button_1) {
                onDiagnose_Multi_Button_1ActionEvent(ev);
            }`

newversion 3.5.7 (not working): Generated code - class EventCallbackClass - actionPerformed starts with:
`

        public void actionPerformed(com.codename1.ui.events.ActionEvent ev) {
            com.codename1.ui.Component sourceComponent = ev.getComponent();

            if(sourceComponent == gui_Diagnose_Multi_Button_1) {
                onDiagnose_Multi_Button_1ActionEvent(ev);
            }`

**Comment by chen-fishbein** [comment]
fixed for next plugin update
