### ISSUE TITLE
Buttons Placed on Dialog Get Squashed by TextField Above on Some Android Devices

### ISSUE THREAD

**Issue by tobymundy** [codenameone/CodenameOne#1956]
I use GUIBuilder to make a Dialog, set to BoxLayout Y and add a TextField then two Buttons.
When I display the dialog using myDialog.show(); the bottom button gets squashed. I have tried revalidate(); but this does not work. Rotating the phone causes it to show correctly. This happens on approximately 50% of Android devices tested. It is also an issue on non GUIBuilder created dialogs.
See screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/22393507/20032552/2a34a8ac-a384-11e6-927e-3583bc114c16.png)

**Comment by codenameone** [comment]
````java
        Form hi = new Form("Dialog");
        
        Button b = new Button("Dialog");
        b.addActionListener(e -> {
            Dialog d = new Dialog("Dialog");
            d.setLayout(BoxLayout.y());
            d.add(new TextField("Text Field"));
            d.add(new Button(new Command("Button 1")));
            d.add(new Button(new Command("Button 2")));
            d.show();
        });
        hi.add(b);
        
        hi.show();
````

![codenameone screenshot 92](https://cloud.githubusercontent.com/assets/2353641/20046339/2870862a-a4b1-11e6-8495-c00bf81b3655.png)

**Comment by tobymundy** [comment]
It only seems to happen on some Android devices.

**Comment by tobymundy** [comment]
The above code works OK.
The code generated by the GUI builder that causes the issue is shown below:
Form code
`

    protected void onShowCompleted(){
        Dialog mD = new MyDialog();
        mD.show();
}`

Dialog code (generated)
`

    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
        setTitle("MyDialog");
        setName("MyDialog");
        addComponent(gui_Text_Field_1);
        addComponent(gui_Button_2);
        addComponent(gui_Button_1);
        gui_Text_Field_1.setText("TextField");
        gui_Text_Field_1.setName("Text_Field_1");
        gui_Button_2.setText("Button");
        gui_Button_2.setName("Button_2");
        gui_Button_1.setText("Button");
        gui_Button_1.setName("Button_1");
    }`

**Comment by shannah** [comment]
I have reproduced this issue with your test code.  The problem only occurs when run insie onShowCompleted().  A workaround to fix this issue is to wrap your Dialog calls inside call Serially so that it is deferred to the next tick. E.g.

Change

~~~
protected void onShowCompleted(){
    Dialog mD = new MyDialog();
    mD.show();
}
~~~

to

~~~
protected void onShowCompleted(){
    Display.getInstance().callSerially(()->{
        Dialog mD = new MyDialog();
        mD.show();
    });
}
~~~

Still looking into the exact cause to see if I can find a fix that doesn't require the workaround (besides the obvious fix of just wrapping the call to onShowCompleted() in a callSerially)

**Comment by codenameone** [comment]
I've pushed this to 3.8 as it has a workaround.

**Comment by shannah** [comment]
I'm no longer able to reproduce this issue.   I'm using the same test app that I used before to reproduce it, and I'm not using the workaround I described.

Perhaps another change that has been made in the mean time has fixed this issue.
