### ISSUE TITLE
com.codename1.ui.Graphics.rotate(float, int, int) does not behave scrutable

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#1958]
Graphics.rotate() with a pivot point seems to work capricious.
Using the following demo code - You can see that the tilted X moves whilst the form gets dragged - using the simulator:

	public class FormTiltedX extends Form {
		private class TiltedIconCanvas extends Component {
			protected void paintBackground(Graphics aGraphics) {
				int colorBefore = aGraphics.getColor();
				boolean antiAliasedBefore = aGraphics.isAntiAliased();
				aGraphics.setColor(0xffffff);
				aGraphics.fillRect(0, 0, getWidth(), getHeight());
				aGraphics.setColor(0x505050);
				aGraphics.setAntiAliased(true);
				aGraphics.drawChar('X', 10, 10);
				aGraphics.rotate(0.4f, 100, 10);
				aGraphics.drawChar('X', 100, 10);
				aGraphics.setColor(colorBefore);
				aGraphics.setAntiAliased(antiAliasedBefore);
				aGraphics.resetAffine();
			}
			
			@Override
			protected Dimension calcPreferredSize() {
				return new Dimension(50, 50);
			}
		}
		
		public FormTiltedX() {
			setTitle("FormTiltedX");
			setScrollable(false);
			setScrollableY(true);
			setLayout(new BoxLayout(BoxLayout.Y_AXIS));
			add(new TiltedIconCanvas());
		}
	}

**Comment by shannah** [comment]
I have updated the javadocs on rotate() to clarify that the pivot is in absolute coordinates.  

Change it to:

~~~~
aGraphics.rotate(0.4f, 100 + aGraphics.getTranslateX(), 10 + aGraphics.getTranslateY());
~~~~

And it will work correctly.
