### ISSUE TITLE
Windows UWP icons need work

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1968]
The icons included in Windows UWP builds are different from standard icons.

Looking at the app list The CodenameOne icon has rounded corners, the standard icons are square. See entry under XXX.

![applist](https://cloud.githubusercontent.com/assets/14006739/20544724/3e1358b6-b0c0-11e6-8020-87ec5d03b24b.png)

A larger icon shows when the app starts but it is truncated.

![appicon](https://cloud.githubusercontent.com/assets/14006739/20544830/beeee3a6-b0c0-11e6-9f76-a4b3054b0e44.png)

**Comment by codenameone** [comment]
https://www.codenameone.com/blog/tip-create-square-icons.html
