### ISSUE TITLE
Simulator doesn't respect FontImage rotate when in scaled mode

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1971]
This is described here: http://stackoverflow.com/questions/40702890/rotate-a-fontimage-in-codenameone/40712831

This test case works as expected in the 3gs simulator:

````java
Image shareIcon = FontImage.createMaterial(FontImage.MATERIAL_REPLY, new Button("").getUnselectedStyle(), 5);
for(int i = 0 ; i < 360 ; i += 45) {
    ShareButton s = new ShareButton();
    s.setIcon(shareIcon.rotate(i));
    hi.add(s);
}
````

But it fails when we pick a higher resolution simulator and leave the scrollable unchecked. Checking the scrollable option works around it.

**Comment by shannah** [comment]
@codenameone Do you know why this block of code was necessary?

~~~~
public void drawString(Object graphics, String str, int x, int y) {
       ...
        // the latter indicates mutable image graphics
        if (zoomLevel != 1 && nativeGraphics  != graphics) {
            nativeGraphics = (Graphics2D) nativeGraphics.create();
            nativeGraphics.setTransform(AffineTransform.getTranslateInstance(0, 0));
            java.awt.Font currentFont = nativeGraphics.getFont();
            float fontSize = currentFont.getSize2D();
            fontSize *= zoomLevel;
            int ascent = nativeGraphics.getFontMetrics().getAscent();
            nativeGraphics.setFont(currentFont.deriveFont(fontSize));
            nativeGraphics.drawString(str, x * zoomLevel, (y + ascent) * zoomLevel);
        } else {
           ...
        }
       ...
    }

~~~~

https://github.com/codenameone/CodenameOne/blob/master/Ports/JavaSE/src/com/codename1/impl/javase/JavaSEPort.java#L4477-L4486

If I prevent that case from happening, it fixes the issue for this test case.  I'm not sure what else this might break though.

**Comment by codenameone** [comment]
My comment for those lines:
65ad28c - Shai Almog <shai@codenameone.com> Jun 24, 2016
Fixed this really annoying bug: http://stackoverflow.com/questions/37986722/why-do-i-get-a-different-behviour-in-codename-one-simulator-than-on-a-real-andro

The graphics was scaled for the mutable image too when the simulator was in scale mode

Commit: 65ad28c from January 24th
