### ISSUE TITLE
Android App crashes if Dialog.show() is called while web browser is shown

### ISSUE THREAD

**Issue by Firethunder** [codenameone/CodenameOne#1973]
Hi,
my app crashes when I try to open a dialog while the web browser is displayed .
The crash is only occurring on devices with Android 5.0.x

tested with Samsung Galaxy S4(5.0.1), Samsung Galaxy Tab A(5.0.2)

Attached is a simple test case and the produced microdump

package com.example;

import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Button;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose of building native
 * mobile applications using Java.
 */
public class App {

	private Form current;
	private Resources theme;

	public void init(Object context) {
		theme = UIManager.initFirstTheme("/theme");

		// Enable Toolbar on all Forms by default
		Toolbar.setGlobalToolbar(true);

		// Pro only feature, uncomment if you have a pro subscription
		// Log.bindCrashProtection(true);
	}

	public void start() {
		if (current != null) {
			current.show();
			return;
		}

		Form scr = new Screen();
		scr.show();

	}

	public void stop() {
		current = Display.getInstance().getCurrent();
		if (current instanceof Dialog) {
			((Dialog) current).dispose();
			current = Display.getInstance().getCurrent();
		}
	}

	public void destroy() {
	}

	private class Screen extends Form {

		public Screen() {
			setProperties();
			initBrowserComponentDemo();
			createReloadButton();
			createDialogButton();

		}

		private void setProperties() {
			setLayout(new BorderLayout());
		}

		private void initBrowserComponentDemo() {
			add(BorderLayout.CENTER, new BrowserComponentDemo());
		}

		private void createReloadButton() {
			Button reload = new Button("Reload");
			add(BorderLayout.SOUTH, reload);
			reload.addActionListener(new ActionListener<ActionEvent>() {

				@Override
				public void actionPerformed(ActionEvent evt) {
					removeAll();
					initBrowserComponentDemo();
					createReloadButton();
					createDialogButton();
					revalidate();
				}
			});
		}

		private void createDialogButton() {
			Button dialog = new Button("Open Dialog");
			add(BorderLayout.NORTH, dialog);
			dialog.addActionListener(new ActionListener<ActionEvent>() {

				@Override
				public void actionPerformed(ActionEvent evt) {
					Dialog.show("Title", "Test", "Ok", "Close");
				}
			});
		}
	}

	public class BrowserComponentDemo extends BrowserComponent {
		public BrowserComponentDemo() {
			setURL("https://www.codenameone.com/");
		}
	}
}

[Microdump.txt](https://github.com/codenameone/CodenameOne/files/618573/Microdump.txt)

**Comment by codenameone** [comment]
This was an Android webview bug that was fixed in newer OS updates. I'm not aware of a workaround for this bug but if there is we'd be happy to incorporate it.

**Comment by hrugani** [comment]
We are facing same problem.
Using JavaScript Bridge, I call new Form.
When  back-command of this form  is executed my app stops.
It is aborted.

**Comment by codenameone** [comment]
This issue was fixed by a commit from @Firethunder although it's not on the build servers yet. Unless you use webview this isn't related to your issue
