### ISSUE TITLE
ToastBar message it doesn't show it content in transition between the forms in real devices and simulator

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#1974]
Problem:

 The problem it occur when the toast message is showing And when this message is going to invisible (at this moment when the label is cleared), you must it return immediately to another form. the message is delete a never is showed again until I killed my app an restart again.

Single code
`

                    String msg0 = UIManager.getInstance().localize(KeyLang.ups_editModeDisable, "Editing mode disable...");
                    Log.i(TAG, methodName + "()->ups_editModeDisable:" + msg0);
                    ToastBar tb = ToastBar.getInstance();
                    tb.setPosition(Component.TOP);
                    tb.showMessage(msg0, FontImage.MATERIAL_MODE_EDIT, 2000);`

**Comment by DurankGts** [comment]
this link it show how to reproduce the issue:

https://drive.google.com/open?id=0BxIcjF4P4hU8dnhmUnNucWstdGs

**Comment by DurankGts** [comment]
I am wating this issue yet, this problem is persistent.

**Comment by codenameone** [comment]
It's assigned for the 3.7 milestone

**Comment by DurankGts** [comment]
but you just have released the 3.5.8 now , and I will wait when you launched the 3.7. It important to me to solve this issue, because this error are persistent in my release app.

**Comment by codenameone** [comment]
No we released 3.6 last week: https://www.codenameone.com/blog/codename-one-3-6-now-live-special-sale.html
3.7 is slated for May so unless this gets bumped it should be addressed before May.

Issues get priority as such:

- Crucial - major failure or problem that impacts a huge percentage of the users
- Enterprise account issues
- Pro account issues reported by multiple accounts or users
- Pro account individual issues
- Everything else

Notice that this issue got a relative high priority as all issues area already slated to 3.8 which will be close to the end of the year!

**Comment by DurankGts** [comment]
I can´t understand this issue it will solve to the end of the year¿

**Comment by codenameone** [comment]
**3.7 is slated for May so unless this gets bumped it should be addressed before May.**
