### ISSUE TITLE
Toolbar side menu doesn't show dynamically added commands on swipe open

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1975]
I have only seen this issue with an old GUI builder project.  It manifests both in the simulator and on an Android device, I haven't yet checked other builds, nor have I checked on more recent projects.  

Steps to reproduce:
1. Create a new project with the old GUI builder with a theme that has a side menu (I used the blue flat theme)
2. in the GUI builder, add a couple of commands to the side menu
3. In the code (in the BeforeMainForm method) add some more commands to the side menu
4. Open the app, press the hamburger menu button. You should see all the menu items
5. Swipe the side menu open, you will only see the menu items added in the GUI builder

For my own purposes, I would be satisfied just being able to prevent users from swiping open the menu, and restricting them to using the hamburger button, but this seems to be a bug in any case.

**Comment by codenameone** [comment]
The old GUI builder calls the generic add command and doesn't have any explicit support for the side menu. This isn't something we will change as we are moving towards the new GUI builder.

**Comment by jegesh** [comment]
For future reference, I seem to have circumvented the problem by setting theme constant `commandBehavior` to native.
