### ISSUE TITLE
Screen flashes black when InfiniteScrollingContainer loads more items

### ISSUE THREAD

**Issue by jegesh** [codenameone/CodenameOne#1976]
On more than one Android device, in more than one `Form`, I have seen the screen flash completely black for about 300-500 ms when the app loads an additional set of items into the `InfiniteContainer`.  I presume this is not the intended behavior.  The same app doesn't flash in the simulator.  I will try to check it on an iPhone soon.

**Comment by codenameone** [comment]
I've seen this in the kitchen sink in the dogs demo, this happens but is very subtle on newer devices you have to really look hard.

**Comment by jegesh** [comment]
It's very noticeable on my Nexus 5, which is not by any means new, by not exactly outdated either.  I'm glad to see it has been targeted for the next versioned release!
