### ISSUE TITLE
Opening a link on Android (23) causes permission request to access "photos, media and files"

### ISSUE THREAD

**Issue by amiga** [codenameone/CodenameOne#1982]
Simply call this Display.getInstance().execute("http://www.google.com");

**Comment by codenameone** [comment]
````java
        Form hi = new Form("Issue 1982");
        Button b = new Button("Open Google");
        hi.add(b);
        b.addActionListener(e -> Display.getInstance().execute("http://www.google.com"));
        hi.show();
````
![2016-12-09 08 50 47](https://cloud.githubusercontent.com/assets/2353641/21043014/888243ae-bdfd-11e6-8cb8-152b5c4e9e37.png)
![2016-12-09 08 50 54](https://cloud.githubusercontent.com/assets/2353641/21043013/8880bf70-bdfd-11e6-8d66-8620c1c35153.png)

No permission prompts
