### ISSUE TITLE
Arbitrary height with FlowLayout wrapped components

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#1986]
A container with FlowLayout contained in containers often gets wrong height.

I created a sample program where ...

1. both containers initially are too short and 
2. when scrolling the second container resizes correctly and
3. when contentPane.revalidate is called (right toolbar button) the first container ist sized correctly and the second container becomes to big.

Here the code:

	public class FormFlowLayoutHeight extends Form {
		private int defaultFontSize = new Label("X").getStyle().getFont().getHeight();
		
		public FormFlowLayoutHeight() {
			setTitle("FormFlowLayoutHeight");
			setScrollable(false);
			Container contentPane = getContentPane();
			contentPane.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
			contentPane.setScrollableY(true);
			contentPane.add("height corrects on revalidate()");
			contentPane.add(decorate(addComponentsToWrap(createOrdinaryFlowLayoutContainer())));
			contentPane.add("height initially wrong, too");
			contentPane.add(decorate(BorderLayout.centerEastWest(addComponentsToWrap(createOrdinaryFlowLayoutContainer()), new Label("east"), new Label("west"))));
			getToolbar().addCommandToRightBar(new Command("revalidate()") {
				@Override
				public void actionPerformed(ActionEvent evt) {
					contentPane.revalidate();
				}
			});
		}
	
		private Container addComponentsToWrap(Container aContainer) {
			String[] labels = {"The","quick","brown","fox","jumps","over","the","lazy","dog", "."};
			for (int loop = 0; loop < 3; loop++) {
				aContainer.add((loop + 1) + ":");
				for (String label: labels) {
					aContainer.add(new Label(label));
				}
				aContainer.add(new SpanLabel("The quick brown fox jumps over the lazy dog"));
			}
			return aContainer;
		}
	
		private Container createOrdinaryFlowLayoutContainer() {
			return new Container(new FlowLayout());
		}
	
		@SuppressWarnings("deprecation")
		private Container decorate(Container aContainer) {
			Style style = aContainer.getAllStyles();
			style.setBorder(Border.createRoundBorder(defaultFontSize, defaultFontSize));
			return aContainer;
		}
	}

**Comment by saeder** [comment]
Perhaps FlowLayout requires a second Layout run. The first to calculate the widths and the second to calculate the heights

**Comment by codenameone** [comment]
There is no such a thing as a "second run" because this will resize the elements and effectively require a 3rd run which might again resize the elements... Infinite loops become an issue.
Reflow shifts determinism to a different location it doesn't solve it, it's a huge performance hurdle you will pay for later on. I suggest re-evaluating the type of layout you are trying to achieve and implementing it in a way that is deterministic.
