### ISSUE TITLE
Keyboard of AutoCompleteTextField keeps switching back to non-numbers in iOS

### ISSUE THREAD

**Issue by gerbenk** [codenameone/CodenameOne#1987]
For a while we had some weird behaviour in the AutoCompleteTextField on iOS. Today, I narrowed it down to a simple program. If you input a number in the TextField, the keyboard switches back to non-numbers. You also see two cursors. And when you scroll the suggestion popup gets detached.

A small sample
```java
Form f = new Form(new BorderLayout());
        
Container c = new Container(new BoxLayout(BoxLayout.Y_AXIS));
c.addComponent(new AutoCompleteTextField(new String[] {"Gerben", "Steve", "Shai"}));
c.setScrollableY(true);
        
f.addComponent(BorderLayout.CENTER, c);
        
f.show();
```

**Comment by shannah** [comment]
Fixed here https://github.com/codenameone/CodenameOne/commit/013067dfe8106b9e12852d41ed6465b9ed786cf2
