### ISSUE TITLE
Two factor authentication causes issues with certificate wizard

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1995]
We need to detect that situation and either present the challenge number to the user or alternatively provide the user with instructions to disable two-factor authentication

**Comment by shannah** [comment]
This is done, pending some server updates to support the latest fastlane.

**Comment by shannah** [comment]
There was a problem with our environment (or with jRuby) that had to be fixed for fastlane to work. For future reference, the issue and its workaround is described here:

https://github.com/jruby/jruby/issues/4672

**Comment by shannah** [comment]
This is now deployed to the server.   2-factor auth requires the latest changes to CodenameOneSettings in SVN - which will be included with the next plugin update.
