### ISSUE TITLE
XYSeries broken, miscalculates max X and max Y values

### ISSUE THREAD

**Issue by Wookie1** [codenameone/CodenameOne#1997]
This was working previously, and works on my Eclipse IDE now until I update the libs. After updating, the min and max are the positive and negative MathHelper.null values. Using series.getX and .getY to verify what numbers are contained, I get the correct values that were added. It seems the getMaxX and getMaxY calculation has an issue, which causes the chart scale to be not unusable.

...
XYSeries series = new XYSeries("Data");
...
series.clear(); //Just to make sure there aren't lingering values
series.add(1.0, 100.0);
System.out.println("Initial series max: " + series.getMaxX() + ", " + series.getMaxY());
}

results in the following on the console:
Initial series max: 1.7976931348623157E308, 1.7976931348623157E308

**Comment by codenameone** [comment]
Since this seems like a recent regression I added it to the 3.6 milestone. Hopefully it will make it, if not it might be valid to fix it during codefreeze.
