### ISSUE TITLE
[iOS] Add keys for compilation with xcode 8

### ISSUE THREAD

**Issue by JrmyDev** [codenameone/CodenameOne#1999]
It might be great to add by default in Info.plist file this keys : 
-NSCameraUsageDescription 
-NSPhotoLibraryUsageDescription
-NSMicrophoneUsageDescription
-NSCalendarsUsageDescription
-NSBluetoothPeripheralUsageDescription

My archive was refused during submission to itunesconnect because it was missing "NSPhotoLibraryUsageDescription" & "NSMicrophoneUsageDescription" with xcode 8. 

More details can be found here : https://medium.com/@zonble/upgrade-to-xcode-8-716cde2bb19d#.u16yu67dg

**Comment by codenameone** [comment]
Our servers currently build with xcode 7.x so I assume you downloaded the source and built with xcode 8.x. I suggest you stick to xcode 7.x as that is what we are testing against. There are other changes in 8.x that might impact push notification and other API's so building using 8.x isn't recommended.

**Comment by JrmyDev** [comment]
OK. But since all my users are using ios 10.x, I have used xcode 8 to test and archive my version.
Which are API's impacted by xcode 8 ??

**Comment by codenameone** [comment]
iOS 10 works fine with xcode 7.x builds. In those cases it just ignores that. You need 8.x to debug on the physical device but for store upload you can use 7.x (or our build servers and Application Loader) and the resulting app will work fine on iOS 10 devices.

**Comment by codenameone** [comment]
Moved to 3.8 due to impending code freeze
