### ISSUE TITLE
Component not painted in its entirety

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2005]
I made a simple descendant of `Component` which paints a rectangle of its size. It is not entirely painted, which seems to be a **serious** bug to me.

This code can be used to demonstrate this - in the simulator and on my iPhone 5S:

	public class FormRectangleComponent extends Form {
		private class RectangleComponent extends Component {
			@Override
			public void paint(Graphics aGraphics) {
				aGraphics.setColor(0xffffff);
				aGraphics.drawRect(getX(), getY(), getWidth(), getHeight());
			}
			
			@Override
			protected Dimension calcPreferredSize() {
				int side = Display.getInstance().getDisplayHeight() / 10;
				return new Dimension(side, side);
			}
		}
		
		public FormRectangleComponent() {
			Display.getInstance().areMutableImagesFast();
			setTitle("FormRectangleComponent");
			setScrollable(false);
			Container contentPane = getContentPane();
			contentPane.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
			contentPane.setScrollableY(true);
			contentPane.getAllStyles().setBgPainter((Graphics aGraphics, Rectangle aRectangle) -> {
				aGraphics.setColor(0x00c0c0);
				aGraphics.fillRect(aRectangle.getX(), aRectangle.getY(), aRectangle.getWidth(), aRectangle.getHeight());
			});
			contentPane.add(new SpanLabel(
					"Below should be a white frame showing all sides."));
			contentPane.add(new RectangleComponent());
		}
	}

**Comment by codenameone** [comment]
Can you add a screenshot?

**Comment by saeder** [comment]
![img_5541](https://cloud.githubusercontent.com/assets/9945131/22106654/140726da-de4a-11e6-8427-4301621e15e5.PNG)

**Comment by codenameone** [comment]
You need to use -1 pixel.
If you read the JavaDocs and graphics sections the rect drawing etc. logic works similarly to the java awt/Swing convention where the rectangle draws on the invisible line between the pixels hence a -1 is needed otherwise you are drawing outside of the clipping area.

**Comment by saeder** [comment]
May be - but with `aGraphics.drawRect(getX() - 1, getY() - 1, getWidth(), getHeight())` it is all the same - **Component not painted in its entirety**.

**Comment by saeder** [comment]
I checked the width and height of `com.codename1.ui.Graphics.drawRect(int, int, int, int)` - apparently this draws one pixel more in width and height. I wonder why that is.

**Comment by codenameone** [comment]
As I said you need -1 on the width/height to match the behavior of JavaSE

**Comment by saeder** [comment]
Where is that documented?
