### ISSUE TITLE
Text field is hidding in android in a Form

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2006]
Hello, When I start to edit my text field, the keyboard it hide my
textField component. Please check if you do some changes in the
TextField component or in a Form. This method is not working now
form.setFormBottomPaddingEditingMode(true);

check this link to see the issue

https://drive.google.com/open?id=0BzHQCAJD0aL_aUJ5RDdONlBkN1k

**Comment by codenameone** [comment]
This was already fixed in GIT and will be in the update next week

**Comment by DurankGts** [comment]
could you send me the url of this fixed commit? it ´s urgent to my this fix
