### ISSUE TITLE
iOS debug build error related to AdmobFullScreen cn1lib

### ISSUE THREAD

**Issue by meseriegh** [codenameone/CodenameOne#2016]
I sent a build for an older unchanged project that uses AdmobFullScreen cn1lib and it failed. The error looks to be because of AdmobFullScreen cn1lib. Here is the the [error log](https://codename-one.appspot.com/getData?m=result&i=6250983098417152&b=bbf469d4-af1e-490a-a5ac-deca8ea06fa4&n=error.txt)

**Comment by shannah** [comment]
Fixed is here: https://github.com/shannah/admobfullscreen-codenameone/commit/e46f44eef84c3417e86039f23ef899b05deade68
