### ISSUE TITLE
Cookies sent with redirect is not registered on iOS

### ISSUE THREAD

**Issue by Munken** [codenameone/CodenameOne#2017]
I'm using a web service that sends cookies (session id etc.) along when it returns a 302. This works fine in the simulator, however on iOS I do _not_ receive these cookies. 

Minimal example:

```java
protected void initVars(Resources res) {
  Cookie.clearCookiesFromStorage();
  ConnectionRequest req = new CookieRequest("https://wayf.wayf.dk");
  NetworkManager.getInstance().addToQueueAndWait(req);
}

class CookieRequest extends ConnectionRequest {

    public CookieRequest(String url) {
        super();
        setUrl(url);
    }

    @Override
    protected void cookieReceived(Cookie c) {
        Log.p("COOKIE REC " + c.getDomain() + " " + c.getName() + " " + c.getValue() + " " + c.getExpires());
        super.cookieReceived(c);
    }

    @Override
    protected void cookieSent(Cookie c) {
        Log.p("COOKIE SENT: " + c);
        super.cookieSent(c);
    }

    @Override
    protected String initCookieHeader(String cookie) {
        Log.p("COOKIE INIT: " + cookie);
        return super.initCookieHeader(cookie);
    }

    @Override
    public boolean onRedirect(String url) {
        Log.p("Redirecting to " + url);
        return super.onRedirect(url);
    }
}
```

Response in the simulator:
```
[Network Thread] 0:0:0,0 - COOKIE INIT: null
Warning: Cookie tried to set to another path
[Network Thread] 0:0:0,350 - COOKIE REC wayf.wayf.dk wayfid wayf-03 0
[Network Thread] 0:0:0,351 - Redirecting to https://wayf.wayf.dk/module.php/core/frontpage_welcome.php
[Network Thread] 0:0:0,352 - COOKIE SENT: name = wayfid value = wayf-03 domain = wayf.wayf.dk
[Network Thread] 0:0:0,352 - COOKIE INIT: wayfid=wayf-03
[Network Thread] 0:0:0,410 - COOKIE REC wayf.wayf.dk PHPSESSID 45e2eb058695a8bef84cee9ad4c9899f 0
[Network Thread] 0:0:0,410 - Redirecting to https://wayf.wayf.dk/module.php/core/loginuserpass.php?AuthState=_3ffed009c8686ef8befe6cbb5595e066e2ce0e8948%3Ahttps%3A%2F%2Fwayf.wayf.dk%2Fmodule.php%2Fcore%2Fas_login.php%3FAuthId%3Dadmin%26ReturnTo%3Dhttps%253A%252F%252Fwayf.wayf.dk%252Fmodule.php%252Fcore%252Ffrontpage_welcome.php
[Network Thread] 0:0:0,411 - COOKIE SENT: name = wayfid value = wayf-03 domain = wayf.wayf.dk
[Network Thread] 0:0:0,411 - COOKIE SENT: name = PHPSESSID value = 45e2eb058695a8bef84cee9ad4c9899f domain = wayf.wayf.dk
[Network Thread] 0:0:0,411 - COOKIE INIT: wayfid=wayf-03;PHPSESSID=45e2eb058695a8bef84cee9ad4c9899f
```

In iOS 
```
[Network Thread] 0:0:0,552 - COOKIE INIT: null
```

This seems to be related to the issue with iOS handling redirects internally. Any way to circumvent this?

**Comment by Munken** [comment]
Additional info. I need the `wayfid` cookie as the web service else reports error 500 and the web service is not under my control. 

I would appreciate it if you could find a solution as this currently has bricked our app.

**Comment by codenameone** [comment]
On iOS redirects happen natively. We don't have as much control over that behavior as we do in other platforms.

**Comment by Munken** [comment]
According to the [documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/RequestChanges.html) for `NSURLSession` it looks like one can attach a delegate to handle the redirect. The most straight forward would be:
 > Reject the redirect and receive any existing data from the connection by returning nil.

Then CN1 code should be entirely in control. 

[Additionally](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/CookiesandCustomProtocols/CookiesandCustomProtocols.html#//apple_ref/doc/uid/10000165i-CH10-SW3) it seems like the iOS layer should be able to collect these cookies and send along with the following request unless:
> The URL loading system automatically sends any stored cookies appropriate for an NSURLRequest object unless the request specifies not to send cookies.

Guess this is so CN1 is entirely in control of the cookies. 


Would the redirect handler be an acceptable fix for this? As a bonus it would mean that [ConnectionRequests.onRedirect](https://www.codenameone.com/javadoc/com/codename1/io/ConnectionRequest.html#onRedirect-java.lang.String-) would be functional on iOS.

**Comment by Munken** [comment]
Using the sources provide by the CN1 build servers I was able to modify `NetworkConnectionImpl.m` and add the following:
```Object-C
- (NSURLRequest *)connection:(NSURLConnection *)connection
             willSendRequest:(NSURLRequest *)_request
            redirectResponse:(NSHTTPURLResponse *)response {
    if (response.statusCode >= 300 && response.statusCode < 400) {
        return nil;
    }
    return _request;
}
```

This effective means that CN1 is in charge of handling redirect logic, and is notified of all cookies.

Could this be added to the master?

**Comment by codenameone** [comment]
I hope this will work across OS versions. Do you want to submit it as a pull request?
https://www.codenameone.com/blog/how-to-use-the-codename-one-sources.html
