### ISSUE TITLE
Table Layout constraints revert to defaults in GUI Builder

### ISSUE THREAD

**Issue by sol72** [codenameone/CodenameOne#2019]
Using the GUI Builder, add a table layout container with any number of components inside it. 

After making changes to the Constraints (Row, Column, Width%, Height%, etc.) on a component, navigate away (select something else) and return to the component. The newly assigned values are not retained but revert to the defaults (-1,-1,-1,-1,No H-Align,No V-Align).

**Comment by shannah** [comment]
Fixed SVN rev. 2356
