### ISSUE TITLE
Table Layout Row and Column constraints are not saved with the assigned values in GUI Builder

### ISSUE THREAD

**Issue by sol72** [codenameone/CodenameOne#2020]
Create a table layout with more than one row and column.
Add some components to it.
Select one of the components and assign it to a specific row and column. For example, Row 1, column 2.
Click "Save"
Open the XML file for the form. 
The row and column constraint values will both be set to '-1' instead of '1' and '2'

**Comment by shannah** [comment]
Fixed.  SVN rev. 2356
