### ISSUE TITLE
Antialiasing not working as expected

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2028]
I noticed that on IOS the native `Graphics.isAntiAliasingSupported` returns true but it does not do the antialiasing with `com.codename1.ui.Graphics.drawLine(int, int, int, int)`.

This code demonstrates that:

	public class FormAntiAliasingSupported extends Form {
		private class Demo extends Component {
			final boolean useNativeGraphics;
			final Label labelTitle;
			final Label labelSupport;
			boolean drawn = false;
			
			public Demo(boolean aUseNativeGraphics) {
				useNativeGraphics = aUseNativeGraphics;
				labelTitle = new Label(aUseNativeGraphics ? "native" : "image");
				labelSupport = new Label("unknown");
			}
			
			@Override
			protected Dimension calcPreferredSize() {
				Display display = Display.getInstance();
				int size = display.getDisplayWidth() / 5;
				return new Dimension(size, size);
			}
	
			public Label getLabelTitle() {
				return labelTitle;
			}
	
			public Label getLabelSupport() {
				return labelSupport;
			}
			
			@Override
			public void paint(Graphics aGraphics) {
				Image imageBuffer = useNativeGraphics ? null : Image.createImage(getWidth(), getHeight());
				Graphics graphics = useNativeGraphics ? aGraphics : imageBuffer.getGraphics();
				if (!drawn) {
					drawn = true;
					labelSupport.setText(String.valueOf(graphics.isAntiAliasingSupported()));
				}
				if (graphics.isAntiAliasingSupported()) {
					graphics.setAntiAliased(true);
				}
				graphics.setColor(0xffffff);
				graphics.fillRect(getX(), getY(), getWidth(), getHeight());
				graphics.setColor(0x000000);
				int x = useNativeGraphics ? getX() : 0;
				int y = useNativeGraphics ? getY() : 0;
				graphics.drawLine(x, y + getHeight(), x + getWidth(), y);
				if (!useNativeGraphics) {
					aGraphics.drawImage(imageBuffer, getX(), getY());
				}
			}
		}
		
		public FormAntiAliasingSupported() {
			super("FormAntiAliasingSupported", new BoxLayout(BoxLayout.Y_AXIS));
			setScrollable(false);
			Container contentPane = getContentPane();
			contentPane.setScrollableY(true);
			contentPane.add(new SpanLabel("Queries and tests antialiasing capabilities in native and image Graphics."));
			{ // native
				Demo demo = new Demo(true);
				contentPane.add(FlowLayout.encloseMiddle(
						demo.getLabelTitle(), demo.getLabelSupport(), demo
						));
			}
			{ // via image
				Demo demo = new Demo(false);
				contentPane.add(FlowLayout.encloseMiddle(
						demo.getLabelTitle(), demo.getLabelSupport(), demo
						));
			}
		}
	}

On an iPhone 5S it shows like this:
![img_5624](https://cloud.githubusercontent.com/assets/9945131/22589378/4d8b593c-ea0a-11e6-8f9f-327c42065e1c.PNG)

Detail:
![detailaa](https://cloud.githubusercontent.com/assets/9945131/22589403/72d35604-ea0a-11e6-9788-4204797cc31e.png)

**Comment by shannah** [comment]
This issue is resolved by making isAntiAliasingSupported() return correct values for graphics contexts (`false` for global contexts and `true` for mutable image contexts).  Opened new issue for the actual implementation of antialiasing in global contexts:
https://github.com/codenameone/CodenameOne/issues/2251
