### ISSUE TITLE
Windows UWP downloadable files should identify app

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#2042]
I have multiple CodenameOne apps.

On iOS and Android the generated files that I must archive or submit to the stores contain the main class name so each file is easily identifiable.

On UWP all files have the same generic filename, i.e. UWPApp_3.54.3.0_x86_x64_ARM_bundle.appxupload

This is difficult to manage, I can't tell which app the file is for Would it be possible top include the main class name in the downloadable filenames?

**Comment by shannah** [comment]
Fixed in SVN rev 2386
