### ISSUE TITLE
ChartComponent background issue

### ISSUE THREAD

**Issue by blessingmobile** [codenameone/CodenameOne#2044]
Hi, 

It seems the ChartComponent has a white background by default, therefore there is an issue on Android when the ChartComponent is placed on a non-white background.

When the ChartComponent is clicked it turns white. This issue seems to only occur on Android.

Potential fix is to make the ChartComponent transparent.

Test case that shows issue on Android device below:

        Font largeFont = Font.createSystemFont(Font.FACE_SYSTEM, Font.SIZE_LARGE, Font.STYLE_BOLD);
        Font smallFont = Font.createSystemFont(Font.FACE_SYSTEM, Font.SIZE_SMALL, Font.STYLE_BOLD);
        Font medFont = Font.createSystemFont(Font.FACE_SYSTEM, Font.SIZE_MEDIUM, Font.STYLE_BOLD);
        
        Form hi = new Form("Pie Chart", new BorderLayout());
        
        hi.getContentPane().setUIID("Button");
        
        ChartComponent comp;
        double[] values = new double[]{1, 2, 3};
        int[] colors = new int[]{ColorUtil.BLUE, ColorUtil.GREEN, ColorUtil.YELLOW};
        DefaultRenderer renderer = new DefaultRenderer();
        renderer.setLabelsTextSize(smallFont.getHeight() * 0.5f);
        renderer.setLegendTextSize(smallFont.getHeight() * 0.5f);
        renderer.setMargins(new int[]{medFont.getHeight(), medFont.getHeight(), medFont.getHeight(), medFont.getHeight()});
        for (int color : colors) {
            SimpleSeriesRenderer r = new SimpleSeriesRenderer();
            r.setColor(color);
            renderer.addSeriesRenderer(r);
        }
        renderer.setZoomButtonsVisible(true);
        renderer.setZoomEnabled(true);
        renderer.setChartTitleTextFont(largeFont);
        renderer.setDisplayValues(true);
        renderer.setShowLabels(true);
        renderer.setLabelsColor(ColorUtil.BLACK);

        //final CategorySeries seriesSet = buildCategoryDataset("Tasks", values);
        CategorySeries series = new CategorySeries("Tasks");

        series.add("Not Started", 1);
        series.add("Started", 2);
        series.add("Completed", 3);

        final com.codename1.charts.views.PieChart chart = new com.codename1.charts.views.PieChart(series, renderer);

        comp = new ChartComponent(chart) {

            private boolean inDrag = false;

            @Override
            public void pointerPressed(int x, int y) {
                inDrag = false;
                super.pointerPressed(x, y); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void pointerDragged(int x, int y) {
                inDrag = true;
                super.pointerDragged(x, y); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            protected void seriesReleased(SeriesSelection sel) {

                if (inDrag) {
                    // Don't do this if it was a drag operation
                    return;
                }

                for (SimpleSeriesRenderer r : renderer.getSeriesRenderers()) {
                    r.setHighlighted(false);
                }
                SimpleSeriesRenderer r = renderer.getSeriesRendererAt(sel.getPointIndex());
                r.setHighlighted(true);

                Shape seg = chart.getSegmentShape(sel.getPointIndex());
                Rectangle bounds = seg.getBounds();
                bounds = new Rectangle(
                        bounds.getX() - 40,
                        bounds.getY() - 40,
                        bounds.getWidth() + 80,
                        bounds.getHeight() + 80
                );

                this.zoomToShapeInChartCoords(bounds, 500);

            }

        };
        comp.setZoomEnabled(true);
        comp.setPanEnabled(true);
        //comp.setUIID("Label");
        hi.add(BorderLayout.CENTER, comp);
        hi.show();

**Comment by codenameone** [comment]
The chart itself has a background color that should be disabled, it's a pretty obtuse API though. I think we do this in the kitchen sink demo.

**Comment by blessingmobile** [comment]
Yes, I see on KitchenSink the Chart Background is set on Renderer, which
can go un noticed if one is not familiar with the API & it's easy to forget
it.



--
Kind Regards,
Blessing Mahlalela
Mfactory (Mobile Factory) CEO
(+27) 076 359 8094
(+27) 012 433 6553
blessing@mfactory.mobi

Office Address: Stevens House, Brooklyn Bridge Office Park, 570 Fehrsen St,
Nieuw Muckleneuk, Pretoria, 0181
