### ISSUE TITLE
RoundBorder with drop shadow performance issue

### ISSUE THREAD

**Issue by bryanjbuchanan** [codenameone/CodenameOne#2045]
If you have a form with multiple components with RoundBorders and drop shadow, there is a noticeable pause when transitioning to this form. If you remove the drop shadow, transition is smooth.

Have tested on a number of Android devices, with various OS versions. On some devices the lag is not too bad. Unfortunately, cannot test whether this is a function of the device or OS version.

Not noticeable in simulator on reasonably powerful desktop.

**Comment by codenameone** [comment]
Note to self: this should use a callSerially on idle to do the heavy lifting to reduce the overhead
