### ISSUE TITLE
Image artifacts on UWP Builds (seems to be pngs on desktop (not arm) builds

### ISSUE THREAD

**Issue by Paul1969** [codenameone/CodenameOne#2059]
I have had strange rendering issues appear when using transparent pngs. It seems to randomly happen fairly regularly and more often with certain pngs than others but they seem to get overwritten with strange artefacts.I have also seen some strange artefacts to appear in the side menu (when launched from the toolbar).

I have only seen this happen on my desktop (ie x86_64) builds and never on a phone (ARM builds).

I originally raised this on the discussion forum and attached a couple of screen dumps to illustrate... Shai's reply when I first raised this on the discussion forum was ...

"Hi,
it looks like images are overriding one another. This is very clear in the first image where the sidemenu shadow image is tiled and you can see it replaced with an icon.

Please file an issue on this.

I'm not familiar with the UWP port but these things might happen if an image is stored on the GPU and is moved to make room for another image. If GPU evacuation process isn't monitored we might be referring to a different image."

**Comment by codenameone** [comment]
Reference: https://groups.google.com/d/msg/codenameone-discussions/8Tv0WujIvio/lu6V6AytBAAJ

**Comment by shannah** [comment]
Please post a test case.  I haven't been successful in reproducing this so far.

**Comment by FabioConceicao** [comment]
We've stumbled upon this too, only in Desktop. The issue is with the removal of old cached images, this should fix the problem:

`

        public override object createImage(byte[] bytes, int offset, int len)
        {
        ...
                    dispatcher.RunAsync(CoreDispatcherPriority.Low, () =>
                    {
                  
                        imageCache.TryAdd(bytes.GetHashCode(), ci);
                        if (ApiInformation.IsTypePresent("Windows.Phone.UI.Input.HardwareButtons"))
                        {
                            while (imageCache.Count > maxCacheSize)
                            {
                                int toRemove = imageCache.OrderBy(m => m.Value.lastAccess).First().Key;
                                CodenameOneImage ignored;
                                imageCache.TryRemove(toRemove, out ignored);
                            }
                        }
                    }).AsTask();
`

**Comment by shannah** [comment]
Thanks.  That points me in the right direction.  It looks like the problem may be with the strategy for keys in the image cache.  It is using GetHashCode() on the byte array which is not well defined.  (Different versions of .Net will behave differently with how these are calculated).  Probably this cache isn't working at all in a lot of cases  (equivalent byte arrays are producing different hash codes).

I'm going to dig into this a little more to see if I can salvage that image cache.

**Comment by shannah** [comment]
A test case or instructions on reproducing this would still be appreciated @FabioConceicao @Paul1969 .
