### ISSUE TITLE
UWP Windows Phone crashes on HD device

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#2060]
When running the app in a Lumia 930 the app crashes trying to render an absurdly big image (seems like it gets the wrong 3x bigger screen size at first), it hits the GPU limit of 4096 pixels wide in phones. See https://github.com/Microsoft/Win2D/issues/38

Our current workaround is to set a temporary screen size at the WindowsAsyncView constructor, like this:

`

    bool firstPass = true;
    public WindowsAsyncView(CanvasControl screen) {
        _screen = screen;
        if (firstPass) {
            _screen.MaxWidth = 600;
            _screen.MaxHeight = 800;
            firstPass = false;
        }
        _screen.Draw += OnDraw;
    }
`

**Comment by FabioConceicao** [comment]
`
bool firstPass = true;
public WindowsAsyncView(CanvasControl screen) {
            _screen = screen;           
 if(Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.Phone.UI.Input.HardwareButtons"))  {
                if (isPas){
                    _screen.MaxWidth = 1080;
                    _screen.MaxHeight = 1260;
                    isPas = false;
                }
            }
            _screen.Draw += OnDraw;
  }

`
