### ISSUE TITLE
RFE: drawing rotated Images anti-aliased

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2065]
it's based on this [SO post](http://stackoverflow.com/questions/42765365/cn1-graphics-drawimage-with-aliasing-effects-after-rotation)

**Comment by shannah** [comment]
Notes to self on this issue (Pasted from email):

I think we can do something about this, but each platform will be different.  E.g. in Simulator I can achieve smooth results on rotated images if I use bilinear interpolation.  E.g. By changing setAntialiased to the following, I get a smooth result:



~~~~
public void setAntiAliased(Object graphics, boolean a) {
        checkEDT();
        Graphics2D g2d = getGraphics(graphics);
        if (a) {
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                   RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        } else {
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);
        }
    }
~~~~ 

![image](https://user-images.githubusercontent.com/2677562/29473080-350c09ba-840b-11e7-9255-a701dbd1747d.png)

I think the same can be achieved in iOS.  I see that in most places we're already using linear interpolation, but GLUIImage uses "nearest" interpolation for getTexture()--- that may be causing this.  Or it might work fine already... haven't tested.

And Android, UWP, and Javascript will each be different - and may already work smoothly.
