### ISSUE TITLE
Images not showing correctly with LocalNotification (at least on Android)

### ISSUE THREAD

**Issue by twilkinson** [codenameone/CodenameOne#2068]
When I use the LocalNotification object and 'scheduleLocalNotification' compiled to Android, the notification works but the message contains white squares where I would expect the application icons.

The behaviour is described in detail in the stackoverflow post at https://stackoverflow.com/questions/42893444/localnotification-icon-not-showing-on-codenameone and I've uploaded the ic_stat_notify.png file I am using.
![ic_stat_notify](https://cloud.githubusercontent.com/assets/1958073/24167354/d3d5ae50-0e4c-11e7-8b74-e72c597ba935.png)

**Comment by codenameone** [comment]
@shannah will this fit into your 3.7 schedule?
