### ISSUE TITLE
Incorrect deviceDensity on android with Small Display

### ISSUE THREAD

**Issue by jaanushansen** [codenameone/CodenameOne#2069]
Latest Android phones allow to configure display size and people seem to like to change it from Default to Small (Settings - Display - Display size).

But this results CN1 to detect wrong displayResolution. I was reported for Google Pixel, but managed to reproduce it also on Android simulator on Nexus 6 API 25:

With Default display size (1440x2392) Android DisplayMetrics show:
densityDpi=560
density=3.5
CN1 displayResolution=Display.DENSITY_560

With Small display size (1440x2417) Android DisplayMetrics show:
densityDpi=476
density=2.975
CN1 displayResolution=Display.DENSITY_MEDIUM

I think, that the error is in [AndroidImplementation](https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java).getDeviceDensity(), which uses for density detection [densityDpi](https://developer.android.com/reference/android/util/DisplayMetrics.html#densityDpi), whose Android api doc is quite misleading:

> The screen density expressed as dots-per-inch. May be either DENSITY_LOW, DENSITY_MEDIUM, or DENSITY_HIGH.

I suggest to use much better documented [density](https://developer.android.com/reference/android/util/DisplayMetrics.html#density) property like this:

		if (metrics.density <= 0.75) {
			//ldpi
			return Display.DENSITY_LOW;
		} else if (metrics.density <= 1) {
			//mdpi
			return Display.DENSITY_MEDIUM;
		} else if (metrics.density <= 1.5) {
			//hdpi
			return Display.DENSITY_HIGH;
		} else if (..) {
			...
		}

Screenshots:
With Default display size:
![default_display_size](https://cloud.githubusercontent.com/assets/11716510/24192761/b5e01848-0ef8-11e7-96e3-775b32f2181c.png)

But with Small display size:
![small_display_size](https://cloud.githubusercontent.com/assets/11716510/24192779/cafe39b2-0ef8-11e7-85d8-f2c17fa53ecd.png)

**Comment by codenameone** [comment]
That isn't the right approach. When we launched we used that API and it's implemented badly on devices so results were much worse. I eventually tracked a groups post from Romain claiming that API isn't covered by Googles TCK's and ignored by many vendors.

Please use the device tester demo on the device to extract the values of the constants from the device so we'll have a baseline to work with.

**Comment by jaanushansen** [comment]
Unfortunately I don't have access to physical Google Pixel device, maybe someone else happen to have to run the device tester demo?

But I have recorded some values by using a test run in Amazon Device farm with Google Pixel device (dimensions = Display.getInstance().getDisplayWidth()/Height()):

Small Display size:
densityDpi: 356
density: 2.225
dimensions: 1080x1760

Default Display size:
densityDpi: 420
density: 2.625
dimensions: 1080x1731
 
Largest Display size:
densityDpi: 540
density: 3.375
dimensions: 1080x1677


indeed it actually seems unlogical, that densities increase, but display dimensions decrease...

**Comment by codenameone** [comment]
I think it's just that the business theme has a custom check box icon image and it doesn't include a 2hd or hd value. 
Try removing the constants for the check images and see if it looks better.

**Comment by jaanushansen** [comment]
I forgot to mention, that in upper left corner d: shows currently used CN1 deviceDensity, that is the 2nd screenshot is using DENSITY_MEDIUM=30. So unfortunately adding images for 2hd and hd won't help. Because in this case densityDpi=476 and current code for unknown densities is:

          default:
                if(metrics.densityDpi > 640) {
                    return Display.DENSITY_4K;
                }
                return Display.DENSITY_MEDIUM;

**Comment by codenameone** [comment]
That's odd. What's the value for densityDpi on that device?

**Comment by codenameone** [comment]
OK, I see the problem

**Comment by jaanushansen** [comment]
thanks! But still a small question:
Why the 1st condition is that densities lower than DENSITY_LOW are detected as DENSITY_MEDIUM?
        
        if(metrics.densityDpi >= DisplayMetrics.DENSITY_LOW &&  metrics.densityDpi < 213) {
            return Display.DENSITY_LOW;
        }

and it's not just

        if(metrics.densityDpi < 213) {
            return Display.DENSITY_LOW;
        }
?

**Comment by jaanushansen** [comment]
some more questions:

the current code now never returns Display.DENSITY_MEDIUM.

probably the beginning should be:

        if(metrics.densityDpi < DisplayMetrics.DENSITY_MEDIUM) {
            return Display.DENSITY_LOW;
        }

        if (metrics.densityDpi >= DisplayMetrics.DENSITY_MEDIUM && metrics.densityDpi < 213) {
            return Display.DENSITY_MEDIUM;
        }
?

and is it intentional, that DisplayMetrics.DENSITY_HIGH is not Display.DENSITY_VERY_HIGH, because you have written:

        if(metrics.densityDpi > DisplayMetrics.DENSITY_HIGH && metrics.densityDpi < 400) {
            return Display.DENSITY_VERY_HIGH;
        }

**Comment by codenameone** [comment]
I fixed the first one. 

The second one is intentional. If we are higher than HIGH it should go to very high.

**Comment by jaanushansen** [comment]
yes, the second was my unfortunate misreading where I could not notice, that in if clause is DENSITY_HIGH and conditions returns DENSITY_VERY_HIGH (saw them both as DENSITY_VERY_HIGH..), I am sorry about that..

But still a question remains - you wrote, that 1st (adding DENSITY_MEDIUM) is fixed, but it's not yet in git?
