### ISSUE TITLE
FacebookConnect constructor should be public

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#2072]
The reason is that we can't implement the Facebook support directly in the UWP port this way (like we did in our XMLVM based port), we would have to extend the Login class and redo the FacebookConnect in C#.

**Comment by codenameone** [comment]
It's package protected, you should just create a subclass in the same package. This prevents users from doing something stupid like `new FacebookConnect()` and allows you to override the implementation.

See the Android port where this is implemented in that way

**Comment by FabricioCabeca** [comment]
Totally agree with the approach, the main problem is that we already tried that and it is not allowing to subclass FacebookConnect() in Visual Studio, even in the same namespace. We could workaround it extending Login() but that would be even more stupid. Ideas ?

**Comment by codenameone** [comment]
Have Java space user code portion of the port that subclasses it and makes it public. Since that's part of the port it isn't exposed to the user but will be exposed to the VS backend.
