### ISSUE TITLE
Unable to hide player controls for media (both video and audio)

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#2075]
Setting a media not to show native controls on both iOS and Android by calling `setNativePlayerMode(false)` and calling `video.getVideoComponent()` isn't effective.

This can be reproduced using the following code:

    private void playVideo(Form parentForm, Form nextForm, String videoUrl) {
        final Form player = new Form(new BorderLayout(CENTER_BEHAVIOR_CENTER));

        Command back = Command.create("", backIcon, evt -> {
            //Mimick "STOP" playing when back button is hit
            video.setTime(video.getDuration());
            video.pause();

            player.setTransitionOutAnimator(CommonTransitions.createSlideFadeTitle(false, 200));
            parentForm.showBack();
        });
        player.setBackCommand(back);
        player.getToolbar().addCommandToLeftBar(back);

        player.add(CENTER, new InfiniteProgress());
        parentForm.setTransitionOutAnimator(CommonTransitions.createSlideFadeTitle(false, 200));
        player.show();
        Display.getInstance().scheduleBackgroundTask(() -> {
            try {
                video = MediaManager.createMedia(videoUrl, true, () -> {
                    player.setTransitionOutAnimator(CommonTransitions.createSlideFadeTitle(false, 200));
                    nextForm.show();
                });
                video.setNativePlayerMode(false);
                video.prepare();
                Display.getInstance().callSerially(() -> {
                    Button btnPlay = new Button("", pauseIcon, "Label");
                    new Helper(btnPlay).textCenter().pa3().ma0();
                    paintBackgroundCircle(btnPlay);
                    btnPlay.addActionListener(e -> {
                        if (video.isPlaying()) {
                            btnPlay.setIcon(pauseIcon);
                            video.pause();
                        } else {
                            btnPlay.setIcon(playIcon);
                            video.play();
                        }
                        player.revalidate();
                    });

                    player.setLayout(new BorderLayout());
                    player.removeAll();
                    player.add(CENTER, video.getVideoComponent()).add(SOUTH, FlowLayout.encloseCenterMiddle(btnPlay));
                    player.revalidate();
                    video.setNativePlayerMode(false);
                    video.play();
                });
                player.revalidate();
            } catch (IOException err) {
                Log.e(err);
                ToastBar.showErrorMessage("Error loading video: " + err);
            }
        });
    }

**Comment by diamondobama** [comment]
Hi Steve & Shai,

Have you had a chance to take a look at this, please?

**Comment by codenameone** [comment]
I didn't really read this before assigning it to Steve but re-reading it I'm not sure it's a bug.

````java
    /**
     * By calling this the Media (if it's a Video) will be played full screen
     * on the native Player of the device.
     * Native playing assumes getVideoComponent() hasn't been called on this Media
     * unexpected behaviour may occur if getVideoComponent() has been called
     * and the Component is placed on a Form.
     * Some platforms such as BlackBerry is able to play video only on the native
     * player on those platforms isNativePlayerMode() will always return true
     */
    public void setNativePlayerMode(boolean nativePlayer);
````

What I read here is that `setNativePlayerMode` will make the UI full screen with native controls. It doesn't mean that non-fullscreen mode won't have native controls.

I think we can probably add a variable that will hint to the platform that native controls aren't desirable and use the `setVariable()` method that's already there.

**Comment by diamondobama** [comment]
I think I didn't state clearly that I set `setNativePlayerMode()` to `false` and I used `video.getVideoComponent()` to add the player to my form.

It would be great if `setVariable()` can allow specifying whether we want the controls or not.

**Comment by shannah** [comment]
Support for this has been added via:

~~~~
Media someMedia = ...
...
someMedia.setVariable(Media.VARIABLE_NATIVE_CONTRLOLS_EMBEDDED, false); // hides native controls

or

someMedia.setVariable(Media.VARIABLE_NATIVE_CONTRLOLS_EMBEDDED, true); // shows native controls
~~~~

The MediaPlayer class also has new methods to show/hide controls, and to toggle native video controls on and off.

**Comment by diamondobama** [comment]
Thank you!
