### ISSUE TITLE
Android Build failure: manifest merge error with FaceBook plugin

### ISSUE THREAD

**Issue by hasselstromk** [codenameone/CodenameOne#2076]
I've been successfully building my app for several weeks in IOS Debug and Android.  My app has had facebook integration during the entire successful build period.  My most recent Android build is now failing.  IOS Build is still successful.

Here is the error in the cloud build logs related to facebook android sdk manifest merger problem:

Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 15 declared in library [com.facebook.android:facebook-android-sdk:4.7.0] /tmp/build4659026421781606323xxx/TaskApp/build/intermediates/exploded-aar/com.facebook.android/facebook-android-sdk/4.7.0/AndroidManifest.xml

**Comment by shannah** [comment]
You can work around this issue for now by adding the following build hint:

`android.min_sdk_version=15`

**Comment by shannah** [comment]
This is fixed now in SVN (will not require above workaround), and will be available in the next build server update.

**Comment by hasselstromk** [comment]
Just confirmed that Android build is now working with Facebook SDK.
