### ISSUE TITLE
Add BoolProperty class

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2077]
currently in order to have `boolean` properties we need to use something like: `Property<Boolean, Owner> property`. But the problem is that on deserialization (over `PropertyIndex`) that property's value becomes a `String` and therefore we get the following exception when we try to access its value:
**java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean**

**Comment by codenameone** [comment]
Thanks, I actually just ran into this myself recently but it stems from the fact that JSONParser doesn't parse Boolean values correctly. That's a good fix as well so I think a good solution will be to include both. Unfortunately the boolean fix for the JSONParser might be a compatibility nightmare.

**Comment by codenameone** [comment]
Fixing `JSONParser` will require migrating the code to Java 8 as we'll need to add a default method to the callback interface. It's something we plan on doing so the full fix will have to wait for that. I'll add the `BooleanProperty` class in the interim which will solve this specific issue.

**Comment by codenameone** [comment]
The migration to Java 8 in terms of the Android port is proving to be harder than expected. I'm not sure this is something we'd want to go into for now. I chose to go in a different route
