### ISSUE TITLE
Changing Android language causes black-screen app

### ISSUE THREAD

**Issue by jaanushansen** [codenameone/CodenameOne#2078]
Hi!

noticed a case, where CN1 Android app open always fails:

1) Open app
2) Open Android Settings and change device language
3) Reopen the app either from app icon or by app switching for both cases now the app shows black screen. (on second reopen the app works normally)

Tested on Android 6.0 simulator.

For testing was used very basic hello-worlds app:

	    public void start() {
	        if(current != null){
	            current.show();
	            return;
	        }
	        final Form hi = new Form("Welcome!", new BorderLayout());
	        hi.add(BorderLayout.CENTER, new Label("Lang: " 
	        		+ Display.getInstance().getLocalizationManager().getLanguage()));
	        hi.show();
	    

Hopefully phone language switching happens only in QA phones, but I am afraid that there might be other, more common config changes, which might similarly cause the black screen...

**Comment by codenameone** [comment]
Is there a stack trace in DDMS?

**Comment by jaanushansen** [comment]
Log after reopening looks like this:

	04-01 14:54:34.956 3135-3135/my.test.app I/System.out: Waiting for deinitializing to complete before starting a new initialization
	04-01 14:54:35.037 3135-3231/my.test.app E/EGL_emulation: tid 3231: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
	04-01 14:54:35.037 3135-3231/my.test.app W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xaaa4d260, error=EGL_BAD_MATCH
	04-01 14:54:35.059 3135-5154/my.test.app D/Codename One: sizechanged: 1080 1731 com.codename1.impl.android.CodenameOneView@9c10f85
	04-01 14:54:35.071 3135-5154/my.test.app I/System.out: showKeyboard false

**Comment by jaanushansen** [comment]
Investigated it some more:

When system language is changed, then Android calls on app resume onDestroy()  followed by onCreate() (https://developer.android.com/guide/topics/resources/runtime-changes.html).

And unfortunately CN1 at the moment can't handle this sequence correctly. For me the logic was too complex to fix, so for now I used a work-around:

Added all possible configChanges options to Android manifest:

android:configChanges="keyboardHidden|orientation|locale|mcc|mnc|touchscreen|keyboard|navigation|screenLayout|fontScale|uiMode|screenSize|smallestScreenSize|layoutDirection"

(https://developer.android.com/guide/topics/manifest/activity-element.html#config)

This way Android is not restarting the app, it's is still not nice that app language is not changing, but it looks way nicer than black screen :)

**Comment by jaanushansen** [comment]
Thank you, it really seems to work now!
