### ISSUE TITLE
Android: Display.execute(url) requires unnecessary WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by jaanushansen** [codenameone/CodenameOne#2079]
It turns out, that Display.getInstance().execute(url) is not working correctly for url open Android 6.0+.

When the following code is run:

	        button.addActionListener(new ActionListener<ActionEvent>() {

				@Override
				public void actionPerformed(ActionEvent evt) {
					Display.getInstance().execute("https://www.codenameone.com");
				}
	        	
			});

Then app asks for media permission (which is not needed for simple urls):
![permission_request](https://cloud.githubusercontent.com/assets/11716510/24608094/92ae6f58-187d-11e7-9336-460ecce3c191.png)

The problem reason seems to be, that in https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java createIntentForURL method has this code:
    
            if (url.startsWith("intent")) {
                intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME);
            } else {
                if(!checkForPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE, "This is required to open the file")){
                    return null;
                }

**Comment by codenameone** [comment]
I think the else statement needs to be wrapped with `if(url.startsWith("file"))`. If you want to submit a pull request I'll approve it I'm just a bit busy with the bootcamp right now.
