### ISSUE TITLE
Need to support different mime types for multipart request & not fail on missing file name

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2080]
Currently multipart request has two hardcoded mime types for binary & text data which prevents me from mixing JSON and binary data into a single request. I would expect a method similar to setFilename only for setMimeType per entry. This needs to be configurable so it will also work with the length calculation code.

We should also have a default file name (matching the entry name) so there won't be an exception for missing filenames. 

If we're changing the code I suggest updating it for generics and removing the usage of the old collection classes while we are at it

**Comment by shannah** [comment]
It looks like this use case (mixing JSON with binary) can be accomplished using addData().  It lets you set the file name, data, and mimetype all together.

It still sets "Transfer-Encoding" to "binary", but you should be able to have parts with JSON (application/json), and binary (application/octet-stream) in the same request.

If you stick to using addData(), missing filenames also become a non-issue.

**Comment by codenameone** [comment]
I've had an NPE in 257 will that be reached with that version of addData?

**Comment by shannah** [comment]
Puzzling.  The only way I can see an NPE occurring there is if you called addData() with a `null` "name" parameter (first parameter null).

**Comment by codenameone** [comment]
I didn't set the file name. So filenames.get(name) would return null thus fail on the get bytes

**Comment by shannah** [comment]
But addData(name, ...) should automatically set the file name as far as I can tell.

https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/io/MultipartRequest.java#L118
https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/io/MultipartRequest.java#L150

**Comment by codenameone** [comment]
I wrote: "I've had an NPE in 257 will that be reached with that version of addData?"
This is an NPE I had with the previous code... I'll try to test again when I'll get the chance.

**Comment by codenameone** [comment]
I didn't have time to test but I'll assume this works for now
