### ISSUE TITLE
Android Filechooser lib and openGallery breaks Inputstream

### ISSUE THREAD

**Issue by xHatti** [codenameone/CodenameOne#2081]
If i use the filechooser library and open up the inputstream from the returned source, the method "InputStream.available" always rounds up by 1024 bytes. As example: i select a file with only 10 bytes, the available method returnes 1024. I select a file with 1200 bytes, the available method returnes 2048

This happens too if i read from the inputstream. I always get additional bytes.

I looked into the filechooser libary code and noticed it uses the Display.openGallery(Actionlistener, -9999)
So i used it too and the same thing happened. The bytes from the selected file are always rounded up to 1024.

The filechooser and the Display.openGallyery with the type (second parameter) -9999 opens up the native filechooser.

Here is the sample code i used for testing:

```
public void start()
{
	if (current != null)
	{
		current.show();
		return;
	}
	Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
	Container container = new Container(new BoxLayout(BoxLayout.Y_AXIS));
	hi.addComponent(BorderLayout.CENTER, container);
	try
	{
		String testString = "TestKuchen";
		FileSystemStorage instance = FileSystemStorage.getInstance();
		String appHomePath = "/storage/emulated/0/tmp/";
		String path = "/storage/emulated/0/tmp/test.log";
		File file = new File(path);
		if (file.exists())
			file.delete();
		File dir = new File(appHomePath);
		if (!dir.exists())
			if (!dir.mkdirs())
				instance.mkdir(appHomePath);
		file.createNewFile();
		try (OutputStream openOutputStream = instance.openOutputStream(path);)
		{
			byte[] bytes = testString.getBytes();
			openOutputStream.write(bytes);
			openOutputStream.flush();
			openOutputStream.close();
			container.addComponent(new Label("StringLenght: " + bytes.length));
		}
		try (InputStream is = instance.openInputStream(path))
		{
			container.addComponent(new Label("IS Lenght b4 FC: " + is.available()));
		}
		container.addComponent(new Button(new Command("Just do it!")
		{
			@Override
			public void actionPerformed(ActionEvent evt)
			{
				super.actionPerformed(evt);
				FileChooser.showOpenDialog("*.*", evt2 -> {
					String source = (String) evt2.getSource();
					container.addComponent(new Label("Source: " + source));

					container.addComponent(new Label("FileLenght: " + instance.getLength(source)));
					try (InputStream is = instance.openInputStream(source))
					{
						container.addComponent(new Label("FileLenght IS Available: " + is.available()));
					}
					catch (IOException e)
					{
						e.printStackTrace();
					}
					hi.revalidate();
					try (InputStream is = instance.openInputStream(path))
					{
						container.addComponent(new Label("IS TMPFILE Lenght AFTER FC: " + is.available()));
					}
					catch (Throwable e)
					{
						e.printStackTrace();
					}
				});
			}
		}));
		hi.show();

	}
	catch (Throwable e)
	{
		Log.e(e);
		Log.showLog();
	}
}
```

It creates a txt file in /tmp/ with a small string. Reads it though hardcoded filepath.
If you click the button to use the filechooser and select the same file, it will round up to 1024 bytes

It also copies the selected file into the application storage.
As you can see in the code. The test files path is "/storage/emulated/0/tmp/test.log"
After selecting the file though the filechooser, the filepath is different and is in the application storage.

**Comment by shannah** [comment]
From [InputStream javadocs](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#available()):

> Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not. It is never correct to use the return value of this method to allocate a buffer intended to hold all data in this stream.

I.e. This is valid behaviour

**Comment by xHatti** [comment]
Please read the full text. This is even happening if i READ from the inputstream!
Use the code above and try to read from the stream to write the same file. You will always have a difference in it!

**Comment by shannah** [comment]
Given that `available()` should not be counted on to return accurate information, which line of your example is producing unexpected results?

**Comment by xHatti** [comment]
Its not in the example cause its mentioned in the text above.
But you can reproduce it by replacing "is.available()" in line 50 with Util.readInputStream(is).length

As mentioned, this only happens on android devices if the filechooser is the native one. Tested on nexus 7 (2013) and pixel tablet
