### ISSUE TITLE
Native editor on wrong position for vertically centered textfields on iOS

### ISSUE THREAD

**Issue by jaanushansen** [codenameone/CodenameOne#2091]
Hi!

I noticed quite a specific issue on iOS:

When textfield height is larger than preferred and it's centered vertically, then on field edit the native textfield is drawn below the expected position.

Test code:

```java
final Form hi = new Form("Welcome!", new BorderLayout());
TextField field = new TextField("test");
field.setVerticalAlignment(Component.CENTER);
hi.add(BorderLayout.CENTER, field);
hi.show();
```

On field edit the native textfield is below the expected position (I manually changed to  [utf setBackgroundColor:[UIColor greenColor]]; in CodenameOneGLViewController.m to visualise native field positions)

![editor_open](https://cloud.githubusercontent.com/assets/11716510/25064712/f4bffef2-2208-11e7-9f2c-bae491cc2b21.png)

The problem seems to be fixable by removing
```java
                    case TextArea.CENTER:
                        if(h > cmp.getPreferredH()) {
                            y += (h / 2 - cmp.getPreferredH() / 2);
                        }
                        break;
```
snippets from
https://github.com/codenameone/CodenameOne/blob/master/Ports/iOSPort/src/com/codename1/impl/ios/IOSImplementation.java

**Comment by codenameone** [comment]
This would need fixing in native code as well as behaviors like right alignment and bottom alignment. We don't support either at the moment as the edge cases are too severe with getting the lightweight and heavyweight text to occupy the same location.
