### ISSUE TITLE
Display.getInstance().registerPush should take a Map not a Hashtable

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2095]
Hashtable is not recommended and shows up as a warning in the IDE and in static analysis but it necessary to use in the app due to the signature of this method specifically using Hashtable when a Map would work.

**Comment by codenameone** [comment]
Both arguments should be removed as they are both meaningless now. The push argument for Android should be passed as a hint now so push on Chrome will work.
