### ISSUE TITLE
The generated ipa stuck in an 'installing' loop

### ISSUE THREAD

**Issue by ronlinet** [codenameone/CodenameOne#2104]
I have created a minimal demo app from the default tab template and the generated apk works correctly on my Android phone. 
When it comes to the generated iphone app the ipa is correctly installed on the device but when I press the app icon it just show a message 'installing' and the app stuck in an infinite “installing” loop. The device is an iphone 4 with IOS 7.1

**Comment by codenameone** [comment]
http://stackoverflow.com/questions/42585376/cant-install-development-build
