### ISSUE TITLE
Implement android 6 permissions into the Bluetooth cn1lib

### ISSUE THREAD

**Issue by fredbar** [codenameone/CodenameOne#2109]
Since android 6, permissions need to be obtained at runtime to access some resources. By not doing so, library silently fails.
[BLE library](https://github.com/codenameone/bluetoothle-codenameone) is an identified target. Others could be impacted by this.

Temporary workaround is to compile for android 5, which then asks for permission when installing. This is done by define a build hint to the project: android.targetSDKVersion=21

See https://www.codenameone.com/discussion-forum.html?place=topic%2Fcodenameone-discussions%2FcCse_IwnuSM%2Fdiscussion for the complete thread on this discussion.

**Comment by codenameone** [comment]
I updated the title to reflect that this is only an issue in the bluetooth library as other libraries work with permissions.

**Comment by codenameone** [comment]
This was fixed by a community member in the lib a while back
