### ISSUE TITLE
RFE - Better iOS screenshots for Apple Store

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#2113]
Hi, just got an app metadata rejected because the screenshots were not close enough to the real device (IMHO they were quite close), we do have the latest iPhone but not the plus one, with the biggest screen, neither the iPad one, so we managed to fix this by grabbing a mac and taking the screenshots from simulator there. I wonder if it is not the case to generate those screenshots using xcode instead of the java simulator when sending an appstore build, not as straightforward but would be bulletproof. It should be as easy as launching the simulator and running the command below:

`xcrun simctl io booted screenshot`

If those images are not meant to be used like this I believe generating screenshots for appstore would be a nice addition.

**Comment by FabricioCabeca** [comment]
Update, they didn't like the fact that the screenshot was from the splash screen, they wanted some real usage, maybe simply a bigger delay would solve this. Maybe I guessed wrong the real usage of those images ?

**Comment by codenameone** [comment]
What's wrong with Simulator -> Screenshot?

**Comment by FabricioCabeca** [comment]
This is what I've done in one use case, but I guess I misinterpreted the reject message, they said to upload a real usage image, but the real usage I believe should be the app in action and not a splash screen. So I'm going to close this for now.
