### ISSUE TITLE
crash in IOS editstring implementation 

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2117]
Presumably this is an interaction with some other process

[2017/05/25 04:38:31] log request from bridge.MasterForm (61.68.174.205)
data=[Java cpu=8.4% screen=2048x1536 ppi=160 Codename1  2.19 Ios] (EDT 13 threads)last chance error catcher
error is : java.lang.NullPointerException: null
[EDT] 0:0:0,0 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
    at com_codename1_impl_ios_IOSImplementation.editString:799
    at com_codename1_impl_CodenameOneImplementation.editStringImpl:317
    at com_codename1_ui_Display.editString:1522
    at com_codename1_ui_Display.editString:1493
    at com_codename1_ui_TextArea.editString:607
    at com_codename1_ui_TextArea.pointerReleased:640
    at com_codename1_ui_Form.pointerReleased:2683
    at com_codename1_ui_Component.pointerReleased:3266
    at bridge_MasterForm.pointerReleased:2200
    at com_codename1_ui_Display.handleEvent:2026
    at com_codename1_ui_Display.edtLoopImpl:1071
    at com_codename1_ui_Display.mainEDTLoop:1000
    at com_codename1_ui_RunnableWrapper.run:120
    at com_codename1_impl_CodenameOneThread.run:176

**Comment by shannah** [comment]
Fixed.  Will be in next server update.
