### ISSUE TITLE
OTA link error by windows UWP build

### ISSUE THREAD

**Issue by hittergabor** [codenameone/CodenameOne#2124]
If I choose "e-mail Link" on the windows build (on dashboard), then I get a mail, with a wrong link.:
"Error: Not Found
The requested URL  XXX  was not found on this server."

(XXX: here I see the URL, but I don't copy it here)

By android build, it's work, the link point to the downloadable apk file.

*****************************************

the Downloadable Files (working link) has the following format:
https://codename-one.appspot.com/getData?m=result&i=XXX&b=YYY&n=ZZZ.appxbundle

the OTA Installation Files (wrong link) has the following format:
http://codename-one.appspot.com/XXX/YYY/ZZZ.appxbundle

the differents are:
https <-> http
getData?m=result&i==   is missing
&n=   is missing

**Comment by codenameone** [comment]
Fixed in server and should be a part of the update tomorrow
