### ISSUE TITLE
Graphics#fillRoundRect renders very different in the simulator compared to IOS

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2125]
See the same component rendered ...

in the simulator with iPhone 5 skin and ...
![frr_simulator](https://cloud.githubusercontent.com/assets/9945131/26716321/3f6a0ae8-4779-11e7-98d5-67ed293f37cc.png)

on an iPhone SE
![frr_iphonese](https://cloud.githubusercontent.com/assets/9945131/26716334/4c270574-4779-11e7-80ec-a68808c32741.jpg)

Here is the code:

	public class FormRoundRect extends Form {
		private class Dimensions {
			int width, height, arcSize;
			@Override
			public boolean equals(Object aThingy) {
				if (!(aThingy instanceof Dimensions)) {
					return false;
				}
				Dimensions dimensionsB = (Dimensions) aThingy;
				return (width == dimensionsB.width
						&& height == dimensionsB.height
						&& arcSize == dimensionsB.arcSize);
			}
		}
		private Dimensions dimensionsPrevious = new Dimensions();
	
		public FormRoundRect() {
			super("FormRoundRect", new BoxLayout(BoxLayout.Y_AXIS));
			setScrollableX(false);
			setScrollableY(true);
			TextArea textArea = new TextArea("");
			textArea.setEditable(false);
			add(textArea);
			Container containerRoundRect = new Container() {
				{
					byte[] paddingUnit = new byte[] {
							Style.UNIT_TYPE_SCREEN_PERCENTAGE,
							Style.UNIT_TYPE_SCREEN_PERCENTAGE,
							Style.UNIT_TYPE_SCREEN_PERCENTAGE,
							Style.UNIT_TYPE_SCREEN_PERCENTAGE,
							};
					Style style = getAllStyles();
					style.setPaddingUnit(paddingUnit);
					style.setPadding(2, 2, 2, 2);
					style.setMarginUnit(paddingUnit);
					style.setMargin(2, 2, 2, 2);
				}
				@Override
				protected Dimension calcPreferredSize() {
					return new Dimension(100, 100);
				}
				@Override
				public void paint(Graphics aGraphics) {
		            if (aGraphics.isAntiAliasingSupported() && !aGraphics.isAntiAliased()) {
		                aGraphics.setAntiAliased(true);
		            }
		            Dimensions dimensions = new Dimensions();
		            dimensions.width = getWidth();
		            dimensions.height = getHeight();
		            dimensions.arcSize = getHeight() / 3;
		            aGraphics.setColor(0x000000);
		            aGraphics.fillRect(
		            		getX(),
		            		getY(),
		            		dimensions.width,
		            		dimensions.height);
		            aGraphics.setColor(0xffffff);
		            aGraphics.fillRoundRect(
		            		getX(),
		            		getY(),
		            		dimensions.width,
		            		dimensions.height,
		            		dimensions.arcSize,
		            		dimensions.arcSize);
		            if (!dimensionsPrevious.equals(dimensions)) {
		            	dimensionsPrevious = dimensions;
		            	textArea.setText(
		            			"width: " + dimensions.height + "; " +
		            			"height: " + dimensions.height + "; " +
		            			"arcSize: " + dimensions.arcSize);
		            }
				}
			};
			add(BorderLayout.centerCenter(containerRoundRect));
		}
	}

**Comment by shannah** [comment]
@codenameone Looks like iOS and Android (and likely all other ports) treat the arc width and height as radius, whereas the simulator treats it as diameter (since Java2D's fillRoundRect() treats them as diameter).  Our javadocs also state that it is diameter.

Do we change to align with Java2D (i.e. change all ports to diameter), or make change that affects fewest platforms (i.e. change simulator to radius - and update javadocs)?

**Comment by codenameone** [comment]
I don't think we should fix this. The API is "done".

Instead use the Shape API which is consistent and modern. It's what we use in `RoundBorder` and is 100% cross platform.

I think the fix should be to deprecate the old API's.
