### ISSUE TITLE
IOS Build Fails: OBJC_CLASS_$_EKAlarm", referenced from:  objc-class-ref in com_codename1_calendar_impl_CalendarNativeInterfaceImpl.o

### ISSUE THREAD

**Issue by rvdkruit** [codenameone/CodenameOne#2126]
Hi 
I'm relative new in building apps with codename one.
I'm building an app which builds just fine on Android.
Now I want to build the app for IOS as well, but the build for IOS keeps failing.
In the error log I find this message:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_EKAlarm", referenced from:
      objc-class-ref in com_codename1_calendar_impl_CalendarNativeInterfaceImpl.o
  "_OBJC_CLASS_$_EKEvent", referenced from:
      objc-class-ref in com_codename1_calendar_impl_CalendarNativeInterfaceImpl.o
  "_OBJC_CLASS_$_EKEventStore", referenced from:
      objc-class-ref in com_codename1_calendar_impl_CalendarNativeInterfaceImpl.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Am I missing something?
I attached the full log to the issue
[error.txt](https://github.com/codenameone/CodenameOne/files/1049821/error.txt)

Thanks

**Comment by codenameone** [comment]
This is due to a missing `ios.add_libs` statement
