### ISSUE TITLE
{"error":"Token is required for push to work"}

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2131]
Could you tell me why from your push server I ‘m receiving this json error:

2:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()-----------------------------------------
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()SENDING MESSAGE
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()-----------------------------------------
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->token       :xxxxxxxxxxxx
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->device      :cn1-gcm-APA91bEmKSKZe2gTKivcr5OR3Qmx016YrqdnrZtFLmco-Py23ybCZbtU96cGKT-q7-iFPDqINClncN7X0wkESquVGo8EVjNH9awO6fX4ObQHuha1WfbS7w-szCP408GuRexR3UDvgp4sXQVxCZC7Tl-75eJYwXHa5w
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->email       :soporte@geotrack-solutions.com
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->type        :1
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->body        :'20258','3','1','Bienvenid@, estamos procesando su solicitud...','Jun  8 2017  9:38PM','0','0','0';
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->auth        :xxxxxxxxxxx
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->production  :false
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->certPassword:xxxxxx
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->cert        :https://cert.forcesos.com/ios/dev_pn_forcesos_gts_230816_240817.p12
| 09-06-2017 08:42:31.274 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()-----------------------------------------
| 09-06-2017 08:42:31.572 AM | PnForceSosCn1_v2.7 | PushServer | Info | sendPush()->statusCode:200
| 09-06-2017 08:42:31.572 AM | PnForceSosCn1_v2.7 | PushServer | Info | sendPush()->response  :**{"error":"Token is required for push to work"}**
| 09-06-2017 08:42:31.572 AM | PnForceSosCn1_v2.7 | PushServer | Info | run()->markCn1PnMessageAsSent:22974

**Comment by DurankGts** [comment]
I'm sending my correct token of my account

**Comment by codenameone** [comment]
That means we didn't get the token. What you submitted here is a log from your app which isn't helpful. What I need to see is http monitor output indicating how the request was sent.
