### ISSUE TITLE
bad IOS code generated

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2135]
This code, when called with null as the "lp" argument, crashes the app rather than throw
a null pointer exception.  I don't see a null check.

    public boolean isALocalPlayer(commonPlayer lp)
    { 	int who = lp.boardIndex;
    	for(int lim=localPlayers.size()-1; lim>=0; lim--)
    	{
    		if(localPlayers.elementAt(lim).order==who) { return(true); }
    	}
    	return(false);
    }

Here's the IOS code generated.

`JAVA_BOOLEAN online_game_commonCanvas_isALocalPlayer___online_game_commonPlayer_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT  __cn1ThisObject, JAVA_OBJECT __cn1Arg1) {
    volatile JAVA_INT ilocals_3_ = 0; /* v3 */
    volatile JAVA_INT ilocals_2_ = 0; /* v2 */
    DEFINE_INSTANCE_METHOD_STACK(2, 4, 0, 10640, 10664);
    locals[0].data.o = __cn1ThisObject; locals[0].type = CN1_TYPE_OBJECT;     locals[1].data.o = __cn1Arg1;
    locals[1].type = CN1_TYPE_OBJECT;
    /* VarOp.assignFrom */ ilocals_2_ = get_field_online_game_commonPlayer_boardIndex(locals[1].data.o);
    { JAVA_INT tmpResult = virtual_online_common_LaunchUserStack_size___R_int(threadStateData, get_field_online_game_commonCanvas_localPlayers(__cn1ThisObject));
        PUSH_INT(tmpResult); }
    PUSH_INT(1); /* ICONST_1 */
    SP--; SP[-1].data.i = (SP[-1].data.i - (*SP).data.i); /* ISUB */
    BC_ISTORE(3);
    
label_L1093441678:
    if (ilocals_3_<0) /* IFLT CustomJump */ goto label_L460380035;
    /* CustomInvoke */{ JAVA_OBJECT tmpResult = virtual_online_common_LaunchUserStack_elementAt___int_R_java_lang_Object(threadStateData, get_field_online_game_commonCanvas_localPlayers(__cn1ThisObject), ilocals_3_);
        PUSH_OBJ(tmpResult); }
    PUSH_INT(get_field_online_common_LaunchUser_order(POP_OBJ()));
    (*SP).type = CN1_TYPE_INT; /* ILOAD */
    (*SP).data.i = ilocals_2_;
    SP++;
    SP-=2; if((*SP).data.i != SP[1].data.i) /* IF_ICMPNE */ goto label_L223668104;
    releaseForReturn(threadStateData, cn1LocalsBeginInThread); return 1 /* ICONST_1 */;
    
label_L223668104:
    BC_IINC(3, -1);
    goto label_L1093441678;
    
label_L460380035:
    PUSH_INT(0); /* ICONST_0 */
    releaseForReturn(threadStateData, cn1LocalsBeginInThread); return SP[-1].data.i;
}

JAVA_INT get_field_online_game_commonPlayer_boardIndex(JAVA_OBJECT __cn1T) {
    return (*(struct obj__online_game_commonPlayer*)__cn1T).online_game_commonPlayer_boardIndex;
}
`

**Comment by codenameone** [comment]
It seems we rely too much on encapsulation the field access isn't guarded which is probably a good idea. We might want to add field guarding but only to public and package protected non-static fields. That way performance/size can still be good

**Comment by ddyer0** [comment]
or generate two different accessor methods, one where it is known to be a field of "self"
and one for everything else.

**Comment by ddyer0** [comment]
BTW, when I first looked at the implementation of your IOS vm, I was surprised to
see all those null checks.  I would have implemented null as a first class object, a
singleton that throws null pointer exception for all methods, with no overhead
to everthing else.  I suppose you had your reasons.

**Comment by codenameone** [comment]
You mean a global function or macro that does the check.  We used to have that but removed it.
The core of the issue was compilation speed as macros are really slow and functions have an overhead. An if statement is cheap in both cases.

I'm not in favor of two functions. It will increase code size and slow compilation. Most variables are private or protected so this shouldn't be much of a problem.

**Comment by ddyer0** [comment]
I was thinking that when accessing an instance variable of "self" you would use the current
function, and when accessing it from non-self you'd have a second function that included
a null check.  The existing code that removes unused functions would take care of the rest.

**Comment by shannah** [comment]
I have added an optional build hint `ios.fieldNullChecks` which, when set to "true" will insert a null check before all field setting and getting.  Right now it defaults to "false".

https://github.com/codenameone/CodenameOne/commit/a9cb03a5ea88f9e1d5ec5dde38be2192087e668b

This is not as fine-grained as some of the approaches suggested here, but it does give you the ability to add these null checks, at the tradeoff of performance and code-side, if you wish.

**Comment by ddyer0** [comment]
given the severity of the crash, I object to closing this, especially with false as the default.

**Comment by shannah** [comment]
@codenameone What do you think about trying to integrate a signal handler (ala http://www.cocoawithlove.com/2010/05/handling-unhandled-exceptions-and.html) to make it fail more gracefully in cases like this.  Looks like it wouldn't be too hard.

**Comment by ddyer0** [comment]
you ought to do that anyway.   The existing behavior of crashing hard is double plus ungood.

I sure hope no one is depending on the details of this kind of exception for normal operations,
but the more closely you can make this kind of trap look like NullPointerException the better.  

If I were designing your vm from scratch, I would arrange the representation of null so 
that trying to dispatch a field or function access would trap out gracefully, without any
additional overhead for field or function access of non-null.   ie; null should be a singleton
in a well defined class.  I realize it may be too late for that now.

**Comment by shannah** [comment]
Fair enough.  Reopening.  Will make it more fine-grained.

**Comment by codenameone** [comment]
I can't find it right now but I had an RFE for integrating a crash protection tool that will send VM state out using our existing crash protection solution. Effectively this would be the same as signal handling since we are already 90% there thanks to the VM. So ideally if we can catch all failures and trigger Java style exceptions that would be great.

**Comment by shannah** [comment]
With this last commit, all bad accesses will be thrown as NPEs that can be caught, so I'm leaning toward leaving this class of Null check turned off by default.

**Comment by ddyer0** [comment]
Sounds right to me.  Thanks.
