### ISSUE TITLE
setComponentLimit on Infinite Scroll causes scrolling issues

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#2140]
When using setComponentLimit on Infinite Scroll, components are removed from the top but don't scroll up by the right amount to compensate which cause components to scroll down abruptly.

**Comment by codenameone** [comment]
Relevance link: https://groups.google.com/d/msg/codenameone-discussions/W80exFraaFc/eGgAZ3yeAQAJ

**Comment by codenameone** [comment]
I've spent a few hours trying various approaches and I think this is hopeless. I think we'll need to create a new `InfiniteScrollAdapter` based on the scroll listener. That's a big task in its own right. The scroll listener didn't exist when the original code was written so we use a bit of a hack there and it's triggering this problem. 

This feature has some general complexity too e.g. if a user wants to scroll back up the components won't return...
