### ISSUE TITLE
Signature Component allows drawing outside the box

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2143]
When signing there is a box presented but it is possible to draw anywhere on the screen, on save the only the part of the signature within the box is saved.

The entire drawing area should be saved, either by saving the full screen or only allowing drawing within the box.

Client feedback suggests the bigger the better for signing purposes in real life applications.

**Comment by codenameone** [comment]
I think it might make sense to broaden the API a bit to give control over the details of this. I know some users asked for the box and for the ability to overflow. If users are given too little space they drag outside of the area which is bad for signatures.
