### ISSUE TITLE
Slider Thumb Icon

### ISSUE THREAD

**Issue by thomasmcneill** [codenameone/CodenameOne#2145]
In the gui builder if you set the thumb icon it does show up correctly but if you exit, after saving, and reopen, the icon is set but not visible.  The icon is not visible when running application either.

**Comment by shannah** [comment]
Is this in autolayout mode?  I have tried and can't seem to reproduce it (with autolayout mode).

**Comment by thomasmcneill** [comment]
No, not in auto layout.  It is a inside another container on a form.

**Comment by shannah** [comment]
I can't seem to reproduce this with or without autolayout mode.  Steps I took:

1. New form with flowlayout
2. Drag slider to the form.
3. Click "Icon" in the properties panel, and select an Icon  (tried both a material icon and one from the theme)
4.  Icon shows up in UI properly.
5. Saved form
6. Closed GUI Builder
7. Opened form again.  Thumb icon shows properly.

Here is the XML for the form:

~~~~
<?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="FlowLayout" flowLayoutFillRows="false" flowLayoutAlign="1" flowLayoutValign="0"  title="SignUpFormGB" uiid="SignUpForm" name="SignUpFormGB">
  <component type="Slider" focusable="true" editable="true" icon="fontImage:e60e" progress="40" name="Slider">
  </component>
</component>
~~~~

Please provide more details of how to reproduce the problem.

**Comment by thomasmcneill** [comment]
On a new project it is working fine.  Is there anything from my other
project I can get to you to help track it down?

**Comment by shannah** [comment]
Yes.  If you can post the .gui xml code that might help.

**Comment by thomasmcneill** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="BoxLayout" boxLayoutAxis="Y"
 title="EditInterval" name="EditInterval">
  <component type="TextField" hint="Interval Name" rTL="false" rows="1"
name="Interval_Name">
  </component>
  <component type="ComboBox" name="Combo_Box_IntervalType"
actionEvent="true">
  </component>
  <component type="Container" layout="BoxLayout" boxLayoutAxis="Y"
 name="Container_Effort">
    <component type="Label" text="Effort Portion" name="Label">
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="X"
 scrollableX="true" scrollableY="false" name="HoursContainer">
      <component type="Slider" editable="true" thumbImage="fontImage:e39e"
maxValue="6" textPosition="2" name="Slider_Interval_Effort_Hours"
dataChangeEvent="true">
      </component>
      <component type="Label" text="Label"
name="Label_Interval_Effort_Hours_Value">
      </component>
      <component type="Label" text="Hours"
name="Label_Intervals_Effort_Hours">
      </component>
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="X"
 name="MinutesContainer">
      <component type="Slider" editable="true" thumbImage="fontImage:e39e"
maxValue="120" textPosition="2" name="Slider_Interval_Effort_Minutes"
dataChangeEvent="true">
      </component>
      <component type="Label" text="Label"
name="Label_Interval_Effort_Minutes_Value">
      </component>
      <component type="Label" text="Minutes"
name="Label_Interval_Effort_Minutes">
      </component>
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="X"
 name="Container_Seconds">
      <component type="Slider" editable="true" thumbImage="fontImage:e019"
maxValue="120" name="Slider_Interval_Effort_Seconds" dataChangeEvent="true">
      </component>
      <component type="Label" text="Label"
name="Label_Interval_Effort_Seconds_Value">
      </component>
      <component type="Label" text="Seconds"
name="Label_Interval_Effort_Seconds">
      </component>
    </component>
  </component>
</component>



public class EditInterval extends com.codename1.ui.Form {

    public EditInterval() {
        this(com.codename1.ui.util.Resources.getGlobalResources());
    }

    public EditInterval(com.codename1.ui.util.Resources
resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }

//-- DON'T EDIT BELOW THIS LINE!!!
    private com.codename1.ui.TextField gui_Interval_Name = new
com.codename1.ui.TextField();
    private com.codename1.ui.ComboBox gui_Combo_Box_IntervalType = new
com.codename1.ui.ComboBox();
    private com.codename1.ui.Container gui_Container_Effort = new
com.codename1.ui.Container(new
com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Label gui_Label = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_HoursContainer = new
com.codename1.ui.Container(new
com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Slider gui_Slider_Interval_Effort_Hours = new
com.codename1.ui.Slider();
    private com.codename1.ui.Label gui_Label_Interval_Effort_Hours_Value =
new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_Intervals_Effort_Hours = new
com.codename1.ui.Label();
    private com.codename1.ui.Container gui_MinutesContainer = new
com.codename1.ui.Container(new
com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Slider gui_Slider_Interval_Effort_Minutes =
new com.codename1.ui.Slider();
    private com.codename1.ui.Label gui_Label_Interval_Effort_Minutes_Value
= new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_Interval_Effort_Minutes = new
com.codename1.ui.Label();
    private com.codename1.ui.Container gui_Container_Seconds = new
com.codename1.ui.Container(new
com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Slider gui_Slider_Interval_Effort_Seconds =
new com.codename1.ui.Slider();
    private com.codename1.ui.Label gui_Label_Interval_Effort_Seconds_Value
= new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_Interval_Effort_Seconds = new
com.codename1.ui.Label();


// <editor-fold defaultstate="collapsed" desc="Generated Code">

    private void guiBuilderBindComponentListeners() {
        EventCallbackClass callback = new EventCallbackClass();
        gui_Combo_Box_IntervalType.addActionListener(callback);
        gui_Slider_Interval_Effort_Hours.addDataChangedListener(new
EventCallbackClass(gui_Slider_Interval_Effort_Hours));
        gui_Slider_Interval_Effort_Minutes.addDataChangedListener(new
EventCallbackClass(gui_Slider_Interval_Effort_Minutes));
        gui_Slider_Interval_Effort_Seconds.addDataChangedListener(new
EventCallbackClass(gui_Slider_Interval_Effort_Seconds));
    }

    class EventCallbackClass implements
com.codename1.ui.events.ActionListener,
com.codename1.ui.events.DataChangedListener {
        private com.codename1.ui.Component cmp;
        public EventCallbackClass(com.codename1.ui.Component cmp) {
            this.cmp = cmp;
        }

        public EventCallbackClass() {
        }

        public void actionPerformed(com.codename1.ui.events.ActionEvent ev)
{
            com.codename1.ui.Component sourceComponent = ev.getComponent();

            if(sourceComponent.getParent().getLeadParent() != null &&
(sourceComponent.getParent().getLeadParent() instanceof
com.codename1.components.MultiButton ||
sourceComponent.getParent().getLeadParent() instanceof
com.codename1.components.SpanButton)) {
                sourceComponent =
sourceComponent.getParent().getLeadParent();
            }

            if(sourceComponent == gui_Combo_Box_IntervalType) {
                onCombo_Box_IntervalTypeActionEvent(ev);
            }
        }

        public void dataChanged(int type, int index) {
            onSlider_Interval_Effort_HoursDataChangeEvent(cmp, type, index);
            onSlider_Interval_Effort_MinutesDataChangeEvent(cmp, type,
index);
            onSlider_Interval_Effort_SecondsDataChangeEvent(cmp, type,
index);
        }
    }
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources
resourceObjectInstance) {
        guiBuilderBindComponentListeners();
        setLayout(new
com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
        setTitle("EditInterval");
        setName("EditInterval");
        addComponent(gui_Interval_Name);
        addComponent(gui_Combo_Box_IntervalType);
        addComponent(gui_Container_Effort);
        gui_Container_Effort.setName("Container_Effort");
        gui_Container_Effort.addComponent(gui_Label);
        gui_Container_Effort.addComponent(gui_HoursContainer);
        gui_HoursContainer.setScrollableX(true);
        gui_HoursContainer.setScrollableY(false);
        gui_HoursContainer.setName("HoursContainer");
        gui_HoursContainer.addComponent(gui_Slider_Interval_Effort_Hours);

gui_HoursContainer.addComponent(gui_Label_Interval_Effort_Hours_Value);
        gui_HoursContainer.addComponent(gui_Label_Intervals_Effort_Hours);
        gui_Slider_Interval_Effort_Hours.setEditable(true);

gui_Slider_Interval_Effort_Hours.setName("Slider_Interval_Effort_Hours");

gui_Slider_Interval_Effort_Hours.setTextPosition(com.codename1.ui.Component.BOTTOM);
        gui_Label_Interval_Effort_Hours_Value.setText("Label");

gui_Label_Interval_Effort_Hours_Value.setName("Label_Interval_Effort_Hours_Value");
        gui_Label_Intervals_Effort_Hours.setText("Hours");

gui_Label_Intervals_Effort_Hours.setName("Label_Intervals_Effort_Hours");
        gui_Container_Effort.addComponent(gui_MinutesContainer);
        gui_MinutesContainer.setName("MinutesContainer");

gui_MinutesContainer.addComponent(gui_Slider_Interval_Effort_Minutes);

gui_MinutesContainer.addComponent(gui_Label_Interval_Effort_Minutes_Value);

gui_MinutesContainer.addComponent(gui_Label_Interval_Effort_Minutes);
        gui_Slider_Interval_Effort_Minutes.setEditable(true);

gui_Slider_Interval_Effort_Minutes.setName("Slider_Interval_Effort_Minutes");

gui_Slider_Interval_Effort_Minutes.setTextPosition(com.codename1.ui.Component.BOTTOM);
        gui_Label_Interval_Effort_Minutes_Value.setText("Label");

gui_Label_Interval_Effort_Minutes_Value.setName("Label_Interval_Effort_Minutes_Value");
        gui_Label_Interval_Effort_Minutes.setText("Minutes");

gui_Label_Interval_Effort_Minutes.setName("Label_Interval_Effort_Minutes");
        gui_Container_Effort.addComponent(gui_Container_Seconds);
        gui_Container_Seconds.setName("Container_Seconds");

gui_Container_Seconds.addComponent(gui_Slider_Interval_Effort_Seconds);

gui_Container_Seconds.addComponent(gui_Label_Interval_Effort_Seconds_Value);

gui_Container_Seconds.addComponent(gui_Label_Interval_Effort_Seconds);
        gui_Slider_Interval_Effort_Seconds.setEditable(true);

gui_Slider_Interval_Effort_Seconds.setName("Slider_Interval_Effort_Seconds");
        gui_Label_Interval_Effort_Seconds_Value.setText("Label");

gui_Label_Interval_Effort_Seconds_Value.setName("Label_Interval_Effort_Seconds_Value");
        gui_Label_Interval_Effort_Seconds.setText("Seconds");

gui_Label_Interval_Effort_Seconds.setName("Label_Interval_Effort_Seconds");
        gui_Label.setText("Effort Portion");
        gui_Label.setName("Label");
        gui_HoursContainer.setScrollableX(true);
        gui_HoursContainer.setScrollableY(false);
        gui_HoursContainer.setName("HoursContainer");
        gui_MinutesContainer.setName("MinutesContainer");
        gui_Container_Seconds.setName("Container_Seconds");
        gui_Interval_Name.setHint("Interval Name");
        gui_Interval_Name.setName("Interval_Name");
        gui_Interval_Name.setRows(1);
        gui_Combo_Box_IntervalType.setName("Combo_Box_IntervalType");
        gui_Container_Effort.setName("Container_Effort");
    }// </editor-fold>



And attached is a screen shot.  On the left at the bottom you can see a
thumb set but on the slider itself there is no thumb.

**Comment by shannah** [comment]
I can't seem to reproduce this issue.  Likely the old project needs an update of the project libs.

**Comment by thomasmcneill** [comment]
Actually it was a new project.  I just started using the software.  I was
really just playing around with it to see how well it the gui builder
worked compared to others.

**Comment by shannah** [comment]
You often have to update project libs on new projects also.  
Project Properties > then click "Update Project Libs" button.
