### ISSUE TITLE
IOS builds switch from success to failure

### ISSUE THREAD

**Issue by xHatti** [codenameone/CodenameOne#2146]
If my IOS builds are successfull, they switch from the successfull status into failed status. This ia happening after about 2 minutes after the build is finished successfully.
All links are working fine and the app is working too.
The error log after the build switches to failed is very short. The only content is following line:

`Exception on appending to log: java.io.IOException: Bad file descriptorFailed xcodebuild step`

This issue has been filed as requested in the [forum thread](https://groups.google.com/forum/embed/?place=forum%2Fcodenameone-discussions&showsearch=true&showpopout=true&hl=en&parenturl=https%3A%2F%2Fwww.codenameone.com%2Fdiscussion-forum.html#!topic/codenameone-discussions/hcD7JE1Z3ac) talking about this issue

**Comment by codenameone** [comment]
This should have a workaround now
