### ISSUE TITLE
Side menu drawer icon disappearance issue

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#2149]
I have applied animateLayout in previous screen which is making side menu icon disappear in other screens. If I remove the animate code in splash screen, the problem is not there. If this problem occurred, the side menu opens with the whole mobile device screen.

PS. I've defined the theme constants for: sideMenuSizeTabPortraitInt, sideMenuSizePortraitInt, sideMenuSizeTabLandscapeInt & sideMenuSizeLandscapeInt.

 f.getToolbar().animateHierarchy(0); If this line is added in every form, then it works but all the components of the form blinks for a second.

Have a look at the issue in youtube [here](https://youtu.be/DVBhGrB2LEA).
Here is the full [project](https://drive.google.com/file/d/0B8ATnICIY2S8NHh5UDVzbWRtdjA/view?usp=sharing)

Code:

      public void start() {
        if (current != null) {
            current.show();
            return;
        }
        showSplashForm1();
     }

    private void showSplashForm1() {
        Display.getInstance().lockOrientation(true);
        int screenWidth = Display.getInstance().getDisplayWidth();

        Form splashForm = new Form(new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER));
        splashForm.setUIID("LoginMain");

        splashForm.getToolbar().setUIID("Container");

        Container parentContainer = new Container(BoxLayout.y());
        splashForm.add(BorderLayout.CENTER, parentContainer);

        Label logoLabel = new Label("LOGO");
        parentContainer.add(logoLabel);

        Label carLabel = new Label("abc");
        Container carContainer = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        carContainer.add(carLabel);

        Container animateContainer = BoxLayout.encloseY(carContainer);
        splashForm.add(BorderLayout.SOUTH, animateContainer);

        splashForm.show();
        splashForm.revalidate();
        
        //car animation starts
        carLabel.setX(-screenWidth);
        carLabel.setVisible(true);

        carContainer.animateLayout(4200);
        //car animation ends

        splashForm.setTransitionOutAnimator(CommonTransitions.createFastSlide(CommonTransitions.SLIDE_VERTICAL, true, 500));
        new UITimer(new Runnable() {
            public void run() {
                carLabel.setHidden(true);
                new Home(theme).show();
            }
        }).schedule(4000, false, splashForm);
    }

SideMenu class:

    public class SideMenu {

    Style style = null;

    public SideMenu(Form f, Resources res) {
        style = UIManager.getInstance().getComponentStyle("small");

        FontImage homeIcon = FontImage.createMaterial(FontImage.MATERIAL_HOME, style, 3);
        Command home = new Command("  Home", homeIcon) {

            @Override
            public void actionPerformed(ActionEvent evt) {
                new Home(res).show();
            }
        };
        f.addCommand(home);

        FontImage bookingIcon = FontImage.createMaterial(FontImage.MATERIAL_FILTER_NONE, style, 3);
        Command booking = new Command("  Book", bookingIcon) {

            @Override
            public void actionPerformed(ActionEvent evt) {
                new Home(res).show();
            }
        };
        f.addCommand(booking);

       //        f.getToolbar().animateHierarchy(0);
      //        f.getToolbar().invalidate();
        }
      }

Home class

    public final class Home extends Form {

    public Home(Resources res) {
        super(new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER));
        getToolbar().setTitle("Home");
        
        SideMenu sm = new SideMenu(this, res);

        loadComponents(res);
        revalidate();
    }

    public void loadComponents(Resources res) {

        Label vehicleNameLabel = new Label("lOGO");
        Label vehicleSlogan = new Label("Designed to excel".toUpperCase());
        Label upcomingServiceDateLabel = new Label("4/28/2017");
        Label lastServiceDateLabel = new Label("4/28/2017");

        Label homeCarLabel = new Label("MAIN IMAGE");

        Container vehicleInfoContainer = BoxLayout.encloseY(vehicleNameLabel, vehicleSlogan, upcomingServiceDateLabel, lastServiceDateLabel,
                homeCarLabel);

        add(BorderLayout.CENTER, vehicleInfoContainer);
    }
}

**Comment by codenameone** [comment]
Discussion https://stackoverflow.com/questions/44692100/side-menu-drawer-icon-disappearance-issue-codenameone/44713700

**Comment by codenameone** [comment]
This will be resolved by the migration to the on-top side menu next week
