### ISSUE TITLE
Wrong behavior with autoSizeMode

### ISSUE THREAD

**Issue by JrmyDev** [codenameone/CodenameOne#2152]
Platform : All
Codenameone version library : 168

**FIRST ISSUE : behavior when rotating screen**
I've problem with autoSizeMode enabled for some labels while rotating screen.

It appears only when I ****first** start the app in portrait** and rotate to landscape (no problem with landscape first then portrait).

Portrait, "06/07/2017" is fully visible :
![image](https://user-images.githubusercontent.com/10810617/27946480-53811b5e-62f2-11e7-8459-b677db23a822.png)

Then, after rotation, "06/07/2017" not fully visible :
![image](https://user-images.githubusercontent.com/10810617/27946490-6054b3a4-62f2-11e7-99cf-16aaca31ef3c.png)

**SECOND ISSUE : doesn't work with checkbox**
It seems that autoSizeMode doesn't work for checkbox (with text). I've tried to call `initAutoResize()` method in `paint()` method of Checkbox class : it works partially. Should refresh autoSize on action event.

You can reproduce similar issues with : 
[TestProject.zip](https://github.com/codenameone/CodenameOne/files/1130353/TestProject.zip)

**Comment by codenameone** [comment]
This happens with the standard demo for the feature and is visible in device rotation:

````java
Form hi = new Form("AutoSize", BoxLayout.y());

Label a = new Label("Short Text");
a.setAutoSizeMode(true);
Label b = new Label("Much Longer Text than the previous line...");
b.setAutoSizeMode(true);
Label c = new Label("MUCH MUCH MUCH Much Longer Text than the previous line by a pretty big margin...");
c.setAutoSizeMode(true);

Label a1 = new Button("Short Text");
a1.setAutoSizeMode(true);
Label b1 = new Button("Much Longer Text than the previous line...");
b1.setAutoSizeMode(true);
Label c1 = new Button("MUCH MUCH MUCH Much Longer Text than the previous line by a pretty big margin...");
c1.setAutoSizeMode(true);
hi.addAll(a, b, c, a1, b1, c1);

hi.show();
````

**Comment by JrmyDev** [comment]
Why should we wait for 3.8 ?

**Comment by codenameone** [comment]
3.8 is the closest release there is. 3.7 is already finished.

**Comment by JrmyDev** [comment]
Sure but I thought that this kind of fix could be part of a friday release ... I misunderstood something

**Comment by codenameone** [comment]
Everything goes into Friday releases. 
This means we are aiming for this to be fixed by the closest deadline at the latest. The two alternatives is unscheduled which means we have no idea when we'll get to it or a further schedule.

**Comment by JrmyDev** [comment]
Ok I see ^^ Thanks for clarification..
