### ISSUE TITLE
Video playback inconsistent between Android & iOS

### ISSUE THREAD

**Issue by amiga** [codenameone/CodenameOne#2156]
Lets say I add a mediaplayer to the centre of a borderlayout and tunr the phone landscape, it appears that the video is stretched on android, to fill the whole borderlayout, but on iOS the video does not stretch. Is there a way to stop it filling the full space in android?

**Comment by codenameone** [comment]
Behavior of the video playback in the media component should be consistent and documented between the various platforms.

**Comment by shannah** [comment]
Behaviour between iOS and Android is now be consistent with respect to Media and MediaPlayer.
