### ISSUE TITLE
Lineborder not working correctly at device density 50 and 70

### ISSUE THREAD

**Issue by xHatti** [codenameone/CodenameOne#2157]
I have a strange issue with line borders at screen density 50 and 70. At density 50, the left line of the border is missing, on screen density 70, the upper border line is missing too. If i increase the line thickness to 2, its clearly seeable, that one pixel thickness is missing on both border lines.

Following screenshots will show with border line thickness set to 1

[Screenshot from a Samsung S7 Edge](https://drive.google.com/file/d/0BySgEy87y_PdRXpqNFZjT1BCN1k/view?usp=sharing)

[Screenshot from a Google Pixel tablet](https://drive.google.com/file/d/0BySgEy87y_PdZllZNVlQaWo5Wms/view?usp=sharing)

This is the whole code of the app:
```
Form form = new Form(new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
Label cmp = new Label("Density: " + Display.getInstance().getDeviceDensity());
Style style = cmp.getStyle();
style.setBorder(Border.createLineBorder(1, 0x000000));
form.add(BorderLayout.CENTER, cmp);
form.show();
```

There is no special theming or anything else. I used the "Getting started app" as a base.
This issue happens to ALL components with borders, not only labels

**Comment by shannah** [comment]
Still don't have a way to reproduce this.
