### ISSUE TITLE
TextArea setEndsWith3Points doesn't work

### ISSUE THREAD

**Issue by mickeyng** [codenameone/CodenameOne#2158]
This is seen on Simulator and iOS builds
Setting a long text in TextArea and set setEndsWith3Points to true doesn't end the text with "..."

TextArea ta = new TextArea();
ta.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis interdum iaculis. Sed sodales neque tellus, ac pellentesque urna sodales vitae. Donec facilisis, est vitae tempus lobortis,");
ta.setPreferredW(200);
ta.setPreferredH(40);
ta.setSingleLineTextArea(true);
ta.setEndsWith3Points(true);

If I change the class to Label then the text properly ends with "..."

**Comment by codenameone** [comment]
I don't think that will work for a single line text area and it's probably not intended for that use case.

**Comment by mickeyng** [comment]
I removed the setSingleLineTextArea line, and it still has the same effect; no "..." for TextArea, but works if it's a Label

Is there a use case where TextArea will end in "..."?

**Comment by codenameone** [comment]
I was actually unaware of this until you pointed it out. It was added by @chen-fishbein in 2014 and I'm not sure if it was ever used.

**Comment by mickeyng** [comment]
For my use case I'm making it single line and truncating, so I can replace it with a Label. Maybe add a javadoc for TextArea when users run into this in the future?

**Comment by codenameone** [comment]
I'll just deprecate it unless @chen-fishbein has a better idea

**Comment by chen-fishbein** [comment]
This is used when there is a grow limit on a TextArea. 
For example: a TextArea with potentially 10 rows can be displayed in 4 rows where the last row can be truncated or ends with 3 points.

**Comment by codenameone** [comment]
Thanks, I clarified the JavaDocs
