### ISSUE TITLE
CodenameOne:Unfortunately,Application has stopped

### ISSUE THREAD

**Issue by Shekhar-jadhav** [codenameone/CodenameOne#2161]
I have created a form(Registration form) in codename one.when ever i clicked on next button and goes to Registration form on clicking anywhere on Registration form application get closed and shows error "Unfortunately,application has stopped". Sometimes its working ,I can able to open Registration form but some times it gets crashed.                                                                                                                                         I have Connected my device with a cable and looked at the logcat/DDMS output. I got below error               "java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.android.InPlaceEditView$EditView.switchTo‌​TextArea(com.codenam‌​e1.ui.TextArea)".                                                                                                                                            so can anyone help me to solve this problem ???

**Comment by codenameone** [comment]
We need a stack trace from DDMS/Logcat for this issue. Without a stack trace I will close it.
