### ISSUE TITLE
disturbed view after resuming app on iOS

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2162]
This is happening when I use multiple `BrowserComponent`s (or even `MapContainer`) in a `Tabs` component (a single `BrowserComponent` per tab). I just need to hide the app and then resume (test on iOS). The result is as follows:
![img_0002](https://user-images.githubusercontent.com/5825645/28108319-57142480-66eb-11e7-8dc4-61ab40d900bf.PNG)

this is the test case:

        Tabs tabs = new Tabs();
        tabs.setSwipeActivated(false);
        tabs.setAnimateTabSelection(false);
        
        BrowserComponent bc1 = new BrowserComponent();
        BrowserComponent bc2 = new BrowserComponent();
        
        bc1.setPage("</head><body><p>Lorem Ipsum 1</p></body></html>", "url1");
        bc2.setPage("</head><body><p>This is the other text</p></body></html>", "url2");
        
        tabs.addTab("t1", bc1);
        tabs.addTab("t2", bc2);
        
        f.addComponent(BorderLayout.CENTER, tabs);

**Comment by kutoman** [comment]
is there a way get this fix integrated before the 3.8 update? I need it urgently for a soon app release

**Comment by shannah** [comment]
It will be available in the next server update (this Friday, I think).

**Comment by kutoman** [comment]
ok I see, thanks
