### ISSUE TITLE
Array instanceof inconsistent in ParparVM with Java Spec

### ISSUE THREAD

**Issue by xHatti** [codenameone/CodenameOne#2163]
I have a very simple example, which just splits a string and outputs into a lable, if the result is empty or not. The expected result is "true" which will be shown on the devices ( IOS and Android ).
BUT... after a short time (1 second maybe), the screen refreshed on IOS and 1. changes the theme AND doing something i do not know, which switches the result from true to false.

I made a video which will show the effect. There is no refreshing code or something else in there. Its a super simple example app to show this error:
After i open the app in the video, the shown text will change from "true" to "false" after short duration and the text style gets changed without any interaction or code that does it.

[Link to the IOS video](https://drive.google.com/file/d/0BySgEy87y_PdWkdlZVlGY3ZIbXc/view?usp=sharing)

This is the whole programm code. I´ve tested it on a IPhone 4s (IOS 9), IPad2 (IOS 10), Samsung S3, Google Nexus 2013 Tablet. Android is working fine, on both Apple devices i have the same behaviour

```
	public void start()
	{
		Form form = new Form(new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
		Label cmp = new Label("");
		form.add(BorderLayout.CENTER, cmp);
		String s = "|";
		String[] stringSplit = stringSplit(s, "|");
		cmp.setText("Split: " + stringSplit.length + " is Empty: " + isEmpty(stringSplit));
		form.show();
	}

	public static String[] stringSplit(String subject, String delimiters)
	{
		StringTokenizer strTkn = new StringTokenizer(subject, delimiters);
		ArrayList<String> arrLis = new ArrayList<String>(subject.length());

		while (strTkn.hasMoreTokens())
			arrLis.add(strTkn.nextToken());

		return arrLis.toArray(new String[arrLis.size()]);
	}

	public static boolean isEmpty(Object o)
	{
		if (o == null)
			return true;
		else if (o instanceof Object[])
			return ((Object[]) o).length == 0;
		return false;
	}
```

You may change the title to a more speaking one, cause i dont know how to title THIS exotic bug:)

**Comment by codenameone** [comment]
See the screenshot process https://www.codenameone.com/manual/appendix-ios.html
The question is why that's acting differently on device vs. simulator and for that I need to know the inputs

**Comment by xHatti** [comment]
The screenshot process would explain the refresh of the screen after short duration but not the wrong code execution. This is a made up example from my big app where i have this error in normal programm execution which leads to a array out of bounds cause my isEmpty check returns a false return.

what do you mean exacly with "inputs"? the fastbuild parameter is not set, i dont have any screenshots for the ios spash screen and as you can see in the vid, i havn´t done any finger inputs on the pad after launching the app.

**Comment by codenameone** [comment]
I didn't notice the `s` variable. Yes I'm familiar with that issue I thought it was fixed. It's due to an optimization in tokenization logic which can be slower on iOS

**Comment by xHatti** [comment]
This bug does not come from the Stringtokenizer. IOS handles the String[] in the code differently as on other platforms.

I simplified the code a bit:

```
Form form = new Form(new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
Label cmp = new Label("");
form.add(BorderLayout.CENTER, cmp);
String[] stringSplit = new String[0];
boolean instanceObjArr = (stringSplit instanceof Object[]);
boolean instanceStrArr = (stringSplit instanceof String[]);
cmp.setText(" instanceOf Object[] " + instanceObjArr + " : instanceof String[] " + instanceStrArr);
form.show();
```


No Stringtokenizer no anything. On IOS the `String[] instanceof Object[]` returns false although it should be true
