### ISSUE TITLE
iOS10: NSLog and printf don't write to device log

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#2166]
https://stackoverflow.com/questions/37886600/ios-10-doesnt-print-nslogs

Summary.  With iOS 10, apple switched to [unified logging](https://developer.apple.com/documentation/os/logging), and no longer writes to disk.  NSLog can be compelled to write to the device log, but this appears to be an Xcode 8 feature.

Best solution right now is probably to change to os_log - but we would need to do this without any compile-time dependencies on it.

One possible solution:

http://blog.safedk.com/technology/nslog-os_log-multiple-ios-versions/

**Comment by codenameone** [comment]
Why won't a build hint that replaced the value in the CNLog macro work as a workaround for this?

**Comment by shannah** [comment]
NSLog no longer works in iOS 10

**Comment by codenameone** [comment]
Even for code compiled with xcode 7.x?

**Comment by shannah** [comment]
As far as I can tell, even if compiled with xcode 7.x.  Xcode 8.x provides some workarounds, but it doesn't look like 7 does.

**Comment by codenameone** [comment]
So let's assign this to the xcode 8.x migration which we need to do anyway.
8.x will break a few things e.g. push so I'd like to schedule it post 3.8 which is in November. Does that make sense?

**Comment by shannah** [comment]
It looks like the only way to force logging to go to an actual file is to roll your own, which we already do with our Logging.  There is lots of documentation out there on how to extract information from Apple's new unified logging - even if it is hard to understand.  Originally this was an extra important issue because Appium wasn't able to get the output of NSLog either, and that was necessary fo CI to work.  But that is fixed now with https://github.com/shannah/cn1-appium-ios/commit/efa3173182870c6429b0acdce1756613b3c5ada1, so this issue has become less important.

If you debug your app in Xcode, you can see the app's output to the output window.  In addition, Using com.codename1.io.Log.sendLog() will work without requiring a mac.

Other use-cases developers can try to use Apple's `log` command to extract logs from the app.

Apple's docs:  https://developer.apple.com/documentation/os/logging

Anyways, I'm concluding that its best just to do nothing here.
