### ISSUE TITLE
Test Unit - Overriting  shouldExecuteOnEDT doesn't work.

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#2167]
I wrote a little unit test for my project.

I wrote this method in my Unit Test Class:

   @Override
    public boolean shouldExecuteOnEDT() {
        return false;
    }

When I run my tests doesn't matter whether my shouldExecuteOnEDT() method returns true or false.
The Test Unit is always running using EDT thread,
As you can see in the following output:

[main] 0:0:0,36 - Starting test case tests.StoCRUDTest
[main] 0:0:0,36 - Test prepared for execution on EDT
[main] 0:0:0,172 - Create action succesful.

[main] 0:0:0,199 - Read action successful.
[main] 0:0:0,199 - Update action successful.
[main] 0:0:0,234 - Delete action successful.

[main] 0:0:0,234 - tests.StoCRUDTest passed
All tests passed. Total 1 tests passed

You can see the same thing in Screen shot image captured during test execution:

![screen_unittextcodenameone](https://user-images.githubusercontent.com/6536369/28538877-29e50a66-7086-11e7-8a82-72e242f975b6.png)

**Comment by codenameone** [comment]
It's just bad printout, fixing it for next update.
