### ISSUE TITLE
ArrayDeque add fails with ArrayIndexOutOfBoundsException on ios devices

### ISSUE THREAD

**Issue by acionescu** [codenameone/CodenameOne#2169]
Hi, due to the fact that an ArrayDeque object is initialized with a length of -1, as per these [lines of code](https://github.com/codenameone/CodenameOne/blob/master/vm/JavaAPI/src/java/util/ArrayDeque.java#L201-L203),
an ArrayIndexOutOfBoundsException is thrown each time the add method is called on the ArrayDeque.

I have manged to fix this in my code by replacing the countInitSize with this: 

```
private int countInitSize(final int minSize) {
        return (minSize > 0)?minSize:DEFAULT_SIZE;
}
```
It's quite amaizing that an error is not being thrown earlier when trying to initialize and Object array with length -1, but nonetheless, this is what happens.

I have lost 2 days tracking this issue, and the fact that I wasn't able to access the stacktrace with a 
Basic Subscription was really frustrating. 

Anyway, I hope you'll find this issue usefull.

**Comment by codenameone** [comment]
Thanks!
