### ISSUE TITLE
Erase/Clear function required in Graphics

### ISSUE THREAD

**Issue by gurankas** [codenameone/CodenameOne#2170]
Recently, I was making a drawing app in CN1 and modified the SignatureComponent class definition to display the canvas full screen. The limitation is when I **cannot erase the path like I can draw**. A short term solution might be to set the stroke colour to the colour of the background; but in the case that the background is an image, this approach might fail miserably.

While manipulating the RGB values in the image to give a clear/erase effect might be a work-around to this problem, it will definitely give a performance degrade. So I request authors of CodeName One to **add an API or method which can replicate the [PorterDuff Mode](https://developer.android.com/reference/android/graphics/PorterDuff.Mode.html) functionality in Android or a simple erase/clear function**

For details and code of my problem, click [here](https://stackoverflow.com/questions/45319864/how-to-draw-a-transparent-stroke-to-reveal-the-background-in-codename-one/45341886#45341886)

**Comment by codenameone** [comment]
Implementing porter duff in a performant cross platform way is impractical. But we should probably expose what we already have which is a relatively brute force `clearRect` API that allows you to delete a square of pixels.

**Comment by codenameone** [comment]
@shannah I'm assuming this is trivial hence the 3.8 assignment, if it's anything other than trivial please move to 3.9 as 3.8 is pretty full

**Comment by gurankas** [comment]
@shannah @codenameone Please consider me at your disposal for this feature. I may be newbie to CN1 but I'm an enthusiast and willing to contribute by putting the effort :+1:

**Comment by shannah** [comment]
Moved to 3.9.  We only have this implemented on iOS Javascript, and UWP right now. It was implemented as part of the Z-Ordering of Peer components, and other platforms didn't require this.

Can probably use [Graphics clearRect](https://docs.oracle.com/javase/7/docs/api/java/awt/Graphics.html#clearRect(int,%20int,%20int,%20int) in simulator, but the docs say that is simply works by filling a rectangle with the background color, and on images this color is system dependent - so it may not actually "clear" the space - and thus cross-platform consistency may not ba achievable.

Will require some experimentation.

**Comment by ramsestom** [comment]
Just wanted to pointed out that BlendModes and ColorTransforms are implemented into OpenFL (http://api.openfl.org/openfl/display/BlendMode.html and http://api.openfl.org/openfl/geom/ColorTransform.html), another Cross Platform (desktop, ios, android, html...) Framework that I am using. This is opensource (and coded in haxe, not java, but the two languages are quite close so it should be easy to understand for a java developper) so it may be worth to take a look at how this was implemented  and try to port it to CN1
