### ISSUE TITLE
Codename one GoogleConnect setScope is not effective

### ISSUE THREAD

**Issue by Jensan3580** [codenameone/CodenameOne#2172]
I am using the new GoogleConnect thing and set the scope like

```
Login gc = GoogleConnect.getInstance();    
gc.setScope("https://www.googleapis.com/auth/plus.profile.emails.read https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.file");
...
gc.doLogin();
```
However, when the access token is generated and checked in https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=(accesstoken) , it shows

`"scope": "https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.profile"`
Is it related to any recent updates or new build hint? I am totally lost here. It is an Android build. Thanks.

To clarify, I am NOT trying to set the scope after the access token is generated.

Related StackOverflow ticket:
https://stackoverflow.com/questions/45351320/codename-one-googleconnect-setscope-is-not-effective?noredirect=1#comment77690195_45351320

**Comment by jmoranrod** [comment]
Hello, How I can workaround this issue? All the Google Accounts in my project has been invalidated because the response not contain the email field

**Comment by codenameone** [comment]
I'll try to push this fix over this weekend

**Comment by codenameone** [comment]
I deployed the fix and it should work for new builds
