### ISSUE TITLE
[ParparVM] String literals are included as comments in the code

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2174]
This means that if the string literal contains /* ... */ then the build will fail as it generates invalid C code.

**Comment by codenameone** [comment]
Do you mean a literal like:

````java
String myString = "/* this";
````

Do you have a sample of the generated C code?

**Comment by DigNZ** [comment]
`private static final String testing = "/**/";`

Produces this error:
`/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build502446659560790458xxx/dist/BluekeyInspect-src/com_bluekey_app_forms_PhotoDisplay.m:37:52: warning: '/*' within block comment [-Wcomment]
    return STRING_FROM_CONSTANT_POOL_OFFSET(11) /* /**/ */;
                                                   ^
/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build502446659560790458xxx/dist/BluekeyInspect-src/com_bluekey_app_forms_PhotoDisplay.m:37:58: error: expected expression
    return STRING_FROM_CONSTANT_POOL_OFFSET(11) /* /**/ */;
                                                         ^
/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build502446659560790458xxx/dist/BluekeyInspect-src/com_bluekey_app_forms_PhotoDisplay.m:37:59: error: expected expression
    return STRING_FROM_CONSTANT_POOL_OFFSET(11) /* /**/ */;`

No code available because code isn't available for failed builds due to this poor decision: https://github.com/codenameone/CodenameOne/issues/1500
