### ISSUE TITLE
Entire touch Screen freezes (Nothing responds) after specific cycles of activities.

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#2177]
We are facing a  weird problem that causes stress with some of our customers.
The entire device's touch screen freezes after a specific cycle of activities.
 
I wrote 1 little Netbeans project where this problem is reproduced. This project has a small number of lines of code. Its entire code is in one file called MyApplication.java.

I published this project in my GitHub and the link for it is below:
[ProjectFreezeScreen1](https://github.com/hrugani/ProjectFreezeScreen1.git)

To reproduce, first of all, **you need run the App ProjectFreezeScreen1 on a real device**. 
(On Simulator the problem doesn't happen). After app loaded, the FORM1 will be shown. This form has only one big button in the center.
 
Now,  the cycle of activities that reproduce  the problem:

1) Touch the button in the center of Form1
2) then, Form2 will be shown. It has only one WebBrowser component in the center and it is set to show the Web Site of Codename One.
3) then, do some navigation on the site (scrolling).
4) Finally, touch in back command to return for Form1 

Please, repeat this cycle several times(steps 1 till 4).
The number of times you need to do this cycle till app freezes its screen (i.e. The button in form1 stops to respond) is random. Could occur in the first cycle as in 20th or 50th cycle.  But it always occurs.

In this project,  the frozen screen has only one simple button, but in our real case,  all components in the screen become untouchable.

**Comment by codenameone** [comment]
@shannah this looks like a creation/dispose race probably with invokeAndBlock and the browser component. Might be an edge case race condition. Does something come to mind?

````java
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        new Form1().show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    class Form1 extends Form {

        public Form1() {
            
            super();

            setTitle("Form 1");
            
            Button btn = new Button("Call Browser");
            btn.addActionListener((ActionListener) (ActionEvent evt) -> {
                
                final Form2 f2 = new Form2();
                Command backCommand = new Command("Back") {
                    @Override
                    public void actionPerformed(ActionEvent ev) {
                        Form1.this.showBack();
                    } 
                }; 
                f2.setBackCommand(backCommand);
                f2.show();        
                
            });
            
            setLayout(new BorderLayout());
            addComponent(BorderLayout.CENTER, btn);
            
        }
        
        
    }
    
    class Form2 extends Form {
        public Form2() {  
            super();
            setTitle("Form 2 - WebBrowser");
            WebBrowser browser =  new WebBrowser("http://codenameone.com");
            setLayout(new BorderLayout());
            addComponent(BorderLayout.CENTER, browser);
        }
    }
````

**Comment by shannah** [comment]
Issue mentions "real device" but doesn't specify which device.  Android or iOS?

**Comment by hrugani** [comment]
Hi Steve,

I will request the devices technical information from our customers.
I reproduced it in my tablet Sumsung Android 4.4 Galaxy Note 8. 
(This is a very old model, but the same problem also happens in current devices).
As soon as possible I will provide you those pieces of information.
(All devices use Android - Several versions)

**Comment by hrugani** [comment]
Adding more details:
Studying the problem, I imagined that the cause was related with WebBrowser deprecated Component.
But this hypothesis didn't verify itself.
I rewrote the same project only exchanging the component "WebBrowser" (that was deprecated) by the new one "BrowserComponent" and following the recommendations described into JavaDoc.
**The same problem happened**.

**Comment by codenameone** [comment]
`WebBrowser` is deprecated because it's not necessary. It should work just fine. @shannah any ideas?

**Comment by hrugani** [comment]
Adding more requested pieces of information about device models where the problem happens:
Motorola - Moto G - second generation,  Android 6.0, security patch level 1th-Ago-2016

**Comment by hrugani** [comment]
Sorry, At the moment, no ideas.

**Comment by codenameone** [comment]
I was asking @shannah for ideas but there is was a holiday in Canada yesterday so he'll probably answer tomorrow

**Comment by shannah** [comment]
I have been unable to reproduce this problem on my test device using the test code provided.  I don't have any of the devices listed.  I was testing on a Nexus 5 running Android 6.0.1.

That said, I have gone through the code and have added additional safe-guards against possible deadlocks that may occur in relation to the Browser Component.  These changes will be available in the next server update (Friday, I think).

**Comment by hrugani** [comment]
Hi, Steve.
I need your confirmation whether yours betterments are already in production.

Independently, we rebuilt our App and the little test-projects even without know whether your new code is really active.

we suppose that they are already in production
because the results are positives.
I believe your actions added more robustness to the code. So far the users' comments are very positives.
Due to the fact of the problem to happen randomly,
we need more tests, but the expectations are good.

I will keep you informed.

Thank you.

**Comment by shannah** [comment]
I think they are there.
