### ISSUE TITLE
Display.getInstance().execute(AudioFile.wav) Fails to open .wav, .mp3, .mp4 files with Android player

### ISSUE THREAD

**Issue by mab1423** [codenameone/CodenameOne#2183]
Android OS 7, Samsung S8+
I download a .wav file from my server and pass that to Display.getInstance().execute(File Here)

AndroidAudioDotWavWontPlay_2.jpg shows the full path file being passed to Display.getInstance().execute(AudioFile.wav)
![androidaudiodotwavwontplay_1](https://user-images.githubusercontent.com/24964162/29461084-658ab144-83f8-11e7-99e6-acb20cec29bb.jpg)
![androidaudiodotwavwontplay_2](https://user-images.githubusercontent.com/24964162/29461085-658aba22-83f8-11e7-8d84-321ecb5faad9.jpg)

AndroidAudioDotWavWontPlay_1.jpg shows the OS Complaint after Display.getInstance().execute(AudioFile.wav) is executed

Note the OS complains of invalid format, however this same file plays on my PC and IOS using the same method of download and play.

Just to prove out the integrity of the .wav file downloaded,
I processed the Audio File with this code and it plays perfectly

                    media = MediaManager.createMedia(AudioFile, false);
                    media.play();

**Comment by codenameone** [comment]
I just tested this and it worked fine:

````java
Form hi = new Form("Hi World", BoxLayout.y());
Button test = new Button("Test");
hi.addComponent(test);
test.addActionListener(e -> {
    String p = getAppHomePath() + "Cats.mp3";
    try {
        try(OutputStream os = openFileOutputStream(p)) {
            try(InputStream is = getResourceAsStream("/Cats.mp3")) {
                Util.copy(is, os);
            }
        } 

        execute(p);
    } catch(IOException err) {
        Log.e(err);
    }
});
hi.show();
````

**Comment by mab1423** [comment]
try(InputStream is = getResourceAsStream("/Cats.mp3"))

“is” Always returns null on Android and IOS

My version of your code below:

        Form hi = new Form("Hi World", BoxLayout.y());
        Button test = new Button("Test");
        hi.addComponent(test);
        test.addActionListener(e -> {
            String p = getAppHomePath() + "Cats.wav";
            try {
                try (OutputStream os = openFileOutputStream(p)) {
                    try (InputStream is = getResourceAsStream("/Cats.wav")) {
                        inc.showDialogMessage("Play Audio File", "AudioFileFullPath = [" + p + "] "
                                + "File Exists = " + inc.fileExists(p) + "\n"
                                + "\"/Cats.wav\" Exists = " + inc.fileExists("/Cats.wav") + "\n"
                                + "is = " + is, null);
                        Util.copy(is, os);
                    } catch (Exception err2) {
                        Log.e(err2);
                    }
                } catch (Exception err1) {
                    Log.e(err1);
                }
                execute(p);
            } catch (Exception er) {
                Log.e(er);
            }
        }
        );
        hi.show();

[cid:3f6f5748-c062-4940-b5ef-a74c0ef47e22@namprd11.prod.outlook.com]

Regards

[cid:image001.jpg@01D27C64.63ED8510]
Digital End to End, Shop Management Software Suite

Auto Shop Technologies, Corp.
Mark Bolduc: VP, Engineering & Product Development
138 Wells Village Road
Sandown, NH 03873-0091

Cell Number 603-327-8465
Email markb@autoshoptechnologies.com<mailto:markb@autoshoptechnologies.com>
Web: www.autoshoptechnologies.com<http://www.autoshoptechnologies.com>

**Comment by mab1423** [comment]
![codenameoneissuenum_2183](https://user-images.githubusercontent.com/24964162/29577014-e746d37e-8737-11e7-8209-f1cef2b0c6af.jpg)

**Comment by codenameone** [comment]
You need to place a Cats.mp3 (case sensitive) in the src directory for my sample to work. It needs to be a valid mp3 file

**Comment by mab1423** [comment]
Ok That Worked.

Why is it necessary to "Util.copy(is, os);" ?
In your example,the file exists in the src dir, why can't we execute it their?
Display.getInstance().execute(file)

Why can't we execute a valid .mp3 file that I have downloaded from my server,saved it on disk here:
FileSystemStorage.getInstance().getAppHomePath() + "A3-TECH/Audiorecordings/"

Using this method:
InputStream is = mySocket.getInputStream();
fos = FileSystemStorage.getInstance().openOutputStream(Directory + fileName);
loop through fos.write(data, 0, bytesRead);

Verify the File exists then pass the full path to Display.getInstance().execute(file)

**Comment by mab1423** [comment]
Turns Out that IOS will accept a file name with spaces in the name and Android does not.

So my only remaining question is regarding "Util.copy(is, os);" 

Is there any special permissions handling with using this?
Please advise the need to use this method why and when.

**Comment by mab1423** [comment]
Last comment,
I rely on FileSystemStorage.getInstance().exists(filename) to indicate if a file exists.
On Android getResourceAsStream() returns null if file not found so when testing the file exists method above indicated the file did exist was counterintuitive.
I would hope the have an IOException thrown with message "File Not Found"

Also Shouldn't FileSystemStorage.getInstance().exists(filename) report false if the filename has a space in its name as getResourceAsStream() can't handle this?

Regards.

**Comment by codenameone** [comment]
getResourceAsStream() != File System != Storage
I'm assuming you are confused with these 3 options and something worked for you in one platform due to overlap between the three so you incorrectly assumed a problem. I suggest looking at the overview here: https://www.codenameone.com/manual/files-storage-networking.html
