### ISSUE TITLE
Text font-size is incorrect on BrowserComponent inside the simulator?

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2199]
I attach two screenshot of the simulator, the java code and the html code: the text has a readable size using the iPhone3gs.skin, but it's very very small (quite unreadable) using other skins like SamsungS7.skin. I don't know why, I hope that the text will be correctly sized on real devices with a good-readable default font size. Is it a fixable issue of the simulator? Can somebody do a test with a real SamsungS7 device? 

![iphone3gsskin](https://user-images.githubusercontent.com/1997316/29978369-37f94372-8f41-11e7-80c2-f5ae236ee6fe.png)
![samsungs7skin](https://user-images.githubusercontent.com/1997316/29978370-38027fe6-8f41-11e7-9b35-ddd66711dd23.png)

Java code:
```
// Create the BrowserComponent
        BrowserComponent browser = new BrowserComponent();

        try {
            // Load a web page placed in the "html" package
            browser.setURLHierarchy("/index.html");
            Log.p("setURLHierarchy executed");
        } catch (IOException ex) {
            Log.e(ex);
        }

        hi.add(BorderLayout.CENTER, browser);
```

index.html:
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <a href="page1.html">Page 1</a><br />
        <a href="page2.html">Page 2</a><br />
        <a href="page3.html">Page 3</a><br />
    </body>
</html>
```

Please note that adding the following style doesn't change anything:
```
	<style type="text/css">
            body {font-size: 1.0em; }
        </style>
```

If I use "mm" in the CSS, like in the following one, the problem persists:
```
        <style type="text/css">
            body {font-size: 5.0mm; }
        </style>
```

**Comment by codenameone** [comment]
Codename One is a mobile Java framework not an HTML framework. If you write HTML you need to use responsive HTML code to adapt to DPI/resolution. We don't provide an HTML framework, there are plenty of those in the market. If you use one of those the text will adapt properly.
