### ISSUE TITLE
Entire touch Screen freezes after specific cycle of activities - New use case.

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#2203]
This issue is similar to issue #2177 but it is another issue.
The issue #2177 was closed after some improvements that Steve did.
The use case described in #2177 was solved and that is great. Thank you.

But after some tests, we figured out another use case where the same problem remains happening.
I wrote a new little project on Github where you can reproduce the new case. You can access this project using the following link: [ProjectFreezeScreen5](https://github.com/hrugani/ProjectFreezeScreen5.git)

To reproduce, first of all, you need run the App ProjectFreezeScreen5 on a real device.
(Typically all devices that have Android 6 - My device is Galaxy J7 Prime).
(On Simulator the problem doesn't happen).

After app loaded, the FORM1 will be shown. This form has only one big button in the center.

Now, the cycle of activities that reproduce the problem:
1. Touch the button in the center of Form1
2. then, Form2 will be shown. It has only one WebBrowser component in the center and it is set to show the "HTML String"  of the Codename One Site.
3. then, do some navigation on the site (scrolling).
4. Finally, touch in back command to return for Form1

Please, repeat this cycle several times(steps 1 till 4).
The number of times you need to do this cycle till app freezes its screen is random.
The button in form1 stops responding to touch events.
Could occur in the first cycle as in 20th or 50th cycle. But it always occurs.

The only difference of this new project to the project from question # 2177 is how WebBrowser component loads with the data to be displayed. In the previous project the webbrowser component itself is responsible for fetching data from an address on the internet.
(the constructor was used **new WebBrowser("http://codenameone.com")** and the second one (where the problem continues to occur) data is loaded into the component via the method **setPage(String html, String baseUrl)**

I suppose some improvements like those made for the previous case are needed.

**Comment by codenameone** [comment]
@shannah I've put it on 3.8 for evaluation while the original issue is still fresh in your memory. If the fix is complex we'll push it to 3.9

**Comment by JrmyDev** [comment]
I've same king of problem appear in my customer tablet (iPad Air 2). Very difficult to extract a use case. Don't know if this commit fix it : https://github.com/codenameone/CodenameOne/commit/c2b4d50c97eb22124c7852c324d0d6b992220523

**Comment by JTBrandao** [comment]
I have also encountered the same situation. The issue ocurred on Android versions 6.0 or 7.0 on some diferent equipments (Moto G, Samsung J5, Samsumg Galaxy Tab A, Lenovo K10)
