### ISSUE TITLE
MATERIAL_SENTIMENT_VERY_SATISFIED

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2206]
I created a side menu in which I used the material icon: MATERIAL_SENTIMENT_VERY_SATISFIED

This icon is shown well in the simulator, but it's replaced with "[]" on my Android device. Other icons are shown well.

**Comment by codenameone** [comment]
![2017-09-04 14 05 46](https://user-images.githubusercontent.com/2353641/30023966-625a1b2e-917a-11e7-9490-505b399edb13.png)

This works for me

**Comment by codenameone** [comment]
````java
Form hi = new Form("Hi World", BoxLayout.y());
Label l1 = new Label("3D_ROTATION");
FontImage.setMaterialIcon(l1, FontImage.MATERIAL_3D_ROTATION);
Label l2 = new Label("SENTIMENT_NEUTRAL");
FontImage.setMaterialIcon(l2, FontImage.MATERIAL_SENTIMENT_NEUTRAL);
Label l3 = new Label("SENTIMENT_VERY_SATISFIED");
FontImage.setMaterialIcon(l3, FontImage.MATERIAL_SENTIMENT_VERY_SATISFIED);
hi.addAll(l1, l2, l3);
hi.show();
````

**Comment by jsfan3** [comment]
Is your screenshot taken in the simulator? Have you tested the difference between the simulator and a real Android device? Look at these two screenshot: the first one is taken from the simulator, the second one from Samsung Galaxy Chat:
![simulator](https://user-images.githubusercontent.com/1997316/30030159-5144ab30-918c-11e7-8146-0a54ecf01288.png)
![samsung](https://user-images.githubusercontent.com/1997316/30030180-7455c582-918c-11e7-9df0-be8d16ad7655.png)
This is the line of code about the third item in the side menu:
`        myToolbar.addMaterialCommandToSideMenu("Gruppo \"Accoglienza matricole\"", FontImage.MATERIAL_SENTIMENT_VERY_SATISFIED, (e) -> ... "));
`

**Comment by jsfan3** [comment]
P.S.: Setting the constant theme "hideBackCommandBool" to true the problem is solved. Of course, I don't know why, it seems very weird...

**Comment by codenameone** [comment]
It's from the device. I'm guessing you copied the material fonts locally to your project and overrode our font settings but it's a guess since you provided a screenshot and not a testcase

**Comment by jsfan3** [comment]
I'm sorry for the late response (I had busy days).

TEST CASE (it's the Netbeans project with the code that generates the bug shown in the screenshots):
[myCommunityBrowser.zip](https://github.com/codenameone/CodenameOne/files/1289867/myCommunityBrowser.zip)

GENERATED APK (tried on my Android device):
[MyBrowser-release.apk.zip](https://github.com/codenameone/CodenameOne/files/1289868/MyBrowser-release.apk.zip)

Please remember that the problem is only on a real device. At the moment, a workaround to solve it is to set the "hideBackCommandBool" to true.

**Comment by codenameone** [comment]
Can you isolate it to one embedded sample I can just run? Similar to the sample I presented above?
APK is useless and debugging peoples apps is a bit problematic when you are dealing with such a huge backlog of issues.

**Comment by jsfan3** [comment]
No, I'm sorry, I cannot isolate the bug in few lines of code: I've tried to reduce my app (that is already very tiny, it's 200 lines of code with comments, imports, etc.) to a minimal code that replicates the bug, but every trial didn't give me the expected result.
My app (in the Netbeans project zipped and attached above) has also another problem: if I uncomment `Display.getInstance().setProperty("WebLoadingHidden", "true");`, that instruction is simply ignored and Android continues to show the native indicator. 
So... feel free to analyze my app that maybe can reveal two different Codename bugs, or ignore it if it's too problematic :-)

**Comment by codenameone** [comment]
Sorry this slipped under the radar at some point. Make sure you aren't using problematic build hints. What's in your build hints for Android?
