### ISSUE TITLE
My app is frizing now in iOS

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2216]
My new update of my shipped app in android an IOS is now frizing in IOS opening the GoogleMapScreen. It was working perfectly before this blog changes

https://www.codenameone.com/blog/vm-changes-updates.html

I download the source code to check the issue and Now it stop in a break point and the console don't write nothing exception.

How can I fix this? could you check all the commint related with  this changes?

**Comment by DurankGts** [comment]
My app simple don't repose the touch event when I click to open my GoogleMap Screen. The I force to killed to open again an the problem it continue.

**Comment by DurankGts** [comment]
My app it don't response the touch event when I click to open my GoogleMap Screen. The I force to killed to open again an the problem it continue.

**Comment by codenameone** [comment]
If it's simple please provide a testcase
