### ISSUE TITLE
Make transparent status bar

### ISSUE THREAD

**Issue by shyamsth** [codenameone/CodenameOne#2220]
I have added 
android.xlayout_attr= android:fitsSystemWindows="true"

but there is no change on status bar ,please fix it as soon as possible.

**Comment by codenameone** [comment]
I've added the build hint `android.hideStatusBar=true`. We'll need to review this once the build server updates this Friday and see if it works. This will also require updating the theme to space the content down using the StatusBar UIID which I haven't done yet.
