### ISSUE TITLE
mysterious "all caps" in buttons

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2221]
About a month ago, some of the menus in my app started mysteriously appearing
in ALL CAPS.  This affects only android, not simulator or ios.

Here's a simple test program that exhibits the problem.

''''java
package dtest.boardspace;

import com.codename1.ui.Command;
import com.codename1.ui.Display;
import com.codename1.ui.Font;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.geom.Point;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

class Button extends com.codename1.ui.Button
{	
	public Button(Image image) { super(image); }
	public Button(String label) { super(label); }
	public Point getLocation() { return(new Point(getX(),getY())); }
	public void setFont(Font f) { getStyle().setFont(f); }
	public String getLabel() { return(getText()); }
	public void setLabel(String t) { setText(t); }
	
	public void setActionCommand(String oK) {
		setCommand(new Command(oK));
	}
	public String getActionCommand() 
		{ Command com = getCommand();
		  return((com==null) ? null : com.toString());
		}
	public void paint(Graphics g)
	{	
		super.paint(g);
	    //g.setColor(0xd000ff);
		//g.drawRect(0,0,getWidth()-1,getHeight()-1);
		//g.drawLine(getWidth(),0,0,getHeight());
	}
	public void setBounds(int l,int t,int w,int h) 
	{ setX(l);
	  setY(t);
	  setWidth(w);
	  setHeight(h);
	}

}

class Vtest 
{
    int ii = 0;
    // adding this line makes IOS builds fail
    //int jj = nextPlayer[ii];
    //
    
    // this version, using a default function, compiles but causes
    // a hard crash on IOS.
    //int jj = nextPlayer(ii);
    
	private Form current;
	private Button display = null;
	private static Resources res;
	
	public void init(Object context) {
        try {
            res = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(res.getTheme(res.getThemeResourceNames()[0]));
        } catch (Exception e) {
            e.printStackTrace();
        }
 	}

	public void start() {
		if (current != null) {
			current.show();
			return;
		}
		Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
		display = new Button("Test Button");
		display.setVisible(true);
		hi.add("Center",display);
		hi.show();
		display.repaint();
		System.out.println("Dtest running");
	}

	public void stop() {
		current = Display.getInstance().getCurrent();
	}

	public void destroy() {
	}

}

public class Dtest extends Vtest
{
	public void init(Object context) { super.init( context); }
	public void start() { super.start(); }
}

''''

**Comment by codenameone** [comment]
I suggest keeping an eye on the blog we had several discussions around this for a while now https://www.codenameone.com/blog/pixel-perfect-material-buttons-part-2.html there are also discussions in stackoverflow etc.

**Comment by ddyer0** [comment]
It's non-intuitive (at least) that a feature called "button ripple effect" causes the buttons
to be all caps.  That's the only practical advice I see in the referenced article, and in 
any case, setButtonRippleEffectDefault(false); and setRippleEffect(false); have no 
effect on my complaint at runtime.

**Comment by ddyer0** [comment]
I see that you referred me to the wrong blog article - the correct one is
https://www.codenameone.com/blog/pixel-perfect-material-buttons.html
..and to save the next reader the trouble, the caps issue can be fixed by
	static {
		setCapsTextDefault(false);
	}
