### ISSUE TITLE
App crashes because android stub activity does not remove added LifecycleListeners in the onDestroy method

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2231]
See attached file for the android crash stacktrace. 

LifecycleListeners added to the generated android activity stub's onCreate method are never removed (should be removed in OnDestroy).  This causes an app crash in any situation where the app is still running but the main activity has been destroyed by normal user action, and an attempt is made to (re)start the main activity.

The app crash is due to an NPE in com.codename1.social.GoogleImpl.onCreate(Bundle savedInstanceState), which incorrectly assumes savedInstanceState will always be non-Null.

GoogleImpl is added as a LifecycleListener to the static AndroidNativeUtil during the stub's onCreate(), but is never removed in the stub's onDestroy().  This is not a problem when the app's main activity/stub is the only application part.  However, in apps which have a persistent service that continues running even when the main activity has been normally ended (closed) by the user, this causes a crash when the main activity is re-created later (by any means - user launching the app from the icon or user launching the app via an intent sent by a persistent notification's default or other action).  This is because LifeCycleListeners are added to a static instance of AndroidNativeUtil, which continues to live after the main activity is destroyed if there is any other app component still running (like a service or other non-CN1 Activity created by app native code).

The fix is fairly simple - add a removeLifecycleListener call to the onDestroy method of the generated stub activity which removes GoogleConnect/GoogleImpl.  I'd suggest also removing any other LifecycleListeners that were added in the main activity stub's onCreate() as well.

[android_crash_stacktrace.txt](https://github.com/codenameone/CodenameOne/files/1363708/android_crash_stacktrace.txt)

**Comment by codenameone** [comment]
We added the remove listeners call that should be available in the next update of the build servers on Friday.

**Comment by igo211** [comment]
Almost but not quite...
You removed one LifeCycleListener (com.codename1.location.AndroidLocationPlayServiceManager), but neglected to remove the other one (com.codename1.social.GoogleConnect), which happens to be the cause of the bug mentioned in the initial filing and attached stacktrace.

**Comment by codenameone** [comment]
I've looked at this again and I don't see that. If this is added to onCreate it should be added to onDestroy. Can you post the source of your stub file's onCreate/Destroy methods?

**Comment by igo211** [comment]
public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        NativeLookup.register(com.zero211.dky.CallLogUtil.class, com.zero211.dky.CallLogUtilStub.class);
        NativeLookup.register(com.zero211.dky.CallMan.class, com.zero211.dky.CallManStub.class);
        NativeLookup.register(com.zero211.dky.NativePrefsWrapper.class, com.zero211.dky.NativePrefsWrapperStub.class);

        Display.getInstance().setProperty("IncludeGPlayServices", "true");
        com.codename1.impl.android.AndroidNativeUtil.addLifecycleListener(com.codename1.location.AndroidLocationPlayServiceManager.getInstance());
        com.codename1.social.GoogleImpl.init();
        com.codename1.impl.android.AndroidNativeUtil.addLifecycleListener((com.codename1.impl.android.LifecycleListener) com.codename1.social.GoogleConnect.getInstance());
    }

    protected void onDestroy()
    {
        com.codename1.impl.android.AndroidNativeUtil.removeLifecycleListener(com.codename1.location.AndroidLocationPlayServiceManager.getInstance());
        super.onDestroy();

        Display.getInstance().callSerially(new Runnable()
        {
            public void run()
            {
                i.destroy();
            }
        });
        AndroidImplementation.stopContext(this);
        running = false;
    }

**Comment by codenameone** [comment]
OK, found the problem. Should be fixed in the next update.
