### ISSUE TITLE
Sidemenu only opens once via icon when setOnTopSideMenu is true

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2233]
Title says it.  When Toolbar.setOnTopSideMenu(true), a form where the sidemenu bar is populated with anything only opens once when using the menu icon.  
After that, the menu icon doesn't respond to a click.  This happens on both simulator and android (didn't check iOS or other platforms).

Note, a manual drag from the left side *does* open the menu, it's just the menu icon that doesn't respond after the first click/open.

**Comment by shannah** [comment]
I can't reproduce this:

Here is the test case I'm using:

~~~~
private void testOnTopSideMenu() {
        Form sideMenuDemo = new Form("Side Menu", new LayeredLayout());
        Toolbar.setOnTopSideMenu(true);
        Toolbar tb = new Toolbar();
        sideMenuDemo.setToolbar(tb);
        tb.addCommandToSideMenu(new Command("Test") {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Hello");
            }
        });
        
        sideMenuDemo.show();
    }
~~~~

Please try this test case to see if you can reproduce the problem you are describing.  If you can't reproduce it, then please modify the test case as required to reproduce this problem

**Comment by shannah** [comment]
After some more tinkering, I've reproduced it.  The test case is:

~~~~
private void testOnTopSideMenu() {
        Form sideMenuDemo = new Form("Side Menu", new LayeredLayout());
        Toolbar.setOnTopSideMenu(true);
        Toolbar tb = new Toolbar();
        sideMenuDemo.setToolbar(tb);
        tb.addCommandToSideMenu(new Command("Test") {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Hello");
            }
        });
        
        sideMenuDemo.show();
    }
~~~~

**Comment by codenameone** [comment]
I see very problematic behaviors in the kitchen sink if I turn on the on-top sidemenu.
