### ISSUE TITLE
Local Notification localNotificationReceived Called Repeatedly On Android

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#2236]
Implementing a local notification calls the `localNotificationReceived` repeatedly on Android, whenever you minimize and restore the app.

Steps:

- Implement `LocalNotificationCallback` and override `localNotificationReceived`
```
@Override
public void localNotificationReceived(String value) {
    CN.callSerially(() ->  ToastBar.showMessage(value, FontImage.MATERIAL_CHECK, 5000));
}
```

- Create a local notification and set the time to like 30 seconds.
```
LocalNotification ln = new LocalNotification();
ln.setAlertTitle("Test");
ln.setAlertBody("This is a test message");
ln.setId("This is a test Id");
```
- Activate the notification and minimize the app on Android

```
Button btnTrigger = new Button("Trigger notification");
btnTrigger.addActionListener(evt -> Display.getInstance().scheduleLocalNotification(ln, 
System.currentTimeMillis() + 30000, LocalNotification.REPEAT_NONE));
```
- Tap the notification to open or restore the app.

- Allow the ToastBar to timeout then minimize and restore the app again, and it will display the ToastBar.

I've tested on both iOS and Android, and this only occurs on Android.

**Comment by codenameone** [comment]
@shannah  I'm assigning this to 3.8 for evaluation of the severity but it should probably go into the 3.9 phase

**Comment by shannah** [comment]
Fixed in build server.  Will be available in next update.
