### ISSUE TITLE
Components disappear when Dragging

### ISSUE THREAD

**Issue by digappsepp** [codenameone/CodenameOne#2237]
While dragging a Component and touching the screen with a second finger the Component disappears and the space it was in stays blank. In the Component inspector the component stays at the position but is just not visible(?). The GUI does strange things(Some Buttons become unresponsive or take a while to respond) after that happens and the CPU load is increasing.

I've created a reproducable Testcase that creates the error on the Simulator and on iOS (on android it works just fine)

Steps to reproduce:
on iOS: Touch the sceen with a second finger while a component is being dragged.
on the Simulator: click the right mouse button while a component is being dragged.

`

		Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));

		Container con = new Container(new FlowLayout());
		
		Label lab1 = new Label("TEST 1");
		Label lab2 = new Label("TEST 11");
		Label lab3 = new Label("TEST 111");
		
		lab1.setDraggable(true);
		lab2.setDraggable(true);
		lab3.setDraggable(true);
		
		con.add(lab1);
		con.add(lab2);
		con.add(lab3);		
		
		con.setDropTarget(true);
		hi.add(BorderLayout.CENTER, con);

		hi.show();`

Screenshots

![screenshot_cn1_01](https://user-images.githubusercontent.com/32707062/31441926-fa012580-ae94-11e7-9a88-06b17dc382d4.jpg)

**Comment by digappsepp** [comment]
Hi, are there any news about this issue?

**Comment by codenameone** [comment]
Sorry I meant to look into it and it slipped under the weight of emails. I've assigned it to the coming milestone so it doesn't get lost.
