### ISSUE TITLE
RFE: Create a new Theme that conforms to Material design guidelines and make available in the new project wizard in IDE plugins

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2238]
The current crop of themes available for selection don't appear to include any choice that conforms to Google's material design guidelines.  Specifically, color (https://material.io/guidelines/style/color.html# ) and typography ( https://material.io/guidelines/style/typography.html# ) sections (and the intersection of the two - font color legibility/accessibility ) don't seem to be followed in any of the themes.  
It would significantly cut down on app time to market if at least one theme available from the new project wizard followed material design guidelines.

Additionally, it would be highly desirable if all foreground/background/transparency colors were derived from a set of styles (not from image borders) that mapped to the material design color categories ( Primary, Primary light, Primary dark, Secondary, Secondary Light, Secondary Dark, Accent ), so that a designer or dev could simply change that set of colors in one style per category and have all components appropriately change to match.

**Comment by ThomasH99** [comment]
Yes, it’s a surprsing amount of work and trial and error to get a working design without having to set hundreds of individual properties on the various UIIDs so the proposed way of reusing colors from central style elements could probably help reduce the effort. And having professional-level designs like Material working out of the box would also help convince developers faster of the effort saved using CN1.

**Comment by codenameone** [comment]
Closing this as this isn't a helpful. I discussed the way to submit helpful theme related issues in this series: https://www.codenameone.com/blog/pixel-perfect-material-buttons.html

We need fine grained issues.

**Comment by igo211** [comment]
I guess I wasn't being clear enough.
This was a request for a *new* theme that follows Material design guidelines, not somehow fixing the existing themes (which would require a non-trivial number of issues filed).
