### ISSUE TITLE
RFE:  Add native:MainMedium and native:ItalicMedium as additional font choices in design tool

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2239]
Please add native:MainMedium and native:ItalicMedium as additional font choices.
Google Material Design guidelines's Typography section specifies Roboto Medium as the preferred font weight in several places, but this doesn't seem to be as easily selectable in the design tool/theme as the other Roboto font weights (yes, possible via specific TTF font selection, but it should be just as easy as native:MainRegular and native:MainBold).

**Comment by codenameone** [comment]
native:MainRegular maps to the platform default font which should map to that.

**Comment by igo211** [comment]
Hmmm...
OK, so if native:MainRegular maps to Roboto Medium, then native:Main* what maps to Roboto Regular?
Roboto Medium and Roboto Regular are two entirely different font weights.
See: https://fonts.google.com/specimen/Roboto

**Comment by igo211** [comment]
Also, note that in the Typography section of Material Design Guidelines ( https://material.io/guidelines/style/typography.html# ), Google specifies the use of Roboto Light, Regular, and Medium for various UI elements.  Regular != Medium
