### ISSUE TITLE
Commands don't generate action events if theme const commandBehavior=Bar

### ISSUE THREAD

**Issue by Shturman8** [codenameone/CodenameOne#2240]
After last update cn1 lib files commands stop generate action events on touche devices if theme const commandBehavior=Bar

In this example command "OK" and "Cancel" don't print anything:

`Form hi = new Form("Hi World", BoxLayout.y());`
`hi.add(new Label("Hi World"));      `
`hi.addCommand(new Command("OK"){`
`	@Override`
`	public void actionPerformed(ActionEvent evt){`
`		System.out.println("OK");`
`	}			`		
`});`
`hi.addCommand(new Command("Cancel"){`
`	@Override`
`	public void actionPerformed(ActionEvent evt){`
`		System.out.println("Cancel");`
`	}		`			
`});`
`hi.show();`

![2017-10-12 20 59 33](https://user-images.githubusercontent.com/13847799/31511414-5632490a-af90-11e7-9ea6-584c79754148.png)

**Comment by codenameone** [comment]
`setCommandBehavior` is deprecated, we use the Toolbar API now. I clarified this in the docs

**Comment by Shturman8** [comment]
But with Toolbar Api I can't place the commands buttons on the bottom of the form. How to do this in latest version?

**Comment by codenameone** [comment]
Add buttons to the SOUTH with a border layout
