### ISSUE TITLE
OverflowMenu error on Android

### ISSUE THREAD

**Issue by jpaul51** [codenameone/CodenameOne#2255]
The overflow menu won't open anymore on android devices since today.
Code example:
```
Form hi = new Form(); 
hi.getToolbar().addCommandToOverflowMenu("Test", FontImage.createMaterial(FontImage.MATERIAL_3D_ROTATION, new Style()), new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
               ToastBar.showMessage("menu", FontImage.MATERIAL_3D_ROTATION);
               hi.revalidate();
            }
        });
hi.show();
```
What I get when i click on the overflowMenu: 
![screenshot_2017-10-27-15-23-59](https://user-images.githubusercontent.com/22674982/32106142-1eb3f07c-bb2b-11e7-8077-e0ae3ded74a9.png)

Tested on android 5.1 and android 4.4

**Comment by codenameone** [comment]
FYI this is due to the on-top side menu change we made. Steve fixed it for the next update (Friday) but you can workaround it by disabling the on top side menu for now.
