### ISSUE TITLE
RFE: addButtonToLeftBar and similar methods on Toolbar API

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2259]
At the moment, the Toolbar API has very useful methods, like:
addCommandToLeftBar
addCommandToRightBar
addCommandToOverflowMenu
addCommandToSideMenu
etc.,
but there aren't methods like "addComponentToRightBar" or "addButtonToLeftBar", that can be useful (for example to add a ShareButton easily). Can you add these kind of methods?

**Comment by codenameone** [comment]
This is something we are generally opposed to. People will start adding buttons and create a complete mess. You can set the Title Component and generally do everything you want within that component (Containers with every button you need) so this is possible but if we make it easy people will start adding buttons then complain their apps look/behave badly.
