### ISSUE TITLE
Internet access for apps on Android 7.0 (Mobile Data)

### ISSUE THREAD

**Issue by demcho** [codenameone/CodenameOne#2261]
Internet access for apps on Android 7.0 (Mobile Data)
Hello I just updated my test mobile phone to android 7.0 and I noted that my app can only access interne while is connected to wifi so I will like to know if there is a known trouble regarding internet access on android 7.0

**Comment by codenameone** [comment]
We have no reports of that. I suggest following up in stackoverflow or the discussion forum
