### ISSUE TITLE
Top Sidemenu should be visible or closed when navigating back

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#2262]
I really enjoyed the new menu, but I ran into an issue, consider 2 forms, one of them have a toolbar with  a side menu, where one of the commands call the other form, which has a toolbar with a back command. When I press the back command and the former form is shown the side menu is invisible but there, clicking outside its area makes it show the closing animation. I would expect it to be either visible or closed.

**Comment by codenameone** [comment]
Thanks. We already saw this and fixed it in the current git
