### ISSUE TITLE
Scrollable x of buttons not running freely

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#2263]
Given the following code:

        Form f = new Form(new BorderLayout());
        Container cont = new Container(new BoxLayout(BoxLayout.X_AXIS));
        cont.setScrollableX(true);
        for (int x=0; x<20; x++) {
            Button btn = new Button();
            FontImage.setMaterialIcon(btn, FontImage.MATERIAL_APPS, 20);
            cont.add(btn);
        }
        f.add(BorderLayout.SOUTH, cont);
        f.show();

This works fine on simulator, but not on Android (have not tried on iOS). Scrolling through the buttons, it gets stuck after lifting the finger, instead of scrolling freely. Changing buttons for labels solves the problem, so it probably has to do with actions...

This workaround solves the problem for now...

        Form f = new Form(new BorderLayout());
        Container cont = new Container(new BoxLayout(BoxLayout.X_AXIS));
        cont.setScrollableX(true);
        for (int x=0; x<20; x++) {
            Button btn = new Button();
            FontImage.setMaterialIcon(btn, FontImage.MATERIAL_APPS, 20);
            Container contButton = new Container(new BorderLayout());
            contButton.add(BorderLayout.CENTER, btn);
            contButton.setLeadComponent(btn);
            cont.add(contButton);
        }
        f.add(BorderLayout.SOUTH, cont);
        f.show();

**Comment by codenameone** [comment]
After evaluating this it seems to be an issue that was there for a while and happened back in 3.7. Since there is a workaround I'm assigning this to 4.0 for full evaluation

**Comment by codenameone** [comment]
It seems this is working now. I'm guessing it's one of the fixes @shannah pushed to pointer events that solved this
