### ISSUE TITLE
Toolbar's findCommandComponent(Command c) method does not work when setOnTopSideMenu is false

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2265]
Get the sidemenu commands via Toolbar's getSideMenuCommands, then call findCommandComponent on any of the returned commands, and in each case, null is returned.

if setOnTopSideMenu is true instead, the component is found.

**Comment by codenameone** [comment]
Was this something that ever worked?
The old side menu bar constructed itself lazily so find command component on the OLD on-top mode probably never worked. Since most of the issues with `setOnTopSideMenu` should be resolved I would suggest switching to that anyway.

**Comment by igo211** [comment]
The bug doesn't appear to have anything to do with lazy construction.  
The full set of Commands are there, and the corresponding buttons are there as well (as seen by stepping thru the findCommandComponent code).  I'm not sure why yet, but the commands returned from getSideMenuCommands and the button associated commands being iterated thru by findCommandComponent have the same names, but are different instances (have different object ids), and so fail the equality check, and so findCommandComponent doesn't find the matching button despite the button being there.  My guess would be that there's some sort of copying/wrapping of the commands going on somewhere in either getSideMenuCommands or during the creation of the buttons, such that the two are working against different instance sets of commands, but I haven't isolated that suspected copy/wrapping yet.

I'd very much like to use the menu-on-top version, but every week for the last several weeks I've found at least one new bug that prevents me from realistically doing so.  I'm hoping Friday's update will be the one where I can actually switch over.

**Comment by codenameone** [comment]
I think my fix to find command component here https://github.com/codenameone/CodenameOne/commit/435f767cfb945b4876a4ce3612c450477aeec7df  would also solve this issue but I didn't get a chance to test it yet
