### ISSUE TITLE
on top sidemenu bar shows a duplicate of itself when opening sidemenu

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2269]
When using on top sidemenu:
1) Main form with the sidemenu is shown.
2) user opens sidemenu.
3) user clicks a sidemenu button/command which opens a new form, passing the main form instance to the new form.
4) user goes back (i.e. main form's showBack() method is called)
5) Main form is displayed again with sidemenu closed (as expected)
6) user opens the sidemenu.
7) a sidemenu is immediately displayed (no animation), with another, duplicate of the sidemenu shown to animate in from the left over the first sidemenu.

**Comment by codenameone** [comment]
Is this happening with today's release?
We added a fix for the side menu issue that should resolve a similar issue. Make sure you used update client libs.

**Comment by igo211** [comment]
Yes, I have updated the client libs today and rebuilt/re-run.  The issue is definitely there.

I suspect the fix you mention is this checkin: https://github.com/codenameone/CodenameOne/commit/8407ef22055b7677fa8e8ad7fe3eb4be6785009a , yes?  
If so, I was the one that sent you an email on that bug (my github id is not similar to my CN1 account email addy), and yes *that* un-filed bug is fixed, but perhaps the fix is what caused this new one?

**Comment by codenameone** [comment]
I'll try to reproduce it and possibly deploy a fix over the weekend
