### ISSUE TITLE
Android 4.3 crash on launch

### ISSUE THREAD

**Issue by jpaul51** [codenameone/CodenameOne#2271]
When I install and launch any get started application on android 4.3 the application crashes. A get started application will start the second time I try to launch it. My application keeps crashing. I have this issue since today. I have tested on android 4.3 and on android 5.0.1. This issue does not occur on android 5.0.1.

Here is the locgat with a priority of Warning and above:
[logcat.log](https://github.com/codenameone/CodenameOne/files/1441090/logcat.log)

**Comment by jpaul51** [comment]
Yes it's a logcat log. There is some noise in that log. The package name is door.door_applications.ecosystem.

**Comment by codenameone** [comment]
This should be fixed by a commit from @shannah it's on the build servers so can you please check a new build?

**Comment by jpaul51** [comment]
I can not check until next Monday. I will keep you updated.

**Comment by jpaul51** [comment]
My app works on Android 4.3.
