### ISSUE TITLE
CodenameOne Settings screen Android cert generator fails with unreadable error message when a comma is part of a field value

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2272]
This is really 2 bugs in 1.

When using the Android Certificate Generator in the CodenameOne Settings screen, entering a comma as part of any field value causes the certificate generation to fail (bug 1 - IMHO, prior to the call into keytool, the settings screen code should escape any commas, or any other illegal/troublesome characters, from the input fields).  

When an error occurs in cert generation, such as the above, the error message is *very* briefly shown in a toastbar at the bottom.  
The error message is shown far too quickly to be read, and so the user/developer has no way of knowing why the cert gen failed (bug 2 - error messages should be dialogs, not shown in anything ephemeral - error messages should stay visible until the user/dev dismisses the message).

**Comment by DigNZ** [comment]
Expanding on this the cert generator fails silently for any error, i.e., password too short. It looks like its worked as the paths have been filled in but the file isn't created and there is no feedback as to what is wrong.

**Comment by igo211** [comment]
Perhaps I'm mis-reading the changes, but the above commit reference appears to only increase the default ToastBar timeout by 1/2 second.  That by itself doesn't really address the issues mentioned (a 1/2 second timeout increase doesn't make a very long error message readable/actionable).  Can you point us to any additional commits, (possibly relating to how "cert generation is now handled better"), that address the issues mentioned above?  thanks.

**Comment by codenameone** [comment]
No the fix itself is in the settings repo that isn't visible here. I increased the timeout there more noticeably (it's hard to move this to something more permanent) and I added better validation. I also escaped commas.
