### ISSUE TITLE
BrowserComponent.pointerPressed() with no effect

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2273]
I would expect that `pointerPressed` calls on `BrowserComponent`s  would also be forwarded to the html page.

        f.removeAll();

        final String html = "<html><body><div style=\"width:100%; height:100%\" onclick=\"appCallback.run()\"></div></html>";
        
        BrowserComponent bc = new BrowserComponent();
        bc.setPage(html, "www.url.com");
        bc.setScrollableX(false);
        bc.setScrollableY(false);
        
        JavascriptContext ctx = new JavascriptContext(bc);
        JSObject jsEvents = (JSObject) ctx.get("{}");
        jsEvents.set("run", (JSFunction) (JSObject self, Object[] args) -> ToastBar.showMessage("CLICKED", ' '));
        ctx.set("window.appCallback", jsEvents);
        
        // these actions have no effect!!! (simulator / android / iOs)
        UITimer.timer(1500, true, () -> {
            int x = CN.getDisplayWidth() / 2, y = CN.getDisplayHeight() / 2;
            bc.pointerPressed(x, y);
            bc.pointerReleased(x, y);
        });
        
        f.addComponent(BorderLayout.CENTER, bc);

**Comment by codenameone** [comment]
That won't work and shouldn't work. Peer components reside in a separate space from lightweight components so this isn't practical.
