### ISSUE TITLE
duplicate symbol in IOS xcode builds

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2274]
Working from today's build sources, compiling with xcode 8.3.3, builds fail with a link error:
This appears to be a legitimate duplicate, the name "popoverControllerInstance" appears
in both IOSNative and CodenameOne_GLViewController.  It's unclear why this is affecting
my local builds but not your server builds, but it ought to be easily fixed by changing IOSNative

---

duplicate symbol _popoverControllerInstance in:

    /Users/davedyer/Library/Developer/Xcode/DerivedData/Develop-gjxjnstwppovjrbixnibhajurmco/Build/Intermediates/Develop.build/Debug-iphonesimulator/Develop.build/Objects-normal/x86_64/CodenameOne_GLViewController-40B184A5574989AD.o

    /Users/davedyer/Library/Developer/Xcode/DerivedData/Develop-gjxjnstwppovjrbixnibhajurmco/Build/Intermediates/Develop.build/Debug-iphonesimulator/Develop.build/Objects-normal/x86_64/IOSNative.o

ld: 1 duplicate symbol for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by codenameone** [comment]
@shannah I see the problem and it looks related to one of my commits (missing extern statement).

The question is should we fix this in the code freeze or wait for next week.

**Comment by ddyer0** [comment]
it doesn’t seem to be affecting server builds, so i wouldn’t push it.
