### ISSUE TITLE
missing string constructor

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2275]
In java 8, the constructor new String(char []chars) is deprecated, and 
the use of the static function String.valueOf(char []chars) is encouraged.

Unfortunately, if you switch to this form, codename1 falls into the constructor
for String.valueOf(Object x) which produces garbage.

At some point, you need to add the equivalent of this static function to the VM support
   /**
     * Returns the string representation of the {@code char} array
     * argument. The contents of the character array are copied; subsequent
     * modification of the character array does not affect the returned
     * string.
     *
     * @param   data     the character array.
     * @return  a {@code String} that contains the characters of the
     *          character array.
     */
    public static String valueOf(char data[]) {
        return new String(data);
    }

**Comment by codenameone** [comment]
The `contains` method is also missing and I'm sure there are some other things. I think we need to make a small "wish list" of JVM changes as one bug.

**Comment by shannah** [comment]
Just went in there to add String.valueOf(char[]) are already defined in CLDC11 and in JavaAPI.  I added isEmpty() and contains() while I was in there.... but valueOf(char[]) should already work.

**Comment by codenameone** [comment]
I assumed you already did most of that for Kotlin which is why I assigned that.
