### ISSUE TITLE
android 7 landscape soft keyboard done button when no next TextField to focus on breaks soft keyboard

### ISSUE THREAD

**Issue by jlainema** [codenameone/CodenameOne#2278]
See details at https://groups.google.com/d/msgid/codenameone-discussions/d761c1a3-1a67-48c5-9f64-e34d13886705%40googlegroups.com

**Comment by shannah** [comment]
Just trying to formulate a test case based on the linked thread.  This is the most recent code provided:

~~~~
public class TextEdit extends TextField {
	Form result;
	TextEdit(Form f) {
		result = f;
		final TextEdit te = this;
		setSingleLineTextArea(false);
		addActionListener(al -> {
			Display.getInstance().callSerially(() -> { te.stopEditing(); result.show();});
		});
		setDoneListener(dl -> {
			Display.getInstance().callSerially(() -> { te.stopEditing(); result.show();});
		});
	}
	
} 
~~~~

**Comment by shannah** [comment]
Note:  With this fix, you no longer need to implement your doneListener to stop editing either.  The keyboard should close on its own.
