### ISSUE TITLE
Any possibility to block entire interaction with Tabs Component?

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2283]
I'm not sure how to block the swipe interaction with a `Tabs` component by an overlay which should catch all kind of touch events so they don't reach the components beneath.
I'm aware of the `setSwipeActivated` method but I would like to have a more generic solution. Thus I wouldn't need to care about whether a Tabs component exists beneath the overlay.
The problem is that the listeners for the Tabs' swipe interaction are added to the `Form` itself but currently (in CN1's implementation) there is no possibility to catch and consume pointerPressed/Dragged etc. events before they reach those listeners (except for adding own listeners before the Tabs component is added to the Form). 
Or did I just miss another possible solution?

Note: the *overlay* is supposed to be placed on the FormLayeredPane of the Form.

**Comment by codenameone** [comment]
I don't understand the use case you are trying to address here. What sort of API would you expect to have?

**Comment by kutoman** [comment]
Intuitivly I would expect that a **focusable** component, which covers the whole screen, would catch all touch events so that no component beneath the covering component would receive any touch event. But this is not the case when a `Tabs` component is used since it makes the containing `form` listening to the touch events. Why is it implemented like this? Why are its `SwipeListener`s not added to the Tabs container itself?

the corresponding code from `Tabs`:

    protected void initComponent() {
        super.initComponent();
        Form form = this.getComponentForm();
        if (form != null && swipeActivated) {
            form.addPointerPressedListener(press);
            form.addPointerReleasedListener(release);
            form.addPointerDraggedListener(drag);
        }
    }

**Comment by codenameone** [comment]
The problem with doing this in the tabs is that the tab would then grab all the focus events from components within. The idea is that this would be non-intrusive. I'm not sure how we can improve that in the current API. 
I think the only workaround for this is a special case for tabs.

**Comment by kutoman** [comment]
hmm I see. In this case maybe the possibility to enable/disable pointer pressed event listenings of `Form`s would help. However I'm not sure if it's a good practice.

**Comment by codenameone** [comment]
You can override the form pointer* callbacks which will block everything but that's probably not what you would want.  I'll close this issue for now as I don't think it's something we can address. If you have something more specific in mind such as an API suggestion we can reopen or file a new issue.
