### ISSUE TITLE
Bug in Codename One Designer 3.8.0: java.lang.ClassCastException

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2286]
**Screenshot**:
![classcastexception](https://user-images.githubusercontent.com/1997316/33494369-5606d07c-d6c3-11e7-8b32-d3d084cf3260.png)

**Steps to reproduce**:
In the theme, add a new style and select an SVG image for the backgroud.

**Workaround to bypass this issue**: instead of using a theme UIID, I solved using the following code that does exactly the same thing that I tried to do with the Codename One Designer...
```
       // Background
        Container backgroundContainer = new Container(BorderLayout.center());
        backgroundContainer.setName("Background-Container");
        backgroundContainer.setUIID("Background-Container");
        backgroundContainer.getUnselectedStyle().setBgImage(theme.getImage("myBackground.svg"));
        backgroundContainer.getUnselectedStyle().setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FILL);
```

**Comment by jsfan3** [comment]
Please don't remove the SVG support: I need that and my SVG images are shown well both on Android and iOS platforms, with better image quality, better scaling quality and less size than equivalent multiimages pngs.
I know well your fork of Flamingo SVG transcoders for Codename One: I've done hours and hours of testing with it. The result is bad, because the Java code produced (using my simple SVGs) doesn't work in Codename One (it adds in the code some instructions that are not in Codename One API). Even when the images are converted correctly, they are not compatible with methods like scaledSmallerRatio() that I use with SVG. So your Flamingo fork is not an option.

I have simple SVGs that works well from old to new versions of the devices. SVGs have several advantages and my code relies on SVG suport. Please keep them supported by Codename One. Thank you.

**Comment by codenameone** [comment]
Your assumption that this feature "works" is incorrect. 
What you are effectively doing is converting the SVG to a raster image and using that on the device so the difference between using that and using MultiImage is that you have the overhead of an additional SVG file within the resource file and the bugs to go with something that is no longer used. 

You should either use multi-image (which as I said would be identical to what you are doing now) or fix the transcoder.

**Comment by jsfan3** [comment]
The conversion of the SVG to a raster image is done during the running of the app? I've seen that the Designer has the option to convert SVG to a multi-image, but I'm not using it.

I ask this question because the same app produces a jar (before sending it to the Codename One build cloud) that is a lot lighter using SVGs instead of PNGs. The APKs files produced by the Codename One build cloud are lighter using SVGs instead of PNGs.

**Comment by codenameone** [comment]
It's done once on your desktop in the tool. I'm guessing you only generated one resolution of the SVG image so it's really the equivalent of an RGB image you haven't scaled. Try scaling the image and see the distortion.

**Comment by jsfan3** [comment]
You're right.
