### ISSUE TITLE
Send an e-mail with attachment

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2287]
The methods of the class [Message](https://www.codenameone.com/javadoc/com/codename1/messaging/Message.html) to attach one or more files to an e-mail (as described in the API) don't work on the real devices that I tested.
Is this functionality working only in some devices and others don't?

**Comment by codenameone** [comment]
It works. Notice that the path needs to point at a full absolute file URI within FileSystemStorage ideally within apphome.It will not work with Storage files!

See: https://stackoverflow.com/questions/46846369/codename-one-attaching-images-to-email-message-fails

https://stackoverflow.com/questions/47102623/how-to-get-an-absolute-uri-of-a-file-that-exists-in-codenameone-filesystemstorag
