### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2288]
From few hours, I have an iOS Build Error with every code that I send, even if a send a basic "Hello world". What is the meaning of the attached log? I previously send iOS build without problems.

[e6929451-7be3-43a5-a5c4-ea81f532e44d-1512441912595-error.txt](https://github.com/codenameone/CodenameOne/files/1529599/e6929451-7be3-43a5-a5c4-ea81f532e44d-1512441912595-error.txt)

**Comment by codenameone** [comment]
This is the error:

````
2017-12-05 02:45:12 +0000 [MT] Filtering based on requested entitlements: {
    "application-identifier" = "Q5GHSKAL2F.it.galgani.apps.demos.svg";
    "get-task-allow" = 1;
    "keychain-access-groups" =     (
        "Q5GHSKAL2F.it.galgani.apps.demos.svg"
    );
}
2017-12-05 02:45:12 +0000 [MT] Rejecting: bf182331-8b5b-4fd9-ade3-6370f2593d4e (Offending Key: application-identifier)
````

I'm guessing you refactored back and forth and the provisioning profile doesn't match app id/package name/certificate etc.
