### ISSUE TITLE
Bug: iOS certificate wizard

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2290]
**Normal functionality**: if you go to the properties of a Netbeans project, then click on IOS, then click on Generate, the "iOS certificate wizard" works fine and it installs the generated certificates.

**Bugged functionality** on a copy of Netbeans without previously installed iOS certificates: if you go to "CodenameOne settings" of a Netbeans project (that is different from the properties of the project as above), then click on "iOS certificate wizard", the wizard will create the new certificates, but it will not give option to save them (so they will be not installed). This is what happened to me.

**Comment by codenameone** [comment]
Did you press the save button after the wizard completed?

**Comment by jsfan3** [comment]
There is no "save button". The GUI of the wizard that you can access from the "CodenameOne settings" is different from the wizard that you can access from properties of a Netbeans project: only in the second case the GUI has a save button.

**Comment by shannah** [comment]
We need to remove the wizard from the regular properties dialog.  It is deprecated, and hasn't been updated in long time.  The only current correct way to use the wizard is through codename one settings.

**Comment by codenameone** [comment]
@jsfan3 if I understood the description correctly the problematic behavior happens in Codename One Settings where the save button exists. So did you press it when the wizard completed or did you press something else?

Also on which OS did this happen?

**Comment by jsfan3** [comment]
No, it's the opposite: if you go to the properties of a Netbeans project, then click on IOS, then click on Generate, the "iOS certificate wizard" works fine (there is an "Install now" button, screenshot 1). The problematic behavior happens if you go to "CodenameOne settings" (no "Install now" button), that means: right click on the project, click on "Codename One", click on "CodenameOne settings", click on "iOS certificate wizard" (screenshot 2).
Tested several times on Linux Mint 18.2 with java version "1.8.0_151". I suppose that it's easily repeatable bug behavior.

Another important information: in the second case (screenshot 2) there is no way to enable push.

Screenshot 1: 
![screenshot1](https://user-images.githubusercontent.com/1997316/33848299-9691716e-dead-11e7-9c9a-3883df0bfc17.png)

Screenshot 2:
![screenshot2](https://user-images.githubusercontent.com/1997316/33848300-96b5791a-dead-11e7-8328-293547fb1184.png)

**Comment by codenameone** [comment]
That's what I said. The save button is in the top right corner in that UI.

**Comment by jsfan3** [comment]
No, there is no "save button" in the top right corner because after creating the certificates the only option is to click a check mark, after that the window closes without giving me the chance to save them. Please also note the bug that prevents me to enable push (there is no way to enable it, see the screenshot). I have a PRO account and accessing to the wizard from the properties of the Netbeans project allows me to enable push.

![noenablepush](https://user-images.githubusercontent.com/1997316/33939342-1c9fb3b6-e00b-11e7-877c-8cf8fdbde687.png)

**Comment by codenameone** [comment]
OK, you did click the checkmark though right?
Login again using the Codename One Settings app and it should refresh your user type and enable that.

Might be a windows related issue, I'll need to look into it.

**Comment by jsfan3** [comment]
Yes, I clicked on the checkmark, after that the window closed without saving anything,
Login again using the Codename One Settings solved the push issue.
