### ISSUE TITLE
html link from BrowserComponent gets autofocused

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2292]
This somehow didn't happen before the recent CN1 update. It happens on my Android device as soon as I touch the BrowserComponent. This is annoying when the link is at the bottom of the html page which is initially not visible and thus the view gets auto scrolled. How can I turn this off?

**Comment by codenameone** [comment]
This is probably related to this fix https://github.com/codenameone/CodenameOne/commit/70c3bdc8ddb38544c2574271d7363e565e1dfbae

We need pointer events over peer components for things like the side menu. Might need a special case to prevent a loop in Android.

**Comment by shannah** [comment]
@kutoman , Can you post a test case?  On Android, the browser component is set to request focus when it is touched - but it has been like this for a while now.  Not a recent update.

**Comment by kutoman** [comment]
@shannah here is a test case:

        BrowserComponent browser = new BrowserComponent();
        String htmlPage = "<html><body>";
        for(int i=0; i<30;i++) htmlPage += "<p>LOREM IPSUM " + i + "</p>";
        htmlPage += " <a href=\"https://www.link.com\">Any auto-focused Link</a></body></html>";
        browser.setPage(htmlPage, "www.anyurl.com");
        
        f.setLayout(new BorderLayout());
        f.add(BorderLayout.CENTER, browser);
        f.revalidate();

**Comment by shannah** [comment]
I adapted your test case to the following:

~~~~
 private void testBrowserComponentAndroidLinkAutoFocus() {
        Form f = new Form();
        BrowserComponent browser = new BrowserComponent();
        String htmlPage = "<html><body>";
        for(int i=0; i<30;i++) htmlPage += "<p>LOREM IPSUM " + i + "</p>";
        htmlPage += " <a href=\"https://www.example.com\">Any auto-focused Link</a></body></html>";
        browser.setPage(htmlPage, "https://www.example.com");

        f.setLayout(new BorderLayout());
        f.add(BorderLayout.NORTH, new Label("Hello World"));
        f.add(BorderLayout.CENTER, browser);
        f.show();
        
        
    }
    
~~~~

But I cannot seem to reproduce the issue.  When I tap in the browser component it doesn't autoscroll anywhere.

**Comment by kutoman** [comment]
@shannah that's weird, if I use your code (e.g. creating a new From) the issue can't be reproduced, I experienced. But with my code the issue can be reproduced. I also noticed on the simulator, the BrowserComponent behaves differently (on click) based on the code I used as the test case:

**Reaction on my code** (Note: on the first click the component kinda gets a padding)
![mytestcase](https://user-images.githubusercontent.com/5825645/34211739-5137dc40-e59a-11e7-8f0d-78f1e467419d.gif)

**Reaction on your code** (is nothing unusual here)
![stevestestcase](https://user-images.githubusercontent.com/5825645/34211741-514f7e86-e59a-11e7-9528-763790237abb.gif)


**to be more precise, this is my code:**

    private void testBrowserComponentAndroidLinkAutoFocusOn(Form f) {

        f.removeAll();

        BrowserComponent browser = new BrowserComponent();
        String htmlPage = "<html><body>";
        for(int i=0; i<30;i++) htmlPage += "<p>LOREM IPSUM " + i + "</p>";
        htmlPage += " <a href=\"https://www.link.com\">Any auto-focused Link</a></body></html>";
        browser.setPage(htmlPage, "www.anyurl.com");
        
        f.setUIID("Form");
        f.setLayout(new BorderLayout());
        f.add(BorderLayout.NORTH, new Label("Hello World"));
        f.add(BorderLayout.CENTER, browser);
        f.revalidate();

    }

**Comment by shannah** [comment]
Can you modify my test case to reproduce the issue?  E.g. create a form, populate it, and show it all in a single method.

**Comment by kutoman** [comment]
I will try

**Comment by kutoman** [comment]
unfortunately I couldn't produce such a Form yet, but I found out that in my test case if I set the `uiid` of the internal component (PeerComponent) to a specific one with padding/margin = 0 the BrowserComponent doesn't get deformed on the clicks at least.

**Comment by kutoman** [comment]
unfortunately I couldn't produce such a Form yet, but I found out that in my test case if I set the `uiid` of the internal component (PeerComponent) to a specific one with padding/margin = 0 the BrowserComponent doesn't get deformed on the clicks at least.

**Comment by kutoman** [comment]
I finally found one possibility to reproduce the issue based on a new `From`. As I added the last lines I thought that those won't change anything but indeed they did!

    private void testBrowserComponentAndroidLinkAutoFocusMine() {
        Form f = new Form();
        
        BrowserComponent browser = new BrowserComponent();
        String htmlPage = "<html><body>";
        for(int i=0; i<30;i++) htmlPage += "<p>LOREM IPSUM " + i + "</p>";
        htmlPage += " <a href=\"https://www.link.com\">Any auto-focused Link</a></body></html>";
        browser.setPage(htmlPage, "https://www.link.com");

        f.setLayout(new BorderLayout());
        f.add(BorderLayout.NORTH, new Label("Hello World"));
        f.add(BorderLayout.CENTER, browser);
        f.show();
        
        Component dummy = new Container();
        Container parent = browser.getParent();
        parent.replaceAndWait(browser, dummy, null);
        parent.replaceAndWait(dummy, browser, null);
        
    }

**Comment by codenameone** [comment]
replace with null argument and replace and wait should be equivalent.
Try invoking this with the form already showing using the show listener.

**Comment by kutoman** [comment]
@codenameone you mean calling it in `protected void postXXX(Form f)`? Well, this is causing the issue as my first test case shows.

**Comment by codenameone** [comment]
This isn't the same. Use the show listener code to bind that logic.

**Comment by kutoman** [comment]
I did but the issue remains

**Comment by codenameone** [comment]
Just so we are on the same page try this:

````java
private void testBrowserComponentAndroidLinkAutoFocusMine() {
    Form f = new Form();
    
    BrowserComponent browser = new BrowserComponent();
    String htmlPage = "<html><body>";
    for(int i=0; i<30;i++) htmlPage += "<p>LOREM IPSUM " + i + "</p>";
    htmlPage += " <a href=\"https://www.link.com\">Any auto-focused Link</a></body></html>";
    browser.setPage(htmlPage, "https://www.link.com");

    f.setLayout(new BorderLayout());
    f.add(BorderLayout.NORTH, new Label("Hello World"));
    f.add(BorderLayout.CENTER, browser);
    f.show();
    
    f.addShowListener(e -> {
       Component dummy = new Container();
       Container parent = browser.getParent();
       parent.replace(browser, dummy, null);
       parent.replace(dummy, browser, null);
    });
}
````

Or (notice the revalidate at the bottom here):

````java
private void testBrowserComponentAndroidLinkAutoFocusMine() {
    Form f = new Form();
    
    BrowserComponent browser = new BrowserComponent();
    String htmlPage = "<html><body>";
    for(int i=0; i<30;i++) htmlPage += "<p>LOREM IPSUM " + i + "</p>";
    htmlPage += " <a href=\"https://www.link.com\">Any auto-focused Link</a></body></html>";
    browser.setPage(htmlPage, "https://www.link.com");

    f.setLayout(new BorderLayout());
    f.add(BorderLayout.NORTH, new Label("Hello World"));
    f.show();
    
    f.add(BorderLayout.CENTER, browser);
    f.revalidate();
}
````

**Comment by kutoman** [comment]
is there any workaround to this issue, considering that the BrowserComponent has to be added like this? The jumping is pretty annoying and I don't know when the fix will happen on your side.

**Comment by codenameone** [comment]
I'm not sure @shannah were you able to reproduce this?

**Comment by shannah** [comment]
Not yet.  Haven't tried again since the new test case was presented.  Will look again on Monday.
