### ISSUE TITLE
CodenameOne video screenshot

### ISSUE THREAD

**Issue by vidime** [codenameone/CodenameOne#2294]
I need to save a screenshot of video when press a button
this is my code 
Display.getInstance().callSerially(() -> {
                        
                        Image screenshot = Image.createImage(mediaPlayerContainer.getInnerWidth(), mediaPlayerContainer.getInnerHeight());
                        String imageFile = FileSystemStorage.getInstance().getAppHomePath() + "screen.png";
                        mp.getMedia().getVideoComponent().paint(screenshot.getGraphics());
                        try (OutputStream os = Storage.getInstance().createOutputStream(imageFile)) {
                            ImageIO.getImageIO().save(screenshot, os, ImageIO.FORMAT_PNG, 1);
                            scr.setEnabled(true);
                        } catch (IOException err) {

                        }
1)when I list files on Storage ( file not found)
2)if I pass directly Image screenshot to "Label.setIcon" I obtain blank Image.
Everything works perfectly in the simulator

Thank you in advance for the help

**Comment by vidime** [comment]
sorry
mp.paint(screenshot.getGraphics());

**Comment by shannah** [comment]
Unfortunately native components like the video component and browser component can't be rendered to a CN1 graphics pipeline.  The simulator is an exception due to the way it is implemented.
