### ISSUE TITLE
Admob ads version

### ISSUE THREAD

**Issue by maaikez** [codenameone/CodenameOne#2297]
When using admob ads with the googleAdUnitId build hint, it is not clear what the version is of admob. Admob < 7 is deprecated and I get a message from google that I'm using a deprecated version of admob. I can not find anywhere what version is used when building. Can you change the admob version so it uses a version > 7?

**Comment by codenameone** [comment]
Looking at the code it seems that using this build hint pushes the target SDK back to 14 instead of the default 23 (which we should update). I'm not sure what the implications are of removing this restriction. 

I'll add an option to disable that behavior for next weeks update. Try adding `android.targetSDKVersion=23` to the build hints and see if it resolves the issue after next weeks update. Let us know.

**Comment by maaikez** [comment]
Thanks!
How can I see what the admob version is? I only get a message from Admob, but I am sure not everyone will update to the newest version directly, so I don't know how to know which version of Admob is used. I also can not find it in the code.

**Comment by maaikez** [comment]
I just installed the new version (developer build) on ios and I don't see any ads.

**Comment by maaikez** [comment]
I just made a build for ios. I can see an ad when starting the app, but after some clicking, it disappears and there is no ad anymore. I don't know if that is normal behaviour, but at least there was an ad.

**Comment by maaikez** [comment]
On Android it seems to work ok!

**Comment by codenameone** [comment]
So is this working now after the fix?

**Comment by maaikez** [comment]
For Android it is working (and since the old version is now really deprecated, I think I wouldn't see anything if this version was not ok). For ios... I'm not sure. I only see one ad for a short time. But I don't use the device every day, so maybe that's the problem (there is no history on that phone about what I like, maybe that's why they don't serve good ads???).

**Comment by codenameone** [comment]
I've reviewed the code on iOS and there it seems like it's using the latest version. I've now enabled this mode for Android by default so you no longer need to explicitly define the target version so I'm considering this as fixed.
