### ISSUE TITLE
Android's TitleBar is visible

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2299]
I don't know why but my App has been displaying a title bar on Android (7.0) for a few weeks. There is no such bar on the simulator or on iOS. How can I hide it? 
Before my form gets displayed I call `form.getToolbar().setHidden(true);`
  
Strangely the title bar gets hidden after hiding and redisplaying the app.

**Comment by kutoman** [comment]
unfortunately executing  `AndroidNativeUtil.getActivity().requestWindowFeature(Window.FEATURE_NO_TITLE);` also doesn't help

**Comment by codenameone** [comment]
Can you provide a screenshot?
Does a hello world reproduce this issue if not how is your app different from the hello world app?
Which device specifically?

**Comment by kutoman** [comment]
@codenameone 
after some experimenting I found out that this is caused by this code (calling of setTransition for **both** In- and OutAnimator. If one of both invocations is missing the issue can't be reproduced!):

    @Override
    protected void beforeMain(Form f) {
        
        f.setTransitionInAnimator(null); //<---- source of issue
        f.setTransitionOutAnimator(null); //<---- source of issue
        
        f.getToolbar().setHidden(true);
        f.revalidate();
    }
Note: I can't reprocduce this when I create and show a new `From` in code.

For simplicity I used an almost none-populated form (called _Main_) which I created in the old gui builder. The following screen is from a Samsung Galaxy A3 (SM-A320FL).

![androidviewwithtitlebar](https://user-images.githubusercontent.com/5825645/34764343-79c3fe64-f5ee-11e7-9b95-5c87e77aa1ca.png)

**Comment by kutoman** [comment]
this can be fixed when `CommonTransitions.createEmpty()` is used instead of `null`

**Comment by codenameone** [comment]
Instead of setting null try `CommonTransition.createEmpty()`

**Comment by kutoman** [comment]
yeah I did as mentioned before

**Comment by codenameone** [comment]
Try `setVisible(false)` instead of `setHidden()`

**Comment by kutoman** [comment]
The first suggestion already fixed it
