### ISSUE TITLE
Custom background - problems with shape clip+rotate on Android

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#2300]
Hi, I was trying to create a custom BgPainter for a container, I was requested to make a diagonal gradient with rounded corners. After a bit of trial and error the following code did the job perfectly in the simulator:

`

        final int arc = Display.getInstance().convertToPixels(2); // 2 mm
        Style style = customContainer.getAllStyles();
        style.setBorder(Border.createEmpty());
        style.setBgPainter((Graphics g, Rectangle rect) -> {
            if (g.isShapeClipSupported()) {
                GeneralPath clip = new GeneralPath();
                clip.arc(0, 0, arc, arc, Math.PI, -Math.PI/2);
                clip.lineTo(rect.getWidth() - arc, 0);
                clip.arc(rect.getWidth() - arc, 0, arc, arc, Math.PI/2, -Math.PI/2, true);
                clip.lineTo(rect.getWidth(), rect.getHeight() - arc);
                clip.arc(rect.getWidth() - arc, rect.getHeight() - arc, arc, arc, 0, -Math.PI/2, true);
                clip.lineTo(arc, rect.getHeight());
                clip.arc(0, rect.getHeight() - arc, arc, arc, -Math.PI/2, -Math.PI/2, true);
                clip.closePath();
                g.setAntiAliased(true);
                int[] clip1 = g.getClip();
                g.setClip(clip);
                g.clipRect(clip1[0], clip1[1], clip1[2], clip1[3]);
                g.rotate((float) (-Math.PI/4));
                g.fillLinearGradient(0x2979ff, 0x1ea8c9, -rect.getWidth(), -rect.getHeight()/4, rect.getWidth()*2, rect.getHeight()*2, true);
                g.rotate((float) (Math.PI/4));
                g.setClip(clip1);
            }
        });

`
On android it loses itself and breaks the graphics stack completely. I've tried many alternate ways to do the same thing, namely using pushClip and popClip instead of clipRect, setTransform and resetAffine instead of rotate, all worked in the simulator but not in Android. if I don't use the clipRect(inefficient and may display artifacts) AND the rotate(needed as per requested) it draws the gradient with rounded corners as expected.

PS: Not sure how it behaves in iOS, will give it a shot when I have time.

**Comment by codenameone** [comment]
I don't understand why you invoke `clipRect` after `setClip`. You should use `resetAffine` after you finish doing everything to restore everything to the default state.

**Comment by FabricioCabeca** [comment]
Actually at least in the simulator the clipRect is necessary, it concatenates the current clip with the needed shape, if you don't clip it sometimes draws the background over the foreground components, ie.: when you have two buttons in the container and press one of them, the custom background draws over the other button. It may not be needed in Android as the current graphics pipeline works but shouldn't hurt either and may be needed if there are any optimizations like using invalidate() only where needed.

I used the resetAffine just like you mentioned.

Just tested background gradients in iOS and it is even worse, it simply not works and fills white instead. Should I open another issue ?

**Comment by codenameone** [comment]
I don't think this is solvable in the current API. @shannah  correct me if I'm wrong but `clipRect` and `clip(Shape)` don't mesh. We might need a new API to support this sort of use case e.g. `subClip(Shape)`.

But I don't think that would be important... Shape clipping performs badly and produces "subpar" results for the use case you have above. You should use masking which allows you to turn on anti-aliasing and get better edges as a result. That way you can cache the result as an image and after the first hit get great rendering speed.

**Comment by FabricioCabeca** [comment]
Ok, I will try using a mask instead of shape clipping.

Without shape clipping the diagonal gradient works in Android.

The linear gradients are still a problem however in iOS, it is completely broken. I've just opened #2305

**Comment by shannah** [comment]
This should be fixed now as part of https://github.com/codenameone/CodenameOne/issues/2567
