### ISSUE TITLE
Kotlin: Dependent Objects include the StackTraceElement class

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2303]
Using dependent objects doesn't work as expected when building for iOS. It produces this error:

````
/var/folders/p7/d3z112yd0156kxkm2p21p8ym0000gn/T/build1246651821544689261xxx/dist/KotlinDemo-src/kotlin_jvm_internal_Intrinsics.m:4:10: fatal error: 'java_lang_StackTraceElement.h' file not found
#include "java_lang_StackTraceElement.h"
         ^
1 error generated.

** ARCHIVE FAILED **
````

Test case:

````kotlin
open class KotlinDemo {

    private var current: Form? = null
    private var theme: Resources? = null

    fun init(context: Any?) {
        theme = UIManager.initFirstTheme("/theme")

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true)

        // Pro only feature
        Log.bindCrashProtection(true)
    }

    fun start() {
        if (current != null) {
            current!!.show()
            return
        }
        val hi = Form("Hi World", BoxLayout.y())
        hi.add(Label("Hi World"))
        hi.show()
        Log.p(O.test);
    }

    fun stop() {
        current = getCurrentForm()
        if (current is Dialog) {
            (current as Dialog).dispose()
            current = getCurrentForm()
        }
    }

    fun destroy() {
    }

    object O {
        val test = "m"
    }
}
````

**Comment by comdori** [comment]
Hi  @shannah fantastic news that you have a fix for this! Does your fix also work when the object definition is at the top level and contains a val?

In my kotlin project i have a compile error in ios build for every val in every object

**Comment by shannah** [comment]
This is my test case:

~~~~
package com.codename1.hellokotlin2

import com.codename1.io.Log
import com.codename1.ui.Button
import com.codename1.ui.Form
import com.codename1.ui.Label
import com.codename1.ui.layouts.BoxLayout

/**
 * Created by shannah on 2017-07-10.
 */
class KotlinForm : Form {

    constructor() : super("Hello Kotlin", BoxLayout.y()) {
        val label = Label("Hello Kotlin")
        val clickMe = Button("Click Me")
        clickMe.addActionListener {
            label.setText("You Clicked Me");
            revalidate();
        }

        add(label).add(clickMe);
        Log.p(O.test);

    }


    object O {
        val test = "m";
    }
}
~~~~

So, Yes I believe it does

**Comment by comdori** [comment]
The two other cases i have seen errors on are

class KotlinForm : Form {

    constructor() : super("Hello Kotlin", BoxLayout.y()) {
        val label = Label("Hello Kotlin")
        val clickMe = Button("Click Me")
        clickMe.addActionListener {
            label.setText("You Clicked Me");
            revalidate();
        }

        add(label).add(clickMe);
        Log.p(O.test);

    }
}

object O {
        val test = "m";
    }

... and ...
class KotlinForm : Form {

    constructor() : super("Hello Kotlin", BoxLayout.y()) {
        val label = Label("Hello Kotlin")
        val clickMe = Button("Click Me")
        clickMe.addActionListener {
            label.setText("You Clicked Me");
            revalidate();
        }

        add(label).add(clickMe);
        Log.p(Testy.label);

    }
}

class Testy{
  companion object {
    val label= "myLabel"
  }
}
