### ISSUE TITLE
Swipeable Container stopping at half way closed

### ISSUE THREAD

**Issue by kazza186** [codenameone/CodenameOne#2308]
Swipeable Container can now be left in a half closed position. This then messes up the display and allows for swiping to a side that has no bottom element. 

Code that was last built in June 30th 2017 doesn't have this issue. First noticed this issue in November 2017

**Comment by codenameone** [comment]
@shannah I was able to reproduce this in the simulator a while back although it took several repeated attempts to do so. Would you have time to look at this in the 4.0 cycle (assuming 2 week delay)?
