### ISSUE TITLE
iOS compile error from kotlin codebase

### ISSUE THREAD

**Issue by comdori** [codenameone/CodenameOne#2314]
I have the following error in an iOS build of a Kotlin codebase - the error is on the Kotlin Collection library classes

/var/folders/p7/d3z112yd0156kxkm2p21p8ym0000gn/T/build4270066954435369931xxx/dist/Time2Math-src/kotlin_collections_CollectionsKt__CollectionsKt.m:257:32: error: implicit declaration of function 'java_util_Arrays_copyOf___java_lang_Object_1ARRAY_int_java_lang_Class_R_java_lang_Object_1ARRAY' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    /* CustomInvoke */PUSH_OBJ(java_util_Arrays_copyOf___java_lang_Object_1ARRAY_int_java_lang_Class_R_java_lang_Object_1ARRAY(threadStateData, locals[0].data.o, CN1_ARRAY_LENGTH(locals[0].data.o), (JAVA_OBJECT)&class_array1__java_lang_Object));

cno build 203

IntelliJ IDEA 2017.3.3 (Community Edition)
Build #IC-173.4301.25, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by shannah** [comment]
Can you provide a test case?  I've tried a few things with Kotlin involving collections, but can't seem to produce a test that results in the kotlin.collections.CollectionsKt class from being made part of the build (That is the class that produces the error).

**Comment by comdori** [comment]
Shai emailed to say he knew what the issue was and asked me to open this issue. It's hard for me to produce a test case for this as I can't tell from the build log which bit of my codebase is including this part of the kotlin library.  Is there a trick to trace back the imports?

**Comment by shannah** [comment]
I have managed to reproduce it.  Test cases are generally helpful though as without a test case there's no way of know if this is the only error that the test case will produce, or if it is just the first in a series.

**Comment by comdori** [comment]
Totally agree on test cases and I spent a couple of hours trying to do that today before crying and asking for help :) Fantastic that you found a repro - can you share maybe i can locate where in my codebase this creeping in and put a work around
