### ISSUE TITLE
Really annoying that Container hierarchy collapses / folds when placing a Component in it

### ISSUE THREAD

**Issue by seinecle** [codenameone/CodenameOne#2316]
The view in the top left panel of the GUI Builder shows Components and Containers.

When using the arrows to move up a Component so that it gets placed inside the Container situated just above, this action folds the content of the Container. One has to expand again the content of the Container to find the Component and use it again (typically to move it up again because we need to do it step by step).

Solution: keep the Container's content open when a Component is moved into it.

**Comment by codenameone** [comment]
This is happening only in the old layout mode right?

**Comment by seinecle** [comment]
No I just tested the following in a Form in the autolayout mode:

- create a Container and set it to a Border layout
- add 5 Labels in it
- select a Label in the top left panel, click on the arrow to move it up
- it folds the Container, have to re-click on it to see the result of my action

**Comment by shannah** [comment]
Note:  This behaviour started happening after this commit:
https://github.com/codenameone/CodenameOne/commit/37d25af76dd1f68f9bcf9444ec95cd00ea8a4163#diff-c1ec0a7a8fa1ad7030aed900493b8092

I have taken a couple of stabs at fixing this in the past, but haven't been successful.

**Comment by codenameone** [comment]
Wasn't that commit the one that fixed this in a previous regression?
The issue sounds like a bug in the arrow code. No?

**Comment by shannah** [comment]
No.  It was to fix this issue:
https://stackoverflow.com/questions/43788002/codename-tree-component-collapse-method-null-pointer-exception/43817090

We have a short discussion about this on the commit itself.
https://github.com/codenameone/CodenameOne/commit/37d25af76dd1f68f9bcf9444ec95cd00ea8a4163#diff-c1ec0a7a8fa1ad7030aed900493b8092

**Comment by codenameone** [comment]
Yes but there was a fix for that later in the GUI builder code that addressed that issue and it worked after that.

**Comment by shannah** [comment]
I never recall it ever working after this.  Though I made several attempts.  Some of the attempts I made mitigated it a little bit, but never fixed it.

**Comment by jegesh** [comment]
+1
