### ISSUE TITLE
AutoCompleteTextField prints wrong value in the simulator

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2318]
This seems to be a regression related to text input:

````java
Form hi = new Form("Hi World", BoxLayout.y());
String[] l =  new String[]{"aaa", "bbb", "ccc", "ddd", "eee"};
AutoCompleteTextField ac = new AutoCompleteTextField(l);
ac.addActionListener((e) -> {
    System.out.println("T: " + ac.getText());
});

hi.add(ac);
hi.show();
````

- Click in the field
- Select `aaa`

The field will be `aaa` but the printout is `T:`.

The action event is invoked once by the synchronous editing code which completes when the popup is clicked and has no text yet. When the selection is made the action event isn't fired for some reason.

**Comment by shannah** [comment]
I'd be surprised if that ever worked.  The actionEvent is likely firing when the text field loses focus by clicking on the drop-down list.  After selecting the item in the drop down list will trigger an event to the list listener (AutoCompleteTextField.addListListener()), but not to the action listeners of the text field.

**Comment by shannah** [comment]
It would be easy to make it fire two action events in this case - the first one with the field value prior to selecting an option in the autocomplete list - and the second one with the value after selecting the option in autocomplete.  Making it fire just one action event (after selecting the option) would be trickier ... high probability of causing regressions if not done *very* carefully.

**Comment by codenameone** [comment]
I can live with that. The class needs a rewrite at some point anyway so a smaller fix would be better.
