### ISSUE TITLE
Swipe and Scroll clash

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2321]
As far as I could see in common UI's, the UI is reacting either on a swipe or scroll action (not both at the same time). But if we use a vertically scrollable page in a `Tabs` component, in which swipe is activated, both actions are clashing. This is bad for UX imho.

            List<Component> listItems = new ArrayList<>();
            for(int i = 0; i < 20; i++) listItems.add(new Label("ITEM " + i));
            
            Container first = BoxLayout.encloseY(listItems.toArray(new Component[listItems.size()]));
            first.setScrollableY(true);
            Container second = BoxLayout.encloseX(new Label("Page"));
            
            Tabs tabs = new Tabs();
            tabs.addTab("1", first);
            tabs.addTab("2", second);
            tabs.setSwipeActivated(true);
            
            
            Form form = new Form(new BorderLayout());
            form.add(BorderLayout.CENTER, tabs);

            form.getToolbar().setHidden(true);
            form.show();

**Comment by codenameone** [comment]
You should disable the side swipe if your page is scrollable on the y axis.
We have some protections in place but there is a limit to what can be done without making scroll feel stunted.

**Comment by kutoman** [comment]
so you suggest not to support swipe in those cases? How about extending the api by swipe/scroll action listening. Thus we could disable the Tabs swipe (or the pages scroll) when a scroll (swipe) begins and enable it when it ends. Currently, swipe listening is not available and the scroll listener only receives scroll value changes.

**Comment by codenameone** [comment]
We already have bias code within the implementation but its effectiveness isn't great. I would suggest disabling that.

**Comment by kutoman** [comment]
hmm ok
