### ISSUE TITLE
Integer property saved as Null in SQLite database

### ISSUE THREAD

**Issue by IntraCherche** [codenameone/CodenameOne#2324]
## How to reproduce the issue :
1. Create an Integer Property 
    public final Property<Integer, Report> integerProp = new Property<>("integerProp", 0);
2. Set it with the data received from server as Double
     tempReport.integerProp.set(((Double) tempTable.get("integerProp")).intValue());
3. Add the object to the database
    LocalDatabase.getInstance().insert(tempReport);
with insert() calling directly smap.insert(object) with smap = SQLMap.create(db);

## Expected result
The local database should be populated with an entry which column "integerProp" has either 1 or 0 depending on what is received at step 2.

## Actual result
The local database gets populated with an entry which column "integerProp" has Null.

## Workaround
Instead of using an Integer Property use a Long Property (at step 2. use longValue()). In this case the database gets populated with 1 or 0 as expected.

**Comment by codenameone** [comment]
I just tried this using the following test case:

````java
try {
    Database db = Database.openOrCreate("bla");
    SQLMap map = SQLMap.create(db);
    map.createTable(new BusinessObjectTest());
    map.insert(new BusinessObjectTest().integerProp.set(2).integerProp2.set(3));
} catch(Exception err) {
    Log.e(err);
}
````

````java
public class BusinessObjectTest implements PropertyBusinessObject {
    public final Property<Integer, BusinessObjectTest> integerProp = new Property<>("integerProp", 0);
    public final IntProperty<BusinessObjectTest> integerProp2 = new IntProperty<>("integerProp2", 0);
    
    private PropertyIndex idx = new PropertyIndex(this, "BusinessObjectTest", integerProp, integerProp2);

    @Override
    public PropertyIndex getPropertyIndex() {
        return idx;
    }
}
````

This generated the correct data into the database when viewed later. I'm guessing this was resolved by one of the commits performed since the issue was submitted.
