### ISSUE TITLE
isGpsEnabled method issue in android

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#2328]
Though location is on (but "battery saving mode" or "wifi or cellular networks mode" is selected in location setting), it gives false.

![jcdmc](https://user-images.githubusercontent.com/13558880/36015505-d0d27fd6-0d96-11e8-8a1f-e8595ce69ff3.png)

**Comment by shannah** [comment]
A couple of things to check here.

1. Check Location > App-level permissions to make sure that the application is allowed to use location services.
2. Make sure that you have location play services enabled.  I.e. the build hint `android.playService.location` should be "true"

It would also help if you provided a test case, as the issue could be related to *when* the method is called.

**Comment by shannah** [comment]
Moved to 6.0 while awaiting feedback from OP to see if the [suggestions](https://github.com/codenameone/CodenameOne/issues/2328#issuecomment-414393000) fix the issue.

**Comment by shannah** [comment]
Closing issue, as I haven't received feedback from OP.   Will reopen if I receive more information.
