### ISSUE TITLE
Scroll not working properly in a scrollable grandchild of a LayeredLayout

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2329]
it's reacting as if the content does not need to be scrolled.

sample:

        Form form = new Form(new LayeredLayout());
        
        List<Component> listItems = new ArrayList<>();
        for(int i = 0; i < 20; i++) listItems.add(new Label("ITEM " + i));
        Container scrollable = BoxLayout.encloseY(listItems.toArray(new Component[listItems.size()]));
        scrollable.setScrollableY(true);
        
        LayeredLayout layout = (LayeredLayout) form.getLayout();
        
        Container top = BorderLayout.center(scrollable);
        form.add(new Container());
        form.add(top);
        
        layout.setInsets(top, "0");
        
        form.show();

**Comment by shannah** [comment]
Just tried your example and it is working for me.

**Comment by kutoman** [comment]
hmm that's weird. This is what happens to me (Note: I'm not scrolling back, it's tensile dragging which shouldn't happen):

![scrollssuell](https://user-images.githubusercontent.com/5825645/36029784-e45a59d0-0da4-11e8-9c24-d21490dd03fe.gif)

**Comment by shannah** [comment]
OK.  I have reproduced it.  Happens in portait mode with 3GS skin.  Not in Nexus 5 skin in landscape mode (which I was trying before).

**Comment by codenameone** [comment]
You have nested scrollables since the forms content pane is scrollable by default. `LayeredLayout` doesn't disable scrolling automatically like `BorderLayout`. So to get this to work you need to explicitly disable scrolling on the layered layout:

````java
form.setScrollableY(false);
````
