### ISSUE TITLE
RFE: TextField display issue in Codenameone when text is larger than the TextField area

### ISSUE THREAD

**Issue by elie7** [codenameone/CodenameOne#2330]
You can reproduce this issue per this Stackoverflow discussion:
https://stackoverflow.com/questions/48727587/textfield-display-issue-in-codenameone-when-text-is-larger-than-the-textfield-ar

Basically, whenever text is larger than the textfield, the text is displayed starting from somewhere in the middle till the end making it easy to lose context from a user's perspective.

**Comment by 3lix** [comment]
Hello, this issue is broken again. You can test with the following code
```
 Form hi = new Form("Hi World", BoxLayout.y());
 hi.add(new Label("Hi World"));
 hi.add(new TextField("A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"));
 hi.show();
```
