### ISSUE TITLE
[BUG] String Picker bugged on iPhone 6S (iOS v.9) and iPhone 6 (iOS v. 8)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2331]
The following code runs correctly on iPhone X, iPhone 8, iPhone 8 Plus, iPhone SE, iPhone 7... but it doesn't run on iPhone 6S (iOS v.9) and iPhone 6 (iOS v. 8), because the string Picker doesn't open. Could you check it, please? Thank you

        Form hi = new Form("Hi World", BoxLayout.y());
        Picker languagePicker = new Picker();
        languagePicker.setType(Display.PICKER_TYPE_STRINGS);
        languagePicker.setStrings("Italian", "English", "German");
        languagePicker.setSelectedString("English");
        languagePicker.addActionListener((ev) -> {
            String newLanguage = languagePicker.getSelectedString();
            if (newLanguage != null && newLanguage.length() > 0) {
                Log.p("Language selected: " + newLanguage);
            }
        });
        hi.add(languagePicker);
        hi.show();
    }

**Comment by codenameone** [comment]
@shannah I'm just assigning it for evaluation on 4.0 it's your call when to address this.

**Comment by shannah** [comment]
Cannot reproduce on iPhone 4S running iOS 9.0 (actual device) or on Xcode simulator iPhone 6 (iOS 8).  Test case runs fine.  I don't have an actual iPhone 6 or 6S so I can't test on the exact specifications listed in this issue.

**Comment by jsfan3** [comment]
I've done the test and I reproduced the error in the Browser Stack App Live real device farm:
[https://www.browserstack.com/app-live](https://www.browserstack.com/app-live)

**Comment by codenameone** [comment]
I have an iPhone 6. I'll try and test it

**Comment by codenameone** [comment]
Works fine on my iPhone 6 iOS 11.

**Comment by jsfan3** [comment]
Thank you both for your tests. My issue, however, is with iPhone 6S (iOS v.9) and iPhone 6 (iOS v. 8). The issue is the same using or not the build hint ios.xcode_version=9.2

I tried to replace the native picker with a popup dialog: also in this case, the issue is present, because the dialog doesn't open and the app is fridged.

Of course I can suppose that this issue is strictly related to the devices of the device farm that I'm using (because I haven't an actual iPhone). Maybe we can keep this issue open until we will have more infos.

**Comment by codenameone** [comment]
I don't know if there is a problem with the issue, the device farm or the iOS version. Lets guess the worst thing that we have a bug/regression on iOS 8. 

Based on this chart: https://developer.apple.com/support/app-store/ only 7% of iOS devices use an OS prior to 10. So it's probably not a big deal. 

In the long term I'd love to kick picker out, I think we need a lightweight picker API but that would take some effort and we don't have the resources for it at this time.

**Comment by jsfan3** [comment]
Ok, thank you for the explanation :)

**Comment by shannah** [comment]
Moved to 6.0 milestone.  I cannot reproduce this on any of my devices, nor in the Xcode simulator running the same device/versions as listed in the issue.

Additionally, the fact that the issue even occurs without the Picker (https://github.com/codenameone/CodenameOne/issues/2331#issuecomment-367292851), is suspicious.   Would be helpful to see the device log when this issue occurs.  Otherwise I don't have any pathways to proceed on this.

**Comment by jsfan3** [comment]
Thank you for the time you spent investigating this issue.
Your last comment gave me another information to be convinced that this issue is a problem of the Browser Stack App Live device farm, not a problem on real devices. Moreover, I abandoned that device farm a while ago because I found other (fake) issues that don't reproduce on my real iPhone X.
That's why we can close this issue.
