### ISSUE TITLE
Network errors on 3.8 and latest CN1, when 2 character YY cookie expirations.

### ISSUE THREAD

**Issue by samlotti2** [codenameone/CodenameOne#2332]
I've determined this issue was cookie being returned with expires as: 
Expires=Wed, 14-Feb-18 03:13:52 GMT
instead of:
Expires=Wed, 14-Feb-2018 03:13:52 GMT

I can now access the server without errors when I set:
request.setCookiesEnabled(false);

This is a regression from 3.7 and prior.

It appears in 3.8

=== ConcurrentModificationException stack trace.
java.util.ConcurrentModificationException
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1378)
	at com.codename1.impl.CodenameOneImplementation.purgeOldCookies(CodenameOneImplementation.java:4171)
	at com.codename1.impl.CodenameOneImplementation.addCookie(CodenameOneImplementation.java:4208)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:713)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

Note: That you will see the when using the Rest version of the call:
            Response<String> asString = Rest.get(url).getAsString();

====

===

-----

Previous:
I get networks errors most frequently on the mobile device to the point where the app is not usable.  I have been able to reproduce this in the simulator.  For the simulator is is not as frequent but will appear.  

Attached are 2 java files to be placed in a new hello world CN1 application.
Run the application (make sure you have latest and updated the project libs.  Then press the 'Click Me to test' to test button.  You will see the console output and should get an error. Sometimes right away, sometimes after a some calls.  The button with loop for 100 calls to the server.

Now change the version to 3.7 or any earlier.  Refresh the libs and you should be able to hit the start button as many times as you want without any errors.

On my mobile device and watching the server log files it looks like the device shows the error without making the call, but when it close the dialog I then see the server get accessed (at this point its too late for the app to use it.  So i get the feeling theres some race or setting that is causing it to immediately fail without actually performing the network operation.
 
Please note this application and my others have been working fine for years and its this latest build that is causing my issues.   The test case has not real business logic from my app.

[myapp.zip](https://github.com/codenameone/CodenameOne/files/1720017/myapp.zip)

![screen shot 2018-02-13 at 8 25 52 am](https://user-images.githubusercontent.com/12683767/36152056-9ac7f0ca-1097-11e8-9b92-37fa953aa98d.png)

=== ConcurrentModificationException stack trace.
java.util.ConcurrentModificationException
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1378)
	at com.codename1.impl.CodenameOneImplementation.purgeOldCookies(CodenameOneImplementation.java:4171)
	at com.codename1.impl.CodenameOneImplementation.addCookie(CodenameOneImplementation.java:4208)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:713)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by codenameone** [comment]
Thanks!
FYI the link to the discussion is here: https://stackoverflow.com/questions/48732900/network-errors-recent-build-about-75-of-time

You also mentioned a `ConcurrentModificationException` can you get the stack for that?

**Comment by samlotti2** [comment]
I added the stack trace and a note that the CME will appear when using the Rest version instead of the ConnectionRequest.

I added in the doGet:
   if ( 1 == 1 ){
            Response<String> asString = Rest.get(url).getAsString();
            Log.p("Response str:" + asString.getResponseData() );
            return 1;
        }

**Comment by samlotti2** [comment]
Hi Shannah, Did you verify the test program works after these changes?  Just want to make sure it fixes the issue I was having.

**Comment by shannah** [comment]
This is the test case that passes:

~~~~
public int doGet(final String url, TextArea output) {

        if (Display.getInstance().isEdt()) {
            Log.p("*** Performing a GET network call on the EDT");
        }

        final ConnectionRequest request = new ConnectionRequest() {
            @Override
            protected void handleException(Exception err) {
                if (Dialog.show("Connection error",
                        "Check your internet connection", "Retry", "Exit")) {
                    Display.getInstance().exitApplication();
                } else {
                    retry();
                }
            }
        };

        request.setUrl(url);
        request.setPost(false);
        request.setFollowRedirects(false);
        request.setReadResponseForErrors(true);
        request.setSilentRetryCount(1);

        request.addResponseCodeListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Log.p("Response code ResponseCodeListener, setting to -1");
                responseCode = -1;
            }
        });
        request.addResponseListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                Log.p("Response listener action for GET performed ");
                ConnectionRequest cr = (ConnectionRequest) evt.getSource();
                responseCode = cr.getResponseCode();
                Log.p("Response listener action for GET performed: " + cr.getResponseCode());
                if (cr.getResponseCode() == 200) {
                    responseData = new String(cr.getResponseData());
                } else {
                    Log.p("Response code: " + cr.getResponseCode() + " of " + cr.getUrl());
                }
            }
        });
        // request will be handled asynchronously
        NetworkManager.getInstance().setTimeout(15000);

        synchronized (lock) {
            depth++;
        }
        try {
            request.setDuplicateSupported(true);
            NetworkManager.getInstance().addToQueueAndWait(request);
        } finally {
            synchronized (lock) {
                depth--;
            }
        }

        Log.p("Response: "+responseCode+" "+responseData);
        output.setText("Response: "+responseCode+" "+responseData);
        return responseCode;
    }
    
    private void testDoGet2332() {
        Form f = new Form("Test 2332", new BorderLayout());
        TextArea ta = new TextArea();
        Button b = new Button("Run Test");
        b.addActionListener(e->{
            doGet("http://server.wordtimelive.xyz/jgame/game/6647?tkn=08F0D0B4E7EE80370B982DBEA261500ADB53266C1847175152-1461100", ta);
        });
        f.add(BorderLayout.NORTH, b);
        f.add(BorderLayout.CENTER, ta);
        f.show();
    }
~~~~
