### ISSUE TITLE
[BUG] Translated Clip on iOS is not working

### ISSUE THREAD

**Issue by Adalbert393** [codenameone/CodenameOne#2335]
During of trying to run my software in a newer version of the CN1, I found that on iOS from version 3.6 practically ceased to operate the limitation of the drawing area (Clip) if at the same time the transformation is performed.
To enable quick removal of the bug I prepared a sample test program.
Below screenshots for the CN1 and XCode iOS simulators.
1. For 0 degree rotation
![codenameone screenshot 10](https://user-images.githubusercontent.com/18614910/36171111-aec43876-1101-11e8-8765-edbd68c03cd4.png)
![simulator screen shot - iphone 6 - 2018-02-13 at 18 37 29](https://user-images.githubusercontent.com/18614910/36171152-cc755e86-1101-11e8-84e8-c6779fced64b.png)
2. For 60 degree rotation
![codenameone screenshot 9](https://user-images.githubusercontent.com/18614910/36171178-ec1d2336-1101-11e8-9b9a-28f119c6a93c.png)
![simulator screen shot - iphone 6 - 2018-02-13 at 18 39 23](https://user-images.githubusercontent.com/18614910/36171184-ef7ef3e2-1101-11e8-9280-0354d35d3879.png)

So how you can see:
1. On iOs Clip is not working 
2. After a few step (120 degree) painting on iOS hangup
3. If you remove t.translate(this.getWidth() / 2, this.getHeight() / 2) Clip is working much better but still after a few step some errors stop the program.

The sample code:
```
  public void start() {
		if (current != null) {
			current.show();
			return;
		}

		Image duke = theme.getImage("duke-no-logos.png");
		MyCanvas c = new MyCanvas();
		c.show();

		new UITimer(() -> {
			c.repaint();
		}).schedule(2200, true, c);
	}
//-----
public class MyCanvas extends Form {

	float a = -30;

	public MyCanvas() {
		super();
	}

	public void paint(Graphics g) {

		g.setTransform(Transform.IDENTITY());

		g.setColor(0x000000);
		g.setClip(0, 0, 3000, 3000);
		g.fillRect(0, 0, this.getWidth(), this.getHeight());

		g.setColor(0x00a000);
		g.setFont(Font.createSystemFont(Font.FACE_MONOSPACE, Font.STYLE_BOLD, 20));
		g.drawString("iOS Clip issue. Angle:" + a, 10, 20);

		g.setColor(0x404040);
		Transform t = Transform.makeIdentity();
		t.translate(this.getWidth() / 2, this.getHeight() / 2);
		t.rotate((float) (a / 180 * Math.PI), 0, 0);

		g.setTransform(t);
		g.drawArc(-100, -100, 200, 200, 0, 360);
		g.setColor(0x770000);
		g.setClip(100, -15, 30, 30);
		g.fillRect(-100, -100, this.getWidth(), this.getHeight());
		g.setColor(0x007700);
		g.setClip(150, -15, 30, 30);
		g.fillRect(-100, -100, this.getWidth(), this.getHeight());
		a += 30;

	}
}

```

**Comment by codenameone** [comment]
I've assigned this to 5.0 tentatively as 4.0 is already overbooked.
