### ISSUE TITLE
Android build error when using Admob and google-services.json

### ISSUE THREAD

**Issue by samlotti2** [codenameone/CodenameOne#2337]
Created a new hello world app, set it to 3.8. 
Added google-services.json in the android directory. 
Opened the properties and added android.googleAdUnitId=myid. 
This still gets the 'com.google.android.gms.ads' error. Removing 
either one will work. But they do not work together. 

Reference:
https://stackoverflow.com/questions/48717367/android-build-error-with-admob-plugin/48728449?noredirect=1#comment84561866_48728449

**Comment by shannah** [comment]
Fixed https://github.com/codenameone/BuildDaemon/commit/103cc652437387b504071c64fef1fa946ff64ea8
