### ISSUE TITLE
[BUG] Exception on trying to update Codename One Libs

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2341]
I've read the post about the new update framework:
[https://www.codenameone.com/blog/new-update-framework.html](https://www.codenameone.com/blog/new-update-framework.html)

1. In "Codename One Settings → Basic" there is no option "Update Client Libs" but only "Update Project Libs"

2. Clicking on "Update Project Libs" I get this java exception (it's a screenshot, because I cannot copy and paste): [https://snag.gy/LFrBJP.jpg](https://snag.gy/LFrBJP.jpg)

Tested on Win8, Netbeans 8.2, Codename One plugin 3.8.3

**Comment by codenameone** [comment]
Should be fixed right now please try again.

**Comment by jsfan3** [comment]
Ok, now I completed the update, even if there is a warning: [https://snag.gy/LKJgiX.jpg](https://snag.gy/LKJgiX.jpg)

It's unclear to me if I have to manually check if there are new updates from time to time or not.
