### ISSUE TITLE
[BUG] Last update of Codename One Designer fails to open correctly themes

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2342]
In my project I have three themes at the moment. In future I'll probably have more themes.

The problem is that the last update of the Codename One Designer fails to open a theme if I previously opened other two themes.

I have these themes: "FirsrForm", "iOSTheme" and "Theme".
If I open the "theme.res" (that contains the above three themes) and I click on "FirstForm", I see the styles of "FirsrForm"... then if I click on "iOSTheme" I see the styles of "iOSTheme", **BUT if finally I click "Theme" there is something strange... the "iOSTheme" and the "Theme" are _both selected_ and I don't see correctly the styles (I see only some of them). If I reduce to icon the "Codename One Designer" and I reopen it, the graphics is rendered only where I move the mouse.** 

Maybe the last update of the Codename One Designer have issues if there are more themes?

I also experienced that the bug [https://github.com/codenameone/CodenameOne/issues/2338](https://github.com/codenameone/CodenameOne/issues/2338) still exists.

Tested on Windows 8 with Netbeans 8.2 after the update, as reported in [https://github.com/codenameone/CodenameOne/issues/2341](https://github.com/codenameone/CodenameOne/issues/2341)

**Comment by codenameone** [comment]
I need the output as explained here: https://www.codenameone.com/blog/tip-track-designer-guibuilder-issues.html

**Comment by jsfan3** [comment]
OK! I executed the following command:
`C:\Users\Francesco\.codenameone>java -jar designer_1.jar "C:\Users\Francesco\Documents\NetBeansProjects\Teammate\src\theme.res"> designerLog.txt 2>&1`

In the log there is a java.lang.ClassCastException that is thrown following the previously described steps, exactly when I wrote: _"BUT if finally I click "Theme" there is something strange"_ (see above).

I attach the [designerLog.txt](https://github.com/codenameone/CodenameOne/files/1733957/designerLog.txt) and the [theme.xml](https://github.com/codenameone/CodenameOne/files/1733958/theme.xml.txt)

**Comment by codenameone** [comment]
This should be fixed if you do an update again. It looks like the RoundBorder and RoundRectBorder collided with one another.

**Comment by jsfan3** [comment]
I confirm that your last update solved this issue.
