### ISSUE TITLE
[BUG] Black window below the Codename One Designer

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2343]
In the last updates of the Codename One Designer, I have a black window below it, please see this screenshot: https://snag.gy/QvT5rR.jpg

This issue is the same opening the Designer from Netbeans or opening it from the command prompt with` java -jar designer_1.jar theme.res`

It's not a real problem because the Designer is usable, however it's strange...

This is the log:

```
feb 18, 2018 1:05:48 PM java.util.prefs.WindowsPreferences <init>
AVVERTENZA: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2018-02-18 13:05:49.432:INFO:oejs.Server:jetty-8.0.y.z-SNAPSHOT
feb 18, 2018 1:05:49 PM org.jdesktop.application.LocalStorage getId
AVVERTENZA: unspecified resource Application.id using ResourceEditorApp
feb 18, 2018 1:05:49 PM org.jdesktop.application.LocalStorage getId
AVVERTENZA: unspecified resource Application.vendorId using UnknownApplicationVendor
2018-02-18 13:05:49.569:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9000 STARTING

```

**Comment by codenameone** [comment]
In which IDE?
Does that happen when you launch Codename One Settings too?
Is this a command window that happens when java.exe is used instead of javaw.exe or is this something else?

**Comment by jsfan3** [comment]
Netbeans IDE.
No, it doesn't happen when I launch Codename One Settings.

If I use "java" or "javaw" the issue is the same.

**Comment by codenameone** [comment]
I meant is this a CMD window or is it a blank black window that seems unrelated to anything? Can you grab a shot of the window itself?

**Comment by jsfan3** [comment]
It was a blank black window, however today this issue disappeared :)
Maybe an update solved it.

I close this issue.
