### ISSUE TITLE
Editable vertical Slider thumb gets hidden

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2344]
The thumb interaction does not work properly. Actually I'm not sure if it's made on purpose but the thumb never gets painted at the bottom border (see the following sample). Neither on `progress == 0` nor on `progress == 1`.
I tested on the simulator (iphone3gs)

        Form form = new Form(new BorderLayout());
        Slider vSlider = new Slider();
        vSlider.setUIID("ToastBar");
        vSlider.setVertical(true);
        vSlider.setEditable(true);
        vSlider.setThumbImage(Image.createImage(10, 30, ColorUtil.WHITE));
        vSlider.setProgress(1);
        vSlider.setMinValue(0);
        vSlider.setMaxValue(5);
        vSlider.setIncrements(1);
        
        vSlider.addDataChangedListener((type, index) -> {
            System.out.println("type: " + type + " " + index);
        });
        
        form.add(BorderLayout.WEST, vSlider);
        
        form.show();

**Comment by codenameone** [comment]
Can you provide a screenshot to illustrate this?

**Comment by kutoman** [comment]
or even a screen recording :)

![thumbgetsmissing](https://user-images.githubusercontent.com/5825645/36413173-8d999bde-161d-11e8-883a-43c52d53b344.gif)
