### ISSUE TITLE
Pull to refresh needs some adjustments

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#2346]
I'm using pull to refresh which works most fo the time but it often goes down way too far with no refresh action.

https://www.youtube.com/watch?v=LXm_uEBOygs

```
    Form hi = new Form("Pull"); 

    hi.getContentPane().addPullToRefresh(() -> {
        hi.add(new Button("Pulled!"));
        hi.revalidate();
    });

    hi.show();
```

**Comment by codenameone** [comment]
Fixed by https://github.com/codenameone/CodenameOne/pull/2348

**Comment by codenameone** [comment]
Too many issues open...

**Comment by codenameone** [comment]
I think Steve fixed this a while back if I recall correctly. Is this still happening?
