### ISSUE TITLE
App icon size no longer accepted on Xcode 9.2 builds

### ISSUE THREAD

**Issue by Wookie1** [codenameone/CodenameOne#2347]
App upload with Xcode 9.2 build is rejected because app icon now needs to be 1024x1024, CN1 settings only allows a 512x512 image to be set as app icon.

**Comment by codenameone** [comment]
We support 1024 icons but that sounds like the icon size icon in itunes connect where you should indeed submit a 1024 icon unrelated to the one used in the build. If you have a screenshot of the error I can confirm it.

**Comment by codenameone** [comment]
OK this should be fixed by this commit already on the build servers https://github.com/codenameone/CodenameOne/commit/d68c7e37b1142707b357d54fbfdd268101ad885c
