### ISSUE TITLE
Black screen when starting app on Android

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2349]
this have been happening since last CN1 update. 
Android: 7.0
Device: Samsung Galaxy A3

(No such issue on iOs or simulator)

**Comment by codenameone** [comment]
Is it possible you are invoking Log.sendLog() or similar API?
This PR caused a regression with that https://github.com/codenameone/CodenameOne/pull/2336

**Comment by kutoman** [comment]
no nothing alike. I only have a custom `sendLog` method which handsovers the log to the native email client by `Display.getInstance().sendMessage`. But I implented this months ago.

**Comment by codenameone** [comment]
Has this started working with latest builds? We pushed out a fix for that regression.
If not please connect a cable and look at the DDMS logs to see if there are exceptions or printouts.

**Comment by kutoman** [comment]
yes this solved it, thanks
