### ISSUE TITLE
Focus behaviour in textArea

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#2353]
I have a textArea which works alright. I've a minor issue here. As soon as there is focus in the textArea, there is no text cursor blinking. It seems like the app hangs here. I've to touch the outside of the textArea and click it again to make it work. And when the other component is touched the keypad stays as before. In the second try only does the textArea has blinking text cursor. However text area still works. Just the cursor isn't blinking which is making the users get confused and they complain the app is not working 

Have a look at the video [here](https://youtu.be/Qfdv8YtDqU4).

````
public Booking(Resources res) {
    super(new BorderLayout());
    Container mainContainer = new Container(new BoxLayout(BoxLayout.Y_AXIS));
    mainContainer.setScrollableY(true);

    Label datePickerIconLabel = new Label(addIcon);

    Picker datePicker = new Picker();
    datePicker.setUIID("small");
    datePicker.setType(Display.PICKER_TYPE_DATE);
    Container datePickerContainer = BoxLayout.encloseX(datePickerIconLabel, datePicker);
    mainContainer.add(datePickerContainer);

    TextArea remarksArea = new TextArea();
    remarksArea.setUIID("TextField");
    remarksArea.setConstraint(TextField.NON_PREDICTIVE);
    remarksArea.setRows(4);
    remarksArea.getAllStyles().setAlignment(Label.TOP);
    remarksArea.setHint("  Remarks");
    remarksArea.getHintLabel().setUIID("TextField");
    remarksArea.getAllStyles().setPadding(2, 2, 2, 2);
    remarksArea.getHintLabel().getAllStyles().setPadding(2, 2, 2, 2);
    mainContainer.add(remarksArea);

    add(BorderLayout.CENTER, mainContainer);
 }
````

**Comment by codenameone** [comment]
I'm not sure if we can squeeze this into 4.0 as the schedule is pretty tight even with the delay in the release.

**Comment by bbeckk** [comment]
Its still not solved. The text cursor starts to appear if only the keyboard is already opened other wise it does not appears.
