### ISSUE TITLE
Codename One - Codename One Settings - nothing happens

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2354]
Using Eclipse Oxygens with the current CodenameOne plugin I get the message

    It seems that you are using an old plugin version please upate to the latest plugin and invoke Codename One -> Codename One Settings -> Basic -> Update Client Libs

However, when opening the project context menu, clicking Codename One and Codename One Settings - nothing happens and no errors appear in teh eclipse error log

**Comment by saeder** [comment]
This is the same using MacOS and Windows 7 with current updates

**Comment by codenameone** [comment]
Make sure you are using JDK 8 and eclipse runs with that VM too. Not JDK 9 or anything else. Also this applies to Codename One Settings too: https://www.codenameone.com/blog/tip-track-designer-guibuilder-issues.html

**Comment by Xachman** [comment]
I also have this issue.  Though everything seems to work. Using linux and /usr/lib/jvm/java-8-openjdk-amd64 is set as jdk home.  Also looks like this instructions in the message are wrong there is no Update Client Libs just Update Project Libs and some spelling issues.
