### ISSUE TITLE
infinite slider animation not working on simulator and iOs

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2356]
the bar stays still

        Status status = ToastBar.getInstance().createStatus();
        status.setMessage("Test");
        status.show();
        status.setProgress(-1);

**Comment by codenameone** [comment]
Copied the code and tested it. Worked as expected.

<img width="749" alt="screen shot 2018-03-21 at 13 40 18" src="https://user-images.githubusercontent.com/2353641/37707924-7e60e2d8-2d0d-11e8-9a48-0fc07e59044a.png">
<img width="743" alt="screen shot 2018-03-21 at 13 40 21" src="https://user-images.githubusercontent.com/2353641/37707926-7ee28f36-2d0d-11e8-94c0-a04d9b197f79.png">

**Comment by kutoman** [comment]
this is still not working. I tested it on the simulator (iphone3gs, AppleIpadMini) and on an iPad Pro Device.

**Comment by kutoman** [comment]
Note: but it's working when I use Android based skins for the simulator

**Comment by codenameone** [comment]
I'm guessing it's related to the styling choices in your app.  Did you modify SliderFull in any way?

**Comment by kutoman** [comment]
yes I did, but why isn't this an issue for Android?

**Comment by codenameone** [comment]
The way the style is implemented in the native theme might impact this.
