### ISSUE TITLE
Download speed very slow on iOS

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2357]
The download happens very slowly on iOS.
I tested it independently on 3 platforms, Andoid (Galaxy A3, Android 7), iOS (iPad Pro, iOS 11.2.1) and Simulator.
All platforms are using the same wifi connection and downloading the same file (about 100MB), but on Android and on the simulator the download takes an average of 9 seconds, whereas on iOs about 80 seconds.

sample:

    private void test() {

        Status status = ToastBar.getInstance().createStatus();
        status.setMessage("Test");

        long startTime = System.currentTimeMillis();
        IoUtils.downloadUrlTo(downloadLink, CN.getAppHomePath() + "/testfile", true, false, new RequestProgressListener() {
            
            int lastPercent;
            
            @Override
            public void onConnectionInitation(int responseCode, int contentSize) {
                log.i(responseCode + " " + contentSize);
                CN.callSerially(() -> status.setProgress(0));
            }

            @Override
            public void onError(Exception e) {
                log.e(e);
            }

            @Override
            public void onProgress(double value) {
                
                final int percent = (int) (value * 100);
                if(lastPercent != percent) {
                    CN.callSerially(() -> {
                        status.setProgress(percent);
                        log.p("prog: " + percent);
                        if(percent >= 100) {
                            int time = (int) ((System.currentTimeMillis() - startTime) / 1000);
                            String result = "took: " + time + "s";
                            status.setMessage(result);
                            log.i(result);
                            status.show();
                        }
                    });
                }
                lastPercent = percent;

            }
        });
        status.show();
      }

IoUtils:

    public static void downloadUrlTo(String url, String fileName, boolean background, boolean storage, RequestProgressListener callback) {

        
        ConnectionRequest cr = new ConnectionRequest(url, false) {
            
                @Override
                protected void readResponse(InputStream input) throws IOException  {
                    
                    int contentSize = getContentLength();
                    
                    if(callback != null) callback.onConnectionInitation(getResponseCode(), contentSize);
                    
                            
                    final IOProgressListener onProgress = (callback != null)? (src, total) -> {
                        callback.onProgress(total / (double) contentSize);
                    } : null;
                    
                    String destinationFile = getDestinationFile();
                    String destinationStorage = getDestinationStorage();
                    
                    if(isKilled()) {
                        return;
                    }
                    if(destinationFile != null) {
                        OutputStream o = FileSystemStorage.getInstance().openOutputStream(destinationFile);
                        copy(input, o, onProgress);
                        
                        // was the download killed while we downloaded
                        if(isKilled()) {
                            FileSystemStorage.getInstance().delete(destinationFile);
                        }
                    } else if(destinationStorage != null) {
                        
                        OutputStream o = Storage.getInstance().createOutputStream(destinationStorage);
                        copy(input, o, onProgress);

                        // was the download killed while we downloaded
                        if(isKilled()) {
                            Storage.getInstance().deleteStorageFile(destinationStorage);
                        }
                    }
                }
        };
        
        cr.setFailSilently(false);
        cr.setReadResponseForErrors(false);
        cr.setDuplicateSupported(true);

        cr.addExceptionListener(evt -> {
            if(callback != null) callback.onError(evt.getError());
        });
        
        if(storage) {
            cr.setDestinationStorage(fileName);
        } else {
            cr.setDestinationFile(fileName);
        }
        if(background) {
            NetworkManager.getInstance().addToQueue(cr);
        } else {
            NetworkManager.getInstance().addToQueueAndWait(cr);
        }

    }

_

    public interface RequestProgressListener {
    
      void onConnectionInitation(int responseCode, int contentSize);
    
      void onError(Exception e);
    
      void onProgress(double value);
    }

**Comment by codenameone** [comment]
If you have a progress listener every byte sends a notification so you'll get slower downloads as a result. Disable that code and speed will be MUCH faster.

**Comment by kutoman** [comment]
Does this mean I shouldn't listen to the progress (as feedback for the user)? How can I manage this otherwise?

**Comment by codenameone** [comment]
If you remove the progress listener is it faster? Looking again at your code the impact shouldn't be that big.

**Comment by kutoman** [comment]
I replaced `copy(input, o, onProgress)` by `copy(input, o)`. It had no impact. It's still extremly slow

**Comment by codenameone** [comment]
It seems this triggered a regression mentioned here: https://stackoverflow.com/questions/49616677/networking-unstable-on-ios
