### ISSUE TITLE
'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2358]
From some users I get the following error report although I do a null check before I call `Image.getWidth()`:

    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

How can I avoid this?

sample code:

    private int determineAppropriateImgWidth(Image img) {
       
        if(img == null) return -1;        

        int targetWidth = page.getWidth();
        int targetHeight = (int) (targetWidth / BG_TARGET_ASPECT_RATIO);
        
        double imgScaleFactor = targetWidth / (double) img.getWidth(); //error source
        int scaledImgHeight = (int) (img.getHeight() * imgScaleFactor);
        
        if(scaledImgHeight >= targetHeight) return targetWidth;
        else {
            double apprImgScaleFactor = targetHeight / (double) img.getHeight();
            return (int) (apprImgScaleFactor * img.getWidth());
        }
    }

**Comment by codenameone** [comment]
We need a stack for these things or a test case that can be reproduced otherwise it's not an issue we can work with. Generally this means the native underlying image is null.

**Comment by kutoman** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
at com.codename1.impl.android.d.d(AndroidImplementation.java:1793)
at com.codename1.y.w.r(Image.java:690)
at org.igmg.app.f.an.b(VakitInfoPageBGmanager.java:179)
```

in VakitInfoPageBGmanager.java:179 there is just a call Image.getWidth()
