### ISSUE TITLE
[BUG] setLoop(true) of a video doesn't work (with workaround)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2362]
Code tested on Android and iOS, the setLoop(true) of a video doesn't work:

	Form hi = new Form("Hi World", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW));
        try {

            InputStream startVideo = Display.getInstance().getResourceAsStream(getClass(), "/legacy.mp4");
            Media video = MediaManager.createMedia(startVideo, "video/mp4");
            MediaPlayer introVideo = new MediaPlayer(video);
            introVideo.setHideNativeVideoControls(true);
            introVideo.hideControls();
            introVideo.setAutoplay(true);
            introVideo.setLoop(true);
            hi.add(BorderLayout.CENTER, introVideo);
        } catch (Exception err) {
            Log.e(err);
        }
	hi.show();

WORKAROUND - To make the loop working, I changed the code so (tested on Android and iOS):

        Form hi = new Form("Hi World", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW));
        try {
            InputStream videoInputStream = Display.getInstance().getResourceAsStream(getClass(), "/legacy.mp4");
            // Media video = MediaManager.createMedia(videoInputStream, "video/mp4");
            // MediaPlayer introVideo = new MediaPlayer(video);
            MediaPlayer introVideo = new MediaPlayer();
            introVideo.setDataSource(videoInputStream, "video/mp4", () -> {
                introVideo.getMedia().setTime(0);
                introVideo.getMedia().play();
            });
            introVideo.setHideNativeVideoControls(true);
            introVideo.hideControls();
            introVideo.setAutoplay(true);
            // introVideo.setLoop(true);
            hi.add(BorderLayout.CENTER, introVideo);
        } catch (Exception err) {
            Log.e(err);
        }

        hi.show();

**Comment by codenameone** [comment]
I don't think we implemented loop for videos but maybe we should. If not we should document it.

**Comment by shannah** [comment]
I've added looping support on Android, iOS, and Simulator, and it's in Git.  Still need to do Javascript and UWP.

**Comment by jsfan3** [comment]
Thank you :)
