### ISSUE TITLE
[BUG] hideControls() on iOS doesn't work

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2363]
The following code should hide the video playback controls. It works as expected on Android, instead on iOS the user can use the video controls (tested with the default xcode 9.2 and the previous xcode 7.3 changing the build hint):

        Form hi = new Form("Hi World", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW));

        try {
            InputStream videoInputStream = Display.getInstance().getResourceAsStream(getClass(), "/legacy.mp4");
            MediaPlayer introVideo = new MediaPlayer();
            introVideo.setDataSource(videoInputStream, "video/mp4", () -> {
                introVideo.getMedia().setTime(0);
                introVideo.getMedia().play();
            });
            introVideo.setHideNativeVideoControls(true);
            introVideo.hideControls();
            introVideo.setAutoplay(true);
            hi.add(BorderLayout.CENTER, introVideo);
        } catch (Exception err) {
            Log.e(err);
        }

        hi.show();
		
If I change the code as the following, the result is the same: the controls are hidden on Android and are shown on iOS:

        Form hi = new Form("Hi World", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW));

        try {
            InputStream videoInputStream = Display.getInstance().getResourceAsStream(getClass(), "/legacy.mp4");
            MediaPlayer introVideo = new MediaPlayer();
            introVideo.setDataSource(videoInputStream, "video/mp4", () -> {
                introVideo.getMedia().setTime(0);
                introVideo.getMedia().play();
            });
            introVideo.getMedia().setVariable(Media.VARIABLE_NATIVE_CONTRLOLS_EMBEDDED, false);
            // introVideo.setHideNativeVideoControls(true);
            // introVideo.hideControls();
            introVideo.setAutoplay(true);
            hi.add(BorderLayout.CENTER, introVideo);
        } catch (Exception err) {
            Log.e(err);
        }

        hi.show();

**Comment by shannah** [comment]
This is fixed in git (but won't be included until after codefreeze).
You can workaround it in the mean time by adding the media player to the hierarchy before you call hideControls.  E.g.

~~~
hi.add(BorderLayout.CENTER, introVideo);
introVideo.hideControls();
~~~
