### ISSUE TITLE
Emoji's not rendering on iPhone

### ISSUE THREAD

**Issue by tikiwade** [codenameone/CodenameOne#2365]
The following multibyte label will correctly render emoji's in a Label in a CN1 Label on an android device, but the same code running on an iPhone will not render emoji's correctly, it will render bozes with question marks or what appears to be Chinese characters.

        container.addComponent(new Label(new String(new byte[]{(byte)0xf0,(byte)0x9f,(byte)0x91,(byte)0x8d,(byte)0xf0,(byte)0x9f, (byte)0x8f,(byte)0xbc,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x9c,(byte)0xf0,(byte)0x9f,(byte)0xa4,(byte)0x94,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x80,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x9d,(byte)0xf0,(byte)0x9f,(byte)0x99,(byte)0x84})));

**Comment by tikiwade** [comment]
iPhone
![image-1](https://user-images.githubusercontent.com/215211/37538542-ea1e035e-291e-11e8-8605-b021afe02ebf.jpg)
Android
![screenshot_20180316-131910](https://user-images.githubusercontent.com/215211/37538560-f84c2d84-291e-11e8-94e9-0a9dbf2a50bd.png)

**Comment by shannah** [comment]
The fix is in the "queued_during_codefreeze" branch, which will be merged after code-freeze is over.
