### ISSUE TITLE
iOS build and provided screenshots

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2369]
When I send an iOS debug build, your cloud build server tries to generate the Default-667h@2x.png (iphone 6 screenshot) even if I provided that file in /native/ios and even if I set the build hint "ios.fastBuild=true" (that is reported in the Codename One preferences, but it's not reported in the properties of the Netbeans project). Tested with the last update of the Codename One Netbeans plugin 4.0 that you released today.

I'm not sure which files are necessary to manually provide ALL iOS screenshots. The following list contains all files that I created in my /native/ios folder: am I missing something? Why does your server try to recreate a screenshot that I've already provided?

```
Default.png
Default@2x.png
Default-568h@2x.png
Default-667h@2x.png
Default-736h@3x.png
Default-736h-Landscape@3x.png
Default-iPadPro@2.png
Default-iPadPro-Landscape@2.png
Default-iPadProSmall@2.png
Default-iPadProSmall-Landscape@2.png
Default-iPhoneX@3.png
Default-iPhoneX-Landscape@3.png
Default-Landscape.png
Default-Landscape@2x.png
Default-Portrait.png
Default-Portrait@2x.png
LaunchImage-700@2x.png
LaunchImage-700-568h@2x.png
LaunchImage-700-Landscape@2x~ipad.png
LaunchImage-700-Landscape~ipad.png
LaunchImage-700-Portrait@2x~ipad.png
LaunchImage-700-Portrait~ipad.png
LaunchImage-800-667h@2x.png
LaunchImage-800-Landscape-736h@3x.png
LaunchImage-800-Portrait-736h@3x.png

```

**Comment by codenameone** [comment]
This should be fixed in current builds, it made it into 4.0
