### ISSUE TITLE
iOs: java.lang.RuntimeException: Collection.toArray(T[]) requires an Array with the same size as collection

### ISSUE THREAD

**Issue by JTBrandao** [codenameone/CodenameOne#2376]
At iOs version only we´ve got such error message: 

Error: java.lang.RuntimeException: Collection.toArray(T[]) requires an Array with the same size as collection to be passed as parameter.

Note: The same project compiled to Android build works properly.

**Comment by codenameone** [comment]
This is discussed here: https://www.codenameone.com/blog/the-toarraynew-array-antipattern.html

Since the method is a part of JavaSE and really valuable in the other usages we didn't want to remove it entirely.

**Comment by JTBrandao** [comment]
Thanks a lot.
