### ISSUE TITLE
Hide/Show the toolbar

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2387]
According to the Javadoc, to hide the toolbar should be enough this one-line code:
`form.getToolbar().hideToolbar();`

Actually it's not enough, because:
1. I have to set `Toolbar.setGlobalToolbar(false);` in the `init()` method
2. I have to add the lines to the `start()` method, after the `Form f` declaration:
```
Toolbar tb = new Toolbar(true);
tb.getUnselectedStyle().setBgTransparency(0);
tb.getUnselectedStyle().setBorder(Border.createEmpty());
f.setToolbar(tb);
f.getToolbar().hideToolbar();
```

My expected behavior is that it should be possible lo leave `Toolbar.setGlobalToolbar(true)` and then hide or show the toolbar every time that it's necessary.

**Comment by codenameone** [comment]
I suggest adding screenshots to clarify what you are seeing in each case

**Comment by jsfan3** [comment]
Ok.

**[Screenshot 1](https://user-images.githubusercontent.com/1997316/38500491-dde23ef8-3c0a-11e8-8876-fb78ddd98f53.png)**: a standard "Hello world (bare bones)" template with native theme. The toolbar is shown.
**[Screenshot 2](https://user-images.githubusercontent.com/1997316/38500492-de0aca26-3c0a-11e8-85fa-26c5edf58d6f.png)**: I added `hi.getToolbar().hideToolbar();` before `hi.show()`, but the toolbar is shown (note that the "Tap me" button moved up, it's not more visible because it's below the toolbar) - _this behaviour is unexpected (is it a bug?)_.
**[Screenshot 3](https://user-images.githubusercontent.com/1997316/38500493-de3c7b66-3c0a-11e8-8747-dcd66ba68503.png)**: I added the code `Toolbar tb = new Toolbar(true); tb.getUnselectedStyle().setBgTransparency(0); tb.getUnselectedStyle().setBorder(Border.createEmpty()); hi.setToolbar(tb);` before `hi.getToolbar().hideToolbar();` and the result is that toolbar and "tap me" are visible _(isn't strange?)_
**[Screenshot 4](https://user-images.githubusercontent.com/1997316/38500494-de5fba4a-3c0a-11e8-9377-f9aea90c5f6b.png)**: in the `init()` I changed `Toolbar.setGlobalToolbar(true);` to `Toolbar.setGlobalToolbar(false);`, in the `start()` I have the same code of the previous step and now the result is what I want: the toolbar is hidden and "tap me" is correctly positioned and visible.

**Comment by codenameone** [comment]
3 is an overlay toolbar so it's rendered on top of the UI hence the hiding of underlying UI.

**Comment by ramsestom** [comment]
Just to add that I am also experiencing this issue (I want to mask the toolbar on some specific Forms like the one of my splash screen and to keep it for the rest of my app Forms. But I can't make it completely dissapear on the Forms where I wish (I use the default blue theme and always have a little blue bar displayed on top of my forms even when the toolbar is empty (no title or buttons or whatsoever) )

Complementary to the trials of @jsfan3, I also tried to override the  initGlobalToolbar() method  in my splash screen Form like that:
```
protected void initGlobalToolbar() {
    	//No Toolbar in splash screen
    }
```
As it is stated in the API that it 
> Allows subclasses to disable the global toolbar for a specific form by overriding this method

but with no success, I always have the blue bar (i.e Toolbar) to appear at the top of my Form

**Comment by codenameone** [comment]
Try:

````java
    protected boolean shouldPaintStatusBar() {
        return false;
    }    
````

**Comment by jsfan3** [comment]
I've just found a very easy workaround to this bug, a lot easier than the workaround that I suggested in the first post of this discussion.

I replaced `myForm.getToolbar().hideToolbar();` with `myForm.getToolbar().setVisible(false);` and it works as expected. No more issues, `setVisible(false)` works fine.

Of course `hideToolbar();` works differently from `setVisible(false)`, because `hideToolbar();` tries to close the Toolbar with a motion effect, however in simple cases `hideToolbar();` is enough. Moreover, the Javadoc doesn't clarify the difference between `hideToolbar();` and `setVisible(false)`, I needed to read the code to understand it.

**Comment by jsfan3** [comment]
I've just corrected my last comment.

**Comment by codenameone** [comment]
Simplified test case:

````java
Form hi = new Form("Test 2387", BoxLayout.y());

hi.add(new Label("Hi World"));
hi.getToolbar().hideToolbar();

Button hide = new Button("Hide");
Button show = new Button("Show");
hide.addActionListener(e -> hi.getToolbar().hideToolbar());
show.addActionListener(e -> hi.getToolbar().showToolbar());
hi.addAll(hide, show);

hi.show();
````
