### ISSUE TITLE
Add SideMenu on right side of Toolbar

### ISSUE THREAD

**Issue by gerbenk** [codenameone/CodenameOne#2388]
A while back, it was possible to create a Hamburger menu on the left or right side of the menu. Since the SideMenuBar was Deprecated, this is no longer supported. It's recommended to use the Toolbar, which works great, but support for a right hand hamburger menu no longer exists.

Can you please add this support of clarify why this is not possible (or too much work)?

Thank you.

**Comment by jsfan3** [comment]
I have the same request for this functionality, thanks :)

**Comment by codenameone** [comment]
You already submitted it though: https://github.com/codenameone/CodenameOne/issues/2257

@gerbenk It's easier with the new on-top mode there are just many small edge cases that should be addressed. It's probably something that can be done in a pull request.
