### ISSUE TITLE
Migrate docs & Implementation of push from GCM to FCM

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2389]
Google announced EoL for GCM in April 2019 so we need to migrate to use the FCM API instead.

**Comment by shannah** [comment]
FCM support is added now, and will be in next server update.

Setup requirements:

1. Add `android.messagingService=fcm` to build hints.
2. Log into [Firebase console](https://console.firebase.google.com/) and add Firebase messaging to the app.
3. Download the google-services.json (from firebase console) to the project's native/android directory.

Some notes:  Including the `android.messagingService=fcm` build hint will automatically set the play services version to 12.0.0 (if project is set to something lower).

**Comment by shannah** [comment]
I have created a chapter on Push notifications in the Wiki https://github.com/codenameone/CodenameOne/wiki/Push-Notifications

It includes push instructions for all platforms.  This document should be added to the developer guide, and the existing push documentation (mostly in the "Working With iOS" section) should be removed or replaced with a link to this section.

**Comment by shannah** [comment]
Assigning to @codenameone for the final touches of inserting the Push-Notifications document into the developer guide.
