### ISSUE TITLE
JS textField enter will repeat the last input value

### ISSUE THREAD

**Issue by mickeyng** [codenameone/CodenameOne#2392]
In Javascript version, a TextField will repeat the last input value if "enter" from keyboard is pressed

See sample program below
Form hi = new Form("Hi World", BoxLayout.y());
TextField tf = new TextField();
tf.setEditable(true);
hi.add(tf);
        
Button b = new Button("get text");
b.addActionListener((e) -> {
	b.setText(tf.getText());
});
hi.add(b);

Steps:
1. Select textfield
2. Press any key, then followed by pressing enter/return key
Note that last value is repeated, getText also has duplicated last value

If textField loses focus then this doesn't happen

**Comment by shannah** [comment]
Fix will be included in next server update.
