### ISSUE TITLE
graphics in window widgets damaged

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2393]
This is a recent issue that popped up in the latest IOS builds.  The checkbox and carat graphics
in standard window widgets are damaged.  The first image is how it looked until very recently,
the second is how it looks now.
![shouldbe](https://user-images.githubusercontent.com/5963076/38763724-8486cab4-3f56-11e8-95ad-be076a2f1298.jpg)
![nowis](https://user-images.githubusercontent.com/5963076/38763726-8d5629e6-3f56-11e8-8256-5398497d6be8.jpg)

**Comment by codenameone** [comment]
This might be a regression due to this fix https://github.com/codenameone/CodenameOne/issues/2335

Can you isolate a test case?

**Comment by ddyer0** [comment]
the checkmark and pulldown triangle were both affected - does this one liner fix both?

**Comment by shannah** [comment]
Yes.  Fixes both.
