### ISSUE TITLE
setScrollOffUponContentPane not animating properly

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2394]
There is a sluttering when the toolbar gets hidden or shown.

sample code:

    private Component[] createItems(int count) {
        List<Component> items = new ArrayList<>();
        for(int i = 0; i < count; i++) items.add(new Label("ITEM " + i));
        return items.toArray(new Component[items.size()]);
    }
    
    private Container loadList(Container list, int itemCount) {
        list.addAll(createItems(itemCount));
        return list;
    }   
.....

        Form f = new Form("Toolbar Title", new BoxLayout(BoxLayout.Y_AXIS));
        f.setScrollableY(true);
        loadList(f.getContentPane(), 30);
        f.revalidate();
        f.show();
        
        f.getToolbar().setScrollOffUponContentPane(true);

demo:
Note: I'm not sliding back and forth, but the animation happens as if this was the case

![scrolloff sluttering](https://user-images.githubusercontent.com/5825645/38777640-a93e69ba-40ab-11e8-8cc0-17fbbe87abb5.gif)

**Comment by shannah** [comment]
Reopening, as this fix appears to have some regressions when using scroll wheel.

**Comment by shannah** [comment]
This is now fixed properly.

**Comment by kutoman** [comment]
there is something I noticed. I'm trying to extend `Toolbar` in order to add more advanced scrollOff methods, but when I replace the `Form`'s initial `Toolbar` instance by my `CustomToolbar` instance `setScrollOffUponContentPane` misbehaves. The toolbar is shaking. Why is this so?

my code

        Form f = new Form("Toolbar Title", new BoxLayout(BoxLayout.Y_AXIS));
        f.setScrollableY(true);
        loadList(f.getContentPane(), 30);
        f.revalidate();
        
        f.show();
        
        f.setToolbar(new CustomToolbar());
        f.getToolbar().setScrollOffUponContentPane(true);
...

         //plain sub class without any additional members
         class CustomToolbar extends Toolbar
