### ISSUE TITLE
 Display Issue in Simulator With TextComponent

### ISSUE THREAD

**Issue by pwade-tvc** [codenameone/CodenameOne#2395]
I'm using Intellij IDEA.  When run in the simulator the behavior of the text component in the following code is not correct.  The hint does not move into the label position when the form loads.  The label position remains blank until the field loses focus and then regains focus the second time.  On the second and subsequent focus event the label functions as expected.

However, if I comment out either the button being added to the container or the setEditOnShow() line then it works correctly.  I'm presuming I'm doing something wrong here because it seems to work fine on an Android device. Btw, this is cut from a much larger form just to reproduce the issue.  I thought perhaps the TextModeLayout was causing the problem with adding the button but even if I move the button outside of the container to BorderLayout.SOUTH the same issue persists.  In the sample image below the cursor, while not visible in the screenshot, is in the first field.

`private void showTestForm(Form parent) {

    Form f = new Form("Edit Entry", new BorderLayout());
    f.getToolbar().setBackCommand("Back", e -> parent.showBack());

    TextModeLayout layout = new TextModeLayout(2, 1);
    Container c = new Container(layout);

    TextComponent meetingName = new TextComponent().labelAndHint("Meeting Name");
    c.add(layout.createConstraint().widthPercentage(100), meetingName);

    Button saveButton = new Button("Save List");
    c.add(layout.createConstraint().widthPercentage(100), saveButton);

    f.add(BorderLayout.CENTER, c);
    f.setEditOnShow(meetingName.getField());
    f.show();

}
![broken_label](https://user-images.githubusercontent.com/38579654/39081287-5c549510-44f3-11e8-98f5-206fd7e13524.jpg)

`

**Comment by codenameone** [comment]
@shannah it seems that this is caused by the sync edit mode in text component. Since devices are now all async I think it makes sense to switch the simulator to async as well which will resolve this issue for the desktop port too.
