### ISSUE TITLE
new GUI Builder options not saved

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2397]
When we have a TableLayout and we select "Grow Horizontally" (in Layout Settings > settings) this option is not saved in the XML file genarated by the GUI builder. As a result, it is not taken into account in the automatically generated java source file and if we reopen the GUI builder this option is unchecked again.

The second issue is with Textfield that are set as RTL. This time, this option is correctly saved in the XML generated file (there is a `rTL=true` flag added to the Textfiel tag) but it is not transposed into the automatically build java file (So it won't be taken into account into you final app if you execute it in the simulator or on a device)

**Comment by shannah** [comment]
Fixed.  Will be included in next release of GUI Builder and Build client.
