### ISSUE TITLE
JSONParser works with invalid json

### ISSUE THREAD

**Issue by Xachman** [codenameone/CodenameOne#2400]
While I was writing some tests for a project I noticed that the JSONParser is working with json that does not have commas.  I have not had a chance to see if I can fix the issue but here is a link to the failing test.  Maybe there should be an exception for invalid json.

https://github.com/Xachman/cn1JSONTest/blob/master/test/com/xachman/jsontest/JSONParserTest.java

**Comment by codenameone** [comment]
I'm not sure if that's a problem. Traditionally we prefer non-validating parsers. They are faster and validation is mostly the job of a server.  I'm not sure why we would want a "strict mode" for the parser. This s true for XMLParser which can parse badly formed HTML too.

**Comment by Xachman** [comment]
You make a good point.  I'll give it some more thought but probably we just need some sort of JSON library to work with that will do that validation.  If you know of any that are available please let me know.

**Comment by ramsestom** [comment]
CN1JSON?: https://github.com/shannah/CN1JSON

**Comment by Xachman** [comment]
CN1JSON provides json validation.

https://github.com/Xachman/cn1JSONTest/blob/master/test/com/xachman/jsontest/JSONParserTest.java
