### ISSUE TITLE
missing skin file

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2401]
The file OTA\iphone3gs_os7.skin referenced in Ports/JavaSE/build.xml (lines 151 and 152) is missing into https://github.com/codenameone/codenameone-skins making the local build of the JavaSE jar (to test my forked version of CN1 before submiting pull requests) to crash
Can you please update the codenameone-skins repository to fix this?

**Comment by codenameone** [comment]
What's the build error you are seeing?
Notice you can/should build the skin files using the build.xml file from that repository.

**Comment by ramsestom** [comment]
The error I have is:
```
CodenameOne.jar:
build-skins:
init-skins:
C:\Development\codenameone\CodenameOneFork\Ports\JavaSE\build.xml:151: Warning: Could not find file C:\Development\codenameone\codenameone-skins\OTA\iphone3gs_os7.skin to copy.
```
