### ISSUE TITLE
ArrayOutOfBoundsException in Calendar Library

### ISSUE THREAD

**Issue by KlausHeywinkel** [codenameone/CodenameOne#2404]
The Calender Library throws an ArrayOutOfBoundsException in an iOS App, wenn the description or location of an event is empty. The error occurs in class EventInfo (Constructor). The code for a possible fix is shown in this entry on [stackoverflow](https://stackoverflow.com/questions/50190701/error-in-calender-library?noredirect=1#comment87409313_50190701)

**Comment by codenameone** [comment]
This is now fixed and should be in the update libs within 4 hours
