### ISSUE TITLE
Order of adding components to BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2405]
I have a BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW

If I add the following components in the following order it's all fine:
```
        hi.addComponent(BorderLayout.CENTER, mapContainer);
        hi.addComponent(BorderLayout.NORTH, locateMeCnt);
        hi.addComponent(BorderLayout.SOUTH, belowMapText);
```

But if I firstly add the BorderLayout.NORTH, its component disappears.  Note that mapContainer is a native Google Map.

My suggestion is to make irrelevant the order of adding the components, because it's not intuitive that it's necessary to add the CENTER component before all the others.

**Comment by codenameone** [comment]
That's z-ordering. Last object added it always on-top. You can control the order of components added with the offset argument to `addComponent`.
