### ISSUE TITLE
CENTER_BEHAVIOR_TOTAL_BELOW not working properly

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2413]
As the sample below shows, there are the following issues:

1. The button (`closeButton`) gets covered by the `MediaPlayer`. Thus the button is not visible (checked on iPhone5c simulator)
2. The button is not clickable. If you use a simple populated container for the center of the form you'll confirm this

        Form cf = CN.getCurrentForm();
        Form f = new Form("Video", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW));
        
        
        Command bc = new Command("back") {
            @Override
            public void actionPerformed(ActionEvent evt) {
                cf.showBack();
                System.out.println("back command");
            }
        };
        
        MediaPlayer mp = new MediaPlayer();
        mp.setDataSource("ANY VIDEO URI");
        
        
        Button closeButton = new Button();
        closeButton.setCommand(bc);
        closeButton.setFocusable(true);
        
        f.addComponent(BorderLayout.NORTH, FlowLayout.encloseRight(closeButton));
        f.addComponent(BorderLayout.CENTER, mp);
        
        f.setBackCommand(bc);
        f.show();

**Comment by codenameone** [comment]
The order of adding elements matters here. The last element added is always on top unless you add it to an explicit position e.g. `f.addComponent(0, BorderLayout.CENTER, mp);`
