### ISSUE TITLE
ios.multitasking shows always the Java Duke icon

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2426]
I have the following build hints. When I open the app on iPhoneX, I see the Java Duke icon as splash screen (instead of my "icon.png"), then my splash screen (that I implemented because the screenshot generation is requested also with `ios.multitasking`).
My icon.png is a standard 512x512 png, that is correctly shown as icon of the app.
At the moment, the only workaround that I found is to remove the `ios.multitasking`

So... is it a bug or is there a way to replace the Duke icon with my icon? Thanks

```
----- BUILD HINTS -----
android.buildToolsVersion = 27
ios.locationUsageDescription = "my description"
ios.objC = true
ios.project_type = ios
ios.NSAppleMusicUsageDescription = Some functionality of the application requires access to your media library
win.ver = 8
android.xpermissions = <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES"/><uses-feature         android:glEsVersion="0x00020000"         android:required="true"/><uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES"/><uses-feature         android:glEsVersion="0x00020000"         android:required="true"/>
ios.dsym = false
android.xapplication = <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="xxxx"/>
ios.glAppDelegateHeader = 
#import "GoogleMaps/GoogleMaps.h"
ios.icloud.CloudDocuments = true
ios.statusbar_hidden = false
ios.application_exits = false
javascript.googlemaps.key = xxx
ios.NSPhotoLibraryUsageDescription = Some functionality of the application requires access to your photo library
ios.includePush = true
android.playService.maps = true
ios.NSCameraUsageDescription = Some functionality of the application requires your camera
android.GoogleMaps.minPlayServicesVersion = 9.4.0
j2me.nativeThemeConst = 0
ios.multitasking = true
java.version = 8
ios.afterFinishLaunching = [GMSServices provideAPIKey:@"xxxxx"];
ios.pods = ,GoogleMaps
ios.prerendered_icon = false
ios.testFlight = false
rim.obfuscation = false
ios.interface_orientation = UIInterfaceOrientationPortrait:UIInterfaceOrientationPortraitUpsideDown:UIInterfaceOrientationLandscapeLeft:UIInterfaceOrientationLandscapeRight
ios.newStorageLocation = true
android.release = false
ios.pods.platform = ,7.0
android.debug = false
ios.pods.sources = ,https://github.com/CocoaPods/Specs.git
```

**Comment by shannah** [comment]
You can customize this.  See https://github.com/codenameone/CodenameOne/wiki/Working-With-iOS#launch-screen-storyboards

**Comment by jsfan3** [comment]
Thank you very much. I suggest to add this documentation in the developer guide (pdf), in which this information is missing.

**Comment by shannah** [comment]
That is where the developer guide is generated from.  It will appear in the guide the next time it is generated.

**Comment by jsfan3** [comment]
Can you reopen this issue, please? I added a file `Launch.Foreground.png` _(that is a copy of my `icon.png` placed in the project root directory)_ in the `native/ios` directory, I recompiled and I sent a new iOS built, but the Duke icon is shown instead of my icon.

I also suggest that if nothing icon is added in the `native/ios` directory, the default `icon.png` should be used...

Thank you for the support.

**Comment by codenameone** [comment]
FYI the developer guide should be up to date now with the changes

**Comment by shannah** [comment]
This is a major annoyance that I forgot to document.  iOS caches the launch screen so updating the launch screen won't actually take effect until the device is restarted.  Even deleting/reinstalling the app doesn't seem to be enough.

Reference https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update

I have added a note in the wiki (which will propagate to the developer guide) about this.
