### ISSUE TITLE
RFE: add "Send to (testing) build server"

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2433]
This RFE is not more than an opinion or suggestion.
Because what happened two day ago (I refer to https://github.com/codenameone/CodenameOne/issues/2429), I think that it could nice if you can involve people to test their apps on new versions of the build servers (marked as "testing") before switch these new versions in the production environments.

In other words, can you involve the CN1 developers/users to do some beta testing before any critical change? In the IDE plugins of CN1 there isn't any option to use a testing version of the build server, maybe you should consider to add this functionality. This can save a lot of headaches, avoid unexpected breaking of apps and hopefully you can get more feedback than now.

**Comment by codenameone** [comment]
We discussed this multiple times in the past. The problem with this is that people never use the test option or test flags or any such thing and are caught off guard regardless of what we do. 
We do have a versioned build option for pro users which does answer the problem of volatility and we have weekly releases (and in this case a hotfix) that resolve things fast. 
We do need more test cases that also check things like performance & similar regressions.
