### ISSUE TITLE
bug in base64.decode()

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2441]
Decoding this base64 encoded String: "eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9=="  gives an indexoutofbounds exception whereas it is supposed to be a correct base64 encoded string (see https://www.base64decode.org/). 
I end up using this implementation of the base64 decoder/encoder: https://gist.github.com/EmilHernvall/953733 that is not broken and gives correct results...

**Comment by codenameone** [comment]
Do you have the stack trace of the index out of bounds?

**Comment by ramsestom** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 30
	at com.codename1.util.Base64.decode(Base64.java:118)
	at com.codename1.util.Base64.decode(Base64.java:31)
```

I assume this is happening because of the "==" I added at the end of the encoded string which comes from a jwt token because I had other decoding failures without it (https://groups.google.com/forum/embed/?place=forum/codenameone-discussions&showsearch=true&showpopout=true&hl=en&parenturl=https%3A%2F%2Fwww.codenameone.com%2Fdiscussion-forum.html#!searchin/codenameone-discussions/base64/codenameone-discussions/eTJgAQG1Sxg/7U76c8BzAAAJ)
Anyway, like I said, I end up using https://gist.github.com/EmilHernvall/953733 that has a much more robust decoding algorithm (it is also insensitive at the presence of the "==" at the end of the base64 encoding string or not)

**Comment by javieranton-zz** [comment]
Just stating that this still happens and hasn't been fixed. I will resort to using https://gist.github.com/EmilHernvall/953733 as well
