### ISSUE TITLE
BackgroundFetch not supported on iPhone 7s (iOS 11.2.5)

### ISSUE THREAD

**Issue by andreamono** [codenameone/CodenameOne#2451]
I tried to implement the BackgroundFetch interface, for giving my app a background behaviour. Running it on iPhone 7s (iOS version: 11.2.5 15D60), I noticed that device does not support the background fetch. In fact, Display.getInstance().isBackgroundFetchSupported() returns false.

**Comment by shannah** [comment]
You need to add the `ios.background_modes=fetch` build hint.
