### ISSUE TITLE
com.codename1.ui.geom.Geometry.BezierCurve missing

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2453]
com.codename1.ui.geom.Geometry.BezierCurve is missing (looks like you forgot to make a `git add`) making com.codename1.ui.geom.GeneralPath to fail compilation

**Comment by shannah** [comment]
It's in git
https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/geom/Geometry.java

How are you building?

**Comment by ramsestom** [comment]
Oh sorry. Was just an issue with eclipse (had to perform a refresh of my CodenameOne project for Geometry.java to be seen by eclipse)
