### ISSUE TITLE
Not able to change the font size for Signature Component

### ISSUE THREAD

**Issue by ChrisLace** [codenameone/CodenameOne#2456]
This issue has been discussed but bug not filed. I'm not sure this has been implemented yet as I don't see in the update. Please refer the https://stackoverflow.com/questions/50781541/how-change-the-font-size-for-signature-component for more details

**Comment by codenameone** [comment]
This was implemented already. If it doesn't work you need to detail what doesn't work and provide configuration screenshots/results so we can make sure we are on the same page.
