### ISSUE TITLE
missing fields in java.util.Calendar

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2462]
Some of the fields of the legacy java.util.Calendar class (like WEEK_OF_YEAR, WEEK_OF_MONTH, DAY_OF_YEAR...) are not present into the CLDC11 Calendar exposed API port: https://github.com/codenameone/CodenameOne/blob/1ac7c6192cae151cb1665888d4a16175d56ef892/Ports/CLDC11/src/java/util/Calendar.java
They seems to be present into the various Calendar platform implementations though:
https://github.com/codenameone/CodenameOne/blob/1ac7c6192cae151cb1665888d4a16175d56ef892/vm/JavaAPI/src/java/util/Calendar.java
https://github.com/codenameone/CodenameOne/blob/1ac7c6192cae151cb1665888d4a16175d56ef892/Ports/WinPhone7/Common/Calendar.cs
So would it be possible to expose them in the public CLDC11 implementation as they are usefull in some situations (I need them to evaluate some opening hours expressed with the openstreetmap convention for example)?

Also is there a reason why the GregorianCalendar is not exposed in the CN1 API? As it is the default calendar returned by Calendar.getInstance() it would be great if we could directly instantialize the GregorianCalendar class (rather than having to call Calendar.getInstance())

**Comment by ramsestom** [comment]
For the `GregorianCalendar` this is just a convenience request. This is just that `Calendar.getInstance()` seems to return a `GregorianCalendar` anyway. But being able to directly instantialise a `GregorianCalendar` seems more clear to me as its name is self explanatory so I directly know the type of calendar I would get (whereas it is a bit obscure with `Calendar.getInstance()`). And as `GregorianCalendar` is already implemented and used under the hood by Calendar, I don't see any reason why not to expose it in the public API ?
Anyway my main request is well about the missing fields of the Calendar class. This is clearly what is the most annoying (the `GregorianCalendar` remarq was more of a detail)

**Comment by codenameone** [comment]
The main incentive not to include `GregorianCalendar` is that the API contains a bit more than `Calendar` and we don't want to open a can of worms of untested code. 

The "right thing" would be adding support for JSR 310 which provides better time/date API's but it's not trivial.

**Comment by ramsestom** [comment]
just wanted to point out that you forgot to declare the field DAY_OF_YEAR as public in your code of java.util.Calendar (https://github.com/codenameone/CodenameOne/commit/fa51219cf8fd856e4fd074a8d1b5f067a12f1473)
