### ISSUE TITLE
RFE: add append(char[] str) method to StringBuilder

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2465]
It would be a good idea to add the `append(char[] str)` method to the CN1 StringBuilder class to make it mimic the legacy StringBuilder java API and avoid this kind of issue: http://www.codenameone.com/discussion-forum.html#!topic/codenameone-discussions/Nd_smpNiEJk?place=msg%2Fcodenameone-discussions%2FNd_smpNiEJk%2F897_ug-_AAAJ
It would also propably make sense to have an `append(StringBuffer sb)` method like in the StringBuilder java API

**Comment by shannah** [comment]
This is fixed in ParparVM and CLDC11 sources now.  It's been a while since I've rebuilt CLDC11 for distribution (if ever).. I recall there were a couple of complexities to keep in mind there wrt corevm.jar vs CLDC11.jar.

**Comment by codenameone** [comment]
corevm is only relevant if we want to use this API in CodenameOne.jar which we don't really need right now. I'm closing this as implemented, right?
