### ISSUE TITLE
[BUG] UIBinding doesn't work on Android only (exception on TextComponent.java:119)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2471]
Same code of this issue (I suppose that the two bug are correlated): https://github.com/codenameone/CodenameOne/issues/2470

The UIBinding works fine in the Simulator and on iPhoneX, but works incorrectly on Android 7, because the binding works with some InputComponents fields and with others don't. For example, on Android the first name is not binded to the property, while the family name is binded. Moreover, I got an exception on the real Android device moving from the user input form to the previous form and then to the user input form again: on iPhone I see all the previously filled data, on Android I see only some of that data.

```
        // Bind the text fields to the User object
        UiBinding uib = new UiBinding();
        uib.bind(me.firstName, firstName.getField());
        uib.bind(me.familyName, familyName.getField());
        uib.bind(me.birthdayDate, birthday.getPicker());
        uib.bind(me.gender, gender.getPicker());
        uib.bind(me.email, email.getField());
        uib.bind(me.password, password.getField());
```

Exception:

```
[EDT] 0:4:25,295 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'java.lang.String com.codename1.p.l.ah()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.codename1.p.l.ah()' on a null object reference
	at com.codename1.p.an$1.n_(TextComponent.java:119)
	at com.codename1.p.l.e(Component.java:1843)
	at com.codename1.p.l.am(Component.java:1782)
	at com.codename1.p.u.a(Form.java:2344)
	at com.codename1.p.u.y(Form.java:2282)
	at com.codename1.p.u.C(Form.java:3885)
	at com.codename1.p.l.be(Component.java:4963)
	at com.codename1.impl.android.InPlaceEditView$3$1$1.a(InPlaceEditView.java:1212)
	at com.codename1.p.k.b.a(EventDispatcher.java:349)
	at com.codename1.p.u.e(Form.java:644)
	at com.codename1.p.q.a(Display.java:2151)
	at com.codename1.p.q.j(Display.java:1043)
	at com.codename1.p.q.i(Display.java:961)
	at com.codename1.p.ai.run(RunnableWrapper.java:120)
	at com.codename1.impl.b$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:776)

```

**Comment by jsfan3** [comment]
Thank you, for commit solved the exception, but not the Android-specific UIBinding problem. I've sent a new Android build and I have the same problem: the first name is not saved in the BusinessPropertyObject, while the family name is saved instead. This issue is not present on iPhone, so I suppose that problem is the transcoding made by the Android build server.

**Comment by codenameone** [comment]
Did you incorporate this commit into the code and recompile? It's not on the build servers yet.

**Comment by jsfan3** [comment]
Yes, the bug is still present. 

Steps to reproduce:


- I deleted my remote and local fork of Codename One
- Few minutes ago I created a new fork and I cloned it locally
- I checked that your commit https://github.com/codenameone/CodenameOne/commit/4623b115245af3704aef2accf9eb33278565b285 is included (as expected)
- In the properties of my UIBindingBug project (code: https://github.com/codenameone/CodenameOne/issues/2472), I changed the compile libraries replacing the default ones with my clone of CodenameOne, and the run library "JavaSE.jar" with the "JavaSE" project under CodenameOne/Ports.
- In the Codename One settings of UIBindingBug project, I executed "Update project libs"
- I commented the lines 151 and 152 of build.xml of the JavaSE project (because they produces an error)
- In the UIBindingBug project I executed "Clean and Build Project": the build was successful
- I tested the build in the Simulator: it works correctly, both first name and family name are saved in the PropertyBusinessObject
- I sent an Android build
- I installed in my Android 7 device the build after closing all the apps and removing the previous UIBindingBug app
- I tested the build: BAD NEWS, SAME ISSUE, the first name is not saved (but the family name is saved).

For me it's a blocking bug, because I cannot complete the registration of the users.

**Comment by codenameone** [comment]
Thanks!
I've assigned the issue, we'll try to track it.
