### ISSUE TITLE
Scroll Behavior difference between Android and iOS.

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#2474]
In our App we are facing in a weird difference of behavior in Scroll. In Android, all works correctly as expected.

But in iOS, doesn' t.

One of our Forms, presents a list of items, each item is composed by a container that has a Codenameone' s Accordion component where inside it was put 2 other containers ( one on header position, and another one on body position.
This is the basic hierarchy disposition of visual components on the Form.

On Android devices and on Simulator all works well. The device shows the list, allowing the user to use the right gesture to perform the scroll on all of the items available and when he touches on a specific item the detail information can be exploded and collapsed.
This is what was coded and works as expected. 

So far so good, but the same code, when packaged and executed on an iOS device, doesn' t works correctly. When the user executes the scroll gesture the scrolling occurs but limited on item component scope.

For illustrating the problem we recorded a video where you can see the problem occurring. You can access the video using the link below:
https://drive.google.com/file/d/1YRzl4b9d-oBVGt_a-Pq9lIvDBgPoM_qs/view?usp=sharing

**Comment by codenameone** [comment]
Is the iOS device acting differently from the iOS simulator?
If so can you make sure your plugin is up to date (4.3) and then in Codename One Settings -> Basic invoke Update Project Libs?

The issue should be reproducible on the simulator.

**Comment by hrugani** [comment]
Only iOS  **devices** have different behavior.
The problem can't be reproducible on the Simulator.
And the problem doesn' t occur on Android devices as well.

**Comment by codenameone** [comment]
Did you try the steps I mentioned to make sure the skin and libraries are up to date?
Since everything is rendered in Java this should be reproducible in the simulator if you are running the exact same code as the servers.

**Comment by hrugani** [comment]
In your comments, you mentioned two things that I need some help to accomplish.

1. to Try to use the last version of Codename One Plugin (4.3). On Plugin Manager of my Netbeans IDE the last version that is shown to update is 4.0.3 and not 4.3. Looking at Github project we saw the last version is really 4.3. How can I get the last version available on Github and install it on my IDE? Then we could make the test that you are requesting to do.

2. You asked us whether this problem could be reproducible on something that you called "iOS Simulator". Are you making reference to the Simulator present in Codename Plugin? Or it is another Simulator that runs only on Mac and used via xCode or something like that. If the second option is what you want. How to use this other Simulator?

**Comment by hrugani** [comment]
**We have just solved the problem.**
We only forced setScrollableY(false) on the constructor
of all "accordion-Component" that are responsible to render each item that is put within BoxLayout-Y manager of the root container.
Doing that, Android and iOS now have the same correct and intuitive scrolling behavior.

**Comment by codenameone** [comment]
Sorry I mislabeled the 4.3 release in NetBeans as 4.0.3. I meant the builtin simulator to Codename One just a skin that's modern and relatively close to the device you are testing with in terms of proportions. 

I'm guessing this got triggered because iOS has tensile scrolling so you saw that behavior but the problem is universal as scrolling can't be nested.

**Comment by hrugani** [comment]
We understand the complexity to handle with all kinds of differences between mobile platform.
We are only waiting to finalize all tests on real devices as so far all tests were executed only on Simulator.
After passing all tests, we'll close this issue. 
Thank you for your support and comments.
