### ISSUE TITLE
Executing files on Android 4.3 fails

### ISSUE THREAD

**Issue by jpaul51** [codenameone/CodenameOne#2480]
When I execute a file (pdf, apk) using Display.getInstance().execute() on android 4.3 it throws the following exception:

[androidLog.txt](https://github.com/codenameone/CodenameOne/files/2197264/androidLog.txt)

Code:
```
 FileSystemStorage fs = FileSystemStorage.getInstance();
                String fileName = fs.getAppHomePath() + "pdf-sample.pdf";
                if (!fs.exists(fileName)) {
                    Util.downloadUrlToFile("http://www.polyu.edu.hk/iaee/files/pdf-sample.pdf", fileName, true);
                }
                Display.getInstance().execute(fileName);
```
It works on Android 8.0

**Comment by shannah** [comment]
It says you don't have any PDF viewers installed on that device.  Install a PDF viewer, and it should work.

**Comment by jpaul51** [comment]
I have the exact same error when  I try to open an apk file. I am sure that I was able to open it with  Display.getInstance().execute on this device. How could it not find the package installer ?
Installing a pdf viewer solves it for the pdf files.

**Comment by codenameone** [comment]
APK installation might be blocked by google with updates to play services that happen outside of the OS update process.
