### ISSUE TITLE
Http requests stopped work on iOS

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#2482]
Our App always worked fine using both protocols (Http and Https).
On Android, The App continues to work well. (http and https).
But recently, on iOS, http stopped work. 
Now on, only the https requests are working on iOS.

Is there some reason for that behavior to have changed?

We have a few clients that are using https.
But, the major part of them continues to use http and
they have a lot of users using iOS.

**Comment by codenameone** [comment]
Apple cut support for HTTP a couple of years ago: https://www.codenameone.com/blog/ios-http-urls.html

This is strictly enforced on xcode 9+ which Apple requires as a minimum. See the article for the workaround and why it's problematic...
