### ISSUE TITLE
[BUG] iOS Debug build fails because it tries to produce a release build

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2483]
The same Netbeans project, that until few days ago has produced iOS Debug builds without problems, cannot produce a new iOS Debug build because the following error. I tried to regenerate the provisioning certificates, but nothing is changed.

```
=== BUILD TARGET StartPoint OF PROJECT StartPoint WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: Provisioning profile "Registrazione Prototipo 2 IOS_DEVELOPMENT Profile" doesn't include the com.apple.developer.icloud-services entitlement.
warning: skipping file '/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build1791003386983925142xxx/dist/StartPoint-src/StartPoint-Info.plist' (unexpected file type 'text.plist.xml' in Frameworks & Libraries build phase)
warning: skipping file '/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build1791003386983925142xxx/dist/StartPoint-src/StartPoint-Prefix.pch' (unexpected file type 'sourcecode.c.objc.preprocessed' in Frameworks & Libraries build phase)
Warning: The Link Binary With Libraries build phase contains this target's Info.plist file 'StartPoint-src/StartPoint-Info.plist'.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
```

I noted that in the error log, in the section "Request Args", there are these two lines:
```
android.release=true
android.debug=false
```
Of course they are wrong, because I sent a debug build, so I guess that this is the cause of the error. Tried several times.

**Comment by codenameone** [comment]
The build hints are android flags that don't impact iOS. We always build release builds. That isn't the reason the build is failing. We'll need the full error log to understand it but I'm guessing you are using something like file picker without the icloud provisioning?

**Comment by jsfan3** [comment]
You're right. Your guess is correct :)
