### ISSUE TITLE
form.removall with dynamically created containers component already exists error

### ISSUE THREAD

**Issue by thomasmcneill** [codenameone/CodenameOne#2485]
If I do a removall and add components that have prevously been created there is no issue except if I enclose some of them inside a container.

form.add(BoxLayout.encloseX(new Label("Sex"),sp_Sex));

This line will throw an error about the component already being on the form.  If I create a new container and add it I get the same results.  If I create that container in my class and keep it global to the class it doesn't give this error when I add it though.

The form is a data entry form that can change depending on event type. All input fields are initialized in the constructor.   I have a function to draw the form depending on other data.

**Comment by codenameone** [comment]
`removeAll()` removes the components from a `Form`. It doesn't recurse. So `sp_Sex` is still in a `Container`. Just do `sp_Sex.remove()` before adding it again.

**Comment by thomasmcneill** [comment]
Can that be documented in the help?  When I see a command that says removeAll() I'd assume it will iterate all child objects as well as their children.

**Comment by codenameone** [comment]
Done
