### ISSUE TITLE
[BUG] intercom.io login mask after every build sent

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2487]
From today, every time that I send a new build I get this login mask:

![schermata](https://user-images.githubusercontent.com/1997316/43317733-4e08f238-919e-11e8-9ed1-754bc2c3f859.png)

**Comment by codenameone** [comment]
Thanks.  I thought we removed the last of that.
We pushed out a new update to the client libs that should hopefully fix it. This is caused because we deleted all of the user data from intercom.
