### ISSUE TITLE
After generating push certificates I didn't received any email

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2488]
According to this guide:
https://github.com/codenameone/CodenameOne/wiki/Push-Notifications
I should receive an email after generating the iOS push certificates.

I generated them two times for an app, but I didn't received any email.

**Comment by codenameone** [comment]
I looked at the sendgrid log and I can see emails going out to the proton mail account. I don't see any rejects. Notice the file with instructions should be in your project root too.

**Comment by jsfan3** [comment]
Thank you for the check. In the project root there is a folder "iosCerts" with four files:

development_provisioning_profile.mobileprovision
development_push_certificate.p12
production_provisioning_profile.mobileprovision
production_push_certificate.p12

There isn't any instructions file.
About my Protonmail account, I usually receive all the email from Codename One, but this instruction email is missing. 

I'll try again in few hours, at the moment I cannot repeate the certificate generation because the "null response" issue.

**Comment by jsfan3** [comment]
I confirm that this issue is solved.
