### ISSUE TITLE
Failed to generate iOS certificates (null response)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2489]
This issue seems related to https://github.com/codenameone/CodenameOne/issues/2488, however it's different.

I've just tried again to generate my iOS Push certificates, hopefully to receive the email with the passwords.

I didn't overwrote the existing Developer and AppStore Certificates. I generated new provisioning profiles for my app, with the option "Enable Push" checked. At the question "Would you like to generate new push certificates" I replied "Yes".  At the question "Overwrite Certificate? This app already has a development push certificate on file" I replied "Yes". Finally, Failed has you can see in this screenshot.

![failed](https://user-images.githubusercontent.com/1997316/43364062-2943fff8-9313-11e8-9b0d-f66929c3ea29.png)

**Comment by jsfan3** [comment]
Workarounded this error deleting a lot of garbage from my account:

- I deleted from my pc all the iOS certificates

- I went to developer.apple.com, I revoked all my certificates

- I deleted almost all my iOS Apps from developer.apple.com  (except my active projects).

- I removed all my (long list of) iOS Provisioning Profiles

- I executed the Certificate Wizard again: this time it worked fine.

However, I didn't received the email with the password for push and the istruction file is not saved in the iosCerts folder. So my push certificates are useless without that error..

Controlling in developer.apple.com, I saw four iOS Provisioning Profiles associated to my app:
<appName> IOS_DEVELOPMENT Profile
<appName> IOS_DISTRIBUTION Profile
<appName> NotificationServiceExtension IOS_DEVELOPMENT Profile
<appName> NotificationServiceExtension IOS_DISTRIBUTION Profile

The first two were invalid: to make them valid, I regenerated them, after that I downloaded them to overwrite the existing ones generated by the wizard.

**Comment by jsfan3** [comment]
Edited my previous post.

**Comment by jsfan3** [comment]
Said that there are some issues about the wizard, however I finally find my push certificates urls and their passwords: they are stored in the file codenameone_settings.properties

I used them in my Spring Boot server and I got my first push message in my iPhone :)

**Comment by shannah** [comment]
The wizard wasn't correctly identifying existing production push certificates, so if the account already had the maximum number (2), it would just fail instead of prompting the user to revoke the oldest one.  This is now fixed.

I cannot reproduce the issue with not receiving emails.

**Comment by shannah** [comment]
Every app needs its own push certificates.
