### ISSUE TITLE
RFE: Implement minuteinterval for Date-Time-Picker

### ISSUE THREAD

**Issue by KlausHeywinkel** [codenameone/CodenameOne#2491]
It would be useful if it was possible to set the minuteinterval for the Date-Time-Picker-Component in codenameone, when the native Picker-Element is used on an iOS device. I saw that you can do so when developing a native app directly in Xcode.

See: [Question on Stackoverflow](https://stackoverflow.com/questions/51562605/set-minuteinterval-for-native-ios-date-timepicker?noredirect=1#comment90176167_51568003)

**Comment by codenameone** [comment]
@shannah I assigned it for 5.0 only if it's trivial. If it isn't then it should go to 6.0.
