### ISSUE TITLE
Avoid opening of the CSS compile windows

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2494]
It's a bit annoying that every time that I compile and I run my projects the CSS support opens a window to creare the 9-piece borders... without closing it.

It can be better if the work of the CSS support should be invisible or, at least, that it closes its windows.

**Comment by codenameone** [comment]
Unfortunately we can't avoid opening the window for some of these cases but it should be closed. We tried to minimize the cases where this opens so compilation will be faster.
