### ISSUE TITLE
RFEs about BoundTableModel

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2502]
Because the `BoundTableModel` can be used to input data, I suggest to:

- add a way to implement `Validator` constraints: if the input doesn't valide for a given constraint (even a custom constraint that extends the `Constraint` class overriding its `isValid` method), for example it can change the color of the text (suppose from black to red);
- add a way to seamless respect the input type of the `Property`: at the moment, if the binded `Property` is an `IntProperty`, the table cell accepts any input and it's wrong; moreover, if the input cell has a correct input constraint (in this case the input should be an `Integer`), it will show the cell arrows to increment or decrement the number (at least in the javascript version).

A test case is the same reported here: https://github.com/codenameone/CodenameOne/issues/2500: in the position row you can enter any string, but it's binded to an IntProperty (and I don't know exactly what it happens because there isn't any exception in the log...)

**Comment by codenameone** [comment]
This is a bit challenging. I'm not sure it will make it to 5.0 but I'll give it a stab if I finish the other issues.

**Comment by jsfan3** [comment]
Thank you! I hope for your help ;-)

**Comment by jsfan3** [comment]
Thank you!
