### ISSUE TITLE
Documentation about BoundTableModel.setValidationConstraint(PropertyBase prop, Constraint c);

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2514]
I've seen to presence of the method `public void setValidationConstraint(PropertyBase prop, Constraint c);` of the class BoundTableModel, however it's unclear how to use it (at least it's unclear to me). Can you add documentation and/or examples?

In the PropertiesTableBindingDemo I added the following line, but apparently it does nothing:

`tb.setValidationConstraint(prot.email, RegexConstraint.validEmail());`

Thank you

**Comment by codenameone** [comment]
I'd like to leave it under the radar for now as I'm still thinking about the "right way" to do validation with properties. 
This should work that way but you also need to submit your validator using `tb.setValidator()`.
