### ISSUE TITLE
Issue about PropertiesTableBindingDemo: editable and not editable fields

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2515]
In the PropertiesTableBindingDemo it's not specified which fields are editable and which are not, so I assume that all of them are editable, right? So, why the email of Shai, Steve and Chen are not editable, while the email of a new row is editable? Tested with iPadAir2 skin.

**Comment by codenameone** [comment]
This happens because the values are null. So they aren't included. You can override the `includeNullValues()` to return true in `Table`. Alternatively you can change the properties to have `""` as the string value by default e.g.: 

````java
public final Property<String, Contact> email = new Property<>("email", "");
````

**Comment by jsfan3** [comment]
Ok!
