### ISSUE TITLE
Screenshot process should be removed by default for 5.0

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2522]
Now that we have the new xib mode it should be on by default and should be fixed to remove the screenshot process entirely. We should do this ASAP so this would be the default mode of 5.0

**Comment by shannah** [comment]
Added note to wiki about new `ios.generateSplashScreens` build hint  https://github.com/codenameone/CodenameOne/wiki/Advanced-Topics-Under-The-Hood/_compare/776ce43648a229e27c4280c18d5e892f2ef48a61...6a9fe5f1611ebcbc3856cae8ff558a8988d55fca

**Comment by shannah** [comment]
Added note to screenshot section of developer guide about sceenshot generation being disabled by default.
https://github.com/codenameone/CodenameOne/wiki/Working-With-iOS/_compare/3b71edbb7f54a2649dede0c706ebf22c839cd5a7...2171199d1252ccfe44853fda3164f27a3ddb9fcc
