### ISSUE TITLE
[RFE for Javascript port] Add a default "window.onbeforeunload = function () {return false;}"

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2535]
**Use case**: the user interact with a web app, than uses the browser refresh functionallity to catch new data in the currently displayed `Form`. It's fine in a "standard" website, but it's completely wrong in a webapp (because the refresh restarts the app with a possibly **loss of data**).

**Proposed solution**: I suggest to add `window.onbeforeunload = function () {return false;}` as default, so every modern browser will show an alert before refreshing or even before closing the current tab. Modern browser like Firefox and Chrome shows an alert ONLY IF there is a minimal interaction with the web page (at least one click on its content) and also allow the user to don't refresh after that alert. It's a solution used by a lot of websites.

**Test code** _(open it, click on the page, then try to refresh to see an alert):_
```
<!doctype html>
<html>
<head>
<title>Test case</title>
<meta charset="utf-8" />
<script>
window.onbeforeunload = function () {return false;}
</script>
</head>
<body>
<h1>Try to refresh this page after clicking in the page</h1>
</body>
</html>
```

_(Even better RFE: it could be even better if it's possible to detect the refresh and use it to refresh the Form content, like if it is a PullToRefresh. However I don't know if it's possible.)_

**Comment by shannah** [comment]
Fixed.  Will be included in next update.

**Comment by jsfan3** [comment]
Thank you!
