### ISSUE TITLE
DialogBody leaves too much space in CodenameOne 4.x compared to 3.x versions

### ISSUE THREAD

**Issue by jvkessel** [codenameone/CodenameOne#2536]
Originally [posted on StackOverflow](https://stackoverflow.com/questions/52022037/codenameone-dialogbody-leaves-too-much-space-in-codenameone-4-x-compared-to-3-x?noredirect=1#comment90995626_52022037), Shai @codenameone requested that I open an issue for it.

Between one version of CodenameOne and the most recent, the DialogBody of a Dialog has become much larger and leaves excessive space below its content.  I'm currently using version 4.4 in IntelliJ.

All my dialogs generated with the Dialog.show(String, String, String, ...) methods now seem to have the same issue.   Dialogs created with the syntax Dialog.show(String, Component, Command...) are showing up properly though

Here's an example of a misbehaving dialog:

The code that generates the dialog:
`Dialog.show("Quit this test?", "Do you really want to quit this test and discard your progress?", "Quit", "Return to Test")`

This is how the dialog should look (built using CN1 3.x version):
![screenshot_normal_dialog](https://user-images.githubusercontent.com/10383606/44628672-8b842980-a912-11e8-9c3f-62ba3b12e4ce.png)

This is how the dialog is showing now in a CN1 4.4:
![codenameone screenshot 1](https://user-images.githubusercontent.com/10383606/44628679-b79faa80-a912-11e8-9dcc-ddad6f49bf89.png)

Note that the component inspector shows that the preferred size of the TextArea int he dialog is only 194 pixels high but the actual height of the component is being set at 573:
![image](https://user-images.githubusercontent.com/10383606/44628694-09e0cb80-a913-11e8-8508-57765849426f.png)

and the theme.res file has no styling for DialogBody (first thing I checked).

**Comment by codenameone** [comment]
I was able to track this to this commit: https://github.com/codenameone/CodenameOne/commit/b3f894888487947b4b4f6a44f6101798b8daf285

Commenting out this code fixes the issue:

````java
if (title != null) {
    titleHeight = title.getPreferredH() + title.getPreferredH();
    Style tStyle = title.getStyle();
    titleHeight += tStyle.getVerticalMargins();
}
````

But I think it will probably break the fix so I reassigned it to @shannah 

Here we have the current state:

![codenameone screenshot 127](https://user-images.githubusercontent.com/2353641/44781167-f0928600-ab83-11e8-8c56-5a81e2f90719.png)

And after commenting out the lines it looks better:

![codenameone screenshot 128](https://user-images.githubusercontent.com/2353641/44781186-fc7e4800-ab83-11e8-8401-bfb5089ae631.png)
