### ISSUE TITLE
RFE: more readable text

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2537]
Can the text of the Codename One Properties of a Project more readable? It's very small on a high-resolution screen. My RFE is that the size of the text can be chosen by the user or selected appropriately according to the DPI. This is how I see it (on Linux with Java 10):

![toosmalltext](https://user-images.githubusercontent.com/1997316/44786918-f5603580-ab95-11e8-8abe-225d88d24d39.png)

**Comment by codenameone** [comment]
@shannah I assigned it for 5.0 just to make sure if there isn't a low hanging fruit here. If not we'll push it to 6.0

**Comment by shannah** [comment]
I'm not sure if this is an issue with HiDPI handling on linux, or if this is just the size it is supposed to be.  

Screenshot on My MBP retina:

![image](https://user-images.githubusercontent.com/2677562/44801282-7eaf4200-ab6d-11e8-9d31-11443787d640.png)

Screenshot on Linux running remotely via X-Windows on MBP retina.

![image](https://user-images.githubusercontent.com/2677562/44801372-bfa75680-ab6d-11e8-9ce9-aa90b96647fa.png)

I don't actually have any linux machines with HiDPI display, so the X-Windows run remotely was my feeble attempt to simulate that situation.

In both cases the resulting text size looks appropriate.

I Admit that the size on the screenshot posted by @jsfan3 looks a little small.

I'm going to try to add some better diagnostics for this by adding support for some environment variables that affect the scaling, and also for logging relevant display properties.

**Comment by shannah** [comment]
@jsfan3 When you run on Java8, do you get different (better) results?

**Comment by jsfan3** [comment]
@shannah Yes, on Java8 I got a different better result, but  I used Java8 on Windows, now I'm using Java10 on Linux (with the same computer and in both cases inside a VirtualBox machine). It seems that Java doesn't consider the DPI of my screen (to run Netbeans with a decent font, I explicity setted the run parameter `/home/francesco/netbeans-9/bin/netbeans --fontsize 20`). On the Linux settings, I changed the default DPI from the standard 96 to the more realistic 140 and all the apps look better (except Java). The same issue is with the `desktop.skin`: when the apps are simulated with the `desktop.skin` they have too small font sizes, when I port them to Javascript the font sizes are correct.

**Comment by jsfan3** [comment]
I have a 17'' monitor, the resolution is 1920x1080

**Comment by shannah** [comment]
I have made some changes that might fix it.   If you're working with CN1 source, you can try this right away (it doesn't rely on anything on the server).

NOTE: Added environment variable `CN1_RETINA_SCALE` and Java System property `cn1.retinaScale` to override the scaling.  Java System property takes highest priority if set, then environment variable, then the platform calculation.

**Comment by shannah** [comment]
If you do run this,  watch the console output on launch (in simulator) as it will say what retina scale value it is using.

**Comment by jsfan3** [comment]
I compiled the new sources. The log shows `Retina Scale: 1.0` when I run an app. However the text of the Codename One Settings is quite unreadable:
![toosmall](https://user-images.githubusercontent.com/1997316/44804899-08d5c580-abc3-11e8-9caf-57900624c6db.png)

**Comment by jsfan3** [comment]
You can read the `Retina Scale: 1.0` in the attached screenshot...

**Comment by shannah** [comment]
Actually... my bad.  You need to rebuild the Settings project (which you can't do), to get these changes in Settings.  Updating your JavaSE will just affect the simulator - not Codename One settings.

*However*  The fact that your simulator reports that retina scale is 1.0 suggests that I was wrong about this being related to HiDPI.  Since you have the same problem with Netbeans IDE's fonts, this is more likely related to the JDK.  I.e. it's a java bug.  

Probably I'll need to enable you to just customize the font sizes in the app like Netbeans allows.

**Comment by shannah** [comment]
I have added an additional environment variable and system property.  `CN1_FONT_SCALE` and `cn1.fontScale` respectively.  System property takes priority if set.  Then env var.  Default is 1.0. 

You should be able to set an appropriate value in your environment to get the result you desire.

https://github.com/codenameone/CodenameOne/commit/21461e529c4b4db9bb05967551a7e7c0e3fb8d95

I'm going to leave this issue open and move it to 6.0 target, because I would like to expand on this to allow adjusting this at runtime via some sort of Font size menu.

**Comment by jsfan3** [comment]
If I recompile the Codename One sources I can enlarge the fonts, or do I have to wait the Friday update?

To set the environment variable, do I have to write the following command in a Bash shell?
`$ export CN1_FONT_SCALE=2.0`

Will it affect also the Simulator?

**Comment by shannah** [comment]
Yes `export CN1_FONT_SCALE=2.0` is correct.

I have just made another change, removing this environment variable from the JavaSE project, and moved it into the GUI builder/Settings projects themselves.  You'll need to wait for the next update of them... (I think that'll be friday).

Works the same way as I described before, just will only work in Settings/GUI builder apps - won't affect the simulator.

**Comment by jsfan3** [comment]
Thank you very much! :-)

**Comment by codenameone** [comment]
We pushed an update of those recently so we won't push a full update again. We'll do it in the next couple of weeks in preparation of 5.0

**Comment by jsfan3** [comment]
Ok

**Comment by shannah** [comment]
@jsfan3 Is there anything more that needs to be done on this issue, or do you consider it resolved?

**Comment by jsfan3** [comment]
I consider it resolved because I start Netbeans using this Bash script:
```
#!/bin/bash
export CN1_FONT_SCALE=1.7
/home/francesco/NetBeans_IDE_10.0/bin/netbeans --fontsize 20
```

but I guess that this issue is resolved only for me and for lucky people with big high-density screens who read this thread. I suggest to document the `export CN1_FONT_SCALE=x.x` trick or do something to make the users aware of this save-eyes feature.

**Comment by shannah** [comment]
I have added a preferences/settings dialog to the CN1 settings and GUI builder apps that will allow you to adjust the font scaling.  The scaling specified in this dialog will override the environment variable that you set on the command-line.

![image](https://user-images.githubusercontent.com/2677562/52231159-111ae680-286e-11e9-9f6e-c3ee3655fd77.png)

This will be available in the next update.

**Comment by jsfan3** [comment]
Great! Thank you

**Comment by jsfan3** [comment]
@shannah After more than a year, I come back to write to you about this thread. I'm still using `export CN1_FONT_SCALE=1.7` and I'm fine with that, anyway, if I wanted to access the window you showed in your last comment, where would I find it?

**Comment by shai-almog** [comment]
In the File menu you should see a settings option and this dialog added by Steve. I see this on my Mac.

**Comment by jsfan3** [comment]
I can't find it, could you please be more clear? In the simulator and in the "Codename One Preferences" window there is no "File" menu, where should I click? Thank you

**Comment by shai-almog** [comment]
Sorry. It seems the windows version didn't add it to the settings app. Only the GUI builder. We'll fix this.

**Comment by jsfan3** [comment]
Thank you. However I use Linux.

**Comment by shai-almog** [comment]
Sorry, I meant to say "not Mac" ;-)
Mac has different menu layouts so it's a special case. Both @shannah and I use Macs by default so we both saw this menu.
