### ISSUE TITLE
[BUG Javascript port] Text written inside a TextComponent moves when it loses the focus

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2541]
Please try this very simple code with native theme, ported to Javascript:
```
Form hi = new Form("Hi World", new TextModeLayout(1,1));
hi.add(new TextComponent());
hi.show();
```

The text is so while you are writing (note that it's not perfectly centered):
![input_component_1](https://user-images.githubusercontent.com/1997316/44953194-0d83cd80-ae92-11e8-9ae1-b09583611529.png)

and so after losing the focus, now it's centered (for example after clicking out of the InputComponent):
![input_component_2](https://user-images.githubusercontent.com/1997316/44953216-14aadb80-ae92-11e8-89e6-956b45d0ecd1.png)

This effect of "not centered" before and "centered" after produces a small motion of the text.

These screenshots are taken with Firefox on Linux, however there is a similar issue with Chrome on Linux and Microsoft Edge on Windows.

**Comment by codenameone** [comment]
I think it's the same as #2540

**Comment by shannah** [comment]
I have improved this.  Fractional font sizes (e.g. 18.5px) were being converted to integers when setting the text size for the native text field.  There is still a slight jump when focusing due to some hard-to-fix issues with the text baseline - but it is far less noticeable now.

**Comment by jsfan3** [comment]
Thank you! :)
