### ISSUE TITLE
iOS TextArea multiline scrolling issue

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#2543]
From:

https://stackoverflow.com/questions/52239932/textfield-with-scrollable-in-codenameone

>I implemented textfield with multiline and scrollable in y-direction. But it works weird as shown in figure below. If I add one text after other in multiline fashion, as soon as I reach the keyboard pop-up the text at top is still visible it just dont scroll till end. enter image description here enter image description here
> 
![image](https://user-images.githubusercontent.com/2677562/45297732-2b1cec80-b4bb-11e8-9cb7-698095536941.png)

![image](https://user-images.githubusercontent.com/2677562/45297717-1e989400-b4bb-11e8-9645-4213de5b28ed.png)

> As it can be seen in first image if I scroll it starts going at top of the screen and in second image it just don't show the text written at end. Any suggestions on this will be helpful. Thanks
> 
> I even used the DataChangedListener but I think that's not issue here.

~~~~
dataTextField = (TextField) uib.findByName(DESIGNER_NAME_TEXT_FIELD, container);
        dataTextField.setMaxSize(model.getMaxLength());
        if (model.isMultiLine()) {
            dataTextField.setSingleLineTextArea(false);
            dataTextField.setRows(2);
        } else {
            dataTextField.setSingleLineTextArea(true);
        }
dataTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (dataTextField != null) {
                    if (dataTextField.getText().compareTo(model.getData().toString()) != 0) {
                        updateModel(dataTextField.getText());
                    }
                }
            }
        });

        public void updateModel(String text) {
    synchronized(syncLock) {
        model.onUserDataEntered(text);
    }
}
~~~~

**Comment by poojanarshetty** [comment]
Hi, I have a container with layout set as BoxLayout.Y_AXIS in that I have TextArea and TextField.

**Comment by shannah** [comment]
Cannot reproduce.  Here is my test case

~~~~
private void testTextAreaScroll2543() {
        Form f = new Form("Scroll Test", BoxLayout.y());
        TextArea ta = new TextArea();
        ta.setRows(30);
        f.add(ta);
        f.show();
    }
~~~~

Please modify this test case to a form to make it reproducible.

**Comment by poojanarshetty** [comment]
Hi, 
This is how I implemented,
[textfieldImplementation.txt](https://github.com/codenameone/CodenameOne/files/2370236/textfieldImplementation.txt)

I tried your method already, I dont want to set rows to 30 or more then 10. I want to set it as 2 so that it grows when user had more data to insert.

**Comment by poojanarshetty** [comment]
@shannah Hi, Were you able to reproduce this issue?

**Comment by shannah** [comment]
Still can't reproduce this issue with your test case.

**Comment by poojanarshetty** [comment]
Thanks for reply. That's fine even by that case you can that issue. Let me know when it's reproduced or the solution for that as I tried different method I still get the same.

**Comment by poojanarshetty** [comment]
Hi, Are you able to reproduce the error? If not, please let me know I can help you out. Thanks

**Comment by shannah** [comment]
No I can't reproduce the problem.  You can help by providing a self-contained test case that will reproduce the problem.

**Comment by poojanarshetty** [comment]
Thanks for your reply. Can you please use the textboxpeer.txt case file attached here. I am using the same thing in my app. The other text file is listener class for TextField in case you need it. If you need any other information let me know.
[textboxpeer.txt](https://github.com/codenameone/CodenameOne/files/2379759/textboxpeer.txt)
[TextFieldListenerHelper.txt](https://github.com/codenameone/CodenameOne/files/2379760/TextFieldListenerHelper.txt)

**Comment by poojanarshetty** [comment]
Hi, Apologies for that. So, here is the test case, by which you can reproduce the error.
`               Container container= new Container();
		container.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
		int margin= Display.getInstance().convertToPixels(3, false);
		container.getStyle().setMargin(Container.BOTTOM, margin);
		container.setScrollableY(true);
		TextField dataTextField= new TextField();
		dataTextField.setMaxSize(4000);
		dataTextField.setConstraint(TextArea.ANY);
            // for multiline textfield		
			dataTextField.setSingleLineTextArea(false);
			dataTextField.setRows(2);
			dataTextField.setGrowByContent(true);
			dataTextField.setScrollVisible(true);
		
		container.add(dataTextField);
		
			dataTextField.addActionListener(new ActionListener<ActionEvent>() {

				@Override
				public void actionPerformed(ActionEvent evt) {
				if(dataTextField!=null) {
					dataTextField.getText();
					
				}
					
				}
			});`

I tried this and I get the same thing, just fill the textbox till it overlaps with keyboard, and as soon as you enter the text here it dont scroll and get stuck at keyboard, Even it scrolls it just goes at top as was shown in figure. I hope this helps. If you cant reproduce the error let me know, I can provide other ways. Thanks

**Comment by poojanarshetty** [comment]
@shannah Hi, Were you able to reproduce the error ?

**Comment by poojanarshetty** [comment]
@shannah any updates?

**Comment by shannah** [comment]
Just tried the test case and can't reproduce the issue.

**Comment by poojanarshetty** [comment]
@shannah Hi, I am reproducing by same thing. Its like you need to add text till you reach the keyboard view. But, the text dont scroll and it results in overlapping of text with keyboard.

**Comment by shannah** [comment]
I did exactly that.  Added text until it overlaps the keyboard.   It seems to scroll ok for me.  Iphone 8 / iOS 11.4.

What device and version of iOS are you using?

**Comment by poojanarshetty** [comment]
I am using Iphone 7/ iOS 11.4 and iPad Mini/ iOS 11.4. I still get that error, it dont scroll for me, the first line of text is still visible to me and if I try to scroll the text goes outside the container as in image.

**Comment by shannah** [comment]
That photo was not taken from your test case.  Can you share a photo of your test case behaving this way?  And/Or post a screencast of it.

**Comment by poojanarshetty** [comment]
@shannah So, this I implemented exactly as in my test case and tested on iPad Mini, so the text just scrolls above the textbox leaving the area.
![img_0052](https://user-images.githubusercontent.com/14349952/45764293-51185e80-bc2a-11e8-82c0-8901ab4d18b9.PNG)
![img_0053](https://user-images.githubusercontent.com/14349952/45764294-51185e80-bc2a-11e8-94c3-21304728778a.PNG)

**Comment by shannah** [comment]
That isn't the self-contained test case that you posted.

**Comment by poojanarshetty** [comment]
but I am using the same test case, you have a look in the code below. I didnt change anything in test case, its exactly same. Just the logo is set nothing else.
![capture](https://user-images.githubusercontent.com/14349952/45765493-0d732400-bc2d-11e8-8f1b-627c62d1d4e3.PNG)

**Comment by shannah** [comment]
Here is the self-contained test case I'm using:

~~~~
private void testTextAreaScroll2543() {
        Form f = new Form("Scroll Test", new BorderLayout());
        Container container= new Container();
        container.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        int margin= Display.getInstance().convertToPixels(3, false);
        container.getStyle().setMargin(Container.BOTTOM, margin);
        container.setScrollableY(true);
        TextField dataTextField= new TextField();
        dataTextField.setMaxSize(4000);
        dataTextField.setConstraint(TextArea.ANY);
    
        dataTextField.setSingleLineTextArea(false);
        dataTextField.setRows(2);
        dataTextField.setGrowByContent(true);
        dataTextField.setScrollVisible(true);
        container.add(dataTextField);
        dataTextField.addActionListener(new ActionListener<ActionEvent>() {

                @Override
                public void actionPerformed(ActionEvent evt) {
                if(dataTextField!=null) {
                        dataTextField.getText();

                }

                }
        });
        
        
        f.add(BorderLayout.CENTER, container);
        f.show();
    }
~~~~

Please modify it so that it reproduces the issue.

**Comment by shannah** [comment]
Still can't reproduce.  Haven't heard back from OP with respect to a test case.  iOS text editing has undergone many improvements since this issue was posted so it is likely this has already been fixed.
