### ISSUE TITLE
Cobobox Options From Gui

### ISSUE THREAD

**Issue by ChristoforosKor** [codenameone/CodenameOne#2549]
Combobox can not be set up from new Gui Builder.
When I am setting options from inside the gui builder the are not shown. The combobox shows as empty in the simulator.

**Comment by codenameone** [comment]
Relevance link: https://stackoverflow.com/questions/52352388/how-to-configure-combobox-from-gui-builder/52360614

**Comment by shannah** [comment]
Fixed.  Will be included in next plugin update.
