### ISSUE TITLE
loosing image buttons or buttons after updating to iOS 12

### ISSUE THREAD

**Issue by poojanarshetty** [codenameone/CodenameOne#2553]
Hi, I am been using codenameone from last 4years and have our app in App-Store. We acknowledged weird thing when we updated from device to iOS 12, all the buttons or can say image buttons from the form are no more visible. For Eg: from second image, it can be seen that there is photo at center and image button at north of component, which is actual design and worked fine these many years and  till iOS 11.4. When our customers updated the device to iOS12, the image buttons are no longer visible, its happening something this away, when you open the form either no buttons are visible or only one or two buttons are visible as in image 1 below. Is anything broke out here? Please any suggestions on this will be very helpful. As we need to resolve this asap.  Thanks 

                  `
                                             

                      class Screen extends Form{
                                              setLayout(new BorderLayout());
                                          this.getTitleArea().setPreferredH(0);
                                      //photoContainer, where image is placed as imageViewer
                                        Container photoContainer= buildPreviewPane();
                                       addComponent(BorderLayout.CENTER, photoContainer);
                                       buildCommandBar();
                                          }

                   protected Container buildPreviewPane()	{
		Container cont = new Container();	
		cont.setLayout (new BorderLayout());
		getStyle().setMargin(0,  0, 0, 0);
		getStyle().setPadding(0,  0, 0, 0);
		cont.addComponent (BorderLayout.CENTER, new Label("  "));
		
		return cont;
	}

	protected void buildCommandBar(){
	Container c = new Container();
	c.setLayout(new BoxLayout(BoxLayout.X_AXIS));
	c.getStyle().setPadding(Component.TOP, 40);
		
		
		int size = Display.getInstance().convertToPixels(4,  false);
		if (Display.getInstance().isTablet()) {
			size *= 2;
		}
		
		Button deleteCommand = new Button();
			try {
				Image im = Image.createImage("/Delete-64-lygrey.png").scaled(size - 2, size - 2);
				deleteCommand.setIcon(im);
			}
			catch (Exception e){}
			c.addComponent(deleteCommand);
			
		Button okCommand = new Button();
		try {
			Image im = Image.createImage("/Checked-64-ltgrey.png").scaled(size - 2, size - 2);
			okCommand.setIcon(im);
		}catch (Exception e){}
		c.addComponent(okCommand);
		
		addComponent(BorderLayout.NORTH, c);
	
	}`
![rsz_img_0057](https://user-images.githubusercontent.com/14349952/45829885-cc921280-bcf3-11e8-8eec-af8ea63c2023.png)
![rsz_img_0055](https://user-images.githubusercontent.com/14349952/45829887-cd2aa900-bcf3-11e8-90f0-0abb4efe91b8.png)

**Comment by shannah** [comment]
I haven't tried your test case out yet specifically, but I've updated to iOS 12, and run a number of my existing apps, and haven't noticed any trouble yet.  I'll give your test case a try as soon as I can.  But if you have a chance to experiment, it would be interesting to know a couple of things:

1. Is it the icons that aren't showing up, or the buttons themselves?  E.g. What if you use the same Image for both buttons.  Do they both show up, or both disappear, or no change?  And if you add a text label for the buttons, does the text show up.

2. You're swallowing a couple of exceptions.  (i.e. `catch (Exception e) {}`).  It would be interesting to know if there are any exceptions there.

**Comment by poojanarshetty** [comment]
Hi, Thanks for your reply. Here, is the workaround I tried:
1. I have added labels to button instead of images and they work fine.
2. Adding same image to both buttons, sometimes both are visible and sometimes either of one or both aren't visible.
3. I debugged on Xcode, and screenshot shows the error I got.
4. The exception gives me null, whenever the image becomes invisible.

Any workaround on this will be helpful. Thanks
![screen shot 2018-09-21 at 09 10 01](https://user-images.githubusercontent.com/14349952/45870030-dcf0ce80-bd81-11e8-89d6-5c9c3ac4f954.png)

**Comment by shannah** [comment]
> Adding same image to both buttons, sometimes both are visible and sometimes either of one or both aren't visible.

So given a particular image.  You're saying sometimes it shows up and sometimes it doesn't?  Or is it the case that with one image it shows up, but with another image it doesn't?

Since you're already debugging in Xcode, the interesting point to monitor is the com_codename1_impl_ios_IOSNative_createNSDataResource___java_lang_String_java_lang_String function in iOSNative.m (lines 1278 to 1288).  This is there the NSData gets created which ends up null causing the EXC_BAD_ACCESS in your screenshot.

A stab in the dark:  Perhaps the path/filename for one of the images is incorrect.  Pay close attention to case sensitivity.

**Comment by poojanarshetty** [comment]
Hi, 
With particular image it shows sometimes and sometimes it don't. Suppose I have 4 image buttons on form, it should show all 4, but sometimes it shows only 3, 2 or sometimes all 4. 
And the path/ filename are correct for all images, that's why I can see all images sometimes. 
P.S: the same thing working on iOS 11.4.1

**Comment by shannah** [comment]
Can you provide the images that you're using?  (upload them somewhere as a zip, so I can be sure I'm using the exact same images).

**Comment by poojanarshetty** [comment]
I uploaded to google drive, here is the link: [https://drive.google.com/file/d/1fr1jUl-A1573cGmJVzUPzgh9g69kZ_h6/view](url)

**Comment by shannah** [comment]
Thanks.  I got them.

**Comment by poojanarshetty** [comment]
Hi, any updates on this issue ?

**Comment by poojanarshetty** [comment]
@shannah Hi, any updates or any solution on  this issue?

**Comment by poojanarshetty** [comment]
@shannah  Hi, Were you able to reproduce the issue? It will be very helpful, if I get any workaround on this. Because I am able to reproduce the issue. Thanks

**Comment by shannah** [comment]
No updates yet.  It is in my queue

**Comment by shannah** [comment]
I reproduced the problem in the CN1 simulator.  The Checked-64-ltgrey.png image doesn't show up for me.  I opened it up in preview, and re-saved it.  Then when I used the new image instead, it worked fine.

It appears that some of the images are either corrupt, or have characteristics that Apple can't seem to handle.
