### ISSUE TITLE
App icon showing after Splash screen image

### ISSUE THREAD

**Issue by ChrisLace** [codenameone/CodenameOne#2554]
App Icon is still displaying after Splash Screen with necessary following build hints:

1. ios.multitasking = false 
2. ios.generateSplashScreens = true

Please fix this issue.

**Comment by bbeckk** [comment]
HI @shannah  how long it will take to solve this issue? I asked Shai and he referred to you. How can I disable the app icon as splash screen? 

Regards

**Comment by shannah** [comment]
I can't reproduce this issue.  Notice, that iOS keeps the launch screens cached for apps even after you reinstall the app.  If you want to change the launch screen, you need to 

1. Uninstall the app
2. Restart the device
3. Reinstall the app

(As described at https://github.com/expo/expo/issues/1918#issuecomment-419015690)

There are quite a few SO threads of people running into this same problem with iOS launch screens.  Possible solutions/non-solutions are discussed in this thread for example.  https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update

**Comment by ChrisLace** [comment]
Hi Shannah, I don't agree. This is happening everytime with my debug builds. I have tried the way it was mentioned in the links. Please advise.

Thanks

**Comment by shannah** [comment]
If you change your app icon, does it cause the icon in the app splash screen to also change?

**Comment by ChrisLace** [comment]
Yes Shannah. Correct. I have tested it now.

**Comment by ChrisLace** [comment]
icon will appear after the splash screen image display.  First Splash Screen image will show up and immediately icon will show up and then go to login screen. Please advise.

**Comment by shannah** [comment]
I still can't reproduce.  

Can you post a video that demonstrates this?

**Comment by bbeckk** [comment]
I've the same issue. Have a look at the video
https://youtu.be/Z5E4hFsBdIg

**Comment by shannah** [comment]
Can you post your build hints?  Particularly any hints related to ios.

**Comment by ChrisLace** [comment]
I have used following build hints : ios.multitasking = false and ios.generateSplashScreens = true

**Comment by ChrisLace** [comment]
Shannah, For me it was other way around, splash screen image display first and icon will display next. Thanks

**Comment by ChrisLace** [comment]
this is the link to the ticket in stackoverflow: https://stackoverflow.com/questions/52156962/app-icon-showing-before-splash-screen-image-on-mobile-app

**Comment by ChrisLace** [comment]
Shannah, I have re-used codenameone logo and splash screen where I'm not able to reproduce the issue. Again, If I go to my splash screen image and icon it starts appearing. Do you think any reason why this could be happening. Thanks

**Comment by shannah** [comment]
Please copy and paste your build hints from the codenameone_settings.properties file.  I want to see them all, exactly as they are in the project.  (Of course mask/redact confidential items).

**Comment by ChrisLace** [comment]
Please see the settings file:

#Fri Sep 28 02:20:24 PDT 2018
codename1.ios.appid=MASKED
codename1.ios.release.provision=/C\:/iosCerts/production_provisioning_profile.mobileprovision
codename1.arg.java.version=8
codename1.arg.rim.obfuscation=false
codename1.arg.ios.newStorageLocation=true
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.arg.ios.project_type=ios
codename1.arg.ios.generateSplashScreens=true
codename1.arg.ios.keyboardOpen=false
codename1.arg.ios.interface_orientation=UIInterfaceOrientationPortrait\:UIInterfaceOrientationPortraitUpsideDown\:UIInterfaceOrientationLandscapeLeft\:UIInterfaceOrientationLandscapeRight
codename1.displayName=Test Mobile
codename1.android.keystoreAlias=TestMobile
codename1.arg.android.asyncPaint=true
codename1.ios.release.certificate=/C\:/iosCerts/appstore_certificate.p12
codename1.android.keystorePassword=MASKED
codename1.ios.provision=
codename1.arg.ios.add_libs=SystemConfiguration.framework;LocalAuthentication.framework
codename1.arg.ios.dsym=false
codename1.arg.android.release=true
codename1.arg.ios.statusbar_hidden=false
codename1.languageLevel=5
codename1.android.keystore=C\:\\Users\\test\\keystore.ks
codename1.vendor=CodenameOne
codename1.arg.win.ver=8
codename1.arg.ios.locationUsageDescription=Location is used to coordinate appointments and directions
codename1.ios.certificatePassword=
codename1.ios.debug.certificatePassword=password
codename1.mainName=Main
codename1.ios.release.certificatePassword=password
codename1.arg.ios.prerendered_icon=false
codename1.ios.debug.certificate=/C\:/iosCerts/development_certificate.p12
libVersion=211
codename1.arg.ios.applicationQueriesSchemes=comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps
codename1.arg.android.xpermissions=<uses-permission android\:name\="android.permission.ACCESS_NETWORK_STATE"/><uses-permission android\:name\="android.permission.USE_FINGERPRINT" />
codename1.arg.ios.application_exits=false
codename1.secondaryTitle=CodenameOne_Template 
codename1.description=
codename1.ios.debug.provision=/C\:/iosCerts/development_provisioning_profile.mobileprovision
codename1.arg.j2me.nativeThemeConst=0
codename1.rim.certificatePassword=
codename1.version=1.0
codename1.ios.certificate=
codename1.icon=icon.png 
codename1.rim.signtoolCsk=
codename1.arg.ios.plistInject=<key>LSApplicationQueriesSchemes</key><array><string>comgooglemaps</string></array>
codename1.arg.android.debug=false
codename1.rim.signtoolDb=
codename1.arg.ios.includePush=true
codename1.arg.ios.testFlight=true
codename1.packageName=MASKED

**Comment by bbeckk** [comment]
Mine looks like this:

![9-28-2018 8-45-52 pm](https://user-images.githubusercontent.com/13558880/46216560-9857cb00-c35f-11e8-8a38-a77f3881b6af.png)

**Comment by ChrisLace** [comment]
Shannah,  did you able to re-produce the issue with build hints?

**Comment by shannah** [comment]
No.

**Comment by bbeckk** [comment]
I have the build setting ios.generateSplashScreens = false. Making it ios.generateSplashScreens = true worked. @ChrisLace  I dont see ios.multitasking = false.  See if it is missing in your build hints

**Comment by ChrisLace** [comment]
It was part of the build hints. I have tested it both with and without build hints. I'm reproduce this issue.

**Comment by codenameone** [comment]
Make sure to include the build hints, uninstall the app. Reboot the phone and install the app with both build hints. The reboot is important because iOS caches the splash screen file!

**Comment by ChrisLace** [comment]
I have tried all the possible ways still it didn't help. Does the build hints in the order it was mentioned has any impact. Please advise.

Thanks

**Comment by codenameone** [comment]
The order doesn't matter. Can you post a new update of the listing of your `codenameone_settings.properties` file with the proper build hints?

**Comment by ChrisLace** [comment]
codename1.ios.appid=MASKED
codename1.ios.release.provision=
codename1.arg.java.version=8
codename1.arg.rim.obfuscation=false
codename1.arg.ios.newStorageLocation=true
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.arg.ios.project_type=ios
codename1.arg.ios.generateSplashScreens=true
codename1.arg.ios.multitasking=false
codename1.arg.ios.keyboardOpen=false
codename1.arg.ios.interface_orientation=UIInterfaceOrientationPortrait:UIInterfaceOrientationPortraitUpsideDown:UIInterfaceOrientationLandscapeLeft:UIInterfaceOrientationLandscapeRight
codename1.displayName=Test Mobile
codename1.android.keystoreAlias=TestMobile
codename1.arg.android.asyncPaint=true
codename1.ios.release.certificate=/C:/iosCerts/appstore_certificate.p12
codename1.android.keystorePassword=MASKED
codename1.ios.provision=
codename1.arg.ios.add_libs=SystemConfiguration.framework;LocalAuthentication.framework
codename1.arg.ios.dsym=false
codename1.arg.android.release=true
codename1.arg.ios.statusbar_hidden=false
codename1.languageLevel=5
codename1.android.keystore=
codename1.vendor=CodenameOne
codename1.arg.win.ver=8
codename1.arg.ios.locationUsageDescription=Location is used to coordinate appointments and directions
codename1.ios.certificatePassword=
codename1.ios.debug.certificatePassword=password
codename1.mainName=Main
codename1.ios.release.certificatePassword=password
codename1.arg.ios.prerendered_icon=false
codename1.ios.debug.certificate=/C:/iosCerts/development_certificate.p12
libVersion=211
codename1.arg.ios.applicationQueriesSchemes=comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps,comgooglemaps
codename1.arg.android.xpermissions=<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/><uses-permission android:name="android.permission.USE_FINGERPRINT" />
codename1.arg.ios.application_exits=false
codename1.secondaryTitle=CodenameOne_Template
codename1.description=
codename1.ios.debug.provision=
codename1.arg.j2me.nativeThemeConst=0
codename1.rim.certificatePassword=
codename1.version=1.0
codename1.ios.certificate=
codename1.icon=icon.png
codename1.rim.signtoolCsk=
codename1.arg.ios.plistInject=LSApplicationQueriesSchemescomgooglemaps
codename1.arg.android.debug=false
codename1.rim.signtoolDb=
codename1.arg.ios.includePush=true
codename1.arg.ios.testFlight=true
codename1.packageName=MASKED

**Comment by ChrisLace** [comment]
Please see the attached codenameone_settings.properties

**Comment by codenameone** [comment]
Odd, this looks OK. @shannah do you have any ideas?
Which device/OS version are you seeing this on? I'll try it too.

**Comment by ChrisLace** [comment]
iPhone 6S Plus + Version 11.4.1(15G77)
There is an issue for sure. I always see this.

**Comment by ChrisLace** [comment]
@shannah: Is there any ETA or update on this? Please advise.

**Comment by ChrisLace** [comment]
This is code of splash screen form if this makes any difference:

 public SplashForm() {
        super(new BorderLayout());
        try {
            add(BorderLayout.CENTER, new ScaleImageLabel(Image.createImage("/APPSTORE.png")));
        } catch (IOException err) {
            Log.e(err); 
            if (!isOffline()) {
                Log.sendLog();
            }
        }
        Container box = new Container(BoxLayout.y());
        box.add(FlowLayout.encloseCenterMiddle(new InfiniteProgress())); 
        Label l1 = new Label("1.0");
        l1.setUIID("Version");
        l1.setAlignment(CENTER);
        box.add(l1);
        add(BorderLayout.SOUTH, box);
        UITimer.timer(500, false, this, () -> new LoginForm().show());
    }

**Comment by ChrisLace** [comment]
I have tried on multiple deveices and even on iPad. I see the same icon image after the splash screen. I have updated codenameone-libs and generated new ios certificates to see if that makes any difference. No luck. Please advise.

**Comment by ChrisLace** [comment]
Did you get a chance to review the codename settings file which I have sent. Did u able to reproduce the issue. Please advise.

**Comment by codenameone** [comment]
I didn't get the attached file. Did you attach the file to a chat on our site?

**Comment by ChrisLace** [comment]
i sent in email to shai@codenameone.com. Please let me know if I have to send it to some other email.

Thanks

**Comment by codenameone** [comment]
We don't specify email addresses in comments. I deleted that comment. Please attach the file in the chat. Don't embed. Attach.

**Comment by ChrisLace** [comment]
I have sent the file in the chat already. Thanks

**Comment by codenameone** [comment]
I looked at the file and I'm officially out of ideas. If you create a new project and add those two hints do you see the splash logo?

**Comment by codenameone** [comment]
I'll choc that up to an odd caching anomaly in iOS.
