### ISSUE TITLE
rotate damages the graphics object, damage persists across calls to paint

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2555]
Android only.  Simulator and IOS are fine.  This program ought to display a slowly 
rotating square, with a loop count.  On Android devices it succeeds in a small number
of iterations, then crashes.

Two things are wrong here.  The first is that rotate followed by unrotate is very unstable
and apparently there is some cumulative damage. The second is that the damage persists
across calls to paint.  I can't think of any reason, given the complexity and unpredicability
of when "paint" will be called, that initial transform shouldn't be defined to be an identity
transform.

java''''
package dtest.boardspace;
//
// this version shows that g.rotate damages the transform after a 
// few iterations, and that the damage persists across calls to paint
// sep 23 2018
//
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;

import java.util.Random;

public class Dtest  {
	
 
 
    private Form current;
    @SuppressWarnings("unused")
	private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    int loops = 0;
   
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi >>0 World");
         current = hi;
        hi.setLayout(new BorderLayout());
        hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {

            @Override
            public void paint(Graphics g) {
            	//g.resetAffine();
             	int w = getWidth();
            	int h = getHeight();
             	g.setColor(0x8f8f9f7f);
            	g.fillRect(0,0,w,h);
            	//drawImage(g,chip,-loops,-loops,w+loops,h+loops,0,0,chip.getWidth(),chip.getHeight());
            	//g.translate(150, 150);
            	float ang = (float)(loops*Math.PI/1000);
            	g.rotate(ang,w/2,h/2);
            	g.setColor(0xff00);
            	g.fillRect(300,300,500,500);
            	g.setColor(0x2020);
            	g.rotate(-ang,w/2,h/2);
            	g.drawString("Loop "+loops, 100, 100);
            	//g.translate(-150, -150);
            	loops++;
            
            	repaint();
            }
            
        });
        hi.show();
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }
    
static int pass =0;
public void testRandom(Graphics g,int x,int y)
{   pass ++;
    g.drawString("Pass "+pass,x,y);
    y+=20;
    { Random r = new Random(63546);
      for(int i=0;i<3;i++) 
        { String val = ""+r.nextLong();
          g.drawString(val,x,y);
          y+=20;
        }
    }
    y+=20;
    { Random r2 = new Random(63546);
    for(int i=0;i<3;i++) 
    { String val = ""+r2.nextLong();
      g.drawString(val,x,y);
      y+=20;
    }
    }
	}

}''''

**Comment by shannah** [comment]
Calling repaint() inside paint() seems like a bad idea.  Can you produce a test case that reproduces this issue without repaint() inside paint()?

**Comment by ddyer0** [comment]
repaint just triggers another paint request, it doesn't actually do anything.  remove the
repaint() and add 
java''''
	Runnable rr = new Runnable (){ 
		public void run() {
			System.out.println("running");
		while(true) 
		{ 
		  hi.repaint();
		  try {
			  Thread.sleep(1); 
			  }
		  
		  catch (InterruptedException e) {};
		}}};
	new Thread(rr).start();
''''
after hi.show()
