### ISSUE TITLE
CSS Borders and px

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2561]
In the developer guide:
https://github.com/codenameone/CodenameOne/wiki/css
and also here:
https://github.com/shannah/cn1-css/wiki/Supported-Properties
there are examples like this:
```
RoundBorder {
    border: 1px #3399ff  cn1-round-border;
    text-align:center;
    margin:2mm;
    padding:3mm;
}
```

I spent some time to address why these examples don't produce the desired effect. Finally I understood that the solution is to replace `1px` with `1pt`, after readering the following sentence in the Codename One blog at https://www.codenameone.com/blog/rounded-corners-shadows-and-gradients-with-css.html:

> Change all px units to pt. This will cause the coordinate to be scaled appropriate for the device density.

Maybe it can be obvious, but it wasn't so for me. So I suggest to change all the CSS examples about borders with the appropriate unit.

**Comment by shannah** [comment]
The example you posted here works fine with 1px or 1pt.

1px: 
![image](https://user-images.githubusercontent.com/2677562/46472039-b0c94a80-c790-11e8-8e7c-6e6b57a7f2ed.png)

1pt: 
![image](https://user-images.githubusercontent.com/2677562/46472067-c2aaed80-c790-11e8-9e9b-3ccb64939773.png)

**Comment by jsfan3** [comment]
You're right, 1px produces a very thin line, as expected.
Maybe I confused the problem, I tested again the code in the Simulator. A border of `1mm` works, but with `border: 0.5mm #3399ff  cn1-round-border;` no border is produced. Please try, thank you
