### ISSUE TITLE
Issue compiling to ios

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2568]
ERROR
A certificate from Apple with the appropriate password is required for building an iOS native app!
You can generate this certificate using our certificate wizard by right clicking on the project and following the steps. Notice you will need an Apple IO developer account.
BUILD FAILED (total time: 1 minute 49 seconds)

I always have used certificates generated in my mac instead your wizard from codenameone settings. Why now it's necessary to provide you my user and password from my itunes?

**Comment by codenameone** [comment]
I can't reproduce this.

**Comment by DurankGts** [comment]
Why you close this issue if you can't reproduce this?. When I update the preferences to 5.1 You demand to set the User and password of my itunnes to generate certificates. I always have generate my certificates in my own mac In now when I compile you demand this.

A certificate from Apple with the appropriate password is required for building an iOS native app!
You can generate this certificate using our certificate wizard by right clicking on the project and following the steps. Notice you will need an Apple IO developer account.
BUILD FAILED (total time: 1 minute 49 seconds)

I always have used certificates generated in my mac instead your wizard from codenameone settings. Why now it's necessary to provide you my user and password from my itunes?

**Comment by codenameone** [comment]
We don't demand any such thing. When you get a build error we provide the more common suggestion of using the certificate wizard. The wizard automates the process of generating files you can generate manually just like before.
