### ISSUE TITLE
In iPad: Combo boxes do not open selections

### ISSUE THREAD

**Issue by JTBrandao** [codenameone/CodenameOne#2571]
This issue occurs only when running on iPad. The same build (published on APP Store) runs correctely on iPhone´s. 

We´ve tested on iPhone 6s in versions 11.4.1 and 12.0 and it runs correctely.
In iPad Mini running same versions 11.4.1 and 12.0  the bug occurs.

**Comment by codenameone** [comment]
We need sample code that reproduces the issue and ideally screenshots

**Comment by JTBrandao** [comment]
We are initially attaching images which evidence the problem:

The first image was taken from the APP (downloaded from App Store) running on iPad (iOs version 12.0)  and shows a simple form containning just one select component: When we tap the selection nothing occurs:
<img width="768" alt="20181005_172017479_ios" src="https://user-images.githubusercontent.com/32176077/46549893-d6964280-c8a9-11e8-8784-c6a52e95fa18.png">

The second image was taken from the same APP (downloaded from App Store)  running on iPhone 6s (iOs Version 12.0) and shows the same simple form containning just one select component: When we tap the selection the options are presented correctly for selection:
<img width="375" alt="20181005_171931185_ios" src="https://user-images.githubusercontent.com/32176077/46549903-dd24ba00-c8a9-11e8-92f9-c48b8d01add9.png">

We´ll next work on a simple project do help isolationg the problem.

Thanks for first return.

**Comment by JTBrandao** [comment]
The link bellow has a simple project for diagnosis.
https://github.com/hrugani/cn1HtmlComboxProblem

**Comment by codenameone** [comment]
I found multiple mentions of a problem related to select in newer versions of iOS e.g. https://forums.developer.apple.com/thread/84585
The workarounds seem to vary a lot and no one knows exactly what fixed the issue but it's clearly a bug in iOS. 

@shannah One of the suggestions was to migrate to `WKWebView` which is probably something we should do regardless and it might resolve this issue. What do you think?

**Comment by JTBrandao** [comment]
If that migration to WKWEBVIEW will be compatable with the new  CN1 Bridge-Java-JavaScript-API we think this approach is valid.

**Comment by codenameone** [comment]
In that case we would probably need to make this optional. Ideally in runtime so a developer can decide. If not maybe as an `#ifdef` but that's far less ideal. By default WK would need to be disabled if this is the case. I don't think shipping a webserver by default is something we should get into.

**Comment by shannah** [comment]
This issue is related to z-layering.  I can reproduce it on both iOS 11.4 and iOS 12.0.1 on my iPad Air 2.  If I switch off Z-layering, the test case works.

Looking into it further to see if I can find a fix.
