### ISSUE TITLE
Problems on iOS 12

### ISSUE THREAD

**Issue by thomas-hutterer-tik** [codenameone/CodenameOne#2574]
My app We-Save-Energy runs very different on a iPhone x with iOS 12 than on other model with iOS 11 or lower. On iOS 12 in 4 out 5 attempts to start the app, it does some back end calls, but does not show any UI except a blank white screen. Once in about 50 attempts to start the app I have seen a NullPointer exception. In the simulator all runs fine.
Have you any hints how I can drill down the cause of this problem.
Thanks Thomas

**Comment by codenameone** [comment]
This isn't necessarily an issue so a more effective place to ask this would be the discussion forum or stackoverflow where other developers can see this and provide suggestions. We can there narrow this down to an actual issue.
If you have a pro account you should use crash protection https://www.codenameone.com/how-do-i---use-crash-protection-get-device-logs.html

If not you should still log and review the device logs https://www.codenameone.com/blog/native-logging-certificate-wizard.html

You should try to isolate the problem through a process of elimination, try commenting out as much as possible within your app until it works then slowly re-enable things until you find the culprit.
