### ISSUE TITLE
com_codename1_impl_ios_IOSImplementation.createImage throws NullPointerException on iOS 12

### ISSUE THREAD

**Issue by thomas-hutterer-tik** [codenameone/CodenameOne#2579]
2018-10-13 18:54:05.282 WseMobileApplication[1390:207073] [EDT] 0:0:4,128 - Exception: java.lang.NullPointerException - null
2018-10-13 18:54:05.284 WseMobileApplication[1390:207073] java.lang.NullPointerException
   at com_codename1_impl_ios_IOSImplementation.createImage:1056
   at com_codename1_ui_Image.createImage:524
   at org_wesaveenergy_mobile_view_DeviceView.getIcon:123
   at org_wesaveenergy_mobile_view_DeviceView.access$200:19
   at org_wesaveenergy_mobile_view_DeviceView_Line.updateIcon:79
   at org_wesaveenergy_mobile_view_DeviceView_Line.updateAll:66
   at org_wesaveenergy_mobile_view_DeviceView_Line.__INIT__:60
   at org_wesaveenergy_mobile_view_DeviceView.addLine:88
   at org_wesaveenergy_mobile_view_DeviceView.init:44
   at org_wesaveenergy_mobile_view_DeviceView.__INIT__:31
   at org_wesaveenergy_mobile_DeviceController.__INIT__:45
   at org_wesaveenergy_mobile_view_TabForm.create:41
   at org_wesaveenergy_mobile_view_TabForm.__INIT__:30
   at org_wesaveenergy_mobile_WseController.changeState:122
   at org_wesaveenergy_mobile_WseController.changeState:113
   at org_wesaveenergy_mobile_WseController.changeState:104
   at org_wesaveenergy_mobile_WseController.changeState:97
   at org_wesaveenergy_mobile_WseController.__INIT__:50
   at org_wesaveenergy_mobile_WseMobileApplication.start:47
   at org_wesaveenergy_mobile_WseMobileApplicationStub.run:31
   at com_codename1_ui_Display.processSerialCalls:1129
   at com_codename1_ui_Display.mainEDTLoop:924
   at com_codename1_ui_RunnableWrapper.run:120
   at com_codename1_impl_CodenameOneThread.run:176
   at java_lang_Thread.runImpl:153
2018-10-13 18:54:05.284 WseMobileApplication[1390:207073] 

This relates to my previous issue: https://github.com/codenameone/CodenameOne/issues/2574

**Comment by codenameone** [comment]
What do you pass `Image.createImage()` in `DeviceView.getIcon` line 123?

**Comment by thomas-hutterer-tik** [comment]
The parameter is "/if_Circle_Yellow_34215.png"
![if_circle_yellow_34215](https://user-images.githubusercontent.com/1253130/46932192-d6870700-d04e-11e8-9470-186695fffd88.png)

**Comment by codenameone** [comment]
Try isolating it into a test case we can run. But I would suggest just moving the file into the resource file and loading it via getImage() on the theme object. It's more portable in that sense and avoids some OS oddities like this one.

**Comment by poojanarshetty** [comment]
this issue is same as raised by me in issue #2553. So, the workaround is to add images to resource folder and load it via getImage(), this issue exists only on iOS 12.

**Comment by shannah** [comment]
If it is indeed the same as issue #2553, then an alternate workaround is to simply re-save the image using an image program - iOS was just having trouble reading those particular images for some reason.

**Comment by thomas-hutterer-tik** [comment]
I pass to it the name of png file included in the jar: "/if_Circle_Yellow_34215.png"
![if_circle_yellow_34215](https://user-images.githubusercontent.com/1253130/47461084-3e241b80-d7e0-11e8-8e1b-2f18722180df.png)

**Comment by codenameone** [comment]
If that specific PNG file is encoded in a way that iOS no longer reads there isn't much we can do. Just open it in a paint program and save it again. This is a bug/issue in iOS itself see: https://stackoverflow.com/questions/51776681/error-when-loading-png-image
