### ISSUE TITLE
RFE: add build hint to support iOS universal link

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2581]
There was some misunderstanding about what I asked here: https://stackoverflow.com/questions/52807700/intercept-an-url-with-a-given-domain-in-the-android-ios-and-javascript-ports-of
(I added two comments to the Shai's answer to better specify what I asked)

Searching on the web, I found that what I asked is described in the Apple documentation at this page:
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

So, while Android is able to do what I asked using a build hint like the following (in which the schema is "https" and the "host" is a custom domain):
`android.xintent_filter=<intent-filter><action android:name="android.intent.action.VIEW" /><category android:name="android.intent.category.DEFAULT" /><category android:name="android.intent.category.BROWSABLE" /><data android:host="example.com" android:scheme="https" /></intent-filter>`
iOS requires a lot of more work. Apple calls with feature "universal link".

While the `apple-app-site-association` file is a JSON that I can manually write and upload to the server that host the javascript port of the app, it's impossible for me to do what Apple requires to do in Xcode in the linked documentation. Essentially I need a build hint to specify the associated domains. 

I tried to open the Apple Developer Console to add manually the domain, but there is no edit button, as you can see in the following screenshot, so that's why I suppose that a build hint is necessary.

![associatedomains](https://user-images.githubusercontent.com/1997316/46953945-8a0feb80-d08f-11e8-9600-d1d780b43a98.png)

**Comment by codenameone** [comment]
If I understand correctly you just need to check the box next to associated domains then using the web UI you can go to the provisioning profiles section and regenerate both provisioning profiles.

**Comment by jsfan3** [comment]
I've done as you suggested: I checked the box next to associated domains then, using the web UI, I regenerated (and downloaded) both provisioning profiles. But after these operations, there is not any "Edit" button near the Associated Domains, so I cannot specify the domain of my web-app... any other idea? Thank you

**Comment by codenameone** [comment]
I've read a bit about this here: https://help.apple.com/xcode/mac/current/#/dev55e137b57 and https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains?language=objc

Based on my understanding we'll need to provide a build hint to add the associated domains to the entitlements file after you do the above. @shannah can you take this?

**Comment by shannah** [comment]
Yes. I can take this

**Comment by shannah** [comment]
I added ios.associatedDomains build hint.

https://github.com/codenameone/CodenameOne/wiki/Advanced-Topics-Under-The-Hood/_compare/98273000e17df0efdd7c0044d9d29a1952bbf982...ec12cc8ccbd6fd95c400cc6df9128098d46f44dc

It takes a comma-delimited list of domains in the same form that you would add them in Xcode (https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains?language=objc)

**Comment by shannah** [comment]
You'll have to wait for the update.

**Comment by jsfan3** [comment]
@shannah I have a problem with the universal links.
I have the build hint `ios.associatedDomains=mydomain.com` and I checked my SSL signed `apple-app-site-association` with https://branch.io/resources/aasa-validator/ and https://limitless-sierra-4673.herokuapp.com/, both of them returns that my JSON is valid. On the Apple Developers website, in the development provision profile of the app I enabled the service "Associated Domains" and then I regenerated the provisioning files using the Codename One wizard. I also configured Apache to return the correct mimetype for `apple-app-site-association`.

But... it doesn't work. I removed and installed a new build of the iOS app, but after tapping a link that point to the app domain, Safari opens. I tried several times.

Do universal links work for you?

**Comment by shannah** [comment]
When you upload your ipa to that validator, does it validate ok?

I'm pretty sure that universal links were working for me, but I was only using it in a test app while developing this feature - nothing production.  I'm a little hazy on the details.

**Comment by shannah** [comment]
So when you log into apple developer and look at the provisioning profile, does it list that it has the associated-domains permission?  

![image](https://user-images.githubusercontent.com/2677562/51048694-856cad80-1580-11e9-8cd4-b48f969b280a.png)

Perhaps try downloading the provisioning profile from there and using that.  Just to see if that makes a difference.

**Comment by jsfan3** [comment]
Yes, I have the "Associated Domains" service enabled, as in your screenshot (without it the Codename One iOS build server doesn't compile). I downloaded and used the file as you suggested, but there is no difference (I also verified that there is no difference using the `diff` command).

When I reinstalled the app, I kept my webserver logging opened, and I noticed this line when the app was just installed:
```
79.37.83.239 - - [11/Jan/2019:18:41:29 +0100] "GET /.well-known/apple-app-site-association HTTP/1.1" 200 5743 "-" "swcd (unknown version) CFNetwork/976 Darwin/18.2.0"
```
So it means that my iPhone automatically downloaded the `apple-app-site-association` file with an http response code 200. So, it seems fine. But trying to open a link in my Protonmail app that points to the same domain (or better, subdomain) specified in `ios.associatedDomains=subdomain.domain.com` does nothing of special, it simply opens it in Safari.

I also tried to change the `paths` array of my JSON from:
```
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "12345ABC90.mypackage",
                "paths": [ "*" ]
            }
        ]
    }
}
```

to:
```
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID":  "12345ABC90.mypackage",
                "paths": [
                    "/",
                    "/*"
                ]
            }
        ]
    }
}
```

but nothing changed.

Tested on iPhone X, iOS 12.1.2

**Comment by shannah** [comment]
I see a possible issue.  I did a search on github for the plist entries that are used for this.  Here is one example:

https://github.com/vineetchoudhary/iOS-Universal-Links/blob/master/Universal%20Links/Universal%20Links/Universal%20Links.entitlements

~~~~
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:vineetchoudhary.github.io</string>
		<string>applinks:www.vineetchoudhary.github.io</string>
	</array>
</dict>
</plist>
~~~~

Notice that his domains are prefixed with `applinks:`.  This is as opposed to `webcredentials:`.  So your build hint would need to be `ios.associatedDomains=applinks:subdomain.domain.com`

**Comment by jsfan3** [comment]
Excellent! You solved the issue, the correct build hint is `ios.associatedDomains=applinks:subdomain.domain.com`

I suggest to update the documentation.

**Comment by shannah** [comment]
I've added a note in the wiki about this

https://github.com/codenameone/CodenameOne/wiki/Advanced-Topics-Under-The-Hood/_compare/ec12cc8ccbd6fd95c400cc6df9128098d46f44dc...7f6e873528bc3bc70f105c82a74e77ffadb1709c

**Comment by jsfan3** [comment]
Thank you!
