### ISSUE TITLE
FCM Messages Are Silent By Default

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2583]
They should play the default notification sound by default for types 0, 1 & 3.

**Comment by shannah** [comment]
Strange.  Looking at the code, it should already play a sound for those types.

https://github.com/codenameone/BuildDaemon/blob/master/src/com/codename1/build/daemon/android/CN1FirebaseMessagingService.javas#L110-L113

I'll fire up the old test push app and see if I can reproduce.

**Comment by codenameone** [comment]
Odd, I see this with the builder app. There is no sound even though other apps play a sound on notifications. Sound works fine on iOS

**Comment by shannah** [comment]
Could be related to the notification channel, which is used in API 26 and higher.

https://developer.android.com/training/notify-user/channels

It is set up here

https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java#L6311

It doesn't look like we're setting the sound explicitly.

https://developer.android.com/reference/android/app/NotificationChannel.html#setSound(android.net.Uri,%20android.media.AudioAttributes)

Probably just need to add that

**Comment by shannah** [comment]
Actually, it'll be a bit more complicated.  Currently we use a single notification channel for the app.  It doesn't distinguish between the types.  Might need to create separate channels for each push type.

**Comment by shannah** [comment]
After playing with this a bit, you can get a sound by just changing the importance level of the notifications for the app.

You can do this in Settings > Apps & Notifications > (Your app) 

![image](https://user-images.githubusercontent.com/2677562/47034004-099ec880-d12b-11e8-9e5d-cb1f34736714.png)

![image](https://user-images.githubusercontent.com/2677562/47034033-158a8a80-d12b-11e8-8e7d-5951c5b0b308.png)

![image](https://user-images.githubusercontent.com/2677562/47034086-3521b300-d12b-11e8-843f-5e263ba04e44.png)

Currently, the default importance level is "Low", which results in no sound.  

You can change the default to "High", by setting

`Display.getInstance().setProperty("android.NotificationChannel.importance", "4");`

inside your `init()` method.

Might still be a good idea to have separate notification channels for each type of notification.  Currently each app just has a single channel named "Notifications" that allows the user to configure how they want the app's notifications to work.

**Comment by codenameone** [comment]
Yes. I'd also set the default importance to 4 because that would match historic behavior better

**Comment by shannah** [comment]
I have changed the default to "high".

**Comment by DurankGts** [comment]
This issue in repeating in the android 10. The notifications is set by default in silent. How can enable alert by default?

**Comment by DurankGts** [comment]
setting this Display.getInstance().setProperty("android.NotificationChannel.importance", "4"); ?
