### ISSUE TITLE
Server Sockets in simulator

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2584]
ServerSocket gets this error immediately after the first client connects successfully.
This trace is from the simulator, but I presume something similar is happening in
the actual android device.   The effect is that the intended loop providing an series
of connections to callers of "accept" that only one is delivered.   It looks like the
second call to "listen" doesn't take into account that the socket is already bound.

Secondary note, these headless "run"  invocations are impossible to catch, so even
if the "bind" problem was fixed, when in the ordinary course of events the socket
gets interrupted, the behavior will be that the server socket just mysteriously 
goes silent.

Third note; the null pointer exceptions aren't good either.  The actual code in question
is in socket.java, which you'll see near the bottom of the traces.

java.net.BindException: Address already in use: NET_Bind
[Listening on 50001] 0:6:21,392 - Exception: java.lang.NullPointerException - null
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.codename1.impl.javase.JavaSEPort$SocketImpl.listen(JavaSEPort.java:10576)
	at com.codename1.impl.javase.JavaSEPort.listenSocket(JavaSEPort.java:10606)
	at com.codename1.io.Socket$1Listener.run(Socket.java:99)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.NullPointerException
	at com.codename1.impl.javase.JavaSEPort.getSocketErrorCode(JavaSEPort.java:10662)
	at com.codename1.io.Socket$1Listener.run(Socket.java:110)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by ddyer0** [comment]
not relevant,  the server binds it and the client uses it.  You're allowed to make
connections to your own host.  and anyway, it works in standard java, and codenameone
behaves the same when the server and client are on different hosts.

**Comment by ddyer0** [comment]
''''java
 package dtest.boardspace;
/**
 * 
 * issue  #2584
 * 
 * Run this in the simulator, and note that although it runs, you get a
 * an bindexception in an unconnected run thread.
 * 
 */
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

import com.codename1.io.Socket;
import com.codename1.io.Socket.StopListening;
import com.codename1.io.SocketConnection;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;


class ClientConnection extends SocketConnection
{
	public void connectionEstablished(InputStream is, OutputStream os) 
	{	String msg = "client established "+is+" "+os;
		Dtest.addMessage(msg);
	}
	public void connectionError(int errorCode, String message) { 
		String msg = "client Failed "+errorCode+" "+message;
		Dtest.addMessage(msg);
	}
}
public class Dtest extends SocketConnection{
	
	public Dtest() {}
	public void connectionEstablished(InputStream is, OutputStream os) 
		{	String msg = "server established "+is+" "+os;
			Dtest.addMessage(msg);
		}
	public void connectionError(int errorCode, String message) { 
			String msg = "server Failed "+errorCode+" "+message;
			Dtest.addMessage(msg);		
		}

	private static Form current;

	public static Vector<String>messages = new Vector<String>();
	public static void addMessage(String m)
	{
		messages.addElement(m);
		current.repaint(); 
		System.out.println(m);
	}
	
	@SuppressWarnings("unused")
	private Resources theme;

	public void init(Object context) {
    theme = UIManager.initFirstTheme("/theme");
	}
	public void delay(int n)
	{
		synchronized(this) { try {
			wait(n);
		} catch (InterruptedException e) {
		} }
	}
    public void start() {
    	if(current != null){
    		current.show();
        return;
    }
    Form hi = new Form("Hi >>0 World");
    current = hi;
    hi.setLayout(new BorderLayout());
    hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {

        @Override
        public void paint(Graphics g) {
        	//g.resetAffine();
         	int w = getWidth();
        	int h = getHeight();
        	float ang = (float)(Math.PI);
        	
         	g.setColor(0x8f8f9f7f);
        	g.fillRect(0,0,w,h);

        	g.setColor(0xffffff);

        	for(int i=0;i<messages.size();i++)
        	{
        		g.drawString(messages.elementAt(i),10,i*30);
        	}
        
        }
        
    });
    hi.show();
	Runnable rr = new Runnable (){ 
		public void run() {
			System.out.println("running");
		{ StopListening stop = null;
		  hi.repaint();
		  try {
			  stop = com.codename1.io.Socket.listen(5001,Dtest.class); 
			  Dtest.addMessage("server listening");
			  delay(2000);
			  for(int i=0;i<5;i++)
			  {
			  Dtest.addMessage("client listening");
			  Socket.connect("localhost",5001,new ClientConnection());
			  delay(1000);
			  }
			  }	
		  catch (Throwable e) { Dtest.addMessage("Error: "+e); delay(100000); }
		  if(stop!=null) { stop.stop(); }
		  Dtest.addMessage("Exiting");
		  delay(5000);
		}}};
	new Thread(rr).start();
}
public void stop() {
    current = Display.getInstance().getCurrent();
}

public void destroy() {}

	}
''''

**Comment by ddyer0** [comment]
also, note on real android devices, requesting connections at human
speeds on multiple other devices, you only get 1 connection, not a sequence 
of connections.  It looks like the listening socket is closing.

**Comment by ddyer0** [comment]
Are there any thoughts on this?  This issue is the last obstacle in my current project.

**Comment by codenameone** [comment]
As I mentioned in the other issue, server sockets aren't a priority at this time

**Comment by ddyer0** [comment]
I looked at the Android `code,` and I think the issue is here.  This is the android implementation, but I suppose the simulator has the same structure.

`
        public Object listen(int param) {
            try {
                ServerSocket serverSocketInstance = new ServerSocket(param);
                socketInstance = serverSocketInstance.accept();
                SocketImpl si = new SocketImpl();
                si.socketInstance = socketInstance;
                return si;
            } catch(Exception err) {
                errorMessage = err.toString();
                err.printStackTrace();
                return null;
            }
        }
`
new ServerSocket creates a socket bound to the port. accept listens and gets the first connection on the port.  listen then exits leaving the serversocket orphaned, still bound to the port.  To fix this the api should be split into a "getSocket(port)" and a listen(socket); and the caller in non-implementation code adjusted accordingly.   Since this involves changing the implementation specific api for all the implementations, it's really something I can't do as a push.

**Comment by amiga** [comment]
Can't you use websockets? I wrote something similar and converted to websockets lib.

**Comment by ddyer0** [comment]
I suppose it's possible, but I already have all the other networking infrastructure
I need using the sockets api as a basis.    Seems like if .listen is part of the API 
it ought to work, and this isn't far removed from working correctly.

**Comment by ddyer0** [comment]
I've got a working implementation for the simulator, which adds new bindSocket and listen
methods to CodenameOneImpl.  The existing listenSocket ought to be removed, as it is
now unused and (as noted) doesn't work correctly.

In the interest of getting this into shape to be pushed: 

1) is there some reason why the old listenSocket version swallowed errors rather than 
throwing IOException ?    throwing an error seems like an cleaner choice.

2) the android version ought to be basically identical to the javase version.  I can supply
the code, but I don't see how I can test it.  Is there some way I can submit builds with
my own copy of the support code?

3) IOS is already unsupported, is there a problem with any of the other platforms?

**Comment by codenameone** [comment]
1. I think there's a callback API that should get the error

2.  Use include source and run the result. Make your changes there and test them: https://www.codenameone.com/how-do-i---use-the-include-sources-feature-to-debug-the-native-code-on-iosandroid-etc.html

3. No other platform is supported with this feature. Only Android and JavaSE

**Comment by ddyer0** [comment]
>>I think there's a callback API that should get the error
No, the existing code catches errors and does a printstacktrace, nothing is ever seen

>>Use include source and run the result. Make your changes there and test them: >>https://www.codenameone.com/how-do-i---use-the-include-sources-feature-to-debug-the-native-code-on-iosandroid-etc.html

In principle I could do that, but I would need to somehow substitute
my modified impl files and codename1 sources in place of the standard
ones embodied in javase.jar  The "build it from sources" approach only
works for ordinary native code.

**Comment by ddyer0** [comment]
I have an alternative proposal for you.  Completely remove the serversocket feature from the VM,
and replace it with a standard native extension.  This would un-encumber the vm with a feature 
that's clearly not complete, and allow it to be developed separatly.    While we've been dithering about this, I've implemented and tested exactly that.  So the proposed push would be a small modification to Socket.java, a new native entension, and leave to you to do the chopping out of the obsolete implementation from codenameoneimpl and it's subclasses.
