### ISSUE TITLE
Storage.getInstance().readObject(); blocking on UWP

### ISSUE THREAD

**Issue by vinsch** [codenameone/CodenameOne#2587]
I try to load a object with Storage.getInstance().readObject(); from storage. Every thing works fine on simulator. If I run the app on UWP (PC or ARM) the method call is just blocking. 
No Object type not supported Exception. 
No null pointer. 
Even the internalize method of the Object is not called. 

Storage.getInstance().exists() is true
Storage.getInstance().entrySize() is plausible 

Is there an Issue with UWP?
What could cause such a behavior?

**Comment by codenameone** [comment]
We'll need a test case, did you test this on Android or only UWP?

**Comment by vinsch** [comment]
I tested it also on android and it works there. 
The Issue is UWP (PC and ARM) only.
A "normal" object is loaded before the blocking happened.
The object which causes the blocking contains some synchronized methods.
The methodes of the Externalizable interface are not synchronized.

**Comment by codenameone** [comment]
Without a test case we can only guess @shannah do you have an idea?

**Comment by shannah** [comment]
I'd need a test case.  I created this simple test case as a start.  It runs fine for me in UWP.

~~~~
private void testSerialization(Container cnt) {
        Util.register("TestSerializableClass", TestSerializableClass.class);
        TestSerializableClass c1 = new TestSerializableClass();
        c1.strVal = "String 1";
        c1.intVal = 10;
        Storage s = Storage.getInstance();
        s.writeObject("object1", c1);
        
        TestSerializableClass c2 = (TestSerializableClass)s.readObject("object1");
        
        if (!c1.strVal.equals(c2.strVal)) {
            cnt.add(new Label("strVal doesn't match"));
        } else {
            cnt.add(new Label("strVal matches"));
        }
        if (c1.intVal != c2.intVal) {
            cnt.add(new Label("intVal doesn't match"));
        } else {
            cnt.add(new Label("intVal matches"));
        }
        cnt.revalidate();
        
    }
    
    private void testSerializationStart() {
        Form hi = new Form("Test Serialization", new BorderLayout());
        Container result = new Container(BoxLayout.y());
        Button b = new Button("Run Test");
        b.addActionListener(e->testSerialization(result));
        hi.add(BorderLayout.NORTH, b);
        hi.add(BorderLayout.CENTER, result);
        hi.show();
        
    }
~~~~

Please modify this test case so that it reproduces the issue that you describe, or provide your own small, self-contained test case.

**Comment by vinsch** [comment]
The problem was indeed caused by the synchronized feature. 
I fixed my bug by removing it.
Please see the  change of you’re example which should Show the same behavior. 

`private void testSerialization(Container cnt) {
        Util.register("TestSerializableClass", TestSerializableClass.class);
        TestSerializableClass c1 = new TestSerializableClass();
        c1.strVal = "String 1";
        c1.intVal = 10;
        c1.write();
        
        TestSerializableClass c2 = c1.read();
        
        if (!c1.strVal.equals(c2.strVal)) {
            cnt.add(new Label("strVal doesn't match"));
        } else {
            cnt.add(new Label("strVal matches"));
        }
        if (c1.intVal != c2.intVal) {
            cnt.add(new Label("intVal doesn't match"));
        } else {
            cnt.add(new Label("intVal matches"));
        }
        cnt.revalidate();
        
    }
    
    private void testSerializationStart() {
        Form hi = new Form("Test Serialization", new BorderLayout());
        Container result = new Container(BoxLayout.y());
        Button b = new Button("Run Test");
        b.addActionListener(e->testSerialization(result));
        hi.add(BorderLayout.NORTH, b);
        hi.add(BorderLayout.CENTER, result);
        hi.show();
        
    }

    public static class TestSerializableClass implements Externalizable {
        String strVal;
        int intVal;

		public synchronized TestSerializableClass read(){
			return (TestSerializableClass)Storage.getInstance().readObject("object1");
		}		
		
		public synchronized void write(){
			Storage.getInstance().writeObject("object1", this);
		}		
		
        @Override
        public int getVersion() {
            return 1;
        }

        @Override
        public void externalize(DataOutputStream out) throws IOException {
            Util.writeUTF(strVal, out);
            out.writeInt(intVal);
        }

        @Override
        public void internalize(int version, DataInputStream in) throws IOException {
            strVal = Util.readUTF(in);
            intVal = in.readInt();
        }

        @Override
        public String getObjectId() {
            return "TestSerializableClass";
        }
        
    }`

**Comment by shannah** [comment]
The test still works fine for me with your version (with the synchronized methods).    Closing.  Will reopen if provided with a test case that reproduces the issue.
