### ISSUE TITLE
Not able to swipe tabs when sidemenu is added

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#2590]
As described in the title, when a sidemenu is present it's no longer possible to swipe tabs, at least not gently.
If you show and hide the side menu, then the tabs start working as they should.

The issue is very easy to reproduce, both in simulator and devices. Here is a test case:

`public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form f = new Form(new BorderLayout());
        Tabs tab = new Tabs();
        Container cont1 = new Container(new BorderLayout());
        Label lbl1 = new Label("Hello 1");
        cont1.add(BorderLayout.CENTER, lbl1);
        Container cont2 = new Container(new BorderLayout());
        Label lbl2 = new Label("Hello 2");
        cont2.add(BorderLayout.CENTER, lbl2);
        tab.addTab("Tab 1", cont1);
        tab.addTab("Tab 2", cont2);
        f.add(BorderLayout.CENTER, tab);
        f.getToolbar().addComponentToSideMenu(new Label("Side Panel"));
        f.show();        
    }`

**Comment by codenameone** [comment]
I think this was resolved by the changes in today's update as the test case works for me now.

**Comment by carlosverdier** [comment]
Yes, it's working fine now, thanks.
