### ISSUE TITLE
Geting current location from method getCurrentLocationSync apparently doesn´t return a real time GPS mesure

### ISSUE THREAD

**Issue by JTBrandao** [codenameone/CodenameOne#2595]
We are using the method     public Location getCurrentLocationSync(long timeout)  in order to get the exact real time location, but the measure apparently has a 5 minutes delay.

Has anyone faced somthing like this ?

**Comment by codenameone** [comment]
I suggest asking this in the forum/discussion group. This relates to the timeout argument and has a lot of nuance.
