### ISSUE TITLE
RFE + BUG report: I need a full working low level camera API

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2596]
**RFE (I understand that requires a big effort)**
On the blog post "[Camera Kit - Low Level Camera API][1]" you wrote: _«As a sidenote the reason we picked up this task is because an enterprise customer asked for this [...] I would love to see ports of this to other Codename One platforms and the simulator. We’ll take a look at these as we move forward based on user demand»_. In the [Github page][2], you wrote: _«Important: not all API's are implemented in a cross platform way at this time as this cn1lib is highly experimental. Basic things might not work...»_

I, too, am an enterprise user: because my employers asked me to develop an app in which an advanced use of the camera is a crucial request, I need that this cn1lib will be developed from an alpha stage to a stable full working stage, at least in Android and iOS, better if also in the Simulator and in the Javascript port. Is this possible? It's very important for me... and it could be also a benefit for all the other Codename One developers.

**BUG REPORT**
Said that, the demo code in the Github page doesn't work for me. I wrote a simpler code, which purpose is to show the camera background in the center of a BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW (my idea is to place components over it).

I tried the code at the bottom of this post, but there are these issues:

**ANDROID 7**

After tapping on "Show Camera" on Android 7, the permissions are asked, after that it shows back to the first form; after tapping on "Show Camera" again, a blank black screen is shown (except for a small white square on the top, in place of the close button); if you tap that small white square and then tap "Show Camera" again, you will get the working background of the camera, but also this crash report:

> [EDT] 0:0:1,924 - Codename One revisions:
> 22614d770059e418030e79ac49b17911d43bfc26
> 
> [EDT] 0:0:1,925 - The device has one or more cameras
> [EDT] 0:0:1,995 - We use the native access to the camera
> [EDT] 0:0:17,294 - The device has one or more cameras
> [EDT] 0:0:17,296 - We use the native access to the camera
> [EDT] 0:1:19,519 - The device has one or more cameras
> [EDT] 0:1:19,557 - We use the native access to the camera
> [main] 0:1:19,713 - Exception: java.lang.RuntimeException - setParameters failed java.lang.RuntimeException: setParameters failed 	at
> android.hardware.Camera.native_setParameters(Native Method) 	at
> android.hardware.Camera.setParameters(Camera.java:2586) 	at
> com.wonderkiln.camerakit.a.h(Camera1.java:804) 	at
> com.wonderkiln.camerakit.a.o(Camera1.java:779) 	at
> com.wonderkiln.camerakit.a.i(Camera1.java:671) 	at
> com.wonderkiln.camerakit.a.a(Camera1.java:124) 	at
> com.wonderkiln.camerakit.CameraView$2.run(CameraView.java:266) 	at
> android.os.Handler.handleCallback(Handler.java:761) 	at
> android.os.Handler.dispatchMessage(Handler.java:98) 	at
> android.os.Looper.loop(Looper.java:156) 	at
> android.os.HandlerThread.run(HandlerThread.java:61)

**IPHONE X**

On iPhone X, tapping on "Show Camera" produces a blank white screen... that's all. There is no permissions request.

My build hints are the following. They are slightly different from the ones added by the cn1lib, because I removed the androidSdkTool version 27 (because it's the current default), I updated the camerakit version from 0.13.1 to 0.13.2 (I also tried the current beta of the 1.0.0 version, but it doesn't compile), I removed the 32bit compiling for iOS and I added a keepclasseswithmembers to proguard (as suggested in the web site of camera kit):

```
    build.incSources = 1
    android.gradleDep = compile 'com.wonderkiln:camerakit:0.13.2';
    ios.includePush = true
    android.proguardKeep = -dontwarn com.google.android.gms.** -keepclasseswithmembers class com.camerakit.preview.CameraSurfaceView {native <methods>;}
    java.version = 8
    ios.NSCameraUsageDescription = We need camera access to grab pictures and videos
    ios.newStorageLocation = true
```

My code:
```
    public class CameraApp {
    
        private Form current;
        private Resources theme;
        private CameraKit ck;
    
        public void init(Object context) {
            if (Display.getInstance().isSimulator()) {
                Log.p("-----------------------");
                Log.p("----- BUILD HINTS -----");
                Map<String, String> hints = Display.getInstance().getProjectBuildHints();
                StringBuilder hintsString = new StringBuilder();
                for (String key : hints.keySet()) {
                    hintsString.append(key + " = " + hints.get(key) + "\n");
                }
                Log.p(hintsString.toString());
            }
    
            ck = CameraKit.create();
    
            // use two network threads instead of one
            updateNetworkThreadCount(2);
    
            theme = UIManager.initFirstTheme("/theme");
    
            // Enable Toolbar on all Forms by default
            Toolbar.setGlobalToolbar(true);
    
            // Pro only feature
            Log.bindCrashProtection(true);
    
        }
    
        public void start() {
            if (current != null) {
                current.show();
                return;
            }
            Form hi = new Form("Native Camera", BoxLayout.y());
            Button showCamera = new Button("Show camera");
            showCamera.addActionListener(l -> {
                showCameraForm();
            });
            hi.add(showCamera);
            hi.show();
        }
    
        public void stop() {
            current = getCurrentForm();
            if (current instanceof Dialog) {
                ((Dialog) current).dispose();
                current = getCurrentForm();
            }
        }
    
        public void destroy() {
        }
    
        private void showCameraForm() {
            if (Capture.hasCamera()) {
                Log.p("The device has one or more cameras");
                if (ck != null) {
                    if (!ck.isStarted()) {
                        ck.start();
                    }
                    Log.p("We use the native access to the camera");
                    Style colorWhite = new Style();
                    colorWhite.setFgColor(0xFFFFFF);
                    colorWhite.setOpacity(0);
                    Form currentForm = Display.getInstance().getCurrent();
                    Form cameraForm = new Form(null, new BorderLayout(BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW));
                    cameraForm.getToolbar().setBackCommand(Command.create(null, FontImage.createMaterial(FontImage.MATERIAL_CLOSE, colorWhite), ev -> {
                        if (ck.isStarted()) {
                            ck.stop();
                        }
                        currentForm.showBack();
                    }), Toolbar.BackCommandPolicy.ALWAYS, 5);
                    cameraForm.getToolbar().hideToolbar();
                    PeerComponent cameraPeerComponent = ck.getView();
                    cameraForm.add(BorderLayout.CENTER, cameraPeerComponent);
                    Button close = new Button(FontImage.createMaterial(FontImage.MATERIAL_CLOSE, colorWhite, 5));
                    close.addActionListener(l -> {
                        if (ck.isStarted()) {
                            ck.stop();
                        }
                        currentForm.showBack();
                    });
                    cameraForm.add(BorderLayout.NORTH, FlowLayout.encloseIn(close));
                    cameraForm.show();
                } else {
                    Log.p("We use the standard Codename One API to access the camera");
                    showInteractionDialog("To be implemented", "We cannot access natively to the camera");
                }
            } else {
                // no camera
                Log.p("The device hasn't camera");
                showInteractionDialog("No Camera", "You haven't a camera");
            }
        }
    
        public void showInteractionDialog(String title, String body) {
            InteractionDialog dlg = new InteractionDialog(title);
            dlg.setLayout(new BorderLayout());
            dlg.add(BorderLayout.CENTER, new SpanLabel(body));
            Button close = new Button("Close");
            close.addActionListener((ee) -> dlg.dispose());
            dlg.addComponent(BorderLayout.SOUTH, close);
            int distance = Display.getInstance().convertToPixels(5);
            dlg.show(distance, distance, distance, distance);
        }
    
    }
```

  [1]: https://www.codenameone.com/blog/camerakit-low-level-camera-api.html
  [2]: https://github.com/codenameone/CameraKitCodenameOne/tree/master

**Comment by codenameone** [comment]
We've taken a bit of time with this since camera kit which was pending 1.0 back when we built the cn1lib is still... pending 1.0. They are working on it but it's taking forever as camera on Android is just horrible. We'll try to align the library to the latest 1.0 branch.

We have a test iPhone X device so I'll check on that as well.

**Comment by codenameone** [comment]
Having spent a lot of time trying to fix this I've come to the conclusion that camerakit is just unworkable. They dropped support for video which was one of the main reasons I picked them up in the first place. 
They adopted androidx which is **way** too early to do so. Despite multiple promises they can't commit to a 1.0 version. They broke API's which meant I had to break a lot and still couldn't get it working because of the androidx nonsense. 

I can see two options moving forward:

- **Use our own code** - possibly directly on the Camera2 API. This is a notoriously bad API and it requires Android 5.0 or newer. I'm not too concerned about the latter as Android 5.0 is already 90% of the market as of now. The former might be a pain but having used these libraries I'm not sure how much worse it can get

- **Find another library** - I looked at https://github.com/infinum/Android-GoldenEye One of the problems with CameraKit is that it's written in native code. That makes it hard to use and flaky. GoldenEye is in Kotlin which makes it harder to deal with from the Java side. So it's an improvement but not by much

I'll give this some thought but it won't make it to 6.0
-

**Comment by jsfan3** [comment]
Thank you Shai for the time that you already spent for this BIG issue.
Of course, this RFE plus https://github.com/codenameone/CodenameOne/issues/2702 and https://github.com/codenameone/CodenameOne/issues/2696 are like only one RFE.

I hope in you and in Steve. As I told, an advanced use of the camera is a crucial request for my social app, but I'm not able to write a so complex cn1lib for Android, iOS and Javascript by myself. If it's difficult for you, it's quite impossible for me: I learnt Java to use Codename One, but writing native interfaces like this require a lot bigger know-how than mine.

Thank you for your help. I'll wait for some good news from you.

**Comment by codenameone** [comment]
We'll place it as a priority task early in the 7.0 cycle

**Comment by shannah** [comment]
I have updated CameraKit to use GoldenEye and it appears to be working.  It needs to use SDK 28, which is not on the build server yet.  Hopefully this will be working for the update on Friday.

**Comment by jsfan3** [comment]
Do you mean that now CameraKit works correctly on Android, iPhone and Javascript? Have you tested all the platforms with all the APIs of CameraKit?

I hope so, that sounds very great and a very important news.

What is the minimum supported Android version?

For GoldenEye, are you referring to https://github.com/infinum/Android-GoldenEye/blob/master/README.md ?

**Comment by shannah** [comment]
Yes.  Now CameraKit works on Android native.  It already works on Javascript.  I haven't tested on iOS yet.

There may be some APIs that don't work.  I need to do additional testing.  I'm using the [CameraKitSample](https://github.com/codenameone/CodenameOne/tree/master/Samples/samples/CameraKitSample) as my test bed.  And so far I've only been testing the ability to record video, take photos, and change between front and back cameras.  It needs to be fleshed out further to test the rest of the APIs.

> What is the minimum supported Android version?

I'm not entirely sure.  I'm testing right now with a Nexus 5 on Android 6.  It is building with minSDK=15 and targetSDK=28.

> For GoldenEye, are you referring to https://github.com/infinum/Android-GoldenEye/blob/master/README.md ?

Yes.  That is the one

**Comment by codenameone** [comment]
Servers should have the latest SDK's now and the cn1lib change should be up in the extension manager.

**Comment by shannah** [comment]
I'm working on the iOS version now.  It has a few issues that need to be sorted out.  I should have this fixed up for the next release (next Friday).

**Comment by shannah** [comment]
I have just committed the latest changes to the camera kit.  The [sample app](https://github.com/codenameone/CodenameOne/tree/master/Samples/samples/CameraKitSample) is now working in iOS, Android, Simulator (still photos only), and Javascript.  On ios is requires the ios.NSCameraUsageDescription, and ios.NSMicrophoneUsageDescription build hints to be present.  If you run it in the simulator, it will add these hints automatically.

The latest cn1lib will be in CodenameOne settings soon.

**Comment by jsfan3** [comment]
Thank you! I understand that you done an hard work. So is it now fully working and ready for a stable app?

**Comment by shannah** [comment]
>  ready for a stable app?

Hopefully.  I've only been working with sample apps so far. If you run into problems, please post them in the issue tracker.
