### ISSUE TITLE
Add connect timeout to WebSocket

### ISSUE THREAD

**Issue by kroepr** [codenameone/CodenameOne#2600]
Currently you are unable to specify a connect timeout on a WebSocket. Therefore even connecting to a unreachable IP will take a long time before the call to connect fails.

Like Steve Hannah mentioned in the Google Groups this could be implemented by using a timer to check the status of the connection. However I feel that this should be part of the standard functionality and should not have to be custom written by everyone that needs this exact same functionality.

**Comment by shannah** [comment]
I have added support for a connection timeout.  You can now call

~~~~
websock.connect(5000);
~~~~

for example to give a 5 second connection timeout.  If it times out, then the onError() method will be called with a WebSocketConnection, with code WebSocket.ERR_TIMEOUT.

This will be available in the next libs update (soon).  Or you can download install the latest cn1lib from https://github.com/shannah/cn1-websockets/releases/tag/1.3.3

**Comment by kroepr** [comment]
@shannah. I noticed the fix was not done in the native code and because of it the native code is still holding system resources beyond the connect timeout.

Additionally, the auto-reconnect is not using the original connect timeout that was passed in during the connect. This causes issues using up system resources during auto-reconnect.

**Comment by shannah** [comment]
> I noticed the fix was not done in the native code and because of it the native code is still holding system resources beyond the connect timeout.

Do you have evidence that native resources are being held after the timeout expires?  On which platform?

**Comment by shannah** [comment]
> auto-reconnect is not using the original connect timeout that was passed in during the connect. This causes issues using up system resources during auto-reconnect.

This is now [fixed](https://github.com/shannah/cn1-websockets/commit/2c6b0cd001ef96432641bc9c7655234417f02809).

**Comment by kroepr** [comment]
`package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.websocket.WebSocket;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.util.Date;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private BrowserForm browserForm;
    private EventSocket client;
    
    public void init(Object context)
    {
        // use two network threads instead of one
        updateNetworkThreadCount(10);
        requestFullScreen();

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start()
    {
        if (current != null)
        {
            current.show();
        }
        else
        {
            browserForm = new BrowserForm();

            current = browserForm;
            browserForm.show();

            browserForm.setPage("<html><body>HELLO WORLD</body><html>");
            test();
        }
    }

    public void stop()
    {
        current = getCurrentForm();
        if (current instanceof Dialog)
        {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy()
    {
    }

    public void test()
    {
        client = new EventSocket("ws://192.168.10.182:4442");
        client.autoReconnect(5000);
        java.lang.System.out.println("Connect: " + new Date());
        client.connect(1000);
        java.lang.System.out.println("Connect done: " + new Date());
    }

    public static class EventSocket extends WebSocket
    {
        protected String  url;

        public EventSocket(String url)
        {
            super(url);
            this.url      = url;
        }

        @Override
        public void onOpen()
        {
            Log.p("onOpenClient: " + url);
        }

        @Override
        public void onClose(int statusCode, String reason)
        {
            Log.p("onCloseClient: " + url);
        }

        @Override
        public void onError(Exception throwable)
        {
            Log.p("onErrorClient: " + new Date() + " - " + throwable.getMessage());
        }

        @Override
        public void onMessage(final String message)
        {
            Log.p("onMessage: " + url + " - " + message);
        }
        
        @Override
        public void onMessage(byte[] message)
        {
            Log.p("onMessage: " + url + " - " + new String(message));
        }
    }
}
`

**Comment by kroepr** [comment]
```
package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.websocket.WebSocket;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.util.Date;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private BrowserForm browserForm;
    private EventSocket client;
    
    public void init(Object context)
    {
        // use two network threads instead of one
        updateNetworkThreadCount(10);
        requestFullScreen();

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start()
    {
        if (current != null)
        {
            current.show();
        }
        else
        {
            browserForm = new BrowserForm();

            current = browserForm;
            browserForm.show();

            browserForm.setPage("<html><body>HELLO WORLD</body><html>");
            test();
        }
    }

    public void stop()
    {
        current = getCurrentForm();
        if (current instanceof Dialog)
        {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy()
    {
    }

    public void test()
    {
        client = new EventSocket("ws://192.168.10.182:4442");
        client.autoReconnect(5000);
        java.lang.System.out.println("Connect: " + new Date());
        client.connect(1000);
        java.lang.System.out.println("Connect done: " + new Date());
    }

    public static class EventSocket extends WebSocket
    {
        protected String  url;

        public EventSocket(String url)
        {
            super(url);
            this.url      = url;
        }

        @Override
        public void onOpen()
        {
            Log.p("onOpenClient: " + url);
        }

        @Override
        public void onClose(int statusCode, String reason)
        {
            Log.p("onCloseClient: " + url);
        }

        @Override
        public void onError(Exception throwable)
        {
            Log.p("onErrorClient: " + new Date() + " - " + throwable.getMessage());
        }

        @Override
        public void onMessage(final String message)
        {
            Log.p("onMessage: " + url + " - " + message);
        }
        
        @Override
        public void onMessage(byte[] message)
        {
            Log.p("onMessage: " + url + " - " + new String(message));
        }
    }
}

```

**Comment by kroepr** [comment]
@shannah 

Code above produced following output:

Connect: Thu Apr 04 19:30:28 EDT 2019
Connect done: Thu Apr 04 19:30:28 EDT 2019
[Timer-0] 0:0:1,965 - Codename One revisions: da47a49b3da818c5b34f77040ed08228711d0194

[Timer-0] 0:0:2,8 - onErrorClient: Thu Apr 04 19:30:29 EDT 2019 - WebSocket connect timeout
[WebSocket] 0:0:22,329 - onErrorClient: Thu Apr 04 19:30:50 EDT 2019 - Exception occurred while trying to connect.

As you can see the WebSocket onErrorClient is 22 seconds after the connect. This is probably the native timeout. 

Additionally, since the output does not continue with "Attempting to reconnect...", the auto reconnect which was set to 5 seconds does not work.

**Comment by kroepr** [comment]
@shannah, were you able to reproduce the issue?

**Comment by shannah** [comment]
This is fixed now.  Should be available soon.  I have also added a [WebSocketSample](https://github.com/codenameone/CodenameOne/tree/master/Samples/samples/WebSocketsSample) to the [SamplesRunner](https://github.com/codenameone/CodenameOne/tree/master/Samples) to make it easier to test out websockets.

**Comment by kroepr** [comment]
@shannah the connect timeout issue is fixed. Thank you.

However the autoReconnect is still not working. When running the example I sent on 4/4/2019 you can see that "Attempting to reconnect..." never shows in the logs.

**Comment by kroepr** [comment]
@shannah. Any ideas why autoReconnect is not working?

**Comment by shannah** [comment]
Just committed a fix for this.

**Comment by kroepr** [comment]
@shannah, I tested the update and the auto reconnect is still not working.

**Comment by kroepr** [comment]
@shannah. Any update?

**Comment by shannah** [comment]
Latest changes should fix the issue

**Comment by kroepr** [comment]
@shannah. Latest fix did not resolve the issue. It still does not try to reconnect when using autoReconnect.

**Comment by shannah** [comment]
When did you try?  
https://github.com/shannah/cn1-websockets/blob/master/dist/cn1-websockets.cn1lib

**Comment by kroepr** [comment]
@shannah. It's working now. I tested it just before you put out the latest it seems.

Thank you for the quick response.
