### ISSUE TITLE
new Date() reporting incorrect time windows phone

### ISSUE THREAD

**Issue by pollaris** [codenameone/CodenameOne#2601]
I have:

        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("h:mm");      
        String s$ = ft.format(dNow);      
        button1.setText(s$);

The time is correct on Windows desktop, version 1803 (the simulator), 
and on Android.  
On Windows Phone version 1607 and Windows Phone version 1703
the time is an hour early when DST is in effect.  Phones are set to
automatically adjust time.  Time is correct on the Phone display, but
codename one is not adjusting for DST.

**Comment by codenameone** [comment]
`new Date()` will produce a different result depending on the date in which we add it. I suggest including a test case that's deterministic and always fails. E.g. with a hardcoded timestamp for the date.
