### ISSUE TITLE
Please add Double.compare

### ISSUE THREAD

**Issue by Maaartinus** [codenameone/CodenameOne#2604]
IMHO it should be present as it's `@since 1.4`. My problem is that it gets used in the code Lombok generates, so something as trivial as
```
@Value
public class Broken {
    private double price;
}
```
fails to compile with "The method compare(double, double) is undefined for the type Double", which I can't fix. Similarly, `Float.Compare` is missing.

The good news is that these are so far the only obstacles in using Lombok.

**Comment by codenameone** [comment]
@shannah I'm leaving milestone assignment to you as VM work is always a pain.

**Comment by shannah** [comment]
Added methods to CLDC11 and ensured that they are implemented in iOS VM.  Other VMs should already support these.
