### ISSUE TITLE
Could you add SafeVarargs?

### ISSUE THREAD

**Issue by Maaartinus** [codenameone/CodenameOne#2610]
Adding `@SafeVarargs` would get rid of a few warnings (warning suppressions) in my code. No big deal, but the effort should be minimal, too (and there's already [this](https://github.com/shannah/codenameone-avian/blob/master/jdk7u-dev/jdk/src/share/classes/java/lang/SafeVarargs.java).

**Comment by codenameone** [comment]
That's a part of Avian which is completely different and we can't use that. But I agree it should be harmless/easy to add
