### ISSUE TITLE
location updates continuously received in simulator although unwanted

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2611]
Disabling the location simulation (setting to `Not-Available`) seems not to have any effect in the simulator. I would like to simulate cases when there is no active gps connection.

        LocationManager.getLocationManager().setLocationListener(new LocationListener() {
            
            @Override
            public void locationUpdated(Location location) {
                log.p("update: " + location); // continuously called
            }

            @Override
            public void providerStateChanged(int newState) {
                log.p("state changed: " + newState);
            }
        });

**Comment by codenameone** [comment]
When the GPS can't connect you should still get location updates from wifi, towers & other sensors.
