### ISSUE TITLE
Missing content after using menu

### ISSUE THREAD

**Issue by Maaartinus** [codenameone/CodenameOne#2612]
In my app, I create a component according to this [SO answer](https://stackoverflow.com/a/53076201/581205) and it works well, until I use the menu. I've reduced it to a small demo showing the bug. Clicking on a row normally changes its look. After using the menu, the row disappears instead (painted all white).

I could have removed more stuff, the only relevant component seems to be the label used as the lead component. I may be doing it all wrong....

It happens in the simulator and also on Android.

[demo1.zip](https://github.com/codenameone/CodenameOne/files/2596965/demo1.zip)

**Comment by codenameone** [comment]
The link to the SO question seems to be broken

**Comment by Maaartinus** [comment]
@codenameone Fixed (but it's hardly relevant).

**Comment by codenameone** [comment]
I thought it would clarify the bug description. Can you please add screenshots and ideally embed some source code for easier evaluation?
Unzipping and running a test project takes time and makes the evaluation process slower. With screenshots and source we can sometimes spot things we ran into instantly.

**Comment by codenameone** [comment]
So this entire thread could have been summed up by: "focusLost() is invoked but focusGained() is never invoked after I open and close the side menu"?
Is that the issue?

**Comment by Maaartinus** [comment]
I don't think so. The items must be visible with or without focus, they just change their text ("not selected" vs. "selected"), but they must never be invisible.

**Comment by codenameone** [comment]
Looking at the code again it seems that you are missing a `revalidate()` call when you change the layout.

**Comment by Maaartinus** [comment]
Damn.... so no `invalidate` nor `repaint` (which I tried and then removed as not helpful), but `revalidate`. That you, that's it.
