### ISSUE TITLE
RFE: improve Javascript manual page

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2617]
I suggest to indicate in this page:
https://github.com/codenameone/CodenameOne/wiki/Working-With-Javascript

that by default the javascript port will not work on Apache2, because it's necessary to disable the "icons" directory alias on the server configuration:
https://support.plesk.com/hc/en-us/articles/360003364874-All-requests-containing-icons-are-redirected-to-the-usr-share-httpd-icons-or-to-usr-share-apache2-icons-folder

I also suggest to indicate that a very simple way on Apache2 to work around the CORS restrictions is to use directives like the following in the website conf file:
```
SSLProxyEngine on
ProxyPass /app https://www.myexternaldomain.com/
ProxyPassReverse /app https://www.myexternaldomain.com/
```

These two indications can be helpful to avoid wast of time with Apache2.

**Comment by shannah** [comment]
I have changed the name of the "icons" directory to "_icons" to avoid this conflict.

Thanks for the apache tip.  I think it might make more sense to create a separate "how-to" document for apache if we want to present tips like this, as this snippet requires a bit more context and might lead to confusing if just inserted on its own.

**Comment by shannah** [comment]
I added a small section in https://github.com/codenameone/CodenameOne/wiki/Working-With-Javascript on the Apache mod_proxy tip.

**Comment by jsfan3** [comment]
Thank you. I added documentation for more domains and I done few fixes.
