### ISSUE TITLE
RFE: lock screen orientation on Javascript port

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2618]
I didn't find any way to lock the screen orientation on the Javascript port.
I tried what discussed here, without success:
https://stackoverflow.com/questions/53462551/codename-one-lock-screen-orientation-in-the-javascript-port

I suppose that the right way is the build hint that modify the web-app manifest:
`javascript.manifest.orientation=portrait`
but it doesn't work.

The use of a native javascript interface implementation, like the following, breaks the page loading on iPhone (Safari and Chrome, I suppose that they have the same rendering engine) and has no effect on Android Chrome (it logs "Orientation locked to portrait" but indeed its not locked).

```
(function (exports) {

    var o = {};

    o.lockPortraitOrientation_ = function (callback) {
        // Screen Orientation API, https://w3c.github.io/screen-orientation/#examples
        screen.lockOrientationUniversal = screen.orientation.lock || screen.lockOrientation || screen.mozLockOrientation || screen.msLockOrientation;
        if (screen.lockOrientationUniversal("portrait-primary")) {
            console.log("Orientation locked to portrait");
        } else {
            // orientation lock failed
            console.log("Failed to lock orientation");
        }
        callback.complete();
    };

    o.isSupported_ = function (callback) {
        callback.complete(true);
    };

    exports.cool_teammate_apps_frontend_NativeUtilities = o;

})(cn1_get_native_interfaces());

**Comment by shannah** [comment]
Try changing your native implementation to this:

~~~~
(function (exports) {

    var o = {};

    o.lockPortraitOrientation_ = function (callback) {
        screen.lockOrientationUniversal = screen.lockOrientation || screen.mozLockOrientation || screen.msLockOrientation;

        if (screen.lockOrientationUniversal("portrait-primary")) {
          // orientation was locked
        } else {
          // orientation lock failed
        }
        callback.complete(null);
    };
    
    o.isSupported_ = function (callback) {
        callback.complete(true);
    };

    exports.cool_teammate_apps_frontend_NativeUtilities = o;

})(cn1_get_native_interfaces());
~~~~

**Comment by jsfan3** [comment]
Is the only difference the removing of "screen.orientation.lock"? I've already tried that.

In the page: https://www.sitepoint.com/introducing-screen-orientation-api/
it's written: _«It’s also worth noting that to lock the screen, the web page must be in full-screen mode (you can achieve this using the Fullscreen API).»_

So... it seems that implementing this features requires the implementation of the fullscreen. In the linked webpage there is a demo: https://www.audero.it/demo/screen-orientation-api-demo.html

BUT that demo doesn't work in mobile Chrome (tested on Android and on iPhone), while it seems to work on a desktop computer (at least for the fullscreen).

Maybe this information is not updated. Moreover, why the orientation specified in the web-app manifest is ignored?

**Comment by shannah** [comment]
I also placed code that could possibly throw a JS exception inside a try/catch. And I passed a null parameter to .complete().

If it was blocking loading, it sounds like the callback was not completing -- which is effectively killing whatever else was going to happen on that thread.  And if you called it from the EDT - then that would be it for the app.

**Comment by jsfan3** [comment]
I tried your code on a new bare bones project.
Results:

- Chrome on Android: the web-app is loaded, but there isn't no lock.
- Chrome on iPhone: the web-app is loaded, but there isn't no lock.

More precisely, I used:
```
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // Lock portrait orientation
        LockPortraitNative lockPortraitNative = NativeLookup.create(LockPortraitNative.class);
        lockPortraitNative.lockPortraitOrientation();
```

```
public interface LockPortraitNative extends NativeInterface {
    public void lockPortraitOrientation();
}
```

```
(function(exports){

var o = {};

    o.lockPortraitOrientation_ = function (callback) {
        screen.lockOrientationUniversal = screen.lockOrientation || screen.mozLockOrientation || screen.msLockOrientation;

        try {
            if (screen.lockOrientationUniversal("portrait-primary")) {
              // orientation was locked
            } else {
              // orientation lock failed
            }
        } catch (e) {
            console.log(e);
        }
        callback.complete(null);
    };
    
    o.isSupported_ = function (callback) {
        callback.complete(true);
    };

exports.cool_teammate_apps_frontend_LockPortraitNative= o;

})(cn1_get_native_interfaces());
```

**Comment by shannah** [comment]
@jsfan3 Is this issue still important for your project, or have you found alternative ways to deal with this (e.g. #2636)?

**Comment by jsfan3** [comment]
Yes, it's still important (assuming that it's possible, as I hope, but I'm not sure).

https://github.com/codenameone/CodenameOne/issues/2636 is only a partial workaround (I noted that on rotation Safari puts its address bar on the Toolbar of my app, it's better to avoid rotation at all, moreover I have an algorithm in the `init()` that adjust the font sizes according to the screen width - _I developed it this morning and it makes the web-app fonts sizes better close (quite identical) to the native app font sizes_ -, but my algorithm assumes that the screen width remains the same during the app execution).

Moreover, a Form inside a Form (https://github.com/codenameone/CodenameOne/issues/2636) is mainly to manage the app on big screen, than to workaround the app rotation locking.

**Comment by shannah** [comment]
`javascript.manifest.orientation=portrait` works on Android Chrome.  I just tested.

There doesn't appear to be any way to lock orientation on Safari.  https://stackoverflow.com/a/5298578/2935174

Note that the [lockOrientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation) only works when an app is in full-screen mode.

From the docs:

> Note: This method only works for installed Web apps or for Web pages in full-screen mode.

And iOS safari doesn't support the Javascript full-screen APIs.  And I tested using the "Add to Homescreen" version on iOS (which *is* full-screen, and the APIs still don't work - and neither does the manifest entry).

Marking this "wont-fix" and closing.  If things change later, I may reopen it.

**Comment by jsfan3** [comment]
Is it possible to automatically add `javascript.manifest.orientation=portrait` when ` Display.getInstance().lockOrientation(true);` is used? This is better than nothing.

**Comment by shannah** [comment]
The manifest is static, and a call to Display.lockOrientation(true) is dynamic (runtime), so this isn't really possible.  

However, it is probably possible to us the [Javascript Full-screen APIs](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) and [lockOrientation APIs](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock) to lock the orientation on supported browsers.

There are two possible ways this could be implemented:

1. `Display.lockOrientation(true)` will put the app in full-screen mode, and lock the orientation automatically.
or
2. `Display.lockOrientation(true)` will only lock the orientation if the app is already in full-screen mode, and fail/do nothing otherwise.

I think the first behaviour is probably better, but forcing the app into full-screen may be somewhat disorienting to the user.

**Comment by shannah** [comment]
Actually, in thinking further, I think it would be better to add fullscreen functionality to our API so that you can enter/exit full-screen mode.  And then use method 2 for lockOrientation (only lock if in fullscreen mode).

**Comment by jsfan3** [comment]
I was writing exactly what you have just wrote in your last comment... I think so, it is also important to document all. Thank you

**Comment by shannah** [comment]
I have added a Full-screen API that is supported in the desktop and javascript ports.  I've also implemented orientation lock in the javascript port.   These APIs are only supported in browsers that support the javascript FullScreen and Screen Orientation Lock APIs. 

* https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation
* https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

Here is the sample App I used for testing this functionality. 

~~~~
private void testFullScreen() {
        Form f = new Form("Full Screen Test", new BorderLayout());
        Button enterFullScreen = new Button("Enter FullScreen");
        enterFullScreen.addActionListener(e->{
            Display.getInstance().requestFullScreen();
        });
        
        Button exitFullScreen = new Button("Exit FullScreen");
        exitFullScreen.addActionListener(e->{
            Display.getInstance().exitFullScreen();
        });
        f.add(BorderLayout.NORTH, enterFullScreen);
        f.add(BorderLayout.SOUTH, exitFullScreen);
        
        Button lockPortrait = new Button("Lock Portrait");
        lockPortrait.addActionListener(e->{
            Display.getInstance().lockOrientation(true);
        });
        
        Button lockLandscape = new Button("Lock Landscape");
        lockLandscape.addActionListener(e->{
            Display.getInstance().lockOrientation(false);
        });
        
        Button unlockOrientation = new Button("Unlock Orientation");
        unlockOrientation.addActionListener(e->{
            Display.getInstance().unlockOrientation();
        });
        f.add(BorderLayout.CENTER, BoxLayout.encloseY(lockPortrait, lockLandscape, unlockOrientation));
        f.show();
    }
~~~~

This will be included in the next update next Friday.

**Comment by jsfan3** [comment]
Thank you!
