### ISSUE TITLE
inconsistent behavior in Dialog.show methods

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2621]
When we have
```
            Dialog.show("title", "l10nKey", "okText", "cancelText"); //A
            Dialog.show("title", "l10nKey", commands); //B
```
the displayed dialog of A contains a localized text (mapped by "l10nKey" if the mapping exists of course) whereas the displayed dialog of B just contains the text "l10nKey" even when there exists a localization mapping. Thus in B auto-localization doesn't happen

**Comment by codenameone** [comment]
Yes, it's a problem that we can't really fix as it will break compatibility to everyone who used the old API's. 
There is actually more history behind this as the OK/Cancel are flipped depending on platform preferences. Some OS's place OK on the left while some place it on the right. With multiple command objects we can't really know which is OK and which might be something else so the direction doesn't really matter. So I don't think it's something we can realistically address.
