### ISSUE TITLE
Generated new iOS Push certificates, but I didn't receive any email

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2623]
About one hour ago (I dont't remember exactly the time, if half hour or more than our hour), I generated new iOS Push certificates, but I didn't received any email.

**Comment by codenameone** [comment]
Is this to the protonmail address or a different address? 
Note that the data should also be saved to disk as well.

**Comment by jsfan3** [comment]
Protonmail address.

Yes, on the disk there is a folder "iosCerts" inside the Netbeans projects, with these files:
development_provisioning_profile.mobileprovision
development_push_certificate.p12
production_provisioning_profile.mobileprovision
production_push_certificate.p12

However I remember that you send an e-mail with instructions (that I would like to read again). I remember that the push certificates are saved in your cloud to use CN1 as intermediate for the push service... maybe I'm wrong. It's a little time that I don't use push and I don't remember the instructions. I also remember that recently you have introduced a lot of new feature about push.

**Comment by codenameone** [comment]
Odd, I don't see anything in the sendgrid logs. @shannah do you see something in the server logs?

**Comment by shannah** [comment]
I can see that the push certificates were generated but I don't see any errors surrounding this.

**Comment by codenameone** [comment]
Is the email code still executing? Does it still use the sendgrid API?
It's possible that some of that code has gone stale.

**Comment by shannah** [comment]
I just tried to generate push certs and also did not receive an email.  No errors.  Looking into it

**Comment by shannah** [comment]
It was because I wasn't logged in in Codename One Settings.   @jsfan3 Can you check to make sure you are logged into Codename One settings.  One of the options in the main menu will say "Login (null)" if you are not.

**Comment by jsfan3** [comment]
I see "Login (Ent: null)" even if I log in (tried several times).

You could see in your logs that I created again the push certificates two times (overwriting the existing ones)... I received e-mails by Apple about the revoke of the certificates, but no e-mail was sent to me by Codename One.

**Comment by shannah** [comment]
"Login (Ent: null)" means you're not logged in.  Something is wrong there.  I'll be making a change that prevents you from accessing the certificate wizard when you're not logged in.  But that won't solve the problem is you can't login to begin with.

So, to clarify.  You clicked on the "Login (Ent: null)" button, and successfully logged in?  And it still says "Login (Ent:null)"?

**Comment by jsfan3** [comment]
Yes, you understood correctly, the login doesn't work. Please watch this video, so you can see what I see:
https://www.informatica-libera.net/videoLavoro/login.mp4

**Comment by jsfan3** [comment]
I tried a lot of times...
To be sure that e-mail / password are correct, I wrote them in a text editor and I copied and pasted them to log in in the Codename One web-site: on the web, my login works. I copied and pasted them in the Codename One Preference, but I always get as in video. If I enter a wrong or right password, there is no difference.

Moreover, there is a non-sense: how can the Codename One Plugin know my rank if I enter a invalid login?

**Comment by shannah** [comment]
Not currently.  I have just pushed an update that will handle the login correctly - and should give you an error message on failure.  It will be part of the friday update.

**Comment by jsfan3** [comment]
Ok. I done a new test in the following way:

I closed Netbeans ().

I executed from Linux terminal:
`rm -fR .cn1Settings .codenameone .com.codename1.designer.css.CN1CSSCLI .java`

I reopened Netbeans.

I opened the Codename One Preferences of the project, in which there was written: "Login (Free: null)".

I executed the login.

After the login it's written: "(Free: null)"

I saved and closed the Codename One Preferences.

I compiled the project.

I sent a javascript build.

It asked me the login, after that the build was sent successfully.

I opened the Codename One Preferences of the project, in which there was writte: "Login (Free: null)".

I executed the login.

After the login it's written: "(Free: null)"

So, at the moment, the login is broken. I'll try on Friday.

Netbeans infos:
Product Version: Apache NetBeans IDE 9.0 (Build incubator-netbeans-release-334-on-20180708)
Java: 1.8.0_181; Java HotSpot(TM) 64-Bit Server VM 25.181-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_181-b13
System: Linux version 4.15.0-38-generic running on amd64; UTF-8; it_IT (nb)
User directory: /home/francesco/.netbeans/9.0
Cache directory: /home/francesco/.cache/netbeans/9.0

(Note that I downgraded from Java 10 to Java 8, because Java 10 gave me too much problems and an incompatibility with Jeddict plugin, that is an important tool for me)

**Comment by jsfan3** [comment]
I didn't noted any difference in the login: do I have to do something to update?

**Comment by shannah** [comment]
That change is part of the CodenameOne settings app.  I'm not sure if that update went out yet.

**Comment by codenameone** [comment]
I didn't push this out because I want to fit in a few other fixes. Is this an important fix for this week?

**Comment by jsfan3** [comment]
Don’t worry, I’ll wait.

**Comment by jsfan3** [comment]
I confirm that this issue is solved.
