### ISSUE TITLE
RFE: significantly speed up the web-app loading on mobile devices

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2625]
I've read this response of Shai about speeding app the loading of a Codename One app ported to Javascript:
https://stackoverflow.com/questions/53462678/codename-one-reduce-the-loading-time-of-a-web-app

However it's not enough, at least on mobile devices. The loading time on desktop browsers is fine (Firefox on Linux, with cookies and cache cleaned, takes three seconds to open an "Hello Word Bare Bones" ported to Javascript), but on mobile devices the situation is very different.

I would ask you to repeat the following test.

Please take an empty CN1 "Hello Word (Bare Bones)" Netbeans project and build it as Javascript: the build size is 2kb and it produces a web site of 5.6MB (decompressed). I uploaded that web-app to an host with gzip and SSL enabled. To simulate the first opening of that website, I cleared cookies and cache of Chrome browser on Android. I have a broad band connection.

Result: it's very very slow... it takes about 20 seconds to open (?!) and for the most of wait seconds the screen is blank and white (??!). Why? It's impossible to propose my users (and my employers) to use a so slow web-app, they can think that it's broken or that there are problems of connection. I know that the second loading is faster, but the first impression is important.

The technical details of my phone are here: https://www.gsmarena.com/huawei_honor_6x-8388.php

The exactly same test, in the same conditions (cookies and cache cleaned), repeated on my iPhone X (with Google Chrome) takes 8 seconds to open... it's better, but it's not good... and the most of people has a medium level Android rather than the latest iPhone.

Please, can you try to significantly speed up the web-app loading on mobile devices? I suppose that for a "bare bones hello world" the time of loading should be one or two seconds... moreover, in my opinion, the blank and white screen, after the logo, should be avoided at all.

Thank you for your support.

**Comment by jsfan3** [comment]
Thank you very much, I’ll wait for the Friday update.
Onestly I don’t know why there is so much difference in the load time... I’ll write you again in this discussion after Friday.

**Comment by shannah** [comment]
I made a few other changes aimed at reducing perceived loading time, including the addition of a progress bar.  That will be part of the release on friday.

**Comment by jsfan3** [comment]
Thank you!

**Comment by jsfan3** [comment]
After this discussion, I learned to inspect my Android device from Google Chrome running in the desktop. I also learned to disable cache in the DevTools.

I saw the new progress bar. I also saw that the white screen disappeared.

The loading time with cache disabled, with the **same device** that took about 20 seconds (with **the same remote VPS**), fell to 6 seconds. With the cache enabled this time drops to 3. It's a marked improvement, thanks. With Google Chrome desktop, the loading time (with cache disabled) of the same project from the same server is about 4 seconds, with cache enabled it is about 2 seconds. Probably my VPS has a poor connectivity compared to Amazon (that you used to performe the tests), but overall the improvement is noticeable.

**Comment by jsfan3** [comment]
I didn't see the use of the Android native theme opening the web-app with Android. It looks so (installing the web-app to the home):
![screenshot_20181130-154133](https://user-images.githubusercontent.com/1997316/49295688-a7b9d880-f4b6-11e8-9598-9dcced14f0ff.png)

**Comment by shannah** [comment]
Looks like I forgot to push the last change (the Android theme support) to git so it didn't make it into the update. I've pushed it now so it will be in the next update.
