### ISSUE TITLE
RFE: loading bar in the Javascript start screen

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2627]
In the Javascript start screen there is an icon, some gray circles and a "loading..." text. That's fine, however let's suppose that an user has a slow connection or that the opening of the web-app is slow for unpredictable and unknown reasons (it could be a temporary issue).

Yesterday you implemented an enhancement of the loading time: https://github.com/codenameone/CodenameOne/issues/2625

Today I have another suggestion: can you insert a progress loading bar (instead of the gray circles)? If there is a slowing down of the loading, with a progress loading bar (like in Gmail start screen) the users will have psychological perception that the app is really loading (and how much it is loaded), instead with only the gray circles they can think that it's not loading (if there is a connection slowing down).

I don't know if it's possible. It's only a suggestion and, in my opinion, it can make sense only if the reported progress in the progress bar is enough accurate.

**Comment by shannah** [comment]
I have been doing some further testing with a simulated slow 3G connection.  I have tried a number of techniques for changing loading order and preloading some things, but nothing that makes a substantial difference in load time.    We could probably improve things slightly by using a tool like webpack to pack everything into a single file. 

The heavy hitters are the classes.js file and the theme files, so it is possible for us to display update messages on the loading screen like:

Loading Application...
Loading Resources...
Loading Theme iPhone7.res...
Loading Theme theme.res...
etc...

That might give enough reassurance that something is still happening and that it isn't just locked.

**Comment by codenameone** [comment]
If you have a file count and pieces then a progress indicator would be possible and probably better than messages like that.

**Comment by shannah** [comment]
I can probably rig up some approximation of a loading bar.

**Comment by shannah** [comment]
Added progress bar.  https://github.com/shannah/cn1-teavm-port/commit/fc3e106fb523b31669cf3a54ee4bd9bedfb4faea

Will be part of Friday release.
