### ISSUE TITLE
RFE: ShareButton for videos and map points

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2630]
Reference: https://stackoverflow.com/questions/50249148/codename-one-addconstraint-to-pickercomponent-date

My RFE is to add ShareButton API to share videos and map points.

**Comment by shannah** [comment]
I think you may have pasted a different reference link than you intended.  That doesn't appear to be related to sharing or maps.

**Comment by jsfan3** [comment]
You're right, I'm sorry: https://stackoverflow.com/questions/53539778/codename-one-sharebutton-for-videos-and-map-points

**Comment by shannah** [comment]
I think in both of these cases you'll just want to share a URL.  You can share the URL as text and it should work.  All of the examples I found for android and iOS native sharing just used the same mechanism to share urls as they use for plain text so it should just work to use the share(text) API.

For videos, you would need to first upload the video somewhere, then share its URL.
For map coordinates you would also need to share the URL.  The URL you use would depend on which app you wanted the recipient to open the link in.  E.g. Google maps has fairly simple syntax for URLs with coordinates and routes.

**Comment by jsfan3** [comment]
Ok, thank you for the hint.

When we share a video from the default iOS Photos app to a messaging app like Signal, is it different? I'm only trying to understand... in that case there isn't any url because the video is not published anywhere in the web, right? However, I think that sharing an url is a lot more portable and lightweight that sharing hundreds of megabytes or even gigabytes...

**Comment by shannah** [comment]
>  in that case there isn't any url because the video is not published anywhere in the web, right? 

Generally this type of sharing would involve uploading the resource/image/video to cloud storage (or some server) in the background, and then sharing the URL to that location.

**Comment by shannah** [comment]
I don't think there is anything to do on this one.  Closing.  Correct me if I'm wrong.
