### ISSUE TITLE
Javascript preview

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2635]
Did the Javascript preview stop to work? I see an infinite loading...

**Comment by codenameone** [comment]
It's failing for me too. Not sure why. This is what I see this in the JS console:
<img width="1269" alt="screen shot 2018-12-07 at 7 48 21" src="https://user-images.githubusercontent.com/2353641/49629941-b2172d80-f9f4-11e8-89a7-a5b95ce7ba15.png">

**Comment by shannah** [comment]
Working on a fix now.
In the mean time, you may notice that project build.xml files now contain "war" and "run-war" targets.  If you run the "run-war" target it will build the .war version and run it directly in an embedded local version of Tomcat.  This is what I usually do.

**Comment by shannah** [comment]
Fix is in git now.  Just the BuildDaemon project - doesn't require changes to the port itself.

**Comment by codenameone** [comment]
This is deployed now
