### ISSUE TITLE
[BUG] orientation listener on javascript

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2636]
This bug is strictly related to https://github.com/codenameone/CodenameOne/issues/2628 (I think that it's the same), but it's a much simpler to investigate, because the following test case is composed by few lines of code.

In short: the following code works on the native apps and on the Javascript port when run on Android, but it produces weird effects when it's run on iPhone. So, to reproduce the bug, simply build to Javascript the following code and test it on Chrome on iPhone, while trying to rotate the device.

```
Form outer = new Form("OuterForm", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
        Label innertext = new Label("Screen size: " + Display.getInstance().getDisplayWidth() + " * " + Display.getInstance().getDisplayHeight());
        Form inner = new Form("InnerForm", BoxLayout.y()) {
            @Override
            protected Dimension calcPreferredSize() {
                return new Dimension(Display.getInstance().convertToPixels(90), Display.getInstance().getDisplayHeight());
            }
        };
        inner.add(innertext);
        outer.add(BorderLayout.CENTER, inner);
        outer.show();

        outer.addOrientationListener(l -> {
            innertext.setText("Screen size: " + Display.getInstance().getDisplayWidth() + " * " + Display.getInstance().getDisplayHeight());
            innertext.repaint();
        });
```

**Comment by shannah** [comment]
Can you provide more information about the problem.  I built this app and ran it in iOS safari and chrome, and it seems to work fine.
![img_4525](https://user-images.githubusercontent.com/2677562/49736521-470d6700-fc3f-11e8-9a7c-af1bc825f672.jpg)
![img_4526](https://user-images.githubusercontent.com/2677562/49736525-4aa0ee00-fc3f-11e8-97b0-b9cfa93bad32.jpg)

**Comment by jsfan3** [comment]
Have you tried to rotate the device multiple times?

**Comment by shannah** [comment]
4 or 5 times.  How many does it take to make it fail?

**Comment by jsfan3** [comment]
Few times... I'm going to record a video.

**Comment by jsfan3** [comment]
This is the video: https://www.informatica-libera.net/videoLavoro/testJavascriptRotationOnIphoneX.mp4

Tested the above code, built as Javascript, on Chrome on iPhoneX.

**Comment by shannah** [comment]
I've managed to reproduce it.  So far only occurring in Chrome.  Not in Safari.  Looking into it further

**Comment by shannah** [comment]
For some reason, Chrome on iOS doesn't yet have the updated window/document size inside the window "resize" event, which we use to trigger the canvas resize.  I have resolved this issue in my tests by adding a 1ms delay between the "resize" event and when we update the canvas size. 

This will be part of the next server update (next Friday).

**Comment by jsfan3** [comment]
Thank you!
