### ISSUE TITLE
getting EXC_BAD_ACCESS error on iOS

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2638]
My iOS build crashes when the app gets started. There is no issue in CN1 simulation. I feel like it's linked to the last CN1 update.

The error is caused at the following line:
<img width="1119" alt="bildschirmfoto 2018-12-09 um 09 54 44" src="https://user-images.githubusercontent.com/5825645/49695301-4a4e1780-fb99-11e8-82c2-b6b29cbf21a0.png">

**Comment by codenameone** [comment]
This is a bit too late to determine the cause. It means there was a memory corruption at some point in the past and the GC is running into it. The question is what happened beforehand?
Can you narrow this down to a specific API whose usage will trigger this?
Do you have native calls or cn1libs that might use native code?

**Comment by kutoman** [comment]
I'm having a tough time in narrowing it down to the specific API since I'm tackling generated code.

While I'm debugging. This here got highlighted. Is this something relevant?
Note it says:

`objc[18317]: Hash table corrupted. This is probably a memory error somewhere. (table at 0x11025ae48, buckets at 0x7fcaab84fe00 (2048 bytes), 128 buckets, 66 entries, 43 tombstones, data 0x12faf63e0 0x12faf63c0 0x70000d03f8a8 0x38303080f00)`

![bildschirmfoto 2018-12-10 um 14 56 48](https://user-images.githubusercontent.com/5825645/49737139-59fa5880-fc8c-11e8-993f-244cf4b6ba9a.png)

**Comment by codenameone** [comment]
I don't have any ideas @shannah can you think of something?

**Comment by shannah** [comment]
Can you post the native interface implementations that you are using?   E.g. I see from your log that you have some NativePlatformCallback class.
![image](https://user-images.githubusercontent.com/2677562/49873889-d480c080-fdd1-11e8-85bd-7ba2f2c3bc05.png)

**Comment by kutoman** [comment]
here you are:
[all relevant files for iOS of our app](https://gist.github.com/kutoman/6e90a02fb54367f2932a23948e3d82a3)

**Comment by kutoman** [comment]
I'm still narrowing it down, I'm going to provide more explicit information next week hopefully.

This is the trace of the error with respect to the CN1 api (beginning with `loadJSON()` from `PropertyIndex`):

```
#12	0x000000010a1159f8 in com_codename1_impl_ios_IOSNative_createNSFileHandle___java_lang_String_R_long at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/IOSNative.m:7798
#13	0x000000010a24babc in com_codename1_impl_ios_NSFileInputStream___INIT_____java_lang_String at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/com_codename1_impl_ios_NSFileInputStream.m:83
#14	0x0000000109e0f557 in com_codename1_impl_ios_IOSImplementation_createStorageInputStream___java_lang_String_R_java_io_InputStream at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/com_codename1_impl_ios_IOSImplementation.m:10561
#15	0x0000000109c93582 in virtual_com_codename1_impl_CodenameOneImplementation_createStorageInputStream___java_lang_String_R_java_io_InputStream at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/com_codename1_impl_CodenameOneImplementation.m:14422
#16	0x0000000109a80f78 in com_codename1_io_Storage_createInputStream___java_lang_String_R_java_io_InputStream at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/com_codename1_io_Storage.m:246
#17	0x0000000109ff2cbe in com_codename1_properties_PropertyIndex_loadJSON___java_lang_String at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/com_codename1_properties_PropertyIndex.m:1216
#18	0x0000000109ff4d22 in virtual_com_codename1_properties_PropertyIndex_loadJSON___java_lang_String at /Users/SoftwareDev/Downloads/sources 8/dist/MainApp-src/com_codename1_properties_PropertyIndex.m:1683
```
