### ISSUE TITLE
Facebook SDK outdated

### ISSUE THREAD

**Issue by jmoranrod** [codenameone/CodenameOne#2641]
We have received an email from Facebook indicating that the application uses the following SDKs:

- Facebook SDK for Android v4.7.0
- Facebook SDK for iOS v4.12.0

That versions refer to the Graph API version of Facebook v2.7 that has become obsolete recently. Facebook suggest updating to the following versions:

- Facebook SDK for Android v4.39.0
- Facebook SDK for iOS v4.39.0

If the SDKs are not updated, there is a risk that the application will not work anymore

**Comment by codenameone** [comment]
We'll push out a build hints in the coming update: android.facebookSdkVersion which you can use as:

`android.facebookSdkVersion=4.39.0`

I haven't tested it so it might fail on newer versions as Facebook is notorious about breaking compatibility. For iOS we already have a similar build hint `ios.facebook.version` which is used a bit differently:

`ios.facebook.version=~>4.39.0`

Again the same caveat applies. If there are errors with setting to a specific newer version we'll deal with those specific errors.

**Comment by jmoranrod** [comment]
When will the update be available to do the tests?

**Comment by codenameone** [comment]
@jmoranrod Is this working for you?
Can I flip this to be the default?

**Comment by jmoranrod** [comment]
Sorry for not having answered before, the SDK works for me correctly.

**Comment by codenameone** [comment]
This will be the default in the next update

**Comment by codenameone** [comment]
This seems to be broken on iOS possibly because the pod was migrated. I'll revert this back on iOS for the 6.0 release.

**Comment by jmoranrod** [comment]
Yesterday I tried to send an iOS compilation and I got this error:

```
Process return code is 0
Executing: / usr / local / bin / pod install Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
   In Podfile:
     FBSDKCoreKit (~> 4.39.0)

Specs satisfying the `FBSDKCoreKit (~> 4.39.0)` dependency were found, but they required a higher minimum deployment target.
Process return code is 1
Cocoapods failed even after updating master repo
```

Fixed by changing the build hint from **ios.pods.platform =, 7.0** to **ios.pods.platform =, 10.0**

**Comment by codenameone** [comment]
Thanks, this should be fixed for the code freeze
