### ISSUE TITLE
ios build sources project simulation sometimes not running instantly

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2642]
sometimes it happens that I cannot run the simulation of a newly built ios projects. And in some cases it  just runs fine. I get the following error:

![grafik](https://user-images.githubusercontent.com/5825645/49950636-78fd2280-fef8-11e8-9e82-4014e2b9ba70.png)

I noticed that the Podflie.lock file is missing in some downloaded ios sources archives. Why is that so?

**Comment by shannah** [comment]
If the resulting source tar.gz would end up being too big (cut off right now is 100mb), then it omits the pods from the archive.  As the error states, you'll need to install cocoapods and run "pod install" (in terminal in the same directory as the PodFile), to reinstall the pods.
