### ISSUE TITLE
make component attributes of generated gui class accessible for subclasses

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2643]
Since I would like to extend (generated) gui classes by kotlin code I want to create a kotlin subclass for each generated java gui classes where it's necessary (I know that just a part of the class is overwritten, but it's just java). By doing so I would like to use the component members which are generated. Unfotunately they are `private`. Isn't it reasonable to make them `protected` instead?

**Comment by kutoman** [comment]
@shannah 
just to be sure because I need to plan the archtiecture of my view classes:
this got rejected, right?

**Comment by codenameone** [comment]
No it was fixed. The comment is probably invisible to you because it refers to an internal commit but this was fixed. I'm not sure if it's already there but `gui_*` fields should now be protected.
This is the comment from @shannah without the commit link: "Changed GUI builder generated components to use protected access instead of private so that subclasses can access them."

**Comment by kutoman** [comment]
ok I see, it seems that it will be applied to the next update I guess as still 'private' modifiers are generated

**Comment by kutoman** [comment]
in which update will this be part of? Today's update seems not to have it either

**Comment by codenameone** [comment]
Both updates should have had it. @shannah can you confirm

**Comment by kutoman** [comment]
is it confirmed? I still have to replace each modifiers after every save actions in the gui builder. If I need to fix something on my side in order to get it working, any advice would be appreciated

**Comment by shannah** [comment]
My system is so "custom" that I can't confirm that the standard updates have the latest.  All I know, is that if I build the BuildClient project from source and then copy the CodeNameOneBuildClient.jar into a project, then all of the GUI builder variables are protected for that project.

**Comment by kutoman** [comment]
@shannah could you share your CodeNameOneBuildClient.jar please?

**Comment by shannah** [comment]
Here is a sample project with CodeNameOneBuildClient.jar that generates variables protected.

https://github.com/shannah/test-gui-builder

**Comment by kutoman** [comment]
thanks.. but that's weired. I opened the project in netbeans.. The gui builder can be run, but when saving only the respective gui file gets modified not the java class source code (`GuiForm.java`)

**Comment by shannah** [comment]
The java source file is updated when you build the project.

**Comment by kutoman** [comment]
ok I see. On Intellij the class is updated as soon as I tap the save button. I guess it's built instantly there? 
And yes the `protected` s are generated in your project. But shouldn't this be also the case when I copy/paste this `CodeNameOneBuildClient.jar` to my project?

**Comment by shannah** [comment]
Shoot!  It looks like the intelliJ plugin has its own copy of the class that generates the GUI sources.  I need to copy the change into the IntelliJ plugin project.  I think that's the only other copy that needs to be updated.  @codenameone Correct me if I'm wrong.

**Comment by codenameone** [comment]
Yes sorry. I forgot about that. It was essential because of the jaxb conflict nonsense.

**Comment by shannah** [comment]
I have made the change in the IntelliJ plugin now.  It will be available in the next update.

**Comment by kutoman** [comment]
both plugin and libraries are updated, but still it's not working :(

**Comment by codenameone** [comment]
We don't update plugins every Friday. We only do that when there are significant changes. When the plugin is newer than 6.0.1 the change will be there.

**Comment by kutoman** [comment]
so this means hat as long as there won't be any significant change, I won't ever have this change in action. I totally understand your point, but it's just unfortunate for me. From experience, how frequently are such significant changes made?
