### ISSUE TITLE
Form rotation wrong

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2646]
On the iPad Air 2 when rotating the device to landscape, then leaving the app, then using other apps, then rotating the device to portrait and finally showing the app again the form is truncated because obviously it is misinformed about the rotation.

![img_0186](https://user-images.githubusercontent.com/9945131/50155083-710ffa80-02cb-11e9-99af-45fd21c3f07d.jpg)

Here is the code:

        Form hi = new Form("Hi World", BoxLayout.y());
        for (int rowIndex = 0; rowIndex < 100; rowIndex++) {
            Container containerRow = new Container(new BorderLayout());
            {
                containerRow.add(BorderLayout.CENTER, new Label("This is row " + (rowIndex + 1)));
            }
            {
                containerRow.add(BorderLayout.EAST, new Switch());
            }
            hi.add(containerRow);
        }
        hi.show();

**Comment by saeder** [comment]
This is with freshly downloaded libraries and with a newly created (barebones) project with the code section above pasted into the main class.

**Comment by jsfan3** [comment]
This bug remember me https://github.com/codenameone/CodenameOne/issues/2636.

**Comment by shannah** [comment]
This would not be related to #2636 since that is javascript specific, and this issue is on iOS (non-javascript)
