### ISSUE TITLE
setShowMeridiem 12 AM and 12 PM issue

### ISSUE THREAD

**Issue by ChrisLace** [codenameone/CodenameOne#2651]
Form hi = new Form("Picker", BoxLayout.y());
Picker p = new Picker();
p.setType(PICKER_TYPE_TIME);
p.setShowMeridiem(true);
Label value = new Label("" + p.getTime());
hi.add(p).add(value);
p.addActionListener(e1 -> {value.setText("" + p.getTime()); } );
hi.show(); 

![2](https://user-images.githubusercontent.com/39275611/50474841-4c74ec00-0977-11e9-85b2-c65e6765a20f.png)
![1](https://user-images.githubusercontent.com/39275611/50474842-4c74ec00-0977-11e9-9a03-c00770dbdfaf.png)

**Comment by ChrisLace** [comment]
Please fix the issue and add this to near release.

**Comment by ChrisLace** [comment]
Please let me know ETA on this issue

**Comment by codenameone** [comment]
It's assigned to milestone 6

**Comment by codenameone** [comment]
Milestone 6 is the closest milestone there is. Our priorities are determined by enterprise subscribers and we have a backlog due to the holiday.

**Comment by ChrisLace** [comment]
Thank You for a quick fix Shannah.
