### ISSUE TITLE
Error in Eclipse Build - Project Losing Formatting and Style

### ISSUE THREAD

**Issue by rainer2208** [codenameone/CodenameOne#2653]
The issue causes the project to lose formatting and style when altering styles in theme editor, mainly when material icons are used and the CSS-support is activated. 

Like in the screenshot below, all is in black and white, but the text color should be red, the buttons should have styled foreground and background.

The issue seems to be limited to Eclipse, NetBeans is working fine. 

This issue seems to be due to the following bugs in the builld.xml file:

When first activating the CSS-Support, the target  :

       cn1-compile-css

seems to be missing. You have to deactivate and re-activate the CSS-support to have the the line in the build.xml file. 

The line: 

          <java jar="${user.home}/.codenameone/designer_1.jar" failonerror="true">

is also not complete. It should read: 

        <java jar="${user.home}/.codenameone/designer_1.jar" failonerror="true" fork="true">

Steps to reproduce:

1.    Create new project, Bare Bone;
2.    Add two buttons;
3.    Add UIID to buttonTwo;
4.    Style buttons One and Two in the theme editor;
5.   Add material icon to button;;
6.   Activate css support in CN1 - settings;
7.   Style buttonTwo in theme.css;

Code snippet:

    Form hi = new Form("Hi World", BoxLayout.y());
    FontImage image = FontImage.createMaterial(FontImage.MATERIAL_ADD_BOX, "", 5);

    Button buttonOne = new Button("Button One");
    Button buttonTwo = new Button("Button Two");

    buttonTwo.setUIID("ButtonTwo");
    buttonOne.setIcon(image);

    hi.add(buttonOne).add(buttonTwo);

    hi.show();

CSS Style:

    ButtonTwo {

        color: red; 

    }

![screenshot](https://user-images.githubusercontent.com/23400899/50482542-d77cd300-09c5-11e9-9422-1f9230497a7a.png)

**Comment by codenameone** [comment]
This is related to https://stackoverflow.com/questions/53887116/codename-one-components-losing-style-on-eclipse/53927413
The fork entry is missing in the generated CSS build.xml and it seems the update action overrides CSS settings on eclipse.
