### ISSUE TITLE
RFE to see Javascript preview in the "Codename One Build" app

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2656]
Can you please add to the "Codename One Build" app a way to open a Javascript build preview? At the moment, there is a Button "OTA - CLICK TO INSTALL", with the html file name, but tapping on it does nothing. Thank you.

(tested on iPhone)

**Comment by codenameone** [comment]
This is fixed now in the build cloud, you might need to kill and restart the app to see the impact. This requires no update to the app.

**Comment by jsfan3** [comment]
Excellent, I confirm that it works! Thank you
