### ISSUE TITLE
BUG: TextArea.isEditing always return false in Javascript port

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2657]
I need that `TextArea.isEditing` works consistently on the Simulator, on Android native, on iOS native and on Javascript port. 

The issue is that  `TextArea.isEditing` always return `false` in Javascript port (tested with Firefox on Linux, Chrome on Android, Safari on iOS, Chrome on iOS).

A simple test case:

```
Form hi = new Form("Hi World", BoxLayout.y());
        TextArea area = new TextArea();
        Label info = new Label("");
        hi.addAll(area, info);
        hi.show();
        
        UITimer.timer(500, true, () -> {
            if (area.isEditing())
                info.setText("is Editing...");
            else
                info.setText("is NOT editing");
            hi.revalidate();
        });
```

**Comment by shannah** [comment]
Fixed.  This will be included in next server update (on Friday I think)

**Comment by jsfan3** [comment]
Thank you very much!
