### ISSUE TITLE
BUG: Capture.photo() is not implemented correctly in Javascript port

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2658]
`Capture.photo()` is not implemented correctly in the Javascript port.

Simple test case:
```
Form hi = new Form("Hi World", BoxLayout.y());
        Label photo = new Label(FontImage.createMaterial(FontImage.MATERIAL_PERSON, "Label", 30));
        Button button = new Button("Take a photo");
        button.addActionListener(l -> {
            Capture.capturePhoto(evt -> {
                if (evt != null && evt.getSource() != null) {
                    String file = (String) evt.getSource();
                    try {
                        photo.setIcon(Image.createImage(file).scaledWidth(Display.getInstance().convertToPixels(30)));
                        hi.revalidate();
                    } catch (IOException ex) {
                        Log.e(ex);
                    }
                }
            });
        });
        hi.addAll(button, FlowLayout.encloseCenter(photo));
        hi.show();
```

**Safari (iPhone X, iOS 12):**
After tapping on "Take a photo", it asks for permissions to access the camera, it shows a red camera icon near the address bar, but no photo is taken. Tapping more times on "Take a photo" does nothing.
Screenshot:
https://www.informatica-libera.net/docLavoro/capture_iphone_safari.png

**Chrome (iPhone X, iOS 12):**
After tapping on "Take a photo", it shows "Click to access the camera". After tapping again, it allows to capture a photo... but the captured photo is not shown correctly (it's rotated of 90 degrees). Screenshot (note the bad orientation of the photo):
https://www.informatica-libera.net/docLavoro/capture_iphone_chrome.png

**Chrome (Android 7):**
It works partially, because it allows only to take a front photo, it doesn't allow to switch to the back camera. Note that in this case the captured image is oriented correctly. Screenshot (note that there isn't any icon to switch the camera):
https://www.informatica-libera.net/docLavoro/capture_android_chrome.png

But that's not all. The previous screenshots are taken using the test case I provided. On a **real world complex app** (in which I use CSS and a custom font), I have this screenshot on Chrome (Android 7), note that the icons are not displayed correctly:
https://www.informatica-libera.net/docLavoro/capture_android_chrome_noicons.png

I didn't test other browsers or other Capture API. I encourage you to test and fix all the Capture API in several browsers and devices. Thank you.

**Comment by shannah** [comment]
This is fixed now.  It will be included in the next server update (on Friday I think).

**Comment by jsfan3** [comment]
Thank you very much!

**Comment by jsfan3** [comment]
I've done some tests: I confirm that all the reported issues are solved :+1:
