### ISSUE TITLE
RFE: Android and iOS default certificates for all new project

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2662]
In the past, in Netbeans there was a Codename One menu to set the default Android and iOS release and debug certificates for any project. That was useful, it was in Tool, Options. So, for every new project, it was necessary only to generate the iOS provisioning certificates.

Now, for every new project, I have to set them manually all the certificates. Can you add a functionality like the one removed?

Thank you

**Comment by codenameone** [comment]
It wasn't removed. Under Codename One Settings there is a globe icon on the top left that switches to "Global Mode". It's something on my todo list to document that

**Comment by jsfan3** [comment]
I never noticed that icon, thank you for the tip!

Happy New Year
