### ISSUE TITLE
RFE about native web-app fonts

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2665]
I noted that the web-apps use native fonts (both on iPhone and Android) that are not the same of the native apps in the same platform. The native fonts of the web-apps occupies more space than the native fonts of the native apps (the difference seems bigger on Android, in my tests). In some cases, in the web-apps my `Labels` don't fit in the screen, while they are fine in the native apps.

My RFE is if it's possible to make the web-apps using the same native font of native apps, in the same platform, with the same DPI.

Thank you

**Comment by jsfan3** [comment]
Thank you for the clarification, however it's not only a problem of pixel density and default font size, it's only half of the problem. The other half of the problem is the font-family, that is even more important.

I haven't a single test-case, but I can show you the problem on a real-world complex app that I'm developing.

Please give a look to this comparison of three UI pieces of same app (on Chrome and as native) on the same device (https://www.gsmarena.com/huawei_honor_6x-8388.php). Note that all the styling is made by CSS (as reported below the image).

In the order (from top to bottom), this comparison contains: the same Toolbar, the same Label, the same piece of SideMenu. Of course the expected correct fonts are the ones used by the native app.

![comparision](https://user-images.githubusercontent.com/1997316/50629558-59787900-0f3d-11e9-840d-d8ccc434a629.png)

About the CSS used in this comparison:

The defaults:
```
/* Default text and color */
Default, Label, TextArea, TextField {
    font-family: "native:MainRegular";
    font-size: 3mm;
    color: black;
}
```

1) The Title of the Toolbar
```
Title {
    font-family: "native:MainBold";
    font-size: 3mm;
    color: black;
    text-align: center;
}
```

2) The Label with my full name:
```
BaseProfileForm-Fullname {
    cn1-derive: Label;
    font-family: "native:MainBold";
    font-size: 3mm;
    text-align: center;
    margin-bottom: 2mm;
    color: #660066;
}
```
3) The Labels shown in the SideMenu:
```
ProfileSideMenu-SidemenuTagline {
    padding: 0;
    margin: 0;
    padding-top: 1mm;
    margin-bottom: 0.5pt;
    font-family: "native:ItalicLight";
    font-size: 3mm;
    color: white;
}
```

**Comment by shannah** [comment]
I have made some changes that give better results in my test cases.  They will be part of the next server update.

**Comment by jsfan3** [comment]
Thank you, I confirm that it's better, the font-family is now correct.
