### ISSUE TITLE
BrowserComponent not loading content properly when added to Dialog on iOS

### ISSUE THREAD

**Issue by schreiby** [codenameone/CodenameOne#2666]
Hello.

I am trying to display dynamically retrieved content with a BrowserComponent inside a Dialog **while using an iPhone**. I have not tested this on Android.

I used `setURL(file.getPath())` to load a .html file. When the Dialog shows the BrowserComponent appears as a blank white space. When disposing the Dialog, the content of my file, or the String display but only for a moment and then disappears so I know that the html is formatted correctly but for some reason won't show immediately in the BrowserComponent. During testing, I found that after opening and closing the Dialog numerous times, the content would load immediately 1 time, but after closing the Dialog and reopening it, the BrowserComponent would display that blank white space again. I have tried to display the Dialog with `show()` and `showModeless()`. 

Previously I tried to `setPage(data, null)` with `data` being a String with proper html. In this  case, the content also appeared briefly when disposing the Dialog. I also tried to display a pdf in the BrowserComponent, which works when the BrowserComponent is in a Form, but this did not work in a Dialog. 

Here is my code:

`FileSystemStorage fss = FileSystemStorage.getInstance();`
`Dialog dialog = new Dialog(Preferences.get("header", ""), new BorderLayout());`
`BrowserComponent browserComponent = new BrowserComponent();`
`browserComponent.setScrollableY(true);`
`File file = new File(fss.getAppHomePath()+"g.html");`
`try {`
      `InputStream stream = Storage.getInstance().createInputStream("g.html");`
      `OutputStream out = fss.openOutputStream(file.getPath());`
      `Util.copy(stream, out);`
      `Util.cleanup(stream);`
      `Util.cleanup(out);`
`} catch (IOException e) {`
    `e.getMessage();`
`}`
`Log.p("file path is " + file.getPath() + " vs " + file.getAbsolutePath() + " " + file.length());`
`browserComponent.setURL(file.getPath());`
`Button btnOk = new Button(Constants.OK_CAPS);`
`btnOk.addActionListener(new ActionListener() {`
`@Override`
`public void actionPerformed(ActionEvent evt) {`
        dialog.dispose();`
`}`
});`
`dialog.setFocusable(false);`
`dialog.add(BorderLayout.CENTER, browserComponent);`
`dialog.add(BorderLayout.SOUTH, btnOk);`
`dialog.show(20,20,20,20);`

Thanks for looking into this. I am aware that this is simulator to Issue 2605, however this is an issue on a real iPhone.

**Comment by codenameone** [comment]
The test case should be:

````java
Form f = new Form("Browser Test", BoxLayout.y());

Button d = new Button("Show");
f.add(d);

d.addActionListener(e -> {
    Dialog dlg = new Dialog("Codename One", new BorderLayout());
    dlg.add(SOUTH, new Button(new Command("Done")));
    BrowserComponent bc = new BrowserComponent();
    bc.setURL("https://www.codenameone.com/");
    dlg.add(CENTER, bc);
    dlg.show(20, 20, 20, 20);
});

f.show();
````

This works in the simulator but fails on an iOS device. @shannah is this related to the EDT JS work you did?

**Comment by shannah** [comment]
> is this related to the EDT JS work you did?

Hard to say until I dig into the problem.  It's possible.

**Comment by shannah** [comment]
I've narrowed it down to the fact that when the dialog is shown, it has `setLightweightMode(true)` called on it for the transition, but `setLightweightMode(false)` is never subsequently called - so it appears that this dialog (maybe all dialogs?) are currently displayed in lightweight mode.

I'm reading the sources to try to figure out when/how setLightweightMode(false) *should* be called.
