### ISSUE TITLE
Picker() with PICKER_TYPE_CALENDAR, changing Month or Year closes selection dialog w/o updating

### ISSUE THREAD

**Issue by mab1423** [codenameone/CodenameOne#2673]
If you are experiencing an issue please mention the full platform your issue applies to:
IDE: NetBeans/Eclipse/IDEA NetBeans 8.2
Desktop OS Windows 10 Pro
Simulator Latest
Device PC, Android 7, IOS 12+

Run this, tap on Date Field, A proper calendar appears, try to change Month or Year and Calendar dialog closes VS changing the calendar view to the selected Month or Year.

            Form hi = new Form("", new BoxLayout(BoxLayout.Y_AXIS));
            Picker A3TimeSheetDate = new Picker();
            A3TimeSheetDate.setDate(new Date(System.currentTimeMillis()));
            A3TimeSheetDate.setType(Display.PICKER_TYPE_CALENDAR);
            SimpleDateFormat formatter = new SimpleDateFormat("E MM-dd-yyyy");
            A3TimeSheetDate.setFormatter(formatter);
            FontImage.setMaterialIcon(A3TimeSheetDate, FontImage.MATERIAL_DATE_RANGE, 4);
            A3TimeSheetDate.setUIID("TimeSheetDate");
            hi.add(A3TimeSheetDate);
            hi.show();

Thanks In Advance

**Comment by shannah** [comment]
Fixed in https://github.com/codenameone/CodenameOne/commit/37bfcc5ee64583809c60e0bb89243133d646903f
