### ISSUE TITLE
`navigator.share` Javascript API

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2674]
If I tested correctly, a code like the following does nothing on the Javascript port:
```
if (Display.getInstance().isNativeShareSupported()) {
            Display.getInstance().share(text, null, null);
}
```
Instead it could be working on Android Chrome: https://developers.google.com/web/updates/2016/09/navigator-share but only for sharing texts and urls.

Do you think that the `navigator.share` API can be integrated in `Display.getInstance().isNativeShareSupported()` and `Display.getInstance().share`?

I'm only asking, I'm not sure because your sharing API expects arguments different from the `navigator.share` API.

**Comment by shannah** [comment]
I have added support for this.  It will be available in the next update (next friday I think)

**Comment by jsfan3** [comment]
Thank you! Does it work like the current API, that means without the need of tapping a `Button`, for example using it in `showListener` of a Form? I'm asking because this morning I saw that this Javascript API works only if it's launched by user interaction. Moreover, how do you handle the case that an user tries to use the Codename One API to share an image?

**Comment by jsfan3** [comment]
Ah, ok, now I understand why there are these additional buttons in the javascript port.

**Comment by jsfan3** [comment]
And how to you handle the case that the user tries to share an Image? The Javascript API doesn't allow that, but the Codename One API allows that. I'm curious to know how you did, thank you.

**Comment by shannah** [comment]
The 2nd parameter (for an image) will send a link only if it starts with http:// or https://
So
~~~
share("Hello", null, null);  // Shares "Hello"
share("Hello", "/path/to/image", "image/jpeg"); // Shares "Hello".  Image ignored
share("Hello", "http://example.com/image.jpg", null);  // Shares "Hello" and provided link.
share(null, "http://example.com/image.jpg", null); // Shares provided link.
~~~~

**Comment by jsfan3** [comment]
Of course, if we want only to share only an url or a text that contains an url, is the first parameter enough?
I mean that:
`share(null, "http://example.com/image.jpg", null); // Shares provided link.`
or
`share("http://example.com/image.jpg", null, null); // Shares provided link`
do exactly the same thing, right?

I suggest to add more documentation in the Javadocs, thank you :)
