### ISSUE TITLE
RFE: make Display.getInstance().getProperty("AppArg", null) working also with universal links

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2677]
The iOS Universal Links are supported by Codename One thanks to a build hint like `ios.associatedDomains=applinks:subdomain.domain.com` discussed here: https://github.com/codenameone/CodenameOne/issues/2581

But... I've just discovered that I cannot get the url of the links with the following code, that works fine on Android and in the web-apps:
```
String arg = Display.getInstance().getProperty("AppArg", null); // iOS and Android
        if (arg == null) {
            // https://www.codenameone.com/manual/appendix-javascript.html
            arg = Display.getInstance().getProperty("browser.window.location.href", null); // Javascript port
        }
```

On iOS the `arg` value is `null`.

Here there is an example to get the url using Objective-C: https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/handling_universal_links

I find it difficult to write a native interface because Objective-C is not my language. Can you please make `Display.getInstance().getProperty("AppArg", null)` working also with universal links?

Thank you.

**Comment by shannah** [comment]
This will be available in the next server update on Friday.
Note that due to the order of when it receives events, this will cause the app to run it's start() method twice when receiving universal link launch.

E.g.
1. User opens link in Safari.
2. App opens. 
     -> App.start() is called  (AppArg == null)
3. iOS sends URL argument.
     -> App.stop() is called
      -> AppArg is set.
     ->  App.start() is called  (AppArg == The applink that was opened).

**Comment by jsfan3** [comment]
Thank you!
