### ISSUE TITLE
ImageViewer: vertical pan on image not working

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2679]
If an image does not fit vertically in an `ImageViewer` I would of course need to pan vertically but it's not possible here. Btw. how can I set the alignment of an image which has `ImageViewer.IMAGE_FILL` as initial position? The image seems to be centered by default.

sample code:

        Form f = new Form(new LayeredLayout());
        
        ImageViewer viewer = new ImageViewer();
        viewer.setImageInitialPosition(ImageViewer.IMAGE_FILL);
        
        ListModel<Image> images = SampleModel.load();
        
        f.addComponent(viewer);
        viewer.setImageList(images);

        f.show();

**Comment by kutoman** [comment]
any idea? I eagerly need to implement this

**Comment by codenameone** [comment]
Try `f.getContentPane().setScrollable(false);`

**Comment by kutoman** [comment]
the issue remains:

        Form f = new Form(new LayeredLayout());
        
        f.setScrollableY(false);
        f.getContentPane().setScrollableY(false);
        
        ImageViewer viewer = new ImageViewer();
        viewer.setImageInitialPosition(ImageViewer.IMAGE_FILL);
        
        ListModel<Image> images = SampleModel.load();
        
        f.addComponent(viewer);
        viewer.setImageList(images);

        f.show();

**Comment by kutoman** [comment]
first of all, thanks for having handled this issue. As I opened the issue it was eagerly needed but I had to put the corresponding feature aside as it couldn't be integrated in time on our side. 
Coming to your commit, it seems not to work for me (even though when I allow scale down). It's still the same issue when I run the given sample code.

**Comment by codenameone** [comment]
Notice you need to invoke `setAllowScaleDown(true)` to enable that behavior, otherwise it won't work as there's a conceptual conflict that can lead to sub par UX.

**Comment by kutoman** [comment]
yeah I mentioned it between the brackets :) 
it's still the same
This is the code I used to test:
```
        Form f = new Form(new LayeredLayout());
        
        f.setScrollableY(false);
        f.setScrollableX(false);
        f.getContentPane().setScrollableY(false);        
        f.getContentPane().setScrollableX(false);

        
        ImageViewer viewer = new ImageViewer();
        viewer.setAllowScaleDown(true);
        viewer.setImageInitialPosition(ImageViewer.IMAGE_FILL);
        
        ListModel<Image> images = SampleModel.load();
    
        f.addComponent(viewer);
        viewer.setImageList(images);

        f.show();
```

**Note:** maybe it's crucial to mention, that I'm testing the viewer in landscape mode as I need this configuration when turning the screen.

**Comment by kutoman** [comment]
for demonstration:
![ImageViewerIssue(2)](https://user-images.githubusercontent.com/5825645/63604172-6977c280-c5cb-11e9-8f97-3137ba8e1bc1.gif)

The interaction gets awkward after the rotation. As you can see, firstly, the sliding gets weird as the initial page (after the rotation) gets somehow aligned left even though the slide gesture is made for the opposite direction. After having slided to the next page vertical panning is not possible anymore. Moreover zooming doesn't happen smoothly and suddenly causes the page to get smaller than intended.

here is the sample code for also having the same ListModel:

```
        Form f = new Form(new LayeredLayout());
        
        f.setScrollableY(false);
        f.setScrollableX(false);
        f.getContentPane().setScrollableY(false);        
        f.getContentPane().setScrollableX(false);

        
        ImageViewer viewer = new ImageViewer();
        viewer.setAllowScaleDown(true);
        viewer.setImageInitialPosition(ImageViewer.IMAGE_FILL);

        ListModel images = new DefaultListModel();
        final int w = 724;
        final int h = 1024;
        for(int i=0; i < 10; i++) {
            Image placeholder = Image.createImage(w, h);
            Image img = URLImage.createCachedImage("experimentImage", "https://media.istockphoto.com/vectors/decorative-black-rectangular-frame-for-label-certificate-card-a3-a4-vector-id1039615844", placeholder, URLImage.FLAG_RESIZE_SCALE);
            images.addItem(img);
        }
        
        f.addComponent(viewer);
        viewer.setImageList(images);

        f.show();
```

**Comment by codenameone** [comment]
That's how it behaves for native image swiping in galleries too. It's really hard to guess what you're trying to do (swipe or pan) so once you zoom the default is "pan" until you reach the edge. I don't think we can improve on that.

**Comment by kutoman** [comment]
it has been more than a year. I could delay the feature I initially needed this issue fixed for, but now it's again on my agenda. 
I think this is a **serious** issue! Please note that this is not only happening when an orientation switch happened before. It's even happening when the app starts in landscape mode (with no orientation switching). When showing the `ImageViewer` initially, panning is **impossible** and is always interpreted as a swipe action. A vertical pan must not be interpreted as a horizontal swipe! This is something I do not experience in other applications (none CN1). Another issue is that the zoom is not working properly (but only tested on simulator so far). It feels like the ImageViewer was tested only in portrait mode by your side.

**Comment by shannah** [comment]
Fixed with https://github.com/codenameone/CodenameOne/commit/cd2951e61f685ed435203e1fad5c6eb45e222f9e

**Comment by kutoman** [comment]
@shannah thanks, I'm looking forward to the next update
