### ISSUE TITLE
 add more skins not work

### ISSUE THREAD

**Issue by fuadnassar90** [codenameone/CodenameOne#2680]
OS:Windows
IDE: Netbeans
Description:
after select and install skins from simulate and 100% process completion,
i'm not seeing the new skins in menu -just see the default skins-.
i tried to re-Run project after that but also there's no anything is happen.

**Comment by codenameone** [comment]
Check if the skins were physically downloaded to the `.codenameone` directory under your home directory. Was anything printed to the simulator console during download?
Are there preferences API issues in your machine?
Which JDK/windows versions?

**Comment by fuadnassar90** [comment]
thanks the problem was fixed and reason is name of folder user👍 
C:\Users\Fuad Nassar\Documents\NetBeansProjects\Test
i tried to delete space in "Fuad Nassar" and that's was work as fine.
