### ISSUE TITLE
CodenameOnePlugin Update Center for Netbeans 10

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2685]
This morning Netbeans 9 started to be crazy without any reason, highlighting a lot of nonexistent errors in my code. So I upgraded to Netbeans 10, automatically importing my preferences and plugins: this solved my problem.

However, Netbeans 10 allow me to use your plugin (imported from the Netbeans 9 installation), but it doesn't show it in the installed plugin list.

I'm using your CodenameOnePlugin Update Center. I have the suspect that your plugin is not detected as compatible with Netbeans 10.

**Comment by codenameone** [comment]
We need to submit the plugin to that center too. NetBeans is a bit annoying with these things.
