### ISSUE TITLE
"Simulate, Skins, Help" of the CN1 Simulator are not clickable

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2686]
From few hours, the "Simulate, Skins, Help" items of the CN1 Simulator menu are not clickable.
Problem experienced both with Netbeans 10 and Netbeans 9. Deleting the folders `.cn1`, `.cn1Settings`,  `.codenameone`, `.com.codename1.designer.css.CN1CSSCLI` doesn't make any difference.

Currently I downgraded to Netbeans 9 because my plugins are better supported. I use Java8.

_Product Version: Apache NetBeans IDE 9.0 (Build incubator-netbeans-release-334-on-20180708)
Java: 1.8.0_201; Java HotSpot(TM) 64-Bit Server VM 25.201-b09
Runtime: Java(TM) SE Runtime Environment 1.8.0_201-b09
System: Linux version 4.15.0-43-generic running on amd64; UTF-8; it_IT (nb)
User directory: /home/francesco/.netbeans/9.0
Cache directory: /home/francesco/.cache/netbeans/9.0_

**Comment by shannah** [comment]
This was a regression from the last update. It is fixed already here.
https://github.com/codenameone/CodenameOne/commit/e7970bbf1f58b068a8d339f06633f08fd51dc34b

Hopefully we'll get this fix out soon.

**Comment by jsfan3** [comment]
Thank you!
