### ISSUE TITLE
[Javascript] java.io.IOException - Temp file writing not supported yet.

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2691]
I have a code that takes a photo with camera or gallery, optimizes it overwriting the acquired image file with a smallest file (reducing the size and the JPEG quality), then I have the rest of my code that works on that image, and finally it deletes the temp file.

It works fine in native apps, but it throws on Javascript this exception:
`java.io.IOException - Temp file writing not supported yet.`

Of course it's not a big problem, I can rewrite my code... but, is there any technical reason to disallow the writing of a temp file?

**Comment by shannah** [comment]
Temp files in javascript are a special case.  For efficiency on JS, rather than copy files that are selected in a File dialog, I we just use the File object reference of the dialog itself.  In javascript these are read-only.  You can copy the image to file system storage and then modify it.
