### ISSUE TITLE
Need a connect timeout on com.codename1.io.Socket.connect

### ISSUE THREAD

**Issue by kroepr** [codenameone/CodenameOne#2692]
com.codename1.io.Socket.connect does not support connect timeout.

In the code below you will see that even trying to connect to an IP that is unavailable the error doesn't happen for 21 seconds. I can make it timeout before using a Timer however that still leaves system resources tied up until the 21 seconds have passed.

Test output:

Sat Feb 02 13:07:50 EST 2019
FAILED: Sat Feb 02 13:07:55 EST 2019
java.net.ConnectException: Connection timed out: connect
Sat Feb 02 13:08:11 EST 2019
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
Connection Error (-1): Failed to connect
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.codename1.impl.javase.JavaSEPort$SocketImpl.connect(JavaSEPort.java:10903)
	at com.codename1.impl.javase.JavaSEPort.connectSocket(JavaSEPort.java:11037)
	at com.codename1.io.Socket$1.run(Socket.java:70)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by kroepr** [comment]
`package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.SocketConnection;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.util.EasyThread;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private BrowserForm browserForm;

    public void init(Object context)
    {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start()
    {
        if (current != null)
        {
            current.show();
        }
        else
        {
            browserForm = new BrowserForm();

            current = browserForm;
            browserForm.show();

            browserForm.setPage("<html><body>HELLO WORLD</body><html>");
            test();
        }
    }

    public void stop()
    {
        current = getCurrentForm();
        if (current instanceof Dialog)
        {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy()
    {
    }

    public void test()
    {
        browserForm.setPage("<html><body>TEST</body><html>");
        
        EasyThread easyThread = EasyThread.start("TEST");

        easyThread.run(() ->
        {
            final Socket socket = new Socket();

            java.lang.System.out.println(new Date());
            com.codename1.io.Socket.connect("192.168.10.222", 80, socket);

            Timer timer = new Timer();
            timer.schedule(new TimerTask()
            {
                public void run()
                {
                    if (socket != null && !socket.isConnected())
                    {
                        socket.close();
                    }
                }
            }, 5000);

            while(!socket.isConnected() && !socket.isClosed())
            {
                try
                {
                    Thread.sleep(500);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
            }

            if (socket.isClosed())
            {
                java.lang.System.out.println("FAILED: " + new Date());
                browserForm.setPage("<html><body>TEST FAILED!!!!</body><html>");
            }
            else
            {
                java.lang.System.out.println("PASSED: " + new Date());
                browserForm.setPage("<html><body>TEST PASSED!!!!</body><html>");
            }
        });
    }
    public static class Socket extends SocketConnection
    {
        private boolean close = false;
        
        @Override
        public void connectionError(int errorCode, String message)
        {
            java.lang.System.out.println(new Date());
            java.lang.System.out.println("Connection Error (" + errorCode + "): " + message);
        }

        @Override
        public void connectionEstablished(InputStream is, OutputStream os)
        {
            synchronized(this)
            {
                if (close)
                {
                    try
                    {
                        is.close();
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }
       }
        
        public synchronized boolean isClosed()
        {
            return close;
        }
        
        public synchronized void close()
        {
            close = true;
        }
    }
}
`

**Comment by kroepr** [comment]
```
package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.SocketConnection;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.util.EasyThread;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private BrowserForm browserForm;

    public void init(Object context)
    {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start()
    {
        if (current != null)
        {
            current.show();
        }
        else
        {
            browserForm = new BrowserForm();

            current = browserForm;
            browserForm.show();

            browserForm.setPage("<html><body>HELLO WORLD</body><html>");
            test();
        }
    }

    public void stop()
    {
        current = getCurrentForm();
        if (current instanceof Dialog)
        {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy()
    {
    }

    public void test()
    {
        browserForm.setPage("<html><body>TEST</body><html>");
        
        EasyThread easyThread = EasyThread.start("TEST");

        easyThread.run(() ->
        {
            final Socket socket = new Socket();

            java.lang.System.out.println(new Date());
            com.codename1.io.Socket.connect("192.168.10.222", 80, socket);

            Timer timer = new Timer();
            timer.schedule(new TimerTask()
            {
                public void run()
                {
                    if (socket != null && !socket.isConnected())
                    {
                        socket.close();
                    }
                }
            }, 5000);

            while(!socket.isConnected() && !socket.isClosed())
            {
                try
                {
                    Thread.sleep(500);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
            }

            if (socket.isClosed())
            {
                java.lang.System.out.println("FAILED: " + new Date());
                browserForm.setPage("<html><body>TEST FAILED!!!!</body><html>");
            }
            else
            {
                java.lang.System.out.println("PASSED: " + new Date());
                browserForm.setPage("<html><body>TEST PASSED!!!!</body><html>");
            }
        });
    }
    public static class Socket extends SocketConnection
    {
        private boolean close = false;
        
        @Override
        public void connectionError(int errorCode, String message)
        {
            java.lang.System.out.println(new Date());
            java.lang.System.out.println("Connection Error (" + errorCode + "): " + message);
        }

        @Override
        public void connectionEstablished(InputStream is, OutputStream os)
        {
            synchronized(this)
            {
                if (close)
                {
                    try
                    {
                        is.close();
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }
       }
        
        public synchronized boolean isClosed()
        {
            return close;
        }
        
        public synchronized void close()
        {
            close = true;
        }
    }
}

```

**Comment by kroepr** [comment]
```
package com.cn1test;

import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Form;
import com.codename1.ui.layouts.BorderLayout;

public class BrowserForm extends Form
{
    protected BrowserComponent browser;
    
    public BrowserForm()
    {
        super(new BorderLayout());

        setUIID("Browser");
        getContentPane().setUIID("Container");
        getToolbar().setUIID("Container");
        browser = new BrowserComponent();
        add(BorderLayout.CENTER, browser);
    }

    public void setPage(String page)
    {
        browser.setPage(page, null);
    }

    public void setPage(String page, String baseUrl)
    {
        browser.setPage(page, baseUrl);
    }

    public void setURL(String url)
    {
        browser.setURL(url);
    }
}

```

**Comment by kroepr** [comment]
Can this be push into the Version 6.0 release? I need this in production. We are planning on going live end of the first quarter of 2019.

**Comment by shannah** [comment]
Note: Both the CN1Sockets cn1lib and the Websockets cn1lib support connection timeout already, in case you need this functionality now.

**Comment by kroepr** [comment]
Perfect. Will do. Thank you.

**Comment by shannah** [comment]
I've added support for Connection Timeout.  E.g.

~~~~
Socket.connect(host.getText(), PORT, new SocketConnection(timeout) {
....
});

~~~~

I've also add a SocketSample in samples to be able to test both client and server sockets.  

This will be available in update tomorrow.

**Comment by kroepr** [comment]
Thank you Steve.

Regards,
Remon Kroep
P: +1.561.807.1502 x2001 <(561)%20807-1502>
F: +1.866.459.4548 <(866)%20459-4548>
E: remonkroep@ordyx.com
[image: Ordyx] Simple, Secure, Online

CONFIDENTIALITY NOTICE: This email message is for the sole use of the named
recipient(s) and may contain proprietary, confidential and privileged
information. Any unauthorized review, use, disclosure, or distribution of
this message or any attachments is expressly prohibited. If you are not the
intended recipient, please contact the sender by reply email and destroy
all copies of the original message.

**Comment by kroepr** [comment]
Steve,

Now that connect timeout is supported, our app runs much better.

Thanks again.

Regards,
Remon Kroep
P: +1.561.807.1502 x2001 <(561)%20807-1502>
F: +1.866.459.4548 <(866)%20459-4548>
E: remonkroep@ordyx.com
[image: Ordyx] Simple, Secure, Online

CONFIDENTIALITY NOTICE: This email message is for the sole use of the named
recipient(s) and may contain proprietary, confidential and privileged
information. Any unauthorized review, use, disclosure, or distribution of
this message or any attachments is expressly prohibited. If you are not the
intended recipient, please contact the sender by reply email and destroy
all copies of the original message.
