### ISSUE TITLE
Wrong image orientation on Javascript port (on iPhone only)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2694]
The Javascript port of the following code works fine on Android, while it shows the taken photo with a wrong orientation on Safari and Chrome on iPhone X (as in the screenshot). Please also note that the same issue happens if you take a photo from the gallery.

```
Form hi = new Form("Hi World", BoxLayout.y());
        Button button = new Button("Take a photo");
        Label label = new Label(FontImage.createMaterial(FontImage.MATERIAL_PERSON, "Label", 40));
        hi.add(FlowLayout.encloseCenter(button));
        hi.add(FlowLayout.encloseCenter(label));
        hi.show();

        button.addActionListener(l -> {
            try {
                String path = Capture.capturePhoto();
                if (path != null) {
                    Image img = Image.createImage(path);
                    label.setIcon(img.scaledWidth(label.getIcon().getWidth()));
                }
            } catch (IOException ex) {
                Log.e(ex);
            }
        });
```

![1e6887d9-f487-477d-9fea-0b48b261b0c3](https://user-images.githubusercontent.com/1997316/52170782-fbfc6580-2750-11e9-87c9-61b5e446c828.PNG)

**Comment by codenameone** [comment]
When you grab portrait photos the camera sometimes saves them with camera orientation then marks them with a special flag indicating that they are rotated. Most image reading code ignores that flag. This problem exists on Android too AFAIK.

**Comment by shannah** [comment]
I have added auto-orientation correction for Photo capture now.  It will be available in the next server update.

**Comment by jsfan3** [comment]
@shannah Thank you, I waited the server update to do a test. You solved half of the problem, that is the orientation of photo captured with the Capture API, but your fix don't solve the wrong orientation of photos taken from the gallery with `Display.getInstance().openGallery`: for example, in the gallery I have a selfie that is correctly orientated, but when I open it with Codename One it's turned upside down.

(tested with Safari on iPhone)

**Comment by shannah** [comment]
openGallery will also now fix orientation for images.  Will be in the next server update.

**Comment by jsfan3** [comment]
Thank you
