### ISSUE TITLE
RFE: keep the focussed component selected even after a refresh in the component inspector

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2695]
This feature would be really appreciated! 
When I try to observe the properties of a specific component in the component inspector and have to repeatedly refresh the tree, it becomes really time consuming the deeper the component is in the tree. As long as the path to the selected component remains unchanged after a refresh the selected component should still be selected and the tree expanded accordingly.

In addition, it would be even more enriching if the feature requested in #1476 was integrated.

<img width="793" alt="bildschirmfoto 2019-02-03 um 11 10 22" src="https://user-images.githubusercontent.com/5825645/52175509-4c051780-27a5-11e9-8c0e-d97188cff230.png">

**Comment by ThomasH99** [comment]
I second that, I've had the same thought, and it would save a lot of effort :-)

Would also be great if the window could retain size and position between launches, as well as the size of each of the two panes.  I always have to manually replace and resize it, to have it next to the simulator window and be able to see all the details.
