### ISSUE TITLE
RFE: API to choose resolution to capture videos

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2696]
At the moment, the file sizes of videos captured with the Capture API of Codename One are too much large to be used in real world apps that need to upload the videos. This is a serious problem with recent smartphones. 

Moreover, I need a portable solution that includes Android, iOS and Javascript. 

Can you add an API to choose the video resolution, between the actually supported resolutions of the used device? The purpose is to take lightweight videos useful in a social app.

**Comment by jsfan3** [comment]
Thank you for quick reply.
I found a solution that seems cross-browser compatible in this actively-developed library that has several dependencies in other libraries:
https://github.com/collab-project/videojs-record

In the readme, there is a list of options. Two of these options are:

> frameWidth -> Width of the recorded video frames. **_Use media constraints to change the camera resolution width._**
> frameHeight -> Height of the recorded video frames. **_Use media constraints to change the camera height._**


Moreover:

> Media stream constraints allow you to specify the types of media to request, along with any requirements for each type.
> The following example shows how to change the camera or screen resolution to 1280 by 720 pixels:

In the readme, please note this example:
```
var player = videojs('myVideo', {
    controls: true,
    loop: false,
    // dimensions of video.js player
    fluid: false,
    width: 1280,
    height: 720,
    plugins: {
        record: {
            maxLength: 5,
            debug: true,
            audio: false,
            video: {
                // video constraints: set resolution of camera
                mandatory: {
                    minWidth: 1280,
                    minHeight: 720,
                },
            },
            // dimensions of captured video frames
            frameWidth: 1280,
            frameHeight: 720
        }
    }
});
```

I also noted that there are options that meet the requirement of recording lightweight videos useful to be uploaded in a social app, like the max length in MB and/or in time of the recorded video.

That's why I would like to enhance this RFE asking also a Codename One API to set a limit (in MB and/or in time) of the recorded video. To give the user a more complete experience, this library has methods to pause and resume the video recording.

I checked that this library also allows to select the wanted audio/video source (that is necessary to select the front or back camera).

However, I think that it's strictly necessary to have an API that returns the list of available resolutions before using an API to set a specific resolution. In this library I didn't see how to get the list of available resolutions (maybe there is a method that I didn't see), however in Javascript the list of available resolutions can be gotten with this method:
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities
As you can see in the table, the browser support is not specified for Safari and it's missing for Firefox. In these case, there could be an alternative approach. I found a bit of documentation here: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints
in which it's written how to set _a range of desirable values_. The range of desirable values can be a workaround if we don't know the list of available resolutions (in that case, it's necessary a Codename One API that accepts both exact resolution and a range of desirable resolutions as fallback).

So, I think that this RFE is possible and that you can improve a lot the opportunities of the usage of the camera with Codename One.

Thank you very much for your support and for your effort.

**Comment by shannah** [comment]
I have this working pretty well in Android and on Desktop.  I've been banging my head against iOS for a little while, but it turns out that Safari only works in their technology preview right now.  So it will work on the latest, greatest iOS Safari version in the future, but for now we're out of luck there.

I think, for now, I'm going to make iOS fall back to the regular capture behaviour.

**Comment by shannah** [comment]
I have just committed this.  This is a test case with sample usage:

~~~~
private void testVideoCaptureConstraints() {
        Form f = new Form("Test Video Capture Constraints", BoxLayout.y());
        TextField prefW = new TextField();
        prefW.setHint("Pref Width");
        TextField prefH = new TextField();
        prefH.setHint("Pref Height");
        TextField prefMaxLen = new TextField();
        prefMaxLen.setHint("Pref Maxlen");
        TextArea result = new TextArea();
        result.setRows(5);
        
        Button compile = new Button("Compile");
        compile.addActionListener(e->{
            int w = 0;
            int h = 0;
            int l = 0;
            try {
                w = Integer.parseInt(prefW.getText().trim());
            } catch (Throwable t){}
            try {
                h = Integer.parseInt(prefH.getText().trim());
            } catch (Throwable t){}
            try {
                l = Integer.parseInt(prefMaxLen.getText().trim());
            } catch (Throwable t){}
            VideoCaptureConstraints cnst = new VideoCaptureConstraints(w, h, l);
            result.setText("Result: "+cnst);
            
        });
        
        Button capture = new Button("Capture");
        capture.addActionListener(e->{
            String path = Capture.captureVideo(new VideoCaptureConstraints(320, 240, 10));
            result.setText(path);
        });
        
        f.add(new SpanLabel("Enter preferred video capture constraints, and press 'Compile' to see supported constraints"));
        f.addAll(prefW, prefH, prefMaxLen, compile, capture, result);
        f.show();
        
    }
~~~~

If the constraints or APIs are not supported, it falls back to default capture behaviour.     iOS currently doesn't support it.

Note:  VideoJS is big, so it is loaded dynamically at runtime - and the build server will strip it out by default, unless the `javascript.includeVideoJS=true` build hint is set.  The simulator will automatically set this build hint if you call `Capture.captureVideo(VideoCaptureConstraints)` or `Capture.captureVideo(VideoCaptureConstraints, ActionListener)`.

This will be available in the next update.

**Comment by jsfan3** [comment]
@shannah Thank you very much, I'll test it carefully when it will be available. However I didn't catch if what you done is about Javascript port only or also native apps. Same question about the problem on iOS: is it about Safari only or also about native apps?

**Comment by codenameone** [comment]
The change was made in the JavaScript port too.

**Comment by shannah** [comment]
Currently this is javascript port only.  However the API for video can be used cross-platform, and it will indicate whether the constraints are supported.   I'm working on porting this to native apps now.

The problem on iOS is about Safari, not native apps.  I should be able to implement this API in iOS native (but haven't yet).

**Comment by shannah** [comment]
I just committed support on Android native for video capture constraints.  I added a "Quality" constraint setting also which takes either a "high" or "low" value, since this maps more directly to Android's video capture workflow (the CAPTURE_VIDEO intent).  If you enter width/height constraints, Android will just map these to high quality or low quality depending on the size  (640x480 is the dividing line between high and low quality).

Android also supports directly the max file size, and max length (duration) constraints.

I will be modifying the JS port implementation tomorrow to add support for the quality and max file size constraints also, then I will move onto the iOS implementation.

**Comment by shannah** [comment]
Support has been added for iOS also.  iOS supports the quality (high/low) constraint directly. It also supports 3 specific size constraints: 640x480, 1280x720, and 960x540.

See iOS supported native mode settings [here](https://developer.apple.com/documentation/uikit/uiimagepickercontrollerqualitytype?language=objc).  We map video capture constraints to these using heuristics.

iOS also supports the maxLength (duration in seconds) constraint directly.  It does not support the max file size constraint.

**Comment by jsfan3** [comment]
Thank you very very much! :D

**Comment by jsfan3** [comment]
About the Safari issue, do you know if is it correct the following sentece about the default low quality?

“iOS/Safari does not support this feature yet, but this is ok since iPhones record small files by default when started from the browser” (taken from: https://stackoverflow.com/questions/45750326/html5-record-moderate-video-quality-for-upload-to-be-playable-by-safari)

**Comment by shannah** [comment]
This does seem to be the case, in my experimentation so far - and I have read this in multiple places as well.

**Comment by jsfan3** [comment]
Ok! I hope that you will also publish a good documentation of these new APIs with examples :)

**Comment by shannah** [comment]
UWP supported added.  Some documentation can be found here
https://github.com/codenameone/CodenameOne/wiki/Video-Capture-Constraints

Not sure where to put this documentation yet.  It should really be in the javadocs for the VideoCaptureConstraints class but editing javadocs is painful.

**Comment by jsfan3** [comment]
I've read your blog post https://www.codenameone.com/blog/video-capture-constraints.html and I tested your test case reported in this discussion. Thank you very much.

I noted some issues.

First issue:

iOS native and Javascript on iOS allow to replay the video after recording it and before tapping "Use video" (that means to return to the app). That's ok.

Instead Android native and Javascript on Android ask to open the video with an external application to see it before accepting it. Moreover, if I try to open it with one of the proposed apps, I get a blank black screen. Don't you think that Android should allow to see the just recorded video without any external application, like on iOS?

Second issue:

Your test case reported in this discussion uses `Capture.captureVideo(new VideoCaptureConstraints(320, 240, 10))`, so it allows a max length of 10 seconds, but on Javascript (tested using the live preview on Android and on iOS) it records more than 10 seconds. According to the table you posted in the blog, Max Length is supported by javascript. I also have the suspect that the given size (320x240) is ignored, because the quality of the live previews seems high (but it's only a suspect, I didn't check the produced file).

Third issue:

In a new project the default `ios.NSCameraUsageDescription` and `ios.NSMicrophoneUsageDescription` build hints are not inserted. Did you intentionally remove them? 

Fourth issue:

In the javadoc of VideoCaptureConstraints, the Platform Support Status is incomplete. Moreover, you wrote "You should set the preferred constraints, then `build()` the constraints", but the method `build()` doesn't exist, I didn't understood this sentence. About the javadoc, you didn't reported the three sizes supported by iOS (and in the blog post, you tell that iOS support three sizes but you don't specify which).

**Comment by shannah** [comment]
> Instead Android native and Javascript on Android ask to open the video with an external application to see it before accepting it. Moreover, if I try to open it with one of the proposed apps, I get a blank black screen. Don't you think that Android should allow to see the just recorded video without any external application, like on iOS?

I didn't notice this in my tests.  This will likely vary by Android version as this is not a low-level API.  It works by merely setting some parameters in the MediaStore intents.

> Your test case reported in this discussion uses Capture.captureVideo(new VideoCaptureConstraints(320, 240, 10)), so it allows a max length of 10 seconds, but on Javascript (tested using the live preview on Android and on iOS) it records more than 10 seconds. According to the table you posted in the blog, Max Length is supported by javascript. I also have the suspect that the given size (320x240) is ignored, because the quality of the live previews seems high (but it's only a suspect, I didn't check the produced file).

The definitive way to check if a constraint is supported is to use the isSupported() or isXXXSupported() methods.  You can also check the value of the constraint (e.g. `getMaxLength()`).  If it returns `0`, then it means that the platform doesn't support the constraint.

*Live Preview doesn't support any VideoConstraints*.  You need to use the Zip or .War version.

> In a new project the default ios.NSCameraUsageDescription and ios.NSMicrophoneUsageDescription build hints are not inserted. Did you intentionally remove them?

These are never added by default.  They are only added if you call Capture.capturePhoto() or Capture.captureVideo() in the simulator.  The simulator will automatically add these hints at that point.

> In the javadoc of VideoCaptureConstraints, the Platform Support Status is incomplete. Moreover, you wrote "You should set the preferred constraints, then build() the constraints", but the method build() doesn't exist, I didn't understood this sentence. About the javadoc, you didn't reported the three sizes supported by iOS (and in the blog post, you tell that iOS support three sizes but you don't specify which).

I'll correct the Javadocs.  build() is private, and is called automatically when whenever the preferred constraints change.

**Comment by jsfan3** [comment]
I've just opened a separate discussion for the first issue: https://github.com/codenameone/CodenameOne/issues/2736
