### ISSUE TITLE
RFE: Save zoom/rotate in Simulator been executions

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#270]
Original [issue 270](https://code.google.com/p/codenameone/issues/detail?id=270) created by codenameone on 2012-07-18T03:22:56.000Z:

<b>What steps will reproduce the problem?</b>
Simulators for hi-res devices require zooming out to see entire screen.  Would be nice to have the zoom/rotate settings saved for each skin.

<b>What version of the product are you using? On what operating system?</b>
Eclipse plugin 1.0.0.201207051020

**Comment by codenameone** [comment]
This was fixed a while back with scrolling, rotation is saved

**Comment by amiga** [comment]
Zoom still does not save.

**Comment by codenameone** [comment]
I agree we'll remove zoom for the next update. Scrollable is the only option that makes sense. We'll turn the menu to something that is a synonym to the scrollable functionality.
