### ISSUE TITLE
[Bug Javascript] Tapping the Toolbar opens the camera or the gallery

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2701]
First of all, this bug is specific of the Javascript port (it doesn't occur on native apps), using mobile browsers (Chrome on Android, Safari on iPhone, I didn't test other browsers) and only if I have a Form inside a Form (like in https://github.com/codenameone/CodenameOne/issues/2636). On desktop browser (Firefox and Chrome) the bug cannot be reproduced.

Step to reproduce:
- Run the following code on a mobile browser
- Tap "Take a photo"
- Tap "Click to access camera"
- Take a photo
- Tap the checkmark to confirm that you want the taken photo
- The photo will be shown in the Form
- Tap "Hi World" in the toolbar
- If doesn't happen anything, repeats these steps two or three times
- After few trials, tapping "Hi World" will open the camera (BUG)
- You can repeat these steps tapping "Choose from gallery", obtain a similar bug: "Hi World" will open the gallery.

In this video the bug occurs from in the third and fourth trials: 
https://www.informatica-libera.net/videoLavoro/Video-2019-02-10-12-30-57_0580.mp4

Please note that in my real app the bug always occurs, without the need to do two or three trials. In my real app, the bug occurs even if I tap the hamburger menu icon or another icon placed in the Toolbar. However, I wasn't able to produce a test case that always reproduce the bug starting from the first trial.

Code:

```
Form outer = new Form(new BorderLayout(BorderLayout.CENTER_BEHAVIOR_SCALE));
outer.getToolbar().hideToolbar();
Form hi = new Form("Hi World", BoxLayout.y());
outer.add(BorderLayout.CENTER, hi);

Button button1 = new Button("Take a photo");
Button button2 = new Button("Choose from gallery");
Label label = new Label(FontImage.createMaterial(FontImage.MATERIAL_PERSON, "Label", 40));

hi.add(FlowLayout.encloseCenter(button1));
hi.add(FlowLayout.encloseCenter(button2));
hi.add(FlowLayout.encloseCenter(label));

outer.revalidate();
outer.show();

button1.addActionListener(l -> {
    try {
String path = Capture.capturePhoto();
if (path != null) {
    Image img = Image.createImage(path);
    label.setIcon(img.scaledWidth(label.getIcon().getWidth()));
}
    } catch (IOException ex) {
Log.e(ex);
    }
});

button2.addActionListener(l -> {
    Display.getInstance().openGallery(new ActionListener() {
@Override
public void actionPerformed(ActionEvent evt) {
    String path = (String) evt.getSource();
    if (path != null) {
try {
    Image img = Image.createImage(path);
    label.setIcon(img.scaledWidth(label.getIcon().getWidth()));
} catch (IOException ex) {
    Log.e(ex);
}
    }
}
    }, Display.GALLERY_IMAGE);
});
```

**Comment by shannah** [comment]
Fixed.  This will be part of the next server update.

**Comment by jsfan3** [comment]
Thank you!
