### ISSUE TITLE
css cn1-background-type has no effect

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2707]
I also tried to reboot the simulator and other `cn1-background-type`s. The image (of `PlayIcon`) remains repeated..

component tree inspector, simulator and css side by side:
![bildschirmfoto 2019-02-15 um 16 59 37](https://user-images.githubusercontent.com/5825645/52868400-7f4f8b00-3143-11e9-9299-3131bf2e8cf9.png)

**Comment by shannah** [comment]
You're missing a semicolon after the background-image directive.  There should be an error written to your console when the CSS tries to compile that.

**Comment by kutoman** [comment]
indeed, sorry..
