### ISSUE TITLE
Codename One CodeScanner Library - cn1-codescan.cn1lib broken on Android

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#2708]
New user reported that they installed my app on Android and selected the scanner function. They got the prompt asking if they wanted to install the barcode scanner. They selected Yes. Google Play Store reports item not found.

I was able to reproduce the problem here by deleting the barcode scanner app ant trying to install it.

Went to CodenameOne Settings->Extensions, updated the cnilib, then refreshed the cn1lib files and submitted a new build. Same problem.

Looks like ZXing have restructured their app, they now have two different versions:

Barcode Scanner+ (Plus) - https://play.google.com/store/apps/details?id=com.srowen.bs.android&hl=en
Barcode Scanner+ Simple - https://play.google.com/store/apps/details?id=com.srowen.bs.android.simple&hl=en

I manually installed the simple version and my app found the scanner and I was able to scan.

I tried installing the plus version but it required way to many permissions. The simple version just requires camera access. I would recommend that you update the cn1lib to install the simple version.

**Comment by codenameone** [comment]
This can be fixed during the freeze as it's a separate cn1lib

**Comment by shannah** [comment]
Fixed to use BarCodeScanner+ Simple.  This doesn't require a reinstall of the cn1lib because this info is set in the CN1 core.
