### ISSUE TITLE
any plans to upgrade kotlin version?

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2711]
as far as I can see kotlin 1.0 is supported by CN1

**Comment by codenameone** [comment]
The issue tracker isn't a good place for plans. These depend on demand from users which makes more sense in the discussion forum or through enterprise support.

**Comment by kutoman** [comment]
@codenameone 
actually my intention wasn't to start a discussion. I was wondering whether you're open to upgrade the kotlin version. There are a couple of issues in kotlin 1.0 which are fixed in later kotlin version and I think it's important to have those fixed. It's also causing confusion when at one side CN1 is supporting 1.0 but on the other side the Intellij Kotlin plugin supports the latest version, as the compiler validates some code parts differently. I'm not even talking about the missing introduced features in later kotlin versions.

**Comment by codenameone** [comment]
If you want to convince us to do something that's a discussion
