### ISSUE TITLE
desktop.fullScreen = true in combination with BrowserComponent not working on 1920 x 1080

### ISSUE THREAD

**Issue by kroepr** [codenameone/CodenameOne#2712]

**Comment by kroepr** [comment]
Refers to issue #2669 . Issue not fixed.

**Comment by kroepr** [comment]
```
package com.cn1test;

import com.codename1.io.Log;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private BrowserForm browserForm;

    public void init(Object context)
    {
        // use two network threads instead of one
        updateNetworkThreadCount(2);
        requestFullScreen();

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start()
    {
        if (current != null)
        {
            current.show();
        }
        else
        {
            browserForm = new BrowserForm();

            current = browserForm;
            browserForm.show();

            browserForm.setPage("<html><body>HELLO WORLD</body><html>");
            test();
        }
    }

    public void stop()
    {
        current = getCurrentForm();
        if (current instanceof Dialog)
        {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy()
    {
    }

    public void test()
    {
        browserForm.setPage("<html><body>HELLO WORLD</body><html>");
    }
}

```

**Comment by kroepr** [comment]
Windows Desktop Build still not fullscreen on 1920 x 1080

**Comment by kroepr** [comment]
How do I get this fix in my NetBeans environment?

**Comment by kroepr** [comment]
Steve, I want to make sure this fixes the issue, how do send a Windows Desktop Build that will use this fix?

Currently the Windows Desktop Build still has the same issue.

**Comment by shannah** [comment]
The test case for this issue is at
https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/FullScreenWithBrowserComponentSample/FullScreenWithBrowserComponentSample.java

I just send a Windows Desktop build for it on the production build server and it seems to be working fine for me on my Surface Pro/Windows 10 machine.

I have recently added a samples section to the Codename One repository along with a SampleRunner application that will allow you easily browse and build samples on your own machine, against the master CN1 sources.  Instructions can be found [here](https://github.com/codenameone/CodenameOne/tree/master/Samples).

This sample is one of the samples that you can currently build and run in the SampleRunner.

Or you can just copy/paste/modify this sample the old fashioned way.

**Comment by kroepr** [comment]
Steve,

I just sent a new Windows Desktop Build to the production build server and it is not fixed. I am running Windows 10 as well on a screen resolution of 1920x1080. Screen is fullscreen for 1 second when app starts and then the window resizes (See attached screenshot).

![fullscreen](https://user-images.githubusercontent.com/2184305/54947581-0943fe00-4f11-11e9-99e0-402783d225c0.png)

**Comment by shannah** [comment]
I only have 3 windows machines.  All work fine with the "FullScreenWithBrowserComponentSample" sample.  

@codenameone Do you have access to a windows machine that you can test this on?

This is a link to the windows desktop build of that test case.
https://drive.google.com/file/d/1JKsXXu8kT0wuof64H8scy8YF_5glmfY6/view?usp=sharing

**Comment by shannah** [comment]
@kroepr Can you try this build also, just to make sure that we're working with the same thing
https://drive.google.com/file/d/1JKsXXu8kT0wuof64H8scy8YF_5glmfY6/view?usp=sharing

**Comment by kroepr** [comment]
@shannah I do not seem to have access rights since it does not allow me to download the .exe

**Comment by shannah** [comment]
@kroepr The has public permissions - anyone with the link can access it.  You must have some restriction on your end that is blocking .exe downloads?

**Comment by kroepr** [comment]
@shannah. Downloaded the .exe you sent and it has the same issue. See screenshot:

![fullscreen2](https://user-images.githubusercontent.com/2184305/55078056-9ac98200-506f-11e9-974f-8fecf5b329b4.png)

**Comment by shannah** [comment]
I was finally able to reproduce this issue on my Surface... I had been using Microsoft Remote Desktop, which was working fine, but when I used the surface directly, the issue was reproduced.

I have made a [change](https://github.com/codenameone/CodenameOne/commit/08a1a24a16263126ef16f0451db33b0d8d124a7b) that fixes this issue for me.

It will be available in the next update (on Friday).

**Comment by kroepr** [comment]
@shannah. Perfect, I'll test it when it's available.

**Comment by kroepr** [comment]
@shannah. I just tested the Windows Desktop Build and fullscreen still does not work.

**Comment by shannah** [comment]
Looks like it is [this JDK bug](https://bugs.openjdk.java.net/browse/JDK-8183109) related to HiDPI settings of the app.

What I've observed:

1. If you run the .exe file produced by the Windows Desktop Build on a HiDPI machine, it will produce incorrect results on first load for this test case.  It won't fill the screen.
2. If you include sources, and then build the resulting project in Netbeans, then it works properly.
3. The .exe file produced by Windows Desktop Build will work correctly if you change the Hi DPI settings for the app.  (e.g.  Right click the .exe (not the setup - the .exe installed by Setup), and select "Properties" > "Compatability" tab > "Change Hi DPI Settings" > Check the "Override high DPI scaling behavior" box).

The workround suggested in the [JDK Bug](https://bugs.openjdk.java.net/browse/JDK-8183109) was to use a tool like mt.exe to copy a manifest file into the exe file.    

I think it is likely that the work that @codenameone is doing right now with ZuluFX will fix this issue.

**Comment by kroepr** [comment]
@shannah. Thank you for the quick response. The workaround "Override high DPI scaling behavior" is working.

We will wait for the ZuluFX work to be finished for production.

**Comment by shannah** [comment]
It looks like this is working in the zuluFX build.  I.e. If you add the `win.desktop-vm=zuluFx8` build hint, it resolves this issue.
