### ISSUE TITLE
StatusBarLandscape

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2714]
Today I updated the Codename One plugin and the Project Libs, but the `StatusBarLandscape` is not used (I refer to https://stackoverflow.com/questions/54712910/codename-one-ios-statusbar-on-landscape-orientation). Please see this screenshot:

![componentinspector](https://user-images.githubusercontent.com/1997316/53173443-ff646d80-35e7-11e9-9e0c-72943dbc8f48.png)

**Comment by codenameone** [comment]
I missed one spot, lets postpone it to after the release.
We need to change this in Toolbar.java:

````java
                bar.setUIID("StatusBar");
````

to:

````java
            if(getUIManager().isThemeConstant("landscapeTitleUiidBool", false)) {
                bar.setUIID("StatusBar", "StatusBarLandscape");
            } else {
                bar.setUIID("StatusBar");
            }
````

You can do this yourself in the code to see how this looks in the simulator until after the release cycle.

**Comment by codenameone** [comment]
This was fixed in the release this Friday

**Comment by codenameone** [comment]
Sorry, no it wasn't...
