### ISSUE TITLE
Last changes

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2719]
Have you changed something about the functionality of Buttons?
The app I'm developing works quite fine in the CN1 Simulator, but I just discovered that in real devices (javascript, ios and android) it's now crazy... if I tap the Buttons the reactions are different and unpredictable. 

At the moment I cannot produce a test case because I've just discovered the problem in a very complex app and I need to investigate.

Probably the problem is caused by my code, but the fact that the behavior in the simulator is correct and that in the builds has become bugged seems strange.

**Comment by codenameone** [comment]
No. We're in code freeze for the release and haven't made changes since the 20th. Code in the devices and simulator should be identical.

**Comment by jsfan3** [comment]
Ok! After one day of trial and errors, I finally was able to reproduce the issue in the Simulator and then I fixed it. :-)
