### ISSUE TITLE
RFE: Gui Builder possibility to change order of components (in AutoLayout)

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2727]
actually I was surprised that such a feature is missing since it's crucial when components are overlapping each other. Changing the order over the raw gui file is not that straightforward when you also have defined reference components.

**Comment by shannah** [comment]
You can change the order using the component's context menu.
![image](https://user-images.githubusercontent.com/2677562/53895230-66b9ee80-3fe6-11e9-9a1b-a99e2cda6126.png)

Just press the context menu button (3 dots) above the selected component, then select "Arrange", then you get options to "move to back", "move to front", "move forward", and "move backward".

**Comment by kutoman** [comment]
oops.. I wasn't aware of it.. sorry

**Comment by kutoman** [comment]
but there seems to be a bug! When I move a specific component that way the reference links to that compoment get lost

**Comment by shannah** [comment]
That is fixed now.  It will be included in the next update.
