### ISSUE TITLE
Android 4.4.2 rounded rectangle border RenderScript thread issue

### ISSUE THREAD

**Issue by triplesub** [codenameone/CodenameOne#2730]
When using rounded rectangle borders in certain configurations on an Android 4.4.2 device, RenderScript threads are created until the application crashes due to lack of memory. The test device is an up to date Samsung TM-320, I haven't attempted to recreate on any other device. 

I have attached a test Eclipse project that shows the issue. Removing rounded rectangle borders solves the problem.

[ThreadIssueTest-project.zip](https://github.com/codenameone/CodenameOne/files/2940762/ThreadIssueTest-project.zip)

[ThreadIssueTest.log](https://github.com/codenameone/CodenameOne/files/2940766/ThreadIssueTest.log)

[ThreadIssueTest-debug.apk.zip](https://github.com/codenameone/CodenameOne/files/2940839/ThreadIssueTest-debug.apk.zip)

![threadissuetest - startup](https://user-images.githubusercontent.com/9727930/53950875-1796bb00-40c5-11e9-8a28-7121d7f07dec.jpg)

![threadissuetest - after buttons pressed](https://user-images.githubusercontent.com/9727930/53950879-1a91ab80-40c5-11e9-96e4-11d71bc12d8e.jpg)

**Comment by shannah** [comment]
I have not been able to reproduce this.  However, I have made a change to clean resources more proactively when doing gaussian blur.  This might fix the issue for you.  This will be part of the next update on Friday.  Please test an let me know if it fixes it.

**Comment by triplesub** [comment]
That's fixed it - thanks Steve.
