### ISSUE TITLE
Intellij IDEA: no detection of "error: cannot find symbol" on simulator run

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2735]
In Netbeans such errors (e.g. due to unsupported Java classes or members) are detected when we start the simulator but in Intellij it's not.
I think the Netbeans approach is better as that way we ensure that the code is valid during development.

**Comment by codenameone** [comment]
That's an inherent behavior in intellij/eclipse that can't be worked around at this time.
