### ISSUE TITLE
[BUG] TextComponent does not display correctly depending on its initialization state

### ISSUE THREAD

**Issue by 3lix** [codenameone/CodenameOne#2745]
First I will start by describing the flow of actions.
I create a form with empty text components and display the form right away, then I lazily fetch data from the server and set data on the text components via ```text()``` method. 

The following code produces the UI 
```
		Form hi = new Form("Hi World", new TextModeLayout(2, 1));
		TextComponent cmp1 = new TextComponent().label("label1");
		TextComponent cmp2 = new TextComponent().label("label2");
		hi.add(cmp1);
		hi.add(cmp2);
		hi.show();

               // call a web service and fetch text1, text2
 
		cmp1.text("text1");
		cmp2.text("text2");
		hi.revalidateWithAnimationSafety();
		hi.repaint();
``` 

![Capture-incorrect](https://user-images.githubusercontent.com/17162242/54801382-9860c580-4c34-11e9-9f1c-869968a74650.PNG)
Note: the ui above does not display the label + text, it only displays text!

The following code produces the correct UI , by adding any initial text
```
		Form hi = new Form("Hi World", new TextModeLayout(2, 1));
		TextComponent cmp1 = new TextComponent().label("label1").text("any text");
		TextComponent cmp2 = new TextComponent().label("label2").text("any text");
		hi.add(cmp1);
		hi.add(cmp2);
		hi.show();

               // call a web service and fetch text1, text2
 
		cmp1.text("text1");
		cmp2.text("text2");
		hi.revalidateWithAnimationSafety();
		hi.repaint();
``` 
![Capture-correct](https://user-images.githubusercontent.com/17162242/54801400-b0384980-4c34-11e9-8a5b-de2702574063.PNG)

**Comment by shannah** [comment]
Fixed.  Also added test case to SampleRunner.
https://github.com/codenameone/CodenameOne/tree/master/Samples/samples/TextComponentSample2745
