### ISSUE TITLE
[BUG] TableLayout  span constraints broken

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2759]
Recently updated CN1 (haven't done it in 4 or 5 months because I was working on other projects using another framework. so I don't know exactly when this bug appeared) and it appears that using an horizontalSpan constraint on a TableLayout makes the Form containing the container with this tablelayout to appear blank...
For exemple:

```
public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
                
        hi.setLayout(new com.codename1.ui.layouts.LayeredLayout());
        hi.setScrollableY(true);
        
        TableLayout gui_table_layout = new TableLayout(7, 2);
        com.codename1.ui.Container gui_table_container = new com.codename1.ui.Container(gui_table_layout);
        gui_table_container.setName("Table_Layout");
        
        gui_table_container.add(new Label("Test"));
        
        hi.addComponent(gui_table_container);
        
        hi.show();
    }
```

works fine and display a form with the "Test" Label whereas 

 ```
public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
                
        hi.setLayout(new com.codename1.ui.layouts.LayeredLayout());
        hi.setScrollableY(true);
        
        TableLayout gui_table_layout = new TableLayout(7, 2);
        com.codename1.ui.Container gui_table_container = new com.codename1.ui.Container(gui_table_layout);
        gui_table_container.setName("Table_Layout");
        
        gui_table_container.add(gui_table_layout.createConstraint().horizontalSpan(2), new Label("Test"));
        
        hi.addComponent(gui_table_container);
        
        hi.show();
    }
```

renders as a completely white Form
and in the simulator I don't see any log that could be related to this bug (so it is hard to track the cause)

**Comment by codenameone** [comment]
I'm not sure if this is a bug. You are spanning but aren't adding anything to the table. If you added a simple non-blank label to the next column this would have worked fine. 
The logic is that a cell doesn't determine row height if it's spanned. It makes no sense for it to do so. I looked at the suggested fix and I don't understand the logic behind it.

**Comment by ramsestom** [comment]
? I am adding a `new Label("Test")` component to the table not anything...

**Comment by codenameone** [comment]
You don't add anything in a non-spanned cell. Think about what are you saying in this statement...

I have "Test" which is two columns wide.

Column 1 has no components and column 2 has no components hence both end up with 0 width... The moment you add spanning into the equation we can't use it to increase the size of the columns as we don't know which column would be applicable.  Spanning is a feature that only makes sense in the context of other non-spanned components. Otherwise it doesn't make sense.
