### ISSUE TITLE
Fingerprint.isAvailable() returns true on Face ID but crashes on Fingerprint.scanFingerprint()

### ISSUE THREAD

**Issue by bunkowm** [codenameone/CodenameOne#2760]
Fingerprint.isAvailable() returns true on Face ID but crashes on Fingerprint.scanFingerprint().

It seems as though Fingerprint.isAvailable() returns true if either face or touch is available on IOS. However, if face is the type available on the device, the app crashes when scanFingerprint is called. It’s not clear to me what causes the crash and we don’t get any logs from CN1 when the crash occurs so its difficult to understand what is happening from our side.

If the following gibhub lib is the code that is used in the codenameone lib, it looks as though there is no check on biometric type (and based on what little I understand of the IOS biometric interface, there really doesn’t need to be, unless you want to change the interface based on what is available). 
https://github.com/codenameone/FingerprintScanner/
https://www.techotopia.com/index.php/Implementing_TouchID_Authentication_in_iOS_8_Apps

Could you guys confirm that either face isn’t supported (and change isAvailable to reflect that) or (better) track down the crash? If there is something we can provide to help you let us know. We have reproduced this on two different devices (all the devices we have with Face ID).

**Comment by bunkowm** [comment]
Hi Steve,

Let me know if we can help with anything regarding this case. We get questions on this quite a bit. Please let me know if this will be in the 7.0 release and if not if there is any workaround you can recommend.

Thanks
Mark

**Comment by shannah** [comment]
Does this failure occur on [this](https://github.com/codenameone/FingerprintScannerTest/blob/master/src/com/codename1/apps/fingerprint/demo/FingerprintScanTest.java) test case?

**Comment by bunkowm** [comment]
Hi Steve,

Yes. That test app failed as well. 

Note: I simply replaced my main class with the test class so I wouldn't have to make a new app, etc. 

Are you not able to reproduce this? Let me know if you think something in config would cause this and I'll build an app from scratch. 

Steps for Face ID:
1) Renamed my main class and renamed the test class to be the main class the app looks at.
2) Built a test build and deployed it to an IPad Pro (3rd gen 12.9inch w/ 12.3.1 IOS).
3) Ran the app and clicked 'Scan Fingerprint' 
4) It never asks to scan my face and exits the app and goes to the menu. No crash email is ever sent to me.

Steps for Touch ID:
1) Same as app as above
2) ...
3) ... Deployed to an iphone 7 plus w/ IOS 12.3.1
4) It shows the Touch ID popup.
5) When I scan successfully it says 'Scan successful!' and when I use the wrong finger it says 'Scan Failed!' as expected.

**Comment by bunkowm** [comment]
Hi Steve,

An update: I built a brand new app from scratch with only that test class and ran the IOS cert wizard to deploy a debug app and it still crashed. Same devices used and same behavior on each. No crash logs sent.

Mark

**Comment by bunkowm** [comment]
Does this crash for you as well or does it work? I'm trying to figure out if it's something with how we're configuring the build or is something everyone will see. It seems strange no one else would be trying to use Face ID given the latest IPhones only have Face ID.

Thanks

**Comment by shannah** [comment]
This does not crash for me on iPhone 8 running 12.2

**Comment by shannah** [comment]
I have acquired an iPhone 10 with FaceID and have been able to reproduce this.  The problem is that FaceID requires a [NSFaceIDUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsfaceidusagedescription?language=objc) in the info.plist.

You can work around this by adding the `ios.NSFaceIDUsageDescription=Requires FaceID` build hint.

I'll update the library to automatically add this build hint also.

**Comment by bunkowm** [comment]
Hi Steve,

I was able to confirm adding the build hint allows it to handle Face ID and not crash both in the test app and in our app.

Thanks for looking into this.
Mark
