### ISSUE TITLE
RFE: TextArea.setHintUIID(String uiid);

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2761]
Currently `TextArea`, `TextField` and `TextComponent` can have an hint, but they don't allow to  choose its uiid, that always is `TextHint`.

That's fine in most case, but in my use case is not what I need. More specially, I have some `Form`s where the default `TextHint` is fine, but I have others where I need a custom uiid for `TextField`s.

Can you add the method `TextArea.setHintUIID(String uiid)` or a similar one?

**Comment by codenameone** [comment]
Try `textField.getHintLabel().setUIID("...")`

**Comment by jsfan3** [comment]
It was so easy! Thank you
