### ISSUE TITLE
[BUG] Dragging a SOUTH container is incorrectly propagated to an underlying element in the CENTER container

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#2766]
As discussed in [StackOverflow thread](https://stackoverflow.com/questions/55665594/issue-with-edt-violation-when-launching-component-inspector-probably-related-to).

About how to resolve it: when I debugged the CN1 code, I expected to find a test somewhere on whether the drag was 'above' (or intersecting with) the *visible* part of the Component before sending the event. Could that be a way to fix it? 

Here's the test code: 

```
//TEST: SWIPEABLE CONTAINER ALSO SWIPES UNDERLYING CONTAINER AS WELL
  Form hi = new Form("Welcome", new BorderLayout());
  Container list = new Container(BoxLayout.y());
  for (int i = 0; i < 20; i++) {
     SwipeableContainer swip = new SwipeableContainer(null, new Label("SWIPE"), new SpanLabel("ListElement " + i + " + a lot of fill text to make the element span over several lines so the dragging of the underlying Swipeable is normally noticeable"));
    list.add(swip);
  }
  list.setScrollableY(true);
  Container cont = hi.getContentPane();
  cont.add(BorderLayout.CENTER, list);
  SwipeableContainer swip = new SwipeableContainer(null, new Label("SOUTHSWIPE"), new Label("SOUTH CONTAINER"));
  cont.add(BorderLayout.SOUTH, swip);
  hi.show();
```

**Comment by shannah** [comment]
@ThomasH99 The linked stackoverflow thread does not appear to be related to this issue.  You must have pasted the wrong link.

Without more context, I'm not sure what to make of this.  I built the test case, but it looks fine to me.  Please describe:

1. Steps to follow when running the test case.
2. What you expect to happen.
3. What actually happens.

**Comment by codenameone** [comment]
https://stackoverflow.com/questions/55664027/dragging-a-south-container-is-incorrectly-propagated-to-an-underlying-element-in/55671835

Try the test case and scroll a bit so you see the last element half peeking. Then swipe the entry in the south. You would see both the south and the last element in the box Y swiping together.

**Comment by shannah** [comment]
Fixed.
Test case added to samples: https://github.com/codenameone/CodenameOne/tree/master/Samples/samples/SwipableContainerTest2766
