### ISSUE TITLE
[RFE] Support any icon font in calls like Label.setMaterialIcon

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#2767]
As discussed in the comments [here](https://www.codenameone.com/blog/using-icon-fonts-such-as-fontello.html). 

Copy of text for reference: 

Hi, I would like to start using external Icon fonts in addition to the CN1 Material font. Is there some way to use external fonts as easily as the built-in Material icons, e.g. use them in `Label.setMaterialIcon()`? A method like `setMaterialIcon()` is really practical because it automatically sets size and color of the icon as defined by the Label UIID style, but it currently seems to have hard-coded support for the predefined CN1 Material icons only?
 
Shai Almog Mod  Ch Hjelm:
That would be great but I'm not sure how we can enable something like that in terms of the API?
One of the ideas that floated around when we introduced FontImage was to create it in an "auto-adapt" mode so it will use component styles all the time. This makes the code a bit awkward as you'd need to create multiple FontImage instances and won't be able to reuse them.
The material code is easy to do because we just pass the character and possibly the size. Here we'd need the additional information of the font which changes the balance a bit. If you have a suggestion of how the API should look I'd be interested in hearing that.
 
Ch Hjelm  Shai Almog:
I'm not much into the inner workings of CN1 but the external api could maybe be something like `Label.setFontIcon(Font font, char icon)`.

I can see that `FontImage.setMaterialIcon((Label l, char icon, float size)` calls `getMaterialDesignFont() `to get the Material font, so if that font could somehow be passed as a parameter instead, maybe that would do trick.

**Comment by ThomasH99** [comment]
I couldn't find this RFE yesterday when I submitted a pull request for an implementation, but if you accept the PR you can close this one

**Comment by codenameone** [comment]
Thanks!
