### ISSUE TITLE
RFE: set a Date before 1970 with a lightweight picker

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2771]
Currently it's not possible to choose a year before 1970 with a lightweight picker: it's a problem for birthdays.

Test code:
```
Property<Date, MyApplication> birthday = new Property<>("Birthday", Date.class, new Date(946749702782l)); // default Date: January 1, 2000
        Form hi = new Form("Picker Test", BoxLayout.y());
        Picker datePicker = new Picker();
        datePicker.setUseLightweightPopup(true);
        datePicker.setType(Display.PICKER_TYPE_DATE);
        UiBinding uib = new UiBinding();
        uib.bind(birthday, datePicker);
        hi.add(datePicker);
        hi.show();
```

**Comment by ramsestom** [comment]
Setting the start date of the picker with the setStartDate() function (like setStartDate(new Date(-2208988800L)) if you want Jan 1st 1900) should work just fine. It is just that the default starting date is set to Date(0) (1st Jan 1970) in the picker constructor. But you can change it

**Comment by jsfan3** [comment]
@ramsestom Thank you for the hint, it was helpful, however your example is incomplete, because it's necessary to set also the end date. The previous test case can be fixed adding:
```
datePicker.setStartDate(new Date(-2208992400000l)); // Jan 1 1900
datePicker.setEndDate(new Date(System.currentTimeMillis())); // today
```
