### ISSUE TITLE
Localize the months of lightweight date picker

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2773]
As described here:
https://stackoverflow.com/questions/55788922/localize-lightweight-date-picker-in-codename-one/55789622#55789622

the Codename One lightweight picker is always in English.

My RFE is to automatically localize the months.

**Comment by jsfan3** [comment]
I would like to correct this RFE in a way that allows a correct localization.
Translating the months isn't enough: for example, an Italian person never writes or selects the month on the left, the day on the center and the year on the right, but he/she expects the day on the left and the month on the center. So a correct localization should consider the correct position of day, month and year in a given locale.

I hope that it is possible.

**Comment by codenameone** [comment]
Can you provide a screenshot of the native date/time spinner in your locale?

**Comment by jsfan3** [comment]
Yes, of course.

The following code:
```
Form hi = new Form("Hi World", BoxLayout.y());
        Picker value = new Picker();
        value.setType(Display.PICKER_TYPE_DATE);
        value.setUseLightweightPopup(false);
        hi.add(value);
        hi.show();
```

generates this UI on Android:

![android](https://user-images.githubusercontent.com/1997316/56492855-505fe780-64ed-11e9-8581-1e76d357a9de.png)

As you can see, the day is on the left, the month on the center, the year on the right.

While the following code:
```
Form hi = new Form("Hi World", BoxLayout.y());
        Picker value = new Picker();
        value.setType(Display.PICKER_TYPE_DATE_AND_TIME);
        value.setUseLightweightPopup(false);
        hi.add(value);
        hi.show();
```

unfortunately generates the following mess on Android:
![mess](https://user-images.githubusercontent.com/1997316/56493057-117e6180-64ee-11e9-896c-dc08b0b4aa24.png)

and it's even a worse mess on the Simulator:
![simulator](https://user-images.githubusercontent.com/1997316/56493114-51454900-64ee-11e9-92a2-03277ad56017.png)

Of course, **the only correct UI with an example of native Italian localization of a date is the first screenshot.**

**Comment by codenameone** [comment]
I meant native on iOS which is the type of UI you referred to in the issue.

**Comment by jsfan3** [comment]
Ok, this is the native UI on iPhone: as you can see, the position of day, month and year is correct (in contrast with the equivalent lightweight picker), but the months are not localized (so this issue is common with the lightweight picker).

![ios](https://user-images.githubusercontent.com/1997316/56495978-f31d6380-64f7-11e9-9835-7c7b83a276a2.png)

**Comment by shannah** [comment]
The lightweight date picker uses the `com.codename1.l10n.SimpleDateFormat` class for all of its dates.  This class supports localization, but it is not tied into the native platform at all.  You'll need to localize these strings yourself in your resource bundle.  The keys to localize are:

* `MONTH_LONGNAME_JANUARY` ... `MONTH_LONGNAME_DECEMBER`  (for the long month names)
* `MONTH_SHORTNAME_JANUARY` ... `MONTH_SHORTNAME_DECEMBER` (for short month names)

I know this isn't as "nice" as have the OS do it automatically, but it will get you there.

@jsfan3 Is this an acceptable compromise, or did you want to shift this into an RFE to integrate SimpleDateFormat with native localization?

@codenameone Any thoughts on this?  (Leaving as is vs integrating with platform localization)

**Comment by codenameone** [comment]
Did you test this?
`setResourceBundle` isn't mapped to the actual resource bundle and there is no way I see to set it globally.
It's also a non-standard mapping, in com.codename1.ui.Calendar we have a different convention for mapping.

This doesn't need to map to the OS mapping but there should be a way to localize this through the bundle.

**Comment by shannah** [comment]
You're right.  The resource bundle needs to be set explicitly, and the Picker and Spinner APIs don't expose it.

**Comment by jsfan3** [comment]
It seems me strange the need to localize the dates by hand. Moreover, please note that the localization should switch the position of days, months and years according to the locale (as I described above, please see the last screenshot I reported), and that is impossible using only the resource bundle.

**Comment by codenameone** [comment]
Localization by hand has the advantage of allowing you to have a consistent experience across locales. E.g. if my phone has one localization but my app is only in English it looks odd to suddenly jump to a different language.

We need to provide a way within the resource bundle to determine the order of the date spinner. Probably a resource bundle constant similar to `@rtl`.

**Comment by jsfan3** [comment]
Ok, your example is fine.

**Comment by shannah** [comment]
I have added some heuristics to localize both the month name, and the field ordering based on the platform localization settings.  This should resolve this issue on its own.

However, I have also tied the UIManager's resource bundle into the DateFormat that is used for rendering months so you can still override the localization of month names manually in your resource bundle.
