### ISSUE TITLE
Center the internal layout of lightweight date pickers

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2774]
As described here:
https://stackoverflow.com/questions/55789170/fix-appereance-of-a-codename-one-lightweight-date-picker

my RFE is that the internal layout of lightweight date picker should be automatically centered (if it's possible).

**Comment by ernatrambulo** [comment]
https://stackoverflow.com/questions/55990877/can-someone-help-me-fix-this-picker-error as described, please fix
