### ISSUE TITLE
The fix of setSwipeActivated(...) doesn't work

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2781]
I tried your fix https://github.com/codenameone/CodenameOne/commit/e2c7f50d97dd37633ac4e946fe41e6db85d3412d, compiling the following test case against a just updated copy of the CN1 sources, but it doesn't work. I checked that my local copy of the CN1 sources containing your fix.

```
Form hi = new Form("Hi World", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_SCALE));
        Tabs tabs = new Tabs();
        tabs.addTab("Tab1", new Label("Tab1"));
        tabs.addTab("Tab2", new Label("Tab2"));
        tabs.addTab("Tab3", new Label("Tab3"));
        hi.add(BorderLayout.CENTER, tabs);
        tabs.setSwipeActivated(false);
        hi.show();
        hi.addShowListener(l -> {
            UITimer.timer(1000, false, hi, () -> {
                hi.show();
                tabs.setSwipeActivated(true);
            });
        });
```

**Comment by jsfan3** [comment]
I have a suggestion. Maybe this code is problematic:

```
if(swipeActivated) {
                        form.addPointerPressedListener(press);
                        form.addPointerReleasedListener(release);
                        form.addPointerDraggedListener(drag);
                    } else {
                        form.removePointerPressedListener(press);
                        form.removePointerReleasedListener(release);
                        form.removePointerDraggedListener(drag);
                    }
```

I've already noted in the past that adding and then removing listeners from the form can have undesirable effects (or, like in this case, it doesn't work). I don't know why, I only noted this fact. 

My suggestion is that another way to solve this issue could be to always add the listeners to the form and insert inside each listener an `if` condition, that is: do nothing (`return`) is `this.swipeActivated` is false, otherwise execute the listener.

**Comment by codenameone** [comment]
This works for me. I looked at your test case and it had a couple of issues:

````java
    tabs.setSwipeActivated(false);
    hi.show();
    hi.addShowListener(l -> {
        UITimer.timer(1000, false, hi, () -> {
            hi.show();
            tabs.setSwipeActivated(true);
        });
    });
````

Should be:

````java
    tabs.setSwipeActivated(false);
    hi.addShowListener(l -> {
        UITimer.timer(1000, false, hi, () -> {
            hi.show();
            tabs.setSwipeActivated(true);
        });
    });
    hi.show();
`````

Notice the show should be after the listener registration especially for the first form of the app. Also the timer is set to repeat which produces the event constantly.

**Comment by jsfan3** [comment]
Thank you!
