### ISSUE TITLE
Localize the months of native date picker

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2782]
Your `L10NManager` fix https://github.com/codenameone/CodenameOne/issues/2772 works, thank you, but the native localization of dates on iPhone is still not complete.

On iOS, the **native** date pickers show the month names in English (on an iPhone X with Settings -> General -> Language & Region -> Italian as language and Italy as region):

![56495978-f31d6380-64f7-11e9-9835-7c7b83a276a2](https://user-images.githubusercontent.com/1997316/57121438-cd098600-6d77-11e9-91a5-9fa0bda106c1.png)

This is similar to the issue https://github.com/codenameone/CodenameOne/issues/2773, but this is referring to the native picker; moreover, please note that the position of days, months and years is correct (while that position in the lightweight pickers is not localized correctly).

**Comment by codenameone** [comment]
This is probably because we don't have native resource bundles for the various languages.

**Comment by jsfan3** [comment]
Please note that the native date pickers of Android are localized correctly (the months names are in Italian). This issue is referring to iPhone only. At the moment, I didn't check the web-apps.
