### ISSUE TITLE
Better pinch-to-zoom

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2786]
Thank you for your support.

I replied to your comment to my question about the new cropping feature:
https://stackoverflow.com/questions/56013760/generalize-code-to-capture-and-crop-a-photo?noredirect=1#comment98673887_56013760

On real devices, the ImageViewer cropping works, but the pinch-to-zoom doesn't work very well: on Android 7, at the end of the pinch-to-zoom the image is sometimes moved to the top-left corner or the bottom-right corner without reason; on iPhone X, the pinch-to-zoom seems not fluid and, when the zoom is big, the image becomes all black (it returns visible reducing the zoom).

Could you please make the pinch-to-zoom working better?

The code that I used is the one reported in the link above.

**Comment by codenameone** [comment]
That might be a regression due to a recent PR that included support for tap to zoom. It might be misfiring since multi-touch is a bit fragmented between devices.

**Comment by shannah** [comment]
The Android issue is fixed.  This fix affects all devices.

I'm currently having some difficulties with my iOS development environment so haven't been able to look at iOS yet.

**Comment by shannah** [comment]
I've tested on iOS now.   In response to your observations:

> the pinch-to-zoom seems not fluid

I see what you mean.  Panning is smooth.  Pinch zoom is a little bit choppy.  IMO still quite usable.  I'll see what I can do to improve this.

>  when the zoom is big, the image becomes all black 

This happens when the image size crosses the device's max texture size threshold.  On iOS, images get rendered as OGL textures.  Working on fixing this now.

**Comment by jsfan3** [comment]
Thank you

**Comment by shannah** [comment]
Both the "black" image issue and the "choppiness" issue is now fixed in iOS.  It will be available in the next update.
