### ISSUE TITLE
Generating Android Certification in JDK12 results in failed build with invalid key format

### ISSUE THREAD

**Issue by davidwaf** [codenameone/CodenameOne#2787]
When generating Android Certificate under JDK12, builds fail with ".....java.io.IOException: Invalid keystore format"

**Comment by shannah** [comment]
Can you provide a more detailed stack trace of this error?  It will help in my googling for a solution.

**Comment by codenameone** [comment]
@shannah I think Oracle changed the format of the keytool certificate circa JDK 9. I think we might need a slightly different set of arguments to the command line tool when generating the certificate.
He's referring to an error in the build server, the Android certificate is generated "correctly" but building with it fails.

**Comment by davidwaf** [comment]
[error.txt](https://github.com/codenameone/CodenameOne/files/3166983/error.txt)
Find attached the error log

**Comment by shannah** [comment]
Yes.  [Here](https://docs.oracle.com/javase/9/tools/keytool.htm#GUID-5990A2E4-78E3-47B7-AE75-6D1826259549__GUID-A8B9E662-C1C2-4A0E-9307-A8464F0E95D4) it is:

> As of JDK 9, the default keystore implementation is PKCS12. This is a cross platform keystore based on the RSA PKCS12 Personal Information Exchange Syntax Standard. This standard is primarily meant for storing or transporting a user's private keys, certificates, and miscellaneous secrets. There is another built-in implementation, provided by Oracle. It implements the keystore as a file with a proprietary keystore type (format) named JKS. It protects each private key with its individual password, and also protects the integrity of the entire keystore with a (possibly different) password.

I have changed type to JKS explicitly in our wizard.  You'll need to regenerate the key after the update.

You should be able to workaround that value in the mean time by either generating the keystore with JDK 8 or earlier, or by override the default type in your `{JAVA_HOME}/lib/security` directory.

> If you don’t explicitly specify a keystore type, then the tools choose a keystore implementation based on the value of the keystore.type property specified in the security properties file. The security properties file is called java.security, and resides in the security properties directory:
> 
> Oracle Solaris, Linux, and OS X:: java.home/lib/security
> 
> Windows: java.home\lib\security
