### ISSUE TITLE
RFE: method to get all clientProperties

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2799]
Can you please add an API to Component to get all clientProperties as a Map?

I mean something like:

```
public Map<String, Object> getClientProperties() {
        return clientProperties;
    }
```

Thank you

**Comment by codenameone** [comment]
Why?
We specifically didn't add something like that to avoid a situation where client properties are used as a map. This could expose internal states of components which developers can rely on as a result. So this can break encapsulation. 

If you just want a Map you can just use `cmp.putClientProperties("myMap", map)`. Then you can use that to store arbitrary introspectable data.

**Comment by jsfan3** [comment]
You're right, probably what I asked is not the right approach.

The motivation of my RFE is the following method, that I created after your response https://stackoverflow.com/a/56094473

This method copies all relevant features of a Button, except the clientProperties that are hidden, that's why I thought to an API to get all clientProperties. However I can manage this issue in a different way.

By the way, do you think that a method like the following can give problems to add buttons to the Toolbar or is it okay? In the Simulator it seems to work correctly.

```
    /**
     * Adds a Button to the right bar (technically it does not add the Button
     * directly, but first creates a Command and then applies all the relevant
     * features of Button to it, see https://stackoverflow.com/a/56094473).
     *
     * @param form
     * @param btn
     */
    public static void addButtonToRightBar(Form form, Button btn) {
        Command cmd = Command.create(btn.getText(), btn.getIcon(), ev -> {
        });
        form.getToolbar().addCommandToRightBar(cmd);
        Button button = form.getToolbar().findCommandComponent(cmd);

        if (btn.getName() != null) {
            button.setName(btn.getName());
        }

        if (btn.getUIID() != null) {
            button.setUIID(btn.getUIID());
        }

        if (btn.getPressedIcon() != null) {
            button.setPressedIcon(btn.getPressedIcon());
        }

        button.setGap(btn.getGap());

        button.setTextPosition(btn.getTextPosition());

        if (btn.getListeners() != null) {
            for (Object listener : btn.getListeners()) {
                button.addActionListener((ActionListener) listener);
            }
        }
    }
```

**Comment by codenameone** [comment]
Yes that should work. Generally client properties are only used for transient purposes and never for important things. You don't need to copy them ever unless they are specific to your app in which case you would know about them.
