### ISSUE TITLE
Sheet component

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#2802]
This issue is just for posterity to mark the addition of the Sheet component.

I frequently need to display a dialog that slides up from the bottom. This is a common UI feature in both Android and iOS for which there isn't a direct equivalent in Codename One.

The Facebook app uses these extensively.  E.g.

![image](https://user-images.githubusercontent.com/2677562/57874296-1a98e080-77c5-11e9-8421-5a42c1ab6b50.png)

This is also a common mechanism for displaying dialogs with just a few option buttons.

E.g.

![image](https://user-images.githubusercontent.com/2677562/57874354-3b613600-77c5-11e9-9791-db7cd11fdd61.png)

(Source [Material Design Sheets bottom](https://material.io/design/components/sheets-bottom.html#usage)

## Features

* displays over the current form, sliding up from the bottom.
* user can navigate between sheets with an appropriate slide up/down transition between them, using a "back" button.
* user can  hide/close the sheet by tapping either a "close" button in the top left, or by tapping a part of the form not occupied by the sheet.
* Includes a "title bar" with a title, and a container to insert buttons in top right.

## Implementation

I have created the [Sheet class](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/Sheet.java) which satisfies all of these features.

I have also added a [usage sample](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/SheetSample/SheetSample.java) to the [Sample Runner](https://github.com/codenameone/CodenameOne/blob/master/Samples).

**Screenshot of Sample**

![image](https://user-images.githubusercontent.com/2677562/57874801-449ed280-77c6-11e9-8f26-e17ba6920aa1.png)

**ScreenCast**

[19 second screencast](https://youtu.be/3okEj_JW3-k)

Relevant commit:

https://github.com/codenameone/CodenameOne/commit/91f049dec16f5439ccd8bf59e141efb554c9fe33

**Comment by ericlight** [comment]
Hi Steve,
Can you take a look at this please? https://github.com/codenameone/CodenameOne/issues/2807
 I have some improvements ideas for this component.

Regards
