### ISSUE TITLE
Codename One Build iOS App (Beta) is expired

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2806]
The Codename One Build iOS App (Beta) is expired and not more available on TestFlight.
I hope you will keep this beta available, even if Apple doesn't want your app into their store.
Thank you.

**Comment by codenameone** [comment]
I'm not sure if this would be a good long term strategy. What features are you missing from the web app?

**Comment by jsfan3** [comment]
I've just tried the web-app installed to the iPhone X home and it doesn't work, in the sense that it doesn't allow to install apps. Please see this video:
https://www.informatica-libera.net/videoLavoro/codenameOneBuildWebApp.mp4

**Comment by codenameone** [comment]
I'll look into this. It seems like a regression

**Comment by jsfan3** [comment]
I've just tried the web-app to see if it works on iPhone X (iOS 12), but it doesn't.
To be more precise: I've discovered now that if I use it in Safari it works, but if I install it on the home (using the sharing icon of Safari to install web-app to home) it gives me the same error that I reported.

**Comment by codenameone** [comment]
I don't think this is fixable for "install on home screen". You would need to use Safari.

**Comment by jsfan3** [comment]
Ok
