### ISSUE TITLE
RFE: Improvements ideas for the new Sheet component

### ISSUE THREAD

**Issue by ericlight** [codenameone/CodenameOne#2807]
Hello,

Thanks Steve for the Sheet component. I have some improvements ideas for you.

**1)** On Android, the title is not centered vertically. To do that horizontally and vertically, I made a few change in your code on the line 128.

Your code at this line: `BorderLayout.center(FlowLayout.encloseCenter(title)),`
I change `encloseCenter` with `encloseCenterMiddle` and it’s now very well centered.

![CodenameOne Screenshot 1](https://user-images.githubusercontent.com/9592818/57969913-3ab5d480-796a-11e9-8731-b00ca90ee9b6.png)

**Well centered**

![CodenameOne Screenshot 2](https://user-images.githubusercontent.com/9592818/57969916-41dce280-796a-11e9-8ea5-0ec6732405fd.png)

**2)** When choosing an action, the Sheet does not close. Even if the action is executed, the Sheet remains on the screen. Can you provide a method to close that automatically once an action is executed ?

**3)** Can you provide a getter method for the "title" Label variable (Label)? It will allow us to apply styles if we want.

**4)** By default, the Sheet has rounded edges. I think it would be better to leave the choice to the user to decide if he wants rounded edges or not. For exeample, I added a third parameter (a boolean) to the constructor to get this :
 Line 163: `public Sheet(Sheet parent, String title, boolean roundedBorder)`
…
```
if(roundedBorder==true) { // my addition
            $(this).setBorder(RoundRectBorder.create()
                    //.topOnlyMode(true)
                    .bottomLeftMode(false)
                    .bottomRightMode(false)
                    .cornerRadius(2f)
            );
  **}**
```
If the third parameter is true, the Sheet will have rounded borders. Otherwise it will have normal borders.

**5)** Can you provide a second constructor which takes a Container as the second parameter? It will helps to build a title like something like that. Look at the screenshot.

![Screenshot_20190516-214145](https://user-images.githubusercontent.com/9592818/57969938-6e90fa00-796a-11e9-9ed6-dfee895a76ae.png)

**6)** Can you provide a method to hide the close button if we want ?

**7)** The line border that you put under the titlearea label doesn’t appear on Android so I tried to change the thickness of the border to 2 and it appear well now.

Once again, thanks for this component. It will be very nice if you can add one or more of the six points that I suggest you. Waiting for your reply :)

**Comment by shannah** [comment]
> On Android, the title is not centered vertically. To do that horizontally and vertically, I made a few change in your code on the line 128.

Thanks.  Fixed.

> When choosing an action, the Sheet does not close. Even if the action is executed, the Sheet remains on the screen. Can you provide a method to close that automatically once an action is executed ?

I'd prefer not to have automatic things happen when the user interacts with things in the commands container.  For simplicity, that container is a "black box" to the Sheet.  You can do what you like with it.  If you want an action to hide the sheet, you can just call the "back()" method on the sheet.


> Can you provide a getter method for the "title" Label variable (Label)? It will allow us to apply styles if we want.

I haven't exposed the label, but I have added an alternate constructor that will allow you specify a UIID for the sheet.  This UIID will be used as a base for all of the "important" components in the sheet, and will allow you to style it any way you like.  E.g. If you pass "Sheet" as the UIID parameter in the constructor, it will set the Sheet's UIID to "Sheet", the title label's to "SheetTitle", the title bar's to "SheetTitleBar", and the back button's to "SheetBackButton".

> By default, the Sheet has rounded edges. I think it would be better to leave the choice to the user to decide if he wants rounded edges or not. For exeample, I added a third parameter (a boolean) to the constructor to get this :

Rather than a roundborder constructor, you can achieve this using the UIID parameter to style it however you like.  Alternatively, you can just edit the border on the sheet itself using `sheet.getStyle().setBorder(...)`

> 5) Can you provide a second constructor which takes a Container as the second parameter? It will helps to build a title like something like that. Look at the screenshot.

I'll have to think about this.  

> Can you provide a method to hide the close button if we want ?

Done.  Added `hideBackButton()`

> The line border that you put under the titlearea label doesn’t appear on Android so I tried to change the thickness of the border to 2 and it appear well now.

I'll look into this.  I'm not able to reproduce so far.

**Comment by ericlight** [comment]
Hi Steve,
Thanks! I will make a test and come back to you soon.

**Comment by ericlight** [comment]
Hi,
For points 1, 2, 4, 5 and 6, everything is OK!

For the third point, there is a bug. When the first constructor is used, the title is no longer displayed. The title appear only if there is an UIID in the third parameter. 

With something like : `Sheet sheet=new Sheet(null, "Ajouter à Dropbox");`, i can't see the title anymore like on the screenshot
![CodenameOne Screenshot 1](https://user-images.githubusercontent.com/9592818/57972013-ed932c00-7984-11e9-890d-3532a3dc01bf.png)

There is also causes another problem. Adding the UIID displays the title, but all the default styles on the Sheet are lost when you do that. In this case, the simple fact of adding this UIID third parameter forces to define a UIID for all the zones of the Sheet (Title, BackButton, etc.). This is frustrating because the user may only want to style a single area. For my case, I just want to define the style of the label of the title. **That's why I asked a getter method for the title label**.

**The default visual aspect of the Sheet is broken when you add an UIID**

![CodenameOne Screenshot 2](https://user-images.githubusercontent.com/9592818/57972065-406ce380-7985-11e9-8a64-cb092d7c5ce5.png)

The UIID parameter that you added forces to define an UIID for each part otherwise the default visual aspect of the Sheet is broken.

**Comment by ericlight** [comment]
About my last message, screenshots comes form the simulator. When i made a test on the device, the title appears for the first case (using the first constructor and withour the UIID) but the font size is really small by default. On the simulator it doesn't appear at all.

**Here is the screenshot from the device:**

![Screenshot_20190518-161202](https://user-images.githubusercontent.com/9592818/57972329-5334e780-7988-11e9-9ffa-299442d9e12a.png)

**Comment by shannah** [comment]
1.  I cannot reproduce this.
2. Samples in the SampleRunner will only run against the "live" source code when run in the simulator.  If you submit to the build server, it will be built against whatever is deployed there. E.g. the Android device one won't be using my latest changes until the update occurs (usually on Fridays).
3. I have had some changes to make it easier to customize the themes.  Now, if you omit the uiid parameter in the constructor, or provide `null`, it will use uiid = "Sheet" - which is defined now in UIManager.  By default if uses the Sheet, SheetTitle, SheetTitleBar, and SheetBackButton uiids to style its components.  You can simply override these in your theme.  You can also specify the uiid paremeter in the constructor to e.g. "MySheet", in which case it will use MySheet, MySheetTitle, MySheetTitleBar, and MySheetBackButton.

**Comment by ericlight** [comment]
Ok Steve ! I will wait for the friday update to make new tests. Thanks

**Comment by shannah** [comment]
Just to be clear.  You are able to test now in the sumulator (via the SampleRunner).  You'd just need to wait until Friday to test on device.

**Comment by ericlight** [comment]
Ok i will do it
