### ISSUE TITLE
Default access point on Simulator is always null

### ISSUE THREAD

**Issue by timovandeput** [codenameone/CodenameOne#2809]
I want to detect if the phone is (still) online before sending a REST request, and have found `NetworkManager.getInstance().getCurrentAccessPoint();` to provide a reliable status on a physical device. On the Simulator, however, this call is not overridden in the platform implementation, and therefore always returns `null` (=no access point).

Please wire this method to the network connection setting in the Simulate/Network menu of the Simulator instead, so the behaviour in case of not being connected to a network can also be tested in the simulator.

PS: The Connectivity cn1lib also always reports being disconnected in the Simulator.

**Comment by codenameone** [comment]
Access point is a bit of a problematic API. Connectivity should work a bit better, I haven't see the problem you describe in the simulator though when I used it. You can exclude the simulator with `isSimulator()`.

**Comment by timovandeput** [comment]
Let me provide a few more details:

The code I am using to detect if the device is offline is as follows:
```java
    private void assertDeviceOnline() throws ServerException {
        String ap = NetworkManager.getInstance().getCurrentAccessPoint();
        if (!CN.isSimulator() && ((ap == null) || ap.isEmpty()))
            throw new ServerException(0, "Device is not online");
    }
```
(Note that it already includes the workaround to handle the `null` value of the simulator.)

My understanding is that this calls the JavaSE port with its source code in: https://github.com/codenameone/CodenameOne/blob/master/Ports/JavaSE/src/com/codename1/impl/javase/JavaSEPort.java

There I find the following implementation of `getCurrentAccessPoint()`:
```java
    //private String currentAp;
    /**
     * Returns the id of the current access point
     *
     * @return id of the current access point
     */
    public String getCurrentAccessPoint() {
        return super.getCurrentAccessPoint();
        //return currentAp;
    }
```

The code of the default `CodenameOneImplementation` implementation that is called in the fragment above reads as follows:
```java
    /**
     * Returns the id of the current access point
     *
     * @return id of the current access point
     */
    public String getCurrentAccessPoint() {
        return null;
    }
```
Are you really sure the current access point returns a non-null value in the simulator on your machine?

I would highly appreciate if the simulator at least returned an access point (so I don't need to explicitly check for the simulator myself), and would be thrilled if you could hook it up to the "Network/Disconnected" menu of the simulator so I can test the behaviour directly in the simulator instead of a physical device.

**Comment by codenameone** [comment]
No. What I was saying is that the access point API is something we originally developed to support RIM devices which required that. A 3rd party contributed an Android implementation and we don't really use that API much since it's pretty obtuse (and as you see it isn't universally supported). The connectivity cn1lib is much simpler and more portable. If it has drawbacks they are pretty easy to fix as the code is small/standalone.
