### ISSUE TITLE
Set the color/style for the iOS shaded Text Field's Hint Label

### ISSUE THREAD

**Issue by MichalRacek** [codenameone/CodenameOne#2811]
After styling the Text Field Hint Label via its `getAllStyles()` method, on iOS devices hint label gets _shaded_ once user taps into the field for input, but this _shaded_ hint can not be styled so far.

This behavior is not present in the simulator nor in the Android devices.

The screenshot is attached with TextField's hint styled behavior:
1. first one shows its hint styled,
2. second one shows its hint _shaded_ (iOS), when user taps in.
![TextFieldHint](https://user-images.githubusercontent.com/50906963/58162078-c472e400-7c81-11e9-9d29-4385bae29e22.png)

**Comment by shannah** [comment]
Can you clarify what you mean by "shaded"?  Do you just mean the color?  Can you provide either a small test case, or a snippet of code so I can try to reproduce this?

**Comment by MichalRacek** [comment]
I think following snipped will do the job - text field and its hint is styled with color. Hint's color is presented on UI (top text field on the screenshot).

But on iOS devices (not seen with simulator or Android devices) when user taps into the text field to enter values, hint text is still present (until some text/data is entered) and its color gets changed (bottom on the screenshot - you can see the cursor right on top of the hint text that is having its color changed).

```
TextField text = new TextField("", "Email or Username", 20, TextArea.ANY);
// field styling
text.getAllStyles().setFont(AVENIR_REGULAR_H4_STORY_DESCRIPTION);
text.getAllStyles().setBgColor(BG_SIGNIN_BUTTON_COLOR);
text.getAllStyles().setFgColor(FONT_MAIN_COLOR);
// hint styling
text.getHintLabel().getAllStyles().setFont(AVENIR_REGULAR_H4_STORY_DESCRIPTION);
text.getHintLabel().getAllStyles().setBgColor(BG_SIGNIN_BUTTON_COLOR);
text.getHintLabel().getAllStyles().setFgColor(FONT_HINT_COLOR);
```

**Comment by shannah** [comment]
Thanks.  I see. It's using the foreground color as the hint color in the native IOS field.  I'll have a fix out shortly.

**Comment by MichalRacek** [comment]
Thanks.

**Comment by shannah** [comment]
This is fixed now in git.  It will be available in the next update on Friday.
