### ISSUE TITLE
buggy drag and drop drawing and handling

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2814]
it's linked to this: https://stackoverflow.com/questions/56209300/how-to-avoid-drag-and-drop-traces-in-cn1?noredirect=1#comment99151434_56209300

I want to emphasize that there are several problems.

1. During the dragging a trace is left
2. In some cases the component can't be dragged at all (when attempting multiple times). This is happening in higher rates in a simulator run with iPadAir2.skin for example, but also on actual devices as well.
3. When in dragging mode the component gets vertically shifted. I'm not sure if this is due to wrong parameter settings on my side.

here is a Java sample code:

```
package com.igmghacumre.duaguide.utils;

import com.codename1.charts.util.ColorUtil;
import com.codename1.ui.*;
import com.codename1.ui.layouts.FlowLayout;

import static com.codename1.ui.ComponentSelector.$;

public class DraggingIssue {

    public static void run() {

        Form f = new Form("test", new FlowLayout(Component.LEFT, Component.CENTER));

        StraightDraggableLabel draggable = new StraightDraggableLabel();
        draggable.setDraggable(true);

        f.addComponent(draggable);

        f.show();
    }

    private static class StraightDraggableLabel extends Label {

        private final boolean isHDragEnabled = true;
        private final boolean isVDragEnabled = false;


        private int dragMinX = Integer.MIN_VALUE;
        private int dragMaxX = Integer.MAX_VALUE;
        private int dragMinY = Integer.MIN_VALUE;
        private int dragMaxY = Integer.MAX_VALUE;

        public StraightDraggableLabel() {
            setMaterialIcon(FontImage.MATERIAL_ARROW_FORWARD);

            $(this).selectAllStyles()
                    .setBgColor(ColorUtil.GREEN)
                    .setBgTransparency(255);
        }

        @Override
        protected Image getDragImage() {
            return toImage();
        }

        @Override
        protected void drawDraggedImage(Graphics g, Image img, int x, int y) {
            int dX = (isHDragEnabled)? clamp(dragMinX, dragMaxX - img.getWidth(), x) : this.getX();
            int dY = (isVDragEnabled)? clamp(dragMinY, dragMaxY - img.getHeight(), y) : this.getY();

            g.drawImage(img, dX, dY);
        }


        private int clamp(int min, int max, int actual) {
            return Math.max(min, Math.min(max, actual));
        }
    }
}
```

**Comment by codenameone** [comment]
Can you remove the `MathUtils` dependency?

**Comment by kutoman** [comment]
sorry for that, I've updated the code accordingly. As I was doing it, I noted that the trace issue has to do with the `isHDragEnabled` and `isVDragEnabled` restrictioning. Because when I write `int dX = x; int dY = y;` instead no traces are caused. But I don't know the reason.

**Comment by codenameone** [comment]
You're drawing the image in an incorrect position. It literally appears in the wrong place. Since we only clear the screen of the areas that were invalidated we have no idea that you drew the image in the incorrect place. I have no idea what you're trying to do here and why you overrode these methods.

**Comment by kutoman** [comment]
well my intention is, that the dragging can only happen in a predetermined direction and with predetermined max distances as you might guess from the animation below (trying to implement an unlock mechanism). That's why I try to at least affect the drawing of the dragged image 

![grafik](https://user-images.githubusercontent.com/5825645/58760077-856f4900-8533-11e9-9c80-5866af2c7dcc.png

**Comment by codenameone** [comment]
This isn't the way to do it, you could accomplish it with repaints but it would perform horribly and might flicker. You're trying to take a free form drag API and make it draw in a completely different position. I would suggest doing something MUCH simpler without the draggable API. Just use a pointer dragged listener to manipulate the left margin of the component so it appears to slide.
