### ISSUE TITLE
Offline builder undefined

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2816]
In the Codename One preferences, I downloaded an offline builder, as shown in the following screenshot:
![offline_builder](https://user-images.githubusercontent.com/1997316/58388328-c17b4900-801d-11e9-8165-5c90469d9190.png)

When I try to do an "Android offline build", I get this error:
_offline-builder-android:
/home/francesco/Projects/SimpleFronted/build.xml:120: Offline builder undefined, you need to define an offline builder in the Codename One -> Codename One Settings menu
BUILD FAILED (total time: 7 seconds)_

I didn't understand if I have to do something or if it's a bug.

**Comment by codenameone** [comment]
Try clicking the button and selecting it explicitly. It's possible that because it was never clicked it wasn't associated correctly.

**Comment by jsfan3** [comment]
Thank you, clicking the button solved this issue. 
Now I have this other error:
```
Error build failed, check out the error above
Executing: /home/francesco/Android/Sdk/tools/android create project --target android-27 --name StartPoint --path /home/francesco/Projects/SimpleFronted/build/and/StartPoint --activity StartPointStub --package cool.teammate.apps.frontend --gradle --gradle-version 3.0.1 *************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "create project --target android-27 --name StartPoint --path /home/francesco/Projects/SimpleFronted/build/and/StartPoint --activity StartPointStub --package cool.teammate.apps.frontend --gradle --gradle-version 3.0.1"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
Process return code is 2
Java Result: 2
```

It can be related to the Android Studio version? Currently I have the 3.2.1 version.

**Comment by codenameone** [comment]
Google effectively broke a lot of tools with some breaking changes they made to the SDK. You need to download older versions of the tools as explained here: https://discuss.cocos2d-x.org/t/cocos-compile-p-android-deprecated/35359/3

Then download SDK level 27 from there. We don't run into those issues since our server images are just replicas of the same SDK install.

**Comment by jsfan3** [comment]
I had difficults to find the direct links for download on developer.android.com. Finally I found this page with the links to download the version 25.2.* of the tools:
https://androidsdkoffline.blogspot.com/p/android-sdk-tools.html

I downloaded the 25.2.5 for Linux, I extracted it in `~/tools-CN1-25.2.5/tools/` and installed SDK level 27 from `tools/android`.

In the Codename One Preferences, I updated the Android SDK folder with the new `/home/francesco/tools-CN1-25.2.5`.

After that, the offline build had success.

I opened it with Android Studio, I changed the Gradle version in the settings of the project and I tried to run the project on my Android device.

Because of the error `Keystore file /home/francesco/Projects/SimpleFronted/build/and/StartPoint/keyStore not found for signing config 'release'`, I tried to copy the Android certificate that I use in all my Codename One apps:
`/home/francesco/Projects/androidCert/keystore_android.ks`
to:
`/home/francesco/Projects/SimpleFronted/build/and/StartPoint/keyStore`

but after that, I get this error on compiling:

`No key with alias '' found in keystore /home/francesco/Projects/SimpleFronted/build/and/StartPoint/keyStore`

Can you please give me any hint? Thank you

**Comment by codenameone** [comment]
Was this helpful?
https://stackoverflow.com/questions/40080710/no-key-with-alias-found-in-keystore

**Comment by jsfan3** [comment]
Thank you for link, I've seen it, but I'm not used to use Android Studio, so initially I didn't understand what to do.

The `signingConfigs` section of `build.gradle` was not generated correctly by the offline build server: the error was caused by an empty `keyAlias` value. I fixed the `keyAlias` value and the `storeFile` value.

After that, I was able to run the app in my device.
