### ISSUE TITLE
RFE: add a public abstract int getOffset(long time) function to the TimeZone class

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2818]
In order to be able to transform a locale date to UTC and vice-versa, I need to have access to the TimeZone .getOffset(long time) function. The SimpleTimeZone already has this function implemented but it has not been defined at the level of the abstract TimeZone parent class (unlike in the original Java API where it is: https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html) . 
So could you please add a `public abstract int getOffset(long time)` declaration to the TimeZone class? 
Also, in the Calendar class, the `DAY_OF_YEAR` field is missing the `public` statment. So could you please change that and set this field as public like others Calendar fields?
Thanks

**Comment by shannah** [comment]
You should be able to use [DateUtil.getOffset()](https://www.codenameone.com/javadoc/com/codename1/util/DateUtil.html#getOffset-long-) for this

**Comment by ramsestom** [comment]
Except that DateUtil.getOffset() only works if the date is in the current timezone. If I have a "local" timezone that do not match my device local timezone `(for example if my app need to compute and display dates for some places in the world in the local timezone of this place) it won't work. That is why having a getOffset() function directly attached to the TimeZone object it relates to is more convenient and powerfull. Anyway this is just a matter of defining this function in the TimeZone class as, as already said, the only actual TimeZone class implemented in CN1 (SimpleTimeZone) already have this function implemented (it's only that it isn't visible when the TimeZone object, retrieved from a Calendar Object for example, isn't typecasted to SimpleTimeZone)

**Comment by ramsestom** [comment]
Thanks.
Would be a good thing to also expose it into the TimeZone class too though, to match the legacy java API better, as it is already implemented into the SimpleTimeZone class anyway (which is the only TimeZone child class implemented in CN1)

**Comment by codenameone** [comment]
The main reason we try to avoid these things is the amount of work/bugs it produces. 
If you use `DateUtil` the code works 100% consistently on all OS's for every case. It's one piece of code we need to maintain and it's simple.
To place something in the VM we need to change: the iOS VM (Parpar), the JavaScript VM (TeaVM) and the UWP VM (iKVM). There are also the desktop and Android VM's over which we have limited to no control. So we need to change 3 VM's and hope the behavior matches that of the 2 other VM's.

The effort isn't justified for most cases. Here I'd rather focus our efforts on a proper port of 310 see https://github.com/ThreeTen/threetenbp/
