### ISSUE TITLE
Interaction with IOS multiprocessing

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2825]
My develop builds seem to interact correctly with IOS multiprocessing, which AFAIK has 3 distinct modes - one app can "float" above another, can be the base while another app "floats" above, and can be a bonded pair sharing the screen with a movable bar between them.

My release builds can only be the base for a floating second app.  They can't pair or float themselves.
Attached; a screen shot of the develop version in pair mode, which I can't achieve in the release
build
![Auto Generated Inline Image 1](https://user-images.githubusercontent.com/5963076/59049443-d1283800-883c-11e9-9393-b5816f7612b9.png)

**Comment by shannah** [comment]
Do you add any different build hints for the release build than for the debug build?  Can you build with sources and compare the generated Info.plist file between debug and release builds to see if there is a difference?  If so, please post them so I can see.

**Comment by ddyer0** [comment]
The build hints are the same, except for the dev build has no support for old hardware.
Attached are the info.plist files.
[Launch-Info.zip](https://github.com/codenameone/CodenameOne/files/3322687/Launch-Info.zip)
[Develop-Info.zip](https://github.com/codenameone/CodenameOne/files/3322691/Develop-Info.zip)

**Comment by shannah** [comment]
Your release build includes `<key>UIRequiresFullScreen</key><true/>` in the Info.plist which is the cause of this.   This suggests that you haven't set `ios.generateSplashScreens` build hint to `true` for release builds.

**Comment by ddyer0** [comment]
Thanks, I will try adding the build hint.  Note that it's not set in the development build either.
It's unclear what the relationship is or ought to be between building splash screens and requiring
full screen.  It seems to me these behaviors ought to be separated.

**Comment by shannah** [comment]
Generating splash screens is incompatible with iOS multitasking support.   Storyboards are the new way. See [this article](https://www.codenameone.com/manual/appendix-ios.html#_launch_screen_storyboards) for some more details on this.

Story boards will eventually be the default, but we haven't flipped the switch.

The `ios.multitasking=true` build hint is the one that technically enables/disables multitasking - only generating splashscreens overrides it to 'false'.

Are there any other differences in build hints between these two builds?  I can't see anything else that would cause this property to be included in the Info.plist

**Comment by ddyer0** [comment]
what about ios.fastBuild ?

**Comment by shannah** [comment]
The `ios.fastbuild` option has no effect if `ios.generateSplashScreens` is "false"

**Comment by ddyer0** [comment]
I don't see any other differences that ought to be significant.  Here are the hint panels.
![dev-hints](https://user-images.githubusercontent.com/5963076/61248920-eb411a00-a708-11e9-844f-c80f0a771bd2.jpg)
![release-hints](https://user-images.githubusercontent.com/5963076/61248935-f1cf9180-a708-11e9-9105-08fde77ac4ec.jpg)

**Comment by shannah** [comment]
I don't see anything significant there.  Perhaps post the actual codenameone_settings.properties files to compare.  If anything, based on that, both of them should have added the "UIRequiresFullScreen" key ... i.e neither should have "worked"

**Comment by ddyer0** [comment]
production settings

[production_settings.zip](https://github.com/codenameone/CodenameOne/files/3398352/production_settings.zip)
development settings
[dev_settings.zip](https://github.com/codenameone/CodenameOne/files/3398354/dev_settings.zip)

**Comment by shannah** [comment]
I can't see any reason one would work and the other not.  The fact that they both have the ios.multitasking=true build hint, and neither are generating splash screens mean that neither should be injecting `<key>UIRequiresFullScreen</key><true/>` into the Info.plist.

Are you doing any preprocessing on either of these files before sending the build?

**Comment by ddyer0** [comment]
the multitasking build hint was just added, it's not tested and not in the
light cone of this report discussion.

**Comment by ddyer0** [comment]
For whatever reason, probably the explicit ios.multiTasking build hint, my latest release builds
interact correctly now.
