### ISSUE TITLE
RFE: Change com.codename1.ui.Component.setScrollY(int) to public

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2826]
The getter method `com.codename1.ui.Component.getScrollY()` is public whereas the setter method `com.codename1.ui.Component.setScrollY(int)` is protected.

Since IOS kills apps when it needs the RAM occupied by those apps should be able to restore their state. Part of this is the state of scrollable Container derivates. 

It would be good to be able to call the `setScrollY` method without having to create a custom Container derivate.

It would probably be even better if Codename One had a factory for Container instances which then could deliver custom Container derivates with methods like `*Layout.enclose*` methods and such.

**Comment by jsfan3** [comment]
@saeder I also need to explicitly set the Y in some cases. I solved this problem with a class that has several methods to do custom scroll actions that I need. I copy for you the first four method that are enough for what you asked. Keep attention to the package:

```
package com.codename1.ui;

public class ScrollMe {

    public static int getScrollY(Component c) {
        return c.getScrollY();
    }

    public static void setScrollY(Component c, int y) {
        c.setScrollY(y);
    }

    public static int getScrollX(Component c) {
        return c.getScrollX();
    }

    public static void setScrollX(Component c, int x) {
        c.setScrollX(x);
    }

[... my other methods]
```

**Comment by codenameone** [comment]
This would break compilation as anyone who wrote code like this:

````java
protected void setScrollY(int y) {
     super.setScrollY(y);
     // my logic here...
}
````

Would fail compilation as a result. Having a generic `getState()` method might be an interesting API to have but I'm not sure if it's practical as you would need to restore everything including all the listener bindings etc. Scroll is just a small part of this. If this is the blocker you can use @jsfan3 workaround.
