### ISSUE TITLE
[BUG] rendering bug in the latest dev version of CN1

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2852]
I recently updated my CN1 fork and the latest development version has a rendering bug with some components.
I made a small video to show you the issue with a date picker:
https://streamable.com/w3wpm
At the right, this is the app runing with the latest CN1 dev version and at the left, with the latest official CN1 release. 
When spinning on the dev version, you can see that spinner labels dissapear whereas this is not the case (normal behaviour) with the latest official CN1 version. So this bug was introduced in one of the latest commits (probably f5ed440716fa8772a7c8ad545eaed68427b60703).

The source of the form used in the test video is simply:
```
package org.mycompany.test;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;


public class TestForm2 extends Form {


 public TestForm2() {
 
 setTitle("Test");
 setLayout(BoxLayout.y());
 
 Picker gui_birthdatePicker = new Picker();
     gui_birthdatePicker.setName("birthdatePicker");
     gui_birthdatePicker.setType(Display.PICKER_TYPE_DATE);
     gui_birthdatePicker.setDate(null);
 
 addComponent(gui_birthdatePicker);
 }
}
```

**Comment by codenameone** [comment]
This was indeed caused by that commit I reverted it as a workaround for now.
