### ISSUE TITLE
[BUG] selected style is ignored on radiobutton and checkbox

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2853]
on RadioButton and CheckBox, the selected style is completely ignored and the component is always rendered with the unselected style even if the checkbox or the radiobutton is actually selected. Actually none of these class overidde the `Component.getStyle()` function, as they should, to return the selected style when the component is in a `selected` state.

**Comment by codenameone** [comment]
Selected == Focused. It will render in pressed style the moment you touch it. This is slightly confusing as selected check/radio != selected component.

**Comment by ramsestom** [comment]
There is already a pressedStyle that is used to render when a component is pressed. 
The selected style is never used for check/radio components (when these components have focus, this is the pressed style that is used or the unselected one).
So they should use the selected style (that they don't use for now)  to determine the style that should be applied when they are in a selected state (same as for Button) as you may want to render them differently (for example change the background color) when they are in a selected state than when they are in an unselected one.

**Comment by codenameone** [comment]
Selected != Selected. There is no special style for the selected flag of radio/checkbox/toggle button. 
Selected (A.K.A focused) is mostly applicable in non-touch devices, try using the arrow keys in your physical keyboard and you'll see the selected style in action
