### ISSUE TITLE
BUG: TextArea preferred size is wrong for multiple lines

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#2858]
Apparently the `TextArea` calculates its preferred size of all lines concatenated instead of the largest line and the number of lines.

Here is code to test this - enter one or more lines and tap the button to revalidate the layout:

        Form hi = new Form("Hi World", FlowLayout.encloseMiddle().getLayout());
        TextArea textArea = new TextArea("Enter some text then press the button");
        textArea.setEditable(true);
        textArea.getAllStyles().setBorder(Border.createRoundBorder(20, 20));
		hi.add(textArea);
		FloatingActionButton floatingActionButton = FloatingActionButton.createFAB(FontImage.MATERIAL_FORMAT_SIZE);
		floatingActionButton.addActionListener(aActionEvent -> hi.getContentPane().revalidate());
		floatingActionButton.bindFabToContainer(hi.getContentPane(), Component.RIGHT, Component.BOTTOM);
        hi.show();

**Comment by codenameone** [comment]
Notice that it works on a typical layout. Text area reflows itself based on applied width/rows.
