### ISSUE TITLE
CNO is likely to fail parsing any date value in an http header when the local is different than English

### ISSUE THREAD

**Issue by ebardet** [codenameone/CodenameOne#2859]
Codename One parses cookie headers using months symbols that are loaded using the platform localized corresponding strings (see stack below).  Since https://tools.ietf.org/html/rfc6265#section-5.1.1 defines these months symbols to be English shorts:
month           = ( "jan" / "feb" / "mar" / "apr" /
                       "may" / "jun" / "jul" / "aug" /
                       "sep" / "oct" / "nov" / "dec" ) *OCTET
chances are Codename One will fail parsing the dates when the platform local language is not English.

DateFormatSymbols.createShortforms(String[], String) line: 222  
DateFormatSymbols.getShortMonths() line: 280    
SimpleDateFormat.readMonth(String, int, String, boolean) line: 883  
SimpleDateFormat.parse(String) line: 500    
SimulatorConnectionManager$1(ConnectionRequest).parseDate(String, String...) line: 1142

**Comment by codenameone** [comment]
This was fixed a few hours before this issue was opened
