### ISSUE TITLE
Can not open guiBuilder from eclipse  NPE 

### ISSUE THREAD

**Issue by demcho** [codenameone/CodenameOne#2866]
I try to open the guiBuilder from  eclipse and it gives me the next error: 
Unhandled event loop exception
java.lang.NullPointerException
at codenameoneplugin.GUIBuilderLauncher.open(GUIBuilderLauncher.java:40)
at org.eclipse.ui.internal.WorkbenchPage$31.run(WorkbenchPage.java:5485)

This is may set up

Ubuntu bionic 18.04.2 LTS
OpenJDK Runtime Environment Corretto-8.202.08.2
Eclipse Java EE IDE for Web Developers, Photon Release (4.8.0)
Eclipse Java EE IDE for Web Developers.
CodenameOnePlugin  6.0.0

This is what I have done, trying to  isolate the problem

Test with various files (java builder forms)
Test with various jvms for java 1.8: Correto, Azul, Oracle VM, Oracle OpenJdk
Test with eclipse Oxygen and Eclipse Photon
Test with a clean instalation    OS, JVM, Eclipse, new Codename proyect, new  Gui Builder (file)
Follow the guide https://www.codenameone.com/blog/tip-track-designer-guibuilder-issues.html

with the fowlling results 

Running  java -jar guibuilder.jar 
Retina Scale: 1.0
[EDT] 0:0:0,0 - Codename One revisions: 41704b739989b480681e24221e1289f51ace4a69

[EDT] 0:0:0,1 - Connector: file:/home/demch/.guiBuilder/guibuilder.input
[EDT] 0:0:0,19 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
at com.codename1.apps.guibuilder.GUIBuilder.getFilePath(GUIBuilder.java:81)
at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$16.run(GUIBuilderMain.java:576)

I Checked that my java files and  res.gui files are in place.
It seems that the  file guibuilder.input is not been generated by the eclipse plugin.
The  only files in the .guiBuilder are:  CN1Log'CN1Log__$'  CN1Preferences Cookies

Since the file guibuilder.input does not exist after launching guiBuilder from eclipse, I made one  with a text editor based on the example of the "TIP: TRACK DESIGNER & GUIBUILDER ISSUES". I try again  "java -jar guibuilder.jar"  ant it works the guiBuilder aplication succesfully opens with the content of my files  (java, gui).

So my hypothesis is that the codenameone eclipse plugin fails to generate the file "guibuilder.input"

May I help you  to debug the plugin it? Can you assist me to find the source file of codenameoneplugin.GUIBuilderLauncher.java(I can not find it)?

**Comment by codenameone** [comment]
This will be fixed in the 6.3 update. I'm not sure when this will be dropped.
