### ISSUE TITLE
Option to disable or dynamically toggle the prompt when leaving a JS Page

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2869]
Whenever I leave a page with a JavaScript built app I get the prompt of leaving in the middle of editing which isn't always desirable. There should be a way to disable this and ideally toggle it on/off dynamically.

**Comment by shannah** [comment]
This option is available as a platform hint that can be toggled on/off.
https://github.com/codenameone/CodenameOne/wiki/Working-With-Javascript#disabling-the-onbeforeunload-handler
