### ISSUE TITLE
nonsense key codes

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2874]
In the simulator, the form "keyPressed" and "keyReleased" public methods are passed nonsense codes for a few important characters.   I traced the problem down to this function in javaseport.java.  
I could accept this as a legacy for some game related application in the simulator's past, 
except for the awful fact that space and return are mapped to the same character.

        private int getCode(int k) {
            switch (k) {
                case KeyEvent.VK_UP:
                    return GAME_KEY_CODE_UP;
                case KeyEvent.VK_DOWN:
                    return GAME_KEY_CODE_DOWN;
                case KeyEvent.VK_LEFT:
                    return GAME_KEY_CODE_LEFT;
                case KeyEvent.VK_RIGHT:
                    return GAME_KEY_CODE_RIGHT;
                case KeyEvent.VK_SPACE:
                case KeyEvent.VK_ENTER:
                    return GAME_KEY_CODE_FIRE;
            }
            return k;
        }

**Comment by ddyer0** [comment]
One additional comment about this.   At the moment this mainly affects the simulator, since iOS and Android don't have keyboards.  That window is closing - chromebooks can have keyboards and IOS will support 5hem soon.

**Comment by codenameone** [comment]
You need to use the game key API not key pressed/released for "game keys". You're relying on behavior that isn't portable to all devices.

**Comment by ddyer0** [comment]
I'm implementing a keylistener, so i can replace the input functionality offered by TextArea.
Is there sme other way to get raw keyboard input?

**Comment by codenameone** [comment]
You have the options of using a native interface or actually using the game key functionality. I would suggest the former. Look at the game key API in form.
