### ISSUE TITLE
cant create new default project in netbeans

### ISSUE THREAD

**Issue by flightcrank** [codenameone/CodenameOne#2875]
1. go to new project
2. select CodnameOne project, click "Next" button
3. select target location click "Finish" button

Then the dialog closes and does nothing.

using netbeans 10

**Comment by codenameone** [comment]
Which version/supplier of JDK are you using?
Which OS?
Do you see something in the IDE log?

**Comment by flightcrank** [comment]
linux
jdk13
theres a log ? where ?

**Comment by flightcrank** [comment]
This issue is resolved by using OpenJDK11. It looks like the plugin breaks with OpenJDK13.
