### ISSUE TITLE
[Bug] From today weird effect on passing from a Form to another (on iOS)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2879]
From today I have a weird effect on passing from a `Form` to another (on iOS).
The default effect of `Form.show()`, that is a very short horizontal transition, shows a white blank area in the top left corner. This issue happens in my iPhone, while on my Android it's fine.

The following two screenshots are frames of two transitions. This happens in all Forms, both using `Form.show()` and `Form.showBack()`. In the areas inside the red corners there should be something during the effect, instead they are empty.

Screenshot 1:
![Screenshot_20190810_203057](https://user-images.githubusercontent.com/1997316/62825723-a2b63880-bbb0-11e9-8ec1-b635bc07a167.png)

Screenshot 2:
![Screenshot_20190810_205433](https://user-images.githubusercontent.com/1997316/62825786-7d75fa00-bbb1-11e9-8bd5-84b06388c0be.png)

**Comment by codenameone** [comment]
Is this happening with a simple test case or one of our samples/demos?

**Comment by jsfan3** [comment]
This morning I tried the KitchenSink demo, but it hasn't this issue.
Moreover, this morning the issue disappeared also in my app: I didn't do another build, it's the same of yesterday.
So, surprisingly the problem disappeared on its own as it appeared.
It's odd, maybe it was a problem of my iPhone device.

I close this issue for now, I'll reopen it if this bug reappears and if I find a way to reproduce it.
