### ISSUE TITLE
Possibility to translate IOS Usage descriptions from Localization section in Theme.res 

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2880]
it's very important to translate the IOS Usage description from the localization section in the theme.res, because are message visible by the users. Actually it just showed like you wrote in the file codenameone_settings.properties.

built hints very important to translates:
codename1.arg.ios.NSLocationAlwaysUsageDescription
codename1.arg.ios.NSPhotoLibraryUsageDescription
codename1.arg.ios.NSCameraUsageDescription
codename1.arg.ios.NSContactsUsageDescription
codename1.arg.ios.locationUsageDescription
codename1.arg.ios.NSLocationWhenInUseUsageDescription
codename1.arg.ios.NSLocationAlwaysUsageDescription 
codename1.arg.ios.NSMicrophoneUsageDescription 
codename1.arg.ios.NSAppleMusicUsageDescription

**Comment by codenameone** [comment]
I doubt that would be technically feasible. A more pragmatic way might be to add localized build hints for each locale. But we'll need to see.

**Comment by DurankGts** [comment]
please tell me about this issue. It's very important this support because is my app is translated to various languages this text is just in one language

**Comment by DurankGts** [comment]
please add support to this issue very soon if more important because this dialos appear to the clients and Always is in the same language actually.

**Comment by shannah** [comment]
Documentation here https://github.com/codenameone/CodenameOne/wiki/Miscellaneous-Features#localizing-native-ios-strings

This will be available on build server in tomorrow's update.

**Comment by DurankGts** [comment]
@shannah i need to create my own .zip file in the ant project?

**Comment by DurankGts** [comment]
![image](https://user-images.githubusercontent.com/16245755/136460868-989fb362-781b-442b-9178-21951ff2153d.png)
there is some problem in build server if I let my unnzipped folder there?

**Comment by DurankGts** [comment]
ok. What is the UsageDescription to receive remote notifications in IOS?

**Comment by DurankGts** [comment]
no in this file don't exist nothing key related with that.

what is the key used in the InfoPlist.strings to this build hint?
codename1.arg.ios.locationUsageDescription=xxxxxxxxxxxxxxxx

**Comment by shannah** [comment]
Best thing is to build with sources and look at the Info.plist file.
You camn refer to this too https://www.iosdev.recipes/info-plist/permissions/

**Comment by DurankGts** [comment]
Hi @shannah . I was testing in my real device In I could check the the Usage descriptions when My phone use English language is showing the usage Description that you implemented as Spanish.

![translation_usages_description](https://user-images.githubusercontent.com/16245755/145032098-04f8f88f-4570-4cd6-a10a-2100b2209432.png)


My InfoPlist.strings is ok in every folder zip

insde the folder native/ios I put 
en.lproj.zip
   InfoPlist.strings

![image](https://user-images.githubusercontent.com/16245755/145032535-97b5db2b-c6b2-47da-ba96-4c2194d8b58e.png)

es.lproj.zip
   InfoPlist.strings

![image](https://user-images.githubusercontent.com/16245755/145032589-23194146-db35-45d7-bc0d-3252896067e9.png)



Could you check if you config some thinks wrong in your build server or implementation

**Comment by shannah** [comment]
I don't think we can change that. 
Imagine what malicious things an app developer could do if they were able to change the labels on permission dialogs like this.  For example, they could change the "Do not allow" button to say "Allow", so that a user would be tricked into allowing access to something that they explicitly did not want to allow.

 When you change the language on an iOS device, some things don't get updated until you restart the device.  Probably those buttons are one of those things.

**Comment by DurankGts** [comment]
I don't have changed my language in phone. I just install my app and I understand that your implementation must to select the correct InfoPlist.string by the language phone.

**Comment by shannah** [comment]
Why do you have English strings in your es.lproj.zip and Spanish in your en.lproj.zip.  Wouldn't you want the opposite.

**Comment by DurankGts** [comment]
Not. I just write bad up in my first comment. I Check this very well before open this issue. Check the path in the image

**Comment by shannah** [comment]
That directory structure isn't standard.    E.g. you have this inside the "natives" directory.  Do you have some build script that copies these to the correct place?

**Comment by DurankGts** [comment]
not @shannah this not the correct folder. I just use this in my project to versioned because in the correct folder is needed a .zip folder. check the image like your documentation.

![image](https://user-images.githubusercontent.com/16245755/145091813-d6460115-c65f-4af0-9730-873b2dde42e1.png)

**Comment by DurankGts** [comment]
Any support about this issue

![Image](https://github.com/user-attachments/assets/fd2168c1-0e44-40e3-89e2-ceb6df68dfc2)

the problem it continue to day.
