### ISSUE TITLE
Back command don't work on Android when form transition is not set

### ISSUE THREAD

**Issue by jazter** [codenameone/CodenameOne#2881]
Back command don't work on Android when formTransitionIn and formTransitionOut is not set.

**Comment by codenameone** [comment]
We need a test case that reproduces this.

**Comment by jazter** [comment]
I could also reproduce the bug in the simulator. 
1.- Just create a new project
2.- Set the following code in start() function:

        Form form = new Form();

        //This lines causes the bug
        form.setTransitionInAnimator(null);
        form.setTransitionOutAnimator(null);

        form.addComponent(new Label("Hola"));
        form.getToolbar().setBackCommand("Back", new ActionListener<ActionEvent>() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                Dialog.show("Atras", "Atras", "Ok", "Cancel");
            }
        });
        form.show();

3.- Press back button in the nexus5 skin or another with the back button enabled.

**Comment by codenameone** [comment]
You need to use `CommonTransitions.createEmpty()` not `null`.
