### ISSUE TITLE
[BUG] Basic TextArea gives VKB issues on Android

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2886]
Test case:
```
Form hi = new Form("Hi World", BoxLayout.y());
TextArea textArea = new TextArea(3, 80);
hi.add(textArea);
hi.show();
```

issues (tested on Android 7 and Android 9):
- during the editing, the VKB doesn't allow to insert a new line (the "return" virtual key is not present)
- the only way to close the VKB is to tap the virtual key "Done": instead, if I tap in any place of the Form outside the TextArea, the VKB remains open.

In the past, if I remember correctly, the behavior of the VKB was different: it was possible to insert empty lines and the tapping outside the TextArea was a way to close the VKB.

**Comment by shannah** [comment]
Probably a regression related to https://github.com/codenameone/CodenameOne/commit/e0d893bf76a55ca80950d335adc1e5fefdd2b2cf#diff-d780ab872b45664cf0c5a367f36f6353

**Comment by jsfan3** [comment]
Thank you for your fix, I suppose that it fixes the "no return button" issue only.

What about the fact that, if I tap in any place of the Form outside the TextArea, the VKB remains open?
