### ISSUE TITLE
[BUG] When a TextArea loses the focus, the VKB remains open

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2887]
I report again this bug to don't lose its report in the closed issue https://github.com/codenameone/CodenameOne/issues/2886

The issue is that when a TextArea loses the focus, the VKB remains open.
In the past, if I remember correctly, it wasn't so.

**Comment by shannah** [comment]
You can disable this behaviour by disabling async editing.  You can do this app-wide, form-wide, or limit it to the particular textarea.

App-wide:

~~~~
Display.getInstance().setProperty("android.VKBAlwaysOpen", "false");
~~~~

Form-wide:

~~~~
myForm.putClientProperty("android.asyncEditing", Boolean.FALSE);
~~~~

TextArea

~~~~
myTextArea.putClientProperty("android.asyncEditing", Boolean.FALSE);
~~~~

**Comment by jsfan3** [comment]
Thank you very much!
