### ISSUE TITLE
[BUG] The text of multiline TextArea is shown in only one row

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2888]
I hope that this bug has the same cause of this other bug fixed few hours ago:
https://github.com/codenameone/CodenameOne/issues/2886

This new issue is that, on Android only, during the typing of a long line the text doesn't automatically break to a new line. The behaviour is slightly different between Android 7 (that breaks the text after closing the VKB) and Android 10 (that never breaks the text, so it results partially not visible).

So, at the moment the TextArea is bugged. If you already fixed this issue (I don't know if it's the same bug), could you please update the build servers? Thank you

**Comment by shannah** [comment]
Closed with https://github.com/codenameone/CodenameOne/commit/e0d893bf76a55ca80950d335adc1e5fefdd2b2cf#diff-d780ab872b45664cf0c5a367f36f6353
