### ISSUE TITLE
[BUG] Table cells wrong alignment (test case)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2893]
I report two issues with Table.

Test case (please note the commented line, it's important for the issue 2):
```
Form hi = new Form("Table", BoxLayout.yCenter());
        int rowsNumber = 2;
        int columnNumber = 3;

        String[][] rows = new String[rowsNumber][columnNumber];
        for (int i = 0; i < rowsNumber; i++) {
            for (int j = 0; j < columnNumber; j++) {
                rows[i][j] = "";
            }
        }

        String[] columns = new String[rows[0].length];

        TableModel model = new DefaultTableModel(columns, rows, true);
        Table table = new Table(model, false) {
            @Override
            protected TableLayout.Constraint createCellConstraint(Object value, int row, int column) {
                TableLayout.Constraint con = super.createCellConstraint(value, row, column);
                // con.setHorizontalAlign(Component.CENTER);
                con.setWidthPercentage(100 / columns.length);
                return con;
            }
            @Override
            protected Component createCell(Object value, int row, int column, boolean editable) {
                Component cell = super.createCell(value, row, column, editable);
                cell.setUIID("BaseStructureForm-TableCell");
                return cell;
            }
        };

        hi.add(table);
        hi.show();
```

CSS (please note the ` text-align`):
```
#Constants {
    includeNativeBool: true; 
}

BaseStructureForm-TableCell {
    text-align: center;
    font-family: "native:MainRegular";
    font-size: 3.0mm;
    color: blue;
    margin: 0px;
    padding: 0.5mm;
}
```

**Issue 1 -> Current behaviour with the reported code: the text aligns to the left during the typing and it aligns to the right after the typing, it never aligns to the center.**

Screenshot:
![screenshot](https://user-images.githubusercontent.com/1997316/63653444-fa39d400-c76c-11e9-930b-d9ee6d49e8c4.png)

**Issue2 -> Behaviour decommenting the line `con.setHorizontalAlign(Component.CENTER)`: it's impossible to type into the cells, if I click on another cell it doesn't take the focus.**

**Comment by codenameone** [comment]
Text field doesn't support center alignment at this time. Since it isn't supported it behaves oddly in both cases. So you can't center align editable content. You can add an RFE for that but it's non-trivial since the text will "jump" every time you edit center alignment text due to platform rendering inconsistencies.

The default cell behavior is scale. That means the cell takes up all the space. Once you align a cell preferred size of the cell is used which might be 0. Hence the cell content will align correctly but you won't have a big enough component to touch... I don't think that's a solvable issue.

**Comment by jsfan3** [comment]
Thank you Shai for the explanation.
After your answer, I found a workaround to get exactly what I want on iPhone and an acceptable behaviour on Android. 

TextField is a subclass of TextArea, but TextArea supports the horizontal center alignment better than TextField: I tested on the Simulator that it's impossible to center the text inside a TextField, while it's possible inside a TextArea. More precisely, on the Simulator and on Android the text inside a TextArea jumps to center after the typing, while it stays in the center during and after the typing on iOS. Instead on the Simulator the text inside a TextField jumps to right instead than to the center. 

My workaround is the override of this method of Table, to have a cell that is a TextArea instead of a TextField:
```
@Override
            protected Component createCell(Object value, int row, int column, boolean editable) {
                // Component cell = super.createCell(value, row, column, editable);
                TextArea cell = new TextArea(1,20);
                cell.setSingleLineTextArea(true);
                cell.setUIID("BaseStructureForm-TableCell");
                return cell;
            }
```
As you can in the following screenshot, the result on iPhone is perfect during the typing and after the typing:
![DA40F47F-2836-4AE5-926A-7F54B8480D32](https://user-images.githubusercontent.com/1997316/63753868-33c92700-c8b4-11e9-9856-c907cb079039.PNG)

Instead, on Android, the text is on the left during the typing and then "jump" to the center after the typing... that's better then before, because before it was jumping to the right.

Why is there this difference between TextField and TextArea?

**Comment by codenameone** [comment]
Text area is multiline by default and text field is single line by default. When typing in a single line the text keeps scrolling to the left when you exceed the line length. Try typing a lot of text more than the column can hold for both cases and see if the behavior matches your expectations.
