### ISSUE TITLE
[BUG] native PeerComponent not returning correct dimensions in some cases

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2896]
In some cases, the native components are returning wrong dimensions, causing layouts and display issues. For example, I was trying to have a `Form` displaying an interactive google map on its top and aditionnal input fields below. As the total height of these fields + map could exceed the screen height, I wanted to make the Form body Y scrollable. But doing so, it broke the map display and it appears that it is related to the native map component (a browserwebview in the case of the simulator) returning an incorrect height.
I made a simple example to test this bug:

```
setTitle("Test");
setLayout(new BorderLayout());
	       
Container body_container = new Container(BoxLayout.y());
body_container.setScrollableY(true);
		
Container mapcontainer = new Container(new LayeredLayout());
//{
//		public Dimension getPreferredSize() {
//			Dimension d = super.getPreferredSize();
//			d.setHeight(500);
//			return d;
//		}
//}; 
mapcontainer.setPreferredH(500);
MapContainer map = new MapContainer(XXXXX);
map.setCameraPosition(new Coord(48.856614,2.3522219)); //center the map on Paris, France
mapcontainer.add(map);
		
body_container.add(mapcontainer);
body_container.add(new Label("Some text 1"));
body_container.add(new Label("Some text 2"));
		
Button getheightbut = new Button("Get heights");
getheightbut.addActionListener(e->{
	System.out.println("Heights:"+mapcontainer.getHeight()+" "+map.getHeight());
});
		
addComponent(BorderLayout.CENTER, body_container);
addComponent(BorderLayout.SOUTH, getheightbut);
```

If the `body_container` isn't made scrollable, everything is fine:

![CN1ss1](https://user-images.githubusercontent.com/636758/63901273-2a4ed480-ca04-11e9-86e1-323c29ba2038.png)

but if I make `body_container` Yscrollable, the map appears cropped at its bottom (Paris, which is the point the map is supposed to be centered on, don't even appear on the displayed map anymore):

![CN1ss2](https://user-images.githubusercontent.com/636758/63901352-769a1480-ca04-11e9-8b43-bf3eeac8cb2e.png)

The same issue appear if I use the default Container layout (FlowLayout) for the `mapcontainer` Container

So, to resume, here is the results obtained:

body_container Yscrollable: no
mapcontainer layout: LayeredLayout
Heights:500 500
Map: OK

body_container Yscrollable: yes
mapcontainer layout: LayeredLayout
Heights:500 500
Map: Bugged (truncated)

body_container Yscrollable: no/yes
mapcontainer layout: FlowLayout
Heights:500 1136
Map: Bugged (truncated)

As you can see, when the `body_container` is made scrollable, even if the map.getHeight() seems to be ok (it returns 500), the map is cropped and the underlying map peer component seems to be higher. When the `mapcontainer` use a FlowLayout, the real (but unwanted) height of this native map component is returned: 1136 pixels (instead to the 500px expected)

To investigate a bit more, I changed a bit my test code and introduced another wrapping container:

```
setTitle("Test");
setLayout(new BorderLayout());
	       
Container body_container = new Container(BoxLayout.y());
//body_container.setScrollableY(true);
		
Container mycontainer = new Container(new LayeredLayout()); 
mycontainer.setPreferredH(500);
		
Container mapcontainer = new Container(new LayeredLayout());
MapContainer map = new MapContainer(XXXXX);
map.setCameraPosition(new Coord(48.856614,2.3522219)); //center the map on Paris, France
mapcontainer.add(map);
mycontainer.add(mapcontainer);
		
body_container.add(mycontainer);
body_container.add(new Label("Some text 1"));
body_container.add(new Label("Some text 2"));
		
Button getheightbut = new Button("Get heights");
getheightbut.addActionListener(e->{
       System.out.println("Heights:"+mycontainer.getHeight()+" "+mapcontainer.getHeight()+" "+map.getHeight());
});
		
addComponent(BorderLayout.CENTER, body_container);
addComponent(BorderLayout.SOUTH, getheightbut);
```

and here are the results:

body_container Yscrollable: no
mycontainer layout: LayeredLayout
Heights:500 500 500
Map: OK

body_container Yscrollable: yes
mycontainer layout: LayeredLayout
Heights:500 500 1136
Map: Bugged (truncated)

body_container Yscrollable: no/yes
mycontainer layout: FlowLayout
Heights:500 500 1136
Map: Bugged (truncated)

we can see that this time, every time the map is bugged (truncated at its bottom), the height return by map.getHeight() is wrong (1136 instead of 500)

I should mention that, in all cases, I obtain the same results by constraining the top container height with `.setPreferredH()` or overriding this component `getPreferredSize()` function to always return a height of 500

**Comment by codenameone** [comment]
This isn't reasonably fixable as native size computation runs on the native EDT which means we will need to constantly poll and reflow native peers. Not a reasonable option although you could do that if you want the flickering.
A solution is to use a deterministic layout that predefines sizes such as table layout (with width/height constraints), center border layout, grid layout etc.

**Comment by ramsestom** [comment]
Your answer completely miss the point. The size is predefined here by the wrapping container which has an height constraint and that determine the native component dimensions. So the native peercomponent do not have to perform any size computation. Its dimensions are deterministic and directly constrained by the CN1 parents lightweighted components. The rendered dimensions of the native components are always the same. It is just that in some cases it is cropped to be displayed to these dimensions instead of beeing created with native dimensions matching them. And this bug only appear when using specific options (= when the parent is scrollable or the wrapping component do not use a layeredlayout) and do not appear on android (it only appears in the simulator so it looks like this is linked to the webbrowser component beeing created with wrong dimensions and cropped in some cases) meaning it has nothing to do with the native component having to compute its size on the native EDT
