### ISSUE TITLE
checkboxes broken

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2900]
Sometime recently, the generic checkbox component broke, and is now
producing checkboxes that look like this:
![image](https://user-images.githubusercontent.com/5963076/64052501-97ad5300-cb33-11e9-91e5-b1633d89168e.png)

**Comment by shannah** [comment]
I can't reproduce.  Please post a test case that can reproduce this issue.

**Comment by ddyer0** [comment]
This turns out to be stranger than I at first thought.   The key step is setting setLookAndFeel
to a derivative of DefaultLookAndFeel, which I use to partially fix another problem, ie; that
menu widths are not calculated correctly.    Perhaps there is some class other than DefaultLookAndFeel I should be deriving from ?  The javadoc says it is deprecated, but
not what replaces it.

And also note again, that this is recent breakage.  I've been using the replacement
of defaultlookandfeel for 2 years.

java''''
package dtest.boardspace;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
//
// issue #2557
// This version demonstrates a crash "after a while" drawing upside down
// zoomed up bitmaps.  This is used in the real world when implementing
// pinch-zoom on inverted screens.
// first, draw a test pattern into a scratch image, display the test pattern,
// then display a portion of the test pattern, upside down, inside a rectangle
// on the actual window.  On IOS and the simulator, this loop runs indefinitely
// on android devices, it runs "for a while" then crashes.  Overall behavior
// suggests a resource exhaustion problem.
//
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.List;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.plaf.DefaultLookAndFeel;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;



class DCheckbox extends com.codename1.ui.CheckBox 
{	
	public DCheckbox(String string, boolean b) { super(string); setSelected(b); }

	public void setState(boolean b) { setSelected(b); }

}

@SuppressWarnings("deprecation")
class BSLookAndFeel extends DefaultLookAndFeel 
{	public BSLookAndFeel(UIManager m) { super(m); }
	/*
	public Dimension getListPreferredSize(@SuppressWarnings("rawtypes") List l)
	{
		Dimension dim = super.getListPreferredSize(l);
		dim.setWidth(dim.getWidth()+(int)(20));
		return(dim);
	}
*/
}
public class Dtest  {
	
    /**
     * Draw an image from/to particular rectangles with rescaling.  Note that
     * this uses left,top,right,bottomt coordinates rather than left,top,width,height 
     * @param gc	the gc to be written to
     * @param im	the image to be written from
     * @param dx	dest left
     * @param dy	dest top
     * @param dx2 dest right
     * @param dy2 dest bottom
     * @param fx  source left
     * @param fy  source top
     * @param fx2 source right
     * @param fy2 source bottom
     * @param c   the image observer (not used in codename1) 
     */
    public static void drawImage(Graphics gc,Image im,
			int dx,int dy,int dx2,int dy2,
			int fx,int fy,int fx2,int fy2
			)
{	if(gc!=null)
	{	int w = dx2-dx;
		int h = dy2-dy;
		int sw = fx2-fx;
		int sh = fy2-fy;
		int imw = im.getWidth();
		int imh = im.getHeight();
		double xscale = w/(double)sw;
		double yscale = h/(double)sh;
	   	int[]clip = gc.getClip();

		if(clip!=null && (clip instanceof int[]) && (clip.length>=4))
		{
	   	gc.clipRect(dx,dy,w,h);			// combine with proper clipping region
	   	//gc.setClip(dx,dy,w,h);		// runs wild, can write anywhere!
	   	int finx = dx-(int)(fx*xscale);
	   	int finy = dy-(int)(fy*yscale);
	   	int finw = (int)(imw*xscale);
	   	int finh = (int)(imh*yscale);
	   	gc.drawImage(im,finx,finy,finw,finh);
	   	gc.setClip(clip);
		}

	}
}	
 
    private Form current;
    @SuppressWarnings("unused")
	private Resources theme;
    private Image background;
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    int loops = 0;
   
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi >>0 World",new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE)); 

        UIManager man = UIManager.getInstance();
  	  	man.setLookAndFeel(new DefaultLookAndFeel(man));
  	  	
        current = hi;
        Container vpanel = new Container();
        current.add(BorderLayout.CENTER,vpanel);

        vpanel.setLayout(new FlowLayout());//new BoxLayout(BoxLayout.Y_AXIS));
         
 
        for(int i=0;i<20;i++)
         {
             DCheckbox cb1 = new DCheckbox("Test Checkbox #"+i,true);
             cb1.setOppositeSide((i&1)==0);	 
             vpanel.add(cb1);
         }

         hi.show();
        Runnable rr = new Runnable (){
        	public void run() {
        	System.out.println("running");
        	while(true)
        	{
        	hi.repaint();
        	try {
        	Thread.sleep(1);
        	}

        		  catch (InterruptedException e) {};
        		}}};
        	new Thread(rr).start();
   
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }
    


}
''''

**Comment by ddyer0** [comment]
this issue is not fixed.  please re-examine.

**Comment by shannah** [comment]
Here's a screenshot your test case:


![image](https://user-images.githubusercontent.com/2677562/64630936-ff249780-d3aa-11e9-8cec-7204251a9a19.png)


Source:
https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/CheckboxTest2900/CheckboxTest2900.java

**Comment by ddyer0** [comment]
I just compiled my test case and ran it, here's the screen shot
![Screenshot_2019-09-10-09-14-30](https://user-images.githubusercontent.com/5963076/64631467-0a2bf780-d3ac-11e9-8f1d-9836696285ef.png)

**Comment by shannah** [comment]
You're not running with the latest then.  My screenshot is also from compiling just now

**Comment by ddyer0** [comment]
I'm using the current live environment ( I have no other)

**Comment by ddyer0** [comment]
The other uncontrolled variable is the resource file.  Here's mine.
[src.zip](https://github.com/codenameone/CodenameOne/files/3596747/src.zip)

**Comment by shannah** [comment]
Try running the sample I linked to.  Apples with apples.  You can run it in the sample runner.

~~~~
git clone https://github.com/codenameone/CodenameOne
cd CodenameOne/Samples
ant run
~~~~

**Comment by ddyer0** [comment]
There's a little too much difference between our dev environments, your ant UI doesn't quite work for me.  Sending an android build from there fails with this:
     [mkdir] Created dir: G:\share\projects\steve\CodenameOne\CodenameOne\build\empty
     [java]     [mkdir] Created dir: G:\share\projects\steve\CodenameOne\CodenameOne\build\generated-sources\ap-source-output
     [java]     [javac] Compiling 598 source files to G:\share\projects\steve\CodenameOne\CodenameOne\build\classes
     [java]     [javac] Fatal Error: Unable to find package java.lang in classpath or bootclasspath

**Comment by shannah** [comment]
You may need to build the CodenameOne project first.
Also make sure your JAVA_HOME points to a valid JDK.

So 

~~~~
git clone https://github.com/codenameone/CodenameOne
git CodenameOne
ant javase
cd Samples
ant run
~~~~

**Comment by ddyer0** [comment]
ok, that works and produces the results you expect - but my usual development environment, and builds from it, are still broken.
