### ISSUE TITLE
[BUG or Java convention?] StringUtil.tokenize wrong behavior

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2902]
Test case:
```
String test = "1,2,3,,,,,,5,6,3"; // 11 tokens
        int count=0;
        for (String token : StringUtil.tokenize(test, ",")) {
            Log.p("Token " + ++count + " -> " + token);
        }
```

Output:
```
[EDT] 0:0:0,75 - Token 1 -> 1
[EDT] 0:0:0,75 - Token 2 -> 2
[EDT] 0:0:0,75 - Token 3 -> 3
[EDT] 0:0:0,75 - Token 4 -> ,
[EDT] 0:0:0,75 - Token 5 -> ,
[EDT] 0:0:0,75 - Token 6 -> ,5
[EDT] 0:0:0,75 - Token 7 -> 6
[EDT] 0:0:0,76 - Token 8 -> 3
```

That's wrong! I expect to have 11 tokens, that are:
token 1 -> "1"
token 2 -> "2"
token 3 -> "3"
token 4 -> "" (empty String)
token 5 -> "" (empty String)
token 6 -> "" (empty String)
token 7 -> "" (empty String)
token 8 -> "" (empty String)
token 9 -> "5"
token 10 -> "6"
token 11 -> "3"

Is it a fixable bug or is it a Java convention?

**Comment by amiga** [comment]
Can't u use a normal string tokenizer and while loop like real java , I
think u can

**Comment by jsfan3** [comment]
Of course I can reinvent the wheel and I can write my own version of this API, but I suppose that if an API is bugged it’s better to report the bug to fix it. In this way, we can contribute to make Codename One better.

Moreover, I’m not sure that it’s a actual bug, that’s why I asked. The javadoc doen’t specify if a token can be empty. There is alal the problem that the change of the behavior of an API can broke something...

**Comment by codenameone** [comment]
This is a bug for sure. The Java convention never returns a blank token, it would have just skipped it.
You can use `StringTokenizer` which has a different implementation. But it sounds to me that you might want `CSVParser` which has a lot of great features for parsing CSV such as recognizing the quote syntax correctly.

**Comment by jsfan3** [comment]
Thank you Shai, you guessed exactly what I need: `CSVParser` works fine to convert a CSV-like `String` to a `Table`, that is my use case.

**Comment by shannah** [comment]
Note:  Also tested on iOS which uses a different (native) implementation of tokenize, and it also passes the unit test.

**Comment by jsfan3** [comment]
Thank you Steve. Now is the default behavior to ignore the empty tokens?

**Comment by jsfan3** [comment]
... or to return them?

**Comment by shannah** [comment]
Ignore them.  Here is the unit test based on your example:
https://github.com/codenameone/CodenameOne/blob/master/tests/core/test/com/codename1/util/StringUtilTests.java#L20

**Comment by jsfan3** [comment]
Ok, thank you for the clarification!
