### ISSUE TITLE
app is sluggish on iOS 13

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2928]
A lot of reports came in lately that our app acts very sluggish on iOS 13. 

Furthermore I noticed that the app acts like this in the iOS simulators as well. In the simulator case it's even happening in prior iOS versions and not only iOS 13.

Any idea what might be the reason here?

**Comment by mattfluency** [comment]
Our CN1-based iOS app is not working on iOS 13 with iPhone 6, 7, Xr. Very sluggish but also some functionality is not working at all. In particular, the signature block is not responding to touch but instead is putting in straight lines randomly.

**Comment by mattfluency** [comment]
We upgraded to iOS 13.1 and that appears to have resolved the iOS 13 issues. Retested on 6, 7, and XR okay.

**Comment by shannah** [comment]
Thanks for reporting this.  We are dealing with a number of issues on iOS 13, and we're knocking them off one by one.

When making reports like this, test cases are always helpful.  It is also helpful to know when you made the build, and what device and OS you are testing on.
