### ISSUE TITLE
Doc errors in Math.round

### ISSUE THREAD

**Issue by Maaartinus** [codenameone/CodenameOne#2933]
There a few mismatches between the doc and the implementation:
https://github.com/codenameone/CodenameOne/blob/master/Ports/CLDC11/src/java/lang/Math.java#L216
- The result is surely not equivalent as `floor` returns `double`.
- L220: The result is `0` rather than `+0.0`. Repeated two more times.
- L224: A typo in "infintiy". Repeated once.

A side question: In my CLDC11.jar, there's `long` instead of `int`. How comes?

**Comment by shannah** [comment]
> The result is surely not equivalent as floor returns double.

Notice the cast to int: `{@code (int) Math.floor(f+0.5)}`

> L220: The result is 0 rather than +0.0. Repeated two more times.

I added a cast now: 720d9b6b

> L224: A typo in "infintiy". Repeated once.

Fixed c07647bc

> A side question: In my CLDC11.jar, there's long instead of int. How comes?

There are two round methods: `public long round(double)` and `public int round(float)`
