### ISSUE TITLE
RFE: Add Image Button for Add Image Dialog in GUI builder and CSS Support

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2934]
The GUI builder dialog should have an entry to add a new image/multi image within the set image dialog body. That way it would be easier to find see https://stackoverflow.com/questions/58468329/where-do-i-store-images-and-how-do-i-get-them-in-codename-one-new-gui

This should also work for CSS seamlessly by detecting CSS mode and placing the image in the right location and within the CSS file.

**Comment by shannah** [comment]
It already does detect CSS mode and will place the image in the CSS file - and regenerate the theme file automatically, if you add the image via the GUI builder.  I just fixed a bug that caused problems if you tried to add an image with a space in the file name, but other than that, it was already there.

I'll look into adding the option to add new images in the set image dialog.
