### ISSUE TITLE
CSS Round border uses screenshot approach for fractions

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2935]
This CSS code works correctly

````css
    border-top-left-radius: 1mm;
    border-top-right-radius: 1mm;
````

It generates the correct round rect border.

Using this:

````css
    border-top-left-radius: 0.7mm;
    border-top-right-radius: 0.7mm;
````
Generates a screenshot process instead of using the round rect border.

**Comment by shannah** [comment]
I can't seem to reproduce.  

~~~~
MyStyle {
	border: 1px solid blue;
	background-color: blue;
    border-top-left-radius: 0.7mm;
    border-top-right-radius: 0.7mm;
}
~~~~

Just uses round rect border.  No screenshots.

I am doing comparisons of the corner radii using `==`, which might be problematic for comparing float values.

**Comment by codenameone** [comment]
I was doing it in the live update mode if that changes anything. Just saw the FX UI popping up while saving. Maybe it was triggered by something else I missed in the code.
