### ISSUE TITLE
404 error trying to import CN1Lib

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2937]
Could you please see this bug report, I suppose that the cause of the error is something that I cannot solve, because there is a 404 error trying to import my VideoOptimizer CN1Lib:

https://github.com/jsfan3/CN1Libs-VideoOptimizer/issues/1

Thank you

**Comment by codenameone** [comment]
This is my bad, I didn't review the PR well: https://github.com/codenameone/CodenameOneLibs/pull/23/files
You should have added the cn1lib file as well to the PR. It's missing

**Comment by jsfan3** [comment]
I'm sorry, I forgot the file :)
I've just submitted a new pull request including the missing CN1Lib

**Comment by jsfan3** [comment]
This issue is now solved
