### ISSUE TITLE
BrowserComponent not displayed on iOS when using a navigation callback 

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2939]
This was working previously. Here is the sample:

        String dummyHtml = "<body><h1>TITLE TEST</h1><a href=\"https://www.codenameone.com/\">link</a></body>";        
        BrowserComponent bc = new BrowserComponent();
        bc.setPage(dummyHtml, "");
        
        bc.addBrowserNavigationCallback(NetUtils.createCallbackDontOpenLinksInComponent());
        
        Form f = new Form(new BorderLayout());
        f.add(Component.CENTER, bc);
        f.show();

NetUtils:

```
public static BrowserNavigationCallback createCallbackDontOpenLinksInComponent() {
        return calledUrl -> {
            
            if("".equals(calledUrl) || calledUrl.startsWith("file")) return true;
            
            //System.out.println("url called: " + calledUrl);
            CN.execute(calledUrl);
            return false;
            
        };
    }
```

**Comment by shannah** [comment]
A browser navigation callback doesn't run in the EDT.  CN.execute(calledUrl) may expect to be called from the EDT> . Try wrapping that in a callSerially()

**Comment by kutoman** [comment]
@shannah the issue still remains. But why should that have an effect anyways? I'm asking beacuse the problem is that the component isn't displayed intitally. The callback doesn't get and doesn't need to be executed in this scenario. I shared the callback code just as an example since I use it in our app. The actual cause seems to be hidden in `addBrowserNavigationCallback`.

**Comment by codenameone** [comment]
We switched to `WKWebView` which probably impacted behavior slightly see https://www.codenameone.com/blog/wkwebview-prs.html

**Comment by shannah** [comment]
I have run the test case and have identified the problem.  When loading pages using `setPage()`, the URL that iOS uses is 'about:blank'.  The navigation callback is preventing this (returning `false`).

I recommend changing your navigation callback to something like:

~~~~
public static BrowserNavigationCallback createCallbackDontOpenLinksInComponent() {
        return calledUrl -> {
            
            if(!calledUrl.startsWith("http")) return true;
            
            System.out.println("url called: " + calledUrl);
            callSerially(()->{
                if (CN.canExecute(calledUrl)) {
                    CN.execute(calledUrl);
                }
            });
            
            return false;
            
        };
    }
~~~~
