### ISSUE TITLE
Rounded border's opacity changes to 255 when theme.res is opened and saved

### ISSUE THREAD

**Issue by dekromant** [codenameone/CodenameOne#2941]
I set a style with border type "Round (circle or square whose corners are completely round)" and set its opacity to 60. After that I saved theme.res, close theme.res designer and run project. It works fine. After that I open and save theme.res, that border's opacity is changed to 255. I use Windows 10, Netbeans, Codename one Designer v. 1.1

**Comment by DurankGts** [comment]
this same issue it occur to me.

**Comment by Nightbringer42** [comment]
Same problem with the Eclipse plugin on Windows 10 and it occured sometimes ago on a Windows 7 too.

**Comment by shannah** [comment]
Fixed https://github.com/codenameone/CodenameOne/commit/866314df673d6f2bbcc250fe00d992bfb8eef928
