### ISSUE TITLE
Adding SpanButton to Swipeable container Issue

### ISSUE THREAD

**Issue by markbolduc74** [codenameone/CodenameOne#2942]
IDE: NetBeans/Eclipse/IDEA NetBeans 11.0
Desktop OS Windows 10 Pro
Simulator Latest
Device PC, IOS, Android

I have 2 SpanButton components in a Swipeable container, however the swipe action is rarley caught.
However if I substitute SpanButton with Button, the operation behaves as expected.

Here is a repeatable test case.

            Form hi = new Form("MpiImagesSwipeableContainer", new BoxLayout(BoxLayout.Y_AXIS));
            Container ctr = new Container(new BoxLayout(BoxLayout.Y_AXIS));
            ctr.setScrollableY(true);
            for (int a = 0; a < 5; a++) {
                Container TestCont = new Container(new com.codename1.ui.table.TableLayout(1, 2), "SchedEditContainerThickBorder");
                TextArea SrvJobText = new TextArea("A-" + (a + 1) + " Service");
                SrvJobText.setHint("Touch To Open Service Jobs Menu");
                SrvJobText.setEditable(true);
                TextArea SrvJobText1 = new TextArea("B-" + (a + 1) + " Service");
                SrvJobText1.setHint("Touch To Open Service Jobs Menu");
                SrvJobText1.setEditable(true);
                buildConstrantsGeneric(TestCont, SrvJobText, 0, 0, 50);
                buildConstrantsGeneric(TestCont, SrvJobText1, 0, 1, 50);
                SrvJobText.setUIID("MpServiceField");
                SpanButton menuButton = new SpanButton("Delete");
                menuButton.setName("Button");
                menuButton.setUIID("A3VacTableTotalHrsCellRed");
                SpanButton editButton = new SpanButton("Edit");
                editButton.setName("Button");
                editButton.setUIID("A3VacTableTotalHrsCell");
                SwipeableContainer MpiImagesSwipeableContainer = new SwipeableContainer(menuButton, editButton, TestCont);
                MpiImagesSwipeableContainer.setUIID("SwipeableContainerRoundedBorder");
                menuButton.addActionListener((evt) -> {
                    MpiImagesSwipeableContainer.close();
                });
                menuButton.addFocusListener(new FocusListener() {
                    @Override
                    public void focusGained(Component cmp) {
                        System.out.println("menuButton: focusGained");
                    }
                    @Override
                    public void focusLost(Component cmp) {
                        System.out.println("menuButton: focusLost");
                        MpiImagesSwipeableContainer.close();
                    }
                });
                editButton.addActionListener((evt) -> {
                    MpiImagesSwipeableContainer.close();
                });
                ctr.add(MpiImagesSwipeableContainer);
                MpiImagesSwipeableContainer.addSwipeOpenListener(e -> {
                    menuButton.requestFocus();
                });
            }
            hi.add(ctr);
            hi.show();

**Comment by ThomasH99** [comment]
I have the same problem. Spend several days trying to debug it since I thought it might be linked to changes in my code. 

In the below code, all cases with SpanLabel or SpanButton behave incorrectly, while the first examples with Button or Label behave correctly: 

`
               Container cxx = new Container(BoxLayout.y());
                cxx.add( new SwipeableContainer(new Button("LL"), new Button("RR"), new Label("with Button")));
                cxx.add( new SwipeableContainer(new Label("LLLL"), new Label("RRRR"), new Label("With all Labels")));
                cxx.add( new SwipeableContainer(new SpanButton("LLLL"), new SpanButton("RRRR"), new Label("With Label above")));
                cxx.add( new SwipeableContainer(new SpanLabel("LLLL"), new SpanLabel("RRRR"), new SpanLabel("With all SpanLabels","Label")));
                cxx.add( new SwipeableContainer(new SpanButton("LLLL"), new SpanButton("RRRR"), new Button("With SpanButtons below","Label")));
                cxx.add( new SwipeableContainer(new SpanButton("LLLL"), new SpanButton("RRRR"), new Button("With SpanButtons below","Label")));
                cxx.add( new SwipeableContainer(new SpanButton("LLLL"), new SpanButton("RRRR"), new SpanButton("With all SpanButtons","Label")));
                hi.getContentPane().add(BorderLayout.CENTER, cxx);
                hi.show();`

As a personal observation: since the asynchronous repaint was introduced (not sure exactly when this done) debugging anything related to graphics update problems has become extremely difficult.

**Comment by shannah** [comment]
Fixed in 0ed47e41
