### ISSUE TITLE
Support Sign-In with Apple

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2947]
We need to support sign in with Apple as it will become mandatory in 2020 for all apps using 3rd party authentication providers: https://appleinsider.com/articles/19/06/03/sign-in-with-apple-mandatory-for-all-apps-with-third-party-sign-in-options

It might be a good idea to pull out the authorization support from the core and implement auth as cn1libs. This would allow developers to customize this aspect more easily and submit PRs without getting into the nuts and bolts of Codename One.

**Comment by shannah** [comment]
The cn1lib is complete.
https://github.com/shannah/cn1-applesignin
