### ISSUE TITLE
Dialog body issue by BrowserComponent 

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2949]
the dialog body of the given sample gets displayed on the CN1 simulator but not on a android device:

            Command close = Command.create("ok", null, (et) -> {});
            
            BrowserComponent bc = new BrowserComponent();
            bc.setPage("<p>Hello World!</p>", "");
            
            Dialog.show("important", bc, close);

**Comment by codenameone** [comment]
That's invalid HTML.

**Comment by codenameone** [comment]
Native peer preferred size is problematic so the dialog won't be sized correctly.

**Comment by kutoman** [comment]
ok I'll set the size manually then
