### ISSUE TITLE
Using SpanButton or SpanLabel in a list breaks the scrolling upwards

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#2950]
Issues created as asked by Shai here: https://stackoverflow.com/questions/58826442/using-spanbutton-or-spanlabel-in-a-list-breaks-the-scrolling-upwards

I see some very weird behavior from SpanButton/SpanLabels. In the below code, if you drag the list upwards (to scroll the list upwards), all the displayed elements will jump down to the bottom of the screen. This doesn't happen with normal Labels (eg. if you disable the line adding the SpanButton).

Dragging down works as you'd expect.
```
//to reproduce: compile the code, drag the screen upwards, and all the text will jump to the bottom of the screen
Form hi2 = new Form();
hi2.setLayout(new BorderLayout()); 
Container cont17 = new Container(BoxLayout.y());
cont17.setScrollableY(true);
for (int i = 0; i < 10; i++) {
    Label l = new Label("Label " + i);
    cont17.add(l);
}
cont17.add(new SpanButton("SpanButton")); //disable this line and the scroll upwards behaves normally
hi2.add(BorderLayout.CENTER,cont17);
hi2.show(); 
```
**NB. I didn't manage to figure out *why* it doesn't work with SpanButton and SpanLabel, so there may be other components causing the same problem.**

**Comment by ThomasH99** [comment]
Hi, This also seems to breaks one of my implemented functions (for "pinch out to insert") so it would be great with any hints on where the issue may be rooted so I could try debugging myself?

**Comment by shannah** [comment]
This is probably the same regression as https://github.com/codenameone/CodenameOne/issues/2957 which was fixed in https://github.com/codenameone/CodenameOne/commit/d53ae818be1c57dfe1c575f1b32be1428164b1d8

**Comment by ThomasH99** [comment]
That would be great. I’ll check asap and let you know

**Comment by ThomasH99** [comment]
Confirm its fixed, thanks!
