### ISSUE TITLE
Font rendering scale changed?

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2955]
I haven't changed any theme parameters with respsect to the shown UUIDs. Did you change the rendering scale? The texts are bigger than they should be.

**earlier versions of CN1:** (density: very high)

![Screenshot_20191118-120436](https://user-images.githubusercontent.com/5825645/69049166-891e5b80-09ff-11ea-81ac-7c11588f32c3.jpg)

**current version of CN1:** (density: very high, same device as before)

![Screenshot_20191117-170754](https://user-images.githubusercontent.com/5825645/69049170-8c194c00-09ff-11ea-9ec4-b5611454bfb3.jpg)

**Comment by shannah** [comment]
No we haven't changed any font scales recently.  Can you provide more details about the theme settings for your UIID?  An isolated test case would be helpful.

**Comment by kutoman** [comment]
sorry for responding so late. There were other issues of higher priority I had to deal with. In addition to the mentioning of my recent email, this issue seems to be fixed as well
