### ISSUE TITLE
'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'*"

### ISSUE THREAD

**Issue by snkachchakaduge** [codenameone/CodenameOne#2956]
Link: https://groups.google.com/d/msg/codenameone-discussions/YnBq2lhUYCc/ETiWxDQUAAAJ

 Specifically, the error was "*Terminating app due to uncaught exception 'NSGenericException', reason:

'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'*"

How do I fix this?? Do I have to manually change each file or can I do this in a quicker way?

**Comment by shannah** [comment]
Where is this happening?   The following test case runs fine on my iPhone 8 with iOS 13, and iPad Air 2 with iOS 12.  And it does use the line of code in question.

~~~~
Form hi = new Form("Hi World", BoxLayout.y());
        TextField text = new TextField("", "Email or Username", 20, TextArea.ANY);
        // field styling
        //text.getAllStyles().setFont(AVENIR_REGULAR_H4_STORY_DESCRIPTION);
        text.getAllStyles().setBgColor(0xff0000);
        text.getAllStyles().setFgColor(0x00ff00);
        // hint styling
        
        text.getHintLabel().getAllStyles().setBgColor(0xcccccc);
        text.getHintLabel().getAllStyles().setFgColor(0x0000ff);
        
        hi.add(text);
        hi.show();
~~~~

(This is also in the Samples.  Named TextFieldHintStylingTest).

**Comment by shannah** [comment]
I couldn't reproduce this, but I've changed the implementation based on the same SO post, to use a non-private API, and it should fix the issue.
