### ISSUE TITLE
Inspector crashes when extending Component

### ISSUE THREAD

**Issue by Maaartinus** [codenameone/CodenameOne#2963]
With `class MyComp extends Component {}`, there's a crash in the inspector because of `currentComponent.getUIID()` being `null` in this line:

https://github.com/codenameone/CodenameOne/blob/6ba63147d065fb6689cf86df30a6a16078a17278/Ports/JavaSE/src/com/codename1/impl/javase/ComponentTreeInspector.java#L138

In addition to this trivial bug report, I'd like to ask if it's OK to use components without UIID or if I should use some default value?

**Comment by shannah** [comment]
Fixed.  Will be in next update.

I don't see any problem with using a null UIID.
