### ISSUE TITLE
Persistent title line above the title area.

### ISSUE THREAD

**Issue by Maaartinus** [codenameone/CodenameOne#2966]
When testing on Android, I somehow managed to add a title line displayed *above* the `titleArea`. It gets added when I show a dialog (actually an `InteractionDialog` on a new form) and it stays there until the app gets terminated. I'm reporting this as a bug as it doesn't happen in the simulator (it may be a feature, but at least the differing behavior is wrong).

I haven't seen this in any other app and don't have a clue what it is. I can investigate myself, just give me a hint.

**Comment by codenameone** [comment]
We'll need a screenshot and ideally a test case. Sounds like the native title which was probably activated by an old theme etc that manipulated command behavior etc.

**Comment by Maaartinus** [comment]
@codenameone Added. Just click the button. It happens on Android, but not in the simulator.

[issue2966.zip](https://github.com/codenameone/CodenameOne/files/4021848/issue2966.zip)

![Screenshot_20200104-122434](https://user-images.githubusercontent.com/2324516/71764876-15bca480-2eee-11ea-9f39-8e2ee5c424bf.jpg)

**Comment by shannah** [comment]
Here is the merged test case from the provided ZIP, for easier reference. Probably missing some imports as I moved the 2 Form subclasses into the test case as inner classes.

~~~~
package bugs.demo;


import static com.codename1.ui.CN.getCurrentForm;

import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MyApplication {
	private Form current;
	private Resources theme;

	public void init(Object context) {
		theme = UIManager.initFirstTheme("/theme");
	}

	public void start() {
		if(current != null){
			current.show();
			return;
		}
		new BugForm1().show();
	}

	public void stop() {
		current = getCurrentForm();
		if(current instanceof Dialog) {
			((Dialog)current).dispose();
			current = getCurrentForm();
		}
	}

	public void destroy() {
	}
	
	public static class BugForm1 extends Form {
		BugForm1() {
			super(BoxLayout.y());

			final Toolbar toolbar = new Toolbar(false);
			setToolbar(toolbar);
			toolbar.setUIID("Toolbar");
			toolbar.addMaterialCommandToSideMenu("Mandanten", FontImage.MATERIAL_3D_ROTATION, e -> new BugForm2().show());

			setTitle("BugForm1");

			final Button button = new Button("switch");
			button.addActionListener(a -> new BugForm2().show());
			add(button);

			revalidate();
		}
	}
	
	public static class BugForm2 extends Form {
		BugForm2() {
			super(BoxLayout.y());

			setTitle("BugForm2");

			final Button button = new Button("switch");
			button.addActionListener(a -> new BugForm1().show());
			add(button);

			revalidate();
		}
	}

}

~~~~

**Comment by shannah** [comment]
I have added a test case to Samples, and tested on an Android device (Galaxy S8, Android 8.0.0), and I can't seem to reproduce it.  It could have been fixed already by another change.  Closing this for now.  If you can modify the sample to reproduce it, then I'll reopen.
