### ISSUE TITLE
Problems registering for push in IOS.

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2967]
check this error when I call Display.getInstance().registerPush()

nothing callback is received in Codenameone api.

this error is showed in xcode 11.3 where I compile the generated source code by your built server

=================================================================
Main Thread Checker: UI API called on a background thread: -[UIViewController view]
PID: 29389, TID: 382049, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   ForceSOS                            0x0000000100e86d4f Java_com_codename1_impl_ios_IOSImplementation_getDisplayWidthImpl + 47
5   ForceSOS                            0x00000001012eb70a com_codename1_impl_ios_IOSNative_getDisplayWidth__ + 58
6   ForceSOS                            0x0000000101305bad com_codename1_impl_ios_IOSNative_getDisplayWidth___R_int + 29
7   ForceSOS                            0x0000000100ea7fb7 com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 215
8   ForceSOS                            0x0000000100eb3a8a virtual_com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 90
9   ForceSOS                            0x0000000100edad19 com_codename1_impl_ios_IOSImplementation_convertToPixels___int_boolean_R_int + 361
10  ForceSOS                            0x0000000100d17b76 virtual_com_codename1_impl_CodenameOneImplementation_convertToPixels___int_boolean_R_int + 102
11  ForceSOS                            0x00000001001a6e9d com_codename1_ui_Display_convertToPixels___float_R_int + 269
12  ForceSOS                            0x000000010039f5d4 com_codename1_ui_plaf_UIManager_resetThemeProps___java_util_Hashtable + 2468
13  ForceSOS                            0x000000010039ebf9 com_codename1_ui_plaf_UIManager___INIT____ + 2297
14  ForceSOS                            0x00000001003b3be9 com_codename1_ui_plaf_UIManager_getInstance___R_com_codename1_ui_plaf_UIManager + 361
15  ForceSOS                            0x000000010018d518 com_codename1_ui_Display_mainEDTLoop__ + 1256
16  ForceSOS                            0x0000000100e34044 com_codename1_ui_RunnableWrapper_run__ + 8516
17  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
18  ForceSOS                            0x0000000100aa883e com_codename1_impl_CodenameOneThread_run__ + 622
19  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
20  ForceSOS                            0x00000001007e2307 java_lang_Thread_runImpl___long + 1223
21  ForceSOS                            0x00000001006a74d0 threadRunner + 80
22  libsystem_pthread.dylib             0x00007fff52466e65 _pthread_start + 148
23  libsystem_pthread.dylib             0x00007fff5246283b thread_start + 15
2019-12-17 10:24:30.736526-0400 ForceSOS[29389:382049] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController view]
PID: 29389, TID: 382049, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   ForceSOS                            0x0000000100e86d4f Java_com_codename1_impl_ios_IOSImplementation_getDisplayWidthImpl + 47
5   ForceSOS                            0x00000001012eb70a com_codename1_impl_ios_IOSNative_getDisplayWidth__ + 58
6   ForceSOS                            0x0000000101305bad com_codename1_impl_ios_IOSNative_getDisplayWidth___R_int + 29
7   ForceSOS                            0x0000000100ea7fb7 com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 215
8   ForceSOS                            0x0000000100eb3a8a virtual_com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 90
9   ForceSOS                            0x0000000100edad19 com_codename1_impl_ios_IOSImplementation_convertToPixels___int_boolean_R_int + 361
10  ForceSOS                            0x0000000100d17b76 virtual_com_codename1_impl_CodenameOneImplementation_convertToPixels___int_boolean_R_int + 102
11  ForceSOS                            0x00000001001a6e9d com_codename1_ui_Display_convertToPixels___float_R_int + 269
12  ForceSOS                            0x000000010039f5d4 com_codename1_ui_plaf_UIManager_resetThemeProps___java_util_Hashtable + 2468
13  ForceSOS                            0x000000010039ebf9 com_codename1_ui_plaf_UIManager___INIT____ + 2297
14  ForceSOS                            0x00000001003b3be9 com_codename1_ui_plaf_UIManager_getInstance___R_com_codename1_ui_plaf_UIManager + 361
15  ForceSOS                            0x000000010018d518 com_codename1_ui_Display_mainEDTLoop__ + 1256
16  ForceSOS                            0x0000000100e34044 com_codename1_ui_RunnableWrapper_run__ + 8516
17  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
18  ForceSOS                            0x0000000100aa883e com_codename1_impl_CodenameOneThread_run__ + 622
19  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
20  ForceSOS                            0x00000001007e2307 java_lang_Thread_runImpl___long + 1223
21  ForceSOS                            0x00000001006a74d0 threadRunner + 80
22  libsystem_pthread.dylib             0x00007fff52466e65 _pthread_start + 148
23  libsystem_pthread.dylib             0x00007fff5246283b thread_start + 15
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 29389, TID: 382049, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   ForceSOS                            0x0000000100e86d79 Java_com_codename1_impl_ios_IOSImplementation_getDisplayWidthImpl + 89
5   ForceSOS                            0x00000001012eb70a com_codename1_impl_ios_IOSNative_getDisplayWidth__ + 58
6   ForceSOS                            0x0000000101305bad com_codename1_impl_ios_IOSNative_getDisplayWidth___R_int + 29
7   ForceSOS                            0x0000000100ea7fb7 com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 215
8   ForceSOS                            0x0000000100eb3a8a virtual_com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 90
9   ForceSOS                            0x0000000100edad19 com_codename1_impl_ios_IOSImplementation_convertToPixels___int_boolean_R_int + 361
10  ForceSOS                            0x0000000100d17b76 virtual_com_codename1_impl_CodenameOneImplementation_convertToPixels___int_boolean_R_int + 102
11  ForceSOS                            0x00000001001a6e9d com_codename1_ui_Display_convertToPixels___float_R_int + 269
12  ForceSOS                            0x000000010039f5d4 com_codename1_ui_plaf_UIManager_resetThemeProps___java_util_Hashtable + 2468
13  ForceSOS                            0x000000010039ebf9 com_codename1_ui_plaf_UIManager___INIT____ + 2297
14  ForceSOS                            0x00000001003b3be9 com_codename1_ui_plaf_UIManager_getInstance___R_com_codename1_ui_plaf_UIManager + 361
15  ForceSOS                            0x000000010018d518 com_codename1_ui_Display_mainEDTLoop__ + 1256
16  ForceSOS                            0x0000000100e34044 com_codename1_ui_RunnableWrapper_run__ + 8516
17  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
18  ForceSOS                            0x0000000100aa883e com_codename1_impl_CodenameOneThread_run__ + 622
19  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
20  ForceSOS                            0x00000001007e2307 java_lang_Thread_runImpl___long + 1223
21  ForceSOS                            0x00000001006a74d0 threadRunner + 80
22  libsystem_pthread.dylib             0x00007fff52466e65 _pthread_start + 148
23  libsystem_pthread.dylib             0x00007fff5246283b thread_start + 15
2019-12-17 10:24:31.991761-0400 ForceSOS[29389:382049] [reports] Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 29389, TID: 382049, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   ForceSOS                            0x0000000100e86d79 Java_com_codename1_impl_ios_IOSImplementation_getDisplayWidthImpl + 89
5   ForceSOS                            0x00000001012eb70a com_codename1_impl_ios_IOSNative_getDisplayWidth__ + 58
6   ForceSOS                            0x0000000101305bad com_codename1_impl_ios_IOSNative_getDisplayWidth___R_int + 29
7   ForceSOS                            0x0000000100ea7fb7 com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 215
8   ForceSOS                            0x0000000100eb3a8a virtual_com_codename1_impl_ios_IOSImplementation_getDisplayWidth___R_int + 90
9   ForceSOS                            0x0000000100edad19 com_codename1_impl_ios_IOSImplementation_convertToPixels___int_boolean_R_int + 361
10  ForceSOS                            0x0000000100d17b76 virtual_com_codename1_impl_CodenameOneImplementation_convertToPixels___int_boolean_R_int + 102
11  ForceSOS                            0x00000001001a6e9d com_codename1_ui_Display_convertToPixels___float_R_int + 269
12  ForceSOS                            0x000000010039f5d4 com_codename1_ui_plaf_UIManager_resetThemeProps___java_util_Hashtable + 2468
13  ForceSOS                            0x000000010039ebf9 com_codename1_ui_plaf_UIManager___INIT____ + 2297
14  ForceSOS                            0x00000001003b3be9 com_codename1_ui_plaf_UIManager_getInstance___R_com_codename1_ui_plaf_UIManager + 361
15  ForceSOS                            0x000000010018d518 com_codename1_ui_Display_mainEDTLoop__ + 1256
16  ForceSOS                            0x0000000100e34044 com_codename1_ui_RunnableWrapper_run__ + 8516
17  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
18  ForceSOS                            0x0000000100aa883e com_codename1_impl_CodenameOneThread_run__ + 622
19  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
20  ForceSOS                            0x00000001007e2307 java_lang_Thread_runImpl___long + 1223
21  ForceSOS                            0x00000001006a74d0 threadRunner + 80
22  libsystem_pthread.dylib             0x00007fff52466e65 _pthread_start + 148
23  libsystem_pthread.dylib             0x00007fff5246283b thread_start + 15
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication isRegisteredForRemoteNotifications]
PID: 29389, TID: 382049, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   ForceSOS                            0x00000001015a355f -[com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCallsImpl isPushNotificationIsEnable] + 63
5   ForceSOS                            0x0000000100374aac com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCallsImplCodenameOne_isPushNotificationIsEnable___R_boolean + 60
6   ForceSOS                            0x00000001011574a7 com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCallsStub_isPushNotificationIsEnable___R_boolean + 215
7   ForceSOS                            0x0000000101802e7d virtual_com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCalls_isPushNotificationIsEnable___R_boolean + 125
8   ForceSOS                            0x0000000100fbeeac com_geotracksolutionsint_multiasistenciaglobal_utils_Utils_isPushNotificationEnable___R_boolean + 1164
9   ForceSOS                            0x0000000100dd4156 com_geotracksolutionsint_multiasistenciaglobal_ForceSOS_checkPushIdOk___boolean_int_java_lang_String_java_lang_String_com_codename1_ui_Form_R_boolean + 438
10  ForceSOS                            0x00000001011d1a4a com_geotracksolutionsint_multiasistenciaglobal_gui_PhoneNumberValidationScreen_show__ + 826
11  ForceSOS                            0x0000000100b16c1a com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_startPhoneNumberValitationScreen__ + 618
12  ForceSOS                            0x0000000100b15a95 com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_checkIfUserHaveService___com_geotracksolutionsint_multiasistenciaglobal_core_StateMachine + 4101
13  ForceSOS                            0x0000000100b171e5 com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_access$300___com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_com_geotracksolutionsint_multiasistenciaglobal_core_StateMachine + 245
14  ForceSOS                            0x0000000101877f9a com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_1_1_run__ + 362
15  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
16  ForceSOS                            0x00000001011939d3 com_codename1_ui_util_UITimer_Internal_run__ + 355
17  ForceSOS                            0x0000000101193a67 virtual_com_codename1_ui_util_UITimer_Internal_run__ + 87
18  ForceSOS                            0x000000010169a2b5 com_codename1_ui_util_UITimer_testEllapse__ + 741
19  ForceSOS                            0x0000000101193817 com_codename1_ui_util_UITimer_Internal_animate___R_boolean + 215
20  ForceSOS                            0x00000001011603cc virtual_com_codename1_ui_animations_Animation_animate___R_boolean + 124
21  ForceSOS                            0x00000001005a5dc2 com_codename1_ui_Form_loopAnimations___java_util_ArrayList_java_util_ArrayList + 546
22  ForceSOS                            0x00000001005a5a69 com_codename1_ui_Form_repaintAnimations__ + 489
23  ForceSOS                            0x00000001005a587a virtual_com_codename1_ui_Form_repaintAnimations__ + 90
24  ForceSOS                            0x000000010018a8fc com_codename1_ui_Display_edtLoopImpl__ + 9068
25  ForceSOS                            0x000000010018f031 com_codename1_ui_Display_mainEDTLoop__ + 8193
26  ForceSOS                            0x0000000100e34044 com_codename1_ui_RunnableWrapper_run__ + 8516
27  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
28  ForceSOS                            0x0000000100aa883e com_codename1_impl_CodenameOneThread_run__ + 622
29  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
30  ForceSOS                            0x00000001007e2307 java_lang_Thread_runImpl___long + 1223
31  ForceSOS                            0x00000001006a74d0 threadRunner + 802019-12-17 10:24:35.510167-0400 ForceSOS[29389:382049] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication isRegisteredForRemoteNotifications]
PID: 29389, TID: 382049, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   ForceSOS                            0x00000001015a355f -[com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCallsImpl isPushNotificationIsEnable] + 63
5   ForceSOS                            0x0000000100374aac com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCallsImplCodenameOne_isPushNotificationIsEnable___R_boolean + 60
6   ForceSOS                            0x00000001011574a7 com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCallsStub_isPushNotificationIsEnable___R_boolean + 215
7   ForceSOS                            0x0000000101802e7d virtual_com_geotracksolutionsint_multiasistenciaglobal_natives_NativeCalls_isPushNotificationIsEnable___R_boolean + 125
8   ForceSOS                            0x0000000100fbeeac com_geotracksolutionsint_multiasistenciaglobal_utils_Utils_isPushNotificationEnable___R_boolean + 1164
9   ForceSOS                            0x0000000100dd4156 com_geotracksolutionsint_multiasistenciaglobal_ForceSOS_checkPushIdOk___boolean_int_java_lang_String_java_lang_String_com_codename1_ui_Form_R_boolean + 438
10  ForceSOS                            0x00000001011d1a4a com_geotracksolutionsint_multiasistenciaglobal_gui_PhoneNumberValidationScreen_show__ + 826
11  ForceSOS                            0x0000000100b16c1a com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_startPhoneNumberValitationScreen__ + 618
12  ForceSOS                            0x0000000100b15a95 com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_checkIfUserHaveService___com_geotracksolutionsint_multiasistenciaglobal_core_StateMachine + 4101
13  ForceSOS                            0x0000000100b171e5 com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_access$300___com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_com_geotracksolutionsint_multiasistenciaglobal_core_StateMachine + 245
14  ForceSOS                            0x0000000101877f9a com_geotracksolutionsint_multiasistenciaglobal_gui_StartScreen_1_1_run__ + 362
15  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
16  ForceSOS                            0x00000001011939d3 com_codename1_ui_util_UITimer_Internal_run__ + 355
17  ForceSOS                            0x0000000101193a67 virtual_com_codename1_ui_util_UITimer_Internal_run__ + 87
18  ForceSOS                            0x000000010169a2b5 com_codename1_ui_util_UITimer_testEllapse__ + 741
19  ForceSOS                            0x0000000101193817 com_codename1_ui_util_UITimer_Internal_animate___R_boolean + 215
20  ForceSOS                            0x00000001011603cc virtual_com_codename1_ui_animations_Animation_animate___R_boolean + 124
21  ForceSOS                            0x00000001005a5dc2 com_codename1_ui_Form_loopAnimations___java_util_ArrayList_java_util_ArrayList + 546
22  ForceSOS                            0x00000001005a5a69 com_codename1_ui_Form_repaintAnimations__ + 489
23  ForceSOS                            0x00000001005a587a virtual_com_codename1_ui_Form_repaintAnimations__ + 90
24  ForceSOS                            0x000000010018a8fc com_codename1_ui_Display_edtLoopImpl__ + 9068
25  ForceSOS                            0x000000010018f031 com_codename1_ui_Display_mainEDTLoop__ + 8193
26  ForceSOS                            0x0000000100e34044 com_codename1_ui_RunnableWrapper_run__ + 8516
27  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
28  ForceSOS                            0x0000000100aa883e com_codename1_impl_CodenameOneThread_run__ + 622
29  ForceSOS                            0x0000000100bc416c virtual_java_lang_Runnable_run__ + 124
30  ForceSOS                            0x00000001007e2307 java_lang_Thread_runImpl___long + 1223
31  ForceSOS                            0x00000001006a74d0 threadRunner + 80
2019-12-17 10:24:36.548502-0400 ForceSOS[29389:382049] isPushNotificationIsEnable()->NO
2019-12-17 10:24:36.720104-0400 ForceSOS[29389:382049] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.720286-0400 ForceSOS[29389:382054] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.721805-0400 ForceSOS[29389:382054] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.727215-0400 ForceSOS[29389:382054] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.727412-0400 ForceSOS[29389:382049] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.730352-0400 ForceSOS[29389:382054] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.731776-0400 ForceSOS[29389:382049] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.736921-0400 ForceSOS[29389:382054] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.737011-0400 ForceSOS[29389:382049] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.738513-0400 ForceSOS[29389:382054] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.738613-0400 ForceSOS[29389:382049] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.739982-0400 ForceSOS[29389:382054] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-12-17 10:24:36.740269-0400 ForceSOS[29389:382049] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}

please tell what is the problem. this Error is occurring after the last friday udate.

**Comment by DurankGts** [comment]
I found debugging your generated source code in xcode that this line is commented

<img width="1241" alt="Screen Shot 2019-12-17 at 10 59 45 AM" src="https://user-images.githubusercontent.com/16245755/71006889-72315e80-20bc-11ea-9742-a7b5cfc0650d.png">


I uncommented and I receive the push notification. why this code is commented?

**Comment by shannah** [comment]
This accidentally commented out in a commit last week.  It has been [fixed](https://github.com/codenameone/CodenameOne/commit/2cd3d93f4d24a05d570b3a527716a1ad0fdab4b2).  We'll be deploying to servers soon.

**Comment by DurankGts** [comment]
ok, could you tell me when this issue it will be available?. This because apple doesn't accept any update in the app store from 23 to 27 of december. I Need to update my app before this dates
