### ISSUE TITLE
Swipe in tabs not working with latest cn1 build (103)

### ISSUE THREAD

**Issue by acionescu** [codenameone/CodenameOne#2973]
Hi, with the latest codename one jar, swipe in tabs is not working anymore. 

Here's the Versions.properties contents:

> #Fri Dec 27 16:24:31 EET 2019
> CodenameOne_SRCzip=103
> CodenameOneJar=103
> CodeNameOneBuildClientJar=101
> CLDC11Jar=18
> JavaSEJar=103

**Comment by shannah** [comment]
Fixed.  https://github.com/codenameone/CodenameOne/commit/69475a0beaad1e93cea1a5e10fb240acf7fd7e30
