### ISSUE TITLE
Enable Dark/Night Mode

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#2979]
Allow to detect this and implement it in themes or elsewhere

**Comment by javieranton-zz** [comment]
I managed to implement this in Android & iOS. Itprobably isn't big enough to be its own library and better to include it as part of CN1. Here is the native interfaces implementation:

### iOS
`-(BOOL)isNightMode{
	BOOL returned = NO;
	if (@available(iOS 13.0, *)) {
	if([UIScreen mainScreen].traitCollection.userInterfaceStyle  == UIUserInterfaceStyleDark){
    	//if (self.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
        	returned = YES;
    	}
	}
	return returned;
}`


### Android
`import android.content.res.Configuration;`
...
`public boolean isNightMode()
	{
		int nightModeFlags =
				context().getResources().getConfiguration().uiMode &
				Configuration.UI_MODE_NIGHT_MASK;
		boolean returned = false;
		switch (nightModeFlags) {
		case Configuration.UI_MODE_NIGHT_YES:
			returned = true;
			break;

		case Configuration.UI_MODE_NIGHT_NO:
			returned = false;
			break;

		case Configuration.UI_MODE_NIGHT_UNDEFINED:
			returned = false;
			break;
		}
		return returned;
	}`

**Comment by javieranton-zz** [comment]
An automatic Night Mode can be achieved with following couple methods. Just need to call setNightMode(form) before each form.show()

`public void setNightMode(Component parent)
	{
		//TODO check if night mode on, if not return
		parent.getAllStyles().setBgColor(getNightColor(parent.getUnselectedStyle().getBgColor()));
		parent.getAllStyles().setFgColor(getNightColor(parent.getUnselectedStyle().getFgColor()));
		if(parent instanceof Container)
			for(Component child : ((Container)parent).getChildrenAsList(true))
			{
				if(child instanceof Container)
					setNightMode((Container)child);
				else
				{
					child.getAllStyles().setBgColor(getNightColor(child.getUnselectedStyle().getBgColor()));
					child.getAllStyles().setFgColor(getNightColor(child.getUnselectedStyle().getFgColor()));
					if(child instanceof Button)
					{
						Image icon = ((Button)child).getIcon();
						if(icon instanceof FontImage)
						{
							((Button)child).setMaterialIcon(((Button)child).getMaterialIcon());
						}
					}
				}
			}
	}
	public int getNightColor(int originalColor)
	{
		//TODO check if night mode on, if not return originalColor
		int tempColor = originalColor;
		int r = tempColor/256/256;
		tempColor=tempColor-r*0x10000;
		int g = tempColor/256;
		tempColor=tempColor-g*0x100;
		int b = tempColor;
		
		if(r==g && g==b)//grayscales
		{
			int newR = r != 0 ? 255 - r : 0;
			int newG = g != 0 ? 255 - g : 0;
			int newB = b != 0 ? 255 - b : 0;
			return newB+(newG*256)+newR*(256*256);
		}
		else//colours
			return originalColor;
	}`

**Comment by codenameone** [comment]
Fixed https://github.com/codenameone/CodenameOne/commit/7b59959d104b8ef451ce1f976bb04767b038f619
