### ISSUE TITLE
"Set bounds to java.awt.Rectangle" in the log

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2984]
I noted that starting from a week or more, in the Simulator log there are sentences like:
`Set bounds to java.awt.Rectangle[x=64,y=257,width=377,height=37]`

Of course it's not an issue, I'm only suspecting that this kind of info is exposed in the log not intentionally. Or is it useful for something?

**Comment by shannah** [comment]
This has now been removed
