### ISSUE TITLE
RFE: Why "shrinkResources true" isn't by default into build.gradle?

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2985]
After reading this documentation:
https://developer.android.com/studio/build/shrink-code.html
I understood that resource shrinking could be convenient, even if I didn't understand how much it could be convenient.

The `build.gradle` generated by the Codename One Android build servers doesn't include `shrinkResources true`.

I suppose that the following code, that is the one generated by your build server:

```
buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.cfg'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
```

could be:
```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.cfg'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
```

Or is there any reason or side effect to avoid that? Or do you think that it's not useful?
Thank you

**Comment by shannah** [comment]
I've added the `android.shrinkResources` build hint `true|false`, with a default value of `false` which can be used.  This will be included in the next server update.  If it appears that this is "safe", then we may change default to `true` at some point in the future.
