### ISSUE TITLE
Dialog autodisposes. Possible malfunctioning of Display.callSerially 

### ISSUE THREAD

**Issue by acionescu** [codenameone/CodenameOne#2987]
Hi,
I had the below kind of logic that worked fine until the last CN1 version.

```
Display.getInstance().callSerially(() -> {
                            ...
                            Dialog.show(...);
                            ....
                        });
...
Display.getInstance().callSerially(() -> {
                            ...
                            some other UI logic
                            ....
                        });
```
These calls are made from a different thread, through a custom eventing system. 
As I said, this worked fine until now. The second callSerially statemend wasn't called until the dialog displayed in the first block was disposed after user action. Now, the dialog autodisposes and the second block is executed.

Contents of the Versions.properties file:

> #
> #Thu Jan 09 14:52:31 EET 2020
> CodenameOne_SRCzip=104
> CodenameOneJar=104
> CodeNameOneBuildClientJar=104
> CLDC11Jar=18
> JavaSEJar=104

Please help. This breaks functionality in an ugly way!

**Comment by shannah** [comment]
You shouldn't be depending on the order in which code inside separate callSerially() calls are being made.  The Dialog.show() call in the first one uses invokeAndBlock internally to block only that dispatch.  Other  call serially calls, including your subsequent ones are not blocked, and can run even before the Dialog.show() call returns.  If you want to make sure that the code runs *after* the Dialog.show() call returns, the code should be included inside the same callSerially().

Alternatively you can use alternate mechanisms (such as status variables) to indicate whether the dialog has been closed yet.
