### ISSUE TITLE
Launching a codenameone app in debug mode fails

### ISSUE THREAD

**Issue by Romadelf** [codenameone/CodenameOne#2994]
Hi,

I initially posted this on [StackOverflow](https://stackoverflow.com/questions/59761649/2-bugs-since-last-cn1-updates-debug-mode-and-rounded-rectangle-border) before realizing should have been here instead. Apologies for that.

On Eclipse, launching the app in debug mode results in the following error (that I wasn't getting last week):

>     ERROR: transport error 202: connect failed: Connection refused
>     ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
>     JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:735]

Initially, I thought that the socket was failing to initialize as the port was being used. That is also what you would mostly find on internet. So I checked the command line used to find out which port the socket was trying to connect to so that I can check if that port was available:

```
C:\Program Files\Java\jdk-13.0.1\bin\javaw.exe -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:54499
 "-javaagent:C:\Users\Roman\eclipse\jee-2019-09\eclipse\configuration\org.eclipse.osgi\1095\0\.cp\lib\javaagent-shaded.jar"
 -Dfile.encoding=UTF-8
 -classpath
 "D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\JavaSE.jar;
D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\bin;
D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\lib\CLDC11.jar;
D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\lib\CodenameOne.jar;
D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\lib\impl\cls;
D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\lib\impl\stubs;
D:\Work\Software_workspaces\Eclipse_IDE\Selisys\FirstOnPersonalPC\native\internal_tmp" 
com.codename1.impl.javase.Simulator be.selisys.rdf.firstonpersonalpc.FirstOnPersonalPC
```

We can see that it is attempting to use port 54499 (in fact, in gets incremented by 1 at each command line call). Now the funny thing is that this port (and the many following ones) is (are) effectively free!

I tried things such as rebooting Eclipse, my computer, check the dt_socket.dll, ... but none of that helped. After hours thought, I noticed the debug mode was working on other applications, but not on CodenameOne ones.

I then moved to another computer:
  
1. Turned off the internet, ran the debugger on a CN1 app ==> Works fine
2. Turned the internet back on, send a built to get the jars updated, ran the debugger again ==> same error as above :(

Since I now know that it is obviously related to CN1 jars last update. Have you got any idea on how to solve that? How much time should we expect for a solution to come up? Any idea of a workaround? Maybe I can use the old jars, if there is a place to find them.

Cheers

**Comment by shannah** [comment]
Fixed.  Will be included in next update tomorrow.
