### ISSUE TITLE
what's the purpose of BrowserComponent.ready ?

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#3010]
Since the respective Javadoc is missing here I'm curious about the case when `ready` is `false`. In that case an ActionListener is instantiated and not passed anywhere:

    public BrowserComponent ready(final SuccessCallback<BrowserComponent> onReady) {
        if (ready) {
            onReady.onSucess(this);
        } else {
            ActionListener l = new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    removeWebEventListener(onStart, this);
                    onReady.onSucess(BrowserComponent.this);
                }
            };
        }
        return this;
    }

**Comment by shannah** [comment]
Added explanation in javadocs..

**Comment by kutoman** [comment]
I've read the javadoc but shouldn't the `ActionListener l` be attached somewhere based on your explanation? Currently the listener is just instantiated and not passed anywhere as I stated initially.

**Comment by shannah** [comment]
Yes. You're right.  I've added it.
