### ISSUE TITLE
RFE: add a section "jQuery/CSS Style Selectors" to the developer guide

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3012]
I searched for `ComponentSelector` in the developer guide (pdf version), but there isn't.

I suggest to add a section to the developer guide that could be a copy of this blog article (that I discovered thanks to this recent comment on SO https://stackoverflow.com/questions/59865786/access-a-component-inside-a-tab-component#comment105910466_59870758):
https://www.codenameone.com/blog/jquery-css-style-selectors-for-cn1.html

I've already read the Javadoc a while ago, but that article is more complete and clear.

I think that the `ComponentSelector` is a great API that can make code simpler in a lot of situations, that's why my suggestion.

**Comment by shannah** [comment]
Done.
https://github.com/codenameone/CodenameOne/wiki/component-selector

**Comment by jsfan3** [comment]
Thank you!
