### ISSUE TITLE
Impossible to modify the Wiki to fix the Developer Guide

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3018]
I tried to fix by myself a page of your developer guide because there is an info partially incorrect, but I cannot do that. When I try to modify the following page, I get a blank page, like if the following charapter of the developer guide doesn't exist:
https://github.com/codenameone/CodenameOne/wiki/File-System,-Storage,-Network-&-Parsing

Could you please check that link? Thank you

The partially incorrect info is the sentence:

> The object in Storage are deleted when an app is uninstalled but are retained between application updates. 

This could be confusing, because some Android devices keep the Storage even after app delete. A more complete sentence could be:

> The objects in Storage are usually deleted when an app is uninstalled but are retained between application updates. The only exception is Android, that on some devices keeps by default objects in Storage after app uninstalling: to force Android to remove them on app uninstalling, use the build hint `android.allowBackup=false`

Indeed, I'm not sure if Android is the only exception: you know that better than me, of course.

**Comment by shannah** [comment]
Thanks.  The link in the wiki sidebar was stale - the page name had changed to just "io".

I have updated the link in the sidebar, and made the requested changes in the doc.

A side tip:  You can clone the CodenameOne wiki like any other github repo, and edit the files locally, then commit them.  This is what I do as it allows much greater flexibility, like adding images.

`git clone https://github.com/codenameone/CodenameOne.wiki.git`

**Comment by jsfan3** [comment]
Ok, thank you for the tip!

**Comment by jsfan3** [comment]
Please note that there are also other obsolete links, like https://github.com/codenameone/CodenameOne/wiki/Basics---Themes,-Styles,-Components-&-Layouts

Maybe it's necessary a global check

**Comment by shannah** [comment]
Thanks.  I've gone through and tested the remaining sidebar links.  Fixed 4 or 5 dead ones.
