### ISSUE TITLE
Problems generating source code to IOS in the build server to compile in xcode

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3022]
Please check why the generated code in your build server isn’t generating the folder Pods and files Podfile.lock. When I try to compile in the xcode the built it fail. I was working perfectly on 7 of February. Could you check the problem please?

**Comment by DurankGts** [comment]
<img width="1200" alt="Screen Shot 2020-02-11 at 10 45 13 AM" src="https://user-images.githubusercontent.com/16245755/74246961-b22b5100-4cbb-11ea-9df0-8408a1790888.png">

**Comment by codenameone** [comment]
Is this the project or workspace file?

**Comment by DurankGts** [comment]
the workspace

**Comment by DurankGts** [comment]
<img width="1200" alt="Screen Shot 2020-02-12 at 9 18 57 AM" src="https://user-images.githubusercontent.com/16245755/74338529-c2edcc80-4d78-11ea-93b2-e3d20cac7a6a.png">


this is the difference. The project ForceSOS don´t have the Pods file and the project MultiasistenciaGlobal it have. I compare the codenameone_settings.properties i both project and they are same.

**Comment by DurankGts** [comment]
Pod folder excuse me

**Comment by DurankGts** [comment]
some one can help me about this issue steve?
