### ISSUE TITLE
Form showing issue on iOS devices with home bars

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#3031]
in our app the user has the possibility to switch to another view when he rotates the device. It's about switching from one form to another. But recently we've noticed that sporadically the switching doesn't happen properly on iOS devices with home bars. The form (doesn't matter on which orientation) doesn't get rendered fully. Either the form doesn't get full screen size or doesn't get rendered at all. I suppose this might be linked to the recent changes you've made concerning safe areas (which we're not making use of). 
I will provide you a sample if necessary in the coming days.

![Bildschirmvideo-aufnehmen-2020-02-19-um-17 02 29](https://user-images.githubusercontent.com/5825645/74854940-4b073f80-5340-11ea-941b-8a997309ab40.gif)

**Comment by jnorth515** [comment]
We are experiencing a similar issue with iOS on 3 separate apps. When switching from portrait to landscape the screen splits. The left half shows the form the right half is black . It only affects recent builds if that helps. We first noticed this on 11/02/20.

**Comment by kutoman** [comment]
@shannah it is fixed now for our case

**Comment by shannah** [comment]
Fixed https://github.com/codenameone/CodenameOne/commit/fbf99392bf46ca68658513264ed96a93e85e3832

**Comment by jnorth515** [comment]
@shannah this is resolved for our case now as well. Many thanks
