### ISSUE TITLE
crash when dragging cursor in text field on iOS devices

### ISSUE THREAD

**Issue by jnorth515** [codenameone/CodenameOne#3032]
I have an issue that only seems to be affecting iOS devices. If I press and hold on a text field to drag and re-position the cursor on a device my app freezes. This only happens if the text is too large to show in the field. As I drag the cursor to show the text that was not visible the crash happens.

Please see the example image when using a text field set as password.
![iOS dragging cursor on textfield](https://user-images.githubusercontent.com/61280167/75343117-a335c880-588f-11ea-9b8d-c79ce17e8775.png)

**Comment by shannah** [comment]
Fixed.  Will be included in update on Friday.

**Comment by jnorth515** [comment]
Many thanks!
