### ISSUE TITLE
textarea "rowStrings" is null

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3041]
This occurred in initial setup of a textarea, no doubt because the initial "paint" occurred
at an inopportune time.   I see two places where rowStrings is set to null.   A definitive fix
would require some careful synchronization, but a stopgap might be to simply make
getLines() defensive against the rare case that getRowStrings returns null

[2020/03/05 13:09:59] log request from lib.FileSelector (78.180.53.140)
data=[Java cpu=5.3% screen=2048x1536 ppi=160 Codename1  3.83 Ios] (EDT 8 threads)error in layoutContainer
error is : java.lang.NullPointerException: null
[EDT] 0:0:0,0 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
    at com_codename1_ui_TextArea.getLines:899
    at com_codename1_ui_TextArea.getActualRows:843
    at com_codename1_ui_plaf_DefaultLookAndFeel.getTextAreaSize:1259
    at com_codename1_ui_plaf_DefaultLookAndFeel.getTextFieldPreferredSize:2031
    at com_codename1_ui_TextField.calcPreferredSize:1552
    at com_codename1_ui_Component.preferredSizeImpl:3000
    at com_codename1_ui_Component.preferredSize:3039
    at com_codename1_ui_Component.getPreferredSize:1383
    at lib_FileSelector.setLocalBounds:1150
    at lib_FileSelector.doNullLayout:1196
    at lib_NullLayout.layoutContainer:98
    at com_codename1_ui_Container.doLayout:2082
    at com_codename1_ui_Container.layoutContainer:1815
    at bridge_Container.layoutContainer:2120
    at com_codename1_ui_Container.doLayout:2087
    at com_codename1_ui_Container.layoutContainer:1815
    at bridge_Container.layoutContainer:2120
    at com_codename1_ui_Container.doLayout:2087
    at com_codename1_ui_Container.layoutContainer:1815
    at bridge_Container.layoutContainer:98
    at com_codename1_ui_Container.paint:1714
    at bridge_Component.paint:368
    at bridge_Container.paint:2710
    at com_codename1_ui_Component.internalPaintImpl:2266
    at com_codename1_ui_Component.paintInternalImpl:2239
    at com_codename1_ui_Component.paintInternal:2214
    at com_codename1_ui_Container.paint:1747
    at bridge_Component.paint:368
    at bridge_Container.paint:554
    at bridge_MasterPanel.paint:2710
    at com_codename1_ui_Component.internalPaintImpl:2266
    at com_codename1_ui_Component.paintInternalImpl:2239
    at com_codename1_ui_Component.paintInternal:2214
    at com_codename1_ui_Component.paintInternal:2182
    at com_codename1_ui_Component.paintComponent:2479
    at com_codename1_ui_Component.paintComponent:2423
    at com_codename1_impl_CodenameOneImplementation.paintDirty:624
    at com_codename1_ui_Display.edtLoopImpl:1225
    at com_codename1_ui_Display.mainEDTLoop:1134
    at com_codename1_ui_RunnableWrapper.run:120
    at com_codename1_impl_CodenameOneThread.run:176
    at java_lang_Thread.runImpl:153

**Comment by codenameone** [comment]
This is an EDT violation

**Comment by ddyer0** [comment]
On a previous iteration of this problem, I wrapped setText and setWidth in "run in edt",
these being the only two places where rowStrings is set to null.  That should have fixed
any EDT violation.    Something else must be going on.

**Comment by codenameone** [comment]
Every get call will create this. Every rendering or query from a thread will do this. It's very thread sensitive!

**Comment by ddyer0** [comment]
there are only 2 methods that set rowStrings to null, and I have both of those covered.
The remaining possibility is that setwidth gets called within edt as a side effect of the
very complex method that creates the row list, but after rowStrings has been initialized.
