### ISSUE TITLE
drag and drop doesn working for ios

### ISSUE THREAD

**Issue by Y-souhail** [codenameone/CodenameOne#3048]
Hello Codenameone support,

I would like to have some help with an issue I'm having in IOS version. The feature Drag and drop is not working anymore, is there any updates or changes I have to make?
Concerning the Android version it's working good.

Thanks in advance for the support.

**Comment by shannah** [comment]
Is this on device only or does it happen in the simulator as well (with iphone skin)?  A test case would be helpful.

**Comment by Y-souhail** [comment]
Hi shannah,

Thank you for your reply and sorry for not providing much details. Yes it does happen on the simulator too and with iPhone skin. 
The behavior is like this, when i press the content I want to drag it stays in its place as if it's a button or icon, I'm not able to move it.

Thanks in advance for the support.

**Comment by shannah** [comment]
And this used to work for you with the iPhone skin?  Please post a test case so I can try to reproduce.  I've already tried building my drag-and-drop test cases and they seem to be working ok.

**Comment by Y-souhail** [comment]
Hello,

Yes, it was working good before. Please find below the code sample I'm using :

if (!isTest) {
            cnt.putClientProperty("isTest", false);            
        } else {
            cnt.putClientProperty("isTest", true);
        }
        cnt.setLeadComponent(imageLbl);
        cnt.setDraggable(true);
        cnt.addPointerDraggedListener((evt) -> {
                if (cnt.getDraggedx() != cnt.getAbsoluteX()) {
                    //do something
                }else 
				if (cnt.getDraggedx() != cnt.getAbsoluteX()) {
                    //do something
                }            
        });
		
		cnt.addDragFinishedListener((evt) -> {

            if (!(Boolean) cnt.getClientProperty("isTest")) {

                if (calculateDistance(cnt, cnt1) < cnt1.getPreferredW()) {
				//NavigateToPage1
                   
                } else if (calculateDistance(cnt, cnt2) < cnt2.getPreferredW()) {
                    //NavigateToPage2
                } else {
                    System.out.println("doNothing");
                }
            } else {

                if (calculateDistance(cnt, cnt3) < cnt3.getPreferredW()) {

                    ////NavigateToPage3                    
                }
            }
        });
		
Hope this can be helpful.

Thank you for the support.

**Comment by shannah** [comment]
Fixed.  Will be included in friday update.

**Comment by Y-souhail** [comment]
Hello, shannah,

addDragFinishedListener doesn't work

Container cnt = new Container();
        Label imageLbl = new Label();
        FontImage.setMaterialIcon(imageLbl, FontImage.MATERIAL_3D_ROTATION, 10);
        cnt.add(imageLbl);
        cnt.add(new Label("Another label in the container"));
        imageLbl.setDraggable(true);
        boolean isTest = true;
        if (!isTest) {
            cnt.putClientProperty("isTest", false);            
        } else {
            cnt.putClientProperty("isTest", true);
        }
        cnt.setLeadComponent(imageLbl);
        cnt.setDraggable(true);
        imageLbl.addPointerDraggedListener((evt) -> {
            System.out.println("in drag");          
        });
	cnt.addDragFinishedListener((evt) -> {

           System.out.println("Drag finished");
        });
        
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(cnt);

Thank you for the support.
