### ISSUE TITLE
longPointerPress() is not invoked 

### ISSUE THREAD

**Issue by Y-souhail** [codenameone/CodenameOne#3049]
Hello, Codenameone support,

I would like to have some help with an issue I'm having. The longPointerPress is not working anymore, is there any updates or changes I have to make?

it was working good before. Please find below the code sample I'm using :

     Container centerCnt = new Container(BoxLayout.y());
        
        if (isTest)
        
             centerCnt = new Container(BoxLayout.y()){
                @Override
                public void longPointerPress(int x, int y) {
                    if (this.getParent().isDropTarget())
                        this.getComponentForm().setGlassPane((g2, rect2) -> {                    
                          g2.drawImage(deleteIcon, (this.getAbsoluteX())-deleteIcon.getWidth()/2- 
                          this.getAllStyles().getMarginLeft(isRtl)+this.getWidth(),(this.getAbsoluteY())- 
                          deleteIcon.getHeight()/2+this.getAllStyles().getMarginTop());
                            currentPressedCnt=this;
                            
                        });

                };
            };

Thanks in advance for the support.

**Comment by shannah** [comment]
You need to make the container focusable to catch longpress  events.

`centerCnt.setFocusable(true)`

**Comment by Y-souhail** [comment]
hi shannah;

 it still not working.
 it was working good in :
/*
#Mon Jul 29 15:26:37 WEST 2019
CodenameOne_SRCzip=81
CodenameOneJar=81
CodeNameOneBuildClientJar=17
CLDC11Jar=18
JavaSEJar=81
*/

Container centerCnt = new Container(BoxLayout.y());
        centerCnt.setFocusable(true);
		
        if (isTest)        
             centerCnt = new Container(BoxLayout.y()){
                @Override
                public void longPointerPress(int x, int y) {
                    if (this.getParent().isDropTarget())
                        this.getComponentForm().setGlassPane((g2, rect2) -> {
                            g2.drawImage(deleteIcon, (this.getAbsoluteX())-deleteIcon.getWidth()/2-this.getAllStyles().getMarginLeft(isRtl)+this.getWidth(),(this.getAbsoluteY())-deleteIcon.getHeight()/2+this.getAllStyles().getMarginTop());
                            currentPressedCnt=this;
                            
                        });

                };
            };
			
	iconBtn.addActionListener((evt)->{
                // 
                          
        });
        
        iconBtn.setUIID("Container");
        centerCnt.setLeadComponent(iconBtn);

Thanks in advance for the support.

**Comment by shannah** [comment]
Notice you’re still not making it focusable.  You create a new container after you set the old one focusable.

**Comment by Y-souhail** [comment]
Container centerCnt = new Container(BoxLayout.y());
        centerCnt.setFocusable(true);        
        System.out.println("old centerCnt if Focusable "+centerCnt.isFocusable());
        
        if (isTest)        
             centerCnt = new Container(BoxLayout.y()){
                @Override
                public void longPointerPress(int x, int y) {
                    if (this.getParent().isDropTarget())
                        this.getComponentForm().setGlassPane((g2, rect2) -> {
                            g2.drawImage(deleteIcon, (this.getAbsoluteX())-deleteIcon.getWidth()/2-this.getAllStyles().getMarginLeft(isRtl)+this.getWidth(),(this.getAbsoluteY())-deleteIcon.getHeight()/2+this.getAllStyles().getMarginTop());
                            currentPressedCnt=this;
                            
                        });

                };
            };
        centerCnt.setFocusable(true);        
        System.out.println("New centerCnt if Focusable "+centerCnt.isFocusable());


output

old centerCnt if Focusable true
New centerCnt if Focusable true

and still not working.
I tried to override setFocusable

if (dropTarget)
            
             centerCnt = new Container(BoxLayout.y()){

            @Override
            public void setFocusable(boolean focusable) {
                super.setFocusable(true); 
            }
                @Override
                public void longPointerPress(int x, int y) {
                    if (this.getParent().isDropTarget())
                        this.getComponentForm().setGlassPane((g2, rect2) -> {
                            g2.drawImage(deleteIcon, (this.getAbsoluteX())-deleteIcon.getWidth()/2-this.getAllStyles().getMarginLeft(isRtl)+this.getWidth(),(this.getAbsoluteY())-deleteIcon.getHeight()/2+this.getAllStyles().getMarginTop());
                            currentPressedCnt=this;
                            
                        });

                };
            };

### **same result.**
