### ISSUE TITLE
Editing TextField in CENTER position makes a Picker unresponsive

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3051]
A pretty weird case. It happened in my app in a much more complex layout, but I've boiled it down to the following test case. In the following test case, editing a TextField in CENTER position somehow prevents clicking on a Picker (or other buttons). The comments explain how to reproduce. 

```
//editing a textField in CENTER position makes Picker unresponsive
//to reproduce: click on TextField2, then Picker. Picker does not activate (unless clicked on the left-most edge)
//Click on TextField1, Picker is activated no matter where it is clicked
Form hi110 = new Form("Welcome", new BorderLayout());
TextField textField1 = new TextField("TextField1", "", 20,  TextArea.ANY);

TextField textField2 = new TextField("TextField2", "", 20,  TextArea.ANY);
hi110.add(BorderLayout.NORTH, textField1);
hi110.add(BorderLayout.CENTER, textField2);
hi110.add(BorderLayout.SOUTH, new Picker());
hi110.show();
```

**Comment by ThomasH99** [comment]
Forgot to add this: issue first detected on iOS device, reproduced on Simulator, using CN1 sources as of 21st of Feb 2020.

**Comment by shannah** [comment]
I can't seem to reproduce in simulator.  I've added a test case based on your example.

**Comment by ThomasH99** [comment]
I just compiled against today's CN1 sources and I still see the problem. 

To be more precise on how to reproduce: click in TextField2 at the Center of the Form, then click on the *right-hand* side of the picker (eg it shows "3/24/20" so click on "...4/20") at the bottom of the screen -> nothing happens. I noticed that clicking on the left-hand side of the picker (e.g. "3/24...") brings it up. 

When you click first in TextField1 at the top of the screen, you can activate the picker no matter where you click on it. 

Weird issue...

**Comment by ThomasH99** [comment]
Did you get a chance to check if you can reproduce this error? It is blocking my UI since it makes the pickers appear not working.

**Comment by shannah** [comment]
I still cannot reproduce this issue.

**Comment by ThomasH99** [comment]
Sorry for not getting back on this sooner, but I've since downloaded a later version of CN1 and the problem seems to be gone now, so maybe it was a side effect of something else you have fixed, so I close the issue. In any case, thanks for looking into it.
