### ISSUE TITLE
iOS iPad: No Buttons in heavyweight Picker since migration to xcode 11.3

### ISSUE THREAD

**Issue by KlausHeywinkel** [codenameone/CodenameOne#3055]
Since the migration to xcode 11.3 the Picker-Dialog on a iPad (iOS 13.3.1 - real Device - no simulator) don't have buttons any more (see Screenshot). The buttons are there on a iPhone 11 (iOS 13.3.1) with the same build. 
![XHWqU](https://user-images.githubusercontent.com/29796657/77299867-6ffb2380-6ced-11ea-8901-5dc79ee4e92c.png)

**Comment by shannah** [comment]
Cannot reproduce on iPad, iOS 12.  Updating to 13.3.1 to try to verify bug.

**Comment by shannah** [comment]
I've reproduced on iPad, iOS 13.3.1
