### ISSUE TITLE
add Drop Listener is not invoked

### ISSUE THREAD

**Issue by Y-souhail** [codenameone/CodenameOne#3059]
Hello, Codenameone support,

I would like to have some help with an issue I'm having. The addDropListener is not working anymore, is there any updates or changes I have to make?

it was working good before. Please find below the code sample I'm using :

~~~~
if (centerCnt.getClientProperty("dropListener")==null)
        {
            ActionListener dropListener = new ActionListener() {
            @Override
                public void actionPerformed(ActionEvent evt) {
                                        
                    System.out.println("drop Listener");
                }                
            };
            
            centerCnt.addDropListener(dropListener);
            
            centerCnt.putClientProperty("dropListener", dropListener);
            
        }
~~~~

Thanks in advance for the support.

**Comment by shannah** [comment]
I would need a more complete test case.  I have just posted a [sample](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/DropListenerSample/DropListenerSample.java) that demonstrates `addDropListener()` on a container, and it works correctly.

**Comment by Y-souhail** [comment]
Hello,

Yes, it was working good before. Please find below the code sample I'm using :

Container cnt = new Container();
        Label imageLbl = new Label();
        FontImage.setMaterialIcon(imageLbl, FontImage.MATERIAL_3D_ROTATION, 10);
        cnt.add(imageLbl);
        cnt.add(new Label("Another label in the container"));
        imageLbl.setDraggable(true);
        boolean isTest = true;
        if (!isTest) {
            cnt.putClientProperty("isTest", false);            
        } else {
            cnt.putClientProperty("isTest", true);
        }
        cnt.setLeadComponent(imageLbl);
        cnt.setDraggable(true);
        setDropListener(cnt);                
                
        Container dropTarget = new Container(new FlowLayout())  {
            @Override
            public void paint(Graphics g) {
                super.paint(g);
                g.setColor(0x0);
                g.setFont(Font.createSystemFont(Font.FACE_SYSTEM, Font.STYLE_PLAIN, Font.SIZE_SMALL));
                g.drawString("Drop Target", 0, 0);
                
            }
            
        };
        dropTarget.getStyle().setBorder(Border.createLineBorder(1, 0x00ff00));
        dropTarget.setDropTarget(true);
        
        dropTarget.add(new Label("DropTarget"));
        
        
        
        Form hi = new Form("Hi World", new GridLayout(1, 2));
        hi.setScrollable(false);
        hi.addAll(cnt,dropTarget);
        hi.show();


     public static void setDropListener (Container centerCnt)
    {

        if (centerCnt.getClientProperty("dropListener")==null)
        {
            ActionListener dropListener = new ActionListener() {
            @Override
                public void actionPerformed(ActionEvent evt) {
                                        
                    System.out.println("drop Listener");
                }

                
            };
            
            centerCnt.addDropListener(dropListener);
            
            centerCnt.putClientProperty("dropListener", dropListener);
            
        }

    }


Hope this can be helpful.

Thank you for the support.

**Comment by shannah** [comment]
You need to set the drop listener on the lead component.

**Comment by shannah** [comment]
I added an additional [sample](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/LeadComponentDropListenerSample/LeadComponentDropListenerSample.java) to demonstrate dropListener with a lead component.
