### ISSUE TITLE
cn1-codescan uses UIWebView 

### ISSUE THREAD

**Issue by fuadnassar90** [codenameone/CodenameOne#3061]
our app uses BrowserComponent to display html content and when uploaded it to testflight we received this msg:

App Store Connect
Dear Developer,We identified one or more issues with a recent delivery for your app, "Yalla Gym" 1.3 (1.3). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.After you’ve corrected the issues, you can upload a new binary to App Store Connect.Best regards,The App Store Team

**Comment by javieranton-zz** [comment]
They are rejecting apps with BrowserComponent? I just submitted an update for mine today and didn't get this message from them. I read on Hacker News that they were rejecting Progressive Apps, but does that also include any BrowserComponent instances?

**Comment by javieranton-zz** [comment]
Just out of curiosity, are you including some specific JS like Electron in your html?

**Comment by codenameone** [comment]
We switched off UIWebView last year: https://www.codenameone.com/blog/wkwebview-prs.html
If you're still seeing this then you have a cn1lib or a build hint that's causing it.

**Comment by fuadnassar90** [comment]
we use cn1-codescan.cn1lib to scan qr code in app, and when using this library a warning message appears.
after search in source code of this library, we can see the ZBarHelpController.h class has define   UIWebView *webView; 
please fix this isuessas soon as possible; becouse we can't submit our app starting tomorow

**Comment by shannah** [comment]
Found this fork of ZBar that has already made this switch. https://github.com/anupambiswal/ZBar

Working on building it...

**Comment by shannah** [comment]
Fixed and rebuilt the lib.  Updated lib is at https://github.com/codenameone/cn1-codescan/blob/master/cn1-codescan.cn1lib and will be available in codenameone settings shortly.

**Comment by fuadnassar90** [comment]
The project fails when trying to sent ios version after update to this lib, on the other hand, the QRScanner has the same problem of using UIWebView component.

**Comment by fuadnassar90** [comment]
[error (3).txt](https://github.com/codenameone/CodenameOne/files/4417586/error.3.txt)

**Comment by shannah** [comment]
Sorry.  Forgot to include armv7 in the static lib.  I've rebuilt it and pushed it.  same deal as before for updating.

**Comment by fuadnassar90** [comment]
no problem, thank you soo much for your efforts
what about QRScanner? 
[https://github.com/littlemonkeyltd/QRScanner](url)

**Comment by fuadnassar90** [comment]
and additional thing when I execute this command on my project folder **grep -r "UIWebView " .**
I got this msg:
`./dist/Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,`

**my pod file is:**
`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'main' do
    pod  'Firebase/Messaging'
    pod  'GoogleMaps'
    pod  'GoogleSignIn', '<5.0.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
    end
  end
end`

**Comment by fuadnassar90** [comment]
I still got same message from apple, if we send our app to App Store review we will get a pretty rejected for same reason.

**Comment by shannah** [comment]
I've opened a new issue #3070 for the GoogleSignIn update.
