### ISSUE TITLE
HTML developer guide is missing a section that is present in the PDF version

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3064]
Please see my answer: https://stackoverflow.com/a/60902419/1277576

The section "5.6 CSS Variables" of the PDF developer guide is currently missing in the HTML version of the developer guide, maybe there are not synchronized.

**Comment by shannah** [comment]
Fixed this in the build script.  Will be updated the next time the site is updated.

**Comment by ThomasH99** [comment]
Great, thanks both of you!
