### ISSUE TITLE
Is `ios.xcode_version=10.1` working?

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3067]
There is a strange fact, described in this bug report: https://github.com/jsfan3/CN1Libs-VideoOptimizer/issues/3

Do you have an idea why the same cn1lib, with the same demo code, stopped to work on iOS even using `ios.xcode_version=10.1`?

Thank you

**Comment by codenameone** [comment]
It works, see this 3rd party confirmation: https://github.com/codenameone/CodenameOne/issues/3055
