### ISSUE TITLE
Swipable Containers not fully closing or opening properly.

### ISSUE THREAD

**Issue by jnorth515** [codenameone/CodenameOne#3069]
I have found recently that the SwipableContainer is not snapping to the closed or open position. I find the same behavior when using the KitchenSink Demo which leads me to believe it is not something in my code. This is similar to [this](https://github.com/codenameone/CodenameOne/issues/2308) previously closed issue. The first image below shows the KitchenSink Contacts Demo where the SC is stopped, one half open and one half closed. The second image shows the SC snap into position after pressing anywhere on the screen there is no SC.

![Screenshot 03_04_2020 14_53_24 (2)](https://user-images.githubusercontent.com/61280167/78368833-28fa1180-75bc-11ea-860f-7bbf0c06e4ba.png)

![Screenshot 03_04_2020 14_57_54 (2)](https://user-images.githubusercontent.com/61280167/78368849-2e575c00-75bc-11ea-9961-61bf8b44802a.png)

**Comment by shannah** [comment]
Fixed in cf921d69

**Comment by jnorth515** [comment]
Many thanks!
