### ISSUE TITLE
Notarization support for Mac Desktop builds

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3074]
With Catalina, Apple now requires apps to be notarized.  This doesn't necessarily need to be built into the build server as notarization can be done manually by the developer after the fact.  However, we at least need to ensure that the bundled JDK doesn't cause any problems with the notarization process.  It is possible we'll need to use a newer JDK 11 for the bundled jdk (probably Zulu) in order for notarization to work.

**Comment by arturhefczyc** [comment]
I agree, notarization does not need to be built-into the build server. It can be easily done by the developer in semi-automated way from a command line. Maybe some kind of integration between the build process on the server and then running notarization script on the developer machine when the build is completed would be useful.

The main problem now is that Mac desktop applications cannot be successfully notarized at all. I tried to notarize our app and got errors from the service. The service complains about all executables that they **do not have hardened runtime enabled**.

Other than that Java runtime included **uses SDK older than the 10.9 SDK**.

I am attaching log from the notarization process with all the details. Please let me know if you need anything else to resolve the issue.

Below is code of my script which I use to send app for notarization from command line. I hope this is useful as well.

``` bash
#!/bin/bash

WAIT_TIME=60

echo "Loading script settings"
source $(dirname $0)/notarize.env

echo "Signing package ${PACKAGE} with ${SIGN_IDENTITY}"
codesign --force --sign "${SIGN_IDENTITY}" "${PACKAGE}"

echo "Uploading package ${PACKAGE}, ${BUNDLE_ID} to notarization service for ${AC_USERNAME}, ${ASC_PROVIDER}"
xcrun altool --notarize-app \
             --primary-bundle-id "${BUNDLE_ID}" \
             --username "${AC_USERNAME}" \
             --password "@keychain:AC_PASSWORD" \
             --asc-provider "${ASC_PROVIDER}" \
             --file "${PACKAGE}" > "${LAST_NOTARIZATION_FILE}"

REQ_UUID=$(grep RequestUUID "${LAST_NOTARIZATION_FILE}" | sed -e "s/RequestUUID = //g")
echo "Upload completed REQ_UUID=${REQ_UUID}, waiting ${WAIT_TIME} seconds for notarization to complete"

echo "in progress" > "${NOTARIZATION_STATUS}"
while grep "in progress" "${NOTARIZATION_STATUS}" ; do
  sleep "${WAIT_TIME}"
  echo "Checking status..."
  xcrun altool --notarization-history 0 \
               --username "${AC_USERNAME}" \
               --password "@keychain:AC_PASSWORD" \
               --asc-provider "${ASC_PROVIDER}" > "${NOTARIZATION_STATUS}"
done

echo "Notarization completed, getting result details"
xcrun altool --notarization-info  "${REQ_UUID}" -u "${AC_USERNAME}" -p "@keychain:AC_PASSWORD" --asc-provider "${ASC_PROVIDER}"
```

[scratch.log](https://github.com/codenameone/CodenameOne/files/5204521/scratch.log)

**Comment by shannah** [comment]
I believe that if we switch to use latest AdoptOpenJDK11 for app bundles on the build server, it should resolve this issue:
https://github.com/AdoptOpenJDK/openjdk-build/issues/1130

**Comment by arturhefczyc** [comment]
When do you expect this to happen? Please let me know when the switch is done so I can test our app notarization.

**Comment by shannah** [comment]
I'll look into it tomorrow.  If there are no hiccups, then we should have it ready for the update next Friday

**Comment by arturhefczyc** [comment]
Great, thank you

**Comment by shannah** [comment]
Looks like we just need to update the ZuluFX11 version on the build server to the latest to fix this issue.  https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=macos&architecture=x86-64-bit&package=jdk

This will also require the use of the `mac.desktop-vm=zuluFx11` build hint.

**Comment by arturhefczyc** [comment]
Do you have ETA for this? Next Friday is still the estimation?

**Comment by arturhefczyc** [comment]
And what about `java.version` build hint? Does it still have to be `8` or should it be increased to `11`?

**Comment by shannah** [comment]
`java.version` should still be `8`.  This is just a change to the JRE that is bundled inside the .app.

**Comment by shai-almog** [comment]
Notice you will need to use the build hint: `mac.desktop-vm=zuluFx11` for this to work.

**Comment by shai-almog** [comment]
It will be available next week
