### ISSUE TITLE
theme.res not found in new project

### ISSUE THREAD

**Issue by issoupanda** [codenameone/CodenameOne#3078]
I tried today to create a new codename one project but the file theme.res and test packages are not found, plus when i try to double click on an old theme.res file it doesnt open.

**Comment by codenameone** [comment]
Duplicate of #3077

**Comment by rombosia** [comment]
After this workaround, the css compiler's generated theme.res doesn't honour overrides.
**Example 1: TextField works, TextField.selected doesn't**
TextField{
	border-bottom: 5px solid #8798A7; 
}
TextField.selected{
	border-bottom: 5px solid #16D173;

}

**Example 2: Button works, LinkButton doesn't**
Button{
	color: white;
	background-color: #16D173;
	border-radius: 1mm;
}
LinkButton{
	cn1-derive: Button;
	border: none;
	padding-left: 1mm;
	color: #16D173;
	background: transparent;
}

![2020_04_15_02_18_35_](https://user-images.githubusercontent.com/63478662/79283107-8301ad80-7ebf-11ea-930d-9eb1a9c60afe.png)
**
