### ISSUE TITLE
iOS Google SignIn has stopped working on older devices

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3080]
Just found out today when testing on my iPad 4 (iOS 10). Works fine on my iPhone 6s (iOS 13). Has the SDK been updated? This may have broken it for older versions. Anyway, time for iOS users to fork out more $ and buy new hardware I suppose, although this is unfortunate as there still are a sizeable amount of iOS 10 users

Just need to know if this is something an updated SDK may have introduced, to be safe

Thx

**Comment by javieranton-zz** [comment]
Just seen this. I think it probably is related to [this](https://github.com/codenameone/CodenameOne/commit/922f94672e71008fbbcb476e4e51c62d963123b2). I was toying with debugging teh CodenameOne src today to see if I could change (to debug) things, but couldn't figure out how to change the stuff in Ports. is this even possible?

**Comment by shannah** [comment]
Minimum version for Google SignIn is 8.0 - so 10.0 should be fine.  Do you get an error message of any kind?

**Comment by javieranton-zz** [comment]
So what happens is that the app closes immediately after returning from the Google SignIn dialog. No errors messages are shown and nothing is traced (I am tracing with NativeLogs plugin and nothing goes there either)

**Comment by shannah** [comment]
I'm working on getting a test device running with something older than iOS 13.  The main device that I used to use seems to have broken, and I've unfortunately updated all of my other devices to iOS 13.

**Comment by javieranton-zz** [comment]
Great thx

**Comment by shannah** [comment]
Got an iOS9 device running and was able to reproduce the issue.  Seems older devices redirect to Safari for login, whereas iOS 13 uses an internal webview and never leaves the app - so they follow different code paths.  Older devices needed to handle the URL redirect back to the app, and the new version of Google Sign In changed the method signature that was used for that so it needed to be updated.

This is fixed now in git, and will be included in Friday's update.

**Comment by javieranton-zz** [comment]
Nice one! If you could look at the other issue I opened regarding ios push registration failures that would be great. At the moment I can't release any app updates until that one is fixed

Thanks for the effort, much appreciated
