### ISSUE TITLE
iOS registeredForPush has stopped working

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3081]
I don't know why `registeredForPush(String token)` isn't being called after calling `Display.getInstance.registerPush()` but I have a suspicion it might be related to [400c356](https://github.com/codenameone/CodenameOne/commit/400c356562ed4fe757f6aa3e48811e5d5900a363)

This was working in the beginning of March and has stopped woking since then

Tested on many many devices

**Comment by javieranton-zz** [comment]
Sorry for being impatient but at the moment push isn't registering on iOS at all (I see 20 daily users or so who try this and all fail). Perhaps the old way of parsing the deviceToken wasn't perfect but it worked most of the time. Can we revert these changes until womething better can be found? I can't help with this since I don't own a mac to debug the source but even then push can't be debugged as I understand

**Comment by shannah** [comment]
Tested working on iOS 9 (iPhone 4S) and iOS 13 (iPhone 8).    What version/device are you seeing failures on?

**Comment by javieranton-zz** [comment]
I am seeing failures on every device (around 20 different iOS devices per day). Basically calling `Display.getInstance.registerPush()` never triggers a callback to `registeredForPush(String token)`.
Thgis should still work even on a Basic subscription, right? I am 100% sure that the call to `Display.getInstance.registerPush()` is made (I log that)

**Comment by shannah** [comment]
I just tested on iOS 10.3.3 (iPhone 5) and it worked there too.

> This should still work even on a Basic subscription, right? 

Push requires a pro account.

**Comment by javieranton-zz** [comment]
I see, I didn't realise that it must have been working during my Pro trial, and then it must have stopped working right after I switched to Basic. My apologies, I thought that the client side functionality wasn't excluded for non-pros, but now I see that it is

Perhaps one day I can upgrade my account, for now the price is too high for my humble means

Thanks for your support with this
