### ISSUE TITLE
AdmobFullscreen crashes iOS apps on startup

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#3083]
Just install AdmobFullscreen.cn1lib, no need to import the lib. The app will crash on iOS right at the start.

I downloaded the sources, opened the workspace file and found this error in Xcode:

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by shannah** [comment]
I'm stuck on this one because I can't figure out how to agree to admob's updated terms and conditiions.

![image](https://user-images.githubusercontent.com/2677562/81078188-bfaf3c00-8ea2-11ea-9a42-62ce2b49700a.png)

If someone has a valid "non-stuck" account or just app ID, I can try to proceed.

**Comment by shannah** [comment]
Thanks for the App ID.  It appears that you are now required to add the admob app ID to your info.plist.  This can be accomplished with the `ios.plistInject` build hint.  I've updated the [README](https://github.com/shannah/admobfullscreen-codenameone/blob/013564537bdf8342a2b63be1a111efd30c838663/README.md#ios-instructions) with these instructions.
