### ISSUE TITLE
Crash in css when using border-top-right-radius (and its variations) in theme.css

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3084]
Since yesterday I started getting the below stack trace when using  border-top-right-radius (and the variations like border-bottom-right-radius) in the theme.css file. 

When I comment out the statements the crash doesn't happen. 

I don't think the change is linked to changes in my theme.css file (I tried reverting my recent edits after it started happening). It may be due to updating the cn1libs or cn1 plugin. 

It also seems that sometimes I can leave a single statement (e.g. "border-top-right-radius: 1mm;" and it will pass, but not systematically. 

````
CSS> Changed detected in /Users/thomas/NetBeansProjects/myApp/css/theme.css.  Recompiling
CSS> Updating merge file /Users/thomas/NetBeansProjects/myApp/css/theme.css.merged
CSS> Acquiring lock on CSS checksums file /Users/thomas/NetBeansProjects/myApp/.cn1_css_checksums...
CSS> Lock obtained
CSS> Releasing lock
CSS> An error occurred while updating resources for UIID ToggleButtonFirst.  Processing property border
CSS> Compile of /Users/thomas/NetBeansProjects/myApp/css/theme.css failed
CSS> java.lang.NullPointerException
CSS> 	at com.codename1.designer.css.CSSTheme.str(CSSTheme.java:1461)
CSS> 	at com.codename1.designer.css.CSSTheme.access$1200(CSSTheme.java:93)
CSS> 	at com.codename1.designer.css.CSSTheme$Element.createCSSBorder(CSSTheme.java:4733)
CSS> 	at com.codename1.designer.css.CSSTheme$Element.getThemeBorder(CSSTheme.java:5014)
CSS> 	at com.codename1.designer.css.CSSTheme.updateResources(CSSTheme.java:1703)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:535)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$100(CN1CSSCLI.java:63)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:321)
CSS> 	at java.lang.Thread.run(Thread.java:748)

````

**Comment by shannah** [comment]
This is fixed, but won't be available until next Friday's update.  If you want to work with the fix immediately, you can replace the designer_1.jar in your $HOME/.codenameone directory, with the one [here](https://drive.google.com/file/d/1UnSeUUiBDHPdG_ZYKmIzwj10RfhoBTpD/view?usp=sharing)

**Comment by ThomasH99** [comment]
Super, thanks. Also for providing the download link

**Comment by ThomasH99** [comment]
Just a quick follow-up question: how/when does the designer_1.jar usually get updated locally? It seems I didn't get it automatically.

**Comment by codenameone** [comment]
It comes down with Update Project which happens automatically when you send a build. Notice that this was released today so you'll only see it later today.

**Comment by ThomasH99** [comment]
Thanks, I thought I needed to do something manually, but I could only find the menu to update the cn1libs
