### ISSUE TITLE
SimpleDateFormat wrong on Android

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#3085]
I guess this is a regression. It works fine on emulator and iOS, but on Android, it fails. So:

`SimpleDateFormat formatoMeta = new SimpleDateFormat("EE, d MMM");
formatoMeta.format(new Date());`

This returns "Fri, 17 de"
instead of "Fri, 17 Apr"

**Comment by shannah** [comment]
@carlosverdier What is the output of 

~~~~
L10NManager l10n = L10NManager.getInstance().formatDateLongStyle(new Date());
~~~~

On Android?

**Comment by carlosverdier** [comment]
20 de abril de 2020
