### ISSUE TITLE
[BUG] Capture.capturePhoto() stopped working on iOS

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3089]
Currently I'm not able to take photo on iOS. Please try the following test: the photo will not be shown. No error or exception is reported.

Test case (it works correctly on Simulator and on Android):

```
Form hi = new Form("Hi World", BoxLayout.y());
        Button button = new Button("Take a photo");
        Label label = new Label();
        hi.addAll(button, label);
        hi.show();

        button.addActionListener(l -> {
            String tempPath = Capture.capturePhoto();
            if (tempPath != null && FileSystemStorage.getInstance().exists(tempPath)) {
                try {
                    InputStream in = FileSystemStorage.getInstance().openInputStream(tempPath);
                    Image img = EncodedImage.create(in, in.available());
                    label.setIcon(img);
                    hi.revalidate();
                } catch (IOException ex) {
                    Log.e(ex);
                }
            }
        });
```

**Comment by jsfan3** [comment]
Same issue using `CN.openGallery(actionEvt, CN.GALLERY_IMAGE);`

**Comment by shannah** [comment]
The problem is this line:

~~~~
EncodedImage.create(in, in.available());
~~~~

in.available() isn't guaranteed to show an accurate value, and in fact it should just be treated as a boolean.  in.available() > 0 means that there is something available.  in.available() == 0 means there is nothing available.

Change it to

~~~~
EncodedImage.create(in);
~~~~

And it works.

**Comment by jsfan3** [comment]
Thank you Steve, you're right, your fix works.
However I need a clarification. Replacing `EncodedImage.create(in, in.available());` with `EncodedImage.create(in);` causes the following warning:

```
Warning: loading large images using EncodedImage.create(InputStream) might lead to memory issues, try using EncodedImage.create(InputStream, int)
```

Every capture photo causes this warning. How can I pass correctly the requested int value?

**Comment by shannah** [comment]
You can use the file size, as returned from the FileSystemStorage API.

**Comment by jsfan3** [comment]
Ok, thanks
