### ISSUE TITLE
padding in CSS incorrectly calculated for mm

### ISSUE THREAD

**Issue by arturhefczyc** [codenameone/CodenameOne#3091]
Hi,
I am trying to adjust text padding for a simple component - Label in CSS. More specifically, the text is aligned left but should not stick to the edge of the component but should be slightly moved away from the edge. I tried to move if away 2mm but it does not have any effect. Then I tried to use different units. Setting padding left to 15pt works.
I thought that mm units are simply not supported but then I tried 100mm and the text was moved slightly, about 2cm on my screen. It turns out the mm units for ladding-left might be incorrectly calculated.
Here is an example code:
``` css
ExampleLabel {
    cn1-derive: 'Label';
    text-align: left;
    color: white;
    padding-left: 100mm;
}
```
and example Kotlin code.
FormController code:
``` kotlin
import com.codename1.charts.util.ColorUtil
import com.codename1.rad.controllers.Controller
import com.codename1.rad.controllers.FormController
import com.codename1.ui.CN
import com.codename1.ui.Container
import com.codename1.ui.Form
import com.codename1.ui.Label
import com.codename1.ui.layouts.BorderLayout

class TestController(parent: Controller) : FormController(parent) {
    private val mainForm: Form = Form("Example", BorderLayout())
    private val mainPanel: Container = Container(BorderLayout())

    init {
        val label = Label("Example Label")
        label.uiid = "ExampleLabel"
        label.allStyles.bgTransparency = 192.toByte()
        // Put an orange color here to better see text position relative to component edge
        label.allStyles.bgColor = ColorUtil.argb(192, 231, 98, 0)
        mainPanel.add(CN.TOP, label)
        mainForm.add(CN.CENTER, mainPanel)
        setView(mainForm)
    }
}
``` 
Example ApplicationController code:
``` kotlin
import com.codename1.rad.controllers.ApplicationController
import com.codename1.rad.controllers.ControllerEvent

@Suppress("unused")
open class ExampleApp: ApplicationController() {

    private var mainController: TestController? = null

    override fun actionPerformed(evt: ControllerEvent) {
        if (evt is StartEvent) {
            evt.consume()
            if (mainController == null) mainController = TestController(this)
            mainController!!.view.show()
        }
    }

}
```

**Comment by shannah** [comment]
I'm having trouble replicating this.  I have adapted your example to Java (the relevant bits) as a sample ([java](https://github.com/codenameone/CodenameOne/blob/746f16ba330ae338c409bb98cb53c06eb67b0271/Samples/samples/LeftPaddingCSSTest3091/LeftPaddingCSSTest3091.java), [css](https://github.com/codenameone/CodenameOne/blob/746f16ba330ae338c409bb98cb53c06eb67b0271/Samples/samples/LeftPaddingCSSTest3091/css/theme.css)

Result:

![image](https://user-images.githubusercontent.com/2677562/81070508-2c710900-8e98-11ea-854e-d65aef416815.png)

You can try running the sample yourself.  It is named "LeftPaddingCSSTest3091".

If you can modify this sample to reproduce the issue, that would help narrow it down.

**Comment by arturhefczyc** [comment]
Hi, thank you for looking into this.
After updating the designed jar file provided in issue #3092 the padding now seems to be working correctly.
