### ISSUE TITLE
NullpointerException on pointerReleased

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#3113]
For a couple of days our users have been reporting Nullpointer errors having the exact same trace. Since we've only updated the iOS version , the reports are solely based on iOS devices. The android update happened weeks before but is based on the same implementation but having an older CN1 version. We just had to postpone the iOS update due to some circumstances (not code based). Therefore I think it has to do with some changes made on the CN1 side. Our iOS update is based on a build from 8th May 2020.

this is the error:
```
java.lang.NullPointerException
   at com_codename1_ui_Form.pointerReleased:3835
   at com_codename1_ui_Component.pointerReleased:4729
   at com_codename1_ui_Display.handleEvent:2324
   at com_codename1_ui_Display.edtLoopImpl:1216
   at com_codename1_ui_Display.mainEDTLoop:1134
   at com_codename1_ui_RunnableWrapper.run:120
   at com_codename1_impl_CodenameOneThread.run:176
   at java_lang_Thread.runImpl:153
```

**Comment by shannah** [comment]
Please try a new build, as there was an iOS bug applied fix last week (Thursday), that may be related to this.

**Comment by kutoman** [comment]
@shannah unfortunately the issue remains even with the bug fix you've mentioned. The bad side is, I don't know how to reproduce this. But it gets reported quite often.

**Comment by ThomasH99** [comment]
I have had the same problem, mentioned here: https://stackoverflow.com/questions/62080164/crash-on-device-but-no-executable-code-where-it-occurs-in-form-java. I will update my CN1 sources before next iOS build to see if it helps

**Comment by shannah** [comment]
In order to debug these issues further, you would need to include sources in the build, then build and debug the project in Xcode.  Then it will show you exactly where the crash occurs.

**Comment by shannah** [comment]
Likely the same as #3201 .  Fixed.
