### ISSUE TITLE
Maven libraries are not recognized

### ISSUE THREAD

**Issue by binunalex** [codenameone/CodenameOne#3114]
Dear Friends,
I am trying to link libraries from Maven to the Codename One project. Namely, I add the entry
_<dependency>
 	<groupId>javax.mail</groupId>
 	<artifactId>mail</artifactId>
 	<version>1.4.7</version>
</dependency>_

to the **POM.xml** file. **No compilation errors are seen in the Eclipse editor.** 

But the Codename One build produces errors:

_Buildfile: C:\Users\dolev\eclipse-workspace\MyApp\build.xml
[javac] C:\Users\dolev\eclipse-workspace\MyApp\src\com\mycompany\myapp\ContextManager.java:5: error: package **com.google.api.services.gmail does not exist**
    [javac] import com.google.api.services.gmail.GmailScopes;_

Does it mean that the **javacc** compiler does not recognize Maven library paths ?

Thanks,
Alex Binun

**Comment by codenameone** [comment]
https://help.codenameone.com/en-us/article/can-i-use-any-jar-1uav2ka/
