### ISSUE TITLE
UTF8 string encoding fails

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3117]
For at least the "illegal ascii" range of values, between 128 and 255,
new String(byte[],x,y,"UTF-8") fails. 

It works correctly in the simulator and in the rest of the universe.
It gives an incorrect result on Android
It throws a runtime exception on IOS

Lots of real things out there (for example, apache web server) routinely 
produce these values.

''''java

package com.boardspace.dtest;

import java.util.Random;

// 
// demonstrates death by stretch image
// 
//
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.layouts.BorderLayout;

public class Dtest {

private Form current;
@SuppressWarnings("unused")
private Resources theme;

public void init(Object context) {
    theme = UIManager.initFirstTheme("/theme");
    // Pro only feature, uncomment if you have a pro subscription
    // Log.bindCrashProtection(true);
}

public void start() {
    if(current != null){
        current.show();
    }
    Form hi = new Form("Hi >>0 World");
     current = hi;
    hi.setLayout(new BorderLayout());
    hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {
        @Override
        public void paint(Graphics gc) {
         	int w = getWidth();
        	int h = getHeight();
        	gc.setColor(0);
        	gc.fillRect(0, 0, w,h);
        	gc.setColor(0xffffff);
        	byte b[] = new byte[]{(byte)0xe9};
        	String m = "";
        	try { m = new String(b,0,1);
        	}
        	catch(Throwable err)
        	{
        		m = err.toString();
        	}
        	String msg = ""+(int)(b[0]&0xff)+" = "+m+" = "+(int)(m.charAt(0)&0xff);
         	gc.drawString(msg,100,100);
        }
        
    });
    hi.show();
	Runnable rr = new Runnable (){ 
		public void run() {
			System.out.println("running");
		while(true) 
		{ 
		  hi.repaint();
		  try {
			  Thread.sleep(10); 
			  }
		  
		  catch (InterruptedException e) {};
		}}};
	new Thread(rr).start();
}
public void stop() {
    current = Display.getInstance().getCurrent();
}

public void destroy() {
}
}
''''

**Comment by codenameone** [comment]
If this fails on Android we're not touching it. What you're doing here is bad. You're treating a String as if it's a byte array. We don't support that usage although it works sometimes supporting it causes issues like this and a lot of other unexpected issues. Use Base64 or similar encoding when transferring binary data via strings.

**Comment by ddyer0** [comment]
this isn't data I generate, its is a html directory listing generated by apache.
I have some code that handles it correctly, if you want to reconsider.
