### ISSUE TITLE
Push Cheatsheet in the developer guide?

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3118]
Do you remember the Push Cheatsheet?
https://www.codenameone.com/files/push-cheatsheet.pdf

I suggest to add a link to download it at the beginning of the Push section of the developer guide:
https://www.codenameone.com/manual/push.html

**Comment by shannah** [comment]
I've added a tip in the manual on the wiki.  https://github.com/codenameone/CodenameOne/wiki/Push-Notifications

It will be include in the manual in the next website update.
