### ISSUE TITLE
Different CSS style for iOS and Android

### ISSUE THREAD

**Issue by arturhefczyc** [codenameone/CodenameOne#3122]
Hi,

I work on an app which will run on desktop and tablets and mobile phones both iOS and Android. All styling is done through CSS and it works well, except one thing.

Some GUI elements show too big font on Android devices (tablets and phones) but they look good on iOS  and desktop. Is there any way to prepare CSS styling for certain elements dedicated specifically for Android devices?

**Comment by codenameone** [comment]
Can you include the specific CSS syntax of the fonts?

**Comment by shannah** [comment]
I have some partial work in implementation of media queries that is almost complete.  I'm working on putting some finishing touches on this and should have it ready soon.

**Comment by shannah** [comment]
I have committed support for media queries.  You have two different options for solving the problem at hand.  See the following sections for some details:

- https://shannah.github.io/cn1-recipes/#_platform_specific_styling
- and https://shannah.github.io/cn1-recipes/#_platform_specific_font_scaling

This will be part of tomorrow's update.

**Comment by arturhefczyc** [comment]
Thank you for looking into this and adding more ways to customize styles.
