### ISSUE TITLE
Error in stacktrace line numbers when running on iOS device

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3128]
In [another issue](https://github.com/codenameone/CodenameOne/issues/3113), and the discussion on [SO](https://stackoverflow.com/questions/62080164/crash-on-device-but-no-executable-code-where-it-occurs-in-form-java), there is a nullPointer in a code line where the error shouldn't be possible. 
 
While executing on my iPhone Xr, I now just got another stacktrace (below, including CN1 version id) which points to `Container` [line 904](https://github.com/codenameone/CodenameOne/blob/7dd4e7d08b3442d90959477ee52a5ae8c4361b29/CodenameOne/src/com/codename1/ui/Container.java#L904) but there is absolutely no executable code there.

So, it seems there is some issue with the stacktrace references when running on the device. Would be great if you can find that since it makes debugging these issues impossible.

````
[EDT] 0:0:0,2 - Codename One revisions: 7dd4e7d08b3442d90959477ee52a5ae8c4361b29
...
[EDT] 0:1:31,302 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
   at com_codename1_ui_Container_3.updateState:904
   at com_codename1_ui_animations_ComponentAnimation.updateAnimationState:100
   at com_codename1_ui_AnimationManager.updateAnimations:72
   at com_codename1_ui_Form.repaintAnimations:1883
   at com_codename1_ui_Display.edtLoopImpl:1233
   at com_codename1_ui_Display.mainEDTLoop:1137
   at com_codename1_ui_RunnableWrapper.run:120
   at com_codename1_impl_CodenameOneThread.run:176
   at java_lang_Thread.runImpl:153

**Comment by shannah** [comment]
This was likely a n EXC_BAD_ACCESS, which gets wrapped as an NPE to prevent the app from crashing, as would normally happen with such an error.

Unfortunately, for this we would need to debug the app in Xcode. (Include sources in the build, open in Xcode, and run on device).  Then it will show where the crash occurred.

**Comment by ThomasH99** [comment]
OK, I guess there is no way to simply get the right line numbers out even in this situation? 

The error *does* makes the app crash, so the wrapping doesn't prevent it in this case. 

Debugging in Xcode is beyond my abilities (I use CN1 to avoid having to learn the iOS and Android environments :-)). Let me know if there is some easy way I could gather useful information for you on the device the next time it happens. 

NB. I have a vague suspicion that it may somehow be linked to either SwipeableContainer or TextField.startEditingAsync() and the interaction with the animation, but that is probably not enough for you to go on. I'll get back if I manage to nail it down more precisely later.

**Comment by codenameone** [comment]
@shannah made a fix today that might impact this. Can you test again and see if this was resolved?

**Comment by shannah** [comment]
This was most likely the same issue as #3201 which is now fixed.
