### ISSUE TITLE
Preferences.get("DeviceId__$", (long)-1); issue

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3143]
I already have an unique identifier of my app installations obtained by my server, however I created a new API to generate unpredicable unique UIIDs according to its canonical text representation (https://en.m.wikipedia.org/wiki/Universally_unique_identifier). My code works and I’m thinking to send a PR to add something like .getUIID() to the Codename One Util class. The issue is that to generate enough strong random numbers (as base for my algorithm), I need at least two random seeds (since Codename One has Random but not SecureRandom): one is the current timestamp, the other one is an unique number assigned to the current installation. For the latter one and for my use, I can use the one generated by my server. But to make an API usable by everyone, I guess that it’s necessary to use something like:
Preferences.get("DeviceId__$", (long)-1);

The issue is that the Preference “DeviceId__$” is stored only if there is an active Internet connection during the first app run, otherwise it is not stored. Is it something fixable? What do you think? Thank you

**Comment by jsfan3** [comment]
I mean that when the Internet connection become available, the Preference “DeviceId__$” is not retrived.

**Comment by codenameone** [comment]
We won't do that. This work predated GDPR which makes these sort of things problematic even for harmless usage like this. So we won't add to the existing behavior.

**Comment by jsfan3** [comment]
Ok, I've developed a mixed approach, which uses the value of `Preferences.get("DeviceId__$", (long)-1)` if available, otherwise it can still generate unique UUIDs. I have now submitted the PR https://github.com/codenameone/CodenameOne/pull/3144
