### ISSUE TITLE
Display.playBuiltinSound(String soundIdentifier) not working on iOS device (nor in Simulator on Mac)

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3145]
I've tried running all the sounds on iPhone Xr (code below), but not are producing any sound. They also don't produce sound in the Simulator. 

When debugging on the Simulator (Mac), the CodenameOneImplementation.playUserSound(String soundIdentifier) returns null for all sound types. 

Seems like a bug unless there is some built hint or configuration needed.

````
Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_ALARM);
            Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_BUTTON_PRESS);
            Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_CONFIRMATION);
            Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_ERROR);
            Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_INFO);
            Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_WARNING);

**Comment by codenameone** [comment]
See `isBuiltinSoundAvailable`

**Comment by ThomasH99** [comment]
Thanks Shai, I wasn't aware of this one. Would be helpful to have it mentioned it in the JavaDoc of the playBuiltinSound method. 

Is it documented somewhere for which platforms CN1 supports builtin sounds? I can't find it mentioned in the developer guide, not by googling,  and it's not feasible to check it by executing isBuiltinSoundAvailable on all platforms.

**Comment by ThomasH99** [comment]
Sorry, it took some time to get around to this again. I've added the below code to my app. On iPhone it shows "SOUND_TYPE_ALARM false" so normal that no sound is played as your comment indicated. 

However, on both Simulator and Android, it shows 'true' but there is no sound played, so it seems to be a bug on these two platforms. (I can't reopen this issue). 

```
hi.add(new Button(Command.create("SOUND_TYPE_ALARM " + Display.getInstance().isBuiltinSoundAvailable(Display.SOUND_TYPE_ALARM), null, 
e -> Display.getInstance().playBuiltinSound(Display.SOUND_TYPE_ALARM))));
```

**Comment by shai-almog** [comment]
On JavaSE we invoke the AWT beep which should work. Not sure why you didn't hear it. However in Android that's a bug it should have returned false (fixed for next update). I deprecated this API as it isn't supported on modern platforms.
