### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3147]
I've seen this one for a while. Copying native logs stacktrace here for resolution. Maybe we could have a null check protection for now

Exception%3A java.lang.NullPointerException - Attempt to invoke virtual method _android.view.ViewGroup%24LayoutParams android.view.View.getLayoutParams()_ on a null object reference
06-24 19%3A51%3A54.129 23055 23085 W System.err%3A java.lang.NullPointerException%3A Attempt to invoke virtual method _android.view.ViewGroup%24LayoutParams android.view.View.getLayoutParams()_ on a null object reference
06-24 19%3A51%3A54.135 23055 23085 W System.err%3A 	at com.codename1.impl.android.a.a(AndroidAsyncView.java335)
06-24 19%3A51%3A54.135 23055 23085 W System.err%3A 	at com.codename1.impl.android.f.a(AndroidImplementation.java3929)
06-24 19%3A51%3A54.135 23055 23085 W System.err%3A 	at com.codename1.w.s.k(Display.java1151)
06-24 19%3A51%3A54.135 23055 23085 W System.err%3A 	at com.codename1.w.aq.run(RunnableWrapper.java120)
06-24 19%3A51%3A54.135 23055 23085 W System.err%3A 	at com.codename1.impl.b%241.run(CodenameOneThread.java60)
06-24 19%3A51%3A54.135 23055 23085 W System.err%3A 	at java.lang.Thread.run(Thread.java764)

**Comment by codenameone** [comment]
Just using a null check will hide a bug that might be worse. This exception shouldn't happen.
Are you changing the native layout in any way? Is there any way to reproduce this?

**Comment by javieranton-zz** [comment]
I will keep digging into this... for now I don't know how to reproduce. I just know that it happens to some users very rarely

**Comment by javieranton-zz** [comment]
If I look at the preceding logs I get the feeling that this happens when the user is typing stuff with the keyboard
This immediately precedes the error for the previous 10 seconds

`21770 W IInputConnectionWrapper%3A requestCursorAnchorInfo on inactive InputConnection
07-06 16%3A48%3A30.029 21770 21788 I InPlaceEditView.ResultReceiver%3A resultCode %3D RESULT_HIDDEN
07-06 16%3A48%3A30.054 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A MSG_RESIZED%3A frame%3D(0%2C0%2C1080%2C2280) ci%3D(0%2C112%2C0%2C144) vi%3D(0%2C112%2C0%2C144) or%3D1
07-06 16%3A48%3A30.078 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme key 1
07-06 16%3A48%3A30.258 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme key 0
07-06 16%3A48%3A30.336 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme key 1
07-06 16%3A48%3A30.337 21770 21830 I System.out%3A showKeyboard false
07-06 16%3A48%3A34.620 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 0
07-06 16%3A48%3A34.676 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 1
07-06 16%3A48%3A36.395 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 0
07-06 16%3A48%3A36.441 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 1
07-06 16%3A48%3A37.910 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 0
07-06 16%3A48%3A37.997 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 1
07-06 16%3A48%3A38.002 21770 21830 I System.out%3A showKeyboard false
07-06 16%3A48%3A38.006 21770 21830 I System.out%3A showKeyboard false
07-06 16%3A48%3A38.687 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 0
07-06 16%3A48%3A38.750 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 1
07-06 16%3A48%3A38.774 21770 21832 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 16%3A48%3A38.774 21770 21832 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 16%3A48%3A39.308 21770 21832 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 16%3A48%3A39.308 21770 21832 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 16%3A48%3A39.598 21770 21830 I System.out%3A showKeyboard false
07-06 16%3A48%3A41.241 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 0
07-06 16%3A48%3A41.293 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A ViewPostIme pointer 1
07-06 16%3A48%3A41.328 21770 21770 D ConnectivityManager%3A requestNetwork%3B CallingUid %3A 10210%2C CallingPid %3A 21770
07-06 16%3A48%3A41.333 21770 21770 D ConnectivityManager%3A requestNetwork%3B CallingUid %3A 10210%2C CallingPid %3A 21770
07-06 16%3A48%3A41.530 21770 21770 D Dialog  %3A mIsSamsungBasicInteraction %3D false
07-06 16%3A48%3A41.530 21770 21770 D Dialog  %3A mIsSamsungBasicInteraction %3D false%2C isMetaDataInActivity %3D false
07-06 16%3A48%3A41.532 21770 21770 I MultiWindowDecorSupport%3A updateCaptionType >> DecorView%40614143c[]%2C isFloating%3A true%2C isApplication%3A true%2C hasWindowDecorCaption%3A false%2C hasWindowControllerCallback%3A false
07-06 16%3A48%3A41.532 21770 21770 D MultiWindowDecorSupport%3A setCaptionType %3D 0%2C DecorView %3D DecorView%40614143c[]
07-06 16%3A48%3A41.537 21770 21770 D ScrollView%3A initGoToTop
07-06 16%3A48%3A41.539 21770 21770 D ScrollView%3A initGoToTop
07-06 16%3A48%3A41.551 21770 21770 D ViewRootImpl%40227387d[GroupChartStub]%3A setView %3D com.android.internal.policy.DecorView%40614143c TM%3Dtrue MM%3Dfalse
07-06 16%3A48%3A41.562 21770 21770 D ViewRootImpl%40227387d[GroupChartStub]%3A Relayout returned%3A old%3D(0%2C112%2C1080%2C2136) new%3D(27%2C950%2C1053%2C1298) req%3D(1026%2C348)0 dur%3D8 res%3D0x7 s%3D{true 502433579008} ch%3Dtrue
07-06 16%3A48%3A41.562 21770 21800 D OpenGLRenderer%3A createReliableSurface %3A 0x74fb167840(0x74fb600000)
07-06 16%3A48%3A41.564 21770 21800 I mali_winsys%3A new_window_surface() [1218x540] return%3A 0x3000
07-06 16%3A48%3A41.566 21770 21770 E DecorView%3A mWindow.mActivityCurrentConfig is null
07-06 16%3A48%3A41.567 21770 21800 D OpenGLRenderer%3A makeCurrent EglSurface %3A 0x75661aea80 -> 0x74fb5fdd00
07-06 16%3A48%3A41.576 21770 21770 D ViewRootImpl%40227387d[GroupChartStub]%3A MSG_WINDOW_FOCUS_CHANGED 1 1
07-06 16%3A48%3A41.578 21770 21770 D ViewRootImpl%40227387d[GroupChartStub]%3A MSG_RESIZED%3A frame%3D(27%2C950%2C1053%2C1298) ci%3D(0%2C0%2C0%2C0) vi%3D(0%2C0%2C0%2C0) or%3D1
07-06 16%3A48%3A41.589 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A MSG_WINDOW_FOCUS_CHANGED 0 1
07-06 16%3A48%3A41.589 21770 21770 D InputMethodManager%3A prepareNavigationBarInfo() DecorView%40537abcb[GroupChartStub]
07-06 16%3A48%3A41.589 21770 21770 D InputMethodManager%3A getNavigationBarColor() -855310
07-06 16%3A48%3A41.658 21770 21800 D OpenGLRenderer%3A makeCurrent EglSurface %3A 0x74fb5fdd00 -> 0x0
07-06 16%3A48%3A41.658 21770 21800 D OpenGLRenderer%3A destroyEglSurface %3A 0x74fb5fdd00
07-06 16%3A48%3A41.658 21770 21800 I mali_egl%3A eglDestroySurface() in
07-06 16%3A48%3A41.661 21770 21800 I mali_winsys%3A delete_surface() [1218x540] return
07-06 16%3A48%3A41.661 21770 21800 I mali_egl%3A eglDestroySurface() out
07-06 16%3A48%3A41.661 21770 21800 W libEGL  %3A EGLNativeWindowType 0x74fb167850 disconnect failed
07-06 16%3A48%3A41.662 21770 21800 D OpenGLRenderer%3A ~ReliableSurface %3A 0x74fb167840
07-06 16%3A48%3A41.662 21770 21770 D ViewRootImpl%40227387d[GroupChartStub]%3A dispatchDetachedFromWindow
07-06 16%3A48%3A41.668 21770 21770 D InputTransport%3A Input channel destroyed%3A _8343c43_%2C fd%3D173
07-06 16%3A48%3A41.673 21770 21770 D ViewRootImpl%40da35fd9[GroupChartStub]%3A MSG_WINDOW_FOCUS_CHANGED 1 1
07-06 16%3A48%3A41.674 21770 21770 D InputMethodManager%3A prepareNavigationBarInfo() DecorView%40537abcb[GroupChartStub]
07-06 16%3A48%3A41.674 21770 21770 D InputMethodManager%3A getNavigationBarColor() -855310
07-06 16%3A48%3A41.675 21770 21770 E ViewRootImpl%3A sendUserActionEvent() mView returned.
07-06 16%3A48%3A41.741 21770 21836 I System.out%3A {\"command\"%3A\"Loaded\"}
07-06 16%3A48%3A41.755 21770 21830 D Codename One%3A native focus gain
07-06 16%3A48%3A41.756 21770 21830 I System.out%3A showKeyboard false
07-06 16%3A48%3A41.767 21770 21800 D OpenGLRenderer%3A makeCurrent EglSurface %3A 0x0 -> 0x75661aea80
07-06 16%3A48%3A41.806 21770 21770 D InputMethodManager%3A prepareNavigationBarInfo() DecorView%40537abcb[GroupChartStub]
07-06 16%3A48%3A41.806 21770 21770 D InputMethodManager%3A getNavigationBarColor() -855310
07-06 16%3A48%3A41.806 21770 21770 V InputMethodManager%3A Starting input%3A tba%3Dcom.groups.network ic%3Dnull mNaviBarColor -855310 mIsGetNaviBarColorSuccess true %2C NavVisible %3A true %2C NavTrans %3A false
07-06 16%3A48%3A41.806 21770 21770 D InputMethodManager%3A startInputInner - Id %3A 0
07-06 16%3A48%3A41.806 21770 21770 I InputMethodManager%3A startInputInner - mService.startInputOrWindowGainedFocus
07-06 16%3A48%3A41.808 21770 21770 D InputTransport%3A Input channel destroyed%3A _ClientS_%2C fd%3D97`

**Comment by javieranton-zz** [comment]
And these are the logs for another user

_07-06 07%3A13%3A09.491  7504  7548 I System.out%3A showKeyboard false
07-06 07%3A13%3A09.492  7504  7539 D OpenGLRenderer%3A destroyEglSurface %3A 0x7e76eeb600
07-06 07%3A13%3A09.493  7504  7548 D Codename One%3A native focus gain
07-06 07%3A13%3A09.494  7504  7548 I System.out%3A showKeyboard false
07-06 07%3A13%3A09.495  7504  7548 I System.out%3A showKeyboard false
07-06 07%3A13%3A09.496  7504  7539 D OpenGLRenderer%3A ~ReliableSurface %3A 0x7e76db6a80
07-06 07%3A13%3A09.497  7504  7504 D ViewRootImpl%404d4ee71[GroupChartStub]%3A dispatchDetachedFromWindow
07-06 07%3A13%3A09.501  7504  7504 D InputTransport%3A Input channel destroyed%3A _666a031_%2C fd%3D173
07-06 07%3A13%3A09.503  7504  7504 E ViewRootImpl%3A sendUserActionEvent() mView returned.
07-06 07%3A13%3A09.503  7504  7504 D ViewRootImpl%40528aa33[GroupChartStub]%3A MSG_WINDOW_FOCUS_CHANGED 1 1
07-06 07%3A13%3A09.503  7504  7504 D InputMethodManager%3A prepareNavigationBarInfo() DecorView%40aa76fd5[GroupChartStub]
07-06 07%3A13%3A09.503  7504  7504 D InputMethodManager%3A getNavigationBarColor() -16777216
07-06 07%3A13%3A09.537  7504  7504 D InputMethodManager%3A prepareNavigationBarInfo() DecorView%40aa76fd5[GroupChartStub]
07-06 07%3A13%3A09.537  7504  7504 D InputMethodManager%3A getNavigationBarColor() -16777216
07-06 07%3A13%3A09.537  7504  7504 V InputMethodManager%3A Starting input%3A tba%3Dcom.groups.network ic%3Dnull mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true %2C NavVisible %3A true %2C NavTrans %3A false
07-06 07%3A13%3A09.537  7504  7504 D InputMethodManager%3A startInputInner - Id %3A 0
07-06 07%3A13%3A09.537  7504  7504 I InputMethodManager%3A startInputInner - mService.startInputOrWindowGainedFocus
07-06 07%3A13%3A09.538  7504  7504 D InputTransport%3A Input channel destroyed%3A _ClientS_%2C fd%3D83
07-06 07%3A13%3A16.271  7504  7504 D ViewRootImpl%40528aa33[GroupChartStub]%3A ViewPostIme pointer 0
07-06 07%3A13%3A16.319  7504  7504 D ViewRootImpl%40528aa33[GroupChartStub]%3A ViewPostIme pointer 1
07-06 07%3A13%3A16.347  7504  7504 D InputMethodManager%3A HSIFW - flag %3A 0
07-06 07%3A13%3A18.483  7504  7504 D InputMethodManager%3A HSIFW - flag %3A 0
07-06 07%3A13%3A20.689  7504  7504 D ViewRootImpl%40528aa33[GroupChartStub]%3A ViewPostIme pointer 0
07-06 07%3A13%3A21.496  7504  7548 D Groups  %3A [EDT] 0%3A0%3A30%2C560 - Exception%3A java.lang.NullPointerException - Attempt to invoke virtual method _void com.codename1.impl.android.a%24b.a()_ on a null object reference
07-06 07%3A13%3A21.496  7504  7548 W System.err%3A java.lang.NullPointerException%3A Attempt to invoke virtual method _void com.codename1.impl.android.a%24b.a()_ on a null object reference
07-06 07%3A13%3A21.496  7504  7548 W System.err%3A 	at com.codename1.impl.android.a.a(AndroidAsyncView.java%3A382)
07-06 07%3A13%3A21.496  7504  7548 W System.err%3A 	at com.codename1.impl.android.f.a(AndroidImplementation.java%3A1650)
07-06 07%3A13%3A21.496  7504  7548 W System.err%3A 	at com.codename1.impl.a.t(CodenameOneImplementation.java%3A644)
07-06 07%3A13%3A21.497  7504  7548 W System.err%3A 	at com.codename1.w.s.m(Display.java%3A1249)
07-06 07%3A13%3A21.497  7504  7548 W System.err%3A 	at com.codename1.w.s.l(Display.java%3A1158)
07-06 07%3A13%3A21.497  7504  7548 W System.err%3A 	at com.codename1.w.aq.run(RunnableWrapper.java%3A120)
07-06 07%3A13%3A21.497  7504  7548 W System.err%3A 	at com.codename1.impl.b%241.run(CodenameOneThread.java%3A60)
07-06 07%3A13%3A21.497  7504  7548 W System.err%3A 	at java.lang.Thread.run(Thread.java%3A919)
07-06 07%3A13%3A21.498  7504  7504 D ViewRootImpl%40528aa33[GroupChartStub]%3A ViewPostIme pointer 1
07-06 07%3A13%3A21.499  7504  7548 D Groups  %3A [EDT] 0%3A0%3A30%2C564 - Exception in Groups version 1.88
07-06 07%3A13%3A21.500  7504  7548 D Groups  %3A [EDT] 0%3A0%3A30%2C565 - OS and
07-06 07%3A13%3A21.502  7504  7548 D Groups  %3A [EDT] 0%3A0%3A30%2C567 - Error java.lang.NullPointerException%3A Attempt to invoke virtual method _void com.codename1.impl.android.a%24b.a()_ on a null object reference
07-06 07%3A13%3A21.503  7504  7548 D Groups  %3A [EDT] 0%3A0%3A30%2C567 - Current Form null
07-06 07%3A13%3A21.504  7504  7548 D Groups  %3A [EDT] 0%3A0%3A30%2C568 - Exception%3A java.lang.NullPointerException - Attempt to invoke virtual method _void com.codename1.impl.android.a%24b.a()_ on a null object reference
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A java.lang.NullPointerException%3A Attempt to invoke virtual method _void com.codename1.impl.android.a%24b.a()_ on a null object reference
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.impl.android.a.a(AndroidAsyncView.java%3A382)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.impl.android.f.a(AndroidImplementation.java%3A1650)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.impl.a.t(CodenameOneImplementation.java%3A644)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.w.s.m(Display.java%3A1249)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.w.s.l(Display.java%3A1158)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.w.aq.run(RunnableWrapper.java%3A120)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at com.codename1.impl.b%241.run(CodenameOneThread.java%3A60)
07-06 07%3A13%3A21.504  7504  7548 W System.err%3A 	at java.lang.Thread.run(Thread.java%3A919)
07-06 07%3A13%3A21.507  7504  7550 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 07%3A13%3A21.507  7504  7550 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 07%3A13%3A21.794  7504  7550 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 07%3A13%3A21.794  7504  7550 I System.out%3A (HTTPLog)-Static%3A isSBSettingEnabled false
07-06 07%3A13%3A22.665  7504  7504 D ViewRootImpl%40528aa33[GroupChartStub]%3A ViewPostIme pointer 0_

**Comment by javieranton-zz** [comment]
Anyway, I might be doing something wrong too who knows. If you can't immediately figure it out leave it with me and I will try to see if it makes any sense

**Comment by javieranton-zz** [comment]
More on this, just trying to be as thorough as possible. If read carefully the native logs show that the problem is that a `Form` is `null`. I use an extended version of `Form` that stores its day/dark theme state so that when the application comes back from bg to fg its `show` event looks for changes and applies color changes to the form accordingly

Because of this, I do not use Display.getInstance().getCurrent() to re-show a `Form`. Instead, I store the current `ExtendedForm` in a static variable and re-show this instead. I check for it to be null too just in case. The resulting code that replaces `Display.getInstance().getCurrent()` looks like this

    public Form getCurrentForm()
    {
        try{
            if(Display.getInstance().getCurrent() instanceof Dialog)
                ((Dialog)Display.getInstance().getCurrent()).dispose();
            else if(Display.getInstance().getCurrent() instanceof ExtendedDialog)
                ((ExtendedDialog)Display.getInstance().getCurrent()).dispose();
            return DataBridge.getInstance().currentForm; //this is my statically saved current form
        }catch(Exception e)
        {
            traceDebug("Utils.getCurrentForm exception: "+e.toString());//this never happens
            return Display.getInstance().getCurrent();
        }
    }

I wonder if this has anything to do with this problem. It's also worth noting that I have only seen this in Android users but Android users outnumber iOS users by a factor of 3 so perhaps I just haven't seen it in iOS yet (this error is not tha common)

**Comment by codenameone** [comment]
This probably has nothing to do with this. This is very low level and I can't see a lot that can impact there unless you wrote native code that manipulated the layout of the core implementation. 

This is the offending line: https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/AndroidAsyncView.java#L335

This code is invoked on the native android thread so I don't see a race condition here unless native code somewhere violated the Android thread safety rules. `v` shouldn't be null in any case I can think of.

**Comment by javieranton-zz** [comment]
No native code that deals with UI on my end. I have searched for all places where I do any "resize" and I can see that I do resize an `AnimatedDialog` in a few places. Could this be it? I will keep looking

**Comment by javieranton-zz** [comment]
Issue has gone away after I added a `synchronized` block in the `AnimatedDialog`'s Dispose and Resize methods
