### ISSUE TITLE
(EasyFix) Image.subImage(...) is ignoring alpha parameter

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3163]
[alpha parameter here](https://github.com/codenameone/CodenameOne/blob/19ba3305628a211d72b238bf2283313f4ebe81d3/CodenameOne/src/com/codename1/ui/Image.java#L331) is ignored, is that normal?

**Comment by javieranton-zz** [comment]
Maybe I am wrong, feel free to close if needed

**Comment by shai-almog** [comment]
An older version of this method used complex image manipulation which was more expensive for the case of alpha support. This is no longer the case and alpha is always preserved by the newer API. If you're seeing a specific problem I suggest opening the issue with the problem and ideally a test case. Thanks!
