### ISSUE TITLE
Support websocket protocol option

### ISSUE THREAD

**Issue by liannacasper** [codenameone/CodenameOne#3179]
The websocket API needs to support the ability to define a protocol when creating a connection.

**Comment by arturhefczyc** [comment]
Hi,

Do you have ETA for this?

**Comment by shannah** [comment]
I can probably fit this in this week.

Notes: 

- iOS:  https://github.com/facebookarchive/SocketRocket/blob/master/SocketRocket/SRWebSocket.h#L159
- Android, JavaSE:  `WebSocket.addProtocol(String)`
- Javascript https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket  (`protocols` parameter).
- Windows UWP : https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.messagewebsocketcontrol.supportedprotocols?view=winrt-19041#remarks

**Comment by arturhefczyc** [comment]
Thank you for update.

I see it is scheduled for version CN1 planned for Sept 20. Is there any way we can get this sooner, before official release?

This is blocking our development and getting it sooner would be very helpful.

**Comment by shai-almog** [comment]
Most of the stuff that's fixed here gets into the Friday releases so it's ready sooner in this case it's a cn1lib so it's will be even sooner than that (roughly a day after fixing). The milestone just indicates a general era for the fix.

**Comment by arturhefczyc** [comment]
Good to know. Thanks a lot!

**Comment by shannah** [comment]
I've added an optional 2nd parameter to the WebSocket constructor for a space-delimited string of sub-protocols.  I've also added  setProtocols(String) and getProtocols():String methods to set this outside the constructor (but before connect()).

You can download new build of cn1lib here https://github.com/shannah/cn1-websockets/blob/master/dist/cn1-websockets.cn1lib

It will be available in Codename One Preferences within a few days.

**Comment by arturhefczyc** [comment]
Thanks a lot!
