### ISSUE TITLE
RFE: more contrasted text in the New Settings UI

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3193]
This is just a reminder of the comment to your blog post https://www.codenameone.com/blog/new-settings-ui.html and of your answer.

My comment:

> [...] My feedback is that the text is too little contrasted: it's hard for me to read a light grey text on a white background, I would prefer a black text on a white background. I also find dark mode tiring for the eyes.
> I hope you can make the text black or at least add an option to it. Thank you

Your answer:

`We'll try to increase contrast here to make it more readable.`

**Comment by shai-almog** [comment]
This is fixed and will be a part of the new update to settings. We're still working on the wizard issue which is why this wasn't out yet.

**Comment by jsfan3** [comment]
After a week, I don't see any change in the UI colors.

**Comment by shai-almog** [comment]
We didn't release an update to the settings yet
