### ISSUE TITLE
NullPointerException on MapContainer of GoogleMaps Lib

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#3199]
Create an app and add the GoogleMaps extension.

Create a simple form with a MapContainer

```
MapContainer googleMap = new MapContainer();
form.add(CENTER, googleMap);
```

It throws the following exception:

> [EDT] 0:0:8,83 - Exception: java.lang.NullPointerException - null
> java.lang.NullPointerException
> 	at com.codename1.ui.Container.insertComponentAtImpl(Container.java:926)
> 	at com.codename1.ui.Container.insertComponentAt(Container.java:918)
> 	at com.codename1.ui.Container.addComponent(Container.java:855)
> 	at com.codename1.ui.BrowserComponent$9.run(BrowserComponent.java:534)
> 	at com.codename1.ui.Display.processSerialCalls(Display.java:1331)
> 	at com.codename1.ui.Display.edtLoopImpl(Display.java:1274)
> 	at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
> 	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
> 	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by shai-almog** [comment]
Make sure to add the JavaScript key for google maps.

**Comment by diamondobama** [comment]
I added the key. I excluded it above for simplicity.

**Comment by shai-almog** [comment]
Did you pass it in the constructor too?

**Comment by diamondobama** [comment]
Yes, I did. The app was working fine until last Friday. The exception seems related to the  BrowserComponent.

**Comment by shai-almog** [comment]
I'm guessing the CEF change broke that: https://www.codenameone.com/blog/big-changes-jcef.html
Make sure you either use CEF or use a VM that includes JavaFX in it.

**Comment by diamondobama** [comment]
Yes, that's the issue. MapContainer is now showing.

Below StackTrace might be of use to you or @shannah, especially the non-intrusive exception part.

> CEF Args: [--disable-gpu, --disable-software-rasterizer, --disable-gpu-compositing, --touch-events=enabled, --enable-media-stream, --device-scale-factor=4, --force-device-scale-factor=4, --autoplay-policy=no-user-gesture-required, --enable-usermedia-screen-capturing]
> Using:
> JCEF Version = 83.4.0.260
> CEF Version = 83.4.0
> Chromium Version = 83.0.4103.106
> initialize on Thread[AWT-EventQueue-0,6,main] with library path C:\Users\Diamond\.codenameone\cef\lib\win64
> Added scheme search://
> Added scheme client://
> Added scheme cn1stream://
> 
> DevTools listening on ws://127.0.0.1:8088/devtools/browser/3267ccb2-8c24-476e-b0d8-5d88d5087c8f
> AppHandler.stateHasChanged: NEW
> AppHandler.stateHasChanged: INITIALIZING
> Rendering frame took too long 698 milliseconds
> AppHandler.stateHasChanged: INITIALIZED
> Setting URL but not ready https://cn1app/streams/1
> Running ready callbacks
> Setting url https://cn1app/streams/1
> Rendering frame took too long 307 milliseconds
> **`Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Stream was closed`**
> Address changed to https://cn1app/streams/1
> [0805/214308.335:INFO:CONSOLE(22)] "Here I am !!!", source: https://cn1app/streams/1 (22)
