### ISSUE TITLE
Android implementation for openGallery has recently been broken

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3204]
The obtained image has an underlying implementation that is `null`. The CN1 `Image` object isn't null, but calling `getHeight()`, or trying to do anything at all with the `Image` returns the following exception:
`java.lang.NullPointerException: Attempt to invoke virtual method _int android.graphics.Bitmap.getHeight()_ on a null object reference`

The below code can reproduce this issue

    openGallery(ee -> {
                    if (ee != null && ee.getSource() != null) {
                        try {
                            Image picImg = Image.createImage((String) ee.getSource());
                            picImg.getHeight();//BREAKS HERE
                        } catch (IOException err) {
                        }
                    }
                }, GALLERY_IMAGE);

Edit2: I saw that app updates have until November to switch to API 29. So for now I can keep submitting with API 28 which means that this isn't a deal breaker at least for me

Edit3: as seen below this is caused by API 29

**Comment by jsfan3** [comment]
Just a curiosity: is it the same if you replace your code with the following?
```
String photoSafePath = FileSystemStorage.getInstance().getAppHomePath() + "/myPhoto.jpg"; 
Image img = Image.exifRotation((String) ee.getSource(), photoSafePath);
picImg.getHeight();
```

**Comment by javieranton-zz** [comment]
> 
> 
> Just a curiosity: is it the same if you replace your code with the following?
> 
> ```
> String photoSafePath = FileSystemStorage.getInstance().getAppHomePath() + "/myPhoto.jpg"; 
> Image img = Image.exifRotation((String) ee.getSource(), photoSafePath);
> picImg.getHeight();
> ```

This results in the application being frozen. No exception is thrown but the app becomes completely unresponsive

**Comment by javieranton-zz** [comment]
My first guess is that an Android update has introduced a requirement for updating some implementation code

**Comment by javieranton-zz** [comment]
I found this

https://github.com/codenameone/CodenameOne/issues/2676

I tried downloading new images and choosing them inc ase the issue is my sd card but the same happened

**Comment by jsfan3** [comment]
I suspect that this bug is related to https://github.com/codenameone/CodenameOne/issues/3192

My suspicion is motivated by the fact that the two bugs have two features in common:

1. the first is that the problem is caused only by the use of files returned from the Gallery, while the photos and videos captured with the Capture API don't generate the same problems (leaving the rest of the code unchanged);

2. the second is that, with the code change I suggested, you got an app freeze that is probably caused by an infinite loop (by the way, the code I gave you had to work, or at least it worked with API 28).

**Comment by javieranton-zz** [comment]
You are correct. This must be caused by API 29. I just recovered an old version from last month before the switch to API29 was made and it didn't have this issue

**Comment by javieranton-zz** [comment]
Did you say in #3192 that there was a workaround? (for pictures)

I need to fix this asap in any way possible as my prod release is glitched

**Comment by jsfan3** [comment]
Try these two build hints:
```
android.targetSDKVersion=28
android.buildToolsVersion=28
```

This is the only workaround I found.

**Comment by javieranton-zz** [comment]
You just saved me. I was under the wrong impression that API 29 was required from August, but after trying to submit with API 28 I learned that that is only for new apps. Updates have until November! Phew!

**Comment by jsfan3** [comment]
I'm glad I could help: even I didn't know when the switch to API 29 will be mandatory, thanks for telling me.

However, I hope that these problems will be fixed soon, because they are certainly having an impact on all the apps.

**Comment by javieranton-zz** [comment]
Just bumping this up... one month and 5 days to go until the play store won't accept submissions with API28. On Nov 1 we won't be able to use the Gallery unless this is fixed

Apologies if this is being actively looked at. Just making sure it doesn't fall off the radar in case the sea of other tasks manages to eclipse this

**Comment by shannah** [comment]
I was able to fix this issue in the provided test case on my Android 11 device with https://github.com/codenameone/CodenameOne/commit/a20dcddb9d158121257b8d4852ca2a3a18663557

This is not a "good" fix, but it should get you moving.  It will be part of next week's update.

**Comment by javieranton-zz** [comment]
That's great, thanks for this. I will make sure to test it on a couple devices 1 week from now

**Comment by javieranton-zz** [comment]
Just finished testing this on 2 devices:
-Samsung galaxy Prime, with Android 5.1.1
-Samsung Galaxy A6, with Android 10

The issue doesn't show in the Prime device. So **the issue remains**. I guess the Prime device can't use API 29 because of its Android version anyway

**Comment by javieranton-zz** [comment]
10 days to go... sry if this is being looked at

**Comment by javieranton-zz** [comment]
As suggested by Shai, adding the following build hint fixes this for now:

`android.xaplication_attr=android:requestLegacyExternalStorage="true"`

**Comment by shannah** [comment]
I have pushed a change that fixes my test case using API 30, Android 10 device.
If you're using Maven, you'll be able to test this out in a few hours by setting your cn1.version and cn1.plugin.version properties in your pom.xml file to 7.0.23.

(The few hours wait is because it takes Maven central that long for releases to propagate - and I just released this version).

Alternatively, build CN1 from source (using Maven), then set cn1.version to 7.0.24-SNAPSHOT.  And do a local Android build.

This fix will be available on the build server next Friday.

**Comment by javieranton-zz** [comment]
I can confirm that this works. Tested on Android 11 and Android 5 (Samsung S21 and Samsung Galaxy Prime)

To be clear I did build with API level 29 (build hint `android.targetDSDKVersion` = 29 and `android.buildToolsVersion` = 29) which corresponds to [Android 10 level](https://developer.android.com/studio/releases/platforms)

Thanks a lot, really appreciate this

**Comment by javieranton-zz** [comment]
I am having to reopen this. I saw in my trace that some users were getting the ` java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference` exception. I then also tried testing these changes on my Samsung Galaxy A6 (Android 10) device and found that it also throws the error. Please fix this soon! As of now it only doesn't work on the A6. It works on my Samsung S21 (Android 11) and Prime (Android 5). I will have to revert my changes until this is fixed and the deadline is May 5th

**Comment by shannah** [comment]
Are you sure that those users are using the fixed version? 

I'd like to look at this tomorrow but there isn't much to go on here.

Do you have a stack trace?

**Comment by javieranton-zz** [comment]
Yes, I am 100% sure of it. Here is the full stack trace:

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference. Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
	at com.codename1.impl.android.f.e(AndroidImplementation.java:2255)
	at com.codename1.y.ac.b(Image.java:713)
```

As discussed in this issue, the `Image` is created with `openGallery`'s param `getSource()` but as soon as `getHeight()` is called on it a null ref is thrown. So the stack trace won't show anything other than an `Image` throwing a null ref I'm afraid

For example:

```
openGallery(ee -> {
    Image picImg = Image.createImage((String)ee.getSource());
    picImg.getHeight();//breaks here
});
```

I can reproduce on a Samsung A6 so feel free to use me for trial-and-error fixes

**Comment by javieranton-zz** [comment]
Native Logs also don't say anything in particular

[This line](https://github.com/codenameone/CodenameOne/blob/40811123ac99f254b1609a1698cf745b71a9b623/Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java#L7984) looks suspicious

If you want I can try building locally to see if I can fix it. I don't currently know how to do this. If you can point me to a guide or spell out the steps for me I'll be happy to try to help fixing this

A few ideas to try:
1. Change `Uri selectedImage = intent.getData();` with `Uri selectedImage = (Uri) intent.getParcelableExtra(Intent.EXTRA_STREAM);`
   Then, skip the second parameter of ContentResolver and do like so: `getContentResolver().query(selectedImage, null, null, null, null);`

**Comment by javieranton-zz** [comment]
Found [this](https://shannah.github.io/cn1-maven-archetypes/cn1app-archetype-tutorial/getting-started.html#android)
It might take me a while to do this as I also have my day job during the week

**Comment by javieranton-zz** [comment]
Trying to build the new maven CN1 project and IDEA is kind of stuck trying to find JCEF
![image](https://user-images.githubusercontent.com/11293898/115212882-e2a91f00-a0f8-11eb-8da8-a84d165f7e9e.png)
Can't fix it by reolving any maven dependency..

**Comment by shannah** [comment]
Wait.  Youre nit building locally?  The fix isn't on the build server yet so you are bit working with the fix yet.  

It will be on server on Friday

**Comment by javieranton-zz** [comment]
OK no problem, couldn't work out that it had to be built locally from your comment. Friday it is

**Comment by javieranton-zz** [comment]
Was able to build locally and checked that the fix works on the A6 device

**Comment by javieranton-zz** [comment]
https://github.com/codenameone/CodenameOne/issues/3394
The path to the built android gradle project was too long. Too many subfolders with long names
