### ISSUE TITLE
com.codename1.db.Database.execute executes queries twice sometimes on Android

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3224]
This is a fringe case that happens very rarely, but it does happen and I have seen it for several months now

The reason why I am able to capture this behavior is that my target's table has a `UNIQUE` column and when an `INSERT` is run twice against it it throws a  `java.io.IOException: UNIQUE constraint failed`

It's almost impossible to reproduce this as it happens extremely rarely

The condition under which this happens is: executing multiple transactions one after another by an `EasyThread`

**Comment by javieranton-zz** [comment]
I can confirm that this issue happens under the following circumstances:

- Rapid succession of INSERT transactions get executed in series

The second INSERT gets executed twice

Again, this is an edge case that happens in 1% of cases. But it does happen, I'm very confident of this

**Comment by shai-almog** [comment]
Unique is implemented by SQLite which isn't under our control. If it fails it's a problem with sqlite. 

However, sqlite is VERY thread sensitive so I suggest verifying that all database access happens from a single thread.

**Comment by javieranton-zz** [comment]
Thx..I will revise my code so that all db access is done from the same thread always
