### ISSUE TITLE
android.proguardKeep build hint doesn't work when the first character isn't [\ ]

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3232]
Spent lots of time trying to figure this one out

**Comment by javieranton-zz** [comment]
the build hint needs to start (without brackets) [\  ] otherwise it breaks

**Comment by shai-almog** [comment]
Did you do this with the UI or by changing codenameone_settings.properties ?
Notice that properties has some weird syntax requirements which the GUI should handle

**Comment by javieranton-zz** [comment]
First I tried the UI

Then I edited the props file including the special initial text (I noticed that initial text in one cn1lib - I forget which one). That worked

**Comment by shai-almog** [comment]
This will be available next week
