### ISSUE TITLE
uses-library   org.apache.http.legacy

### ISSUE THREAD

**Issue by Y-souhail** [codenameone/CodenameOne#3235]
Hello Codenameone support,

I would like to have some help with my question.
I can't find this declaration 
<uses-library
      android:name="org.apache.http.legacy"
      android:required="false" />

 in  AndroidManifest.xml

Thanks in advance for the support.

**Comment by liannacasper** [comment]
Hi,
Our support is in the website chat, stackoverflow and the discussion forum. This is for issues and RFEs.
