### ISSUE TITLE
JavaScript port should provide an option for Android theme as fallback

### ISSUE THREAD

**Issue by liannacasper** [codenameone/CodenameOne#3243]
When running on an OS that is neither Android nor iOS the fallback is to use the iOS theme. We should provide an option so the fallback would be the Android theme.

**Comment by shannah** [comment]
You can use the "javascript.native.theme" display property to set the native theme inside your app's init() method (before loading the theme).

E.g. 

~~~~
CN.setProperty("javascript.native.theme", "/android_holo_light.res");  // set native theme to android.
~~~~
