### ISSUE TITLE
The build link is not encoded correctly (for email)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3257]
Please take a look at this screenshot, as you can see the link is not correct (the encoding should not have been done). 

Moreover, for those like me who do not use a mail program (like the one that opened automatically) but only webmail, the previous functionality was the one desired (i.e. the automatic sending of the email through your server). 

Alternatively, it would be enough a functionality that allows me to copy the link and send it to who I want in the way I prefer.

![Screenshot_20200905_134656](https://user-images.githubusercontent.com/1997316/92304522-06ab5c00-ef7f-11ea-86d6-380fa461a329.png)

**Comment by shai-almog** [comment]
This looks to me like a bug in kmail. The URI should be encoded and I think kmail doesn't decode the link correctly. There will be a copy action in the Friday update
