### ISSUE TITLE
[BUG or RFE?] CSS margins currently don't support percentage

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3260]
I'm not sure if it's a bug or a RFE.

I need to set a margin in percentage.

The Codename One Designer allows to set margins using as measure unit "Millimeters", "Pixels" and "Screen Size Percentage".

The issue is that using percentage in a CSS element, like:
```
LoginForm {
    margin-top: 15%;
    margin-bottom: 15%;
    text-align: center;
}
```

produces the following error:
```
ant -f /home/francesco/MyApp/MyAppClient -Dnb.internal.action.name=rebuild clean jar
Generating GUI sources
No GUI Entries available
init:
deps-clean:
Deleting directory /home/francesco/MyApp/MyAppClient/build
refresh-libs-impl:
Deleting directory /home/francesco/MyApp/MyAppClient/lib/impl
Deleting directory /home/francesco/MyApp/MyAppClient/native/internal_tmp
clean:
Created dir: /home/francesco/MyApp/MyAppClient/native/internal_tmp
Generating GUI sources
No GUI Entries available
init:
deps-jar:
Created dir: /home/francesco/MyApp/MyAppClient/build/classes
JavaFX is loaded
Retina Scale: 1.0
Updating merge file /home/francesco/MyApp/MyAppClient/css/theme.css.merged
Input: /home/francesco/MyApp/MyAppClient/css/theme.css
Output: /home/francesco/MyApp/MyAppClient/src/theme.res
Acquiring lock on CSS checksums file /home/francesco/MyApp/MyAppClient/.cn1_css_checksums...
Lock obtained
An error occurred while updating resources for UIID LoginForm-MyAppLogo.  Processing property margin
Releasing lock
java.lang.RuntimeException: Unsupported unit for inset %
	at com.codename1.designer.css.CSSTheme.getFloatValue(CSSTheme.java:6328)
	at com.codename1.designer.css.CSSTheme.getInsets(CSSTheme.java:6341)
	at com.codename1.designer.css.CSSTheme.access$1000(CSSTheme.java:94)
	at com.codename1.designer.css.CSSTheme$Element.getThemeMargin(CSSTheme.java:4043)
	at com.codename1.designer.css.CSSTheme.updateResources(CSSTheme.java:1573)
	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:539)
	at com.codename1.designer.css.CN1CSSCLI.main(CN1CSSCLI.java:394)
	at com.codename1.designer.ResourceEditorApp.main(ResourceEditorApp.java:556)
/home/francesco/MyApp/MyAppClient/build.xml:625: Java returned: 1
BUILD FAILED (total time: 4 seconds)
```

**Comment by shannah** [comment]
Since, in CSS, percentage units exist, and mean something different than percentage units in CN1, I felt is was best just not to support them at this time.  In order to support them the way CSS does, we'd need to calculate them at runtime ("layout time").  This currently isn't implemented in CN1, but wouldn't be impossible so it's possible that we could support it at some point in the future.  The alternative - just map CSS percentage units to the current CN1 meaning for percentage units - would be easy to do, but then it would cause confusion later if we supported a "different" kind of percentage.

Background:  Percentage in CSS generally means percent of parent dimension.  Percentage in CN1 is percentage of screen.

CSS does include units that map to CN1 percentages.  "vw" and "vh".  These aren't implemented yet though, but should be.

Were you looking for the CN1 behaviour (actually "vw" and "vh"), or the CSS behaviour for percentage?

**Comment by jsfan3** [comment]
> Background: Percentage in CSS generally means percent of parent dimension. Percentage in CN1 is percentage of screen.

I didn't know this difference, thanks for the clarification. I understand that based on the difference in the meaning of the "%" symbol between the CSS standard and the behaviour of CN1 there may be confusion, but it is an important limitation not to be able to use the percentage unit provided by CN1, especially as I now only use CSS.

> Were you looking for the CN1 behaviour (actually "vw" and "vh"), or the CSS behaviour for percentage?

I'm looking for the CN1 behaviour.

To be as clear as possible, I would like a little piece of CSS like this:
```
MyComponent {
    margin-top: 10 vh;
    margin-bottom: 10 vh;
    text-align: center;
}
```
is fully equivalent to what I could achieve with this code:
```
UIManager.initFirstTheme("/theme");
Resources resource = Resources.openLayered("/theme");

Hashtable themeProps = resource.getTheme("Theme");

themeProps.put("MyComponent.margin", "10,10,0,0"); /* top bottom left right */
themeProps.put("MyComponent.marUnit", new byte[]{Style.UNIT_TYPE_SCREEN_PERCENTAGE, Style.UNIT_TYPE_SCREEN_PERCENTAGE, Style.UNIT_TYPE_SCREEN_PERCENTAGE, Style.UNIT_TYPE_SCREEN_PERCENTAGE});

UIManager.getInstance().setThemeProps(themeProps);
Resources.setGlobalResources(resource);
```

Do you confirm that the CSS I posted could be fully equivalent to the Java code above?

**Comment by shannah** [comment]
In CSS you can use the `vh`, `vw`, `vmin`, and `vmax` units to achieve screen percentage.  E.g.

~~~~
MyStyle {
    padding-left: 25vw;  /* 25% of the screen width*/
    padding-top: 25vh;  /* 25% of the screen height */
    padding-bottom: 25vmin; /* 25% of the minimum of screen width and height */
    padding-right: 25vmax; /* 25% of the maximum of screen width and height */
~~~~
