### ISSUE TITLE
TextArea hint

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3261]
Please make public the method setHintLabelImpl to custom the Uiid hint. Actually is private in your source code.

![image](https://user-images.githubusercontent.com/16245755/92662790-93328300-f2cd-11ea-89bd-4d46904e21a0.png)

**Comment by shai-almog** [comment]
It's intentionally package private. What's the use case for exposing it?

**Comment by DurankGts** [comment]
how can I to custom the hint in TextArea Component with different uiid if I have various TextArea components?

**Comment by liannacasper** [comment]
Use `textArea.getHintLabel().setUIID("...");`

**Comment by javieranton-zz** [comment]
@liannacasper 's answer is right, this should be closed imo
