### ISSUE TITLE
Preferences issue

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3265]
Plese tell me witch character if not permitted to write in preferences because some times fails in your code

![image](https://user-images.githubusercontent.com/16245755/93367136-1c8c0d00-f81a-11ea-9157-ad943060f731.png)

**Comment by shai-almog** [comment]
This is caused by the end of file. The file got corrupted.

**Comment by DurankGts** [comment]
but my question is why this fail is ramdonly?

**Comment by shai-almog** [comment]
At this point we can't tell. The file is already corrupt. My guess is that you might be writing to that file on destroy() or some other method where the app is already dying and doesn't have time to sync before writing is finished.
