### ISSUE TITLE
Floating Action Button - exception after orientation change

### ISSUE THREAD

**Issue by P5music** [codenameone/CodenameOne#3277]
The attached zip file contains the src files from a simplified project that reproduces the issue. 
It is a Hello world project. [src.zip](https://github.com/codenameone/CodenameOne/files/5292437/src.zip)

The issue is that  an exception is issued when reconstructing the user interface (see the source code) after orientation change (the code in the listener is executed).

A message is displayed on screen ("an internal error occurred") with the same text of exception:
if the fab is removed no exception is produced

` if (!fabFirstTime) fab.remove();`
 
 but the user interface does not reconstruct. It sort of hangs.

Here's the error when the fab is not removed.

java.lang.IllegalArgumentException: Component is already contained in Container: Container[x=0 y=0 width=2048 height=1423 name=null, layout = FlowLayout, scrollableX = false, scrollableY = false, components = [FloatingActionButton]]
	at com.codename1.ui.Container.insertComponentAtImpl(Container.java:929)
	at com.codename1.ui.Container.insertComponentAt(Container.java:920)
	at com.codename1.ui.Container.addComponent(Container.java:842)
	at com.codename1.ui.Container.add(Container.java:362)
	at com.codename1.components.FloatingActionButton.bindFabToContainer(FloatingActionButton.java:313)
	at com.codename1.components.FloatingActionButton.bindFabToContainer(FloatingActionButton.java:286)
	at com.codename1.fabusercase.FabTestCase.setContainers(FabTestCase.java:150)
	at com.codename1.fabusercase.FabTestCase.lambda$start$1(FabTestCase.java:100)
	at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
	at com.codename1.ui.Form.sizeChangedInternal(Form.java:787)
	at com.codename1.ui.Display.handleEvent(Display.java:2442)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1244)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
[EDT] 0:0:29,145 - Exception: java.lang.IllegalArgumentException - Component is already contained in Container: Container[x=0 y=0 width=2048 height=1423 name=null, layout = FlowLayout, scrollableX = false, scrollableY = false, components = [FloatingActionButton]]

**Comment by shai-almog** [comment]
Please embed sources into the issue as mentioned below.
As is shown in the stack trace in line 150 you invoke `fab.bindFabToContainer(itemListContainer))` again on a FAB which is already bound. Hence the exception. You can solve this with the new `unbind` method that will be available in the next update or you can avoid calling bind again for the fab.

```java
public void start() {
    if(current != null){
        current.show();
        return;
    }
    Form hi = new Form("Hi World", BoxLayout.y());
    hi.add(new Label("Hi World"));

   mainForm=hi;

    tl=new TableLayout(1,2);
    mainForm.setLayout(tl);
    mainForm.setScrollable(false);

    leftContainerRatio= Float.valueOf(Display.getInstance().getDisplayHeight())/Float.valueOf(Display.getInstance().getDisplayWidth());
    itemListContainer=new ItemListContainer();

    mainEditingContainer=new Container(new BorderLayout());
    editingContainer=new EditingContainer();
    mainEditingContainer.add(BorderLayout.CENTER,editingContainer);
    fab= FloatingActionButton.createFAB(FontImage.MATERIAL_ADD);
    fab.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
        }
    });

    setContainers();

    mainForm.addOrientationListener(e -> {
        setContainers();
    });
    mainForm.show();
}

private void setContainers()
{
    mainEditingContainer.remove();
    itemListContainer.remove();

    //if (!fabFirstTime) fab.remove();

    mainEditingContainer.revalidate();
    editingContainer.revalidate();
    itemListContainer.revalidate();

    mainForm.revalidate();

    if (isPortrait()){
        mainForm.add(tl.createConstraint().heightPercentage(100).widthPercentage((int)(1*100)),fab.bindFabToContainer(itemListContainer));
    }
    if(isTablet() && !isPortrait() ) {
        {mainForm.add(tl.createConstraint().heightPercentage(100).widthPercentage((int) (leftContainerRatio * 100)), fab.bindFabToContainer(itemListContainer)).add(mainEditingContainer);}
    }

    mainEditingContainer.revalidate();
    editingContainer.revalidate();
    itemListContainer.revalidate();
    mainForm.revalidate();

    if (fabFirstTime) fabFirstTime=false;
}
```
