### ISSUE TITLE
TableLayout is not set on default BorderLayout form

### ISSUE THREAD

**Issue by P5music** [codenameone/CodenameOne#3281]
IntelliJ IDEA 2020.2.2 (Community Edition)
Build #IC-202.7319.50, built on September 15, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 949M
Cores: 4
Non-Bundled Plugins: com.kaylerrenslow.plugin.armaplugin.id, com.codename1.plugin.intellij
Current Desktop: ubuntu:GNOME

This test case shows that the TableLayout is not set correctly.
Debug allows you to see this issue just after the setLayot() method is called on mainForm,
and
in the setContainers method.
BorderLayout seems to be sticking on that form.

Here is the main class of the Hello worlld project

    public class FabTestCase {

    private Form current;
    private Resources theme;
    private ItemListContainer itemListContainer; //empty Container subclass
    private EditingContainer editingContainer; //empty Container subclass
    private Container mainEditingContainer;
    private Container fabBoundContainer;
    Form mainForm;
    TableLayout tl;
    FloatingActionButton fab;
    boolean fabFirstTime=true;
    Float leftContainerRatio;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });

    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));

       mainForm=hi;

        tl=new TableLayout(1,2);
        mainForm.setLayout(tl);
        mainForm.setScrollable(false);

        leftContainerRatio= Float.valueOf(Display.getInstance().getDisplayHeight())/Float.valueOf(Display.getInstance().getDisplayWidth());

    itemListContainer=new ItemListContainer();
        mainEditingContainer=new Container(new BorderLayout());
        editingContainer=new EditingContainer();
        mainEditingContainer.add(BorderLayout.CENTER,editingContainer);
        fab= FloatingActionButton.createFAB(FontImage.MATERIAL_ADD);
        fab.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
            }
        });

        setContainers();

        mainForm.addOrientationListener(e -> {
            setContainers();

        });

        mainForm.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

    private void setContainers()
    {
        mainEditingContainer.remove();

        if (fabBoundContainer!=null) fabBoundContainer.remove();

        if (fabFirstTime) fabBoundContainer=fab.bindFabToContainer(itemListContainer);

        if (isPortrait() )
        {

            mainForm.add(tl.createConstraint().heightPercentage(100).widthPercentage((int)(1*100)),fabBoundContainer);
        }
        if(isTablet() && !isPortrait() ) {

            {mainForm.add(tl.createConstraint().heightPercentage(100).widthPercentage((int) (leftContainerRatio * 100)), fabBoundContainer).add(mainEditingContainer);}

        }

        mainEditingContainer.revalidate();
        editingContainer.revalidate();
        itemListContainer.revalidate();
        mainForm.revalidate();

        if (fabFirstTime) fabFirstTime=false;
    }
    
    }

**Comment by shai-almog** [comment]
There are two things you can try here. First and possibly seamless:

```java
    mainForm.addOrientationListener(e -> {
        tl=new TableLayout(1,2);
        mainForm.setLayout(tl);
        setContainers();
    });
```

The motivation behind this is that table layout is a stateful layout. So it might be left in a state that makes its mutation harder. Creating a new layout should reset it.

The second approach is to always add elements to explicit row/column constraints. Since that's the core state of the table layout it would make sense to circumvent the statefulness of the layout and avoid `tl.createConstraint()`. Instead use `tl.createConstraint(row, column)` or `tl.cc(row, column)` for short.

**Comment by P5music** [comment]
I already tried the first approach but it did not work.
I tried also the second approach with
    createContraint(0,0)
but it does not work either.
I think the reason is that the TableLayout does not get set on the form, as the issue complains. It is strange altogether.

**Comment by shai-almog** [comment]
When you invoke setLayout() on form it's effectively a synonym to invoking:

```java
form.getContentPane().setLayout(...);
```

The form itself is always in border layout which I guess is what you saw when debugging. (Since the form includes the title etc. within it). When you add stuff to the form this also physically adds everything to the content pane and not to the form.
