### ISSUE TITLE
iOS app crashes after pressing info button on scanning screen with cn1-codescan lib

### ISSUE THREAD

**Issue by mykovolod** [codenameone/CodenameOne#3287]
Issue related to https://github.com/codenameone/cn1-codescan lib

In iOS version of the build, there is a Cancel and Info button at the bottom of the screen and when you press the info button, the application just crashes/close immediately with no errors.

Not reproducible in Android as there is simply no such buttons

I think it is something wrong with iOS native code and in particular with ZBar implementation of QR code scanning library. That might be a side effect of moving from UIWebView to WKWebView

**Comment by shannah** [comment]
I have fixed this by removing the info button.  It is available already https://github.com/codenameone/cn1-codescan/blob/master/cn1-codescan.cn1lib[here].  Will be available in Codename One preferences in next update (generally in a few days).
