### ISSUE TITLE
SplitPane for 3 columns.

### ISSUE THREAD

**Issue by arturhefczyc** [codenameone/CodenameOne#3289]
Hi,

Currently `SplitPane` allows for creating view with 2 columns only. I need to split my view into 3 independent columns.

I was going to start implementing my own version of the `SplitPane`, however, before I do, I was wondering that maybe there is something like this already which I missed.

Please let me know if CN1 offers a component like this already. If not, I would be grateful for any suggestions or hints if you have for the SplitPane3 implementation.

**Comment by shai-almog** [comment]
Hi,
it doesn't. 
But the common approach is to nest split panes so one pane includes another split pane. It's not "exactly" the same as a 3 column split pane but it's enough for many use cases.

**Comment by arturhefczyc** [comment]
Thank you for responding. This is what I am doing right now. But the result is not quite good, hence the plan to replace it with SplitPane3.
