### ISSUE TITLE
BrowserComponent is blocked by Dialog

### ISSUE THREAD

**Issue by P5music** [codenameone/CodenameOne#3300]
This example is to demonstrate an issue involving BrowserComponents and Dialogs.
In certain circumstances if one or more BrowserComponents are in the layout, they are subject to get stuck after a Dialog returns.
This is the case I could reproduce, it seems to be an issue, at least in the simulator.
Use this code in a HelloWorld app, you will experience the blocking of the BC after clicking on the button on top.
You will be able to select text in the BC or scroll only before opening the dialog.
After the dialog is opened and the OK button is clicked, you can neither select text, nor scroll the page.

    import static com.codename1.ui.CN.*;
    
    import com.codename1.components.SpanLabel;
    import com.codename1.ui.*;
    import com.codename1.ui.events.ActionEvent;
    import com.codename1.ui.events.ActionListener;
    import com.codename1.ui.layouts.BorderLayout;
    import com.codename1.ui.plaf.UIManager;
    import com.codename1.ui.util.Resources;
    import com.codename1.io.Log;

    import ca.weblite.codename1.json.JSONArray;
    import ca.weblite.codename1.json.JSONException;
    import java.io.IOException;
    import java.util.ArrayList;

    import com.codename1.ui.layouts.BoxLayout;
    import com.codename1.io.NetworkEvent;

    /**
     * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
     * of building native mobile applications using Java.
     */
    public class MyApplication {

    private Form current;
    private Resources theme;
    boolean onloadCalled=false;
    BrowserComponent bc;
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
       Form hi = new Form("Hi World", new BorderLayout());
       bc=new BrowserComponent();
        bc.addWebEventListener("onLoad", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {

    if (onloadCalled) {return;} else
    {onloadCalled=true;

    //openAlertDialog("Test Dialog after onload","Blocking");

    }

            }});

        bc.setPage("<HTML><BODY "
                +"style=\"display:flex;flex-direction:column;\""
                +" >"+
                createLines()+
                "</BODY></HTML>","");

        Button button=new Button("Press this button after HTML is loaded to test");
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                openAlertDialog("User activated test Dialog","Blocking");
            }
        });
        hi.add(BorderLayout.NORTH,button);
        hi.add(BorderLayout.CENTER,bc);
        hi.show();
      
    }

    private String createLines()
    {
        String result="";
        for (int i=0;i<100;i++)
            result=result+"<BR/><P>TRY TO SELECT THIS TEXT / TRY TO SCROLL - LINE "+i+"</P>";
        return result;
    }
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

    Command okCommand=new Command("ok");

    private void openAlertDialog( String s1, String s2)
    {
        Dialog alertDialog=new Dialog(s1);
        Button okButton=new Button(okCommand);
        alertDialog.setLayout(BoxLayout.y());
        Container c1=new Container();
        c1.setLayout(BoxLayout.x());
        alertDialog.add(new SpanLabel(s2, "DialogBody"));
        c1.add(okButton);
        alertDialog.add(c1);
        Command result=alertDialog.showDialog();

    }
    }

**Comment by schreiby** [comment]
Hi, @P5music.  I just had a similar experience on both the simulator and a real device (Android). 

In my case, using the debugger, I saw that `invokeAndBlock()` was called twice and the `BrowserComponent` was stuck hanging on a `wait()` method call. This may be what's happening in your project as well. 

Lianna suggested using `showModeless()` instead of `show()` with my `Dialog` because it doesn't call `invokeAndBlock()` deep inside the stack -- this fixed the problem for me. Maybe you this will work for you as well.

**Comment by P5music** [comment]
@schreiby
Thank you for your response and suggestions.
In fact I need the methods that do return a Command, I tried also another method (showPopupDialog) but it is blocking too.
I am using CodenameOne also for this feature that simplifies my code a lot, and I think the issue is at the feature itself.
If you found the debug path of the issue, please may you share all relevant information here?
Regards

**Comment by javieranton-zz** [comment]
@P5music I had the same issue and resolved using `InteractionDialog` which doens't block the EDT. Be careful on blocking the EDT because on iOS the OS is very strict and will actually halt all your bg js as well as soon as a a Dialog is shown

**Comment by P5music** [comment]
@javieranton-zz 
Thanks.
I need the dialog to return a Command. The Dialog class is what I need because it does so.
Furthermore I do not care blocking the BrowserComponent because there is no background Javascript: the Dialog is opened when all is accomplished in the BC, and if not, there is no harm blocking the BC when the Dialog is foreground.
This issue is about the Dialog blocking the normal functioning of the BrowserComponent (like selecting text, responding to mouse events, scrolling, Javascript of course too) after the Dialog has been closed by the user choosing a command.
In the test case I have a simple dialog with a Ok button.
Regards

**Comment by javieranton-zz** [comment]
It might not be the answer you are looking for but you can also "return" something from InteractionDialog by setting an OnComplete<returnedObject> or by calling a previously defined Runnable. That's how I do it anyway :)

**Comment by P5music** [comment]
@javieranton-zz 
@schreiby 
I tested other Dialog methods and it seems that it is not Dialog's fault.
I see that the BrowserComponent is rendered again after the Dialog returns.
I mean that I see the BC blinking like it is loaded again, then it does not respond to mouse or scroll events.
So the BC gets stuck after receiving some strange "revalidate" command that hangs.
How to avoid or debug that?

**Comment by javieranton-zz** [comment]
All I can say is that after spending lots of time working on this I came to the conclusion that one must never show a Dialog in front of a BC. Browser engines use all sorts of tricks to "save" battery. iOS in particular goes to great lengths to make sure no browser app can run when the browser isn't seen (i.e. blocked by a dialog) because they try to marginalize browser apps in favor of their app store money making machine slave labor apps

**Comment by shannah** [comment]
The most compelling reason not to show a Dialog in front of a BrowserComponent is because the BrowserComponent will appear blank behind the dialog due to the way that dialogs work.  If you want to show a dialog on front of a BrowserComponent, use InteractionDialog, Sheet, or ToastBar as they will work smoothly, and the browser component will still render properly behind it.

**Comment by P5music** [comment]
@javieranton-zz 
@shannah 
Thanks
I will try all your suggestions.
Just please notice that I do not care about what happens when the Dialog is displayed (and I have to say that the BC is just greyed out).
What I experience is that after the Dialog is dismissed after pressing the OK button the BC undergoes a strange transformation: it becomes very tiny, then it is revalidated at normal size but now it does not respond.

**Comment by schreiby** [comment]
@P5music 
Sorry for the delay -- the stacktrace I had is here in this [SO question](https://stackoverflow.com/questions/64650299/after-reloading-cn1-form-gui-elements-stop-working-properly).

As you can see, `invokeAndBlock()` is called twice, then `wait()` is called. In the app, we call a Dialog in a **different** Form, and after this occurs, when showing our Form with the BrowserComponent, the Form opens but the BrowserComponent is blank/empty. Once we changed `show()` to `showModeless()` to show the Dialog, the BrowserComponent worked properly. We also saw that this issue occurred when using 1+ Forms one after the other that the BrowserComponent seemed to just wait to work. Again, in this case, we never show a Dialog in the same Form as the the BrowserComponent, yet it seemed to affect it in a different Form. I realize that this is somewhat different from your case, but as noted above, Dialogs and BrowserComponents seem to interact with each other in certain instances.

@javieranton-zz  & @shannah I've seen that exact behavior where the Dialog in front of the BrowserComponent goes blank.

**Comment by shannah** [comment]
I made a small change that might fix this.  Will be available in next update on Friday.

**Comment by P5music** [comment]
@shannah 
I updated, invalidated chaces and restarted IDEA and rebuilt the project but the issue is there yet.
Has the fix been implemented on Friday?
How to check if I updated correctly? Thanks

**Comment by shannah** [comment]
Are you using CEF or JavaFX for the browser component?  JavaFX is currently the default but this will be changing soon.
https://www.codenameone.com/blog/big-changes-jcef.html

I think that this issue only affects JavaFX, so we have decided not to fix it (in the JavaFX port).  The solution is to use CEF.

Let me know if you're on CEF and you still get this issue.

**Comment by P5music** [comment]
@shannah 
I think I am using the CEF browser. Indeed I get this output:
Using:
JCEF Version = 84.3.8.261
CEF Version = 84.3.8
Chromium Version = 84.0.4147.105
initialize on Thread[AWT-EventQueue-0,6,main] with library path C:\Users\me\.codenameone\cef\lib\win64
Added scheme search://
Added scheme client://
Added scheme cn1stream://

I can reproduce with this example two of three blocking cases: with a Dialog, and with a Form.
I cannot reproduce the orientation change blocking but it is possible that my app is different from this example.
Below the modified main Java file and a new file:

package com.example.myapp;
import static com.codename1.ui.CN.*;

import com.codename1.components.SpanLabel;
import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import com.codename1.ui.layouts.BoxLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    boolean onloadCalled=false;
    BrowserComponent bc;
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", new BorderLayout());
        bc=new BrowserComponent();
        bc.addWebEventListener("onLoad", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {

                if (onloadCalled) {return;} else
                {onloadCalled=true;

//openAlertDialog("Test Dialog after onload","Blocking");

                }

            }});

        bc.setPage("<HTML><BODY "
                +"style=\"display:flex;flex-direction:column;\""
                +" >"+
                createLines()+
                "</BODY></HTML>","");

        Button button=new Button("Press this button after HTML is loaded to open the blocking dialog");
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                openAlertDialog("User activated test Dialog","Blocking");
            }
        });
        Button button2=new Button("Press this button after HTML is loaded to open the blocking form");
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                NewForm newForm=new NewForm(hi);
                newForm.show();
            }
        });

        Container buttonArea=new Container();
        buttonArea.setLayout(BoxLayout.y());
        buttonArea.add(button).add(button2);
        hi.add(BorderLayout.NORTH,buttonArea);
        hi.add(BorderLayout.CENTER,bc);
        hi.show();

    }


    private String createLines()
    {
        String result="";
        for (int i=0;i<100;i++)
            result=result+"<BR/><P>TRY TO SELECT THIS TEXT / TRY TO SCROLL - LINE "+i+"</P>";
        return result;
    }
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }


    Command okCommand=new Command("ok");

    private void openAlertDialog( String s1, String s2)
    {
        Dialog alertDialog=new Dialog(s1);
        Button okButton=new Button(okCommand);
        alertDialog.setLayout(BoxLayout.y());
        Container c1=new Container();
        c1.setLayout(BoxLayout.x());
        alertDialog.add(new SpanLabel(s2, "DialogBody"));
        c1.add(okButton);
        alertDialog.add(c1);
        Command result=alertDialog.showDialog();

    }
}

---------------------------------------------------------------------------------------------------------------------------
package com.example.myapp;

import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;

public class NewForm extends com.codename1.ui.Form {

    private Form callingForm;
    public NewForm(Form callingForm) {
        this(com.codename1.ui.util.Resources.getGlobalResources());
        this.callingForm=callingForm;
    }
    
    public NewForm(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
        Command backCommand=new Command("Back") {
            @Override
            public void actionPerformed(ActionEvent evt) {

               callingForm.showBack();

            }
        };
        Toolbar toolbar=new Toolbar();
        this.setToolbar(toolbar);
        toolbar.setEnabled(true);
        //toolbar.showToolbar();

        Container topBar = BorderLayout.west(new Label());
        topBar.add(BorderLayout.WEST, new Label("Cool App Tagline...", "SidemenuTagline"));
        topBar.setUIID("SideCommand");
        toolbar.addComponentToRightSideMenu(topBar);



        toolbar.setBackCommand(backCommand);



    }
    
//-- DON'T EDIT BELOW THIS LINE!!!


// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.LayeredLayout());
        setInlineStylesTheme(resourceObjectInstance);
                setInlineStylesTheme(resourceObjectInstance);
        setTitle("ewForm");
        setName("ewForm");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}

**Comment by shannah** [comment]
Fixed.  Will be available in next update on Friday.
