### ISSUE TITLE
Bug hidden in SplitPane

### ISSUE THREAD

**Issue by arturhefczyc** [codenameone/CodenameOne#3301]
I was reading the SplitPane code to learn how it works and found that `getTopOrLeftComponent` method might have mistaken implementation:
```java
    public Component getTopOrLeftComponent() {
        for (Component c : bottomOrRight) {
            return c;
        }
        return null;
    }
```

Either I do not understand the concept or this method returns incorrect component.

**Comment by shannah** [comment]
Thanks!  Fixed in git. Will be in next Friday's update.
