### ISSUE TITLE
iOS, display local notifications while in foreground

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3304]
Currently local notifications on iOS can only be shown while the app is in the background.  It should be possible to add support for displaying the notification even while the app is in the foreground.  

From the [developer docs](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html#//apple_ref/doc/uid/TP40008194-CH5-SW15):

> **Handling Notifications When Your App Is in the Foreground**
> 
> If a notification arrives while your app is in the foreground, you can silence that notification or tell the system to continue to display the notification interface. The system silences notifications for foreground apps by default, delivering the > notification’s data directly to your app. You can use the notification data to update your app’s interface directly. For example, if a new sports score arrived, you would just update that information in your interface.
> 
> If you want the system to continue to display the notification interface, provide a delegate object for the `UNUserNotificationCenter` and implement the `userNotificationCenter:willPresentNotification:withCompletionHandler:` method. Your implementation of this method should still process the notification data. When finished, execute the provided completion handler block with the delivery option (if any) that you want the system to use. If you do not specify any options, the system silences the notification. Listing 3-4 shows a sample implementation of this method that tells the system to play a sound. The notification’s payload identifies which sound to play.

This may involve rewriting the entire local notifications implementation on iOS to use the `UNUserNotificationCenter` instead of  `UILocalNotification` and `[[UIApplication sharedApplication] scheduleLocalNotification: notification];` as we currently do it.

References:

- https://izziswift.com/getting-local-notifications-to-show-while-app-is-in-foreground-swift-3/
- https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html#//apple_ref/doc/uid/TP40008194-CH5-SW15

**Comment by shannah** [comment]
Note:  This is related to, but not the same as https://github.com/codenameone/CodenameOne/issues/3286

**Comment by shannah** [comment]
Added new method `LocalNotification.setForeground(boolean)` which can be used to cause a notification to be displayed in the notification center even if the app is in the foreground when the notification is received.
Currently this is only used in iOS.  Looking into Android behaviour now...

**Comment by javieranton-zz** [comment]
Thanks, very useful. Android notifications work ok while in FG in my experience. Thanks again

**Comment by javieranton-zz** [comment]
Just tested this
`localNotificationReceived` is automatically called (without tapping)

**Comment by javieranton-zz** [comment]
`localNotificationReceived` gets automatically called after the notification is shown in the fg

This is the code I used to show the notification in the fg:

    LocalNotification n = new LocalNotification();
                        n.setId(localNotifId);
                        n.setForeground(true);
                        n.setAlertBody("some message");
                        n.setAlertTitle(localNotifTitle);
                        n.setAlertSound("/notification_sound_beep-01a.mp3");
    Display.getInstance().scheduleLocalNotification(
                                n,
                                System.currentTimeMillis() + 500,
                                LocalNotification.REPEAT_NONE
                            );

**Comment by javieranton-zz** [comment]
Also, my debug builds need to be initialized at least 2 times before push registration occurs. Could this have affected this?

**Comment by javieranton-zz** [comment]
My debug builds need to be initialized twice before push registration occurs, I wonder if this has anything to do with it...

**Comment by javieranton-zz** [comment]
Apologies if my feedback is unwanted/too much. Perhaps it's just me, but shouldn't `localNotificationReceived` be called from [didReceiveNotificationResponse](https://github.com/codenameone/CodenameOne/blob/274fa4ac97f086d8a3eb2fcb5b3ae720a1e1ee20/Ports/iOSPort/nativeSources/CodenameOne_GLAppDelegate.m#L421) and not from [willPresentNotification](https://github.com/codenameone/CodenameOne/blob/274fa4ac97f086d8a3eb2fcb5b3ae720a1e1ee20/Ports/iOSPort/nativeSources/CodenameOne_GLAppDelegate.m#L398)? I haven't finished my testing of this, but it seems that `localNotificationReceived` is automatically triggered when the fg notification is also triggered. However, on Android the behavior is that `localNotificationReceived` is called when the notification is _tapped_
None of my business and feel free to ignore, I will need to override anyway
