### ISSUE TITLE
How to avoid close and open keyboard in Various TexArea Components In IOS and Android

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3311]
If I have more that one TextArea Components, the Keyboard close and Open while I'm moving to next TextArea. See the video link.

https://drive.google.com/file/d/1DP1aTvtNxNJ5s9DJ8MQeW9n8BAXid6yP/view?usp=sharing
I'm using this code to move between TextAreaComponents.

    private void editNextDigit(TextArea editing, TextArea nextEditing) {
        editing.stopEditing(new Runnable() {
            @Override
            public void run() {
                //nextEditing.requestFocus();
                nextEditing.startEditingAsync();
            }
        });
        editing.getParent().revalidateWithAnimationSafety();
    }

**Comment by DurankGts** [comment]
this text was create in reals devices android and Ios too.

**Comment by DurankGts** [comment]
this solution provided here:  https://stackoverflow.com/questions/59811793/form-with-the-vkb-always-open/59816111#59816111 doesn't work

myForm.setFormBottomPaddingEditingMode(true);

**Comment by DurankGts** [comment]
Any solution to this issue?

**Comment by DurankGts** [comment]
some people can help me with this topic?

**Comment by DurankGts** [comment]
hello some people can help me please?

**Comment by javieranton-zz** [comment]
Hi,
1. Override pointerPressed and pointerReleased of your TextField and remove all code within
2. Install a bounds listener to your form and detect when you want to show/hide keyboard (i.e. perhaps when tapped on a textfield or when tapped on a non-textfield) and call yourt startAsync and stopEditing there

There is an example of how to install a forms bound listener in InteractionDialog.java within CN1s source code. This will work (I use this way)

I don't know, but perhaps it makes more sense to use StackOverflow for questions? Just a thought. These issues already are too littered with requests and it makes keeping a clean record of problems harder

**Comment by DurankGts** [comment]
I Can't understand your solution. The method startAsync inside close the Keyboard by default. This an issue the cn1 must to provide

**Comment by javieranton-zz** [comment]
what part do you now understand? have you looked at the code I mentioned?

**Comment by DurankGts** [comment]
Overriting the methods in the TextArea but I can't understand the purpose of to install bounds listener to detect show/hide keyboard. Could you provide an example please?

**Comment by DurankGts** [comment]
private void installPointerOutOfBoundsListeners() {
        
        final Form f = getComponentForm();
        if (f != null) {
            if (pressedListener == null) {
                pressedListener = new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent evt) {
                        if (disposed) {
                            f.removePointerPressedListener(pressedListener);
                            f.removePointerReleasedListener(releasedListener);
                            return;
                        }
                        pressedOutOfBounds = disposeWhenPointerOutOfBounds && 
                                !getContentPane().containsOrOwns(evt.getX(), evt.getY()) &&
                                !getTitleComponent().containsOrOwns(evt.getX(), evt.getY())
                                ;
                        if (pressedOutOfBounds && disposeWhenPointerOutOfBounds) {
                            evt.consume();
                        }
                    }
                };
            }
            if (releasedListener == null) {
                releasedListener = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent evt) {
                        if (disposed) {
                            f.removePointerPressedListener(pressedListener);
                            f.removePointerReleasedListener(releasedListener);
                            return;
                        }
                        if (disposeWhenPointerOutOfBounds && 
                                pressedOutOfBounds && 
                                !getContentPane().containsOrOwns(evt.getX(), evt.getY()) &&
                                !getTitleComponent().containsOrOwns(evt.getX(), evt.getY())) {
                            evt.consume();
                            f.removePointerPressedListener(pressedListener);
                            f.removePointerReleasedListener(releasedListener);
                            dispose();
                        }
                    }
                };
            }
            f.addPointerPressedListener(pressedListener);
            f.addPointerReleasedListener(releasedListener);
            
        }
    }

**Comment by DurankGts** [comment]
this the issue tha cn1 must to implement a way to avoid close every time that start editing

![image](https://user-images.githubusercontent.com/16245755/100659942-b8142080-3327-11eb-8c32-13ce1fd3f9e8.png)

**Comment by javieranton-zz** [comment]
I agree with you that TextArea needs to be improved, but CN1 seems to be overrun with requests so in the meantime the best we can do is try to hack our way through ourselves. Unfortunately this feel like building on a crooked tower but I feel for CN1 because they've accomplished so much with so little and their product is really amazing. To be fair android's keyboard implementation is very buggy to start with so layering CN1 over it is bound to cause many edge cases

What you need to do in the listener is this:

    if(myTextField.containsOrOwns(evt.getX(), evt.getY()))
       myTextField.startEditingAsync();
    else
       myTextField.stopEditing();//this is just in case you want to close when tapped away

You can expand this logic to do many things, this is just an example. I think that once you've done this your keyboard will stay on, it does for me. Don;t forget to keep the TextField's pressed events nice and empty!

Here is my full logic, lots of it won't make any sense to you but it's the best I can do with my limited time 👍 

    private void installPointerOutOfBoundsListeners() {
        Utils.getInstance().onKeyboardHidden = () -> {
            if(!unfocused && msgField.getLines() > 1)
            {
                msgField.getAllStyles().setMargin(Component.BOTTOM, 2);
                meRef.revalidate();
            }
        };
        final Form f = getComponentForm();
        if (f != null) {
            if (pressedListener == null) {
                pressedListener = new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent evt) {
                       ignoreReleased = false;
                        if(!finalCnt.containsOrOwns(evt.getX(), evt.getY()))//tapped away from extendedTextField
                        {
                            pressedInsideOfBounds = false;
                            if(!msgField.isSingleLineTextArea())
                            {
                                unfocused = true;
                                ignoreReleased = true;
                                if(msgField.getLines() <= 1)
                                    msgField.getAllStyles().setMargin(Component.BOTTOM, 0);
                                else
                                    msgField.getAllStyles().setMargin(Component.BOTTOM, 2);
                                setGrayLine.run();
                                meRef.revalidate();
                                //BUG FIX: On Android, when we tap away from multiline txtField whose cursor wasn't at the end, and type more keys the last lines gets duplicated. Added this to prevent (just stop editing)
                                //on android, stop editing when unfocused and cursor isnt' at end
                                //https://github.com/codenameone/CodenameOne/issues/3316
                                if(isAnd)
                                    EasyThread.start(Utils.getInstance().getRandomIV()).run(()->{
                                        try{Thread.sleep(100);}catch(Exception e){}//need to postpone 100 millis because cursor position isn't immediately available
                                        if(msgField.getText().length() != msgField.getCursorPosition())
                                            msgField.stopEditing();
                                    });
                            }
                        }
                        else if(!btnsCnt.containsOrOwns(evt.getX(), evt.getY()))//tapped on ExtendedTextField but not on its buttons
                        {
                            pressedInsideOfBounds = true;
                            if(!msgField.isSingleLineTextArea())
                            {
                                unfocused = false;
                                ignoreReleased = true;
                                setBlueLine.run();
                                if(isAnd)
                                    msgField.getAllStyles().setMargin(Component.BOTTOM, 0);
                                else if(getPlatformName().equals("ios"))
                                    msgField.getAllStyles().setMargin(Component.BOTTOM, 2);
                                if(isChatTextField && !Utils.getInstance().isKeyboardShown)
                                {
                                        //START SCROLL LAST BUBBLE TO ABOVE KEYBOARD IF IT WAS IN VIEW
                                        List<Component> cmps = ChatUtils.chatRoomBoxCenter.getChildrenAsList(true);
                                        Component lastCmp = cmps.get(cmps.size() - 1);
                                        //if last item is in second half of screen, scroll all to bottom
                                        int originalItemAbsY = lastCmp.getAbsoluteY();
                                        int originalTextFieldAbsY = meRef.getAbsoluteY();
                                        if(originalItemAbsY < originalTextFieldAbsY)
                                        {
                                            //keep detecting keyboard inout until shown or until n retried
                                            EasyThread.start(Utils.getInstance().getRandomIV()).run(()->{
                                                int retries = 0;
                                                while(originalTextFieldAbsY == meRef.getAbsoluteY() && retries < 50)
                                                {
                                                    try
                                                    {
                                                        Thread.sleep(20);
                                                    }catch(Exception ex){}
                                                    retries++;
                                                }
                                                Display.getInstance().callSerially(()->{
                                                    com.codename1.ui.ScrollMe.setDisableSmoothScrolling(true);
                                                    com.codename1.ui.ScrollMe.scrollComponentToNearlyVisible(ChatUtils.chatRoomBoxCenter,lastCmp);
                                                    com.codename1.ui.ScrollMe.setDisableSmoothScrolling(false);
                                                });
                                            });
                                    }
                                    //END
                                }
                                meRef.revalidate();
                                msgField.startEditingAsync();
                            }
                        }
                    }
                };
            }
            if (releasedListener == null) {
                releasedListener = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent evt) {
                        if(ignoreReleased)
                        {
                            ignoreReleased = false;
                            return;
                        }
                        if(btnsCnt.containsOrOwns(evt.getX(), evt.getY()))
                            ;
                        else if (pressedInsideOfBounds && finalCnt.containsOrOwns(evt.getX(), evt.getY())) {
                            try
                            {
                                unfocused = false;
                                setBlueLine.run();
                                meRef.revalidate();
                                msgField.startEditingAsync();
                            }catch(Exception e){}
                        }else if(!pressedInsideOfBounds)
                        {
                            if(!unfocused)
                            {
                                try
                                {
                                    unfocused = true;
                                    setGrayLine.run();
                                    if(!msgField.isSingleLineTextArea())
                                    {
                                        if(msgField.getLines() > 1)
                                            msgField.getAllStyles().setMargin(Component.BOTTOM, 2);
                                        else if(isIOS && isTablet && msgField.getLines() <= 1)
                                            msgField.setRows(1);
                                    }
                                    //if tapped away from ExtendedTxtxField && not tapped one of its buttons
                                    //if released on another box but not this one, stop editing
                                    if(f.getComponentAt(evt.getX(), evt.getY()) instanceof TextArea && f.getComponentAt(evt.getX(), evt.getY()) != msgField)
                                    {
                                        msgField.stopEditing();
                                        ((TextArea)f.getComponentAt(evt.getX(), evt.getY())).startEditingAsync();
                                    }else if(f.getComponentAt(evt.getX(), evt.getY()) instanceof CustomContainer && f.getComponentAt(evt.getX(), evt.getY()) != encapsulateMsgFieldCnt)
                                    {
                                        msgField.stopEditing();
                                        ((CustomContainer)f.getComponentAt(evt.getX(), evt.getY())).getChildrenAsList(true).get(0).startEditingAsync();
                                    }
                                    //if(f.getComponentAt(evt.getX(), evt.getY()) != msgField && f.getComponentAt(evt.getX(), evt.getY()) != encapsulateMsgFieldCnt)
                                    //    msgField.stopEditing();
                                }catch(Exception e){}
                                meRef.revalidate();
                            }
                        }
                    }
                };
            }
            f.addPointerPressedListener(pressedListener);
            f.addPointerReleasedListener(releasedListener);
            f.addShowListener(l->{
                if(firstShown && !firstText.isEmpty())
                    setText(firstText);
                firstShown = false;
            });
        }
    }

**Comment by javieranton-zz** [comment]
Actually, I realised my solution works some times, but not always. I was looking through the native code and came across this
    Display.getInstance().setProperty("android.reuseTextEditorOnSwitch", "true");

Unfortunately, it also doesn't work. In fact it crashed my app

I have to conclude that I agree with you, CN1 needs to offer a way to prevent the keyboard from hiding and coming back when fields are changed

The following (taken from ClearableTextField) also needs to stop hiding the keyboard. It just looks bad. Some fields just shouldn't cause the keyboard to hide when they are done/switched. There needs to be a way to keep the keyboard and the editing on in Android

    txtField.stopEditing();
    txtField.setText("");
    txtField.startEditingAsyn();

@shai-almog @shannah

**Comment by javieranton-zz** [comment]
OK, I found the bit of native code that causes this. I will create a pull request with a fix once I've tested everything works ok

**Comment by javieranton-zz** [comment]
@DurankGts using `Display.getInstance().setProperty("android.reuseTextEditorOnSwitch", "true");` should be enough for you in your case (switching fields) I think. I still need to implement a fix that will stop re-showing the keyboard for when fields are cleared, but if you are just switching between fields setting that flag to `true` should be enough. Don't implement the listeners I told you earlier because that will break this flag's functionality

**Comment by javieranton-zz** [comment]
Pull request created... @shai-almog pls merge so we can start taking advantage of this #3318

**Comment by DurankGts** [comment]
@shai-almog this pull request have been include in your build server ?

**Comment by javieranton-zz** [comment]
Hi @DurankGts . The PR is https://github.com/codenameone/CodenameOne/pull/3319

Shai said that Steve would review it after he comes back from his holidays. Let's hope it gets added soon :)

**Comment by shannah** [comment]
Note: I have closed this pull request and committed a generalized fix that addresses the issue raised in the pull request.  The fix for that is https://github.com/codenameone/CodenameOne/commit/cdaaf8ed81fac6c2c8d4bcfef0ede120625649a1

However, that fix does not address this issue.   

I believe the solution to your issue, as mentioned by @javieranton-zz (https://github.com/codenameone/CodenameOne/issues/3311#issuecomment-736790252) is:

> @DurankGts using Display.getInstance().setProperty("android.reuseTextEditorOnSwitch", "true"); should be enough for you in your case (switching fields) ...

@DurankGts Can you confirm that that flag fixes the issue for you?

**Comment by soufianemaadour** [comment]
i am in the same situation, but i cant figure out how to use the solution you offered @javieranton-zz  in my following code :
 private void automoveToNext( TextArea current,  TextArea next) {
         current.addDataChangedListener(new DataChangedListener() {
            public void dataChanged(int type, int index) {
                if (current.getText().length() == 1) {
                    next.startEditing();
                   
                }

            }
        });
}

**Comment by DurankGts** [comment]
@shannah yes this solutions it work perfectly.
