### ISSUE TITLE
how to change ios toolbar based to the Form appareance in cn1?

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3315]
Please provide a way to do ít?

**Comment by DurankGts** [comment]
...

**Comment by shai-almog** [comment]
This issue is very unclear

**Comment by DurankGts** [comment]
it's very important that you add support to custom the ios toolbar by view controler appareance.

Dark mode
![image](https://user-images.githubusercontent.com/16245755/100868789-7e9bfc00-3472-11eb-8f0e-bffa48ba529d.png)

light mode
![image](https://user-images.githubusercontent.com/16245755/100868827-8c518180-3472-11eb-9abd-aebc79383d83.png)

apple pemitt to custom this bar in all application and by view controller because some times we have entire background with background similar to the ios toolbar style. for example this

![image](https://user-images.githubusercontent.com/16245755/100869230-1d285d00-3473-11eb-9919-41b44f7738c6.png)

but in my application I could have other forms with light background like this:

![image](https://user-images.githubusercontent.com/16245755/100869305-42b56680-3473-11eb-9ae0-37a3058b2a3c.png)

you can add support with this docs: https://sarunw.com/posts/how-to-set-status-bar-style/#:~:text=If%20you%20want%20to%20change,status%20bar%20is%20black%20text.

https://www.ryadel.com/en/xcode-set-status-bar-style-and-color-in-objective-c/

In my case I implemented a native interface with this method.

Cn1 side:


1- add this method to your native interface class

public void setToolBarColor(int type);


2- create a method in your utils class

    public static String setToolBarColor(int type){

        try {
            NativeCalls nc = (NativeCalls) NativeLookup.create(NativeCalls.class);
            if (nc != null) {

                if (nc.isSupported()) {
                    nc.setToolBarColor(type);
                } 
            }

        } catch (ClassCastException e) {
            Log.e(TAG, "Error1:" + e.toString());
        }  catch (Exception e) {
            Log.e(TAG, "Error2:" + e.toString());
        }
        return model;
    }
    //--------------------------------------------------------------------------
3- create an interface with the values of the ios style
public interface IosToolBarStyle {
    
    int DEFAULT = 0;
    int LIGHT = 1;
    int DARK = 3;

}

4- add this built hint in your codenameone_settings.properties

codename1.arg.ios.plistInject=<key>UIViewControllerBasedStatusBarAppearance</key><false/><key>UIStatusBarStyle</key> <string>UIStatusBarStyleDarkContent</string>

codename1.arg.ios.viewDidLoad=[self setNeedsStatusBarAppearanceUpdate];


objetive c side:

1-add this code

-(void) setToolBarColor : (int) type {
    dispatch_async(dispatch_get_main_queue(), ^{

        /*
         *      See: https://developer.apple.com/documentation/uikit/uistatusbarstyle?language=objc
                    UIStatusBarStyleDefault     : 0; A dark status bar, intended for use on light backgrounds.
                    UIStatusBarStyleLightContent: 1; A light status bar, intended for use on dark backgrounds.
                    UIStatusBarStyleDarkContent : 3; A dark status bar, intended for use on light backgrounds.
         */
        switch (type) {
            case 0:
            case 1:
            case 3:
                [[UIApplication sharedApplication] setStatusBarStyle : type];
            break;

        }
    });
}
//------------------------------------------------------------------------------

next that you have created your native method to custom your ios tool bar by any forms, just call this after your form have  showed

      myForm.addShowListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                Utils.setToolBarColor(IosToolBarStyle.DARK); // or light
              }
        });

**Comment by DurankGts** [comment]
this work perfectly in this moment to me but you must to implement @shannah in you code.
