### ISSUE TITLE
(Android) PICKER_TYPE_DATE_AND_TIME Picker shows date - 1 day when editing

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3325]
This is a strange one. I could have sworn that this wasn't happening before, but I don't see any change affecting the Picker in the commits. The following minimal code reproduces the issue:

            Form hi = new Form("Test", new BorderLayout());
            Container center = new Container(BoxLayout.y());
            Picker startDateTimePicker = new Picker();
            startDateTimePicker.setType(Display.PICKER_TYPE_DATE_AND_TIME);
            startDateTimePicker.setDate(new Date());
            center.add(startDateTimePicker);
            hi.add(BorderLayout.CENTER, center);
            hi.show();

Using this code, when the picker displays the following example date:
<img src="https://user-images.githubusercontent.com/11293898/101803277-3df25180-3b08-11eb-9058-1470d5daa839.png"  width="200">
It then shows this other date when tapped and starting to edit:
<img src="https://user-images.githubusercontent.com/11293898/101803096-126f6700-3b08-11eb-8d02-830368c9e09e.png"  width="200">

From what I have seen, it doesn't always happen. I would say 90% of times. Race condition?

**Comment by javieranton-zz** [comment]
I know we are in code freeze but it would be great if this very small issue could be fixed. I've pasted very detailed code on how to reproduce here. I tried fixing myself but unfortunately couldn't figure it out. Perhaps the person who first developed this one can help more...

**Comment by javieranton-zz** [comment]
Up

**Comment by javieranton-zz** [comment]
As of today, this is still happening

**Comment by shannah** [comment]
Is this only happening in Android, or can you reproduce it in the simulator?

**Comment by shannah** [comment]
Tried this test case today and couldn't reproduce it. I also stepped through the code and wasn't able to identify where this would be happening.  Could be timezone related.  Tried in a few different timezones with no results.

**Comment by javieranton-zz** [comment]
https://user-images.githubusercontent.com/11293898/143045753-e460b720-5999-4d80-a624-bfa1be135566.mp4

Here is the result of the code above
My time zone is UTC +00

**Comment by javieranton-zz** [comment]
@shannah 
I was able to fix this in my own version of CN1.
The problem is that the selected index of the spinner is calculated and then truncated, not rounded. Would be good to fix in CN1's code. The line [here](https://github.com/codenameone/CodenameOne/blob/4f0817d7ad10af880b6c1836f267ae947cf903b3/CodenameOne/src/com/codename1/ui/spinner/SpinnerDateModel.java#L125) needs to be changed from 
```
int out = (int)((currentValue - min) / DAY);
```
to
```
int out = (int) Math.round((new Long(this.currentValue).doubleValue() - new Long(this.min).doubleValue()) / new Long(DAY).doubleValue());
```

Testing this requires choosing dates in the future incrementally, one day at a time. Because of how the value is truncated, depending on the time of day different results will be obtained too. But the above code fixes this teething issue

**Comment by javieranton-zz** [comment]
Actually scrap this.  The error still persists (now adding a day instead of subtracting)

**Comment by javieranton-zz** [comment]
I managed to fix this but the solution is ugly and not worth sharing. Basically, I runs an extra check to see if the date is as intended and if it isn't it moves the date to +-1 day as needed before showing the dialog
