### ISSUE TITLE
"Control Center" layout issue

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3333]
The new "Control Center" is very nice and a lot more readable!

However, the box "Questions? Chat with us" is over the last items on the left, so the Enterprise menu and/or other items in that portion of the screen are not clickable. I attach a screenshot.

![ControlCenter](https://user-images.githubusercontent.com/1997316/103138618-9747ac80-46d4-11eb-8d9c-0b079b7036fa.png)

**Comment by chen-fishbein** [comment]
thanks! fixed this for the next update
