### ISSUE TITLE
Please hide email addresses in blog comments

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3338]
Happy New Year!

Today I posted this comment on the blog:
https://www.codenameone.com/blog/codename-one-control-center-desktop-app.html#comment-24369

but I didn't realize that posting a comment involved exposing my email address (with all the possible consequent spam problems).

I would ask you as soon as possible to hide the email addresses in the comments. It would be more sensible that instead of my email address there was my name and surname.

Thank you!

_Additional question: when I posted the comment, was there an option to hide or show the email address and/or first or last name? Maybe I didn't pay attention to it...._

**Comment by shai-almog** [comment]
To you too. We've been working on this for a while and it might work for your particular case if you post again (since I manually edited your mirrored user). This is a bit harder to do right now. I can delete that comment for now if you would like?

**Comment by shai-almog** [comment]
I was able to fix that specific comment so no need to delete it.

**Comment by jsfan3** [comment]
Thank you very much!

**Comment by shai-almog** [comment]
This should be resolved now for all users.
