### ISSUE TITLE
Videos captured on iOS can't be played on Android native player

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3341]
The issue is specifically with Android Samsung native player (as tested)

When producing a video from iOS via the `Capture` API, no matter the settings used (low/high quality, different resolutions, etc) they then can't be played on a Samsung Android phone when using the native video player. 

It does work if a separate Android application is chosen (VLC, etc)

Does anyone know how to fix this?

I know it's very device-specific, feel free to close if necessary

**Comment by jsfan3** [comment]
iOS records movies in QuickTime format (with MOV extension), Android records them in H264 format (with MP4 extension).

At the playback level, iOS supports movies recorded with Android, but the reverse is not true, at least at the native media player level. VLC and other external programs support more codecs than those natively supported by Android. In fact, Android doesn't support quicktime videos by default (source: https://www.easefab.com/topic-mov/play-mov-files-on-android.html)

In my case, I solved the problem by uploading the movies to my Spring Boot server as recorded by the phones, but then downloading them only in MP4 format (conversion from QuickTime to H.264 is done server-side on-the-fly, via Cloudinary).

This solution is only applicable for small movies, on the Cloudinary documentation there are limits in megabytes to perform a conversion on the fly. Alternatively, you can convert the video in advance. Documentation: https://cloudinary.com/documentation/video_manipulation_and_delivery#video_trans_overview

Of course you can also use Cloudinary directly from your Codename One application, there is also a dedicated cn1lib that you can install form the Control Center (I don't know how much this cn1lib is updated): https://github.com/shannah/cloudinary-codenameone

**Comment by javieranton-zz** [comment]
Hi Francesco, thanks so much for coming to the rescue with this

You pointed me in the right direction, but I wanted to avoid third-partys. So I did a little session of wall banging with my head today and came up with the following, which re-encodes the video capture from the Capture API (mp4 with mov) to the correct Android format for mp4

No need for third part cloudinary - happy days!

The important bits are `presetName:mp4Quality` and `AVAssetExportPresetPassthrough`

`- (void)encodeVideo:(NSURL *)videoURL
{
    AVURLAsset *asset = [[AVURLAsset alloc] initWithURL:videoURL options:nil];

    // Create the composition and tracks
    AVMutableComposition *composition = [AVMutableComposition composition];
    AVMutableCompositionTrack *videoTrack = [composition addMutableTrackWithMediaType:AVMediaTypeVideo preferredTrackID:kCMPersistentTrackID_Invalid];
    AVMutableCompositionTrack *audioTrack = [composition addMutableTrackWithMediaType:AVMediaTypeAudio preferredTrackID:kCMPersistentTrackID_Invalid];
    NSArray *assetVideoTracks = [asset tracksWithMediaType:AVMediaTypeVideo];
    if (assetVideoTracks.count <= 0)
    {
            NSLog(@"Error reading the transformed video track");
            return NO;
    }

    // Insert the tracks in the composition's tracks
    AVAssetTrack *assetVideoTrack = [assetVideoTracks firstObject];
    [videoTrack insertTimeRange:assetVideoTrack.timeRange ofTrack:assetVideoTrack atTime:CMTimeMake(0, 1) error:nil];
    [videoTrack setPreferredTransform:assetVideoTrack.preferredTransform];

    AVAssetTrack *assetAudioTrack = [[asset tracksWithMediaType:AVMediaTypeAudio] objectAtIndex:0];
    [audioTrack insertTimeRange:assetAudioTrack.timeRange ofTrack:assetAudioTrack atTime:CMTimeMake(0, 1) error:nil];

    // Export to mp4
    NSString *mp4Quality = AVAssetExportPresetPassthrough;
    NSFileManager *manager = [NSFileManager defaultManager];
    // Remove Existing File
    [manager removeItemAtPath:videoURL error:nil];

    NSURL *exportUrl = videoURL;//[NSURL fileURLWithPath:exportPath];
    AVAssetExportSession *exportSession = [[AVAssetExportSession alloc] initWithAsset:composition presetName:mp4Quality];
    exportSession.outputURL = exportUrl;
    CMTime start = CMTimeMakeWithSeconds(0.0, 0);
    CMTimeRange range = CMTimeRangeMake(start, [asset duration]);
    exportSession.timeRange = range;
    exportSession.outputFileType = AVFileTypeMPEG4;
    dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
    [exportSession exportAsynchronouslyWithCompletionHandler:^{
            switch ([exportSession status])
            {
                case AVAssetExportSessionStatusCompleted:
                {
                     break;
                 }
                case AVAssetExportSessionStatusFailed:
                {
                        break;
                }
                case AVAssetExportSessionStatusCancelled:
                {
                       NSLog(@"Export canceled");
                       break;
                }
                default:
                {
                       break;
                }
            }
            dispatch_semaphore_signal(semaphore);
    }];
    if (![NSThread isMainThread]) {
        dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
    } else {
        while (dispatch_semaphore_wait(semaphore, DISPATCH_TIME_NOW)) { 
            [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:0]]; 
        }
    }
}`

**Comment by javieranton-zz** [comment]
@shannah @shai-almog perhaps CN1's video capture API can be tweaked to produce Android-compatible iOS videos with the above, for now I will close this issue
