### ISSUE TITLE
[BUG] Multiline Textfield Jumps To Beginning of Field Randomly

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#3343]
Just recently (after I created/installed a new apk), when typing in a multiline textfield, the cursor will randomly jump to the beginning of the field. It doesn't seem to happen on the simulator, but it happens on my Android testing phone. Doesn't seem to be happening on my iPhone. Code below creates form that can replicate the issue (it doesn't happen every single time, but it happens a lot):

```
Form f = new Form(BoxLayout.yCenter());
TextField tf = new TextField("", "Enter here");
tf.setSingleLineTextArea(false);
f.add(tf);        
f.show();    
```

Attached video shows what is happening. 

https://user-images.githubusercontent.com/25064795/104112783-6a8cbb00-52b8-11eb-983f-e134d07c0ed8.mp4

**Comment by shannah** [comment]
This fix will be part of deployment on Friday.
