### ISSUE TITLE
[BUG] HTTP headers do not support the new line character ('\n') nor the standard sequence ("\r\n")

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3345]
First of all, new lines characters are allowed in http headers: https://stackoverflow.com/a/5757349/1277576
The correct sequence is "\r\n", but "\n" is also permissible.

Codename One doesn't support '\n' character in http headers nor the standard sequence "\r\n": I don't know if this restriction is intentional or not. There are some cases where allowing the '\n' character increases the readability of http headers during debugging (when reading requests sent through the Network Monitor). E.g., a JSON inside an http header is much more readable if formatted with new lines. 

On the server side, I use Spring Boot: I'm not sure if Spring Boot correctly interprets '\n' in http headers, but I hope so. In any case, "\r\n" is a standard.

Test case:
```
Form hi = new Form("Hi World", BoxLayout.y());
Button workingBtn = new Button("Working");
Button bugBtn = new Button("Bug \\n");
Button bugBtn2 = new Button("Bug \\r\\n");
hi.addAll(workingBtn, bugBtn, bugBtn2);
hi.show();

Map<String, String> map = new LinkedHashMap<>();
map.put("key1", "value1");
map.put("key2", "value2");
map.put("key3", "value3");

String json = JSONParser.mapToJson(map);
Log.p("JSON:\n" + json, Log.DEBUG);

workingBtn.addActionListener(l -> {
    Rest.get("https://www.google.com/search")
    .jsonContent()
    .header("header1", "headerValue1")
    .header("header2", "headerValue2")
    .header("headerJSON", json.replace('\n', ' '))
    .queryParam("q", "this is just an example...")
    .fetchAsBytes((Response<byte[]> response) -> {
Log.p("HTTP Response code: " + response.getResponseCode(), Log.INFO);
    });
});

bugBtn.addActionListener(l -> {
    Rest.get("https://www.google.com/search")
    .jsonContent()
    .header("header1", "headerValue1")
    .header("header2", "headerValue2")
    .header("headerJSON", json)
    .queryParam("q", "this is just an example...")
    .fetchAsBytes((Response<byte[]> response) -> {
Log.p("HTTP Response code: " + response.getResponseCode(), Log.INFO);
    });
});

bugBtn2.addActionListener(l -> {
    Rest.get("https://www.google.com/search")
    .jsonContent()
    .header("header1", "headerValue1")
    .header("header2", "headerValue2")
    .header("headerJSON", StringUtil.replaceAll(json, "\n", "\r\n"))
    .queryParam("q", "this is just an example...")
    .fetchAsBytes((Response<byte[]> response) -> {
Log.p("HTTP Response code: " + response.getResponseCode(), Log.INFO);
    });
});
```

**Comment by shannah** [comment]
My understanding is that line-breaks are not allowed in HTTP headers, except to serve as a delimiter between separate headers.  I think that SO post is discussing whether to use \r\n or \n headers as those delimiters.

**Comment by jsfan3** [comment]
Thank you for your response. I investigated this issue further, and in short, you are right.
A detailed discussion on this topic can be found here:
https://github.com/postmanlabs/postman-app-support/issues/4485
In particular:
https://github.com/postmanlabs/postman-app-support/issues/4485#issuecomment-449689450

So, ultimately, there is no need to change the behavior of Codename One.
