### ISSUE TITLE
Emojis saved in SQLite DB cannot be added to TextField in iOS

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#3347]
After saving a string with emojis to a sqlite db, they can be read back and added to a label, but not to a textfield. It doesn't error, the textfield just shows up as blank. Only happens on iOS, works fine in Android/Simulator. 

Below are the helper functions/code to reproduce the issue. The form shows the emojis working fine within a label, but the textfield they should be added to just shows up as blank on an iPhone. (My apologies for the formatting below, github doesn't want to work with me).

public void createTestDB() 
    {
        Database db = null;
        Cursor cur = null;
        try {
            db = Display.getInstance().openOrCreate("testEmoji.db");
            //db.execute("DROP TABLE IF EXISTS TestLines");
            db.execute("CREATE TABLE IF NOT EXISTS TestLines (AutoID INTEGER PRIMARY KEY ASC, TestString varchar)");
            db.execute("INSERT INTO TestLines (TestString) VALUES('😁😏👌')");
        } catch (IOException err) {
            Log.e(err);
        } finally {
            Util.cleanup(db);
            Util.cleanup(cur);
        }
    }

    public String getTestEmojiStringFromDB() {
        String returnString = "";
        String query = "SELECT TestString FROM TestLines ORDER BY AutoID DESC LIMIT 1";
        Database db = null;
        Cursor cur = null;
        try {
            db = Display.getInstance().openOrCreate("testEmoji.db");
            cur = db.executeQuery(query);
            boolean next = cur.next();
            if (next) {
                while (next) {
                    Row currentRow = cur.getRow();
                    returnString = currentRow.getString(0);
                    next = cur.next();
                }
            }
        } catch (IOException err) {
            Log.e(err);
        } finally {
            Util.cleanup(db);
            Util.cleanup(cur);
        }
        return returnString;
    }

public void start() {
Form f = new Form(BoxLayout.yCenter());

createTestDB();
String lastEntry = getTestEmojiStringFromDB();

Label l = new Label(lastEntry);
TextField tf = new TextField(lastEntry);
f.add(l);
f.add(tf);
        
f.show();   
}

**Comment by javieranton-zz** [comment]
Hi there, 

iOS uses a different charset. Do this to fix your issue:

Before saving anything to SqlLite, run the to-be-saved string through the following method. This will translate your iOS non-UTF-8 emojis to unicode representations, which are compatible with SQLite and java itself

    public static String escapeUnicode(String originalText){
        StringBuffer stringBuffer = new StringBuffer();
        for (int i = 0; i < originalText.length(); i++) {
            char c = originalText.charAt(i);
            if (c < 128) {
                stringBuffer.append(c);
            } else if (c < 256) {
                stringBuffer.append(c);
            } else {
                String hex = Integer.toHexString(c);
                while(hex.length() < 4)
                    hex = "0" + hex;
                stringBuffer.append("\\u");
                stringBuffer.append(hex);
            }
        }
        return stringBuffer.toString();
        //return originalText;
    };

Then, after you read a string from your SqlLite, to ensure your emojis are correctly displayed, pass the read string through the following before putting them in your textfields:

    //returns string with emojis instead of with \u0123 etc
    //which means: unescapes escaped octals and unicode
    public String unescapeJavaString(String st) {

        StringBuilder sb = new StringBuilder(st.length());

        for (int i = 0; i < st.length(); i++) {
            char ch = st.charAt(i);
            if (ch == '\\') {
                char nextChar = (i == st.length() - 1) ? '\\' : st
                        .charAt(i + 1);
                // Octal escape?
                if (nextChar >= '0' && nextChar <= '7') {
                    String code = "" + nextChar;
                    i++;
                    if ((i < st.length() - 1) && st.charAt(i + 1) >= '0'
                            && st.charAt(i + 1) <= '7') {
                        code += st.charAt(i + 1);
                        i++;
                        if ((i < st.length() - 1) && st.charAt(i + 1) >= '0'
                                && st.charAt(i + 1) <= '7') {
                            code += st.charAt(i + 1);
                            i++;
                        }
                    }
                    sb.append((char) Integer.parseInt(code, 8));
                    continue;
                }
                switch (nextChar) {
                case '\\':
                    ch = '\\';
                    break;
                case 'b':
                    ch = '\b';
                    break;
                case 'f':
                    ch = '\f';
                    break;
                case 'n':
                    ch = '\n';
                    break;
                case 'r':
                    ch = '\r';
                    break;
                case 't':
                    ch = '\t';
                    break;
                case '\"':
                    ch = '\"';
                    break;
                case '\'':
                    ch = '\'';
                    break;
                // Hex Unicode: u????
                case 'u':
                    if (i >= st.length() - 5) {
                        ch = 'u';
                        break;
                    }
                    int code = Integer.parseInt(
                            "" + st.charAt(i + 2) + st.charAt(i + 3)
                                    + st.charAt(i + 4) + st.charAt(i + 5), 16);
                    sb.append(Character.toChars(code));
                    i += 5;
                    continue;
                }
                i++;
            }
            sb.append(ch);
        }
        return sb.toString();
    }

If you save & display everything using these 2 methods you will also ensure Android-iOS emoji compatibility, no matter who created the unicode character first

**Comment by rochanas** [comment]
Thanks very much Javier - that fixes the problem!

**Comment by javieranton-zz** [comment]
Welcome, glad I could help!
