### ISSUE TITLE
SIMULATOR ERROR ISSUE

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3350]
please help me with this issue. I need to compile my app with your source code javaSE

ant -q -f F:\\data_kdp\\programs\\CodenameOne\\ws_codenameone\\CodenameOne\\Ports\\JavaSE -Dnb.internal.action.name=rebuild clean jar
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
Init env executing with cn1env = ${cn1env} for ../../CodenameOne/GUIBuilder/src
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
warning: [options] bootstrap class path not set in conjunction with -source 1.7
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:29: error: package javax.media does not exist
import javax.media.AudioDeviceUnavailableEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:30: error: package javax.media does not exist
import javax.media.ConnectionErrorEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:31: error: package javax.media does not exist
import javax.media.Controller;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:32: error: package javax.media does not exist
import javax.media.ControllerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:33: error: package javax.media does not exist
import javax.media.ControllerErrorEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:34: error: package javax.media does not exist
import javax.media.DataLostErrorEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:35: error: package javax.media does not exist
import javax.media.EndOfMediaEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:36: error: package javax.media does not exist
import javax.media.InternalErrorEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:37: error: package javax.media does not exist
import javax.media.Player;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:38: error: package javax.media does not exist
import javax.media.ResourceUnavailableEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:39: error: package javax.media does not exist
import javax.media.StartEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:40: error: package javax.media does not exist
import javax.media.StopEvent;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:41: error: package javax.media does not exist
import javax.media.Time;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\JavaJMFSEPort.java:115: error: cannot find symbol
        private Player player;
  symbol:   class Player
  location: class JavaJMFSEPort.CodenameOneMediaPlayer
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:9: error: cannot find symbol
import org.cef.CefApp;
  symbol:   class CefApp
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:10: error: package org.cef.CefApp does not exist
import org.cef.CefApp.CefAppState;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:11: error: cannot find symbol
import org.cef.browser.CefBrowser;
  symbol:   class CefBrowser
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:12: error: cannot find symbol
import org.cef.browser.CefFrame;
  symbol:   class CefFrame
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:13: error: package org.cef.callback does not exist
import org.cef.callback.CefSchemeHandlerFactory;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:14: error: package org.cef.callback does not exist
import org.cef.callback.CefSchemeRegistrar;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:15: error: package org.cef.handler does not exist
import org.cef.handler.CefAppHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:16: error: package org.cef.handler does not exist
import org.cef.handler.CefResourceHandler;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:17: error: package org.cef.network does not exist
import org.cef.network.CefRequest;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:19: error: cannot find symbol
public class AppHandler extends CefAppHandlerAdapter  {
  symbol: class CefAppHandlerAdapter
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:99: error: cannot find symbol
    public void onRegisterCustomSchemes(CefSchemeRegistrar registrar) {
  symbol:   class CefSchemeRegistrar
  location: class AppHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:164: error: cannot find symbol
    public void stateHasChanged(CefAppState state) {
  symbol:   class CefAppState
  location: class AppHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:149: error: cannot find symbol
    private class SchemeHandlerFactory implements CefSchemeHandlerFactory {
  symbol:   class CefSchemeHandlerFactory
  location: class AppHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:152: error: cannot find symbol
                CefBrowser browser, CefFrame frame, String schemeName, CefRequest request) {
  symbol:   class CefBrowser
  location: class AppHandler.SchemeHandlerFactory
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:152: error: cannot find symbol
                CefBrowser browser, CefFrame frame, String schemeName, CefRequest request) {
  symbol:   class CefFrame
  location: class AppHandler.SchemeHandlerFactory
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:152: error: cannot find symbol
                CefBrowser browser, CefFrame frame, String schemeName, CefRequest request) {
  symbol:   class CefRequest
  location: class AppHandler.SchemeHandlerFactory
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\AppHandler.java:151: error: cannot find symbol
        public CefResourceHandler create(
  symbol:   class CefResourceHandler
  location: class AppHandler.SchemeHandlerFactory
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:40: error: cannot find symbol
import org.cef.CefApp;
  symbol:   class CefApp
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:41: error: cannot find symbol
import org.cef.CefClient;
  symbol:   class CefClient
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:42: error: cannot find symbol
import org.cef.CefSettings;
  symbol:   class CefSettings
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:43: error: cannot find symbol
import org.cef.OS;
  symbol:   class OS
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:45: error: cannot find symbol
import org.cef.browser.CefBrowser;
  symbol:   class CefBrowser
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:46: error: cannot find symbol
import org.cef.browser.CefFrame;
  symbol:   class CefFrame
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:47: error: cannot find symbol
import org.cef.browser.CefMessageRouter;
  symbol:   class CefMessageRouter
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:48: error: package org.cef.handler does not exist
import org.cef.handler.CefDisplayHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:49: error: package org.cef.handler does not exist
import org.cef.handler.CefFocusHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:50: error: package org.cef.handler does not exist
import org.cef.handler.CefLifeSpanHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:51: error: package org.cef.handler does not exist
import org.cef.handler.CefLoadHandler;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:52: error: package org.cef.handler does not exist
import org.cef.handler.CefLoadHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:75: error: cannot find symbol
    private CefBrowser browser_ = null;
  symbol:   class CefBrowser
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:82: error: cannot find symbol
    private final CefClient client_;
  symbol:   class CefClient
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:332: error: cannot find symbol
    private static CefFocusHandlerAdapter createFocusHandler(BrowserPanel p) {
  symbol:   class CefFocusHandlerAdapter
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:354: error: cannot find symbol
    private static CefDisplayHandlerAdapter createDisplayHandlerAdapter(BrowserPanel p) {
  symbol:   class CefDisplayHandlerAdapter
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:378: error: cannot find symbol
    private static CefLoadHandlerAdapter createLoadHandler(BrowserPanel p) {
  symbol:   class CefLoadHandlerAdapter
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:428: error: cannot find symbol
    private static CefLifeSpanHandlerAdapter createLifespanHandler(BrowserPanel p) {
  symbol:   class CefLifeSpanHandlerAdapter
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:472: error: cannot find symbol
    public void setBrowser(CefBrowser browser) {
  symbol:   class CefBrowser
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\BrowserPanel.java:488: error: cannot find symbol
    public CefBrowser getBrowser() {
  symbol:   class CefBrowser
  location: class BrowserPanel
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\StreamWrapper.java:27: error: package org.cef.callback does not exist
import org.cef.callback.CefCallback;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\StreamWrapper.java:28: error: package org.cef.network does not exist
import org.cef.network.CefRequest;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\CEFBrowserComponent.java:24: error: cannot find symbol
import org.cef.CefApp;
  symbol:   class CefApp
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\CEFBrowserComponent.java:25: error: cannot find symbol
import org.cef.CefSettings;
  symbol:   class CefSettings
  location: package org.cef
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\CEFBrowserComponent.java:27: error: cannot find symbol
import org.cef.browser.CefBrowserFactory;
  symbol:   class CefBrowserFactory
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:15: error: package org.cef.callback does not exist
import org.cef.callback.CefCallback;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:16: error: package org.cef.handler does not exist
import org.cef.handler.CefResourceHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:17: error: package org.cef.misc does not exist
import org.cef.misc.IntRef;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:18: error: package org.cef.misc does not exist
import org.cef.misc.StringRef;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:19: error: package org.cef.network does not exist
import org.cef.network.CefRequest;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:20: error: package org.cef.network does not exist
import org.cef.network.CefResponse;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:27: error: cannot find symbol
public class ClientSchemeHandler extends CefResourceHandlerAdapter {
  symbol: class CefResourceHandlerAdapter
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:40: error: cannot find symbol
    public synchronized boolean processRequest(CefRequest request, CefCallback callback) {
  symbol:   class CefRequest
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:40: error: cannot find symbol
    public synchronized boolean processRequest(CefRequest request, CefCallback callback) {
  symbol:   class CefCallback
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:134: error: cannot find symbol
            CefResponse response, IntRef response_length, StringRef redirectUrl) {
  symbol:   class CefResponse
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:134: error: cannot find symbol
            CefResponse response, IntRef response_length, StringRef redirectUrl) {
  symbol:   class IntRef
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:134: error: cannot find symbol
            CefResponse response, IntRef response_length, StringRef redirectUrl) {
  symbol:   class StringRef
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:145: error: cannot find symbol
            byte[] data_out, int bytes_to_read, IntRef bytes_read, CefCallback callback) {
  symbol:   class IntRef
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ClientSchemeHandler.java:145: error: cannot find symbol
            byte[] data_out, int bytes_to_read, IntRef bytes_read, CefCallback callback) {
  symbol:   class CefCallback
  location: class ClientSchemeHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:14: error: cannot find symbol
import org.cef.browser.CefBrowser;
  symbol:   class CefBrowser
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:15: error: cannot find symbol
import org.cef.browser.CefFrame;
  symbol:   class CefFrame
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:16: error: package org.cef.callback does not exist
import org.cef.callback.CefContextMenuParams;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:17: error: package org.cef.callback does not exist
import org.cef.callback.CefMenuModel;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:18: error: package org.cef.callback.CefMenuModel does not exist
import org.cef.callback.CefMenuModel.MenuId;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:19: error: package org.cef.handler does not exist
import org.cef.handler.CefContextMenuHandler;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:24: error: cannot find symbol
public class ContextMenuHandler implements CefContextMenuHandler {
  symbol: class CefContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:34: error: cannot find symbol
            CefBrowser browser, CefFrame frame, CefContextMenuParams params, CefMenuModel model) {
  symbol:   class CefBrowser
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:34: error: cannot find symbol
            CefBrowser browser, CefFrame frame, CefContextMenuParams params, CefMenuModel model) {
  symbol:   class CefFrame
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:34: error: cannot find symbol
            CefBrowser browser, CefFrame frame, CefContextMenuParams params, CefMenuModel model) {
  symbol:   class CefContextMenuParams
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:34: error: cannot find symbol
            CefBrowser browser, CefFrame frame, CefContextMenuParams params, CefMenuModel model) {
  symbol:   class CefMenuModel
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:72: error: cannot find symbol
    public boolean onContextMenuCommand(CefBrowser browser, CefFrame frame,
  symbol:   class CefBrowser
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:72: error: cannot find symbol
    public boolean onContextMenuCommand(CefBrowser browser, CefFrame frame,
  symbol:   class CefFrame
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:73: error: cannot find symbol
            CefContextMenuParams params, int commandId, int eventFlags) {
  symbol:   class CefContextMenuParams
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:105: error: cannot find symbol
    public void onContextMenuDismissed(CefBrowser browser, CefFrame frame) {
  symbol:   class CefBrowser
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\ContextMenuHandler.java:105: error: cannot find symbol
    public void onContextMenuDismissed(CefBrowser browser, CefFrame frame) {
  symbol:   class CefFrame
  location: class ContextMenuHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\DragHandler.java:7: error: cannot find symbol
import org.cef.browser.CefBrowser;
  symbol:   class CefBrowser
  location: package org.cef.browser
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\DragHandler.java:8: error: package org.cef.callback does not exist
import org.cef.callback.CefDragData;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\DragHandler.java:9: error: package org.cef.handler does not exist
import org.cef.handler.CefDragHandler;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\DragHandler.java:11: error: cannot find symbol
public class DragHandler implements CefDragHandler {
  symbol: class CefDragHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\DragHandler.java:13: error: cannot find symbol
    public boolean onDragEnter(CefBrowser browser, CefDragData dragData, int mask) {
  symbol:   class CefBrowser
  location: class DragHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\DragHandler.java:13: error: cannot find symbol
    public boolean onDragEnter(CefBrowser browser, CefDragData dragData, int mask) {
  symbol:   class CefDragData
  location: class DragHandler
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:15: error: package org.cef.callback does not exist
import org.cef.callback.CefCallback;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:16: error: package org.cef.handler does not exist
import org.cef.handler.CefResourceHandlerAdapter;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:17: error: package org.cef.misc does not exist
import org.cef.misc.IntRef;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:18: error: package org.cef.misc does not exist
import org.cef.misc.StringRef;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:19: error: package org.cef.network does not exist
import org.cef.network.CefRequest;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:20: error: package org.cef.network does not exist
import org.cef.network.CefResponse;
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:27: error: cannot find symbol
public class InputStreamSchemeHandler extends CefResourceHandlerAdapter {
  symbol: class CefResourceHandlerAdapter
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\src\com\codename1\impl\javase\cef\InputStreamSchemeHandler.java:58: error: cannot find symbol
    public synchronized boolean processRequest(CefRequest request, CefCallback callback) {
  symbol:   class CefRequest
  location: class InputStreamSchemeHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
1 warning
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\nbproject\build-impl.xml:1117: The following error occurred while executing this line:
F:\data_kdp\programs\CodenameOne\ws_codenameone\CodenameOne\Ports\JavaSE\nbproject\build-impl.xml:409: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 17 seconds)

**Comment by DurankGts** [comment]
...

**Comment by DurankGts** [comment]
...

**Comment by shai-almog** [comment]
You need to use the cn1binaries project for the dependencies of JMF and JCEF.

**Comment by DurankGts** [comment]
could you provide a way how to do that?
