### ISSUE TITLE
Mime type audio/mp3 is not supported on this platform use getAvailableRecordingMimeTypes()

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3351]
this error is ocurring using simulator in method MediaManager.getAvailableRecordingMimeTypes()

**Comment by DurankGts** [comment]
some help please?

**Comment by DurankGts** [comment]
...

**Comment by DurankGts** [comment]
Mime type audio/mp3 is not supported on this platform use getAvailableRecordingMimeTypes()

**Comment by shannah** [comment]
mp3 recording is not supported by default in simulator.  You can add the [cn1mp3encoder cn1lib](https://github.com/shannah/CN1MP3Encoder) to add support for this.
