### ISSUE TITLE
On CN1 plugin 7.0 the lib *.jar are missing

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3353]
On Linux, after updating the CN1 Netbeans plugin from 6.0 to 7.0, the following files are missing every time that I create a new project:

![missingFiles](https://user-images.githubusercontent.com/1997316/106648048-09db6000-6590-11eb-9f05-bd12a1d428b3.png)

To solve, I copy them from another project.

**Comment by shai-almog** [comment]
This is a result of a change in the way the plugin works. It now runs the update process instead of packing old jars. Unfortunately the package process can fail if there's a lock file in your .codenameone directory. Make sure to delete the lock file in the home directory if it exists before creating the project.

**Comment by jsfan3** [comment]
This is the content of my `.codenameone` directory. Hidden files are shown. Is there something that I have to delete?

![codenameoneFolder](https://user-images.githubusercontent.com/1997316/106716721-0f23c380-65ff-11eb-8e44-357a80e0363e.png)

**Comment by shai-almog** [comment]
Odd. It's `UpdateStatus.lock` but that isn't here. If you run the update process on the project manually does it work or provide an error?

**Comment by jsfan3** [comment]
If I create a new project, without manually adding any files, and then I manually run the update, I get this error:

![error](https://user-images.githubusercontent.com/1997316/107081664-55da0f00-67f3-11eb-8db9-03dcf0a33a34.png)

**Comment by shai-almog** [comment]
That's very odd. I just ran an update that downloaded all files successfully. Do you have CEF installed?

**Comment by jsfan3** [comment]
I had manually enabled CEF a while back with the instructions you blogged about. I haven't been interested in it since, I don't even remember what I had done to enable it.

**Comment by shai-almog** [comment]
Please try replacing your `UpdateCodenameOne.jar` with the one from https://www.codenameone.com/files/updates/UpdateCodenameOne.jar and see if it solves the problem.

**Comment by jsfan3** [comment]
I tried. First, I verified that my version of the file was different from the one downloaded (I used `diff`).

The problem of the three missing files remains.

Running the manual update, a different error now appears, this one:

![error](https://user-images.githubusercontent.com/1997316/107120131-127faf00-688c-11eb-85fa-4081b28b6f64.png)

**Comment by shai-almog** [comment]
I think I finally see the problem. Please check now.

**Comment by jsfan3** [comment]
Now it works, the problem is solved! There are no more missing files. Thank you! :)
