### ISSUE TITLE
.codenameone/cef/lib/linux64/libjawt.so is missing

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3360]
When I try to play a video in the Simulator, I get this error:

```
java.lang.UnsatisfiedLinkError: /home/francesco/.codenameone/cef/lib/linux64/libjcef.so: libjawt.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[EDT] 0:1:42,132 - Exception: java.lang.UnsatisfiedLinkError - /home/francesco/.codenameone/cef/lib/linux64/libjcef.so: libjawt.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
```

Translated:

```
java.lang.UnsatisfiedLinkError: /home/francesco/.codenameone/cef/lib/linux64/libjcef.so: libjawt.so: unable to open shared object file: Non-existing file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[EDT] 0:1:42,132 - Exception: java.lang.UnsatisfiedLinkError - /home/francesco/.codenameone/cef/lib/linux64/libjcef.so: libjawt.so: unable to open shared object file: File or directory does not exist
```

**Comment by shai-almog** [comment]
You can probably workaround this temporarily by removing the `~/.codenameone/cef` directory and falling back to the JavaFX backend or by updating the system lib path to include a path to `libjawt.so`

**Comment by shannah** [comment]
This looks like this known issue:

https://github.com/shannah/codenameone-cef#known-issues-1

> On Ubuntu 20, and some other versions of Linux, it has been reported that, when running the Codename One simulator with CEF installed, you get UnsatisfiedLinkException mentioning that libjcef.so could not find libjawt.so. This is caused because the lib directory of the JDK is not in the LD_LIBRARY_PATH. You an work around this problem by adding it. E.g.
>
> `export LD_LIBRARY_PATH=$JAVA_HOME/lib/amd64`

**Comment by jsfan3** [comment]
I confirm that removing the ~/.codenameone/cef directory and falling back to the JavaFX workarounded this issue.

**Comment by shannah** [comment]
I would recommend the other workaround, we are moving to CEF for many things.  E.g. The CSS compiler now requires CEF for some things.

**Comment by jsfan3** [comment]
@shannah I confirm that `export LD_LIBRARY_PATH=$JAVA_HOME/lib/amd64` solved my issue but only after enabling 3D hardware acceleration (without 3D acceleration it crashes).

**Comment by shannah** [comment]
This issue is resolved in Maven, as the maven plugin will automatically add the LD_LIBRARY_PATH to the environment.
