### ISSUE TITLE
[Regression] On iOS, wrong app root for videos after app upgrade

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3362]
There is a regression (or I just discovered that the previous fix was incomplete). I refer to this commit:
https://github.com/codenameone/CodenameOne/commit/6cbc741d96a6f3607638e1f34e207e6888c8bb8e
that solved this issue:
https://github.com/codenameone/CodenameOne/issues/2551

Currently, after reinstalling an app on iOS, the images are still shown correctly, but videos are not, because the home path is not seamlessly updated. Do you remember that after reinstalling an app on iOS its home path is changed every time?

In the while, I workarounded this issue with this temporary code, that will not more necessary after a proper fix in Codename One:
```
public static Container getMediaPlayer(String videoFile) throws IOException {
        String videoFilePath;
        String homePath = FileSystemStorage.getInstance().getAppHomePath();
        if (DeviceUtilities.isiOSNative() && !videoFile.startsWith(homePath)) {
            // Small workaround for the change of home path on iOS after upgrading the app
            String myAppDir = "/Documents/app.myapp.client/";
            String relativePath = videoFile.substring(videoFile.lastIndexOf(myAppDir) + myAppDir.length());
            videoFilePath = homePath + relativePath;
        } else {
            videoFilePath = videoFile;
        }
        Log.p("Video file: " + videoFilePath + " lenght (bytes): " + FileSystemStorage.getInstance().getLength(videoFilePath), Log.DEBUG);
       
       [....]
       Media video = MediaManager.createMedia(videoFilePath, true, () -> {
       [....]
```

**Comment by shannah** [comment]
Fix will be available in Friday's update.
