### ISSUE TITLE
FileNotFoundException when opening an external file with AppArg - Android build

### ISSUE THREAD

**Issue by P5music** [codenameone/CodenameOne#3364]
I am trying to check my CodenameOne app on Android device.
The file read/write permission seems to have some problems. The user is asked about it at installation, but it does not seem to become effective for the app (some basic files are not saved on filesystem, exception is thrown)

Said that,
I am testing the file opening from the filesystem (AppArg).

When the user selects a file
from the Download folder
I see in logcat:

System.err: java.io.FileNotFoundException: file:/data/user/0/com.myapp.app/files/myfile.ext: open failed: ENOENT (No such file or directory)

(and the app seems blocked, two "activity" screens are in the "recent apps")

The app is trying to open the url from AppArg.
To reproduce it is a very simple case because just that instruction has to be put in the start() method of any test app with

codename1.arg.android.xintent_filter=<intent-filter><action android\:name\="android.intent.action.SEND" /><action android\:name\="android.intent.action.VIEW" /><action android\:name\="android.intent.action.PICK" /><category android\:name\="android.intent.category.DEFAULT" /><category android\:name\="android.intent.category.BROWSABLE" /><category android\:name\="android.intent.category.OPENABLE" /><data android\:scheme\="file" /><data android\:scheme\="content" /><data android\:mimeType\="*/*" /></intent-filter>

public void start() {
String arg=Display.getInstance().getProperty("AppArg",null);
System.out.println("arg="+arg);
if(current != null){
current.show();
return;
}

...

...

Then put a file into the Download folder and open it with some file-manager app.
I sent the Android build also for such a simple case and the issue is confirmed.

The method is called once, and then the url is null when it gets to the application, I think that
String arg=Display.getInstance().getProperty("AppArg",null);

gives the exception, then yields null.

**Comment by shannah** [comment]
Fix will be part of tomorrow's update.
