### ISSUE TITLE
CEF crashes the Simulator - Cannot communicate with zygote

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3366]
Relevant log when trying to play a video in the Simulator:

```
[EDT] 0:0:13,285 - Video file: file://home//posts/mejaGatbEpnWkuaCi4HFMC43d6TAkyOu5eVzUgWrZewHz0Jw9rIJwrLgakJtjle53bdZXpQRsQt6g36TXWrezn1u.mp4 lenght (bytes): 5968662
Using:
JCEF Version = 84.4.1.262
CEF Version = 84.4.1
Chromium Version = 84.0.4147.105
AppHandler.stateHasChanged: INITIALIZING
initialize on Thread[AWT-EventQueue-0,6,main] with library path /home/francesco/.codenameone/cef/lib/linux64
Added scheme search://
Added scheme client://
Added scheme cn1stream://
LaunchProcess: failed to execvp:
/home/francesco/.codenameone/cef/lib/linux64/jcef_helper
[0213/203759.452082:FATAL:zygote_communication_linux.cc(255)] Cannot communicate with zygote
/home/francesco/ArenApp/ArenAppClient/nbproject/build-impl.xml:1357: The following error occurred while executing this line:
/home/francesco/ArenApp/ArenAppClient/nbproject/build-impl.xml:895: The following error occurred while executing this line:
/home/francesco/ArenApp/ArenAppClient/nbproject/build-impl.xml:980: Java returned: 133
BUILD FAILED (total time: 23 seconds)
```

It seems to refer to this file:
https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1/content/browser/zygote_host/zygote_communication_linux.cc

My system (that is a VirtualBox guest) is Linux Mint 19 Tara, that is based on Ubuntu bionic. Enabling or disabling 3D hardware acceleration in VirtualBox doesn't change.

Installing Chromium or Chrome doesn't change this error.

As workaround, I renamed ./codename/cef to .codenameone/cef_old

**Comment by shannah** [comment]
Is this the same issue as https://github.com/codenameone/CodenameOne/issues/3367
Or is it on a different machine/different app/different video, different problem?

**Comment by jsfan3** [comment]
`Cannot communicate with zygote` is an error that no more appeared. I close this bug report for the moment, I will reopen it if this error reappears. Anyway, to answer your question, yes, the two bugs appeared in the same machine under similar conditions.
