### ISSUE TITLE
Long URLs Failing on iOS

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#3379]
I use Google Static Map within my App and this map is generated with some parameters that are so long.

It works fine on Simulator and Android but not on iOS.

This [short url](https://maps.googleapis.com/maps/api/staticmap?markers=icon:https://app.redtrucks.co.za/storage/files/marker_green.png|-26.2041028,28.0473051&markers=icon:https://app.redtrucks.co.za/storage/files/marker_red.png|-33.971463,18.6020851&size=640x320&mobile=true&maptype=roadmap&key=Google-Map-API-Key-Redacted) works on iOS but the moment I add path information which makes the URL  
[very long](https://maps.googleapis.com/maps/api/staticmap?path=weight:5%7Ccolor:0x0000FF%7Cenc:t~|~Cw~djDnv@jGgDjuAxw@~fA`bDboBl`BpdBeChiDhsAbiA`sD|K|oIdmEvpMdxGjwG|rGf}KrfBvpMrpDfxH`eJdxZhiL~qQtcFdzUpwIpe_@lbJ||Jpy@zkObvI|d\nkS~_W`jM~}GrvAxnBmb@plCj}AheEbHl|E~~@b{N~kA|aLho@lqIxlBlmCfHbdFthBjaKl{CnvDf~Bj{H`|@`lP~iEh~CpeBbtD|E|`KdoA`jGlrBjdD`BpnDvFps@pfAxmDxzCnrIb_DxxFfsDltEjbFtwMxkUhrNdiOfmDfbFd}E~uP|_F`tPf_FnsHxlEngIdpBhbM|r@fpEdpAlr@jwEbwCv|Ar_FdpAfd@xxFf{F|jFvExdHwvC|fEpOr}Dnt@xbWpmEb_VfnHneJdeEjkKxvGdiJltEdvIvoBbdIr_BliJ`tG`{NnaJ`oPjnGbtYxgJruJ``D~dHpAbdHcGt}FruC|kLl}DjkFlxGdxFjeE~zE`mE``Dx|GprItdUxiDpiHcG`~Fzn@dmIxvClaJv}J|}R~hDroCvgF|cI|`Rzz_@~vGd`PzjGr{TvpEdaMjfItjQb{CroIxiAb~AppVjrZjeWfva@~zH|~TbsDbeFfz@fiErpCdqEh|BzyJldBn}FtbA`fK`cC|wQx_@zcB~}B|xBjlIfiI~gOjrNv`J|vC~`IzlGfcFvrF~zBj`F`uEf`L`hBluGwStxS~hB|eGvzMxvFl_HfcAxzAxnCx|ClsB||CvzBrgE`_FnwGzjFtqFbhCrjFfqKzkLpz[jxClaJx`A?bwAuDvb@xlBiMzbCpzKf{StyNdzYdgJ~qKjpIpgOp}QxmUv`GhmHtkBvyA`yE|b@|tFnaB`{Bj{Dz{CbyMbmCxhMvuEt{KdtFlwDh{@~dBnhB|e@joFxaH|eFzxFfy@~lWr{AfiQrk@|qQ~PjmJleG`gd@duBnzThWj|Jq~@`oBoJvfKbv@p`N~fBd_IfyB|pHvl@`{KrgAfaTlcBhm]oBhnKbsBhhKhmDdxH`dJbsShgFlvFcQpcJUbmPhCntAdl@|Nbl@zfD~nCjyAvoDjcDh_CzoC`rB~eOz}DtgHh}BrhChtGdl@t_BbAfHhiAviAp_Hha@t|V`tCt~F`pDbpAttBvmBoOr{Du@bfClvBpxAjb@htHpr@d{E{OfdD|u@vnA~Wz_G{M`wBnaBfuClmBnxCbaBrmHroAh|JrnAn{GrlDr}Od`D~}FhmDuJxcOt}ClqBpgBkd@~pCycAdxCo}@{~@&markers=icon:https://app.redtrucks.co.za/storage/files/marker_green.png|-26.2041028,28.0473051&markers=icon:https://app.redtrucks.co.za/storage/files/marker_red.png|-33.971463,18.6020851&size=640x320&mobile=true&maptype=roadmap&key=Google-Map-API-Key-Redacted), it fails without an error.

The same long URL works fine on an Android build.

**Note: A valid Google Map API Key is required for the pasted URLs to work, please replace it.**

**Comment by shai-almog** [comment]
The URL seems badly formed and includes characters such as `@` which should be `%40` if I remember correctly. iOS is very sensitive to these sort of URLs. Ideally we should add a check in the simulator and fail bad URLs there as well but it's not a common problem so we never got around to do it.
