### ISSUE TITLE
Some issues with the CN1 Maven support

### ISSUE THREAD

**Issue by ericlight** [codenameone/CodenameOne#3390]
Hello

I have a few things to report about Maven support

1) Normally, a Kotlin project accepts a mix of Java and Kotlin files. With the Ant support, I could mix * .kt and * .java files in the same project and everything worked fine. With this new Maven support, when I mix these two file formats in a kotlin project, the first run goes fine and everything displays fine, but when I make changes to the * .java file and re executes the code, the simulator starts but the modifications are not applied. Any modification that is done after the first execution in the java file is not applied at all. With Ant, this problem was not present. What is the cause?

2) With the previous Ant build system, we can see methods documentation in the popup in the IDE. With Maven, this documentation is no longer displayed. Can you fix that please ?

3) In the Codename One Maven developer guide, you show how to create CN1 maven project via the command line and Codename One initializer. Can you also add in the documentation how to do it directly via the IDE without going through the two previous options?

Thanks

**Comment by shannah** [comment]
> Normally, a Kotlin project accepts a mix of Java and Kotlin files. With the Ant support, I could mix * .kt and * .java files in the same project and everything worked fine. With this new Maven support, when I mix these two file formats in a kotlin project, the first run goes fine and everything displays fine, but when I make changes to the * .java file and re executes the code, the simulator starts but the modifications are not applied. Any modification that is done after the first execution in the java file is not applied at all. With Ant, this problem was not present. What is the cause?

I can't reproduce this.  Steps I used:

1. Created Bare-bones kotlin project using initializr
2. Added Java class 
~~~~
package ca.weblite.kotlintest1;

public class HelloJ {
    public String getString() {
        return "hello 1";
    }
}
~~~~
2. Added button in Kotlin class that uses this class.  E.g.
~~~~
val btn = Button("Click Me")
btn.addActionListener{
    Log.p(HelloJ().getString());
}
hi.add(btn)
~~~~
3. Run in simulator.  Click button.  Prints "hello 1";
4. Change `getString()` method to return "hello 2";
5. Run in simulator.  Click button.  Prints "hello 2" now.

> With the previous Ant build system, we can see methods documentation in the popup in the IDE. With Maven, this documentation is no longer displayed. Can you fix that please ?
 I can't reproduce this.  E.g.
![image](https://user-images.githubusercontent.com/2677562/114608305-66bf5a80-9c52-11eb-8e76-619a402954a1.png)

> In the Codename One Maven developer guide, you show how to create CN1 maven project via the command line and Codename One initializer. Can you also add in the documentation how to do it directly via the IDE without going through the two previous options?

You should be able to just adapt the instructions that you see for command-line.  Note the parameters that you need to add in whatever IDE you use.

**Comment by ericlight** [comment]
Hi,
It's weird because i have differents results onthe first and the second point. I will give you more details about the first point. 

### **First point:**
When i create Kotlin project (with the initializr) and add the java file.  I have an execution failure at the first execution. Then i convert the java file into kotlin file and the execution performs well. I revert the kotlin file to java file again and the execution works well again. Now when i made a modification and execute again, i have the previous issue that i told you in my previous message. 
PS: I have also made the test with the same example that you took in your reply

Here is the failure message that i got for the first execution when i mix java and kotlin files .
_Failed to execute goal com.codenameone:codenameone-maven-plugin:7.0.22:compliance-check (cn1-process-classes) on project appmain-common: Compliance check failed_

### **Second point:**
About the fact that i don't have methods documentation in the popup in the IDE, i have the same problem in Netbeans too. Not only in IntelliJ

**On IntelliJ (no documentation in the popup)**

![11](https://user-images.githubusercontent.com/9592818/114613898-6a270600-9c93-11eb-9668-8f9e2daee509.png)

**On NetBeans (no documentation in the popup)**

![12](https://user-images.githubusercontent.com/9592818/114613911-6bf0c980-9c93-11eb-885f-3f8af05fc67f.png)

About the **third point**, Ok thanks

**Comment by ericlight** [comment]
Just to send you additionnal informations.

I use intellij 2021.1 (the last one) with JDK 11. I have JDK 1.8 and 11 installed but when i open a CN1 Maven project, JDK 11 is used by default

About the Netbeans version, it's Netbeans 12

Windows is my operating system

Thanks

**Comment by shannah** [comment]
Make sure you have Java files in common/src/main/java and kotlin in common/src/main/kotlin

**Comment by ericlight** [comment]
> Make sure you have Java files in common/src/main/java and kotlin in common/src/main/kotlin

I did it during my test and the kotlin file didn't find the java file.

**Comment by shannah** [comment]
I cannot reproduce this issue.

**Comment by ericlight** [comment]
> I cannot reproduce this issue.

Ok thanks! About the second issue, did you make a test on Windows too ?

**Comment by ericlight** [comment]
I have removed the Maven repository completely to allow the IDE to download Maven files and jar again. After that, i created a New kotlin project again and separate again the java file (in java folder) from the kotlin (in kotlin folder) and it works now. Very weird. 

The second issue about the method documentation is still not resolved. It continues to not show on both IDE

**Comment by ericlight** [comment]
On the Netbeans method documentation screenshot that i sent you previously, there is an "Attach Javadoc..." link. I click on it and it download some files which resolved the second issue both in Netbeans and in IntelliJ. 

Thanks for your help.

**Comment by shannah** [comment]
Thanks for sharing your solution.
