### ISSUE TITLE
Website blog not  showing "Post" button for comments

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3406]
As seen using Opera (not the first time I see this). Writing text doesn't make the button visible either

![image](https://user-images.githubusercontent.com/11293898/117548651-faa3fc80-b02d-11eb-87a1-9becf62dbec7.png)

**Comment by shai-almog** [comment]
Thanks!
This is a CSS regression. Notice that the button is there just below the text area aligned to the left. You can see it when hovering in that area. We're looking into this.

**Comment by javieranton-zz** [comment]
Cool beans
