### ISSUE TITLE
OTA iOS ipa file cannot install for 12.4

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#3407]
Whenever I try to install a new debug app I get this message after pressing the ipa install button:

(“null)” is Already Installed
“(null)” has the same Bundle ID as “(null)” and can’t be installed. To continue, delete “(null)” from your device and try again.

Problem is:

When you build for 12.4, it takes the display name for the ipa file, and since it normally has spaces on it, then it won't install.

If you build for 11.3, it takes the main name, which means no spaces and no problems.

**Comment by DurankGts** [comment]
this same issue it occurr in my case

**Comment by shai-almog** [comment]
This should be solved now. Please let me know if it's still happening or close if it's working now.
