### ISSUE TITLE
iOS Sqlite Issue

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3410]
Sqlite on iOS (C/C++ sqlite3) presents the following problem: when transactions are executed in rapid succession, a % of them gets execute twice

In the past, it has been noted that Sqlite is "thread sensitive". But I have now tested this thoroughly and have found that the issue is not only that sqlite is "thread sensitive" (in this particular instance), it also is that it can't handle multiple consecutive calls gracefully even when they are made from the same thread

To test this, I wrapped my calls in an EasyThread (to make sure we don't actually have a threading issue), and called 1000 queries in a for loop like so:

```
//function and vars definition
EasyThread dbTasks = EasyThread.start("DBTasks");

public void createNewTestTable()
	{
		transaction = "CREATE TABLE IF NOT EXISTS TEST123TEST (" +
				"   Id uuid PRIMARY KEY UNIQUE" +
				") ";
		executeTransaction(transaction);
	}
public void insertIntoTestTable(){
		String transaction = "INSERT INTO TEST123TEST (Id) VALUES (X'"+getRandomHexBlob()+"')";
		this.executeTransaction(transaction);
	}
public String getRandomHexBlob() {
        Random r = new Random();
        StringBuffer sb = new StringBuffer();
        while (sb.length() < 32) {
            sb.append(Integer.toHexString(r.nextInt()));
        }
        return sb.toString().substring(0, 32).toUpperCase();
    }
public Boolean executeTransaction(String query)//returns success/error
	{
		return dbTasks.run(()->{
			try
			{
				db.execute(query);//this example doesn't show how to initialize the db variable, please do that elsewhere
				if(getPlatformName().equals("ios"))
					pauseForSafety();
				return true;
			}catch(Exception ex)
			{
				//log a duplicate here
				return false;
			}
		});
	}
public long lastTimeDBAccessed = 0;
public void pauseForSafety(){
		try {
			if (System.currentTimeMillis() - lastTimeDBAccessed < 20)//if last transaction was within previous 20ms, wait 20ms
				Thread.sleep(20);
			lastTimeDBAccessed = System.currentTimeMillis();
		} catch (Exception ex) {
			//log if desired
		}
	}
```

```

//test method content
createNewTestTable()
for(int i=0;i<1000;i++)
     insertIntoTestTable();

```

The above code includes code that ensures that no transaction is ever executed within 20ms of each other. This prevents the duplicate transaction problem on iOS
But if the call to `pauseForSafety()` is removed, and the exception in `executeTransaction()` is logged, it will be seen that multiple "violation of UNIQUE Id" errors are thrown

I am opening this issue so that we are aware of this and perhaps can find a solution that doesn't require manually distancing each transaction 20ms from each other. This can't be completely safe. Could it be that there is a newer version of sqlite3 that perhaps doesn't have this problem? Is there something in CN1's implementation that triggers this? Interestingly, the duplicates seem to also increase in number when the EDT is blocked  doing other things.  If for example we call  from 2 threads, like so:

```
        getInstance().createNewTestTable();
        Runnable oneThreadExe = ()->{
            for(int i=0;i<1000;i++)
                SqlLite.getInstance().insertIntoTestTable();
            Display.getInstance().callSerially(()->{
                Utils.getInstance().showDialogNoBlock("Info","1 Done");
            });
        };
        Thread execThread = Display.getInstance().createThread(oneThreadExe , "1234");
        execThread.start();
       Thread execThread2 = Display.getInstance().createThread(oneThreadExe , "5678");
        execThread2.start();
```

No duplicates will be found as long as we space transactions 20ms from each other

If however we call from one thread and then from the EDT at the same time, no length of pause will be enough to prevent duplicates:

```
        createNewTestTable();
        Runnable oneThreadExe = ()->{
            for(int i=0;i<1000;i++)
                SqlLite.getInstance().insertIntoTestTable();
            Display.getInstance().callSerially(()->{
                Utils.getInstance().showDialogNoBlock("Info","1 Done");
            });
        };
        Thread execThread = Display.getInstance().createThread(oneThreadExe , "123");
        execThread.start();
        oneThreadExe .run();//calling from EDT
```

This is not a huge deal btw. Just writing it down in case it becomes of interest

**Comment by shai-almog** [comment]
Based on this: https://stackoverflow.com/questions/17364910/store-huge-data-in-sqlite
I would suggest having a transaction in place instead of sleeping.

**Comment by javieranton-zz** [comment]
Oh that's so obvious. The worst part is that I'd stumbled on this same stone many years ago, only to end up applying the same solution!

Thanks for this

**Comment by javieranton-zz** [comment]
I know you guys are super busy and this isn't a priority, but even after executing multiple statements in a transaction, the error thrown by ios's sqlite3 persists because it simply isn't possible to group every statement in a transaction and "hope" enough time runs until the next transaction to prevent this issue

The bottom-line is that in the current sqlite3 c implementation, the database isn't synchronously immediately available after a transaction has returned from execution. If another transaction is executed before the previous one has freed the DB, the second transaction will be executed twice. The larger the first transaction, the longer it will take for the DB to return to a normal state

I've tried working around this issue but it would be so much better if the root cause was fixed. If there is absolutely nothing we can do then by all means feel free to close this issue. It just really stinks that the DB should be so unreliable

[The strange thing](https://github.com/codenameone/CodenameOne/blob/9484391daa62f5e449a868e1e8453c71afb8c061/Ports/iOSPort/nativeSources/IOSNative.m#L5898) is that in the code everything looks like it should work fine (`sqlite3_step` is called with follow up with `sqlite3_finalize`) 

But in reality the method returns before the DB is ready to accept a further transaction. Actually, it is ready to accept another transaction, it's just that it will choose to execute it twice unless enough time has passed since the last transaction.

**Comment by javieranton-zz** [comment]
Actually, looking at [the code](https://github.com/codenameone/CodenameOne/blob/9484391daa62f5e449a868e1e8453c71afb8c061/Ports/iOSPort/nativeSources/IOSNative.m#L5898) again I can guess that what is happening is that `sqlite3_step` is not returning `SQLITE_ROW` or `SQLITE_DONE` or `SQLITE_OK` and as a result a threading exception is thrown, which probably triggers CN1 to retry the call

[The documentation](http://sqlite.org/c3ref/step.html) says, however, that when that happens a rollback needs to first be performed on the current transaction (I think)

**Comment by javieranton-zz** [comment]
I am thinking that an alternative to fix this is to implement a [sqlite busy handler](https://www.sqlite.org/c3ref/busy_handler.html). Then, always check whether the db is busy before attempting to write to it

**Comment by javieranton-zz** [comment]
Some reading on [SQLITE_BUSY](https://activesphere.com/blog/2018/12/24/understanding-sqlite-busy)

**Comment by shai-almog** [comment]
Can you test if adding a rollback call in that row solves the issue?

**Comment by shai-almog** [comment]
In that line... 5092

**Comment by javieranton-zz** [comment]
I couldn't "fix" the root cause. It also seems that sqlite3_exec is used in CN1's code, not sqlite3_step. So if sqlite3_exec fails, then all bets are off

Also, I have seen this same "error" on Android's SQLITE (even though it only happens 0.001% of the time when compared to how often it happens on iOS). Which leads me to think that this is a SQLITE issue more than anything

As an almost definite workaround the following can be done to (almost) completely mitigate these issues:

1-Create every table with a UNIQUE column and populate it with a GUID etc (not autoincrement)
2-Only use INSERT OR IGNORE (never just INSERT)
3-Call the DB from a dedicated thread (an EasyThread works great) and manually space out transactions at least 20ms on iOS

(1) and (2) will ensure that no duplicate row is ever created, and at the same time no errors will ever be thrown because they will just be ignored
(3) will ensure that every transaction is executed at least once. When 1 and 2 are applied but 3 is left out, around 30% out of 1000 successive transactions will never be executed (at all!). Spacing them out with 20ms takes care of this

All in all it's pretty frustrating stuff. But I guess that this is where we are and it seems it isn't even CN1's fault, unless the whole VM-threading thing affects SQLITE somehow

**Comment by javieranton-zz** [comment]
As a last comment, I have now even verified that this very same issue occurs on sql.js (based on sqlite3)

So this is totally a sqlite3 problem and nothing else. sqlite doesn't like consecutive queries, it prefers big transactions. Some platforms such as Android are forgiving, while others like iOS or WASM are very sensitive to this
