### ISSUE TITLE
iOS Push certificates are inverted in the readme.txt

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3415]
It's a small problem that's easy to notice, but those who aren't careful are likely to get it wrong. In the "readme.txt" file inside the "iosCerts" folder generated via your wizard, there is:

```
Development Push Certificate URL: 
https://codename-one-push-certificates.s3.amazonaws.com/xxx_ProductionPushxxx.p12

Development Push Certificate Password: 'xxx'

Production Push Certificate URL: 
https://codename-one-push-certificates.s3.amazonaws.com/xxx_DevelopmentPushxxx.p12

Production Push Certificate Password: 'xxx'
```

As you can see, Production and Development urls are inverted.

I don't know if the same error is in the email, because I didn't receive the email (or I absent-mindedly deleted it).

**Comment by shannah** [comment]
Fixed in git.  Will be part of next update.
