### ISSUE TITLE
Issue in the Accordion Component

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3420]
This code it work when I click in any part of the Header Test 1 or Test2

Form hi = new Form("Hi World", BoxLayout.y());
Accordion acc = new Accordion();
acc.addContent("Test 1", new Button("Test 1"));
acc.addContent("Test 2", new Button("Test 2"));
hi.add(acc);
hi.show();

This code doen’t work now when click in any part of the header when I use addContent(Component cmp, Component cmp) in accordion

        Form hi = new Form("Hi World", BoxLayout.y());
        Accordion acc = new Accordion();
        acc.addContent(new MultiButton("test1"), BoxLayout.encloseY(new Button("Test 1")));
        acc.addContent(new MultiButton("test1"), BoxLayout.encloseY(new Button("Test 1")));
        hi.add(acc);
        hi.show();

Why? I have old version of my app Released in the market where this code it was work perfectly.

**Comment by shai-almog** [comment]
I don't think this will work since the MultiButton is a lead component.
