### ISSUE TITLE
Bug in updating from Control Center

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3421]
In my Netbeans maven project, the update from "Run Maven" -> "Update Codename One" works, while the update from the Control Center doesn't work.

Screenshot of the error:
![erroreAggiornamento](https://user-images.githubusercontent.com/1997316/120207291-89222d00-c22c-11eb-841b-5e48105d5e16.png)

Note that the directory `/common/lib` doesn't exist.

**Comment by shai-almog** [comment]
When working with maven the update process is no longer applicable. I'm leaving this open since we need to detect the maven project and show a notification about that.
