### ISSUE TITLE
Simulate -> Location simulation: This simulation requires a JDK with JavaFX

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3425]
On the Simulator, the option "Simulate -> Location simulation" is not more usable. It logs: "This simulation requires a JDK with JavaFX"

Currently I'm using openjdk version "11.0.11" on Linux.

**Comment by shai-almog** [comment]
This is covered in this issue: https://github.com/codenameone/CodenameOne/issues/3173

**Comment by plumberg** [comment]
Hi, 

I get the same message when I try to run Location Simulator. This wasn't an issue a week ago. 
What can I do? Thank you.
@shai-almog

**Comment by jsfan3** [comment]
@plumberg This issue was solved. I've just tested that I haven't the regression you reported. With `<cn1.plugin.version>7.0.32</cn1.plugin.version>`, `<cn1.version>LATEST</cn1.version>` (in the `pom.xml`), and zulu-fx-11-amd64, it works.

Maybe do you have a Java version different from Zulu FX 11?
https://www.azul.com/downloads/?version=java-11-lts&architecture=x86-64-bit&package=jdk-fx

**Comment by jsfan3** [comment]
@plumberg See also all the comments here: https://stackoverflow.com/questions/68068064/codename-one-location-simulator
