### ISSUE TITLE
JavaSE build `Display`'s doesn't include `AppVersion` property from the Control Center's settings

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3430]
It needs to be manually set at runtime with

`Display.getInstance().setProperty("AppVersion","some value")`

The build process doesn't automatically get the value from the Control Center's settings

**Comment by shai-almog** [comment]
Is this with a maven local build?

**Comment by javieranton-zz** [comment]
> Is this with a maven local build?

yes

**Comment by shannah** [comment]
With Maven local builds, the "stub" class is part of your sources, and it has the app version hard-coded.  You can find and modify this file in the javase/src/desktop/java directory.

When I fix this, I'll have the build process add a properties file to javase/src/desktop/resources with the version, name and title.  But in the mean time, this is something you can adjust yourself.

**Comment by javieranton-zz** [comment]
I am using the stub class but had missed the APP_VERSION property. I can see that it works after testing, so I am satisfied by this method :-)

Thanks
