### ISSUE TITLE
Push notifications stopped working in iOS

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#3471]
Push notifications have stopped working on iOS recently. I believe it was triggered by an iOS update - I'm currently on 14.6 and not receiving any notifications. 

Registering for push appears to still work fine. I have tried uninstalling/reinstalling my app and that didn't fix the problem.

**Comment by shai-almog** [comment]
I'm not aware of such an issue. Are older devices still receiving push messages?

Did you check that your certificate is still valid?

**Comment by rochanas** [comment]
Ah, you are correct. Thanks for your help Shai!
