### ISSUE TITLE
Android build server not working

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3473]
Build stays in progress and never finishes

**Comment by shai-almog** [comment]
To be clear it does finish and you see it when you reload, right? You just lose the connection to the build server.

**Comment by javieranton-zz** [comment]
In my case neither reloading nor cancelling and resending works. I did notice that this crept up slowly as since one month ago some builds would get stuck but not always. Now it's all of them

I'm happy to wait for a permanent fix as I can still use local gradle builds. Perhaps the new bundle system will fix it in August. But I do enjoy the ease of building through the build server so it would be great if this could be fixed at some point

**Comment by javieranton-zz** [comment]
I would really appreciate some feedback, even if it's just "we're working on it". I can carry on with local builds but they do get annoying fast. Using the build server for Android was a lot more enjoyable :-)

**Comment by javieranton-zz** [comment]
It is now working again. Thx
