### ISSUE TITLE
Permission request text is not displayed the first time the permission requested

### ISSUE THREAD

**Issue by plumberg** [codenameone/CodenameOne#3475]
**Describe the bug**
The https://www.codenameone.com/blog/switching-on-android-marshmallow-permission-prompts.html says:
> When permission is requested a user will be seamlessly prompted/warned, we have builtin text to control such
> prompts but you might want to customize the text.  You can customize permission text via the Display properties ...

This doesn't work with `ACCESS_FINE_LOCATION`. 
The custom message is shown only after user denied the permission, and then requested it again. It has "Don't ask" and "Ask again" buttons, so it seems like the dialog is suppose to be shown only after the user declined the permission the first time it was asked. 
![image](https://user-images.githubusercontent.com/22183321/125318188-a2c49300-e307-11eb-86bd-62dc9d6bdab6.png)
First time it's requested, no dialog boxes are shown. 
According to the blog, I assumed that the `Display` properties can customize the text at the moment permission is requested, including the first request. 

**To Reproduce**
1. Follow https://www.codenameone.com/blog/switching-on-android-marshmallow-permission-prompts.html - Add `Display.getInstance().setProperty("android.permission.ACCESS_FINE_LOCATION", "Location required - custom string from init()");` into your `init(Object context)` method
2. Build the app, open it and try to do something that will request location. 

**Expected behavior**
Show "Location required - custom string from init()" in a Dialog

 - OS: Android

**Smartphone (please complete the following information):**
 - Device: Moto g9 play
 - OS: Android 10 API 29

**Comment by shannah** [comment]
This fix will be part of tomorrow's update.
