### ISSUE TITLE
Capture audio is crashing in simulator

### ISSUE THREAD

**Issue by plumberg** [codenameone/CodenameOne#3477]
**Sometimes**, the simulator crashes on `Capture.captureAudio()`. 
The recorder opens and the logs show 

> State is now Initialized
> State is now Paused

However, the moment I press the red record button, it crashes. 
It throws `java.lang.RuntimeException: Audio format not supported on this platform`. 

This happened few times , and every time it was unexpected - I didn't make any changes in the code, it just stopped working. 
I am not sure how it was resolved at a time. I tried to update cn1 and refresh libs, but now it's not helping. 

I am running the Ant configuration.

**Comment by shai-almog** [comment]
This could be related to CEF. Look at the logs when it succeeds vs. when it fails. Do you see a difference e.g. CEF related warnings?

**Comment by plumberg** [comment]
@shai-almog I don't have any CEF-related warning in my logs. Here are the full logs for the case when capture audio is failing:
https://gist.github.com/plumberg/89def336f06d02a923c89785fb798e73
Or is there any other place where I can find more logs? 

It didn't start working yet, so I can't compare the logs, but when it will, I'll check the difference.

**Comment by plumberg** [comment]
The problem was resolved - it's important to make sure that the mic is properly connected. 

@shai-almog  Following this issue, is it possible to modify a Runtime exception string message from `"Audio format not supported on this platform"` to something else, which would be less confusing in this particular case? For example, "Microphone is not detected"
