### ISSUE TITLE
Hint in TextField Component isn't rendering correct in the Iphone 11, xs ios 14.7.1

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3485]
![image](https://user-images.githubusercontent.com/16245755/129963660-5c50ce8c-5349-4743-a3ed-5d25b6a71665.png)

![image](https://user-images.githubusercontent.com/16245755/129963739-c23a35f1-6b6a-49d9-82d5-6a58281820fc.png)

**Comment by DurankGts** [comment]
@shannah  could you check if this fixed cause this issue in ios side

https://github.com/codenameone/CodenameOne/commit/c5afb3862aae95b6a8b65f52d4adf1f271d308c4#diff-a0be7e8605e80e9799e01dfa7563f0183c97ed1e3285dd568ee3bc13f3a112e0

**Comment by shannah** [comment]
Can you post a test case?

**Comment by DurankGts** [comment]
this issue doesn't have problem on April of this year aproximally. I don't Know why now the hint is failing when I click on the TextField Component...

**Comment by DurankGts** [comment]
this your simple test case

        Form test = new Form("TestHintIssue", BoxLayout.y());
        Image iconSearch = FontImage.createMaterial(FontImage.MATERIAL_SEARCH, UIManager.getInstance().getComponentStyle("icon"));//Utils.getMaterialImageUnselected(FontImage.MATERIAL_SEARCH, Uiid.gpcl_iconSearchContact);
        Image icB        = FontImage.createMaterial(FontImage.MATERIAL_ARROW_BACK, UIManager.getInstance().getComponentStyle("icon"));
        
        TextField tf = new TextField("");
        tf.setHint("Search",iconSearch);
        tf.setUIID("ta");
        tf.getHintLabel().setUIID("hint");
        
        Container tb = new Container(new BorderLayout());
        Button btnB = new Button();
        btnB.setUIID("Btn");
        btnB.setIcon(icB);
        btnB.setDisabledIcon(icB);
        btnB.setPressedIcon(icB);
        
        tb.add(BorderLayout.WEST, btnB);
        tb.add(BorderLayout.CENTER, tf);
        tb.setUIID("cntBgnToolBar");

        test.getToolbar().setTitleComponent(tb);
        test.setSafeArea(true);
        test.show();

this the error

![image](https://user-images.githubusercontent.com/16245755/130492692-76f90c51-eed3-4581-a6ce-d435c99f899e.png)

tested on iphone xs ios 14.6

**Comment by DurankGts** [comment]
When this fix it will available on the buid server?

**Comment by DurankGts** [comment]
@shannah  this issue was solved on august 23 2021 but now the problem is in the TextArea Component with hint in android side.

![image](https://user-images.githubusercontent.com/16245755/155140818-bfcd0b65-5a6a-4b4d-ad69-2d40976894f0.png)

**Comment by shannah** [comment]
Please file as new issue.
