### ISSUE TITLE
Android FB SDK needs upgrading

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3487]
Someone has managed to break their 2FA and now they need this. Current SDK is 4.39, they need at least 8.2 before the 5th of October

See screenshot of email notification

![image](https://user-images.githubusercontent.com/11293898/130359566-8e2ce84f-4c0a-4e2a-afb9-cbdc26620dc1.png)

**Comment by shannah** [comment]
This may be naive, but does it work when you set the facebook SDK version in the build hint to 8.2.0.  E.g. `android.facebookSdkVersion=8.2.0`?

**Comment by javieranton-zz** [comment]
@shannah No, building with that requires using androidX. So the below needs to[ be added ](https://stackoverflow.com/questions/60506895/android-studio-3-6-1-error-this-project-uses-androidx-dependencies)to gradle.properties to use androidX:
```
android.useAndroidX=true
android.enableJetifier=true
```
However, all instances of `import android.support.v4...` need to [be replaced](https://dev.to/serverbroad/answer-package-android-support-v4-app-does-not-exist-in-android-studio-0-8-3fih) with `import androidx.core...` in CN1's code as well as any native code others have implemented that uses the v4 support library

So it seems that some work needs to be done to move the codebase to AndroidX along with a general comms telling everyone to switch their references as well. This, or CN1 stops supporting FB login by October

This is my initial analysis, I might be wrong

**Comment by shannah** [comment]
> However, all instances of import android.support.v4... need to be replaced with import androidx.core...

The build server already does this when you enable Android X. The replacement should occur on user native interface code also (it runs a massive find and replace using the Android X class mappings on all source files).

**Comment by javieranton-zz** [comment]
I see. I hadn't sent it marked with AndroidX to the server (guess there is a build hint for this?)

I will be away for a couple days but I'll look into this again when I come back next week if you haven't had time to see it first

**Comment by shannah** [comment]
The build hint to use androidX is `android.useAndroidX=true`

**Comment by javieranton-zz** [comment]
Excellent news. Both 8.2.0 and 11.2.0 FB logins work. Thanks
