### ISSUE TITLE
On IOS Display.getInstance().openGallery() selected file is always reported as jpeg by Util.guessMimeType()

### ISSUE THREAD

**Issue by jeeneeno** [codenameone/CodenameOne#3493]
On ios :
 
If I select a gif file using Display.getInstance().openGallery(), Util.guessMimeType() reports it incorrectly as being a .jpeg 

I suspect this is related to :

https://github.com/codenameone/CodenameOne/issues/3492

**Comment by shai-almog** [comment]
The code that fixes orientation should ignore gifs and try to preserver the filename extension.

**Comment by shannah** [comment]
I have just updated the behaviour so that jpegs are returned as jpegs, and all other types will be returned as PNG.    This was about the best that could be done without doing some major custom image encoding support - iOS supports PNG and JPEG encoding natively.
