### ISSUE TITLE
VSCode support

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3499]
Need to add vscode config files to maven project archetypes so that main build targets can be more easily accessed in VSCode.

VSCode appears to use eclipse for its java language server, and it complains about a number of things.

![image](https://user-images.githubusercontent.com/2677562/134014215-ca286cd5-174f-43f2-9add-9cf2b200c5e9.png)

Not sure if any of these are important or not.

I did experience some problems with one project in VSCode, where, while the project is opened, if you run `mvn clean` and then `bash run.sh` it would fail every second run with an exception indicating that not all of the classes were being pulled in.

Closing VS code and running from terminal fixed this.  With VS code and running from terminal, still had same issues.

So... some work to be done here to figure out how VScode likes it.

**Comment by shai-almog** [comment]
This seems to be resolved by the current Maven plugin version and start.codenameone.com
