### ISSUE TITLE
Provisioning profile  doesn't include the com.apple.developer.icloud-services

### ISSUE THREAD

**Issue by JTBrandao** [codenameone/CodenameOne#3501]
Error in generating debug version for iOs:

Recently the following message are being exibited : 

error: Provisioning profile "com.iw.mobile.pro.development" doesn't support the iCloud capability. (in target 'IwCareAppPro' from project 'IwCareAppPro')

error: Provisioning profile "com.iw.mobile.pro.development" doesn't support the iCloud capability. (in target 'IwCareAppPro' from project 'IwCareAppPro')

error: Provisioning profile "com.iw.mobile.pro.development" doesn't include the com.apple.developer.icloud-services entitlement. (in target 'IwCareAppPro' from project 'IwCareAppPro')

error: Provisioning profile "com.iw.mobile.pro.development" doesn't include the com.apple.developer.icloud-services entitlement. (in target 'IwCareAppPro' from project 'IwCareAppPro')

Is there any compiling hint which must be valued ?

**Comment by shannah** [comment]
@JTBrandao Can you share your solution to this problem for posterity?  Might help others who hit the same issue
