### ISSUE TITLE
FileChooser stopped working on iOS

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#3514]
When trying to open a file with the FileChooser, it gives this error on iOS:

*** Assertion failure in -[UIDocumentMenuViewController _commonInitWithCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UIDocumentMenuViewController.m:123

When trying to call FileChooser.isAvailable(), it just returns a null value. I'm not exactly sure when this started happening, but it was working previously. I have one device on iOS 12 and one on iOS 15 and both have the issue. I tried refreshing the cn1libs to see if it might be fixed in a new version, but the same thing happened. 

**To Reproduce**
I used this code to test:

 ```
Form f = new Form(BoxLayout.yCenter());
Log.p("is file chooser available:" + FileChooser.isAvailable());

NativeLogs.initNativeLogs();

Button b1 = new Button("Checks available");
Button b2 = new Button("No check");
        
b1.addActionListener((ee) -> { // <2> 
    if (FileChooser.isAvailable()) 
    {
        FileChooser.showOpenDialog(".txt, text/plain", e2->        
        {                
            String file = ""; 
            try{
                file = (String)e2.getSource();
            }
            catch(Exception ex){}
        });
    }
});

b2.addActionListener((ee) -> { // <2> 
    FileChooser.showOpenDialog(".txt, text/plain", e2->        
    {                
        String file = ""; 
        try{
            file = (String)e2.getSource();
        }
        catch(Exception ex){
            Log.p(ex.toString());
        }
    });
});
        
f.add(b1).add(b2);
f.show();
```

**Comment by shannah** [comment]
Please try another build, as there have been some fixes to entitlements on iOS that might fix this issue.

**Comment by rochanas** [comment]
Yep, it's working again. Thank you!
