### ISSUE TITLE
Database/Cursor cleanup doesn't actually work, leading to iOS crash when garbage collector runs

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#3515]
**Describe the bug**
My app crashes after being used for a while on iOS. I thought it was a memory issue and ran memory profiling, but there was lots of free memory. I use a Database in my app and I believe that the problem is that the database/cursor cleanup doesn't actually work, leading to iOS crash when garbage collector runs. I thought that maybe opening/closing the database was causing the problem, so I changed my code to just try opening the database once and keeping it open, but then I got this message:

**** WARNING! DB Cursor was released by the GC without being closed first! This might cause crashes on iOS *****
**** WARNING! Database object was released by the GC without being closed first! This might cause crashes on iOS *****

So I deployed this code (not closing the database/cursor) to my iPad and found that it crashed after the same amount of navigation. I'm pretty sure that what's happening is despite me cleaning up the Database and Cursor in a finally block after doing my query, it's not getting properly closed. I have tried Util.cleanup(db)/(cur); and just close(); in a try catch and neither works.  

**To Reproduce**
1. Do a Database query using a Cursor
2. Attempt to close that using Util.cleanup(db) & Util.cleanup(cur)
3. Create enough memory overhead in the app to get the garbage collector to run
4. App crashes/stops responding correctly when trying to access database

**Comment by rochanas** [comment]
Is there anything I can do to have this looked at? It's causing constant crashing for my ios app users if they have the app open for longer than a minute or two. If I could create a test function that caused it would that help?

It didn't happen as much when I originally published my app, but every time I add more functionality, it gets worse because the app has more data to look at.

**Comment by shannah** [comment]
You need to use the `close()` method on the cursor and the database when you are finished using them.  Otherwise the GC will reclaim them, which is problematic since they should only be used on a single thread (and the GC is a separate thread).

**Comment by rochanas** [comment]
I have tried using both close() and Util.cleanup() and neither work. The crashing happens after the same amount of navigation whether I use any of those methods, or no closing method at all.

**Comment by shannah** [comment]
Please post a self-contained test case that reproduces the issue.

**Comment by rochanas** [comment]
So I tried to create a really bare bones case of this, but nothing that I tried worked. So instead I distilled some of the existing code I had, as much as I could, to the point where it could show the problem that I'm having. I did my testing on a 2020 Apple iPad Air (4 GB memory).

Originally, it would crash after clicking through all of the days in the month 4 times + a few more days (~127 clicks)

I thought that maybe because I was creating multiple instances of the database function class, that could be causing it, but it still crashed after 6 cycles (~180 clicks) through all of the days. 

When I added additional memory overhead outside of the database, I saw the available memory get lower (under 2 gbs displayed at the bottom, compared to ~3 gbs where it crashed before), but it took approximately the same amount of clicks before the database crash happened. So it's almost like I have a limited # of queries that I can make to the database, before it will crash. And whether I close my Database/Cursor doesn't affect this either way. 

And I'm saying crash, but this example doesn't fully crash the app, but it makes getting anything from the database not possible, and the icons on the screen change from black to white to signify that. In my actual app it fully crashes sometimes and sometimes it just returns nothing back from the database causing other problems. 

So then I took the part the grabbed the large text string from the DB and ran it 20 times over, per each day click. Now it crashes after 20 clicks (amounting to over 2500 calls to the database). I've attached a video of what that looks like, in case it's helpful at all. I've also attached the code. The first time it's run - it will set up the database for testing. 

After learning all of this, I went back to my simple test case (showCrashTestForm()) and tried running a ton of db queries within it, but I could never get it to crash. So there's something in the way that I'm interacting with the DB that's causing this crashing, but I'm at a loss for what exactly that is. 

https://user-images.githubusercontent.com/25064795/140433145-bb478790-3a21-4b9f-8702-916f12a7200c.MP4
[MyApplicationCrash.txt](https://github.com/codenameone/CodenameOne/files/7479404/MyApplicationCrash.txt)

**Comment by shannah** [comment]
You'll need to be methodical about your Database connection and cursors to ensure that they are closed.  Evidently one of your cursors and connections is not closed.

**Comment by rochanas** [comment]
I have 3 methods that connect to the database, and all of them close the cursor/database after. I never get that **** WARNING! DB Cursor was released by the GC without being closed first! This might cause crashes on iOS ***** when using the simulator, so I must be closing them.

Maybe the problem is something else, still database related though? In the example above, it always crashes after the exact same amount of navigation. I don't know what other testing I can do when there's no error, nothing in the cn1 logs, nothing in the native logs. I've spent so long trying to track this problem down and I'm out of ideas.

**Comment by rochanas** [comment]
Shai suggested that I might closing the DB from the "wrong thread", and that I should close the cursor first and the DB after. So I changed the order to close the cursor first, and checked on the threading by logging all of my cursor opens/closes.

I didn't find anything conclusive, so perhaps I was wrong about the cursor openness causing the problem. Using the simulator, for every opening/closing of a cursor, I logged: 

[EDT] 0:0:1,268 - OPEN com.codename1.impl.javase.SECursor@115c4b25 
[EDT] 0:0:1,268 - CLOSE com.codename1.impl.javase.SECursor@115c4b25 

I ran a quick powershell script on the logging output of 5890 lines and every open was followed by a close with the same @id, and every call started with [EDT] (meaning they are all on the main EDT thread?) 

All of my database calls come from 3 functions in the DBFunctions class, which all close the db/cursor in a finally block. I've attached my updated code, which has the cursor logging in it. 

I have tried everything that I can think of to solve this on my own, but I just don't know what else to do.

[MyApplicationCrash.txt](https://github.com/codenameone/CodenameOne/files/7499369/MyApplicationCrash.txt)

**Comment by shannah** [comment]
When running in the simulator does it still display these messages?
**** WARNING! DB Cursor was released by the GC without being closed first! This might cause crashes on iOS *****
**** WARNING! Database object was released by the GC without being closed first! This might cause crashes on iOS *****

**Comment by rochanas** [comment]
No, it does not

**Comment by shannah** [comment]
Then you should no longer have an issue with unclosed DB or Cursor.  If your app is still crashing, then it is  likely a different issue. 
The best way to track down iOS crashing issues is to debug in Xcode if you have a mac with Xcode.

**Comment by rochanas** [comment]
I originally thought it was a cursor issue because it crashed at that point whether the cursor was closed or not. And I don't have a Mac with Xcode to test this. It's working on Android and the simulator, so it should be working on iOS too.

**Comment by rochanas** [comment]
I've found the problem is caused when several really small queries run consecutively. After removing those the larger queries run without crashing. I'd still consider it a bug, but considering that it's probably happening within native iOS, I'll close this. Thanks for your help.
