### ISSUE TITLE
unnecessary bloat in IOS source codfe

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3517]
Class ArimaaViewer extends commonCanvas

In the .m and .h files corresponding to ArimaaViewer, I find this:

JAVA_BOOLEAN get_field_arimaa_ArimaaViewer_useAuxSliders(JAVA_OBJECT __cn1T) {
  return (*(struct obj__arimaa_ArimaaViewer*)__cn1T).online_game_commonCanvas_useAuxSliders;
}

void set_field_arimaa_ArimaaViewer_useAuxSliders(CODENAME_ONE_THREAD_STATE, JAVA_BOOLEAN __cn1Val, JAVA_OBJECT __cn1T) {
    (*(struct obj__arimaa_ArimaaViewer*)__cn1T).online_game_commonCanvas_useAuxSliders = __cn1Val;
}

The problem is that the variable useAuxSliders is a private variable of commonCanvas, and can't
legally be used by ArimaaViewer.  No big deal from the viewpoint of legality, since code to call it
won't ever be generated by Java.  The problem is the code bloat caused by including all these
meaningless getters and setters in class ArimaaViewer.  They still have to be compiled and probably
post-compilation sent to oblivion, which takes time.

This kind of thing is a major contributor to my build times for IOS.    class commonCanvas has many
private instance variables, and is subclassed 80 or more times.

**Comment by shannah** [comment]
Thanks for spotting this.  I have committed a fix that will be part of the next update on Friday.
