### ISSUE TITLE
New Implementation of Google Maps in android to version 18.0.0 in March of 2022

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3520]
Please check this documentation

[https://developers.google.com/maps/documentation/android-sdk/renderer](url)

Some of your projects use Maps SDK for Android. Try the new upgrade to test the improved renderer and other features.
Hello Google Maps Platform Customer,

We're writing to inform you that we released a major update of Maps SDK for Android (version 18.0.0), and it is now available via Google Play services. This Maps SDK update features a new map renderer, which will become the default renderer for Android devices* through a progressive rollout, starting in March 2022 at the earliest.

Update to the new SDK (version 18.0.0) now to test and deploy the new SDK and renderer with your apps before the new renderer becomes the default for Android devices*.

We’ve improved how we serve tiles to your apps and render the map on client devices with the new SDK. Therefore, Android devices will benefit from:

Reduced network load, processing demand, and memory consumption.
Improved gesture handling for better animations, plus smoother panning and zooming.
More fluid transitions and clearly positioned map labels.
A more stable and improved user experience for future map innovations on Android.
The new SDK also includes the general availability of Cloud-based maps styling on mobile (Android and iOS). Usage of Cloud-based maps styling for a map in Maps SDK for Android is billed with the Dynamic Maps SKU. For more information on pricing and included features, see our Cloud-based maps styling documentation.

*All devices on Android 5.0 (Lollipop) or later with 2 GB or more of data storage will use the new renderer. All other devices will continue to use the legacy renderer until further notice.

What do I need to do?
To anticipate and avoid issues with your apps we advise you to:

Use the new SDK.
Specify the new renderer in your code.
Before the beginning of the new SDK progressive rollout in March 2022. See our documentation for instructions on how to try the new renderer.

If you encounter any issues in your apps with the new SDK or the new renderer, please report them to us, and consider pausing the apps’ deployment to users until the issues are resolved.

**Comment by shannah** [comment]
I have just pushed a new version of the google maps cn1lib that supports this new renderer.  It will be available in CodenameOnePreferences soon.  

If you are using Maven, you can add this new version with the following dependency:

```xml
           <dependency>
              <groupId>com.codenameone</groupId>
              <artifactId>googlemaps-lib</artifactId>
              <version>1.1.0</version>
              <type>pom</type>
            </dependency>
```

Alternatively, you can download the cnlib manually from https://github.com/codenameone/CodenameOneLibs/blob/master/cn1libs/GoogleMaps.cn1lib

Some things to note:

1. This new version will require that your `android.min_sdk_version=19` or higher.
2. This new version will bump your play services version to 18.0.0 (if it was previously lower).

**Comment by DurankGts** [comment]
I am using now ant project I want to solve in the google map library project because I have modified this library with some log to detect some error adding Path in the simulator but I don't have finish yet.

**Comment by DurankGts** [comment]
@shannah  I just need to add version 18.0.0 in the google map project

![image](https://user-images.githubusercontent.com/16245755/154725261-9c9766aa-6149-4479-85a8-a9e01e569e74.png)

**Comment by DurankGts** [comment]
do I need to update 18.0.0 this version in this file?

**Comment by shannah** [comment]
Yes.

**Comment by DurankGts** [comment]
it's necessary to update too in the codenameone_settings.properties?

![image](https://user-images.githubusercontent.com/16245755/154726349-6e5dc6ab-a69e-4cf7-9277-ebdf9f950f0b.png)

**Comment by DurankGts** [comment]
the build to android is failing now.
[180222_1.txt](https://github.com/codenameone/CodenameOne/files/8099700/180222_1.txt)

**Comment by shannah** [comment]
Did you try what was suggested in the error log?

This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry

**Comment by DurankGts** [comment]
there is a link where can i check the new build hints ?

**Comment by shannah** [comment]
I've updated the lib to auto add this build hint (`android.useAndroidX=true`).  You can download again from the same link.  New maven version is 1.1.1

**Comment by DurankGts** [comment]
![image](https://user-images.githubusercontent.com/16245755/155001640-57b51da5-f106-4597-ae69-460dfe273a43.png)

this the built hint in the codenameone_properties

![image](https://user-images.githubusercontent.com/16245755/155001719-368bb2ec-05c0-42fe-a036-dd2dc15e8235.png)

**Comment by DurankGts** [comment]
What I need to do to solve this issue?

**Comment by DurankGts** [comment]
I solved the issue removing this ,GoogleMaps ${var.ios.pods.GoogleMaps.version\:2.6.0}
codename1.arg.ios.pods=GoogleMaps ${var.ios.pods.GoogleMaps.version\:2.7.0}
