### ISSUE TITLE
Debug build cannot be installed on an iOS 15.1 device

### ISSUE THREAD

**Issue by KlausHeywinkel** [codenameone/CodenameOne#3524]
To be able to install 2 apps on iOS devices with iOS 15.1 I added the build hint `ios.zsign=true`. This solved the problem for one of the two apps - but the other app still cannot be installed.

Recording the device with xcode when trying to install the app shows this error:

`-[IXSCoordinatedAppInstall _finishAppInstallAtURL:result:error:]: Installation for <IXSCoordinatedAppInstall<0x105f0df90> identifier:de.klaus.todo uuid:4CEC79FF-8E9E-4174-A965-D4CE996D6EAC intent:IXCoordinatorIntentInitiating creator/appDRI:App Store importance:UserWaiting state:IXAppCoordinationStateWaitingForInstall> at path /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/74BF0FD0-3847-439F-987A-EF8B52FD27A3/extract failed: Error Domain=MIInstallerErrorDomain Code=63 "Application is missing the application-identifier entitlement." UserInfo={LegacyErrorString=ApplicationVerificationFailed, FunctionName=-[MIInstallableBundle _validateApplicationIdentifierForNewBundleSigningInfo:error:], SourceFileLine=899, NSLocalizedDescription=Application is missing the application-identifier entitlement.}`

See also: https://stackoverflow.com/questions/69711204/codenameone-debug-build-cannot-be-installed-on-ios-15-device?noredirect=1#comment123323330_697112

I attached the ipa and provisioning file:
[Provisioning + ipa](https://github.com/codenameone/CodenameOne/files/7454879/provision_ipa.zip)
04

**Comment by shannah** [comment]
This ipa certainly includes the application-identifier entitlement, and it would appear to be correct.
A couple of thing to check:
1. If a previous version of the app is already installed on device, delete it first, then try to install.
2. Make sure that the device in question is included in this provisioning profile.  If not regenerate the profile with the UDID of the device in question, and do a rebuild.

**Comment by KlausHeywinkel** [comment]
1. I installed the current app-store version (from Jan 21) on a iPhone 7 with iOS 14.8.1. Then I deleted it and installed the current debug build. This worked. An iPhone 11 was updated to iOS 15.1 while the app was installed. After the iOS update the app could not be started anymore. After deleting the old installation the new build cannot be installed.
2. The device is definitely included in the provisioning file.

**Comment by shannah** [comment]
One more step I can suggest, after deleting the old install from the device, is to restart the device before trying to install again.
All I know is that the error message is a red herring (the app includes the application-identifier entitlement.  That is often the case with apple codesign-related error messages.  So we are left to feel around the periphery to find possible other causes.

If you can send me the ipa of the app the *does* work on iOS 15 (and was built by the build server), that would allow me to poke around for differences.

**Comment by KlausHeywinkel** [comment]
I removed the app from the iOS 15.1 device, restarted it and tried to install it again: Still the same problem :-(

I attached the ipa of the app that works with iOS 15:
[MyApplication.ipa.zip](https://github.com/codenameone/CodenameOne/files/7455454/MyApplication.ipa.zip)

**Comment by shannah** [comment]
When what the MyApplication.ipa built?  The provisioning profile says it was created in Febrary.  Is that also when the app was built, or was it built more recently?

**Comment by KlausHeywinkel** [comment]
The provisioning file was created in February - the build is from yesterday

**Comment by shannah** [comment]
It is possible that the problem is with the certificate wizard.  Make a backup of your "good" provisioning profile for MyApplication, then generate a new provisioning profile with the certificate wizard and try a build with that one to see if the resulting app will then "fail" to install on your device.

**Comment by shannah** [comment]
Actually, I believe this issue is now fixed on the build server.  No need to test with a different provisioning profile.  Simply generate a new build, and it should install correctly.  Please let me know if this is working for you.

**Comment by KlausHeywinkel** [comment]
Great - a new build can now be installed successfully :-)
