### ISSUE TITLE
iOS certificate wizard: the provided provisioning profile and certificate do not match

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3525]
I cannot run my app I'm developing on iOS 15.1, as I reported: https://new.reddit.com/r/cn1/comments/qkfc1z/same_app_generated_by_codename_one_ios_build/

The build hint `ios.zsign=true` doesn't help.

So, on the Apple Developer web site, I removed all certificates, indentifiers and profiles.
I also removed all the files in the `/common/iosCerts/` dir.

I tried to regenerated certificates (with push enabled) using the Certificate Wizard. I tried several times, but all the times the build fails.

At the end of the log, there is this error:
```
The provided provisioning profile and certificate do not match.  Please ensure that the provisioning profile you provide was generated using the certificate that you provide.
To skip validation, you may add the ios.validateProvisioningProfile=false build hint
```

Could you please check that the iOS Certificate wizard works well? Thank you

**Comment by shannah** [comment]
When did you last test this?  I just made some updates to the server about an hour ago that fixes some iOS15.1 issues.

**Comment by jsfan3** [comment]
My last test is less than an hour ago, maybe half hour. I have to step away from the computer now, I'll do the next test in a few hours.

**Comment by shannah** [comment]
Certificate wizard is working fine for me.  I just ran a couple more tests.  That validation error really suggests that the provisioning profile doesn't match the certificate.  I would look very closely at that.

You can print out details of the provisioning profile using the `security` command.  E.g.

`security cms  -D -i "Payload/ToDoApp.app/embedded.mobileprovision"`

The output will include `<key>DeveloperCertificates</key>`.  You should be able to use this value to compare to your certificate and verify a match.

**Comment by jsfan3** [comment]
I went back to the computer, tried the certificate wizard again now (after again deleting certificates, identifiers and profiles from developer.apple.com). It gives the error in this screenshot:
![error](https://user-images.githubusercontent.com/1997316/139949260-66bea898-1525-4c44-8686-9956ab321761.png)

**Comment by jsfan3** [comment]
I suggest suspending investigation of the problems reported here, which are currently no longer occurring. What is happening now (and was also happening yesterday before the problems listed here) I have reported here: https://github.com/codenameone/CodenameOne/issues/3526
