### ISSUE TITLE
iOS certificate wizard: three bugs? Invalid certificates prevent me from producing an iOS build

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3526]
This morning I tried the wizard again: the errors of the previous bug report (https://github.com/codenameone/CodenameOne/issues/3525) are no longer there, but I noticed other tree bugs. At the moment I can't produce an iOS build for the reason explained below.

_[BUG 1, not so important]_ If I remove just about all certificates, including "iOS Development" and "iOS Distribution", the wizard regenerates these two, **then hangs after creating them**.

To create the app-specific certificates ("APNs Development iOS" and "Apple Push Services"), to create the "identifiers" and "profiles" ("MyApp IOS_DEVELOPMENT Profile", "MyApp IOS_DISTRIBUTION Profile", "MyAppNotificationServiceExtension IOS_DEVELOPMENT Profile" and "MyAppNotificationServiceExtension IOS_DISTRIBUTION Profile"), I have to use the wizard a second time.

I have enabled the Push and received the Push instructions by email.

So the wizard arrives at the end without reporting any errors.

_[BUG 2]_ But in truth, on the page https://developer.apple.com/account/resources/profiles/list, **the two profiles "MyApp IOS_DEVELOPMENT Profile" and "MyApp IOS_DISTRIBUTION Profile" have the word "Invalid" in the column "Expiration"**.

_[BUG 3]_ When submitting a new build "iOS App (Debug)", it fails. The server log ends with this error: **"Provisioning profile does not have push enabled.  Either set the ios.includePush build hint to false or generate a new provisioning profile with push enabled"**. _This doesn't make sense, because I have Push enabled and even received the instructions by email._

Everything I reported here was also occurring in the attempts I made yesterday, before the problems reported in: https://github.com/codenameone/CodenameOne/issues/3525

**Comment by shannah** [comment]
Checking the logs, I see this error message, but don't know if it's associated with your requests:  "You already have two active push certificates of the same type".

**Comment by jsfan3** [comment]
I don't know what's the meaning of "You already have two active push certificates of the same type".

Before executing the wizard, I removed all the certificates, the identifiers, and the profiles. I made my Apple Developer space as clean as possible to don't have duplicates.

Don't you think that profiles marked as "Invalid" could be the cause of this issue?

![Schermata del 2021-11-03 14-45-59](https://user-images.githubusercontent.com/1997316/140071916-9e3c3ae6-f052-43a2-bafa-eac3ee4fab23.png)

**Comment by shannah** [comment]
Yes. That's fishy.  So if you delete those profiles and generate new ones, the new ones also have an invalid expiration date?

This might be something to do with daylight savings time changes.  Time changes always cause hiccups.

**Comment by jsfan3** [comment]
Yes, it is as you wrote.

**Comment by jsfan3** [comment]
I sent you one of them by email.

**Comment by shannah** [comment]
I'm looking at it right now.  Have you already gone through this document that discusses reasons why a provisioning profile status would be invalid?  https://developer.apple.com/library/archive/qa/qa1878/_index.html

**Comment by shannah** [comment]
> ? Can you remove any information (including push) associated with the app.aren.client package from the CodenameOne servers

We don't keep any information on our servers.  Everything is loaded as needed from Apple.

If your app uses Push, make sure that your App ID has "Push Notifications" enabled in the app ID (in apple developer).  If it was not enabled, then enable it and re-generate a provisioning profile using the certificate wizard.

I'm still looking through the provisioning profile that you sent but nothing jumping out as "invalid" right now.

**Comment by jsfan3** [comment]
Maybe this can help to reproduce the issues: https://github.com/codenameone/CodenameOne/issues/3527
