### ISSUE TITLE
Steps to reproduce the wizard issues consistently

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3527]
Steps to reproduce the wizard issues consistently (I tried several times):

1. Generate a new project with https://start.codenameone.com/ with a new (never used) package name
2. Follow README.adoc instructions according to your IDE (I use Netbeans 12.3)
3. Run Maven -> Update Codename One
4. Run Maven -> Open Control Center -> Follow the iOS Certificate Wizard (remember to enable Push!)
5. You receive the Push instructions by email
6. Send "iOS Debug build". It fails with the error:
```
Provisioning profile does not have Push enabled.  Either set the ios.includePush build hint to false or generate a new provisioning profile with Push enabled
```
7. Rerun the Wizard with Push enabled
8. You receive the Push instructions again by email
9. Send an "iOS Debug build". It fails again but with a different error:
```
The provided provisioning profile and certificate do not match.  Please ensure that the provisioning profile you provide was generated using the certificate that you provide.
To skip validation, you may add the ios.validateProvisioningProfile=false build hint
```

Tested both on Linux and MacOS, with Netbeans.

**Comment by shannah** [comment]
I have tried the steps you described and cannot reproduce.  Is it possible that your codenameone_settings.properties file is pointing to a different iOS certificate or provisioning profile than you expect?
