### ISSUE TITLE
Can't get url when opening the app from closed state via universal link, in ios 15.1

### ISSUE THREAD

**Issue by acionescu** [codenameone/CodenameOne#3529]
**Describe the bug**
`continueUserActivity` never gets called when opening the app, from closed state, via universal link, so there's no way get the url at start. 
This works when the app is open via universal link from background.

**To Reproduce**
This is a followup of [this  issue on stackoverflow](https://stackoverflow.com/q/69989153/7845333).

**Expected behavior**
The url that opened the app should be made available via the `AppArg` property or via a callback.

**Smartphone (please complete the following information):**
 - Device: iphone 6s
 - OS: ios 15.1

**Additional context**

The solution seems to be to use the launchOption `UIApplicationLaunchOptionsUserActivityKey` in the `didFinishLaunchingWithOptions` method, as per this [stackoverflos answer.](https://stackoverflow.com/a/33185555/7845333)

**Comment by shannah** [comment]
It isn't clear from that SO answer how to retrieve the URL that was used to open the app.  Have you tested this solution?  If so, what code did you use to retrieve the URL?

**Comment by acionescu** [comment]
@shannah, [in the current implementation of didFinishLaunchingWithOptions](https://github.com/codenameone/CodenameOne/blob/8be34b14f6e7323141c0f1773d1fb85c76291a79/Ports/iOSPort/nativeSources/CodenameOne_GLAppDelegate.m#L116) i see that the AppArg is populated from the `UIApplicationLaunchOptionsURLKey` option. 

Maybe trying to get the url from the `UIApplicationLaunchOptionsUserActivityKey` as well could solve the issue?

I haven't tested this, I don't know how. Can I override the entire `didFinishLaunchingWithOptions` via the ios.glAppDelegateBody build hint?

**Comment by shannah** [comment]
There are a number of injection points to inject code directly in the callbacks.  See https://www.codenameone.com/developer-guide.html#_advanced_topicsunder_the_hood

I'll probably need to create a test case to reproduce this issue to identify when and where this URL can be found.

**Comment by acionescu** [comment]
@shannah, [here's a much recent solution](https://coderedirect.com/questions/383370/firebase-deeplink-not-calling-applicationcontinueuseractivityrestorationhandle) ( 3 months ago ),  that uses the same option, `UIApplicationLaunchOptionsUserActivityKey`, to get the launch url in the `didFinishLanunchingWithOptions`. Look at the first answer. The swift code is this: 

```
             if let userActDic = launchOptions?[UIApplicationLaunchOptionsKey.userActivityDictionary] as? [String: Any],
                        let  auserActivity  = userActDic["UIApplicationLaunchOptionsUserActivityKey"] as? NSUserActivity{

                        NSLog("type (userActDic.self),(userActDic)") // using NSLog for logging as print did not log to my 'Device and Simulator' logs
                        launchURL = auserActivity.webpageURL
                    }
            ...
            }
```

**Comment by acionescu** [comment]
I'll use the `ios.afterFinishLaunching` build hint to test this.

**Comment by acionescu** [comment]
@shannah, another intersting solutions is [this](https://stackoverflow.com/a/33792750/7845333). Apparently, the call to

```
    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];
```
causes `didFinishLaunchingWithOptions` to return false, which prevents the call to `continueUserActivity`.

I see this exact code in the codenameone implementation of `didFinishLaunchingWithOptions`, guarded by `#ifdef INCLUDE_FACEBOOK_CONNECT`. Is it possible to disable this via build hints?

**Comment by shannah** [comment]
That part is only included if using facebook connect.  It is required for facebook connect to work properly - i.e. facebook login won't work without it.

**Comment by acionescu** [comment]
@shannah, so I confirm that the facebook sdk call is the culprit. I'm not using facebook anymore, but I did at some point, and I forgot a` facebook.appId` build hint in my codename one settings. After I removed it, things started working. 

However, things are still going to be broken for people that are using facebook connect. 

Also, I wish it was a smoother way to handle applink opening than the  start->stop->start roller coaster. The AppArg property is populated already at the first start call, so the second call shouldn't be necessary at all.

**Comment by acionescu** [comment]
Since I've lost 3 days on this, I tried to get a solution that would work for everybody.
By adding the following code to the `ios.afterFinishLaunching` build hint, the AppArg will be populated at start with the app launchUrl(if any), even if facebook is sdk is used:

```
NSDictionary *activityDictionary = [launchOptions objectForKey:UIApplicationLaunchOptionsUserActivityDictionaryKey];
if (activityDictionary) {
    NSUserActivity *userActivity = [activityDictionary valueForKey:@"UIApplicationLaunchOptionsUserActivityKey"];
    if (userActivity != nil) {
	       if ([NSUserActivityTypeBrowsingWeb isEqualToString:userActivity.activityType] && userActivity.webpageURL != nil) {
		JAVA_OBJECT launchUrlStr = fromNSString(CN1_THREAD_GET_STATE_PASS_ARG [userActivity.webpageURL absoluteString]);
		JAVA_OBJECT appArgKey = fromNSString(CN1_THREAD_GET_STATE_PASS_ARG @"AppArg");
		JAVA_OBJECT displayInstObj = com_codename1_ui_Display_getInstance__(CN1_THREAD_GET_STATE_PASS_SINGLE_ARG);
		
		com_codename1_ui_Display_setProperty___java_lang_String_java_lang_String(CN1_THREAD_GET_STATE_PASS_ARG displayInstObj, appArgKey, launchUrlStr);
	    }
    }
}
```

Just tested this and it works. Hope it helps.

**Comment by shannah** [comment]
Thanks.  I'll try to get this in for next Friday's update.

**Comment by acionescu** [comment]
@shannah, is the modification already available in the latest CodenameOne build? Thanks?

**Comment by shannah** [comment]
It should be there now.

**Comment by acionescu** [comment]
@shannah , Is this in build 198 or 197? I noticed that with build 197 the app crashes when trying to open it via a custom url. This used to work before. I hope that this isn't caused by the above code.

**Comment by shannah** [comment]
That is the only change so if it is crashing, it is likely related to that change.  You can build with sources to verify.

**Comment by acionescu** [comment]
I will try to to that. Until then, it may be safer to remove that code in order not to brake custom urls. If one wants to read applinks via AppArg at start, can add it to the `ios.afterFinishLaunching`. I'll try to come back on this after doing more tests.

**Comment by acionescu** [comment]
@shannah, I manged to build from source, however I don't know how to include  the `CodenameOne_GLAppDelegate.m` that I modified, in the build. Will it be enough to add the IOSPort.jar to the project libraries or do I have to do something else? Thanks.

**Comment by acionescu** [comment]
@shannah, so the app crashing when trying to open from a custom scheme has something to do with the `facebook.appId` build hint as well, except that it crashes if **the build hint is missing**, and working well when the build hint is present. 
With the added change and keeping the facebook.appId build hint, things work for me in both cases, so I'm gonna leave it like this, as I lost way to much time on this issue. Thanks.
