### ISSUE TITLE
Possibility to create common variables to use in the theme.xml or theme.css like colors, unit, etc

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3530]
actually is very difficult to share the same color in the theme.xml or theme.css. I android is uses a files color.xml, dimens.xml etc.

Please check this: 

(https://developer.android.com/guide/topics/resources/providing-resources)

it would very util if you implement this in CN.

**Comment by shannah** [comment]
I have made a start at this goal in this project https://github.com/shannah/cn1-material-theme

Still a lot of work to do there though.

**Comment by DurankGts** [comment]
ok, thank you it's very important that the Developer can create it's own custom variable like colors, dimension, styles, etc.

**Comment by shannah** [comment]
You absolutely can.  That project is _just_ a CSS file.  It uses CSS variables for colors and dimensions.    You could do the same thing with your own styles.

**Comment by DurankGts** [comment]
but you can create a documentation like to create a variable for example a color common an how to reference in the css style?

**Comment by DurankGts** [comment]
or provide in the readme project.

**Comment by shannah** [comment]
https://www.codenameone.com/developer-guide.html#_css_variables
