### ISSUE TITLE
SafeArea is using margin not padding in toolBar. Please provide as a new alternative

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3533]
Why when I use method in my Form myForm.setSafeArea(true); my tool bar create a margin to the Container toolBar instead Padding?

if I have different background color form of my background color toolbar. It's imposible to custom entire background color of my tool bar.

Please provide a way to use padding as other alternative to custom the background color to entire tool bar.

![image](https://user-images.githubusercontent.com/16245755/143898008-c0037fe4-6f8c-42b6-85af-0b1f7757c42f.png)

**Comment by DurankGts** [comment]
how can I detect Nocht bar in Ios using cn1 code to apply my custom code without add model real device that support this?

**Comment by shannah** [comment]
Generally you don't want to set safe area true on the form itself.  Even setting it in the content pane may be too heavy-handed.  Better to set it on the actual containers whose contents need to be "safe", because you'll want outer/background containers to bleed directly to the edge of the device.

**Comment by DurankGts** [comment]
I can't understand you. Please give me another explanation. Can I set setSafeArea to ToolBar instead Form an this issue will solved?

**Comment by TonGalaxy** [comment]
???


ในวันที่ อ. 30 พ.ย. 2021 23:04 Durank ***@***.***> เขียนว่า:

**Comment by shannah** [comment]
> Can I set setSafeArea to ToolBar instead Form an this issue will solved?

The concept of a "safe area" is a container that will add the necessary padding to itself so that its children are fully in the "safe are" of the screen.  If the children of the container need to bleed to the edge of the screen, then it shouldn't be marked as safe.

You may need to experiment to get the results you're looking for.

**Comment by DurankGts** [comment]
I tested setting my ToolBar to safeArea using this method and this the result that I expected. But the bottom component don't Adapt to safe area. Setting the safe area in the Form is more easy that setting to specific component. I think that you must create and alternative using padding in Form instead Marging.

![image](https://user-images.githubusercontent.com/16245755/144118847-43dba110-b46d-4090-8294-985efb02025b.png)

**Comment by shannah** [comment]
The ToolBar is probably not the best thing to make into a safe area.  It is sort of a wrapper component.  Look at the component inspector and try to identify a different component that will achieve what you want.  E.g. TitleArea.

**Comment by DurankGts** [comment]
I just want to avoid that my app in devices with notch bar don't  overlap my component. Any suggestion?

**Comment by DurankGts** [comment]
this not the purpose of the safeArea Method?

**Comment by shannah** [comment]
The safearea method is on the container.  If true, then all of the container's _children_ won't overlap the notch.
The ToolBar is a special component, and making it "safe" may not yield the result you're looking for.  E.g. It may bump the title bar down, leaving a gap at the top of the screen.

**Comment by DurankGts** [comment]
This the result that I expected. I just what a padding from top to my title to avoid the background color of the Form Background.

**Comment by DurankGts** [comment]
this just in devices that have notch bar.

**Comment by shannah** [comment]
Look at the component inspector to get an idea of what the result will be.  Safe area is simple.  But if you apply it in the wrong place, it will give results like you're observing.

**Comment by DurankGts** [comment]
I can't understand . I'm observing the result what I expected when I set safeArea to the toolbar. What are the future problems is My toolbar use this method?

**Comment by shannah** [comment]
I don't understand your issue then.  You're saying that it works properly if you set ToolBar to be a safe area?  Then what is the issue then?

**Comment by DurankGts** [comment]
The issue is that If I set safeArea to the Form you use Margin from Top and Bottom instead Padding. this the issue in my attached image. I solve the issue setting safeArea to the ToolBar that Just add Padding instead margin. I need this because the Native tool bar in ios side just use light or Dark mode. I needed that the native tool bar have the same background color of my App Tool Bar.

**Comment by shannah** [comment]
You'd never want to set safe area on form itself.  That would prevent anything in your UI from bleeding to the edge.  It doesn't set margin, it just sets padding on the form, which causes the entire content pane to be inset inside the safe area.

**Comment by DurankGts** [comment]
I understand you, I applied setSafeArea to specific containers Inside the Form but I consider that Is more easy some time use this in the form because generally we want to avoid this on top and bottom of the Form.

**Comment by shannah** [comment]
> I consider that Is more easy some time use this in the form 
That would be more complicated than you think.  There are many scenarios where this would give bad results, as it is hard/impossible to predict which "child" components you want to bleed to the edge, and which components you want to be inside the "safe" area.
Giving you the option to apply "safe area" to the specific containers you need seems like the simplest option.  The rule is not complex.  A "safe area" will have padding applied as necessary so that its children are all in the device's safe area.  No caveats.  One simple rule.
