### ISSUE TITLE
Possibility to Enable Done Button in IOS keyboard using TextField Component and MultiLine

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3535]
Please provide a way to show done button in Keyboard instead Toolbar.

![image](https://user-images.githubusercontent.com/16245755/144285583-dc83d6e3-b045-4152-a2ff-16b534dae747.png)

**Comment by shannah** [comment]
For single-line text fields it should use a Done button by default.  The return button will appear in multi-line textfield.  That text field looks like it is a single line.  Is it _actually_ multiline, just sized to a single line?

**Comment by DurankGts** [comment]
![image](https://user-images.githubusercontent.com/16245755/144287340-1ad92690-d495-4274-921a-83016d3e39e2.png)

There is a way to show done button in keyboard using multiline textfield?

**Comment by shannah** [comment]
I dealt with the same issue when developing the chat app demo.  What I found was that a "Done" button on the keyboard is an antipattern.  Check out other text apps, like Whatsapp.  They use a "return" button.  If you replace the "Return" button with "Done" in a multiline text field it create UX issues since users can't add new lines.

**Comment by DurankGts** [comment]
I understand perfectly. But if I hide the done button because it occupy very space on top of the keyboard then the user could not close the keyboard like android side.

How can I custom the Name of the Done button?

**Comment by shannah** [comment]
You can localize the Done button using the same mechanism as you would use to localize a button line `new Button("Done")`.  I.e. Just add a translation for the "Done" string in your resource file.

If you want the user to be able to fold the keyboard, you can do this programmatically.  The Whatsapp does it is they detect when you're swiping down in the text field, and they fold the keyboard then.
