### ISSUE TITLE
Possibility to download Image in SVG in runtime.

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3539]
Please provide a way to download images in svg in cn1. Actually it's possible using static SVG images using flamingo transcoder to Java Class, but I would be very important if we can Download Image in svg in Runtime from a server.

**Comment by shannah** [comment]
While relatively straight forward (translating well-defined XML tags into drawing commands), this would be a big job and it isn't planned right now.  If someone else wants to do this as a cn1lib, there's nothing stopping them though.

**Comment by DurankGts** [comment]
I think that you must schedule to the future development to you intead close.
