### ISSUE TITLE
"Barebones" projects default theme

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3546]
I recently reconstructed my builds in the new maven substrate, by using the project initializer.  Since my existing 
projects were derived from a prior generation of skeleton projects, they used /theme.res as the name for their
default UI theme.

In the new environment, that /theme.res was ignored and, as far as I can see, impossible to use under that name
because of some machinery that constructs a theme.res from a CSS.  The result was my app came up with completely
bizarre styles.   Maybe the process is broken, or maybe the defaults are not very well thought out, you be the judge.
These two snapshots show the intended appearance, and the actual appearance when using this default theme.
![image](https://user-images.githubusercontent.com/5963076/151585114-c7dad089-6897-4ac7-a98a-7d0f7d043c67.png)
![image](https://user-images.githubusercontent.com/5963076/151585737-b83df8bf-d06d-4105-b660-ab182f14b7a3.png)

Suggestions:

Change the name of the default theme in the new skeletons, so it won't conflict with the names used
in previous eras.

Add the missing \common\src\main\resources directory, so there is a place to put "old style" resource files.

Document this as a specific  issue if converting existing projects.

**Comment by shannah** [comment]
If you don't want to use CSS, you can disable it manually in the common/codenameone_settings.properties file:

~~~
codename1.cssTheme=false
~~~
