### ISSUE TITLE
Structure of bare bones projects

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3547]
It "ought to" be the case that content (source files) of projects can be located in some external
directory, so that the sources can be source controlled (git) and/or shared among several projects.
This was never the case in the old build system, at least without performing surgery on the .xml
build files.

With the new maven build system, it is possible (hurray!) for the main sources - eclipse external source
links are followed seamlessly.   However, it's not possible as far as I can determine, for native files
and resources.   

Please go the distance - all sources ought to be able to be located external to the project hierarchy.

**Comment by shannah** [comment]
I wouldn't muck with the source locations.  There's a lot of machinery there, and some of it may depend on source existing where it expects it to.
