### ISSUE TITLE
Deeper builds

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3548]
It would help a lot, for people like me who are willing to get into the weeds, if there were a way to
submit a build where locally modified java and native sources were used.   Current example, I'd tinker
with ios implementation to collect information and maybe fix the "disappearing text box" problem 
if there were a more convenient way to run modified code from iosImplementation on an actual ipad.

**Comment by shannah** [comment]
It's all open source.  You can build the whole thing locally.
https://www.codenameone.com/blog/building-codename-one-from-source-maven-edition.html

**Comment by ddyer0** [comment]
There's always the option to start with a bucket of sand, but I was referring to an intermediate option.  If I've
cloned the codename1 repository, I wish I could easily designate that repository to be substituted for the one that's
used by the build server.

**Comment by shannah** [comment]
This has come up before a few times, but some members of the team felt that it would lead to people monkey-patching the libs, forgetting about it, and then it would lead to very hard to debug errors on the build server.  
I understand the utility of this, but it won't be happening in the near term.
Building locally with Maven is the best pathway for this sort of thing.
