### ISSUE TITLE
Adding the build hint: ios.NSCameraUsageDescription with description of why you need to use the camera.

### ISSUE THREAD

**Issue by danieltsai1230** [codenameone/CodenameOne#3564]
Added automatically by the simulator and should have been documented.

**Comment by shannah** [comment]
Is this related to the cn1-codescan cn1lib?   Can you provide more context?

**Comment by danieltsai1230** [comment]
Yes, it is related to the cn1-codescan cn1lib.
[https://stackoverflow.com/questions/71499472/codesacnner-library-of-cn1-works-in-android-but-crashed-in-ios-without-any-error/71507082#71507082](url)

**Comment by shannah** [comment]
I pushed out a new version of the cn1lib yesterday that automatically adds this build hint if you run it in the Simulator.  I've also added a [section](https://github.com/codenameone/cn1-codescan#ios-permissions) to the readme about this.

https://github.com/codenameone/cn1-codescan/commit/ac8b58c71861e6eda18c009a98cc705ac0d4ab32
