### ISSUE TITLE
Migrate your servers with xcode 13 by Apple warning

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3567]
WARNING ITMS-90725: "SDK Version Issue. This app was built with the iOS 14.4 SDK. Starting April 25, 2022, all iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or later."

please program urgent your server to upadte to xcode to 13  instead 12.4 by this warning of apple

**Comment by DurankGts** [comment]
hello you are migrating to xcode 13 ?

**Comment by shai-almog** [comment]
This is currently resolved.

**Comment by DurankGts** [comment]
Could you provide the new build hint to compile to code 13?

**Comment by shai-almog** [comment]
Just remove the xcode version build hint. Older versions are no longer supported.
