### ISSUE TITLE
Certificate Wizard: Please update to Xcode 7.3 or later to continue developing with your Apple ID

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3571]
Apple has shut down one of the APIs used by spaceship, and this is affecting the certificate wizard's ability to generate profiles.

Caused by https://github.com/fastlane/fastlane/issues/20060

**Comment by AmirAlahmedy** [comment]
Do you know what API exactly was shut down?

**Comment by shannah** [comment]
@AmirAlahmedy Details are in the linked fastlane issue.

**Comment by shannah** [comment]
Ugh!  I can't reproduce this issue.  I'll leave this open for people to provide more details about the issue and perhaps provide some specifics that will allow me to reproduce it.

**Comment by ThomasH99** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/16265939/160478739-4b0940d6-a03f-4171-8519-1b976a685a78.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/16265939/160478966-e18f6997-ed07-4570-a6f2-c9852d75264c.png">

**Comment by ThomasH99** [comment]
Don't know if any of this will help? I also tried generating again without the Production Certificate (which was not selected by default), but it didn't change anything.

**Comment by ThomasH99** [comment]
Oh, I just noticed the wizards say it may only work if you have one device associated with the account and I have multiple devices (2 x iPhone, iPad). Can that be the reason? Since it was a bit of a pain to add the devices, and I need them for testing, I'd rather not delete them if it can be avoided.

**Comment by ThomasH99** [comment]
This time (contrary to the other times I tried the wizard) I just got an email from Apple saying the certifications has been revoked. So, it seems the wizard got further in the process than before.

**Comment by ThomasH99** [comment]
Tried generating again and got a new revoked message. So, I just connected to my apple developer account and the new certificates are there. So, it seems the generation (now?) works, but the download not.

**Comment by ThomasH99** [comment]
But the product provisioning profile was not generated! I tried creating one manually and relaunch the wizard and got this: <img width="390" alt="image" src="https://user-images.githubusercontent.com/16265939/160483878-30dfa556-9490-4933-9818-6aefd942c99a.png"><img width="390" alt="image" src="https://user-images.githubusercontent.com/16265939/160483968-ef0bc3e5-0a08-4105-a012-65ac3549e8b7.png"><img width="394" alt="image" src="https://user-images.githubusercontent.com/16265939/160484089-1d5b8d67-9692-40b1-b971-16b6fd2126ab.png">

**Comment by shannah** [comment]
Must be some differences between our accounts.  I have a few things I can try based on the fastlane issue.  It is just harder when I can't reproduce the issue myself.

**Comment by AmirAlahmedy** [comment]
Setting the following the Fastfile before using `Spaceship` solves the problem.

`ENV['SPACESHIP_AVOID_XCODE_API'] = 'true'`

**Comment by shannah** [comment]
@ThomasH99 I have added the environment variable that @AmirAlahmedy suggests.  Please give it another try and let me know how it goes.

**Comment by ThomasH99** [comment]
Thanks Steve, I just tried but it fails with same message (update to Xcode 7.3). Do I need to update anything on my side?

Btw, I noticed the wizard fails if you leave a space before your login email, in case you want to clean the email.

**Comment by etxfaqa** [comment]
Same here, still not working

**Comment by ThomasH99** [comment]
Any suggestions for how I might help move this forward? I've tried to delete and recreate my certificates. I've disabled all my iOS devices except one. I still get the same error message. The wizards clearly connects and works up to and including revoking the old certificated since I get an email from Apple titled "Your Certificate Has Been Revoked".

**Comment by ThomasH99** [comment]
I'm trying to get this to work manually (without the wizard). However, the the CN1 Control Center page for iOS signing asks for a password (line just below where you specify the p12 certification file) but it's not clear what password is expected. The CN1 password doesn't seem to work. I couldn't find any Help page, nor did Google help. 

Can you clarify? 

(it's probably also worth specifying which password is expected directly in the UI)

As a side note, in the Control Center's left side menu, the bottom says "Questions? Please Chat with us!" But clicking it leads to a blank page ;-)

**Comment by shai-almog** [comment]
P12 files are password protected. I think you incorrectly generated a cer file which isn't password protected. Notice that there's a section in the developer guide that covers the manual setup too.

**Comment by shannah** [comment]
@ThomasH99 @etxfaqa Please give it another try.  I made a few more changes to try to workaround this issue.

**Comment by ThomasH99** [comment]
Get, thanks Steve, it also works for me now!

**Comment by stefancohn** [comment]
Hello, I know this thread is very old, but how did you guys get the Certifications? I'm running into the null issue. Did you just end up getting them manually? If so, how do you do that? Did you get the cert wizard to work, and if so how? I would love any help as I am still kind of a noob to programming and this is my first time working with a framework.
