### ISSUE TITLE
Java Timer not working on iPhone 10r

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3580]
**Describe the bug**
Submitted as requested by Shai on reddit. I replaced my UITimer with a Java java.util.Timer and TimerTask (based on the reddit thread "Display.callSeriallyOnIdle doesn't work when a UITimer is used") and it works as expected in the simulator. However, I just tried on the iPhone and UI refresh the Timer should trigger doesn’t happen.  I tried building the test example below on iOS and it doesn't update the button, but in the Simulator it works as expected. I also ran my app with lots of log messages that should show up, but absolutely nothing shows.

**To Reproduce**
Run this code on Simulator and the button updates with current time every second. Run on iOS and nothing happens (the "XXXXX" remains unchanged): 
```
Form hi = new Form("Timer test", BoxLayout.y());
Button b = new Button("XXXXXXX");
hi.add(b);
long periodMillis = 1000;
Runnable r = () -> {
  b.setText(new Date().toString());
  b.repaint();
};
Timer timer = new Timer();
TimerTask timerTask = new TimerTask() {
public void run() {
Log.p("Timer: timerTask.run(): Display.getInstance().callSerially(r); r=" + (r != null ? "<defined>" : "<null>"));
Display.getInstance().callSerially(r);
}
};
timer.scheduleAtFixedRate(timerTask, new Date(), periodMillis);
hi.show();
```

**Expected behavior**
Timer should update on device.

**Smartphone (please complete the following information):**
 - OS: iOS/iPhone 10r

**Comment by shai-almog** [comment]
I'm experiencing some build issues on my newer machine and can't get an environment set up properly. Will try to look into this. Please ping me if I don't.

**Comment by ThomasH99** [comment]
Hope your machine is working again. Does the test example work for you?

**Comment by shannah** [comment]
This is fixed in git and will be part of the next update (7.0.73).  This issue only affected Timer.schedule(TimerTask, Date, long) and Timer.scheduleAtFixedRate(TimerTask, Date, long).  It didn't handle the Date parameter properly.  You can work around this in the mean time by using Timer.schedule(TimerTask, long, long) or Timer.scheduleAtFixedRate(TimerTask, long, long) instead.
