### ISSUE TITLE
New Build HINT for iOS - generate AppStoreInfo.plist 

### ISSUE THREAD

**Issue by fjosores** [codenameone/CodenameOne#3597]
I think you should add a new BUILD HINT for iOS that should add AppStoreInfo.plist to the files generated when building on CN1 servers. It's needed only when performing a RELEASE iOS Build.

From my research, **with iTMSTransporter tool you're able to upload to Apple App Store from Windows/Linux.**

```
iTMSTransporter.cmd -assetfile myApp.ipa -u appDevUser -m upload
```
And the error I receive is:

>Unable to generate a software package on Windows. Export an AppStoreInfo.plist from Xcode, and use the -assetDescription option.

If i'm not mistaken, that AppStoreInfo.plist file is all I need to be able to upload from WINDOWS to App Connect.

Check

https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#apdAe41970bd

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/public/Transporter__Windows/bin

**Comment by shai-almog** [comment]
This should be for all iOS builds now (at least release builds).

**Comment by shai-almog** [comment]
This requires an additional fix in the client application side.

**Comment by fjosores** [comment]
I've successfully uploaded my IPA from Windows.

- Built with CN1 in RELEASE IOS. (I downloaded both my IPA and AppStoreInfo.plist
- Using appleid.apple.com I generated an app-password (https://support.apple.com/en-us/HT204397) (be sure to store pwd somewhere, because once you close the popup you cannot see it again)
- Executed iTmsTransporter

iTMSTransporter.cmd -m upload -o mylogFile.log  -u {apple-dev-user} 
  -p {app-password generated} -v eXtreme -assetFile {myApp.ipa} -assetDescription AppStoreInfo.plist

After it finishes, you need to LOGOUT from https://appstoreconnect.apple.com/ and login again. You'll see there are compiled packages uloaded, which you can add to your app's new version.

**Comment by ddyer0** [comment]
I'm not quite there - where does the appstoreinfo.plist come from?   Having most of this running, I get this error:
> ERROR: The '-assetDescription' option must specify an existing file.

**Comment by ddyer0** [comment]
nevermind, i figured it out.  the plist file is another dowdload with the ipa and the sources.
