### ISSUE TITLE
Icon in Launch screen is not updating in your build server project.

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3598]
the icon.png used by you in the Launch Screen Storyboards is not updating with the last icon update in my cn1 project.

I did what you suggest in this post.
![image](https://user-images.githubusercontent.com/16245755/171276107-8e9218dd-8fa2-497b-996c-94848c1ebd7a.png)

https://www.codenameone.com/blog/version-4-1-launch-screen-storyboards.html
 but this icon does not update to the current icon in the cn1 project.

**Comment by DurankGts** [comment]
When I open my app I could check the last icon that I update but no the current of the app.

**Comment by shannah** [comment]
iOS often caches things like launch images.  You may need to restart the device before you can see the changes.

**Comment by DurankGts** [comment]
this not normal to the user. this means that in every update the user must restar your device?

**Comment by DurankGts** [comment]
the problem was solver after restart. thank you...
