### ISSUE TITLE
RFP: Make it easy to support launching a new Form from a command in a Dialog

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3600]
See the discussion here: https://stackoverflow.com/questions/72500808/form-shown-via-a-command-in-a-dialog-doesnt-show-correctly. 

Given that it is common use case to launch another form from a command in a dialog, it could make sense to make this easier for developers. It was also really tricky to debug and it is difficult to know if you're making a mistake yourself, or whether it's a platform issue, so potentially a lot of time can be wasted.

**Comment by shai-almog** [comment]
Making this easier is problematic. There are already several workarounds embedded for that but they never solved all the edge cases. 

Making all commands use call serially by default is problematic too as it slows down the system and causes other problems. We did this for menus by default but it's impossible to make it generic.
