### ISSUE TITLE
Wav playback doesn't make a sound in the simulator

### ISSUE THREAD

**Issue by shai-almog** [codenameone/CodenameOne#3616]
See test case: https://github.com/shai-almog/testwav

**Comment by shannah** [comment]
There were two problems with this sample.  Fixing both of these problems resulted in the wav file playing as expected in my test.

Problem 1:  The sound is never played.  [Link](https://github.com/shai-almog/testwav/blob/main/common/src/main/java/com/codenameone/testwav/TestWav.java#L46-L47)

~~~~
InputStream is = Display.getInstance().getResourceAsStream(getClass(), "/" + fileName);
                m = MediaManager.createMedia(is, "audio/wav");
~~~~

Need to add `m.play();` after loading the stream.

Problem 2: The name of the Wav file is incorrect. [Link](https://github.com/shai-almog/testwav/blob/main/common/src/main/java/com/codenameone/testwav/TestWav.java#L33)

~~~~
new RegularSound("playwav.wav");
~~~~

Should be 

~~~~
new RegularSound("mywav.wav");
~~~~
