### ISSUE TITLE
Add dark mode support in Maven plugin

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3623]
Currently the maven plugin doesn't compile  dark mode CSS files as described in this blog post. https://www.codenameone.com/blog/dark-mode.html

We need to add support for this, so that dark-theme.css will be compiled to dark-theme.res when using the Maven plugin.

Also see this SO thread with a request for this feature.

https://stackoverflow.com/questions/73522377/how-to-switch-between-cn1-css-theme-with-maven

**Comment by MoKamal** [comment]
Hi @shannah, thank you for looking into this, please correct me if I misunderstood the aim of this issue, which is to update Maven plugin to compile any number of .css files to .res files found under the common/src/main/css folder by default or specified in the Maven plugin config?? 
For example on my APP, and inaddition to the Default and Dark themes, I would like to be able to add more themes for the user to select from !,

**Comment by shannah** [comment]
I've added support for dark themes in github.  It will be part of the next update on Maven central 7.0.82 (should be up within a few days).  Alternatively build from source, and use "8.0-SNAPSHOT"

You'll need to update your cn1.plugin.version to 7.0.82 in your pom.xml file.

This change will also support other CSS files whose names conform to *-theme.css.  E.g. `red-theme.css`, `blue-theme.css`, etc...  However CSS live update only works for `dark-theme.css` and `theme.css`.  For other themes, you'll need to restart simulator to see the changes.

**Comment by MoKamal** [comment]
@shannah , many thanks for the speedy support on this, just had a go and worked as expected with dark-theme, I will create additional themes while following the naming patterns above and keep you posted,
