### ISSUE TITLE
Building to android using maven project don't uploading to build server

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3629]
I have migrated my ant project to maven with very difficults but a made it.

Now when I select config android in netbeans 15 with jdk 8, the compilation doesn't upload to your build server. my question is witch config i'ts necessary android or Android App?

other question
Why if I just want to compile to specific platform the simulator run first an next when I close the simulator then go to compile to specific platform?

**Comment by DurankGts** [comment]
now when I compile using Android App config the compilation upload to your build server. yesterday doesn't work. 
 My question now is why the compilation run in Debug mode in your build server if my built hint is in false?

![image](https://user-images.githubusercontent.com/16245755/190429787-b788b9b4-d22a-45e7-bf15-44479452acd5.png)
![image](https://user-images.githubusercontent.com/16245755/190429995-5ba2b3e3-3abf-47c3-80f0-798d53a8bb66.png)

**Comment by DurankGts** [comment]
how can I solve this issue if my properties up it'ok. When I compile the same project from old ant project the final apk or aar is in release but when I compile withe the maven project is compile in debug. why?

**Comment by DurankGts** [comment]
I was checking your generate source code and I found in your buid.gradle file this. the password of the ceritificate is lossing in the buid server.

![image](https://user-images.githubusercontent.com/16245755/190502319-1e1734d3-2e7c-4ffb-8e9c-763716c4a1fd.png)

**Comment by DurankGts** [comment]
I found the problem. Your maven project doesn't recognize the relative path to the project: cert\\ios\\p12\\xxxxxxxx I set the adsolute path and the build server it compile in release. You must to fix this issue

**Comment by DurankGts** [comment]
this problem it continue now althoght I using the absolute path in the codenameone_settings.propoerties

yesterday it was working perfectly but today it's failing.

![image](https://user-images.githubusercontent.com/16245755/190661488-93569b1c-2f6d-45b0-b440-3cf638e9215d.png)
Every time that I compile to android this message is showed like your settings don't detect the path of my locals certificates

**Comment by DurankGts** [comment]
witch jdk version do you recommend to use in the netbeans 15?

**Comment by DurankGts** [comment]
actually I'm using jdk 1.8.192

**Comment by shai-almog** [comment]
We recommend JDK 11. Make sure that the JDK (not the JRE) is first in the system path. Then relaunch the IDE. Make sure the JRE isn't in that path.

**Comment by shannah** [comment]
I just created a sample app from scratch using start.codenameone.com.  Used Codename One Settings to specify the keystore for Android.  Then sent a build, and it seemed to work OK.

![image](https://user-images.githubusercontent.com/2677562/190868357-9197b30e-9886-423d-8260-b4fb8c520403.png)

I was using IntelliJ

**Comment by shannah** [comment]
Are you still having this issue?
