### ISSUE TITLE
Changes in the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by itsmenikhill** [codenameone/CodenameOne#3634]
I was going through the CONTRIBUTING.md file and found "generated" spelled as "genenrated ".

Also, under Documenting, "The [Codename One developer guide](https://www.codenameone.com/manual/) is genenrated from [the wiki pages of this project](https://github.com/codenameone/CodenameOne/wiki/) you can just [edit the wiki directly](https://www.codenameone.com/blog/wiki-parparvm-performance-actionevent-type.html) and your changes propogate into the developers guide."

could be reframed as,

"The [Codename One developer guide](https://www.codenameone.com/manual/) is genenrated from [the wiki pages of this project](https://github.com/codenameone/CodenameOne/wiki/). You can just [edit the wiki directly](https://www.codenameone.com/blog/wiki-parparvm-performance-actionevent-type.html), and your changes will reflect in the developers guide." which I think looks a little better.

**Comment by YashPimple** [comment]
I would like to work on this issue.

**Comment by FercueNat** [comment]
Hello! I would like to help in this one :)

**Comment by shai-almog** [comment]
Fixed by https://github.com/codenameone/CodenameOne/pull/3639
