### ISSUE TITLE
Light-weight pickers send events to underlying Form on iOS

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3642]
**Describe the bug**
On iOS, when the light weight CN1 Picker is open, it seems to send the pointer events to the Form below.

**To Reproduce**
Create a Form with several Tabs and setSwipeActivated true . Open a CN1 Picker. Swipe left/right on the Picker itself and the tabs will swipe. I have only observed this issue in a Form with Tabs, but it may have other effects. 

**Expected behavior**
Only the picket itself should react to touch events. 

**Screenshots**

**Smartphone (please complete the following information):**
  - OS: iOS 16, iPhone Xr
  - Also on Simulator

**Additional context**

**Comment by shannah** [comment]
@ThomasH99 Can you share a test case I can build.  I have a suspicion that the tabs component may be a key ingredient in reproducing this.

**Comment by ThomasH99** [comment]
Thanks for looking at this Steve. 

Below's the code to reproduce. Click the Picker w the date, then swipe left inside the picker and the label "Tab 2" is shown. Expected result is that the events in the picker should not be send to the underlying form. 

```
Form hi = new Form("Picker events send to underlying Form w Tabs", BoxLayout.y());
hi.setLayout(new BorderLayout());
Tabs tabs = new Tabs();
tabs.setTabPlacement(Tabs.BOTTOM);
tabs.setSwipeActivated(true);

Container mainCont = new Container(new BoxLayout(BoxLayout.Y_AXIS));
Picker picker = new Picker();
mainCont.add(picker);
tabs.addTab("1", mainCont);
tabs.addTab("2", new Label("Tab2"));
hi.add(BorderLayout.CENTER, tabs);
hi.show();
```

**Comment by shannah** [comment]
Fixed with https://github.com/codenameone/CodenameOne/commit/39a6df57f9b64ed1bb79d730cdb898ab34e34a1e

Will be part of next update on Friday.
