### ISSUE TITLE
Android gradle build defaults are not clean

### ISSUE THREAD

**Issue by Rocketeer007** [codenameone/CodenameOne#3643]
**Describe the bug**
When running the Maven "Gradle Android Project" build, some defaults are used from the file `AndroidStudioProjectTemplate.zip`

These defaults are not very compatible with a default steup of Android Studio on a developer's PC:
* The Gradle JVM is set to "1.8 (2)" (in `.idea/gradle.xml`)
* The Android SDK home is set to "/Volumes/NVMe2TB/Users/shannah/Library/Android/sdk" (in `local.properties`)

**To Reproduce**
1. Create a new template project
2. Run the "Gradle Android Project" run configuration in IntelliJ
3. Open the resulting Android Project in Android Studio

**Expected behavior**
The project should open cleanly and allow the user to build it.

**Additional context**
There appears to be some code in `AndroidGradleBuilder.extract` that would attempt to set a valid `sdk.dir` in `local.properties`.  However, the only reference to this method passes `sdkPath=null`, and is in a method (`extractAAR`) which appears to be never called.

**Comment by shannah** [comment]
I have removed these files in the android studio project template now.  This will be part of the next plugin update.  You'll need to set the cn1.plugin.version to 7.0.86 when it is released next Friday.
