### ISSUE TITLE
BrowserComponent error "cleartext not permitted"

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3648]
When a browser component accidentally moves into a http: rather than https: link, a "cleartext not permitted"
error occurs.  Aside from if this should be the default behavior, there must be a way to override it and permit
http links.    Maybe also, some kind of rewrite capability that could intercept and rewrite http as https

**Comment by shannah** [comment]
Android doesn't allow clear text networking by default.  See [this thread](https://stackoverflow.com/a/57130188) for a possible workaround to this issue.
