### ISSUE TITLE
iOS project settings

### ISSUE THREAD

**Issue by soufianee** [codenameone/CodenameOne#3687]
Hi everyone,

i m. new in codenameone. I try to build an app for iOS platform. but I didn't find any documentation of the list of sitting properties I can set for iOS platform. for example I want to build for iOS 13 minimum and on any 64 device.

any idea please.

**Comment by shai-almog** [comment]
Hi,
the full list is in the developer guide: https://www.codenameone.com/developer-guide.html
This is an issue tracker, not a discussion forum. Please use https://www.reddit.com/r/cn1/ for questions/discussions.
