### ISSUE TITLE
RFE: iOS Promotional Offer Support 

### ISSUE THREAD

**Issue by renzrivero** [codenameone/CodenameOne#3696]
Thank you for the response given [here](https://stackoverflow.com/questions/76007543/implementing-auto-renewable-subscription-with-promotional-offer)

The current [Purchase API](https://www.codenameone.com/javadoc/com/codename1/payment/Purchase.html) is great and will support introductory offers, but not promotional offers. An update to support it would be great!

Thanks in advance!

**Comment by shai-almog** [comment]
This should be addressed by [this commit](https://github.com/codenameone/CodenameOne/commit/93b0419a2b1d31bd64a1e455ece2ffa63bab7837).

**Comment by renzrivero** [comment]
This is working great! We ran across general issues implementing, but [here](https://stackoverflow.com/questions/76159273/generating-a-signature-for-apple-promotional-offers) is a source that can help
