### ISSUE TITLE
Permission in your native android source code isn't adapted to android 13

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3712]
please check your code https://github.com/codenameone/CodenameOne/blob/9e85ec3f42615cd9316b66ed954bf12818f01226/Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java#L6317

**Comment by shai-almog** [comment]
@shannah has been working on this for a while. It's more complex than that line and requires a bit of re-architecture of the `FileSystemStorage` API. We hope to have this around in the near future.

**Comment by shai-almog** [comment]
This was resolved with this feature: https://www.codenameone.com/blog/codename-one-shared-files-library.html
