### ISSUE TITLE
How avoid ACCESS_MOCK_LOCATION in android side?

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3714]
```
  <uses-permission
        android:name="android.permission.ACCESS_MOCK_LOCATION"
        android:required="false" />
```

this permission is generated in your final generated source code. Could you tell me how avoid this permission in my final app?

other issue is that you are duplicating this permission in the androidManifiest.xml

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />

**Comment by shai-almog** [comment]
Use the build hint: `android.mockLocation=false`.
