### ISSUE TITLE
Unable to build because CameraKit cannot be downloaded

### ISSUE THREAD

**Issue by masartbenji** [codenameone/CodenameOne#3728]
With my team, we did, two years ago, an app based on CodeNameOne, we used Camerakit, and we pushed the builted apk to google store. Today, Google ask us to upgrade android version to 33, but when we try to build app on your server we receive an error

`Execution failed for task ':mergeReleaseResources'.
> Could not resolve all files for configuration ':releaseRuntimeClasspath'.
   > Could not download camerakit-0.13.1.aar (com.wonderkiln:camerakit:0.13.1)
      > Could not get resource 'https://jcenter.bintray.com/com/wonderkiln/camerakit/0.13.1/camerakit-0.13.1.aar'.
         > Could not GET 'https://jcenter.bintray.com/com/wonderkiln/camerakit/0.13.1/camerakit-0.13.1.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by shai-almog** [comment]
It seems the project we're based on got a bit stuck https://github.com/CameraKit/camerakit-android
See https://mvnrepository.com/artifact/com.camerakit/camerakit

I think the option is to migrate to a newer version or get a binary version of the aar and add it directly to the library then remove the build hint to include this through the maven repo. The latter is probably simpler.

**Comment by shai-almog** [comment]
Are you using the current version?
We used camera kit for the original implementation but migrated to goldeneye. I suggest deleting your applicable build hints and refreshing.

**Comment by masartbenji** [comment]
The version of camera kit defined in camerakitCodeNameOne.ver is 8

**Comment by shai-almog** [comment]
Did you try removing the android.* build hints that might be triggering the problem?
I'm assuming this is an old Ant project.

**Comment by masartbenji** [comment]
Hello,

I worked by removing the part of camerakit inside build hints, we try application on multiples devices and the camerakit still worked, so we supposed that's ok.

We developped this small app in 2020 and we just update it when Google ask a new version of Android, maybe once per year
