### ISSUE TITLE
Local Notifications Not working On Android 13 version

### ISSUE THREAD

**Issue by luisguga** [codenameone/CodenameOne#3729]
I am experiencing problems with Local notifications on Android 13 - It's not working - nothing is shown. minimized or not. 
Started on Android 13. Even calling the routine from a simple button click, does nothing.

Same app works fine on Android 8 and 12, tested by myself.

Curiously, on Android 13, navigating thru Settings / Notifications / App Notifications / my app is listed only as system app ! So, holding pressed on it it opens a form 'Application Notifications' with a switch 'Allow notifications' Disabled ...
Just bellow it a message like 'All notifications for this app are blocked'.
Is it something on Android 13 notifications policy that has changed.. that stopped local notifications from work.. 
Vibration is not working as well but I know there's an issue reported about it.

Example of code:
        private void sendLocalNotification(){
            LocalNotification ln = new LocalNotification();
            ln.setId("CPMessage");
	    ln.setAlertTitle("Wake up");
	    ln.setAlertBody("Wake up Mike, you are late to go to school.");
            ln.setBadgeNumber(1);
            long time = System.currentTimeMillis() + 500;
            try{
                Display.getInstance().scheduleLocalNotification(ln, time, LocalNotification.REPEAT_MINUTE);
		Display.getInstance().vibrate(3000);
            }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
        }

Tested on Android version 13
Google Play updated on July 1, 2023
Samsung Galaxy S21FE One UI 5.1

Android version 8 (S. Galaxy Edge S7) works fine
Android version 11 (S. Galaxy M31) works fine

**Comment by shai-almog** [comment]
Discussion: https://www.reddit.com/r/cn1/comments/15u03fm/codename_one_local_notification_doesnt_show_up_on/

**Comment by shannah** [comment]
This should be fixed https://github.com/codenameone/CodenameOne/commit/fd84cff2bd9ff950f06785d6a5054d39e95cc823
