### ISSUE TITLE
Android Play Billing Needs updating

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3730]
I finally got my release ready for SDK 33
Upon submitting, Google said the following:

 _We've  detected that one or more of the app bundles included in this release  are using the following Play Billing Library versions
- 4.0.0
These are old versions of Google Play Billing that will be deprecated soon. Upgrade to a supported version before 1 November. [Learn more.](https://developer.android.com/google/play/billing/deprecation-faq)_

[Reddit thread](https://www.reddit.com/r/cn1/comments/16352l7/android_play_billing_needs_updating/)

**Comment by shai-almog** [comment]
https://github.com/codenameone/CodenameOne/issues/3706
