### ISSUE TITLE
Please increase fragment version in android

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3745]
the google play are waring about this version of fragment
androidx.fragment:fragment:1.0.0

please increase to (1.1.0+) or other.

**Comment by shai-almog** [comment]
I don't see that we include androidx.fragment:fragment. Is it possible one of your dependencies includes it?

**Comment by shai-almog** [comment]
Maybe @shannah has a guess where this is coming from

**Comment by shannah** [comment]
Probably this is coming from the androidx.appcompat dependency which is currently set at 1.0.0 by default.
We have started migrating to gradle 8 (from 6.5) when certain features are enabled, in which case it will use version 1.6.1 of this library.

You can explicitly enable gradle 8 right now by adding the `android.useGradle8=true` build hint.

Alternatively, if your app uses Push notifications, you can also enable the newer firebase messaging libraries via the `android.newFirebaseMessaging=true` build hint, which will also have the effect of enabling gradle 8.  Which, in turn will have the effect of using version 1.6.1 of the androidx.appcompat library.
