### ISSUE TITLE
Please add a skin with iPhone Dynamic Island support

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3762]
With the release of the iPhone 15 range, the screen layout of all new iPhones uses the 'dynamic island' which is quite different from the earlier 'notch', and the simulator needs skins to test this properly. 

Ideally for both the normal screen and 'max'. I found this page which summarizes the screen sizes, size of protected areas etc: https://useyourloaf.com/blog/iphone-15-screen-sizes/

**Comment by manumafe98** [comment]
Hi! There's someone working with this one? And if not, how I can help with it! Regards

**Comment by mseeam99** [comment]
Hi there. Is anyone working on this issue? Otherwise I want to work on this one.

**Comment by shai-almog** [comment]
Sorry I missed that message @manumafe98 either one of you or @mseeam99 can grab this.

**Comment by ghostly72** [comment]
Hi there. I'm new to open-source contributions. Can I try this one?

**Comment by shai-almog** [comment]
@ghostly72 I guess you can try since we didn't hear anything from the other guys...

**Comment by ghostly72** [comment]
okay cool

**Comment by ddyer0** [comment]
also note that the iphone x skin has a visible fixed island, but does not have a corresponding safe area

**Comment by JBurchette** [comment]
Hello! I see this is from a few months back but I would love to grab this and try it out for myself. Thanks!

**Comment by shai-almog** [comment]
@JBurchette OK

**Comment by IvanoskiHarmonia** [comment]
@shai-almog is this issue still open to work on it? I would love to work on it.

**Comment by shai-almog** [comment]
@IvanoskiHarmonia OK

**Comment by IvanoskiHarmonia** [comment]
@shai-almog I just created this PR lmk what you think: https://github.com/codenameone/codenameone-skins/pull/7

**Comment by shai-almog** [comment]
Thanks!
Merged.
