### ISSUE TITLE
physical keyboard

### ISSUE THREAD

**Issue by DB107** [codenameone/CodenameOne#3774]
HI,
I'm developing an application in codename one for multiple devices (tablets, phones, etc.) some of them have a physical keyboard, for these devices I want to use only and exclusively the physical keyboard but some keys such as the 'TAB' key don't work as they should in fact in debug when I press the TAB key I realize that one of the logs is: I/InPlaceEditView: showVirtualKeyboard show=true so I imagine that it opens the virtual keyboard even if from the device options I tell it not to show it on the screen and the focus that should go to the textfield according to my code goes somewhere else entirely, what could I do to resolve this?

**Comment by shai-almog** [comment]
Context https://www.reddit.com/r/cn1/comments/18nrpzq/comment/keglljv/

For this code: https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/InPlaceEditView.java#L604

**Comment by shai-almog** [comment]
This can be worked around using:

```
Display.getInstance().setProperty("showVkb", "false");
```

Notice this only impacts Android.
