### ISSUE TITLE
Codenameone Android app crashes using BrowserComponent with a input type file multiple

### ISSUE THREAD

**Issue by Karrtojal** [codenameone/CodenameOne#3787]
**Describe the bug**
In  an android apk generated by codenameone there is an issue using a BrowserComponent. The web page loaded, only have a <input type="file" multiple name="inputFiles" id="inputFiles"> to select one or more files.
When a single file is selected, it works fine. But if more than one file is selected, the application closes abruptly. 
The same code used to generate a iOS works fine. The problem is with the android compilation.

**To Reproduce**
1. Example code:
```
public void start()
    {
        if(current != null)
        {
            current.show();
            return;
        }
        
        Form hi = new Form("", new BorderLayout());
        BrowserComponent browser = new BrowserComponent();
        String baseUrl = "https://xxxxxx.com/test.html";
        browser.setURL(baseUrl);
        hi.add(BorderLayout.CENTER, browser);
        hi.show();
    }
```

3. Compile a generate an android apk with codenameone.
4. Open the app and click on Input component. Then select more than one files you have.
5. The app crash.

Here and example, but can be test it with any simple html with a form and an <input type="file" multiple name="inputFiles" id="inputFiles">

**Screenshots**
![1 input select multiple files](https://github.com/codenameone/CodenameOne/assets/37321813/81e22f32-25a0-4605-b7f8-afb9fe5eb75f)
![2 select 2 or more files](https://github.com/codenameone/CodenameOne/assets/37321813/8c6c5cab-2d29-4ca1-89da-76c92b9fa503)

**Smartphone (please complete the following information):**
 - Device: Tested in a lot of android devices full updated.

**Comment by shannah** [comment]
This is fixed in git.  Will be included in next update on Friday.

**Comment by Karrtojal** [comment]
Thanks, I will test it the next Friday generating a new apk.

**Comment by Karrtojal** [comment]
Hello, It works fine now. Thanks for resolve the issue.
