### ISSUE TITLE
android side compiling faling in Firebase in built server

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3790]
Hi my app to day is failing... Any new built hint necessary?  yesterday I was compiling perfectly.

Transforming userClasses.jar with IdentityTransform
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain '/home/ec2-user/zulu17.40.19-ca-jdk17.0.6-linux_x64'.
file or directory '/tmp/build3054476578416695511xxx/ForceSOS/src/release/java', not found
file or directory '/tmp/build3054476578416695511xxx/ForceSOS/build/generated/aidl_source_output_dir/release/out', not found
Compiling with JDK Java compiler API.
t-1.0.0.aar because:
  Build cache is disabled
Skipping AarToClassTransform: /home/ec2-user/.gradle/caches/modules-2/files-2.1/androidx.print/print/1.0.0/7722094652c48ebe27acc94d74a55e759e4635ff/print-1.0.0.aar as it is up-to-date.
Transforming userClasses.jar with JetifyTransform
Transforming userClasses.jar with IdentityTransform
Caching disabled for task ':compileReleaseJavaWithJavac' because:
  Build cache is disabled
Task ':compileReleaseJavaWithJavac' is not up-to-date because:
  No history is available.
The input changes require a full rebuild for incremental task ':compileReleaseJavaWithJavac'.
Transforming userClasses.jar with JetifyTransform
Transforming userClasses.jar with IdentityTransform
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain '/home/ec2-user/zulu17.40.19-ca-jdk17.0.6-linux_x64'.
file or directory '/tmp/build3054476578416695511xxx/ForceSOS/src/release/java', not found
file or directory '/tmp/build3054476578416695511xxx/ForceSOS/build/generated/aidl_source_output_dir/release/out', not found
Compiling with JDK Java compiler API.
/tmp/build3054476578416695511xxx/ForceSOS/src/main/java/com/geotracksolutionsint/asistenciachn/ForceSOSStub.java:141: error: cannot find symbol/tmp/build3054476578416695511xxx/ForceSOS/src/main/java/com/geotracksolutionsint/asistenciachn/ForceSOSStub.java:141: error: cannot find symbol

**com.google.firebase.messaging.FirebaseMessaging.getInstance().getToken()com.google.firebase.messaging.FirebaseMessaging.getInstance().getToken()**

                                                             ^                                                             ^

  symbol:   method getToken()  symbol:   method getToken()

  location: class FirebaseMessaging  location: class FirebaseMessaging

Note: Some input files use or override a deprecated API.Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use unchecked or unsafe operations.Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.Note: Recompile with -Xlint:unchecked for details.

1 error1 error

> Task :compileReleaseJavaWithJavac> Task :compileReleaseJavaWithJavac FAILED FAILED

AAPT2 aapt2-8.1.0-10154469-linux Daemon #0: shutdownAAPT2 aapt2-8.1.0-10154469-linux Daemon #0: shutdown

**Comment by shai-almog** [comment]
See this: https://www.reddit.com/r/cn1/comments/1b06naw/we_will_switch_to_grdale_8_by_default_for_android/
