### ISSUE TITLE
"safe area" rectangle is unstable, and incorrect, for iphones

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3793]
AFAIK the first time display.getSafeArea() is called, the rectangle is correct, whichever orientation
the phone is in.  Subsequently, each time you flip from portrait to landscape, the safe area is
modified to a different, incorrect value, where the width and height are swapped from the current
width and height that are being assigned to the new display being constructed.

safe x=117 y=0 w=1845 h=897
safe x=0 y=117 w=960 h=1878
safe x=117 y=0 w=1962 h=876
safe x=0 y=117 w=960 h=1878
safe x=117 y=0 w=1845 h=897

**Comment by ThomasH99** [comment]
I’ve experienced a similar issue several times, so I think there is a real bug Sent from my iPhoneOn 8 Mar 2024, at 08:43, ddyer0 ***@***.***> wrote:﻿
AFAIK the first time display.getSafeArea() is called, the rectangle is correct, whichever orientation
the phone is in.  Subsequently, each time you flip from portrait to landscape, the safe area is
modified to a different, incorrect value, where the width and height are swapped from the current
width and height that are being assigned to the new display being constructed.
safe x=117 y=0 w=1845 h=897
safe x=0 y=117 w=960 h=1878
safe x=117 y=0 w=1962 h=876
safe x=0 y=117 w=960 h=1878
safe x=117 y=0 w=1845 h=897

**Comment by shannah** [comment]
@ddyer0 In your readout there, which outputs are "incorrect"?

**Comment by ddyer0** [comment]
all of them.  tThe lines wheere x=0 correspond to holding the phone horizontally, where the notch is either lift or right.  
In general, whichever orientation the app is initially launched in, the safe area is correct, then is corrupt for all subsequent times the phone is rotated.  getDisplayWidth and getDisplayHeight are also incorrect, and incompatible with the dimensions of the form itself.

**Comment by ddyer0** [comment]
''''java
/**
 * demo program for issue 3973
 */
package com.boardspace.dtest;

import com.codename1.ui.Component;
import com.codename1.ui.Container;
// issue #3645
// 
// drawing pdfs
//
//
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.Label;
import com.codename1.ui.Toolbar;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.geom.Rectangle;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

class Test extends Component
{	Form form = null;
	@SuppressWarnings("deprecation")
	Test(Form f)
	{	form = f;
		setPreferredSize(new Dimension(2000,2000));
	}
	public void paint(Graphics gc)
	{
		int w = form.getWidth();
		int h = form.getHeight();
		gc.setColor(0xfffff0);
		gc.fillRect(0,0,w,h);
		Display dis = Display.getInstance();
		int screenw = dis.getDisplayWidth();
		int screenh = dis.getDisplayHeight();
		Rectangle rect = dis.getDisplaySafeArea(new Rectangle());
		int safex = rect.getX();
		int safey = rect.getY();
		int safew = rect.getWidth();
		int safeh = rect.getHeight();
		gc.setColor(0xff);
		gc.drawString("form "+w+" x "+h,100,100);
		gc.drawString("screen "+screenw+" x "+screenh,100,200);
		gc.drawString("safe x="+safex+" y="+safey,100,300);
		gc.drawString("     w="+safew+" h="+safeh,100,400);
		
		
	}
}
@SuppressWarnings("rawtypes")
public class Dtest{

private Form current;
@SuppressWarnings("unused")
private Resources theme;



public void init(Object context) {
    theme = UIManager.initFirstTheme("/theme");
    // Pro only feature, uncomment if you have a pro subscription
    // Log.bindCrashProtection(true);
}
public Toolbar toolbar = null;

public void start() {
    
    if(current != null){
        current.show();
    }
    Form hi = new Form();
    Container panel = new Container();
    hi.setToolbar(new Toolbar());
    toolbar = hi.getToolbar();
    Label s = new Label("this is on the toolbar");
    panel.add(s);
    toolbar.add("West",panel);
    s.setVisible(true);
    Component can = new Test(hi);
    hi.addComponent(can);
    can.setVisible(true);
    hi.show();

}
public void stop() {
    current = Display.getInstance().getCurrent();
}

public void destroy() {
}

}
''''

**Comment by ddyer0** [comment]
Also note; the skin for iphone x has a visible notch but no corresponding safe area

**Comment by shannah** [comment]
Thanks for the test case.  This is fixed in Git now.  Will be included in next week's release.

**Comment by ddyer0** [comment]
This now works approximately correctly if the phone is initially held in normal, portrait mode, but
it is incorrect if the phone is initially landscape and is flipped to vertical.

Also, the safe area makes no distinction between a phone rotated with the notch at the left 
verses rotated at the right.

Also, the safe area takes no account of the rounded corners or the bar at the bottom when in normal,
portrait mode.
![432688357_1088400102382852_7393293100341739542_n](https://github.com/codenameone/CodenameOne/assets/5963076/4848b00b-cf8d-4081-a922-c578ec8de2b1)
![432574426_935801981475581_4441966622539016824_n](https://github.com/codenameone/CodenameOne/assets/5963076/afe5d89e-712a-4b55-9e41-9bbe372c4188)
