### ISSUE TITLE
The arrow doesn't draw if you define a CSS style for the InteractionDialog

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3798]
**Describe the bug**
The arrow doesn't draw if you define a CSS style for the InteractionDialog.

Your support indicated this may be due to a regression in the CSS parser.

(tested on Simulator)

Here’s my test code: 

    Form hi = new Form("InteractionDialog", BoxLayout.y());
    TextArea textArea = new TextArea("some text");
    hi.add(textArea);
    hi.show();
    InteractionDialog id = new InteractionDialog();
    id.setTitle("TitleX");

    id.showPopupDialog(textArea);
When I run without any css styling I get this (simulator) with a white arrow:
<img width="492" alt="PastedGraphic-4" src="https://github.com/codenameone/CodenameOne/assets/16265939/838f2c65-876a-4c00-b22e-11a8673906f5">

When I add this to the css: 
PopupDialog {
    background-color: lightblue;
    border-radius: 1mm;
    margin: 0px;
    padding: 2mm;
    }

I get this without the arrow: 

<img width="487" alt="PastedGraphic-5" src="https://github.com/codenameone/CodenameOne/assets/16265939/987d37a1-93eb-45cc-aeaf-c6f581bfc6a5">

So, it seems the issue is with CN1 and not my code?

Also, if I remove the PopupDialog definition from css and save it again (so the Simulator reloads the css), it updates the color and size of the popup (and leaves space for the arrow), but does NOT add the arrow:

<img width="487" alt="PastedGraphic-6" src="https://github.com/codenameone/CodenameOne/assets/16265939/462e0708-8f70-4601-8b44-b5933481c693">

**Comment by Eric-Chomba** [comment]
I realized this too when trying to customize PopupDialog in CSS. When you
add border-radius attribute, the arrow of the Popup disappear.
You can remove border-radius in CSS for the arrow to show.

**Comment by ThomasH99** [comment]
Thanks Eric! You’re right that removing the border-radius brings the arrow back, but it seems that it leads to ignoring remaining of the CSS definition (e.g. the background-color).

**Comment by shannah** [comment]
Fixed.  Will be part of next update on friday.
