### ISSUE TITLE
IntelliJ Create Project does not see CodeName One Template

### ISSUE THREAD

**Issue by chuahyen** [codenameone/CodenameOne#3802]
<img width="803" alt="Screenshot 2024-04-08 at 20 26 53" src="https://github.com/codenameone/CodenameOne/assets/12381758/2ccc9afe-94a6-4684-bfe1-6943b41c7dfb">
<img width="900" alt="Screenshot 2024-04-08 at 20 27 13" src="https://github.com/codenameone/CodenameOne/assets/12381758/118f0d3a-738c-4478-8e7d-71498e8825fd">

Codename One Plug in has been installed into IntelliJ 2024.1 Community Edition
However, when i create a new Project, i do not see any option to create a template for CodeName One as shown in your video

please advise

regards
chris

**Comment by shai-almog** [comment]
The plugin has been deprecated in favor of Maven builds created by [the Initializr](https://start.codenameone.com/). It's only there for legacy support.

**Comment by chuahyen** [comment]
Hi
From the developer guide, I am still trying to follow it for IntelliJ but I can’t find a GuiBuilder in my IntelliJ
Did I not do something properly?

regards
Chris

￼￼
