### ISSUE TITLE
App with AdmobFullscreenAd doesn't compile anymore for android

### ISSUE THREAD

**Issue by lacsap3** [codenameone/CodenameOne#3806]
My App with AdmobFullscreenAd doesn't compile anymore for android after adding these build hints:

`android.newFirebaseMessaging=true`
`possibly android.playService.ads=22.6.0`

I use the CN1Extensions:

- Admob Fullscreen Ads (version 3)
- Codename One CodeScanner Library (version 9)
- QR code generator (version 1)
- QRScanner (version 4)

I've attached the error log:
[error_log.txt](https://github.com/codenameone/CodenameOne/files/15351210/error_log.txt)

**Comment by Eric-Chomba** [comment]
I reported a similar problem [here](https://www.reddit.com/r/cn1/comments/1dugvj8/admob_fullscreen_ads_dependancy_missing/)

Admob Fullscreen Ads Dependancy is missing in the Extensions.

Is there a temporary solution to add it to the project?

**Comment by Eric-Chomba** [comment]
I reported a similar problem [here](https://www.reddit.com/r/cn1/comments/1dugvj8/admob_fullscreen_ads_dependancy_missing/)

Admob Fullscreen Ads Dependancy is missing in the Extensions.

Is there a temporary solution to add it to the project?

**Comment by Eric-Chomba** [comment]
@lacsap3 can you successfully run this project with AdMobFullScreen in a simulator?

From your build error log, InterstitialAd class which is part of AdMobManager is missing. But if the project with AdMobFullScreen runs successfully in a simulator, it should build android app successfully.

Also note, according to [this](https://www.reddit.com/r/cn1/comments/1duhiry/codescanner_complile_errors/) you shouldn't use CodeScanner & QRScanner together.

**Comment by lacsap3** [comment]
The APP runs in the simulator without any problems.
In the past, before I updated the BuildHints, building was no problem either.
I will try adding the missing library manually.

I have both CodeScanner & QRScanner in, as one is needed for android and the other for ios.

**Comment by lacsap3** [comment]
I tried a bit more and found out that if you increase `android.playService.ads` above 19.4.0 the app crashes (e.g. at 19.6.0) and if you increase it to 22.6.0 it won't build anymore.

**Comment by Eric-Chomba** [comment]
> I tried a bit more and found out that if you increase `android.playService.ads` above 19.4.0 the app crashes (e.g. at 19.6.0) and if you increase it to 22.6.0 it won't build anymore.

Try version 19.8.0. 

Why not remove this build hint and let builder to automatically insert the version which is compatible by default?

**Comment by lacsap3** [comment]
Removing the build hint, the app crashes with:
`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent`

**Comment by Eric-Chomba** [comment]
> Removing the build hint, the app crashes with: `Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent`

You might now be experiencing [this](https://www.reddit.com/r/cn1/comments/xlclcf/comment/ipskn2u/)

Did the build hint version 19.8.0 work?

**Comment by lacsap3** [comment]
In 19.8.0 it's the same error.

Regarding the reddit solution: I'm using eclipse. In eclipse the latest CodenameOne sees to be version is 6.0.0. Is there any option to update?
