### ISSUE TITLE
Format pom.xml of the Generated Maven project

### ISSUE THREAD

**Issue by Eric-Chomba** [codenameone/CodenameOne#3807]
A Generated Maven project at [https://start.codenameone.com/](https://start.codenameone.com/) has unnecessary line breaks in pom.xml of the project's root directory MyApp/myapp/pom.xml which requires a lot of scrolling when studying the pom.xml. Can the unnecessary line breaks be removed as in common/pom.xml?

cn1.plugin.version in MyApp/myapp/pom.xml is generated as 7.0.86. can it be latest CN1 version number by default also?

**Comment by HrithikPadavala** [comment]
May I know the latest CN1 version number??

**Comment by Eric-Chomba** [comment]
> May I know the latest CN1 version number??

7.0.150

Latest version is aways release here

https://github.com/codenameone/CodenameOne

**Comment by HrithikPadavala** [comment]
Thanks, I'll work on it

**Comment by HrithikPadavala** [comment]
I have made required changes and opened a PR. Could someone please check and let me know.

**Comment by shai-almog** [comment]
@HrithikPadavala I don't see the PR. Did you submit it?
It should appear here: https://github.com/codenameone/CodenameOne/pulls

**Comment by HrithikPadavala** [comment]
I found the corresponding codebase for [](https://start.codenameone.com/) here [](https://github.com/shannah/coderad2-starter-template). Here is my PR [](https://github.com/shannah/coderad2-starter-template/pulls)

**Comment by HrithikPadavala** [comment]
I found the corresponding codebase for [https://start.codenameone.com/](url) at [https://github.com/shannah/coderad2-starter-template](url). You can see my PR here [https://github.com/shannah/coderad2-starter-template/pulls](url)

**Comment by shai-almog** [comment]
@HrithikPadavala that's a template. All the links you provided are dead.

**Comment by HrithikPadavala** [comment]
Thanks for the clarification @shai-almog . I am unable to find the corresponding pom.xml. Could you please let me know where can I find it.

**Comment by shai-almog** [comment]
@HrithikPadavala sorry, I didn't realize you're trying to fix this issue. It's probably not an issue you can fix. I'm not sure if that code is even public. Notice that it isn't marked as a "Good first issue" and is already assigned to Steve. You wouldn't find the pom.xml since that file is generated automatically by the start server.

**Comment by HrithikPadavala** [comment]
Okay. I'll try working on another issue.

**Comment by shannah** [comment]
Been banging my head on this one.  Was not able to reproduce locally, but _am_ able to reproduce on server.
Finally found what it probably is.   This bug:  https://issues.apache.org/jira/browse/ARCHETYPE-584

**Comment by Eric-Chomba** [comment]
Yes, the are neater now.
