### ISSUE TITLE
Update your apps to the latest Firebase Cloud Messaging APIs and SDKs (Attention CN1)

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3817]
are you prepare to this @shannah , @shai-athena ?

Hi xxxxxxx, 
We’re writing to remind you that starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued. This change will cause the legacy APIs to return an increased number of error responses.
The discontinued APIs will be completely shut down by July-August 2024.
What you need to do 
**If you’re still using legacy APIs to send messages with FCM, and do not expect the migration to the HTTP v1 API to be completed by June 20, 2024, please submit an extension request with [Firebase Support]**(https://notifications.google.com/g/p/ANiao5rHQiC2DgVZatRBGAEh8gwOc_EfyLN4I_kEkocgtAoNIisw0pInkgQlvRHE3Rj2T1z4F4yRxA4fh17xLjERlSFpdUBnDsTF8Hh_xiaDgBge8wrSt7IMtGz2YFeBSm-ATNpdQnxGsw5zTHphpovQaBq417pHcmk7OVnRqdeR1K3SlOl0SUjz_XyUBWmb8LE3xBWNWq_SJIrwHwzUHcluq7E) before then to avoid disruptions in your service.
We’re here to help 
We understand this change may take some planning, and we're here to support you during this transition. If you have any questions or need more information about the specific error codes and error messages, please review the [Firebase FAQs](https://notifications.google.com/g/p/ACUgQrGWmlpeanXUFO3JhOOhs6gWPl21shBf2SdeEsiZ-4WPbZ6hALRF7ua8pm42Lw7gtgqtOCuY95ixgqbL26cDbGYwHafGrKfi2h4A4NUviFZKMDSSaXYeFcX8ORwt_NljivYmeeyYmIr7Bavm5i3N8Fb2zWcNMIhcGbUBFu1ootsSoBBO6QxUZh-goVL7595B7Zy2EkOJ5oShAorlo0bcSz6b8VH9jR3cVA).
Thanks, 
- Todd on behalf of the Firebase team

**Comment by DurankGts** [comment]
this your post related with this issue??

https://www.codenameone.com/blog/android-push-changes.html

It's working now @shannah ?

**Comment by shai-almog** [comment]
Yes. This was resolved.
