### ISSUE TITLE
Keyboard keep open behaivor in android

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3821]
I notice that when I write in a TextField or TexArea that the keebord keep open all time althought I pass from Forms...Something change in your native implementation TextField or TextAre??

tested in android: 12,13,,14

**Comment by shai-almog** [comment]
@shannah There seems to be a related issue on Crisp

**Comment by DurankGts** [comment]
this issue cause a bad behaivor in some forms of my lanched app. Because the keyboard keep open in some situation. I would have to implement my native own solutions in android side.
