### ISSUE TITLE
Cannot get resources

### ISSUE THREAD

**Issue by duy1502** [codenameone/CodenameOne#3830]
![image](https://github.com/user-attachments/assets/91cb6aba-8bad-4ae5-8fcb-e918137acd7e)
![image](https://github.com/user-attachments/assets/85089a34-4dcd-4625-886d-6ba83ccbaae0)
I want to get the image from the resources folder, but when I get it, the Input Stream is all null and there is a message "resources cannont be nested in directories in Codename One! Invalid resource: : /resources/0.png"

**Comment by shai-almog** [comment]
For help questions please use https://stackoverflow.com/tags/codenameone or https://www.reddit.com/r/cn1/

We don't support resource hierarchies. Use Display.getResourceAsStream.
