### ISSUE TITLE
VKB Won't Close when stopped explicitly

### ISSUE THREAD

**Issue by shai-almog** [codenameone/CodenameOne#3835]
Test case:

```java
Form hi = new Form("Test Edit", BoxLayout.y());
TextField textField     = new TextField();
Button startEditing  = new Button("Start Editing");
startEditing.addActionListener((ev) -> textField.startEditing());
Button stopEditing   = new Button("Stop Editing");
stopEditing.addActionListener((ev) -> textField.stopEditing());

textField.getAllStyles().setFont(Font.createSystemFont(Font.FACE_SYSTEM, Font.STYLE_BOLD, Font.SIZE_LARGE));

hi.addAll(textField, startEditing, stopEditing);
hi.show();
```

**Comment by DurankGts** [comment]
this update is applied to the build server???

**Comment by DurankGts** [comment]
this no working actually... the keyboard keep open in android side

**Comment by DurankGts** [comment]
private void hideKeyBoard (){
        if (tfMessageChat != null) {
            tfMessageChat.stopEditing(new Runnable() {
                @Override
                public void run() {
                    Log.i(TAG, "hideKeyBoard()->stopped...");
                }
            });
        }
    }

**Comment by DurankGts** [comment]
this the same issue reported. I would have to implement my own hide/show keyboard to stop editing mode

https://github.com/codenameone/CodenameOne/issues/3821
