### ISSUE TITLE
CocoaPods need to be updated on server

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#3842]
Trying to build on iOS, throws the following error:

```
!] `FirebaseAnalytics` requires CocoaPods version `>= 1.12.0`, which is not satisfied by your current version, `1.11.3`.

[!] `FirebaseAnalytics` requires CocoaPods version `>= 1.12.0`, which is not satisfied by your current version, `1.11.3`.
```

The offline build succeeds with CocoaPods version 1.15.2 installed in a local Mac, which indicates that CocoaPods need to be updated on CN1 servers

**Comment by shannah** [comment]
Cocoapods has now been updated to version 1.15.2 on all iOS build servers.
