### ISSUE TITLE
iOS app with fullscreenads launches and closes immediately 

### ISSUE THREAD

**Issue by EmanueleCal** [codenameone/CodenameOne#3849]
**Describe the bug**
iOS app with fullscreen ads builds successfully using the server.
But when installed in iPhone, it launches and closes immediately. Seems the app is crashing.
I can’t get the crash log since I don’t have a Mac OS laptop.

**To Reproduce**
1. Create an application with codenameone
2. Add fullscreen ads
3. Compile for iOS
4. Try to run on an iPhone

The customer service of codenameone suggested to open a bug report.

**Comment by Eric-Chomba** [comment]
I am also experiencing this problem in iOS app. Any update?

**Comment by shannah** [comment]
It appears that you now need to add your app ID in the info.plist.  I have updated the readme instructions in the library with the following:

## iOS Build Hints

On iOS, you need to add the the following to your `ios.plistInject` build hint:

```xml
<key>GADApplicationIdentifier</key>
<string>... your Admob App ID...</string>
```

e.g.

```properties
ios.plistInject=<key>GADApplicationIdentifier</key><string>ca-app-pub-394025xxxxxxxx</string>
```

## Android Build Hints

Add the following to your `android.xapplication` build hint:

```
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="YOUR_APP_ID_HERE"/>
```

If you don't have an Admob App ID, you can create one [here](https://admob.google.com).

**Comment by Eric-Chomba** [comment]
This works now. 

However it's IMPORTANT to mention that in Java code the AdMob ID should be set with / E.g.

ca-app-pub-3940256099942544/1458002511

But when adding it to AndroidManifest and iOS plist via build hints above, the / need to be replaced with ~ Eg

ca-app-pub-3940256099942544~1458002511

Without doing this, the app will still launch & close immediately
