### ISSUE TITLE
Edtions on virtual keyboard SAMSUNG treats <enter> key as TAB key

### ISSUE THREAD

**Issue by JTBrandao** [codenameone/CodenameOne#3850]
Only on SAMSUNG devices using it´s virtual keyboard: when we tap the "<enter>" key on the virtual keyboard: there should be a line break in the text, but instead there is a loss of editing focus on the text component.

Folllows a simple code to reproduce problem:

package com.mycompany.myapp;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.TextArea;
import com.codename1.ui.layouts.BorderLayout;
/**
• This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
• of building native mobile applications using Java.
*/

public class MyApplication {
private Form current;
private Resources theme;
public void init(Object context) {
theme = UIManager.initFirstTheme("/theme");
Toolbar.setGlobalToolbar(true);
}

public void start() {
if(current != null){
current.show();
return;
}

Form hi = new Form("Samsung Test TextArea", new BorderLayout());
TextArea textArea = new TextArea();
hi.add(BorderLayout.CENTER, textArea);
hi.show();
}

public void stop() {
current = getCurrentForm();
if(current instanceof Dialog) {
((Dialog)current).dispose();
current = getCurrentForm();
}
}

public void destroy() {
}
}

A link to video showing the issue:
https://github.com/user-attachments/assets/bbb14a18-da1b-4818-a690-54e5e1d3014c

**Comment by shai-almog** [comment]
This seems to be related to this pull request: https://github.com/codenameone/CodenameOne/commit/1bf72d567fedebc8ed6169def0fa80fd75d7c328 I'll look into it.

**Comment by shai-almog** [comment]
No. The fix is in the code only. The server update is scheduled for next week (Friday) but I pushed it out now so new builds should work.
