### ISSUE TITLE
Simulator screenshot wll not capture WebBrowser component

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#562]
Original [issue 562](https://code.google.com/p/codenameone/issues/detail?id=562) created by codenameone on 2013-02-27T00:30:53.000Z:

Using CodenameOne plugin Version: 1.0.34 with Netbeans.

The simulator screenshot feature will not capture a WebBrowser component.

Sample code:

```
    Form hi = new Form(&quot;Hi World&quot;);
    BorderLayout borderLayout = new BorderLayout();
    hi.setLayout(borderLayout);

    WebBrowser webBrowser = new WebBrowser();
    webBrowser.setURL(&quot;http://www.google.com&quot;);
    hi.addComponent(BorderLayout.CENTER, webBrowser);

    hi.show();
```

The above code works and displays the web page but if I take a screenshot I get the title bar and an empty background. I am trying to get screenshots for app store submission.

**Comment by codenameone** [comment]
This can't be fixed due to the behavior of the peer component
Closing old Google code issues which are no longer relevant by now

**Comment by shannah** [comment]
Actually, my changes for z-ordering support in native components has the side effect of making native components compatible with screenshots now.  So this will be resolved

**Comment by shannah** [comment]
The WebView component will now be correctly captured in screenshots.
https://github.com/codenameone/CodenameOne/commit/25b02604989bb1decb31a8831ca52aacb9bef096
