### ISSUE TITLE
White Transparencies on iOS don't work

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#980]
Original [issue 980](https://code.google.com/p/codenameone/issues/detail?id=980) created by codenameone on 2013-12-03T23:51:36.000Z:

I have a container with bg white and Transparency 110 over a Container with bg blue and Transparency 0. And in the white Container transparency don´t work.

<b>What steps will reproduce the problem?</b>
1.Create a style &quot;jcontainer&quot; with color blue and Transparency 0
2.Create a style &quot;jcontainer_text&quot; with color FFFFFF and transparency 110
3.Add a Container on the form with BorderLayout and Style &quot;jcontainer&quot;
4.Add a Container on the previous Container with contrains BorderLayout.SOUTH and Style &quot;jcontainer_text&quot;

What is the expected output? 

A container white with Transparency 110 over a blue container

What do you see instead?

A container white with no Transparency over a blue container

What version of the product are you using?

NB plugin 1.0.60 

On what operating system?

Windows 7

<b>Please provide any additional information below.</b>

Here are two screenshots of my app running on iOs 6 and running on android 4.4

**Comment by shannah** [comment]
I believe this is a duplicate of https://github.com/codenameone/CodenameOne/issues/1419
Which is fixed.
